<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>CargoWise.RefDbRepo.CarrierMessagingBuss.RefDataProducer.Test</RootNamespace>
		<AssemblyName>CargoWise.RefDbRepo.CarrierMessagingBuss.RefDataProducer.Test</AssemblyName>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
	</ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\RefDataProducer\RefDataProducer.csproj" />
		<ProjectReference Include="..\Shared.Test\Shared.Test.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>
	<Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
