<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Tools.Common.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Tools.Common.Test</AssemblyName>
    <OutputPath>..\..\Bin\Tools\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\Bin\Tools\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\Bin\Tools\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.DbUpgrade">
      <HintPath>..\..\Bin\Tools\net8.0\CargoWise.RefDbRepo.Common.DbUpgrade.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Tools.Common">
      <HintPath>..\..\Bin\Tools\net8.0\CargoWise.RefDbRepo.Tools.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>