<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.Common.GUI</AssemblyName>
    <RootNamespace>Enterprise.Customs.Common.GUI</RootNamespace>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>