<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <EnableWinzorTests>true</EnableWinzorTests>
    <RootNamespace>Enterprise.ZArchitecture.GUI.BrowserInterop.Tests</RootNamespace>
    <AssemblyName>Enterprise.ZArchitecture.GUI.BrowserInterop.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ClientLink\ClientLinkWindowLauncherTest.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.ZArchitecture.GUI.BrowserInterop\Enterprise.ZArchitecture.GUI.BrowserInterop.Winzor.csproj" />
    <ProjectReference Include="..\Enterprise.ZArchitecture.GUI.Test\Enterprise.ZArchitecture.GUI.Test.Winzor.csproj" />
  </ItemGroup>
</Project>