<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <AssemblyName>Enterprise.Customs.CN.GUI</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="JobDeclaration\EntryInstructionUserControl\EntryInstructionDetailsUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="JobDeclaration\EntryInstructionUserControl\TwoStageAccessApplicationUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>