<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.cargowise.com/Schemas/OCM/BookingRequest/1"
  targetNamespace="http://www.cargowise.com/Schemas/OCM/BookingRequest/1"
  elementFormDefault="qualified" version="1.0">
  <xs:element name="BookingRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="MessageContext">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SenderID">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="36"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="RecipientID">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="36"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="MessageDateTime">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="20"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="MessageNumber">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="35"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ServiceType" type="ServiceType"/>
              <xs:element name="RequestType" type="RequestType"> </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="BookingDateTime" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" ref="Contact"/>
        <xs:element name="MovementType" minOccurs="0" type="MovementType"/>
        <xs:element name="CargoMode" minOccurs="0" type="CargoMode"/>
        <xs:element minOccurs="0" name="ReferenceNumberCollection">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="ReferenceNumber" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="ReferenceNumberType"/>
                    <xs:element minOccurs="0" name="Value" type="StringMaxLength35"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="RemarkCollection">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element maxOccurs="unbounded" minOccurs="0" name="Remark">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="RemarkType"/>
                    <xs:element minOccurs="0" name="Value" type="StringMaxLength512"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="CustomsFilingInstruction">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element minOccurs="0" ref="Country"/>
              <xs:element minOccurs="0" name="FilingParty" type="FillingPartyType"/>
              <xs:element minOccurs="0" name="FilingPartyCode">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="4"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="NatureOfCargo" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="TemperatureControlled" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Hazardous" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="MarinePollutant" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="OutofGauge" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="LocationCollection" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="Location" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="LocationType"/>
                    <xs:element name="UNLOCode" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="5"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Name" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="35"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element minOccurs="0" ref="Country"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="DateTimeCollection">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element minOccurs="0" name="DateTime" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="DateTimeType"/>
                    <xs:element minOccurs="0" name="Value" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="OrganizationAddressCollection" maxOccurs="1" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="OrganizationAddress" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="PartyType"/>
                    <xs:element minOccurs="0" name="OrganizationCode">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="12"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Name" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="100"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="StreetAddress1" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="50"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="StreetAddress2" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="50"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="City" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Postcode" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="10"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="State" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element minOccurs="0" ref="Country"/>
                    <xs:element minOccurs="0" ref="Contact"/>
                    <xs:element minOccurs="0" name="ReferenceNumberCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="ReferenceNumber" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="Type" type="PartyReferenceNumberType"/>
                                <xs:element minOccurs="0" name="Value" type="StringMaxLength70"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="PaymentTermCollection" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="PaymentTerm" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="Type" minOccurs="0" type="PartyChargeType"/>
                    <xs:element name="Method" minOccurs="0" type="PartyChargeMethod"/>
                    <xs:element minOccurs="0" name="ResponsiblePartyType" type="xs:string"/>
                    <xs:element name="Location" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Type" type="PartyChargeLocationType"/>
                          <xs:element name="UNLOCode" minOccurs="0">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="5"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="Name" minOccurs="0">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:maxLength value="35"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element minOccurs="0" ref="Country"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="TransportLegCollection" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="TransportLeg" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="Type" type="TransportLegType"/>
                    <xs:element minOccurs="0" name="Mode" type="TransportLegMode"/>
                    <xs:element name="LegOrder" minOccurs="0" type="xs:byte"/>
                    <xs:element name="VesselName" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="35"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="VoyageNumber" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="10"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="LloydsNumber" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="7"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="CarrierCode" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="4"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="LocationCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="Location" maxOccurs="2" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="TransportLocationType"/>
                                <xs:element name="UNLOCode" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="5"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="Name" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="35"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element minOccurs="0" ref="Country"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="DateTimeCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="DateTime" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="ETAETD_DateTimeType"/>
                                <xs:element minOccurs="0" name="Value" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="EquipmentCollection" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="Equipment" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element minOccurs="0" name="EquipmentNumber">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Type" type="EquipmentNumberType"/>
                          <xs:element minOccurs="0" name="Value" type="StringMaxLength20"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="EquipmentType" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="StringMaxLength4">
                            <xs:attribute name="Description" type="StringMaxLength35"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="EquipmentOwner" minOccurs="0" type="EquipmentSupplierType"/>
                    <xs:element name="EquipmentShippedStatus" minOccurs="0"
                      type="EquipmentStatusType"/>
                    <xs:element name="EquipmentCount" minOccurs="0" type="xs:int"/>
                    <xs:element minOccurs="0" name="HaulageArrangement">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="StringMaxLength2">
                            <xs:attribute name="Description" type="HaulageArrangementDesc"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="1" minOccurs="0" name="MeasurementCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Measurement" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type"
                                  type="EquipmentMeasurementType"/>
                                <xs:element minOccurs="0" name="Unit">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="EquipmentMeasurementUOMType">
                                        <xs:attribute name="Description" type="xs:string"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element minOccurs="0" name="Value" type="xs:decimal"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="Temperature" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Unit" type="TemperatureUOMType"/>
                          <xs:element minOccurs="0" name="Value" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="SpecialHandlingCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="SpecialHandling" maxOccurs="9" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type"
                                  type="EquipmentSpecialHandlingType"/>
                                <xs:element minOccurs="0" name="Value" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="SealNumberCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="SealNumber" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="EquipmentSealNumberType"/>
                                <xs:element minOccurs="0" name="Value" type="StringMaxLength20 "/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="1" minOccurs="0" ref="Dimensions"/>
                    <xs:element minOccurs="0" name="RemarkCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element maxOccurs="unbounded" minOccurs="0" name="Remark">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="EquipmentRemarkType"/>
                                <xs:element minOccurs="0" name="Value" type="StringMaxLength512"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="ReferenceNumberCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="ReferenceNumber" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="EquipmentReferenceNumberType"/>
                                <xs:element minOccurs="0" name="Value" type="StringMaxLength35"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="OrganizationAddressCollection" maxOccurs="1" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="OrganizationAddress" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="EquipmentPartyType"/>
                                <xs:element minOccurs="0" name="OrganizationCode">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="12"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="Name" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="100"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="StreetAddress1" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="50"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="StreetAddress2" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="50"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="City" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="25"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="Postcode" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="10"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="State" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="25"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element minOccurs="0" ref="Country"/>
                                <xs:element minOccurs="0" ref="Contact"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="DateTimeCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="DateTime" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="EquipmentDateTimeType"/>
                                <xs:element minOccurs="0" name="Value" type="xs:string"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="GoodsLineCollection" minOccurs="0">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="GoodsLine" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="LineNumber" minOccurs="0" type="xs:short"/>
                    <xs:element name="NumberOfPackages" minOccurs="0" type="xs:int"/>
                    <xs:element name="PackageType" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="StringMaxLength3">
                            <xs:attribute name="Description" type="StringMaxLength50"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="1" minOccurs="0" name="MeasurementCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element maxOccurs="unbounded" minOccurs="0" name="Measurement">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="MeasurementType"/>
                                <xs:element minOccurs="0" name="Unit">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="MeasurementUOMType">
                                        <xs:attribute name="Description" type="xs:string"/>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element minOccurs="0" name="Value" type="xs:decimal"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ClassificationCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Classification" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="ClassificationType"/>
                                <xs:element minOccurs="0" ref="Country"/>
                                <xs:element minOccurs="0" name="Code" type="StringMaxLength15"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="GoodsDescription" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="2147483647"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="MarksAndNumbers" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="2147483647"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element name="Temperature" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" name="Unit">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="TemperatureUOMType">
                                  <xs:attribute name="Description" type="xs:string"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="Value" type="xs:decimal"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" ref="Dimensions"/>
                    <xs:element name="GoodsPlacementCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="GoodsPlacement" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element name="EquipmentNumber" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="StringMaxLength20">
                                      <xs:maxLength value="20"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="NumberOfPackages" minOccurs="0" type="xs:int"/>
                                <xs:element maxOccurs="1" minOccurs="0" name="MeasurementCollection">
                                  <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                      <xs:element maxOccurs="unbounded" minOccurs="0"
                                        name="Measurement">
                                        <xs:complexType>
                                          <xs:sequence minOccurs="0">
                                            <xs:element minOccurs="0" name="Type"
                                              type="MeasurementType"/>
                                            <xs:element minOccurs="0" name="Unit">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="MeasurementUOMType">
                                                  <xs:attribute name="Description" type="xs:string"
                                                  />
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element minOccurs="0" name="Value" type="xs:decimal"
                                            />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="HazardousGoodsItemCollection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="HazardousGoodsItem" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element name="IMOCode" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="4"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="PageNumber" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="5"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="UNDGNumber" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="5"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="PackingGroupCode" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:enumeration value="1"/>
                                      <xs:enumeration value="2"/>
                                      <xs:enumeration value="3"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element minOccurs="0" name="FlashPoint">
                                  <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                      <xs:element minOccurs="0" name="Unit">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="TemperatureUOMType">
                                              <xs:attribute name="Description" type="xs:string"/>
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element minOccurs="0" name="Value" type="xs:decimal"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="ProperShippingName" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="100"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="TechnicalName" minOccurs="0">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:maxLength value="100"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                                <xs:element name="MarinePollutantClassification" minOccurs="0"
                                  type="MarinePollutantStatusType"/>
                                <xs:element name="EmergencyContact" minOccurs="0">
                                  <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                      <xs:element name="Name" minOccurs="0">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:maxLength value="50"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="Phone" minOccurs="0">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:maxLength value="20"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="Email" minOccurs="0">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:maxLength value="60"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                      <xs:element name="Fax" minOccurs="0">
                                        <xs:simpleType>
                                          <xs:restriction base="xs:string">
                                            <xs:maxLength value="20"/>
                                          </xs:restriction>
                                        </xs:simpleType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element maxOccurs="1" minOccurs="0" name="MeasurementCollection">
                                  <xs:complexType>
                                    <xs:sequence minOccurs="0">
                                      <xs:element maxOccurs="unbounded" minOccurs="0"
                                        name="Measurement">
                                        <xs:complexType>
                                          <xs:sequence minOccurs="0">
                                            <xs:element minOccurs="0" name="Type"
                                              type="MeasurementType"/>
                                            <xs:element minOccurs="0" name="Unit">
                                              <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="MeasurementUOMType">
                                                  <xs:attribute name="Description" type="xs:string"
                                                  />
                                                  </xs:extension>
                                                </xs:simpleContent>
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element minOccurs="0" name="Value" type="xs:decimal"
                                            />
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="ReferenceNumberCollection">
                      <xs:complexType>
                        <xs:sequence minOccurs="0">
                          <xs:element name="ReferenceNumber" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence minOccurs="0">
                                <xs:element minOccurs="0" name="Type" type="CargoReferenceNumberType"/>
                                <xs:element minOccurs="0" name="Value" type="StringMaxLength35"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Contact">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element name="Name" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="50"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Phone" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Email" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="60"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Fax" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Dimensions">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element minOccurs="0" name="Unit">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="DimensionUOMType">
                <xs:attribute name="Description" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Length" minOccurs="0" type="xs:decimal"/>
        <xs:element name="Width" minOccurs="0" type="xs:decimal"/>
        <xs:element name="Height" minOccurs="0" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Country">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="StringMaxLength2">
          <xs:attribute name="Name" type="StringMaxLength35"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="Location">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element minOccurs="0" name="Type" type="PartyChargeLocationType"/>
        <xs:element name="Code" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="5"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Name" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="35"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element minOccurs="0" ref="Country"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="HaulageArrangementDesc">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Carrier haulage at export, Carrier haulage at import"/>
      <xs:enumeration value="Carrier haulage at export, Merchant haulage at import"/>
      <xs:enumeration value="Merchant haulage at export, Carrier haulage at import"/>
      <xs:enumeration value="Merchant haulage at export, Merchant haulage at import"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FillingPartyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Self"/>
      <xs:enumeration value="Carrier"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MessageType">
    <xs:annotation>
      <xs:documentation>BookingRequest</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="BookingRequest"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ServiceType">
    <xs:annotation>
      <xs:documentation>VOCC, NVOCC</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="VOCC"/>
      <xs:enumeration value="NVOCC"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RequestType">
    <xs:annotation>
      <xs:documentation>N-New, U-Update, C-Cancellation</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="New"/>
      <xs:enumeration value="Update"/>
      <xs:enumeration value="Cancel"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MovementType">
    <xs:annotation>
      <xs:documentation>Port-Port, Port-Door, Door-Port, Door-Door</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Port-Port"/>
      <xs:enumeration value="Port-Door"/>
      <xs:enumeration value="Door-Port"/>
      <xs:enumeration value="Door-Door"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CargoMode">
    <xs:annotation>
      <xs:documentation>FCL, LCL</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="FCL"/>
      <xs:enumeration value="LCL"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ReferenceNumberType">
    <xs:annotation>
      <xs:documentation>MessageReference, BookingNumber, BillOfLadingNumber, ForwarderReference, ShipperReference, ContractNumber</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="MessageReference"/>
      <xs:enumeration value="BookingNumber"/>
      <xs:enumeration value="BillOfLadingNumber"/>
      <xs:enumeration value="ForwarderReference"/>
      <xs:enumeration value="ShipperReference"/>
      <xs:enumeration value="ContractNumber"/>
      <xs:enumeration value="ContractNamedAccount"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RemarkType">
    <xs:annotation>
      <xs:documentation>GoodsHandlingInstruction, SpecialInstruction, ReasonForAmendment, ReasonForCancellation</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="GoodsHandlingInstruction"/>
      <xs:enumeration value="SpecialInstruction"/>
      <xs:enumeration value="ReasonForAmendment"/>
      <xs:enumeration value="ReasonForCancellation"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PartyType">
    <xs:annotation>
      <xs:documentation>BookingParty, Carrier, Forwarder, Consignor, Consignee, MainNotifyParty, SecondNotifyParty, ThirdNotifyParty, ContractParty, FreightPayer, PickupFrom(NVOCC), DeliverTo(NVOCC)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="BookingParty"/>
      <xs:enumeration value="Carrier"/>
      <xs:enumeration value="Forwarder"/>
      <xs:enumeration value="Consignor"/>
      <xs:enumeration value="Consignee"/>
      <xs:enumeration value="MainNotifyParty"/>
      <xs:enumeration value="SecondNotifyParty"/>
      <xs:enumeration value="ThirdNotifyParty"/>
      <xs:enumeration value="ContractParty"/>
      <xs:enumeration value="FreightPayer"/>
      <xs:enumeration value="PickupFrom"/>
      <xs:enumeration value="DeliverTo"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PartyChargeType">
    <xs:annotation>
      <xs:documentation>OceanFreight, DestinationHaulage, DestinationTerminalHandling, OriginHaulage, OriginTerminalHandling</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="OceanFreight"/>
      <xs:enumeration value="DestinationHaulage"/>
      <xs:enumeration value="DestinationTerminalHandling"/>
      <xs:enumeration value="OriginHaulage"/>
      <xs:enumeration value="OriginTerminalHandling"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PartyChargeMethod">
    <xs:annotation>
      <xs:documentation>Collect, PrePaid, ElseWhere</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Collect"/>
      <xs:enumeration value="PrePaid"/>
      <xs:enumeration value="ElseWhere"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PartyChargeLocationType">
    <xs:annotation>
      <xs:documentation>PaymentLocation</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PaymentLocation"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PartyReferenceNumberType">
    <xs:annotation>
      <xs:documentation>GovernmentTaxID</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="GovernmentTaxID"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportLocationType">
    <xs:annotation>
      <xs:documentation>PortOfLoading, PortOfDischarge</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PortOfLoading"/>
      <xs:enumeration value="PortOfDischarge"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ETAETD_DateTimeType">
    <xs:annotation>
      <xs:documentation>EstimatedDeparture, EstimatedArrival</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="EstimatedDeparture"/>
      <xs:enumeration value="EstimatedArrival"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DateTimeType">
    <xs:annotation>
      <xs:documentation>EarliestDeparture, LatestDelivery, EstimatedPickupFrom, EstimatedDeliverTo</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="EarliestDeparture"/>
      <xs:enumeration value="LatestDelivery"/>
      <xs:enumeration value="EstimatedPickupFrom"/>
      <xs:enumeration value="EstimatedDeliverTo"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportLegMode">
    <xs:annotation>
      <xs:documentation>Sea, Road, Rail</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Sea"/>
      <xs:enumeration value="Road"/>
      <xs:enumeration value="Rail"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TransportLegType">
    <xs:annotation>
      <xs:documentation>Main, PreCarriage, OnForwarding</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Main"/>
      <xs:enumeration value="PreCarriage"/>
      <xs:enumeration value="OnForwarding"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="LocationType">
    <xs:annotation>
      <xs:documentation>PlaceOfReceipt, PlaceOfDelivery, CarrierBookingOffice</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PlaceOfReceipt"/>
      <xs:enumeration value="PlaceOfDelivery"/>
      <xs:enumeration value="CarrierBookingOffice"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MeasurementType">
    <xs:annotation>
      <xs:documentation>GoodsWeight, GoodsVolume</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="GoodsWeight"/>
      <xs:enumeration value="GoodsVolume"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MeasurementUOMType">
    <xs:annotation>
      <xs:documentation>GoodsWeight(KG/LB), GoodsVolume(M3/CF)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="KG"/>
      <xs:enumeration value="LB"/>
      <xs:enumeration value="CF"/>
      <xs:enumeration value="M3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CargoReferenceNumberType">
    <xs:annotation>
      <xs:documentation>OrderNumber, VIN, SKU, ITN</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="OrderNumber"/>
      <xs:enumeration value="VIN"/>
      <xs:enumeration value="SKU"/>
      <xs:enumeration value="ITN"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DimensionUOMType">
    <xs:annotation>
      <xs:documentation>IN or CM</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="IN"/>
      <xs:enumeration value="CM"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TemperatureUOMType">
    <xs:annotation>
      <xs:documentation>CEL, FAH</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="CEL"/>
      <xs:enumeration value="FAH"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ClassificationType">
    <xs:annotation>
      <xs:documentation>HS, NCM</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="HS"/>
      <xs:enumeration value="NCM"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentDateTimeType">
    <xs:annotation>
      <xs:documentation>EmptyPositionAtDoor, EstimatedFullPickup, RequestedEmptyPickup, PositionAtIntermediateStop, PickupFromIntermediateStop, RequestedFullDelivery</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="EmptyPositionAtDoor"/>
      <xs:enumeration value="EstimatedFullPickup"/>
      <xs:enumeration value="RequestedEmptyPickup"/>
      <xs:enumeration value="PositionAtIntermediateStop"/>
      <xs:enumeration value="PickupFromIntermediateStop"/>
      <xs:enumeration value="RequestedFullDelivery"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentReferenceNumberType">
    <xs:annotation>
      <xs:documentation>ReleaseNumber</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="ReleaseNumber"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentRemarkType">
    <xs:annotation>
      <xs:documentation>EquipmentRemarks</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="EquipmentRemarks"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentSealNumberType">
    <xs:annotation>
      <xs:documentation>Carrier, Shipper, Customs, Quarantine, Terminal</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Carrier"/>
      <xs:enumeration value="Shipper"/>
      <xs:enumeration value="Customs"/>
      <xs:enumeration value="Quarantine"/>
      <xs:enumeration value="Terminal"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentSpecialHandlingType">
    <xs:annotation>
      <xs:documentation>NonOperativeReefer, VentSetting</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="NonOperativeReefer"/>
      <xs:enumeration value="VentSetting"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentMeasurementType">
    <xs:annotation>
      <xs:documentation>GrossWeight, GoodsWeight, TareWeight, GrossVolume, Humidity, AirFlow</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="GrossWeight"/>
      <xs:enumeration value="GoodsWeight"/>
      <xs:enumeration value="TareWeight"/>
      <xs:enumeration value="GrossVolume"/>
      <xs:enumeration value="Humidity"/>
      <xs:enumeration value="AirFlow"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentMeasurementUOMType">
    <xs:annotation>
      <xs:documentation>GrossWeight(KG/LB), GoodsWeight(KG/LB), TareWeight(KG/LB), GrossVolume(M3/CF), Humidity(PER), AirFlow(M3)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="KG"/>
      <xs:enumeration value="LB"/>
      <xs:enumeration value="CF"/>
      <xs:enumeration value="M3"/>
      <xs:enumeration value="PER"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentStatusType">
    <xs:annotation>
      <xs:documentation>Full, Empty</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Full"/>
      <xs:enumeration value="Empty"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentSupplierType">
    <xs:annotation>
      <xs:documentation>Shipper, Carrier</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Shipper"/>
      <xs:enumeration value="Carrier"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentNumberType">
    <xs:annotation>
      <xs:documentation>Actual, Logical</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Actual"/>
      <xs:enumeration value="Logical"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EquipmentPartyType">
    <xs:annotation>
      <xs:documentation>PickupFrom, DeliverTo, EmptyPickup, IntermediateStop</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PickupFrom"/>
      <xs:enumeration value="DeliverTo"/>
      <xs:enumeration value="EmptyPickup"/>
      <xs:enumeration value="IntermediateStop"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MarinePollutantStatusType">
    <xs:annotation>
      <xs:documentation>MarinePollutant, NonMarinePollutant, SevereMarinePollutant</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="MarinePollutant"/>
      <xs:enumeration value="NonMarinePollutant"/>
      <xs:enumeration value="SevereMarinePollutant"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength15">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="15"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength2">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength3">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength35">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="35"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength4">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength20">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="20"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength50">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength512">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="512"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="StringMaxLength70">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="70"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
