<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <WarningsNotAsErrors>1030</WarningsNotAsErrors>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
	  <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Test" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Business.Test" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="MailManager.Test" />
    <Reference Include="MailManager" />
    <Reference Include="MailManager.Integration" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agency.Business.Test\Enterprise.Freight.Agency.Business.Test.csproj" />
    <ProjectReference Include="..\Agency.Business\Enterprise.Freight.Agency.Business.csproj" />
    <ProjectReference Include="..\Agency.DataTransfer.Test\Enterprise.Freight.Agency.DataTransfer.Test.csproj" />
    <ProjectReference Include="..\Agency.DataTransfer\Enterprise.Freight.Agency.DataTransfer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agency.ServiceTasks\Enterprise.Freight.Agency.ServiceTasks.csproj" />
  </ItemGroup>
</Project>