// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CartageForm.#Cartage_OnGetNonContainerisedCartageLegsToPrint(System.Object,Enterprise.Freight.LocalCartage.Business.DocumentCartageLegEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CartageForm.#SetupForm()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CartageLegRunSheetAllocationPlugin.#OnWorkSheetLegLinkAdded(System.Object,Enterprise.Freight.LocalCartage.Business.WorkSheetLegLinkEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CartageWorkSheetForm.#.ctor(Enterprise.Freight.LocalCartage.Business.CommonWorkSheet)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CommonCartageXmlExportDirector.#QueryAdditionalBookingInformation(Enterprise.Freight.LocalCartage.DataTransfer.ICartageExporter,Enterprise.Freight.LocalCartage.Business.CommonCartage,Enterprise.ZArchitecture.NotificationBuffer)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1044:PropertiesShouldNotBeWriteOnly", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.CommonCartageXmlExportDirector.#WasCanceled", Justification = "For tests.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.GPSMonitorPlugin.#AddSendToVehicleMenu(Enterprise.ZArchitecture.ZGrid)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.GPSMonitorPlugin.#CheckModifiedLegsForResend(CargoWise.EntityFramework.BusinessObjectFactory)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.LooseMovesControl.#SetUpContextMenus()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.QuickAddressHelper.#FindOrCreateMenu(System.Windows.Forms.Menu+MenuItemCollection,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.QuickAddressHelper.#ShowAddressSelectionMenu()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.RunSheetTile.#AddCartageLeg(Enterprise.Freight.LocalCartage.Business.CommonCartageLeg)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.SignatureDrawer.#PopupSignature()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#DrawFilledRectangle(System.Drawing.Graphics,System.Single,System.Single,System.Single,System.Single,System.Int32,Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile+TilesGradient,System.Drawing.Color,System.Single,System.Single,System.Single[],System.Drawing.Color[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:DisposeObjectsBeforeLosingScope", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#GetBrush(System.Drawing.Color)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#PanelColorPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#PanelColors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#TileColorPositions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#TileColorPositionsCore")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#TileColors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.Freight.LocalCartage.GUI.ZGroupBoxTile.#TileColorsCore")]
