<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Testing\Test2.resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.IO\CargoWise.IO.csproj" />
    <EmbeddedResource Include="Resources\Testing\Test2.resources" />
    <EmbeddedResource Include="Resources\Testing\Test.resources" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="CargoWise.Shared.40" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>