// ----------------------------------------------------------------------
// <auto-generated>
//      This code is auto-generated by the awesome NonPersistentBusinessObjectGenerator(tm)
//      Any changes to this file will be lost when the generator is next run.
// </auto-generated>
// ----------------------------------------------------------------------
using System;
using System.ComponentModel;
using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.Environment;

namespace Enterprise.Client.EDI.Billing.Business
{
	
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoClientLicenceFeeFlattened : NonPersistentBusinessObject, IObsoleteValidation
	{
		#region Schema
		public class Schema
		{
			public const string OrgCode = "OrgCode";
			public const int OrgCodeMaxLength = 12;
			public const string ServerCode = "ServerCode";
			public const int ServerCodeMaxLength = 3;
			public const string StartDate = "StartDate";
			public const string EndDate = "EndDate";
			public const string Amount = "Amount";
			public const int AmountPrecision = 19;
			public const int AmountScale = 4;
			public const string AmountAsText = "AmountAsText";
			public const int AmountAsTextMaxLength = 12;
			public const string ChargeCode = "ChargeCode";
			public const int ChargeCodeMaxLength = 10;
			public const string Comment = "Comment";
			public const int CommentMaxLength = 1024;
			public const string Description = "Description";
			public const int DescriptionMaxLength = 1024;
			public const string IsDiscountable = "IsDiscountable";
			public const string Order = "Order";
			public const string RenewalMonths = "RenewalMonths";
			public const string Currency = "Currency";
			public const int CurrencyMaxLength = 3;
			public const string SystemCode = "SystemCode";
			public const int SystemCodeMaxLength = 3;
			public const string FeeType = "FeeType";
			public const int FeeTypeMaxLength = 3;
			public const string TaxDate = "TaxDate";
			public const int TaxDateMaxLength = 3;
		}
		#endregion
		protected AutoClientLicenceFeeFlattened()
		{
		}
		protected AutoClientLicenceFeeFlattened(BusinessObjectFactory factory) : base(factory)
		{
		}
		#region OrgCode
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|OrgCode", Caption="Org. Code")]
		[MaxLength(Schema.OrgCodeMaxLength)]
		public virtual ZString OrgCode
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return orgCode;
			}
			set
			{
				CheckMaximumLength(OrgCodeInfo, value);
				SetNonPersistentPropertyValue(OrgCodeInfo, ref orgCode, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateOrgCode();
				}
			}
		}
		public virtual ZPropertyInfo OrgCodeInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.OrgCode);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString orgCode;
		public virtual void ValidateOrgCode()
		{
			OrgCodeInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(OrgCodeInfo);
		}
		#endregion
		#region ServerCode
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|ServerCode", Caption="Server Code")]
		[MaxLength(Schema.ServerCodeMaxLength)]
		public virtual ZString ServerCode
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return serverCode;
			}
			set
			{
				CheckMaximumLength(ServerCodeInfo, value);
				SetNonPersistentPropertyValue(ServerCodeInfo, ref serverCode, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateServerCode();
				}
			}
		}
		public virtual ZPropertyInfo ServerCodeInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.ServerCode);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString serverCode;
		public virtual void ValidateServerCode()
		{
			ServerCodeInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(ServerCodeInfo);
		}
		#endregion
		#region StartDate
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|StartDate", Caption="Start Date")]
		public virtual ZDateTime StartDate
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return startDate;
			}
			set
			{
				SetNonPersistentPropertyValue(StartDateInfo, ref startDate, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateStartDate();
				}
			}
		}
		public virtual ZPropertyInfo StartDateInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.StartDate);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZDateTime startDate;
		public virtual void ValidateStartDate()
		{
			StartDateInfo.ClearAllNotifications();
			TypeValidation.CheckValidZDateTimeAndRange(StartDateInfo);
		}
		#endregion
		#region EndDate
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|EndDate", Caption="End Date")]
		public virtual ZDateTime EndDate
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return endDate;
			}
			set
			{
				SetNonPersistentPropertyValue(EndDateInfo, ref endDate, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateEndDate();
				}
			}
		}
		public virtual ZPropertyInfo EndDateInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.EndDate);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZDateTime endDate;
		public virtual void ValidateEndDate()
		{
			EndDateInfo.ClearAllNotifications();
			TypeValidation.CheckValidZDateTimeAndRange(EndDateInfo);
		}
		#endregion
		#region Amount
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|Amount", Caption="Amount")]
		[DecimalPrecision(Schema.AmountPrecision)]
		[DecimalPlaces(Schema.AmountScale)]
		public virtual ZDecimal Amount
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return amount;
			}
			set
			{
				SetNonPersistentPropertyValue(AmountInfo, ref amount, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateAmount();
				}
			}
		}
		public virtual ZPropertyInfo AmountInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Amount);
			}
		}
		protected virtual int Amount_Precision
		{
			get
			{
				return 19;
			}
		}
		protected virtual int Amount_Scale
		{
			get
			{
				return 4;
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZDecimal amount;
		public virtual void ValidateAmount()
		{
			AmountInfo.ClearAllNotifications();
			TypeValidation.CheckValidDecimal(AmountInfo, AutoClientLicenceFeeFlattened.Schema.AmountPrecision, AutoClientLicenceFeeFlattened.Schema.AmountScale);
		}
		#endregion
		#region AmountAsText
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|AmountAsText", Caption="Amount")]
		[MaxLength(Schema.AmountAsTextMaxLength)]
		public virtual ZString AmountAsText
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return amountAsText;
			}
			set
			{
				CheckMaximumLength(AmountAsTextInfo, value);
				SetNonPersistentPropertyValue(AmountAsTextInfo, ref amountAsText, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateAmountAsText();
				}
			}
		}
		public virtual ZPropertyInfo AmountAsTextInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.AmountAsText);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString amountAsText;
		public virtual void ValidateAmountAsText()
		{
			AmountAsTextInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(AmountAsTextInfo);
		}
		#endregion
		#region ChargeCode
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|ChargeCode", Caption="Charge Code")]
		[MaxLength(Schema.ChargeCodeMaxLength)]
		public virtual ZString ChargeCode
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return chargeCode;
			}
			set
			{
				CheckMaximumLength(ChargeCodeInfo, value);
				SetNonPersistentPropertyValue(ChargeCodeInfo, ref chargeCode, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateChargeCode();
				}
			}
		}
		public virtual ZPropertyInfo ChargeCodeInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.ChargeCode);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString chargeCode;
		public virtual void ValidateChargeCode()
		{
			ChargeCodeInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(ChargeCodeInfo);
		}
		#endregion
		#region Comment
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|Comment", Caption="Comment")]
		[MaxLength(Schema.CommentMaxLength)]
		public virtual ZString Comment
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return comment;
			}
			set
			{
				CheckMaximumLength(CommentInfo, value);
				SetNonPersistentPropertyValue(CommentInfo, ref comment, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateComment();
				}
			}
		}
		public virtual ZPropertyInfo CommentInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Comment);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString comment;
		public virtual void ValidateComment()
		{
			CommentInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(CommentInfo);
		}
		#endregion
		#region Description
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|Description", Caption="Description")]
		[MaxLength(Schema.DescriptionMaxLength)]
		public virtual ZString Description
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return description;
			}
			set
			{
				CheckMaximumLength(DescriptionInfo, value);
				SetNonPersistentPropertyValue(DescriptionInfo, ref description, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateDescription();
				}
			}
		}
		public virtual ZPropertyInfo DescriptionInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Description);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString description;
		public virtual void ValidateDescription()
		{
			DescriptionInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(DescriptionInfo);
		}
		#endregion
		#region IsDiscountable
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|IsDiscountable", Caption="Is Discountable")]
		public virtual ZBool IsDiscountable
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return isDiscountable;
			}
			set
			{
				SetNonPersistentPropertyValue(IsDiscountableInfo, ref isDiscountable, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateIsDiscountable();
				}
			}
		}
		public virtual ZPropertyInfo IsDiscountableInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.IsDiscountable);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool isDiscountable;
		public virtual void ValidateIsDiscountable()
		{
			IsDiscountableInfo.ClearAllNotifications();
		}
		#endregion
		#region Order
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|Order", Caption="Order")]
		public virtual ZShort Order
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return order;
			}
			set
			{
				SetNonPersistentPropertyValue(OrderInfo, ref order, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateOrder();
				}
			}
		}
		public virtual ZPropertyInfo OrderInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Order);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZShort order;
		public virtual void ValidateOrder()
		{
			OrderInfo.ClearAllNotifications();
		}
		#endregion
		#region RenewalMonths
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|RenewalMonths", Caption="Renewal Months")]
		public virtual ZInt RenewalMonths
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return renewalMonths;
			}
			set
			{
				SetNonPersistentPropertyValue(RenewalMonthsInfo, ref renewalMonths, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateRenewalMonths();
				}
			}
		}
		public virtual ZPropertyInfo RenewalMonthsInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.RenewalMonths);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZInt renewalMonths;
		public virtual void ValidateRenewalMonths()
		{
			RenewalMonthsInfo.ClearAllNotifications();
		}
		#endregion
		#region Currency
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|Currency", Caption="Currency")]
		[MaxLength(Schema.CurrencyMaxLength)]
		public virtual ZString Currency
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return currency;
			}
			set
			{
				CheckMaximumLength(CurrencyInfo, value);
				SetNonPersistentPropertyValue(CurrencyInfo, ref currency, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateCurrency();
				}
			}
		}
		public virtual ZPropertyInfo CurrencyInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Currency);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString currency;
		public virtual void ValidateCurrency()
		{
			CurrencyInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(CurrencyInfo);
		}
		#endregion
		#region SystemCode
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|SystemCode", Caption="Bill")]
		[MaxLength(Schema.SystemCodeMaxLength)]
		public virtual ZString SystemCode
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return systemCode;
			}
			set
			{
				CheckMaximumLength(SystemCodeInfo, value);
				SetNonPersistentPropertyValue(SystemCodeInfo, ref systemCode, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateSystemCode();
				}
			}
		}
		public virtual ZPropertyInfo SystemCodeInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.SystemCode);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString systemCode;
		public virtual void ValidateSystemCode()
		{
			SystemCodeInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(SystemCodeInfo);
		}
		#endregion
		#region FeeType
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|FeeType", Caption="Type")]
		[MaxLength(Schema.FeeTypeMaxLength)]
		public virtual ZString FeeType
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return feeType;
			}
			set
			{
				CheckMaximumLength(FeeTypeInfo, value);
				SetNonPersistentPropertyValue(FeeTypeInfo, ref feeType, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateFeeType();
				}
			}
		}
		public virtual ZPropertyInfo FeeTypeInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.FeeType);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString feeType;
		public virtual void ValidateFeeType()
		{
			FeeTypeInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(FeeTypeInfo);
		}
		#endregion
		#region TaxDate
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Client.EDI.Billing.Business.ClientLicenceFeeFlattened|TaxDate", Caption="Tax Date")]
		[MaxLength(Schema.TaxDateMaxLength)]
		public virtual ZString TaxDate
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return taxDate;
			}
			set
			{
				CheckMaximumLength(TaxDateInfo, value);
				SetNonPersistentPropertyValue(TaxDateInfo, ref taxDate, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateTaxDate();
				}
			}
		}
		public virtual ZPropertyInfo TaxDateInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.TaxDate);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString taxDate;
		public virtual void ValidateTaxDate()
		{
			TaxDateInfo.ClearAllNotifications();
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(TaxDateInfo);
		}
		#endregion
		#region Validation
		protected override void RunPreSaveValidationCore()
		{
			ValidateOrgCode();
			ValidateServerCode();
			ValidateStartDate();
			ValidateEndDate();
			ValidateAmount();
			ValidateAmountAsText();
			ValidateChargeCode();
			ValidateComment();
			ValidateDescription();
			ValidateIsDiscountable();
			ValidateOrder();
			ValidateRenewalMonths();
			ValidateCurrency();
			ValidateSystemCode();
			ValidateFeeType();
			ValidateTaxDate();
			base.RunPreSaveValidationCore();
		}
		#endregion
	}
}
