<Project>
  <ItemGroup>
    <Reference Include="AppDomainWrappers.Net" />
    <Reference Include="AuthenticationService.Client" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.UniversalCopy" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.Accounting.Business" />
    <Reference Include="Enterprise.Accounting.GUI" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Business" />
    <Reference Include="Enterprise.Billing.Business.Test" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.Universal.Test" />
    <Reference Include="Enterprise.Customs.US.Business" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentScanning.Integration" />
    <Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.eTail.Business" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Agency.Business" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.CFS.Business" />
    <Reference Include="Enterprise.Freight.CFS.GUI" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.AWB.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Documents.DataObjects" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Freight.LocalCartage.Business" />
    <Reference Include="Enterprise.Freight.LocalCartage.Integration" />
    <Reference Include="Enterprise.Freight.QuotedBookings.Business" />
    <Reference Include="Enterprise.Freight.QuotedBookings.GUI" />
    <Reference Include="Enterprise.Freight.QuotedBookings.GUI.Test" />
    <Reference Include="Enterprise.Freight.Test" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.LandedCosting.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.MasterFiles.GUI" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.MasterFiles.Module.Test" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Business" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.Services.OperationalActions.Support" />
    <Reference Include="Enterprise.Services.OperationalActions.Support.Test" />
    <Reference Include="Enterprise.TransportBookings.Business" />
    <Reference Include="Enterprise.TransportBookings.GUI" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.TransportCommon.Business" />
    <Reference Include="Enterprise.TransportCommon.Business.Test" />
    <Reference Include="Enterprise.TransportCommon.Shared" />
    <Reference Include="Enterprise.TransportConsignment.Business" />
    <Reference Include="Enterprise.TransportConsignment.Integration" />
    <Reference Include="Enterprise.UniversalCopy.GUI" />
    <Reference Include="Enterprise.Warehouse.Environment.Business" />
    <Reference Include="Enterprise.Warehouse.Environment.Business.Test" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.Warehouse.Transactions.Business" />
    <Reference Include="Enterprise.Warehouse.Transactions.Business.Testing" />
    <Reference Include="Enterprise.Warehouse.Transactions.Invoicing" />
    <Reference Include="Enterprise.Warehouse.Transit.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="MailManager" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Urs.Api.Integration" />
    <Reference Include="WiseRates.Api.Client" />
    <Reference Include="WiseRates.Api.Model" />
    <Reference Include="WiseRates.Tools" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business.Test\Rating.Business.Test.csproj" />
    <ProjectReference Include="..\Business\Rating.Business.csproj" />
    <ProjectReference Include="..\Rateable\Rateable.csproj" />
    <ProjectReference Include="..\Rating.DataTransfer\Rating.DataTransfer.csproj" />
  </ItemGroup>
</Project>