<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Rating.Testing</AssemblyName>
    <RootNamespace>Enterprise.Rating.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Rating.GUI.Winzor.csproj" />
    <ProjectReference Include="..\Rating.CarrierConnect\Rating.CarrierConnect.csproj" />
    <ProjectReference Include="..\Rating.Integration.Test\Rating.Integration.Test.csproj" />
    <ProjectReference Include="..\Rating.Integration\Rating.Integration.csproj" />
    <ProjectReference Include="..\Rating.Module\Rating.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.FeatureControl.Abstractions" />
    <Reference Include="Enterprise.Rating.Business" />
    <Reference Include="Enterprise.Rating.Business.Test" />
    <Reference Include="Enterprise.Rating.Rateable" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>