using System.Collections.Generic;

namespace CargoWise.RefDbRepo.IEReferenceData.ExchangeRates.Business
{
	public static class IrishCurrencyCodes
	{
		public static IReadOnlyDictionary<string, string> CurrencyCodes
		{
			get
			{
				return new Dictionary<string, string>
				{
					{ "ALBANIA LEK", "ALL" },
					{ "ALGERIAN DINAR", "DZD" },
					{ "ANTIGUA & BARBUDA DOLLAR", "XCD" },
					{ "ARGENTINA PESO", "ARS" },
					{ "AUSTRALIAN DOLLAR", "AUD" },
					{ "AZERBAIJAN NEW MANET", "AZN" },
					{ "BAHRAIN DINAR", "BHD" },
					{ "BANGLADESH TAKA", "BDT" },
					{ "BARBADOS DOLLAR", "BBD" },
					{ "BELIZE DOLLAR", "BZD" },
					{ "BERMUDA DOLLAR", "BMD" },
					{ "BHUTAN NGULTRU", "BTN" },
					{ "BHUTAN NGULTRUM", "BTN" },
					{ "BOSNIA HERZEGOVIAEA MARKA", "BAM" },
					{ "BOTSWANA PULA", "BWP" },
					{ "BRAZIL REAL", "BRL" },
					{ "BRUNEI DOLLAR", "BND" },
					{ "BULGARIAN LEV", "BGN" },
					{ "CFA FRANC", "CDF" },
					{ "CANADIAN DOLLAR", "CAD" },
					{ "CAYMAN ISLAND DOLLAR", "KYD" },
					{ "CHILEAN PESO", "CLP" },
					{ "CHINESE RENMINBI", "CNY" },
					{ "COLOMBIAN PESO", "COP" },
					{ "COSTA RICAN COLON", "CRC" },
					{ "CROATIAN KUNA", "HRK" },
					{ "CZECH KORUNA", "CZK" },
					{ "DANISH KRONE", "DKK" },
					{ "DOMINICAN REPUBLIC PESO", "DOP" },
					{ "EGYPTIAN POUND", "EGP" },
					{ "ERITREA NAKFA", "ERN" },
					{ "ETHIOPIA BIRR", "ETB" },
					{ "FIJI DOLLAR", "FJD" },
					{ "GEORGIA LARI", "GEL" },
					{ "GHANA CEDI", "GHC" },
					{ "GIBRALTAR POUND", "GIP" },
					{ "HONG KONG DOLLAR", "HKD" },
					{ "HUNGARIAN FORINT", "HUF" },
					{ "ICELANDIC KRONA", "ISK" },
					{ "INDIAN RUPEE", "INR" },
					{ "INDONESIAN RUPIAH", "IDR" },
					{ "IRAQI DINA", "IQD" },
					{ "ISRAELI SHEKEL", "ILS" },
					{ "JAPANESE YEN", "JPY" },
					{ "JORDAN DINAR", "JOD" },
					{ "KAZAKHSTAN TENGE", "KZT" },
					{ "KENYAN SHILLING", "KES" },
					{ "KUWAITI DINAR", "KWD" },
					{ "LEBANESE POUND", "LBP" },
					{ "LIBYAN DINAR", "LYD" },
					{ "MALAWI KWACHA", "MWK" },
					{ "MALAYSIAN RINGGIT", "MYR" },
					{ "MAUR RUPEE", "MUR" },
					{ "MEXICAN PESO", "MXN" },
					{ "MOLDOVA LEU", "MDL" },
					{ "MOROCCAN DIRHAM", "MAD" },
					{ "NAMIBIA DOLLAR", "NAD" },
					{ "NEPALESE RUPEE", "NPR" },
					{ "NEW ZEALAND DOLLAR", "NZD" },
					{ "NIGERIAN NAIRA", "NGN" },
					{ "NORWEGIAN KRONE", "NOK" },
					{ "OMANI RIAL", "OMR" },
					{ "PAKISTAN RUPEE", "PKR" },
					{ "PERUVIAN NEW SOL", "PEN" },
					{ "PHILIPPINES PESO", "PHP" },
					{ "POLISH ZLOTY", "PLN" },
					{ "QATAR RIYA", "QAR" },
					{ "QATAR RIYAL", "QAR" },
					{ "ROMANIAN LEU", "RON" },
					{ "RUSSIAN ROUBLE", "RUB" },
					{ "SAINT HELENA POUND", "SHP" },
					{ "SAUDI ARABIA RIYAL", "SAR" },
					{ "SERBIA DINAR", "RSD" },
					{ "SINGAPORE DOLLAR", "SGD" },
					{ "SOLOMON ISLANDS DOLLAR", "SBD" },
					{ "SOUTH AFRICAN RAND", "ZAR" },
					{ "SOUTH KOREAN WON", "KRW" },
					{ "SRI LANKAN RUPEE", "LKR" },
					{ "STERLING", "GBP" },
					{ "SWEDISH KRON", "SEK" },
					{ "SWEDISH KRONA", "SEK" },
					{ "SWISS FRANC", "CHF" },
					{ "TAIWAN DOLLAR", "TWD" },
					{ "TANZANIAN SHILLING", "TZS" },
					{ "THAILAND BAHT", "THB" },
					{ "TRINIDAD/TOBAGO DOLLAR", "TTD" },
					{ "TUNISIAN DINAR", "TND" },
					{ "TURKISH LIRA", "TRY" },
					{ "UAE DIRHAM", "AED" },
					{ "US DOLLAR", "USD" },
					{ "UKRAINE HRYVNIA", "UAH" },
					{ "VIETNAM DONG", "VND" },
					{ "YEMEN RIAL", "YER" },
					{ "ZIMBABWE DOLLAR", "ZWL" },
					{ "IRAQI DINAR", "UQD" },
					{ "URUGUAY PESO", "UYU" },
				};
			}
		}
	}
}
