<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <EnableDataProviderGenerator>true</EnableDataProviderGenerator>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.IT.MessageContracts" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EFTA.TemporaryStorageRegister.Business" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.TemporaryStorage.Business" />
    <Reference Include="Enterprise.Customs.IT.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\CusCodeDataTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CusCodeDataTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageSubTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageSubTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PNTSCustomsStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PNTSCustomsStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PNTSMessageStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PNTSMessageStatusList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\CusCodeDataTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CusCodeDataTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\MessageSubTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageSubTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\PNTSCustomsStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PNTSCustomsStatusList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\PNTSMessageStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PNTSMessageStatusList.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>