namespace Enterprise.Customs.EU.NCTS.Business;

public sealed class CommonPreviousDocumentArrivalValidationDecider : CommonPreviousDocumentValidationDecider, ICommonPreviousDocumentArrivalValidationDecider
{
}
