// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Schema.OnlineUpgrade.TablePreSynchroniser.AddAndPopulateAuditAndNaturalKeyColumns")] // C:\git\wtg\CargoWise\Dev\Database\Odyssey\Transformations\Transformations\OnlinePreUpgrade\Internal\TablePreSynchroniser.cs:86:6
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Transformations.PreUpgrade.Freight.Testing.EnsureUniqueGateBookingNumbersTest.CreateGateBooking(System.String,System.String,System.Guid)")] // Database/Odyssey/Transformations/Transformations/PreUpgrade/Public/Freight/EnsureUniqueGateBookingNumbers.cs:142,68
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Transformations.PreUpgrade.Freight.Testing.EnsureUniqueGateBookingNumbersTest.CreateGateBooking(System.String,System.String,System.Guid)")] // Database/Odyssey/Transformations/Transformations/PreUpgrade/Public/Freight/EnsureUniqueGateBookingNumbers.cs:143,70
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Transformations.PreUpgrade.Public.Customs.DE.Testing.MoveZG_OriginFederalStateToJI_StateOrRegionOfOriginTest.PrepareTestData")] // Database/Odyssey/Transformations/Transformations/PreUpgrade/Public/Customs/DE/MoveZG_OriginFederalStateToJI_StateOrRegionOfOrigin.cs:75,76
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Transformations.PreUpgrade.Public.Customs.DE.Testing.MoveZG_OriginFederalStateToJI_StateOrRegionOfOriginTest.PrepareTestData")] // Database/Odyssey/Transformations/Transformations/PreUpgrade/Public/Customs/DE/MoveZG_OriginFederalStateToJI_StateOrRegionOfOrigin.cs:77,74
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "We want to compare Utc Time", Scope = "member", Target = "~M:Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.TransformStmALogToWhsInventoryHoldChangeLog.OnlinePreUpgradeTransformCore")]
