<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.IEReferenceData.Tests</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.IEReferenceData.Tests</AssemblyName>
    <Configurations>Debug</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <ProjectReference Include="..\IEReferenceData.Business\IEReferenceData.Business.csproj" />
    <ProjectReference Include="..\IEReferenceData.CmdLine\IEReferenceData.CmdLine.csproj" />
    <ProjectReference Include="..\IEReferenceData.Services\IEReferenceData.Services.csproj" />
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <EmbeddedResource Include="*\TestFiles\Output\**" />
    <Content Include="*\TestFiles\Input\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>