using Enterprise.Edifact.Auto;

namespace Enterprise.Customs.AU.Declaration.Business.D98B
{
	[Resources.AutoGeneratedSourceCode()]
	public class IFTERAMessage : SegmentGroup
	{
		public IFTERAMessage()
		{
			UNH = new UNHSegmentMessageSection(1);
			BGM = new BGMSegmentMessageSection(1);
			DTM = new DTMSegmentMessageSection(1);
			Group1 = new SegmentGroup1MessageSection(2);
			Group3 = new SegmentGroup3MessageSection(2);
			Group4 = new SegmentGroup4MessageSection(2);
			UNT = new UNTSegmentMessageSection(1);
		}

		public readonly UNHSegmentMessageSection UNH;
		public readonly BGMSegmentMessageSection BGM;
		public readonly DTMSegmentMessageSection DTM;
		public readonly SegmentGroup1MessageSection Group1;
		public readonly SegmentGroup3MessageSection Group3;
		public readonly SegmentGroup4MessageSection Group4;
		public readonly UNTSegmentMessageSection UNT;

		protected override MessageSectionBase[] GetMessageSections()
		{
			return new MessageSectionBase[] { UNH, BGM, DTM, Group1, Group3, Group4, UNT };
		}
	}
}
