// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.DatabaseResourceStringSource.WriteAll(System.Collections.Generic.IEnumerable{CargoWiseOne.ResourceStrings.ResourceStringData})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ResourceStrings\Business\Data\Cache\DatabaseResourceStringSource.cs:34:22
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.DatabaseResourceStringSource.WriteAll(System.Collections.Generic.IEnumerable{CargoWiseOne.ResourceStrings.ResourceStringData})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ResourceStrings\Business\Data\Cache\DatabaseResourceStringSource.cs:42:22
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.TranslationFeedbackResourceStringsSource.CreateAll(System.String[])")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ResourceStrings\Business\Data\Cache\TranslationFeedbackResourceStringsSource.cs:33:20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.TranslationFeedbackResourceStringsSource.ReadAll")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ResourceStrings\Business\Data\Cache\TranslationFeedbackResourceStringsSource.cs:72:20
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.ResourceFilesAreInBuildXmlTestCase.GetLanguagesInBuildXml")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ResourceStrings\Business\ResourceFilesAreInBuildXmlTestCase.cs:29:82
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.TranslationFeedbackTestCase.ResetConnection")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackFactory.cs:1153,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.TranslationFeedbackTestCase.ResetConnection")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackFactory.cs:1154,3
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.StringContentTest.TestSpelling(System.String)")] // Enterprise/Product/Core/ResourceStrings/Business/StringContentTest.cs:609,36
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.TranslationFeedbackContentAdapterTest.TestApprovedFeedbackInMatchingLanguage")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackContentAdapter.cs:137,21
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.TranslationFeedbackContentAdapterTest.TestApprovedFeedbackInMatchingLanguage")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackContentAdapter.cs:140,135
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ResourceStrings.Business.Testing.StmTranslationFeedbackResourceTest.TestReportNameMaxLength")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/StmTranslationFeedback/StmTranslationFeedbackResource.cs:190,35
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.Testing.StringContentTest.ExcludedDependencyFiles")] // Enterprise/Product/Core/ResourceStrings/Business/StringContentTest.cs:925,18
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.Segmentation.segmentBreakRegex")] // Enterprise/Product/Core/ResourceStrings/Business/TM/Segmentation.cs:71,15
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.TranslationFileModuleMapping.NonContextPaths")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFileModuleMapping.cs:84,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.TranslationFileModuleMapping.instance")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFileModuleMapping.cs:11,38
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.HelpDataStringSchema.Instance")] // Enterprise/Product/Core/ResourceStrings/Business/Data/HelpDataStringSchema.cs:47,46
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.TranslationFeedbackFactory.captionCache")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackFactory.cs:432,74
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.TranslationFeedbackConfiguration.isMasterDatabaseForTest")] // Enterprise/Product/Core/ResourceStrings/Business/TranslationFeedback/TranslationFeedbackConfiguration.cs:26,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.Analysis.CodeStringFinder.SupportedReturnTypes")] // Enterprise/Product/Core/ResourceStrings/Business/Analysis/CodeStringFinder.cs:366,18
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.Analysis.Testing.CodeStringFinderTest.ClassWithStaticConstructor.Item")] // Enterprise/Product/Core/ResourceStrings/Business/Analysis/CodeStringFinder.cs:1042,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ResourceStrings.Business.ResourceStringsFactory.cacheReferences")] // Enterprise/Product/Core/ResourceStrings/Business/Data/ResourceStringsFactory.cs:460,56
