<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.edi.com.au/EnterpriseService/#Usage_2.1" elementFormDefault="qualified">
	<xs:element name="UsageTransaction">
		<xs:complexType>
			<xs:all>
				<xs:element name="UsageCount">
					<xs:simpleType>
						<xs:restriction base="xs:int">
							<xs:minExclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ServiceOccuredUTC">
					<xs:simpleType>
						<xs:restriction base="xs:dateTime">
							<xs:minExclusive value="1900-01-01T00:00:00"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="AdditionalRefs" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EnterpriseCode" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ServerCode" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Environment" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CompanyCode" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="CompanyName" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="BranchCode" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="UsageCode" minOccurs="0" nillable="true">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>
