<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <SuppressObsoleteWarnings>SYSLIB0006</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\Operations\MasterFiles\Business\MasterFiles.Business\System\StmUpgrade\testing.edp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScheduledUpgrader\Enterprise.ServiceManager.Tasks.ScheduledUpgrader.csproj" />
  </ItemGroup>
</Project>