--------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated from TriggerGenerator.
--
--     Manual changes to this file may cause unexpected behavior in your application.
--     Manual changes to this file will be overwritten if the code is regenerated.
-- </auto-generated>
--------------------------------------------------------------------------------
CREATE TRIGGER RefAccTaxRate_Version_Create
	ON RefAccTaxRate
	FOR INSERT
	AS
	INSERT RefDbVersionControl (RVC_ParentPK, RVC_ParentCode)
	SELECT ZAT_PK, 'ZAT'
	FROM inserted
GO
CREATE TRIGGER RefAccTaxRate_Version_Update
	ON RefAccTaxRate
	FOR Update
	AS
	UPDATE version SET RVC_IsPublished = 0, RVC_LastEditedUser = dbo.GetUserId()
	FROM RefDbVersionControl version
	JOIN inserted ON ZAT_PK = RVC_ParentPK
	WHERE RVC_IsPublished = 1
GO
CREATE TRIGGER RefAccTaxRate_DataChangeHistory
	ON RefAccTaxRate
	FOR INSERT, UPDATE, DELETE
	AS
	DECLARE @sourcePK SourcePKList;
	INSERT @sourcePK
	SELECT ZAT_PK, 'ZAT' FROM inserted
	UNION
	SELECT ZAT_PK, 'ZAT' FROM deleted

	EXEC dbo.RecordDataSetChangeHistory @sourcePK
GO
CREATE TRIGGER RefAccTaxRate_DataProcessingResult_Delete
	ON RefAccTaxRate
	FOR DELETE
	AS
	BEGIN
		DELETE dpr
		FROM dbo.RefStagingDatabase_DataProcessingResult dpr
		JOIN deleted d ON dpr.DPR_ParentPK = d.ZAT_PK
	END
GO
