<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <EmbeddedResource Include="MXEnterpriseApplicationConfiguration.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Business\CodeDescriptionPairLists\CustomsRegimeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CustomsRegimeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Business\CodeDescriptionPairLists\MessageTypesList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageTypesList.xml</DependentUpon>
    </Compile>
    <Compile Update="Business\CodeDescriptionPairLists\MXDeclarationTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MXDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Business\CodeDescriptionPairLists\GoodsRegionList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GoodsRegionList.xml</DependentUpon>
    </Compile>
    <Compile Update="Business\CodeDescriptionPairLists\MXCustomsContainerCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MXCustomsContainerCodeList.xml</DependentUpon>
    </Compile>
    <None Update="Business\CodeDescriptionPairLists\CustomsRegimeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CustomsRegimeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.MX.Business</CustomToolNamespace>
    </None>
    <None Update="Business\CodeDescriptionPairLists\MessageTypesList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageTypesList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.MX.Business</CustomToolNamespace>
    </None>
    <None Update="Business\CodeDescriptionPairLists\MXDeclarationTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MXDeclarationTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.MX.Business</CustomToolNamespace>
    </None>
    <None Update="Business\CodeDescriptionPairLists\GoodsRegionList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>GoodsRegionList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.MX.Business</CustomToolNamespace>
    </None>
    <None Update="Business\CodeDescriptionPairLists\MXCustomsContainerCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.MX.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MXCustomsContainerCodeList.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>