<Project>
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.DataTransfer.Test" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
</Project>