<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientPOW.Test</AssemblyName>
    <RootNamespace>Enterprise.Client.ZClientPOW.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientPOW\ZClientPOW.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\..\Enterprise\ClientExtensions\POW\ZClientPOW\ZClientPOW.Test\Suzuki\TestFiles\SuzukiTestData.txt">
      <LogicalName>SuzukiTestData.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>