<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:ns4="http://Microsoft.LobServices.Sap/2007/03/Types/Idoc/Common/" elementFormDefault="qualified" targetNamespace="http://Microsoft.LobServices.Sap/2007/03/Types/Idoc/Common/" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:appinfo>
      <fileNameHint xmlns="http://schemas.microsoft.com/servicemodel/adapters/metadata/xsd">IDocSharedTypes</fileNameHint>
    </xs:appinfo>
  </xs:annotation>
  <xs:complexType name="EDI_DC">
    <xs:annotation>
      <xs:documentation>
        <doc:description xmlns:doc="http://schemas.microsoft.com/servicemodel/adapters/metadata/documentation">Control record for the interface to the EDI subsystem</doc:description>
      </xs:documentation>
      <xs:appinfo>
        <groupInfo sequence_number="0" xmlns="http://schemas.microsoft.com/BizTalk/2003">
        </groupInfo>
      </xs:appinfo>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="TABNAM" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of external structure</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="10" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="MANDT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Client</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="3" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="DOCNUM" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc number</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="16" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="DOCREL" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>SAP Release for IDoc</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="4" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="STATUS" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Status of IDoc</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="2" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="DOCTYP" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc type</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="8" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="DIRECT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Direction for IDoc transmission</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="1" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVPOR" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Receiver port (SAP System, EDI subsystem)</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="10" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVPRT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner Type of Receiver</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="2" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVPRN" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner Number of Receiver</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="10" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVSAD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc: SADR fields in total</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="21" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVLAD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Logical address of recipient</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="70" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="STD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>EDI Standard</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="1" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="STDVRS" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Version of EDI standard</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="6" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="STDMES" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>EDI message type</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="6" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="MESCOD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Logical message code</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="3" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="MESFCT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Logical message function</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="3" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="OUTMOD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Output Mode</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="1" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="TEST" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Test flag</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="1" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDPOR" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Sender port (SAP System, EDI subsystem)</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="10" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDPRT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner type of sender</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="2" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDPRN" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner Number of Sender</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="10" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDSAD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc: SADR fields in total</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="21" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDLAD" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Logical address of sender</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="70" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="REFINT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Reference to interchange file</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="14" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="REFGRP" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Reference to message group</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="14" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="REFMES" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Reference to message</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="14" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="ARCKEY" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>EDI archive key</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="70" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="CREDAT" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc Created On</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="8" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="CRETIM" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>IDoc creation time</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="6" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="MESTYP" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Logical message type</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="6" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="IDOCTYP" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of basic type</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="8" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="CIMTYP" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Extension</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="8" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="RCVPFC" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner Function of Recipient</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="2" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SNDPFC" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Partner Function of Sender</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="2" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="SERIAL" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>EDI/ALE: Serialization field</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="20" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" maxOccurs="1" name="EXPRSS" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:documentation>Overriding in inbound processing</xs:documentation>
          <xs:appinfo>
            <fieldInfo pad_char="0x20" pad_char_type="hex" justification="left" pos_offset="0" pos_length="1" xmlns="http://schemas.microsoft.com/BizTalk/2003">
            </fieldInfo>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="EDI_DC" nillable="true" type="ns4:EDI_DC" />
</xs:schema>