<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\OperationalActions.Integration\Enterprise.Services.OperationalActions.Integration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Support" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Microsoft.SqlServer.Types" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="FieldModule\AutoFieldModule.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoFieldModule.xml</DependentUpon>
    </Compile>
    <Compile Update="FieldSupporters\BooleanChangeType.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>BooleanChangeType.xml</DependentUpon>
    </Compile>
    <Compile Update="OperationalActionRunner\AutoOperationalActionRunner.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoOperationalActionRunner.xml</DependentUpon>
    </Compile>
    <Compile Update="OperationalActionFieldDescriptor\AutoOperationalActionFieldDescriptor.cs">
      <DependentUpon>AutoOperationalActionFieldDescriptor.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="OperationalActionMethodDescriptor\AutoOperationalActionMethodDescriptor.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoOperationalActionMethodDescriptor.xml</DependentUpon>
    </Compile>
    <Compile Update="Shared\EmptyBehaviourList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmptyBehaviourList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="FieldModule\AutoFieldModule.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoFieldModule.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
    </None>
    <None Update="FieldSupporters\BooleanChangeType.xml">
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>BooleanChangeType.cs</LastGenOutput>
    </None>
    <None Update="OperationalActionFieldDescriptor\AutoOperationalActionFieldDescriptor.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoOperationalActionFieldDescriptor.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
    </None>
    <None Update="OperationalActionMethodDescriptor\AutoOperationalActionMethodDescriptor.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoOperationalActionMethodDescriptor.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
    </None>
    <None Update="OperationalActionRunner\AutoOperationalActionRunner.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
      <LastGenOutput>AutoOperationalActionRunner.cs</LastGenOutput>
    </None>
    <None Update="Shared\EmptyBehaviourList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmptyBehaviourList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Services.OperationalActions.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>