<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Initialisation.Test</AssemblyName>
    <RootNamespace>Enterprise.Initialisation.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <PackageReference Include="WTG.AppDomainWrappers.Core" />
    <PackageReference Include="WTG.AppDomainWrappers.Runner" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Initialization\Initialisation.csproj" />
  </ItemGroup>
</Project>