<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.ZArchitecture.Web.Business.csproj" />
    <ProjectReference Include="..\GUI.Test\Enterprise.ZArchitecture.Web.GUI.Test.csproj" />
    <ProjectReference Include="..\GUI\Enterprise.ZArchitecture.Web.GUI.csproj" />
    <ProjectReference Include="..\Ajax\Enterprise.ZArchitecture.Web.GUI.Ajax.csproj" />
    <ProjectReference Include="..\Utilities.Test\Enterprise.ZArchitecture.Web.Utilities.Test.csproj" />
  </ItemGroup>
</Project>