<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <BaseOutputPath>..\..\..\Bin\ElasticSearch.WorkerService.Tests</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Collector\ElasticSearch\WorkerService\CargoWise.eServices.Billing.Collector.NET.ElasticSearch.WorkerService.csproj" />
    <ProjectReference Include="..\..\NET\WindowsService\Common.Tests\CargoWise.eServices.Billing.Collector.NET.BackgroundService.Common.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Billing.API">
      <HintPath>..\..\..\Bin\CargoWise.Billing.CollectorService\Plugin\netstandard2.0\CargoWise.Billing.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Client">
      <HintPath>..\..\..\Bin\CargoWise.Billing.Client\netstandard2.0\CargoWise.Billing.Client.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.CollectorService.Plugin">
      <HintPath>..\..\..\Bin\CargoWise.Billing.CollectorService\Plugin\netstandard2.0\CargoWise.Billing.CollectorService.Plugin.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.CollectorService.Plugin.Tests">
      <HintPath>..\..\..\Bin\CargoWise.Billing.CollectorService\Plugin.Tests\net8.0\CargoWise.Billing.CollectorService.Plugin.Tests.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
