version: '3'

services:
  api:
    image: api
    build:
      context: FrontEnd/API
      dockerfile: FrontEnd/API/Dockerfile

  paralleliser:
    image: paralleliser
    build:
      context: Components/Paralleliser
      dockerfile: Components/Paralleliser/Dockerfile

