<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.BufferManagement.NetworkVisualisation.GUI</RootNamespace>
    <AssemblyName>Enterprise.BufferManagement.NetworkVisualisation.GUI</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Compile Remove="Winzor\**" />
    <Compile Remove="wwwroot\**" />
    <EmbeddedResource Remove="Winzor\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="Winzor\**" />
    <None Remove="wwwroot\**" />
    <Page Remove="Winzor\**" />
    <Page Remove="wwwroot\**" />
    <AdditionalFiles Remove="wwwroot\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Main.Navigation" />
    <Reference Include="CargoWise.NetworkVisualisation.GUI" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.TimeEngineScheduler.Integration" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
    <Reference Include="System.Resources.Extensions" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Main\Business\BufferManagement.Business.csproj" />
    <ProjectReference Include="..\..\Main\GUI\BufferManagement.GUI.csproj" />
    <ProjectReference Include="..\..\Main\Integration\BufferManagement.Integration.csproj" />
    <ProjectReference Include="..\NCN.Business\BufferManagement.NetworkVisualisation.Business.csproj" />
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.Business\VisualBoards.Business.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>