FROM microsoft/dotnet:sdk AS build
ENV HTTPS_PROXY=http://sydco-spxy-1.wtg.zone:8080
WORKDIR /src
COPY . .
RUN dotnet publish -c Debug -o out

FROM microsoft/dotnet:runtime AS final
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT ["dotnet", "/app/Paralleliser.dll"]
