// ----------------------------------------------------------------------
// <auto-generated>
//      This code is auto-generated by the awesome NonPersistentBusinessObjectGenerator(tm)
//      Any changes to this file will be lost when the generator is next run.
// </auto-generated>
// ----------------------------------------------------------------------
using System;
using System.ComponentModel;
using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.Environment;

namespace Enterprise.ServiceManager.Business
{
	
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoStmServiceTaskAdapter : NonPersistentBusinessObject
	{
		#region Schema
		public class Schema
		{
			public const string Period = "Period";
			public const string Monday = "Monday";
			public const string Tuesday = "Tuesday";
			public const string Wednesday = "Wednesday";
			public const string Thursday = "Thursday";
			public const string Friday = "Friday";
			public const string Saturday = "Saturday";
			public const string Sunday = "Sunday";
			public const string DayOfMonth = "DayOfMonth";
			public const string YearlyDay = "YearlyDay";
			public const string CalcDailyStartTimeUtc = "CalcDailyStartTimeUtc";
			public const string CalcDailyEndTimeUtc = "CalcDailyEndTimeUtc";
		}
		#endregion
		protected AutoStmServiceTaskAdapter()
		{
		}
		protected AutoStmServiceTaskAdapter(BusinessObjectFactory factory) : base(factory)
		{
		}
		#region Period
		public virtual ZInt Period
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return period;
			}
			set
			{
				SetNonPersistentPropertyValue(PeriodInfo, ref period, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidatePeriod();
				}
			}
		}
		public virtual ZPropertyInfo PeriodInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Period);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZInt period;
		#endregion
		#region Monday
		public virtual ZBool Monday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return monday;
			}
			set
			{
				SetNonPersistentPropertyValue(MondayInfo, ref monday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateMonday();
				}
			}
		}
		public virtual ZPropertyInfo MondayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Monday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool monday;
		#endregion
		#region Tuesday
		public virtual ZBool Tuesday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tuesday;
			}
			set
			{
				SetNonPersistentPropertyValue(TuesdayInfo, ref tuesday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateTuesday();
				}
			}
		}
		public virtual ZPropertyInfo TuesdayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Tuesday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool tuesday;
		#endregion
		#region Wednesday
		public virtual ZBool Wednesday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return wednesday;
			}
			set
			{
				SetNonPersistentPropertyValue(WednesdayInfo, ref wednesday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateWednesday();
				}
			}
		}
		public virtual ZPropertyInfo WednesdayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Wednesday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool wednesday;
		#endregion
		#region Thursday
		public virtual ZBool Thursday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return thursday;
			}
			set
			{
				SetNonPersistentPropertyValue(ThursdayInfo, ref thursday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateThursday();
				}
			}
		}
		public virtual ZPropertyInfo ThursdayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Thursday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool thursday;
		#endregion
		#region Friday
		public virtual ZBool Friday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return friday;
			}
			set
			{
				SetNonPersistentPropertyValue(FridayInfo, ref friday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateFriday();
				}
			}
		}
		public virtual ZPropertyInfo FridayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Friday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool friday;
		#endregion
		#region Saturday
		public virtual ZBool Saturday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return saturday;
			}
			set
			{
				SetNonPersistentPropertyValue(SaturdayInfo, ref saturday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateSaturday();
				}
			}
		}
		public virtual ZPropertyInfo SaturdayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Saturday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool saturday;
		#endregion
		#region Sunday
		public virtual ZBool Sunday
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return sunday;
			}
			set
			{
				SetNonPersistentPropertyValue(SundayInfo, ref sunday, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateSunday();
				}
			}
		}
		public virtual ZPropertyInfo SundayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.Sunday);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZBool sunday;
		#endregion
		#region DayOfMonth
		public virtual ZInt DayOfMonth
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return dayOfMonth;
			}
			set
			{
				SetNonPersistentPropertyValue(DayOfMonthInfo, ref dayOfMonth, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateDayOfMonth();
				}
			}
		}
		public virtual ZPropertyInfo DayOfMonthInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.DayOfMonth);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZInt dayOfMonth;
		#endregion
		#region YearlyDay
		public virtual ZInt YearlyDay
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return yearlyDay;
			}
			set
			{
				SetNonPersistentPropertyValue(YearlyDayInfo, ref yearlyDay, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateYearlyDay();
				}
			}
		}
		public virtual ZPropertyInfo YearlyDayInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.YearlyDay);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZInt yearlyDay;
		#endregion
		#region CalcDailyStartTimeUtc
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.ServiceManager.Business.StmServiceTaskAdapter|CalcDailyStartTimeUtc", Caption="Start time (UTC)")]
		public virtual ZDateTime CalcDailyStartTimeUtc
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return calcDailyStartTimeUtc;
			}
			set
			{
				SetNonPersistentPropertyValue(CalcDailyStartTimeUtcInfo, ref calcDailyStartTimeUtc, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateCalcDailyStartTimeUtc();
				}
			}
		}
		public virtual ZPropertyInfo CalcDailyStartTimeUtcInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.CalcDailyStartTimeUtc);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZDateTime calcDailyStartTimeUtc;
		#endregion
		#region CalcDailyEndTimeUtc
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.ServiceManager.Business.StmServiceTaskAdapter|CalcDailyEndTimeUtc", Caption="End time (UTC)")]
		public virtual ZDateTime CalcDailyEndTimeUtc
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return calcDailyEndTimeUtc;
			}
			set
			{
				SetNonPersistentPropertyValue(CalcDailyEndTimeUtcInfo, ref calcDailyEndTimeUtc, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateCalcDailyEndTimeUtc();
				}
			}
		}
		public virtual ZPropertyInfo CalcDailyEndTimeUtcInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.CalcDailyEndTimeUtc);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZDateTime calcDailyEndTimeUtc;
		#endregion
		#region Validation
		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore();
		}
		public StmServiceTaskAdapterValidation Validation
		{
			get
			{
				return GetNewValidation();
			}
		}
		protected virtual StmServiceTaskAdapterValidation GetNewValidation()
		{
			return new StmServiceTaskAdapterValidation(this);
		}
		#endregion
	}
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoStmServiceTaskAdapterValidation : ZValidation
	{
		public AutoStmServiceTaskAdapterValidation(AutoStmServiceTaskAdapter parent) : base(parent)
		{
			this.parent = parent;
			this.ZValidationInternals = this;
			this.ParentListInternals = parent;
		}
		public void Add(AutoStmServiceTaskAdapterValidation validation)
		{
			ZValidationInternals.Add(validation);
		}
		public void Remove(AutoStmServiceTaskAdapterValidation validation)
		{
			ZValidationInternals.Remove(validation);
		}
		#region ValidateAll
		public override void ValidateAll()
		{
			IDisposable suspender = ParentListInternals.SuspendListChanged();
			try
			{
				ValidateAllCore();
			}
			finally
			{
				suspender.Dispose();
			}
		}
		protected virtual void ValidateAllCore()
		{
			ValidatePeriod();
			ValidateMonday();
			ValidateTuesday();
			ValidateWednesday();
			ValidateThursday();
			ValidateFriday();
			ValidateSaturday();
			ValidateSunday();
			ValidateDayOfMonth();
			ValidateYearlyDay();
			ValidateCalcDailyStartTimeUtc();
			ValidateCalcDailyEndTimeUtc();
		}
		#endregion
		#region Period
		public void ValidatePeriod()
		{
			ZValidationInternals.Validate(Parent.PeriodInfo, new RunValidationInvoker(this.CheckPeriod));
		}
		protected virtual void CheckPeriod()
		{
		}
		#endregion
		#region Monday
		public void ValidateMonday()
		{
			ZValidationInternals.Validate(Parent.MondayInfo, new RunValidationInvoker(this.CheckMonday));
		}
		protected virtual void CheckMonday()
		{
		}
		#endregion
		#region Tuesday
		public void ValidateTuesday()
		{
			ZValidationInternals.Validate(Parent.TuesdayInfo, new RunValidationInvoker(this.CheckTuesday));
		}
		protected virtual void CheckTuesday()
		{
		}
		#endregion
		#region Wednesday
		public void ValidateWednesday()
		{
			ZValidationInternals.Validate(Parent.WednesdayInfo, new RunValidationInvoker(this.CheckWednesday));
		}
		protected virtual void CheckWednesday()
		{
		}
		#endregion
		#region Thursday
		public void ValidateThursday()
		{
			ZValidationInternals.Validate(Parent.ThursdayInfo, new RunValidationInvoker(this.CheckThursday));
		}
		protected virtual void CheckThursday()
		{
		}
		#endregion
		#region Friday
		public void ValidateFriday()
		{
			ZValidationInternals.Validate(Parent.FridayInfo, new RunValidationInvoker(this.CheckFriday));
		}
		protected virtual void CheckFriday()
		{
		}
		#endregion
		#region Saturday
		public void ValidateSaturday()
		{
			ZValidationInternals.Validate(Parent.SaturdayInfo, new RunValidationInvoker(this.CheckSaturday));
		}
		protected virtual void CheckSaturday()
		{
		}
		#endregion
		#region Sunday
		public void ValidateSunday()
		{
			ZValidationInternals.Validate(Parent.SundayInfo, new RunValidationInvoker(this.CheckSunday));
		}
		protected virtual void CheckSunday()
		{
		}
		#endregion
		#region DayOfMonth
		public void ValidateDayOfMonth()
		{
			ZValidationInternals.Validate(Parent.DayOfMonthInfo, new RunValidationInvoker(this.CheckDayOfMonth));
		}
		protected virtual void CheckDayOfMonth()
		{
		}
		#endregion
		#region YearlyDay
		public void ValidateYearlyDay()
		{
			ZValidationInternals.Validate(Parent.YearlyDayInfo, new RunValidationInvoker(this.CheckYearlyDay));
		}
		protected virtual void CheckYearlyDay()
		{
		}
		#endregion
		#region CalcDailyStartTimeUtc
		public void ValidateCalcDailyStartTimeUtc()
		{
			ZValidationInternals.Validate(Parent.CalcDailyStartTimeUtcInfo, new RunValidationInvoker(this.CalcDailyStartTimeUtcValidationInvoker));
		}
		private void CalcDailyStartTimeUtcValidationInvoker()
		{
			CheckCalcDailyStartTimeUtcIsValidZDateTime();
			CheckCalcDailyStartTimeUtcIsValidZDateTimeRange();
			CheckCalcDailyStartTimeUtc();
		}
		protected virtual void CheckCalcDailyStartTimeUtcIsValidZDateTime()
		{
			TypeValidation.CheckValidZDateTimeWithoutRange(Parent.CalcDailyStartTimeUtcInfo);
		}
		protected virtual void CheckCalcDailyStartTimeUtcIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.CalcDailyStartTimeUtcInfo);
		}
		protected virtual void CheckCalcDailyStartTimeUtc()
		{
		}
		#endregion
		#region CalcDailyEndTimeUtc
		public void ValidateCalcDailyEndTimeUtc()
		{
			ZValidationInternals.Validate(Parent.CalcDailyEndTimeUtcInfo, new RunValidationInvoker(this.CalcDailyEndTimeUtcValidationInvoker));
		}
		private void CalcDailyEndTimeUtcValidationInvoker()
		{
			CheckCalcDailyEndTimeUtcIsValidZDateTime();
			CheckCalcDailyEndTimeUtcIsValidZDateTimeRange();
			CheckCalcDailyEndTimeUtc();
		}
		protected virtual void CheckCalcDailyEndTimeUtcIsValidZDateTime()
		{
			TypeValidation.CheckValidZDateTimeWithoutRange(Parent.CalcDailyEndTimeUtcInfo);
		}
		protected virtual void CheckCalcDailyEndTimeUtcIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.CalcDailyEndTimeUtcInfo);
		}
		protected virtual void CheckCalcDailyEndTimeUtc()
		{
		}
		#endregion
		#region Implementation
		public override Type AutoValidationType
		{
			get
			{
				return typeof(AutoStmServiceTaskAdapterValidation);
			}
		}
		public AutoStmServiceTaskAdapter Parent
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return parent;
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private AutoStmServiceTaskAdapter parent;
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private IValidationInternals ZValidationInternals;
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ISingleElementListInternal ParentListInternals;
		#endregion
	}
}
