// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondHeaderTest.TestShouldPopulateUniqueJobReference")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondHeader/CusInBondHeaderTest.cs:40,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondHeaderTest.TestShouldPopulateUniqueJobReference")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondHeader/CusInBondHeaderTest.cs:47,3
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.InBondMessageSendingObjectTest.TestArrivalFieldsValidationOnlyForMoveHeaderToBeSent")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/MessageAction/InBondMessageSendingObjectTest.cs:1523,34
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondMoveHeaderTest.TestICBPEDIMessageMessageTextNumberPlaceHolderFillerMembers")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:1006,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondMoveHeaderTest.TestICBPEDIMessageMessageTextNumberPlaceHolderFillerMembers")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:1025,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondMoveHeaderTest.TestAutomaticallyAllocateNumber")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:1035,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.InBond.Business.Testing.CusInBondMoveHeaderTest.TestAutomaticallyAllocateNumber")] // Enterprise/Product/Operations/Customs/US/InBond/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:1070,4
