// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.KR.Business.Testing.ExtendedHoursRequestHeaderTest.TestPopulateEntryData5AC")] // Enterprise/Product/Operations/Customs/KR/Business.Test/NonPersistentBO/ExtendedHoursRequestHeader/ExtendedHoursRequestHeaderTest.cs:23,45
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.KR.Business.Testing.ExtendedHoursRequestHeaderTest.TestPopulateEntryData5GW")] // Enterprise/Product/Operations/Customs/KR/Business.Test/NonPersistentBO/ExtendedHoursRequestHeader/ExtendedHoursRequestHeaderTest.cs:47,45
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.KR.Business.Testing.CusEntryInstructionTest.TestAddInfoIsOverflowWhenMaxLengthData")] // Enterprise/Product/Operations/Customs/KR/Business.Test/Business/CusEntryInstruction/CusEntryInstructionTest.cs:51,45
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.KR.Business.Testing.CusEntryInstructionTest.TestAddInfoIsOverflowWhenMaxLengthData")] // Enterprise/Product/Operations/Customs/KR/Business.Test/Business/CusEntryInstruction/CusEntryInstructionTest.cs:71,16
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.KR.Business.Testing.GOVCBRRR3MessageProcessorTest.TestUpdateEM_ApplicationReference")] // Enterprise/Product/Operations/Customs/KR/Business.Test/MessageProcessors/LocalExport/GOVCBRRR3MessageProcessorTest.cs:866,42
