<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.DE.MessageContracts" />
    <Reference Include="CargoWise.Customs.DE.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.DE.Business" />
    <Reference Include="Enterprise.Customs.DE.Messaging" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.EMCS.Business" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\EmcsGlobalConclusionOfReceiptList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsGlobalConclusionOfReceiptList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsNotificationType.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsNotificationType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsInterruptionReasonList.cs">
      <DependentUpon>EmcsInterruptionReasonList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsRejectionReasonList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsRejectionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsCancellationReason.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsCancellationReason.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsManualClosureRejectionReasonList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsManualClosureRejectionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsErrorTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsErrorTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsReminderMessageType.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsReminderMessageType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsDeferredSubmissionList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsDeferredSubmissionList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsGuarantorTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EmcsGuarantorTypeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\EmcsGlobalConclusionOfReceiptList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsGlobalConclusionOfReceiptList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsNotificationType.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsNotificationType.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsInterruptionReasonList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsInterruptionReasonList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsRejectionReasonList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsRejectionReasonList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsCancellationReason.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <LastGenOutput>EmcsCancellationReason.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsManualClosureRejectionReasonList.xml">
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsManualClosureRejectionReasonList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsErrorTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsErrorTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsReminderMessageType.xml">
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsReminderMessageType.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsDeferredSubmissionList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <LastGenOutput>EmcsDeferredSubmissionList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsGuarantorTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.DE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsGuarantorTypeList.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.DE.EMCS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>