<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing" xmlns:pnt="http://www.myvan.descartes.com/pnt/2018/r1" xmlns:ebi="http://www.myvan.descartes.com/ebi/2004/r1" xmlns:S="http://www.w3.org/2003/05/soap-envelope" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.w3.org/2003/05/soap-envelope" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="Common/DescartesSOAP_wsa.xsd" namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing" />
  <xs:import schemaLocation="Common/DescartesSOAP_ebi.xsd" namespace="http://www.myvan.descartes.com/ebi/2004/r1" />
  <xs:import schemaLocation="Common/DescartesSOAP_pnt.xsd" namespace="http://www.myvan.descartes.com/pnt/2018/r1" />
  <xs:element name="Envelope">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Header">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="wsa:From" />
              <xs:element ref="wsa:To" />
              <xs:element ref="wsa:Action" />
              <xs:element ref="ebi:Sequence" />
              <xs:element ref="pnt:CSPInformation" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Body" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>