using System;
using System.ComponentModel;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.GUI;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.LandedCosting.GUI
{
	public partial class LandCostHistoryUserControl
	{
		#region Component Designer generated code
		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new ZTextBoxColumnStyleInfo();
			ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new ZTextBoxColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfoLineType = new ZDropEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo9 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo10 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo11 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo16 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo17 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo18 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo19 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo20 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo21 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo22 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo23 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo24 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo25 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo26 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo27 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo28 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo29 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo30 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo31 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo32 = new ZCalcEditColumnStyleInfo();
			ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo33 = new ZCalcEditColumnStyleInfo();
			this.LCHistoryGrid = new ZGrid();
			((ISupportInitialize)(this.BindingSource)).BeginInit();
			((ISupportInitialize)(this.LCHistoryGrid)).BeginInit();
			this.LCHistoryGrid.SuspendLayout();
			this.SuspendLayout();
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Business.GenericLandedCostHistoryCollection);
			// 
			// LCHistoryGrid
			// 
			this.LCHistoryGrid.AllowNavigation = false;
			this.BindingSource.SetBindingMember(this.LCHistoryGrid, ".");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(null);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).HumanReadableUltimateDistributeeCode);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).UniqueReferenceNumber);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_OP);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).Lookups.SupplierParts);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostHistoryLineType);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_DutyPercent);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup1);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup2);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup3);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup4);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup5);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroup6);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostGroupMisc);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).UnitPriceInLocalCurrency);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedPerUnitCustomsDisbursementCharges);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedPerUnitLandingCost);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedPerUnitTotalCost);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostMarginPercent1);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostMarginPercent2);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).LH_LandedCostMarginPercent3);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).EffectiveMarkUpPercentage1);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).EffectiveMarkUpPercentage2);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).EffectiveMarkUpPercentage3);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice1ExGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice1IncGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice2ExGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice2IncGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice3ExGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).RoundedSellPrice3IncGST);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).InvoiceQuantity);
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Business.LandedCostHistory)(null)).TotalCost);

			this.LCHistoryGrid.CaptionVisible = false;
			zTextBoxColumnStyleInfo1.Caption = null;
			zTextBoxColumnStyleInfo1.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|ed7b072e-be4d-4a11-a4ec-89a56d6e3155", "LC Host Line Code");
			zTextBoxColumnStyleInfo1.ColumnName = "HumanReadableUltimateDistributeeCode";
			zTextBoxColumnStyleInfo1.IsReadOnly = true;
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(116);
			zTextBoxColumnStyleInfo2.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("ed4bd8df-3641-47a4-b2ba-1dd8cbb12aa1", "Job Reference");
			zTextBoxColumnStyleInfo2.ColumnName = "UniqueReferenceNumber";
			zGuidFindBoxColumnStyleInfo1.BindToList = "Lookups.SupplierParts";
			zGuidFindBoxColumnStyleInfo1.Caption = null;
			zGuidFindBoxColumnStyleInfo1.CaptionResourceString = null;
			zGuidFindBoxColumnStyleInfo1.ColumnName = "LH_OP";
			zGuidFindBoxColumnStyleInfo1.IsReadOnly = true;
			zGuidFindBoxColumnStyleInfo1.ModuleID = Enterprise.ZArchitecture.Modules.ModuleIDs.SupplierPart;
			zDropEditColumnStyleInfoLineType.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfoLineType.ColumnName = "LH_LandedCostHistoryLineType";
			zDropEditColumnStyleInfoLineType.IsVisible = false;
			zDropEditColumnStyleInfoLineType.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.Caption = null;
			zCalcEditColumnStyleInfo3.CaptionResourceString = null;
			zCalcEditColumnStyleInfo3.ColumnName = "LH_DutyPercent";
			zCalcEditColumnStyleInfo3.IsVisible = false;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(51);
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.Caption = null;
			zCalcEditColumnStyleInfo5.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|ca968afa-eed9-4ee2-ad5f-f91b71d8d721", "LC Grp. 1");
			zCalcEditColumnStyleInfo5.ColumnName = "LH_LandedCostGroup1";
			zCalcEditColumnStyleInfo5.IsReadOnly = true;
			zCalcEditColumnStyleInfo5.IsVisible = false;
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.Caption = null;
			zCalcEditColumnStyleInfo6.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|ab65c471-be06-4df3-a475-5859febd7e01", "LC Grp. 2");
			zCalcEditColumnStyleInfo6.ColumnName = "LH_LandedCostGroup2";
			zCalcEditColumnStyleInfo6.IsReadOnly = true;
			zCalcEditColumnStyleInfo6.IsVisible = false;
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.Caption = null;
			zCalcEditColumnStyleInfo7.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|4a40eed4-b94e-4b9f-b467-d274bee81943", "LC Grp. 3");
			zCalcEditColumnStyleInfo7.ColumnName = "LH_LandedCostGroup3";
			zCalcEditColumnStyleInfo7.IsReadOnly = true;
			zCalcEditColumnStyleInfo7.IsVisible = false;
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.Caption = null;
			zCalcEditColumnStyleInfo8.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|8e641a8e-c4ed-480e-ba1d-cbd44e4a4ac6", "LC Grp. 4");
			zCalcEditColumnStyleInfo8.ColumnName = "LH_LandedCostGroup4";
			zCalcEditColumnStyleInfo8.IsReadOnly = true;
			zCalcEditColumnStyleInfo8.IsVisible = false;
			zCalcEditColumnStyleInfo9.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo9.Caption = null;
			zCalcEditColumnStyleInfo9.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|fa5487ee-b0c4-4e43-b7e5-a5d49118d4ee", "LC Grp. 5");
			zCalcEditColumnStyleInfo9.ColumnName = "LH_LandedCostGroup5";
			zCalcEditColumnStyleInfo9.IsReadOnly = true;
			zCalcEditColumnStyleInfo9.IsVisible = false;
			zCalcEditColumnStyleInfo10.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo10.Caption = null;
			zCalcEditColumnStyleInfo10.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|e6b00cea-bce2-42a6-a2e7-c753c5382c40", "LC Grp. 6");
			zCalcEditColumnStyleInfo10.ColumnName = "LH_LandedCostGroup6";
			zCalcEditColumnStyleInfo10.IsReadOnly = true;
			zCalcEditColumnStyleInfo10.IsVisible = false;
			zCalcEditColumnStyleInfo11.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo11.Caption = null;
			zCalcEditColumnStyleInfo11.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|0cf3d7e4-5f78-4c30-87e1-c090531fafb1", "LC Grp. Misc");
			zCalcEditColumnStyleInfo11.ColumnName = "LH_LandedCostGroupMisc";
			zCalcEditColumnStyleInfo11.IsReadOnly = true;
			zCalcEditColumnStyleInfo11.IsVisible = false;
			zCalcEditColumnStyleInfo16.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo16.Caption = null;
			zCalcEditColumnStyleInfo16.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|43102d99-65f6-4a9b-aaf9-0667d3e3be1d", "Unit Price Local Curr");
			zCalcEditColumnStyleInfo16.ColumnName = "UnitPriceInLocalCurrency";
			zCalcEditColumnStyleInfo16.Decimals = 4;
			zCalcEditColumnStyleInfo16.IsReadOnly = true;
			zCalcEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zCalcEditColumnStyleInfo17.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo17.Caption = null;
			zCalcEditColumnStyleInfo17.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|05f1d792-7459-482e-a7bd-59b3cf044675", "Customs Disbursement Charges Per Unit");
			zCalcEditColumnStyleInfo17.ColumnName = "RoundedPerUnitCustomsDisbursementCharges";
			zCalcEditColumnStyleInfo17.Decimals = 4;
			zCalcEditColumnStyleInfo17.IsReadOnly = true;
			zCalcEditColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(208);
			zCalcEditColumnStyleInfo18.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo18.Caption = null;
			zCalcEditColumnStyleInfo18.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|0c34c193-a47f-4201-a51f-1c171e1ffe9c", "Landing Cost Per Unit");
			zCalcEditColumnStyleInfo18.ColumnName = "RoundedPerUnitLandingCost";
			zCalcEditColumnStyleInfo18.Decimals = 4;
			zCalcEditColumnStyleInfo18.IsReadOnly = true;
			zCalcEditColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(126);
			zCalcEditColumnStyleInfo19.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo19.Caption = null;
			zCalcEditColumnStyleInfo19.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|476b267e-72f1-4032-94ae-ccb9564126c8", "Total Cost Per Unit");
			zCalcEditColumnStyleInfo19.ColumnName = "RoundedPerUnitTotalCost";
			zCalcEditColumnStyleInfo19.Decimals = 4;
			zCalcEditColumnStyleInfo19.IsReadOnly = true;
			zCalcEditColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(114);
			zCalcEditColumnStyleInfo20.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo20.Caption = null;
			zCalcEditColumnStyleInfo20.CaptionResourceString = null;
			zCalcEditColumnStyleInfo20.ColumnName = "LH_LandedCostMarginPercent1";
			zCalcEditColumnStyleInfo21.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo21.Caption = null;
			zCalcEditColumnStyleInfo21.CaptionResourceString = null;
			zCalcEditColumnStyleInfo21.ColumnName = "LH_LandedCostMarginPercent2";
			zCalcEditColumnStyleInfo22.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo22.Caption = null;
			zCalcEditColumnStyleInfo22.CaptionResourceString = null;
			zCalcEditColumnStyleInfo22.ColumnName = "LH_LandedCostMarginPercent3";
			zCalcEditColumnStyleInfo23.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo23.Caption = null;
			zCalcEditColumnStyleInfo23.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|e30f5d1e-5002-4a90-a5cf-af87508cdf5a", "Effective Markup % 1");
			zCalcEditColumnStyleInfo23.ColumnName = "EffectiveMarkUpPercentage1";
			zCalcEditColumnStyleInfo23.IsReadOnly = true;
			zCalcEditColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(116);
			zCalcEditColumnStyleInfo24.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo24.Caption = null;
			zCalcEditColumnStyleInfo24.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|e8f14444-71ca-4c4f-92ac-b9e9506cea5a", "Effective Markup % 2");
			zCalcEditColumnStyleInfo24.ColumnName = "EffectiveMarkUpPercentage2";
			zCalcEditColumnStyleInfo24.IsReadOnly = true;
			zCalcEditColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(116);
			zCalcEditColumnStyleInfo25.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo25.Caption = null;
			zCalcEditColumnStyleInfo25.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|bb792286-594a-4f83-a60c-446eb1a113fb", "Effective Markup % 3");
			zCalcEditColumnStyleInfo25.ColumnName = "EffectiveMarkUpPercentage3";
			zCalcEditColumnStyleInfo25.IsReadOnly = true;
			zCalcEditColumnStyleInfo25.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(116);
			zCalcEditColumnStyleInfo26.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo26.Caption = null;
			zCalcEditColumnStyleInfo26.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|731b22e4-2fd4-4b04-bde8-d69cf61a28df", "Sell Price 1 Ex GST");
			zCalcEditColumnStyleInfo26.ColumnName = "RoundedSellPrice1ExGST";
			zCalcEditColumnStyleInfo26.IsReadOnly = true;
			zCalcEditColumnStyleInfo27.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo27.Caption = null;
			zCalcEditColumnStyleInfo27.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|b80651a8-1991-41fd-87bf-60d58cfb2984", "Sell Price 1 Inc GST");
			zCalcEditColumnStyleInfo27.ColumnName = "RoundedSellPrice1IncGST";
			zCalcEditColumnStyleInfo27.IsReadOnly = true;
			zCalcEditColumnStyleInfo28.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo28.Caption = null;
			zCalcEditColumnStyleInfo28.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|adebf464-cbb1-4eec-894f-ba75759ceac8", "Sell Price 2 Ex GST");
			zCalcEditColumnStyleInfo28.ColumnName = "RoundedSellPrice2ExGST";
			zCalcEditColumnStyleInfo28.IsReadOnly = true;
			zCalcEditColumnStyleInfo29.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo29.Caption = null;
			zCalcEditColumnStyleInfo29.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|61574f7a-6e13-4482-a497-b66521a82438", "Sell Price 2 Inc GST");
			zCalcEditColumnStyleInfo29.ColumnName = "RoundedSellPrice2IncGST";
			zCalcEditColumnStyleInfo29.IsReadOnly = true;
			zCalcEditColumnStyleInfo30.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo30.Caption = null;
			zCalcEditColumnStyleInfo30.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|c7ca1d03-1f49-48dc-b7cf-56681a891c0e", "Sell Price 3 Ex GST");
			zCalcEditColumnStyleInfo30.ColumnName = "RoundedSellPrice3ExGST";
			zCalcEditColumnStyleInfo30.IsReadOnly = true;
			zCalcEditColumnStyleInfo31.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo31.Caption = null;
			zCalcEditColumnStyleInfo31.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("LandCostHistoryUserControl|f29a6279-7534-4e1f-82b8-2dad5c8fe714", "Sell Price 3 Inc GST");
			zCalcEditColumnStyleInfo31.ColumnName = "RoundedSellPrice3IncGST";
			zCalcEditColumnStyleInfo31.IsReadOnly = true;
			zCalcEditColumnStyleInfo32.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo32.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("1a11b662-a6a7-4a6e-9d9f-fa6f4c924997", "No Of Units");
			zCalcEditColumnStyleInfo32.ColumnName = "InvoiceQuantity";
			zCalcEditColumnStyleInfo32.IsReadOnly = true;
			zCalcEditColumnStyleInfo32.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo33.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo33.CaptionResourceString = Enterprise.LandedCosting.GUI.Res.GetData("97c09291-2cf1-47ec-bf8f-bb7c563675df", "Total Cost");
			zCalcEditColumnStyleInfo33.ColumnName = "TotalCost";
			zCalcEditColumnStyleInfo33.IsReadOnly = true;
			zCalcEditColumnStyleInfo33.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);

			this.LCHistoryGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.LCHistoryGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.LCHistoryGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.LCHistoryGrid.ColumnStyles.Add(zDropEditColumnStyleInfoLineType);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo9);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo10);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo11);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo16);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo17);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo18);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo19);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo20);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo21);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo22);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo23);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo24);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo25);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo26);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo27);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo28);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo29);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo30);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo31);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo32);
			this.LCHistoryGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo33);
			this.LCHistoryGrid.GridId = "5662fda2-2620-48f6-9a56-546d7db2fe6c";
			this.LCHistoryGrid.CopySelectedRowsAllowed = true;
			this.LCHistoryGrid.Dock = System.Windows.Forms.DockStyle.Fill;
			this.LCHistoryGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.LCHistoryGrid.LayoutKey = "LCHistoryGrid";
			this.LCHistoryGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.LCHistoryGrid.Name = "LCHistoryGrid";
			this.LCHistoryGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(616, 568, true);
			this.LCHistoryGrid.TabIndex = 0;
			// 
			// LandCostHistoryUserControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Controls.Add(this.LCHistoryGrid);
			this.Name = "LandCostHistoryUserControl";
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(616, 568, true);
			((ISupportInitialize)(this.BindingSource)).EndInit();
			((ISupportInitialize)(this.LCHistoryGrid)).EndInit();
			this.LCHistoryGrid.ResumeLayout(false);
			this.LCHistoryGrid.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		#endregion
	}
}
