<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.ASYCUDA.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.ASYCUDA.Business</AssemblyName>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.BufferManagement.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Agency.Business" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.DataTransfer" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.LogWalker" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BusinessObjects\AsycudaBill\AsycudaBillCountry.cs">
      <DependentUpon>AsycudaBill.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\AsycudaBill\AsycudaBillCountryLookups.cs">
      <DependentUpon>AsycudaBillLookups.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\AsycudaBill\AsycudaBillCountryValidation.cs">
      <DependentUpon>AsycudaBillValidationForRegularBill.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\AsycudaManifestHeader\AsycudaManifestHeader.Country.cs">
      <DependentUpon>AsycudaManifestHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\AsycudaManifestHeader\AsycudaManifestHeaderLookups.Country.cs">
      <DependentUpon>AsycudaManifestHeaderLookups.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\AsycudaManifestHeader\BaseAsycudaManifestHeaderValidation.Country.cs">
      <DependentUpon>BaseAsycudaManifestHeaderValidation.cs</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\SealTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SealTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\SpecificCircumstanceList.cs">
      <DependentUpon>SpecificCircumstanceList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\SpecificCircumstanceListPartial.cs">
      <DependentUpon>SpecificCircumstanceList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageStatusCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageStatusCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageStatusCodeListPartial.cs">
      <DependentUpon>MessageStatusCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageSubTypeCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageSubTypeCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CargoStatusList.cs">
      <DependentUpon>CargoStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmptyFullIndicatorList.cs">
      <DependentUpon>EmptyFullIndicatorList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\TransportDocumentTypes.cs">
      <DependentUpon>TransportDocumentTypes.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="InferredSharedManifestSchema.cs">
      <DependentUpon>InferredSharedManifestSchema.xsd</DependentUpon>
    </Compile>
    <Compile Update="InferredSharedManifestSchemaUsingIntsNotIntegers.cs">
      <DependentUpon>InferredSharedManifestSchemaUsingIntsNotIntegers.xsd</DependentUpon>
    </Compile>
    <Compile Update="Messaging\MessageChooser\AutoMessageChooser.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoMessageChooser.xml</DependentUpon>
    </Compile>
    <Compile Update="Messaging\MessageChooserItem\AutoMessageChooserItem.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoMessageChooserItem.xml</DependentUpon>
    </Compile>
    <Compile Update="UniversalDataTransfer\AsycudaUniversalEventMessageProcessor.Constants.cs">
      <DependentUpon>AsycudaUniversalEventMessageProcessor.cs</DependentUpon>
    </Compile>
    <None Update="CodeDescriptionPairLists\SealTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SealTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\SpecificCircumstanceList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SpecificCircumstanceList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\MessageStatusCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageStatusCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\MessageSubTypeCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageSubTypeCodes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\TransportDocumentTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransportDocumentTypes.cs</LastGenOutput>
    </None>
    <None Update="Messaging\MessageChooser\AutoMessageChooser.xml">
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoMessageChooser.cs</LastGenOutput>
    </None>
    <None Update="Messaging\MessageChooserItem\AutoMessageChooserItem.xml">
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoMessageChooserItem.cs</LastGenOutput>
    </None>
    <Content Include="CAR\JavaSource\CarXmlConverter.txt" />
    <Content Include="CAR\JavaSource\ReadCarXmlToVector.txt" />
    <Content Include="CAR\JavaSource\VectorToCar.txt" />
    <Content Include="CAR\JavaSource\XmlCar.txt" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\CargoStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CargoStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EmptyFullIndicatorList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmptyFullIndicatorList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ASYCUDA.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
