// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaPack.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaPack/AsycudaPack.cs:46,52
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaContainerBillOrPackageLink.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaContainerBillOrPackageLink/AsycudaContainerBillOrPackageLink.cs:13,70
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaManifestHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeader.cs:91,62
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaPackedItem.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaPackedItem/AsycudaPackedItem.cs:37,58
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaTax.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaTax/AsycudaTax.cs:13,51
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.CusPersonCountry.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/CusPersonCountry/CusPersonCountry.cs:15,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaContainer.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaContainer/AsycudaContainer.cs:28,57
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaArrivalHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaArrivalHeader/AsycudaArrivalHeader.cs:23,61
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.CusPerson.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/CusPerson/CusPerson.cs:33,46
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.ASYCUDA.Business.AsycudaBill.TypeDecider")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business/BusinessObjects/AsycudaBill/AsycudaBill.cs:50,52
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.ASYCUDA.Business.AsycudaManifestHeader.Messages")]
