//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from EUGuaranteeTypeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.EU.Business.CodeDescriptionPairLists
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class EUGuaranteeTypeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string COD = "COD";
			public const string IMP = "IMP";
			public const string TRA = "TRA";
			public const string TST = "TST";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString COD { get { return ResString.GetMultilingualString("EUGuaranteeTypeList|COD", "Ongoing/comprehensive guarantee"); } }
			public static MultilingualString IMP { get { return ResString.GetMultilingualString("EUGuaranteeTypeList|IMP", "Import"); } }
			public static MultilingualString TRA { get { return ResString.GetMultilingualString("EUGuaranteeTypeList|TRA", "Transit"); } }
			public static MultilingualString TST { get { return ResString.GetMultilingualString("EUGuaranteeTypeList|TST", "Temporary Storage"); } }
		}

		public EUGuaranteeTypeList()
		{
			AddPair(Codes.COD, Descriptions.COD);
			AddPair(Codes.IMP, Descriptions.IMP);
			AddPair(Codes.TRA, Descriptions.TRA);
			AddPair(Codes.TST, Descriptions.TST);
		}
	}
}
