<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.ZAReferenceData.Services</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.ZAReferenceData.Services</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug;Release;UAT</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='UAT|AnyCPU'">
    <DefineConstants>$(DefineConstants);ClientNew</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.SafeDataClient">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.SafeDataClient.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.UniversalXMLProducers.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.UniversalXMLProducers.Common.dll</HintPath>
    </Reference>
    <Reference Include="Edifact">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\Edifact.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Edifact.D96B">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\Enterprise.Edifact.D96B.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>