<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Rating.Business" />
    <Reference Include="Enterprise.Rating.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="PortHubSelection\PortHubSelectionProcessTypeList.cs">
      <DependentUpon>PortHubSelectionProcessTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="PortHubSelection\PortHubSelectionPackModeList.cs">
      <DependentUpon>PortHubSelectionPackModeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="PortHubSelection\PortHubSelectionDirectionList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PortHubSelectionDirectionList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="PortHubZonePivot\PortHubZonePivotResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="PortHubSelection\PortHubSelectionProcessTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PortHubSelectionProcessTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.PortHubs.Business</CustomToolNamespace>
    </None>
    <None Update="PortHubSelection\PortHubSelectionPackModeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PortHubSelectionPackModeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.PortHubs.Business</CustomToolNamespace>
    </None>
    <None Update="PortHubSelection\PortHubSelectionDirectionList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PortHubSelectionDirectionList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.PortHubs.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="PortHubSelection\PortHubSelectionResourceStrings.xml" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>