<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">

    <!-- ============================ -->
    <!--  Definition of simple types  -->
    <!-- ============================ -->
    <!--  Other simple type definitions  -->
    <xsd:simpleType name="SID">
        <xsd:restriction base="xsd:long">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goodsNomenclatureCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{10}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goodsNomenclatureCode_2">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="updateType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[I]|[U]|[D]" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="changeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[U]|[D]" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="national">
        <xsd:restriction base="xsd:long">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="nationalAbbreviation">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="description">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="language">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[A-Za-z]{2}"></xsd:pattern>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="additionalCodeId">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{3}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="additionalCodeType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="applicationCodeAdditionalCodeType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="meursingTablePlanId">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{2}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="footnoteType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}|[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="footnoteId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{5}|[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="applicationCodeFootnoteType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="certificateCode">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{3}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="certificateType">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="headingNumberType">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="dutyExpressionId">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}|[0-9A-Za-z]{2}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="expression">
    	<xsd:restriction base="xsd:string">
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="dutyAmountApplicabilityCode">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="measurementUnitApplicabilityCode">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="monetaryUnitApplicabilityCode">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{1}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="productLineSuffix">
    	<xsd:restriction base="xsd:string">
    		<xsd:pattern value="[0-9A-Za-z]{2}" />
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quantityIndents">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9]{2}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="geographicalAreaId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{4}|[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="statisticalLineCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="geographicalAreaCode">
        <xsd:restriction base="xsd:integer">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goodsNomenclatureGroupType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="goodsNomenclatureGroupId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{6}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="nomenclatureGroupFacilityCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="reductionIndicator">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quotaOrderNumber">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{6}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quotaCriticalStateCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quotaSuspendedStateCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quotaExhaustionStateCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="quotaBlockedStateCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="surveillanceNumber">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{6}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="relationType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="regulationRoleType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="regulationId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{8}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="journalId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z /]{5}|[0-9A-Za-z /]{4}|[0-9A-Za-z /]{3}|[0-9A-Za-z /]{2}|[0-9A-Za-z]{1}|[0-9A-Za-z /]{2}," />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="journalPage">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z ]{1,5}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="replacementIndicator">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="regulationApprovedFlag">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="communityCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{8}|[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="regulationGroup">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="stoppedFlag">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="chapterHeading">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="url">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="actionCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}|[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="conditionCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}|[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="conditionCodeId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}|[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementUnitCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementUnitQualifierCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementType">
        <xsd:restriction base="xsd:int">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementUnitDeclarationCode">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="isReference">
        <xsd:restriction base="xsd:boolean">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="scaleToReference">
        <xsd:restriction base="xsd:decimal">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementSeparator">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measurementSeparatorOrder">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="monetaryUnitCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tradeMovementCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measureType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3,6}"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measureTypeSeriesId">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{2}|[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measureTypeCombination">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="priorityCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="measureComponentApplicableCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="originDestinationCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="orderNumberCaptureCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="explosionLevel">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}|[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="headingNumber">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="rowColumnCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="subheadingSequenceNumber">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{4}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="publicationSigle_CodeType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{4}|[0-9A-Za-z]{3}|[0-9A-Za-z]{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="publicationSigle_Code">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{10}|[0-9A-Za-z]{7}|[0-9A-Za-z]{4}|[0-9A-Za-z]{3}|[0-9A-Za-z]{2}|[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="publicationCode">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{1}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="publicationSigle">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="sequenceNumber">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[0-9A-Za-z]{3}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hiddenQuerySystemDB">
        <xsd:restriction base="xsd:long">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="hiddenDeclarationSystemDB">
        <xsd:restriction base="xsd:long">
        </xsd:restriction>
    </xsd:simpleType>
	
    <xsd:simpleType name="LongDescription">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="20000"/>
        </xsd:restriction>
    </xsd:simpleType>

        <!--<xsd:simpleType name="idType">-->
        <!--<xsd:restriction base="xsd:string">-->
        <!--</xsd:restriction>-->
    <!--</xsd:simpleType>-->



    <!-- =============================== -->
    <!--  Definition of simple elements  -->
    <!-- =============================== -->

    <!--  Simple element definitions of the data export record  -->
    <xsd:element name="id" type="xsd:string"/>
    <xsd:element name="exportType" type="xsd:string"/>

    <!--  Other element definitions  -->
    <xsd:element name="SID" type="at:SID"/>
    <xsd:element name="goodsNomenclatureItemId" type="at:goodsNomenclatureCode"/>
    <xsd:element name="queryDateStart" type="xsd:date"/>
    <xsd:element name="queryDateEnd" type="xsd:date"/>
    <xsd:element name="dateStart" type="xsd:date"/>
    <xsd:element name="dateEnd" type="xsd:date"/>
    <xsd:element name="languageId" type="xsd:string"/>
    <xsd:element name="national" type="xsd:boolean"/>



    <!-- ========================== -->
    <!--  Definition of attributes  -->
    <!-- ========================== -->

    <xsd:attribute name="SID" type="at:SID"/>
    <xsd:attribute name="SIDAdditionalCode" type="at:SID"/>
    <xsd:attribute name="SIDAdditionalCodeDescr" type="at:SID"/>
    <xsd:attribute name="SIDAdditionalCodeDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDCertificateDescription" type="at:SID"/>
    <xsd:attribute name="SIDCertificateDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDFootnoteDescription" type="at:SID"/>
    <xsd:attribute name="SIDFootnoteDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDParentGroup" type="at:SID"/>
    <xsd:attribute name="SIDGeographicalArea" type="at:SID"/>
    <xsd:attribute name="geoGraphicAreaSid" type="at:SID"/>
    <xsd:attribute name="SIDGeographicalAreaDescr" type="at:SID"/>
    <xsd:attribute name="SIDGeographicalAreaDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDGeographicalAreaGroup" type="at:SID"/>
    <xsd:attribute name="SIDMeursingAdditionalCode" type="at:SID"/>
    <xsd:attribute name="SIDQuotaOrderNumber" type="at:SID"/>
    <xsd:attribute name="originSid" type="at:SID"/>
    <xsd:attribute name="SIDSubQuota" type="at:SID"/>
    <xsd:attribute name="SIDQuotaDefinition" type="at:SID"/>
    <xsd:attribute name="SIDTargetDefinition" type="at:SID"/>
    <xsd:attribute name="SIDGoodsNomenclature" type="at:SID"/>
    <xsd:attribute name="SIDGoodsNomenclatureDescr" type="at:SID"/>
    <xsd:attribute name="SIDGoodsNomenclatureDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDExportRefundNomenclature" type="at:SID"/>
    <xsd:attribute name="SIDExportRefundNomenclatureDescr" type="at:SID"/>
    <xsd:attribute name="SIDExportRefundNomenclatureDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="SIDMeasure" type="at:SID"/>
    <xsd:attribute name="SIDMeasureCondition" type="at:SID"/>
    <xsd:attribute name="SIDMonetaryExchangePeriod" type="at:SID"/>
    <xsd:attribute name="SIDTaxCode" type="at:SID"/>

    <xsd:attribute name="updateType" type="at:updateType"/>
    <xsd:attribute name="changeType" type="at:changeType"/>
    <xsd:attribute name="national" type="at:national"/>
    <xsd:attribute name="nationalAbbreviation" type="at:nationalAbbreviation"/>
    <xsd:attribute name="dateStart" type="xsd:date"/>
    <xsd:attribute name="dateEnd" type="xsd:date"/>
    <xsd:attribute name="languageId" type="at:language"/>
    <xsd:attribute name="languageCodeId" type="at:language"/>
    <xsd:attribute name="description" type="at:description"/>
    <!--<xsd:attribute name="shortDescription" type="xsd:string"/>-->
    <!--<xsd:attribute name="longDescription" type="xsd:string"/>-->

    <xsd:attribute name="footnoteId" type="at:footnoteId"/>
    <xsd:attribute name="footnoteType" type="at:footnoteType"/>
    <xsd:attribute name="applicationCodeFootnoteType" type="at:applicationCodeFootnoteType"/>
    <xsd:attribute name="additionalCodeType" type="at:additionalCodeType"/>
    <xsd:attribute name="additionalCodeId" type="at:additionalCodeId"/>
    <xsd:attribute name="applicationCodeAdditionalCodeType" type="at:applicationCodeAdditionalCodeType"/>
    <xsd:attribute name="meursingTablePlanId" type="at:meursingTablePlanId"/>

    <xsd:attribute name="certificateType" type="at:certificateType"/>
    <xsd:attribute name="certificateCode" type="at:certificateCode"/>

    <xsd:attribute name="dutyExpressionId" type="at:dutyExpressionId"/>
    <xsd:attribute name="dutyAmountApplicabilityCode" type="at:dutyAmountApplicabilityCode"/>
    <xsd:attribute name="measurementUnitApplicabilityCode" type="at:measurementUnitApplicabilityCode"/>
    <xsd:attribute name="monetaryUnitApplicabilityCode" type="at:monetaryUnitApplicabilityCode"/>


    <xsd:attribute name="measureTypeSeriesId" type="at:measureTypeSeriesId"/>
    <xsd:attribute name="measureTypeCombination" type="at:measureTypeCombination"/>
    <xsd:attribute name="regulationGroup" type="at:regulationGroup"/>
    <xsd:attribute name="codeType" type="at:publicationSigle_CodeType"/>
    <xsd:attribute name="code" type="at:publicationSigle_Code"/>
    <xsd:attribute name="publicationCode" type="at:publicationCode"/>
    <xsd:attribute name="publicationSigle" type="at:publicationSigle"/>
    <xsd:attribute name="measurementUnitCode" type="at:measurementUnitCode"/>
    <xsd:attribute name="measurementUnitQualifierCode" type="at:measurementUnitQualifierCode"/>
    <xsd:attribute name="measurementType" type="at:measurementType"/>
    <xsd:attribute name="measurementUnitDeclarationCode" type="at:measurementUnitDeclarationCode"/>
    <xsd:attribute name="isReference" type="at:isReference"/>
    <xsd:attribute name="scaleToReference" type="at:scaleToReference"/>
    <xsd:attribute name="measurementSeparator" type="at:measurementSeparator"/>
    <xsd:attribute name="measurementSeparatorOrder" type="at:measurementSeparatorOrder"/>
    <xsd:attribute name="monetaryUnitCode" type="at:monetaryUnitCode"/>
    <xsd:attribute name="measureType" type="at:measureType"/>
    <xsd:attribute name="tradeMovementCode" type="at:tradeMovementCode"/>
    <xsd:attribute name="priorityCode" type="at:priorityCode"/>
    <xsd:attribute name="measureComponentApplicableCode" type="at:measureComponentApplicableCode"/>
    <xsd:attribute name="originDestinationCode" type="at:originDestinationCode"/>
    <xsd:attribute name="orderNumberCaptureCode" type="at:orderNumberCaptureCode"/>
    <xsd:attribute name="explosionLevel" type="at:explosionLevel"/>
    <xsd:attribute name="geographicalAreaId" type="at:geographicalAreaId"/>
    <xsd:attribute name="geographicalAreaCode" type="at:geographicalAreaCode"/>
    <xsd:attribute name="datePublished" type="xsd:date"/>
    <xsd:attribute name="dateAbrogation" type="xsd:date"/>
    <xsd:attribute name="officialJournalId" type="at:journalId"/>
    <xsd:attribute name="journalPage" type="at:journalPage"/>
    <xsd:attribute name="replacementIndicator" type="at:replacementIndicator"/>
    <xsd:attribute name="regulationApprovedFlag" type="at:regulationApprovedFlag"/>
    <xsd:attribute name="effectiveEndDate" type="xsd:date"/>
    <xsd:attribute name="communityCode" type="at:communityCode"/>
    <xsd:attribute name="url" type="at:url"/>

    <xsd:attribute name="regulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="regulationId" type="at:regulationId"/>
    <xsd:attribute name="baseRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="baseRegulationId" type="at:regulationId"/>
    <xsd:attribute name="modificationRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="modificationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="prorogationRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="prorogationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="prorogatedRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="prorogatedRegulationId" type="at:regulationId"/>
    <xsd:attribute name="dateProrogated" type="xsd:date"/>
    <xsd:attribute name="antidumpingRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="antidumpingRegulationId" type="at:regulationId"/>
    <xsd:attribute name="completeAbrogationRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="completeAbrogationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="explicitAbrogationRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="explicitAbrogationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="stoppedFlag" type="at:stoppedFlag"/>
    <xsd:attribute name="ftsRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="ftsRegulationId" type="at:regulationId"/>
    <xsd:attribute name="stoppedRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="stoppedRegulationId" type="at:regulationId"/>
    <xsd:attribute name="replacingRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="replacingRegulationId" type="at:regulationId"/>
    <xsd:attribute name="replacedRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="replacedRegulationId" type="at:regulationId"/>
    <xsd:attribute name="justificationRegulationRoleType" type="at:regulationRoleType"/>
    <xsd:attribute name="justificationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="combinedRegulationRoleType" type="at:regulationRoleType"/>

    <xsd:attribute name="expression" type="at:expression"/>

    <xsd:attribute name="chapterHeading" type="at:chapterHeading"/>
    <xsd:attribute name="headingNumber" type="at:headingNumber"/>
    <xsd:attribute name="rowColumnCode" type="at:rowColumnCode"/>
    <xsd:attribute name="subheadingSequenceNumber" type="at:subheadingSequenceNumber"/>
    <xsd:attribute name="conditionCode" type="at:conditionCode"/>
    <xsd:attribute name="conditionCodeId" type="at:conditionCodeId"/>
    <xsd:attribute name="actionCode" type="at:actionCode"/>
    <xsd:attribute name="dutyAmount" type="xsd:decimal"/>
    <xsd:attribute name="reductionIndicator" type="at:reductionIndicator"/>
    <xsd:attribute name="quotaOrderNumber" type="at:quotaOrderNumber"/>
    <xsd:attribute name="volume" type="xsd:decimal"/>
    <xsd:attribute name="initialVolume" type="xsd:decimal"/>
    <xsd:attribute name="quotaMaximumPrecision" type="xsd:integer"/>
    <xsd:attribute name="quotaCriticalStateCode" type="at:quotaCriticalStateCode"/>
    <xsd:attribute name="quotaCriticalThreshold" type="xsd:integer"/>
    <xsd:attribute name="relationType" type="at:relationType"/>
    <xsd:attribute name="coefficient" type="xsd:decimal"/>
    <xsd:attribute name="blockingPeriodType" type="xsd:integer"/>
    <xsd:attribute name="occurrenceTimestamp" type="xsd:dateTime"/>
    <xsd:attribute name="endOccurrenceTimestamp" type="xsd:dateTime"/>
    <xsd:attribute name="lastImportDate" type="xsd:date"/>
    <xsd:attribute name="unblockingDate" type="xsd:date"/>
    <xsd:attribute name="criticalDate" type="xsd:date"/>
    <xsd:attribute name="exhaustionDate" type="xsd:date"/>
    <xsd:attribute name="reopeningDate" type="xsd:date"/>
    <xsd:attribute name="unsuspensionDate" type="xsd:date"/>
    <xsd:attribute name="closingDate" type="xsd:date"/>
    <xsd:attribute name="oldBalance" type="xsd:decimal"/>
    <xsd:attribute name="newBalance" type="xsd:decimal"/>
    <xsd:attribute name="importedAmount" type="xsd:decimal"/>
    <xsd:attribute name="transferredAmount" type="xsd:decimal"/>
    <xsd:attribute name="surveillanceNumber" type="at:surveillanceNumber"/>
    <xsd:attribute name="dateCeilingReached" type="xsd:date"/>

    <xsd:attribute name="goodsNomenclatureCode" type="at:goodsNomenclatureCode"/>
    <xsd:attribute name="exportRefundCode" type="at:additionalCodeId"/>
    <xsd:attribute name="productLineSuffix" type="at:productLineSuffix"/>

    <xsd:attribute name="goodsNomenclatureGroupType" type="at:goodsNomenclatureGroupType"/>
    <xsd:attribute name="goodsNomenclatureGroupId" type="at:goodsNomenclatureGroupId"/>
    <xsd:attribute name="nomenclatureGroupFacilityCode" type="at:nomenclatureGroupFacilityCode"/>

    <xsd:attribute name="originGoodsNomenclatureCode" type="at:goodsNomenclatureCode"/>
    <xsd:attribute name="originProductLine" type="at:productLineSuffix"/>
    <xsd:attribute name="successorGoodsNomenclatureCode" type="at:goodsNomenclatureCode"/>
    <xsd:attribute name="successorProductLine" type="at:productLineSuffix"/>
    <xsd:attribute name="statisticalIndicator" type="at:statisticalLineCode"/>
    <xsd:attribute name="quantityIndents" type="at:quantityIndents"/>

    <xsd:attribute name="sequenceNumber" type="at:sequenceNumber"/>
    <xsd:attribute name="amount" type="xsd:decimal"/>
    <xsd:attribute name="abrogationRegulationId" type="at:regulationId"/>
    <xsd:attribute name="abrogationOfficialJournalId" type="at:journalId"/>
    <xsd:attribute name="abrogationJournalPage" type="at:journalPage"/>
    <xsd:attribute name="monetaryConversionRate" type="xsd:decimal"/>

    <xsd:attribute name="hiddenQuerySystemDB" type="at:hiddenQuerySystemDB"/>
    <xsd:attribute name="hiddenDeclarationSystemDB" type="at:hiddenDeclarationSystemDB"/>

    <xsd:attribute name="balance" type="xsd:decimal"/>
	<xsd:attribute name="lastAllocationDate" type="xsd:date" />
	<xsd:attribute name="allocatedPercentage" type="xsd:string"/>
	<xsd:attribute name="quotaExhaustionStateCode" type="at:quotaExhaustionStateCode"/>
	<xsd:attribute name="quotaBlockedStateCode" type="at:quotaBlockedStateCode"/>
	<xsd:attribute name="quotaSuspendedStateCode" type="at:quotaSuspendedStateCode"/>
	<xsd:attribute name="totalAwaitingAllocation"  type="xsd:decimal"/>
	<xsd:attribute name="nationalDB" type="at:national"/>
	<xsd:attribute name="taxCode" type="xsd:string"/>
	<xsd:attribute name="prefCode" type="xsd:string"/>
	<xsd:attribute name="calculationUnit" type="xsd:long"/>
    <xsd:attribute name="notified" type="xsd:int"/>
    <xsd:attribute name="reliefCodeType" type="xsd:string"/>
    <xsd:attribute name="reliefCode" type="xsd:string"/>
    <xsd:attribute name="SIDReliefCode" type="at:SID"/>
    <xsd:attribute name="SIDReliefCodeDescriptionPeriod" type="at:SID"/>
    <xsd:attribute name="tableId" type="xsd:string"/>
    <xsd:attribute name="minInterval" type="xsd:decimal"/>
    <xsd:attribute name="maxInterval" type="xsd:decimal"/>
	<xsd:attribute name="interpolate" type="xsd:boolean"/>
	<xsd:attribute name="threshold" type="xsd:decimal"/>
	<xsd:attribute name="value" type="xsd:decimal"/>
	<xsd:attribute name="state" type="xsd:int"/>
	<xsd:attribute name="insertDate" type="xsd:date"/>
    <xsd:attribute name="updateDate" type="xsd:date"/>
    <xsd:attribute name="incorrectData" type="xsd:boolean"/>
    <xsd:attribute name="commodityCode12" type="at:goodsNomenclatureCode_2"/>
    <xsd:attribute name="commodityCode34" type="at:goodsNomenclatureCode_2"/>
    <xsd:attribute name="commodityCode56" type="at:goodsNomenclatureCode_2"/>
    <xsd:attribute name="commodityCode78" type="at:goodsNomenclatureCode_2"/>
    <xsd:attribute name="commodityCode90" type="at:goodsNomenclatureCode_2"/>


</xsd:schema>
