//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.MasterFiles.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoGlbStaffEntitlement : EnterpriseBusinessObject, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "GlbStaffEntitlement";
			public const string PK        = "GSI_PK";

			public const string GSI_Comment               = "GSI_Comment";
			public const string GSI_EntitlementCode       = "GSI_EntitlementCode";
			public const string GSI_Frequency             = "GSI_Frequency";
			public const string GSI_GEG_Breakdown         = "GSI_GEG_Breakdown";
			public const string GSI_GrantDate             = "GSI_GrantDate";
			public const string GSI_GSR_Remuneration      = "GSI_GSR_Remuneration";
			public const string GSI_IsFTEScalable         = "GSI_IsFTEScalable";
			public const string GSI_IsPartOfPackage       = "GSI_IsPartOfPackage";
			public const string GSI_SystemCreateTimeUtc   = "GSI_SystemCreateTimeUtc";
			public const string GSI_SystemCreateUser      = "GSI_SystemCreateUser";
			public const string GSI_SystemLastEditTimeUtc = "GSI_SystemLastEditTimeUtc";
			public const string GSI_SystemLastEditUser    = "GSI_SystemLastEditUser";
			public const string GSI_Value                 = "GSI_Value";

			public const int GSI_CommentMaxLength = 255;
			public const int GSI_EntitlementCodeMaxLength = 3;
			public const int GSI_FrequencyMaxLength = 3;
			public const int GSI_SystemCreateUserMaxLength = 3;
			public const int GSI_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoGlbStaffEntitlement(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSI_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSI_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSI_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSI_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return GlbStaffEntitlementSchema.PK; }
		}

		#endregion

		#region Properties

		#region GSI_Comment

		public virtual ZString GSI_Comment
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_Comment)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSI_CommentInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_Comment();
				}
			}
		}

		public virtual ZPropertyInfo GSI_CommentInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_Comment); }
		}

		#endregion

		#region GSI_EntitlementCode

		public virtual ZString GSI_EntitlementCode
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_EntitlementCode)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSI_EntitlementCodeInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_EntitlementCode();
				}
			}
		}

		public virtual ZPropertyInfo GSI_EntitlementCodeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_EntitlementCode); }
		}

		#endregion

		#region GSI_Frequency

		public virtual ZString GSI_Frequency
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_Frequency)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSI_FrequencyInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_Frequency();
				}
			}
		}

		public virtual ZPropertyInfo GSI_FrequencyInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_Frequency); }
		}

		#endregion

		#region GSI_GEG_Breakdown

		public virtual ZGuid GSI_GEG_Breakdown
		{
			get {  return new ZGuid(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_GEG_Breakdown)); }
			set
			{
				SetPropertyValue(GSI_GEG_BreakdownInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_GEG_Breakdown();
				}
			}
		}

		public virtual ZPropertyInfo GSI_GEG_BreakdownInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_GEG_Breakdown); }
		}

		#endregion

		#region GSI_GrantDate

		public virtual ZDate GSI_GrantDate
		{
			get {  return new ZDate(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_GrantDate), DateTimeKind.Local); }
			set
			{
				SetPropertyValue(GSI_GrantDateInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_GrantDate();
				}
			}
		}

		public virtual ZPropertyInfo GSI_GrantDateInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_GrantDate); }
		}

		#endregion

		#region GSI_GSR_Remuneration

		public virtual ZGuid GSI_GSR_Remuneration
		{
			get {  return new ZGuid(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_GSR_Remuneration)); }
			set
			{
				SetPropertyValue(GSI_GSR_RemunerationInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_GSR_Remuneration();
				}
			}
		}

		public virtual ZPropertyInfo GSI_GSR_RemunerationInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_GSR_Remuneration); }
		}

		#endregion

		#region GSI_IsFTEScalable

		public virtual ZBool GSI_IsFTEScalable
		{
			get {  return new ZBool(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_IsFTEScalable)); }
			set
			{
				SetPropertyValue(GSI_IsFTEScalableInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_IsFTEScalable();
				}
			}
		}

		public virtual ZPropertyInfo GSI_IsFTEScalableInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_IsFTEScalable); }
		}

		#endregion

		#region GSI_IsPartOfPackage

		public virtual ZBool GSI_IsPartOfPackage
		{
			get {  return new ZBool(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_IsPartOfPackage)); }
			set
			{
				SetPropertyValue(GSI_IsPartOfPackageInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_IsPartOfPackage();
				}
			}
		}

		public virtual ZPropertyInfo GSI_IsPartOfPackageInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_IsPartOfPackage); }
		}

		#endregion

		#region GSI_SystemCreateTimeUtc

		public virtual ZDateTime GSI_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(GSI_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo GSI_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_SystemCreateTimeUtc); }
		}

		#endregion

		#region GSI_SystemCreateUser

		public virtual ZString GSI_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSI_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo GSI_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_SystemCreateUser); }
		}

		#endregion

		#region GSI_SystemLastEditTimeUtc

		public virtual ZDateTime GSI_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(GSI_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo GSI_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_SystemLastEditTimeUtc); }
		}

		#endregion

		#region GSI_SystemLastEditUser

		public virtual ZString GSI_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSI_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo GSI_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_SystemLastEditUser); }
		}

		#endregion

		#region GSI_Value

		public virtual ZDecimal GSI_Value
		{
			get {  return new ZDecimal(GetValueFromRowSafely(GlbStaffEntitlementSchema.GSI_Value)); }
			set
			{
				SetPropertyValue(GSI_ValueInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSI_Value();
				}
			}
		}

		public virtual ZPropertyInfo GSI_ValueInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffEntitlementSchema.Constants.GSI_Value); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[GlbStaffEntitlementSchema.Constants.GSI_Comment              ] = "";
			row[GlbStaffEntitlementSchema.Constants.GSI_EntitlementCode      ] = "";
			row[GlbStaffEntitlementSchema.Constants.GSI_Frequency            ] = "YRL";
			row[GlbStaffEntitlementSchema.Constants.GSI_GEG_Breakdown        ] = DBNull.Value;
			row[GlbStaffEntitlementSchema.Constants.GSI_GrantDate            ] = DBNull.Value;
			row[GlbStaffEntitlementSchema.Constants.GSI_GSR_Remuneration     ] = Guid.Empty;
			row[GlbStaffEntitlementSchema.Constants.GSI_IsFTEScalable        ] = false;
			row[GlbStaffEntitlementSchema.Constants.GSI_IsPartOfPackage      ] = true;
			row[GlbStaffEntitlementSchema.Constants.GSI_SystemCreateTimeUtc  ] = DBNull.Value;
			row[GlbStaffEntitlementSchema.Constants.GSI_SystemCreateUser     ] = "";
			row[GlbStaffEntitlementSchema.Constants.GSI_SystemLastEditTimeUtc] = DBNull.Value;
			row[GlbStaffEntitlementSchema.Constants.GSI_SystemLastEditUser   ] = "";
			row[GlbStaffEntitlementSchema.Constants.GSI_Value                ] = (decimal)0;
		}

		#endregion

		#region Lookups

		public GlbStaffEntitlementLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual GlbStaffEntitlementLookups GetNewLookups()
		{
			return new GlbStaffEntitlementLookups(this);
		}

		GlbStaffEntitlementLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public GlbStaffEntitlementValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual GlbStaffEntitlementValidation GetNewValidation()
		{
			return new GlbStaffEntitlementValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return GSI_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return GSI_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return GSI_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return GSI_SystemLastEditUser; }
		}

		#endregion
	}
}
