<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.wisetechglobal.com/EnterpriseService/" xmlns="http://www.wisetechglobal.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema"  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="OrgStatus">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Valid"/>
              <xs:enumeration value="Invalid"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="ErrorLog">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="ErrorItem" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="WarningLog">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="WarningItem" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>