namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.Output
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[OutputBlock("U4")]
	public partial class ENSU4 : MessageBlock
	{
		public ENSU4()
			: base("U4")
		{
		}

		/// <summary>
		/// Continuation of comments which began on Record Identifier U3.
		/// </summary>
		[MessageBlockString(74, 3, "M")]
		public ZString RejectComments;
	}
}
