<Project>
  <ItemGroup>
    <Reference Include="AppDomainWrappers.Net" />
    <Reference Include="CargoWise.BrandManager" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="WTG.SpellCheck" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>