<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.FRReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.FRReferenceData.Business</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <Configurations>Debug;Release;UAT</Configurations>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.FRReferenceData.Services">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.FRReferenceData.Services.dll</HintPath>
    </Reference>
     <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>