<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.EUReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.EUReferenceData.Business</AssemblyName>
    <Configurations>Debug;Release;UAT</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <OutputPath>..\..\..\bin\UniversalXMLProducers</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.UniversalXMLProducers.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.UniversalXMLProducers.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <ProjectReference Include="..\EUReferenceData.Services\EUReferenceData.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AdditionalTranslations\IT.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>