<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.FaxRouter.MailSecurity.Test</AssemblyName>
    <RootNamespace>Enterprise.FaxRouter.MailSecurity.Test</RootNamespace>
    <NoWarn>$(NoWarn);SA1011;SA1000</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MailSecurity\MailSecurity.csproj" />
  </ItemGroup>
</Project>