//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CargoWise.RefDbRepo.Service.Schema_0_9_New;

[Table("UNDGVersion")]
[Index("DV_Name", Name = "IX_UNDGVersion_DV_Name", IsUnique = true)]
public partial class UNDGVersion
{
    [Key]
    public Guid DV_PK { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string DV_Name { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string DV_Standard { get; set; }

    [Required]
    public bool? DV_IsActive { get; set; }
}
