//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.Workflow.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0"), IsActiveProperty(UniversalValidationRuleSchema.Constants.VR_IsActive), PreventDelete(true)]
	public abstract class AutoUniversalValidationRule : EnterpriseBusinessObject, ICancellable, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "UniversalValidationRule";
			public const string PK        = "VR_PK";

			public const string VR_BusinessRule          = "VR_BusinessRule";
			public const string VR_IsActive              = "VR_IsActive";
			public const string VR_MessageLog            = "VR_MessageLog";
			public const string VR_Sequence              = "VR_Sequence";
			public const string VR_Status                = "VR_Status";
			public const string VR_SystemCreateTimeUtc   = "VR_SystemCreateTimeUtc";
			public const string VR_SystemCreateUser      = "VR_SystemCreateUser";
			public const string VR_SystemLastEditTimeUtc = "VR_SystemLastEditTimeUtc";
			public const string VR_SystemLastEditUser    = "VR_SystemLastEditUser";
			public const string VR_VRS_Parent            = "VR_VRS_Parent";

			public const int VR_BusinessRuleMaxLength = 2147483647;
			public const int VR_MessageLogMaxLength = 2048;
			public const int VR_StatusMaxLength = 3;
			public const int VR_SystemCreateUserMaxLength = 3;
			public const int VR_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoUniversalValidationRule(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(VR_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(VR_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(VR_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(VR_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return UniversalValidationRuleSchema.PK; }
		}

		#endregion

		#region Properties

		#region VR_BusinessRule

		public virtual ZString VR_BusinessRule
		{
			get { 
				EnsureBlobField(UniversalValidationRuleSchema.VR_BusinessRule);
				return new ZString(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_BusinessRule)); }

			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = VR_BusinessRuleInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_BusinessRule();
				}
			}
		}

		public virtual ZPropertyInfo VR_BusinessRuleInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_BusinessRule); }
		}

		public virtual System.IO.TextReader GetVR_BusinessRuleReader(bool closeReaderBetweenReads = false)
		{
			return Factory.GetTextFieldReader(this, UniversalValidationRuleSchema.VR_BusinessRule, closeReaderBetweenReads);
		}

		public virtual void SetVR_BusinessRuleSource(ITextReaderSource source)
		{
			SetSource(source, UniversalValidationRuleSchema.VR_BusinessRule);
		}

		#endregion

		#region VR_IsActive

		public virtual bool IsCancelled
		{
			get { return !VR_IsActive; }
			set { VR_IsActive = !value; }
		}

		public virtual bool IsCancelledHasChanged
		{
			get { return VR_IsActiveInfo.HasChanges; }
		}

		public virtual string CanCancel()
		{
			return null;
		}

		public virtual string CanReactivate()
		{
			return null;
		}

		public virtual ZBool VR_IsActive
		{
			get {  return new ZBool(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_IsActive)); }
			set
			{
				SetPropertyValue(VR_IsActiveInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_IsActive();
				}
			}
		}

		public virtual ZPropertyInfo VR_IsActiveInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_IsActive); }
		}

		#endregion

		#region VR_MessageLog

		public virtual ZString VR_MessageLog
		{
			get {  return new ZString(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_MessageLog)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = VR_MessageLogInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_MessageLog();
				}
			}
		}

		public virtual ZPropertyInfo VR_MessageLogInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_MessageLog); }
		}

		#endregion

		#region VR_Sequence

		public virtual ZShort VR_Sequence
		{
			get {  return new ZShort(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_Sequence)); }
			set
			{
				SetPropertyValue(VR_SequenceInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_Sequence();
				}
			}
		}

		public virtual ZPropertyInfo VR_SequenceInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_Sequence); }
		}

		#endregion

		#region VR_Status

		public virtual ZString VR_Status
		{
			get {  return new ZString(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_Status)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = VR_StatusInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_Status();
				}
			}
		}

		public virtual ZPropertyInfo VR_StatusInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_Status); }
		}

		#endregion

		#region VR_SystemCreateTimeUtc

		public virtual ZDateTime VR_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(VR_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo VR_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_SystemCreateTimeUtc); }
		}

		#endregion

		#region VR_SystemCreateUser

		public virtual ZString VR_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = VR_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo VR_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_SystemCreateUser); }
		}

		#endregion

		#region VR_SystemLastEditTimeUtc

		public virtual ZDateTime VR_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(VR_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo VR_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_SystemLastEditTimeUtc); }
		}

		#endregion

		#region VR_SystemLastEditUser

		public virtual ZString VR_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = VR_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo VR_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_SystemLastEditUser); }
		}

		#endregion

		#region VR_VRS_Parent

		public virtual ZGuid VR_VRS_Parent
		{
			get {  return new ZGuid(GetValueFromRowSafely(UniversalValidationRuleSchema.VR_VRS_Parent)); }
			set
			{
				SetPropertyValue(VR_VRS_ParentInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateVR_VRS_Parent();
				}
			}
		}

		public virtual ZPropertyInfo VR_VRS_ParentInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(UniversalValidationRuleSchema.Constants.VR_VRS_Parent); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[UniversalValidationRuleSchema.Constants.VR_BusinessRule         ] = "";
			row[UniversalValidationRuleSchema.Constants.VR_IsActive             ] = true;
			row[UniversalValidationRuleSchema.Constants.VR_MessageLog           ] = "";
			row[UniversalValidationRuleSchema.Constants.VR_Sequence             ] = (short)0;
			row[UniversalValidationRuleSchema.Constants.VR_Status               ] = "";
			row[UniversalValidationRuleSchema.Constants.VR_SystemCreateTimeUtc  ] = DBNull.Value;
			row[UniversalValidationRuleSchema.Constants.VR_SystemCreateUser     ] = "";
			row[UniversalValidationRuleSchema.Constants.VR_SystemLastEditTimeUtc] = DBNull.Value;
			row[UniversalValidationRuleSchema.Constants.VR_SystemLastEditUser   ] = "";
			row[UniversalValidationRuleSchema.Constants.VR_VRS_Parent           ] = Guid.Empty;
		}

		#endregion

		#region Lookups

		public UniversalValidationRuleLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual UniversalValidationRuleLookups GetNewLookups()
		{
			return new UniversalValidationRuleLookups(this);
		}

		UniversalValidationRuleLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public UniversalValidationRuleValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual UniversalValidationRuleValidation GetNewValidation()
		{
			return new UniversalValidationRuleValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return VR_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return VR_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return VR_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return VR_SystemLastEditUser; }
		}

		#endregion
	}
}
