<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Moq" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Winzor.Telemetry\CargoWise.Winzor.Telemetry.csproj" />
    <ProjectReference Include="..\Infrastructure\CargoWise.Blazor.Common.Data\CargoWise.Blazor.Common.Data.csproj" />
    <ProjectReference Include="..\Infrastructure\CargoWise.Blazor.Common\CargoWise.Blazor.Common.csproj" />
  </ItemGroup>

</Project>
