//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.MasterFiles.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoRefMessagingBussPackageInfoAttribute : EnterpriseBusinessObject
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "RefDatabase_RefMessagingBussPackageInfoAttribute";
			public const string PK        = "ZPA_PK";

			public const string ZPA_AttributeValue    = "ZPA_AttributeValue";
			public const string ZPA_ZAI_AttributeInfo = "ZPA_ZAI_AttributeInfo";
			public const string ZPA_ZMP_PackageInfo   = "ZPA_ZMP_PackageInfo";

			public const int ZPA_AttributeValueMaxLength = 200;
		}

		#endregion

		protected AutoRefMessagingBussPackageInfoAttribute(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return RefMessagingBussPackageInfoAttributeSchema.PK; }
		}

		#endregion

		#region Properties

		#region ZPA_AttributeValue

		public virtual ZString ZPA_AttributeValue
		{
			get {  return new ZString(GetValueFromRowSafely(RefMessagingBussPackageInfoAttributeSchema.ZPA_AttributeValue)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = ZPA_AttributeValueInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZPA_AttributeValue();
				}
			}
		}

		public virtual ZPropertyInfo ZPA_AttributeValueInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_AttributeValue); }
		}

		#endregion

		#region ZPA_ZAI_AttributeInfo

		public virtual ZGuid ZPA_ZAI_AttributeInfo
		{
			get {  return new ZGuid(GetValueFromRowSafely(RefMessagingBussPackageInfoAttributeSchema.ZPA_ZAI_AttributeInfo)); }
			set
			{
				SetPropertyValue(ZPA_ZAI_AttributeInfoInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZPA_ZAI_AttributeInfo();
				}
			}
		}

		public virtual ZPropertyInfo ZPA_ZAI_AttributeInfoInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_ZAI_AttributeInfo); }
		}

		#endregion

		#region ZPA_ZMP_PackageInfo

		public virtual ZGuid ZPA_ZMP_PackageInfo
		{
			get {  return new ZGuid(GetValueFromRowSafely(RefMessagingBussPackageInfoAttributeSchema.ZPA_ZMP_PackageInfo)); }
			set
			{
				SetPropertyValue(ZPA_ZMP_PackageInfoInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZPA_ZMP_PackageInfo();
				}
			}
		}

		public virtual ZPropertyInfo ZPA_ZMP_PackageInfoInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_ZMP_PackageInfo); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_AttributeValue   ] = "";
			row[RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_ZAI_AttributeInfo] = Guid.Empty;
			row[RefMessagingBussPackageInfoAttributeSchema.Constants.ZPA_ZMP_PackageInfo  ] = Guid.Empty;
		}

		#endregion

		#region Lookups

		public RefMessagingBussPackageInfoAttributeLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual RefMessagingBussPackageInfoAttributeLookups GetNewLookups()
		{
			return new RefMessagingBussPackageInfoAttributeLookups(this);
		}

		RefMessagingBussPackageInfoAttributeLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public RefMessagingBussPackageInfoAttributeValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual RefMessagingBussPackageInfoAttributeValidation GetNewValidation()
		{
			return new RefMessagingBussPackageInfoAttributeValidation(this);
		}

		#endregion
	}
}
