<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	id="LicenceOnDemandLogSchema"
	targetNamespace="http://www.edi.com.au/EnterpriseService"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
  <xs:element name="LicenceConsumptionLogSchema" >
    <xs:complexType>
      <xs:sequence>
        <!-- Indicates this is in response to a resend request, as opposed to a regular automatic report -->
        <xs:element name="IsRequest" type="xs:boolean" minOccurs="0"/>
        
        <!-- Requesting user -->
        <xs:element name="RequestedBy" type="xs:string" minOccurs="0"/>
        
        <xs:element name="DateFrom" type="xs:date" minOccurs="0"/>
        <xs:element name="DateTo" type="xs:date" minOccurs="0"/>

        <xs:element name="EnterpriseCode" type="xs:string" minOccurs="0"/>
        <xs:element name="ServerCode" type="xs:string" minOccurs="0"/>
        <xs:element name="DbServerName" type="xs:string" minOccurs="0"/>
        <xs:element name="DbName" type="xs:string" minOccurs="0"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element name="LicenceConsumptionLogs">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="ErrorStatus" type="xs:string" minOccurs="0" />
                <xs:element name="LicenceModuleCode" type="xs:string" minOccurs="0" />
                <xs:element name="StaffName" type="xs:string" minOccurs="0" />
                <xs:element name="StaffEmail" type="xs:string" minOccurs="0" />
                <xs:element name="UsageTime" type="xs:dateTime" minOccurs="0" />
                <xs:element name="CompanyLicenceCode" type="xs:string" minOccurs="0" />
                <xs:element name="LicenceType" type="xs:string" minOccurs="0" />
                <xs:element name="StaffCode" type="xs:string" minOccurs="0" />
                <xs:element name="BranchCode" type="xs:string" minOccurs="0" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>