//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Universal
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoRefCusNomenclatureGroupNoteValidation : ZValidation
	{
		protected AutoRefCusNomenclatureGroupNoteValidation(AutoRefCusNomenclatureGroupNote Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoRefCusNomenclatureGroupNoteValidation); }
		}

		/// <summary>
		/// Add more validation to the RefCusNomenclatureGroupNote's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoRefCusNomenclatureGroupNoteValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The RefCusNomenclatureGroupNote's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoRefCusNomenclatureGroupNoteValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region ZZL_Note

		public void ValidateZZL_Note()
		{
			ZValidationInternals.Validate(Parent.ZZL_NoteInfo, GetZZL_NoteValidationInvoker());
		}

		RunValidationInvoker GetZZL_NoteValidationInvoker()
		{
			return delegate
			{
				CheckZZL_NoteIsNotEmpty();
				CheckZZL_Note();
			};
		}

		protected virtual void CheckZZL_NoteIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZL_NoteInfo);
		}

		protected virtual void CheckZZL_Note()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZL_NoteType

		public void ValidateZZL_NoteType()
		{
			ZValidationInternals.Validate(Parent.ZZL_NoteTypeInfo, GetZZL_NoteTypeValidationInvoker());
		}

		RunValidationInvoker GetZZL_NoteTypeValidationInvoker()
		{
			return delegate
			{
				CheckZZL_NoteTypeIsNotEmpty();
				CheckZZL_NoteTypeIsWesternEuropean();
				CheckZZL_NoteType();
			};
		}

		protected virtual void CheckZZL_NoteTypeIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZL_NoteTypeInfo);
		}

		protected virtual void CheckZZL_NoteTypeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZL_NoteTypeInfo);
		}

		protected virtual void CheckZZL_NoteType()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZL_ZX6_NKLanguage

		public void ValidateZZL_ZX6_NKLanguage()
		{
			ZValidationInternals.Validate(Parent.ZZL_ZX6_NKLanguageInfo, GetZZL_ZX6_NKLanguageValidationInvoker());
		}

		RunValidationInvoker GetZZL_ZX6_NKLanguageValidationInvoker()
		{
			return delegate
			{
				CheckZZL_ZX6_NKLanguageIsNotEmpty();
				CheckZZL_ZX6_NKLanguageIsWesternEuropean();
				CheckZZL_ZX6_NKLanguage();
			};
		}

		protected virtual void CheckZZL_ZX6_NKLanguageIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZL_ZX6_NKLanguageInfo);
		}

		protected virtual void CheckZZL_ZX6_NKLanguageIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZL_ZX6_NKLanguageInfo);
		}

		protected virtual void CheckZZL_ZX6_NKLanguage()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZL_ZZ5_NomenclatureGroup

		public void ValidateZZL_ZZ5_NomenclatureGroup()
		{
			ZValidationInternals.Validate(Parent.ZZL_ZZ5_NomenclatureGroupInfo, GetZZL_ZZ5_NomenclatureGroupValidationInvoker());
		}

		RunValidationInvoker GetZZL_ZZ5_NomenclatureGroupValidationInvoker()
		{
			return delegate
			{
				CheckZZL_ZZ5_NomenclatureGroupIsNotEmpty();
				CheckZZL_ZZ5_NomenclatureGroupIsValidZGuid();
				CheckZZL_ZZ5_NomenclatureGroup();
			};
		}

		protected virtual void CheckZZL_ZZ5_NomenclatureGroupIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.ZZL_ZZ5_NomenclatureGroupInfo);
		}

		protected virtual void CheckZZL_ZZ5_NomenclatureGroupIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZL_ZZ5_NomenclatureGroupInfo);
		}

		protected virtual void CheckZZL_ZZ5_NomenclatureGroup()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZL_ZZZ_NKDataGrouping

		public void ValidateZZL_ZZZ_NKDataGrouping()
		{
			ZValidationInternals.Validate(Parent.ZZL_ZZZ_NKDataGroupingInfo, GetZZL_ZZZ_NKDataGroupingValidationInvoker());
		}

		RunValidationInvoker GetZZL_ZZZ_NKDataGroupingValidationInvoker()
		{
			return delegate
			{
				CheckZZL_ZZZ_NKDataGroupingIsNotEmpty();
				CheckZZL_ZZZ_NKDataGroupingIsWesternEuropean();
				CheckZZL_ZZZ_NKDataGrouping();
			};
		}

		protected virtual void CheckZZL_ZZZ_NKDataGroupingIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZL_ZZZ_NKDataGroupingInfo);
		}

		protected virtual void CheckZZL_ZZZ_NKDataGroupingIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZL_ZZZ_NKDataGroupingInfo);
		}

		protected virtual void CheckZZL_ZZZ_NKDataGrouping()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateZZL_Note();
				ValidateZZL_NoteType();
				ValidateZZL_ZX6_NKLanguage();
				ValidateZZL_ZZ5_NomenclatureGroup();
				ValidateZZL_ZZZ_NKDataGrouping();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoRefCusNomenclatureGroupNote Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
