<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.UniversalXMLProducers.ZANomenclatureGroupProducer.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.UniversalXMLProducers.ZANomenclatureGroupProducer.Test</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.XmlProducer.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.XmlProducer.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <ProjectReference Include="..\ZANomenclatureGroupProducer\ZANomenclatureGroupProducer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Samples\2022modelv7.pdf" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>