<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Edifact" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.US.Business" />
    <Reference Include="Enterprise.Customs.US.DataTransfer" />
    <Reference Include="Enterprise.Customs.US.ISF.Business" />
    <Reference Include="Enterprise.Customs.US.Messaging.Business" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Edifact.D95B" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.eTail.Integration" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Agency.Business" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BusinessObject\CusCodeData\IssuerAndBillOfLading\IssuerAndBillOfLadingStatusList.cs">
      <DependentUpon>IssuerAndBillOfLadingStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\MessageSendingAction\AutoMessageSendingAction.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoMessageSendingAction.xml</DependentUpon>
    </Compile>
    <Compile Update="BusinessObject\MessageSendingAction\MessageSendingBill\AutoMessageSendingObject.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoMessageSendingObject.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\STWIssueFilterList.cs">
      <DependentUpon>STWIssueFilterList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\DirectionTypeList.cs">
      <DependentUpon>DirectionTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="StowPlan\DataObjects\AutoStowPlanContainerData.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoStowPlanContainerData.xml</DependentUpon>
    </Compile>
    <Compile Update="StowPlan\DataObjects\AutoStowPlanSailingData.cs">
      <DependentUpon>AutoStowPlanSailingData.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="StowPlan\DataObjects\AutoStowPlanVesselData.cs">
      <DependentUpon>AutoStowPlanVesselData.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="StowPlan\DataObjects\AutoStowPlanShipmentData.cs">
      <DependentUpon>AutoStowPlanShipmentData.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="StowPlan\DataObjects\AutoStowPlanContainerStockData.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoStowPlanContainerStockData.xml</DependentUpon>
    </Compile>
    <Compile Update="StowPlan\MessageHost\AutoVoyagePort.cs">
      <DependentUpon>AutoVoyagePort.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ContainerLoadConditionStatusList.cs">
      <DependentUpon>ContainerLoadConditionStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\CommunicationsNumberQualifierList.cs">
      <DependentUpon>CommunicationsNumberQualifierList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ManifestUnitList.cs">
      <DependentUpon>ManifestUnitList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ServiceTypeList.cs">
      <DependentUpon>ServiceTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ModeTypeList.cs">
      <DependentUpon>ModeTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ExportTypeList.cs">
      <DependentUpon>ExportTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TransportTypeList.cs">
      <DependentUpon>TransportTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\PaymentMethodCodeList.cs">
      <DependentUpon>PaymentMethodCodeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\WeightUnitList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>WeightUnitList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\VolumeUnitList.cs">
      <DependentUpon>VolumeUnitList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.US.AMS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="BusinessObject\CusCodeData\IssuerAndBillOfLading\IssuerAndBillOfLadingStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>IssuerAndBillOfLadingStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\MessageSendingAction\AutoMessageSendingAction.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoMessageSendingAction.cs</LastGenOutput>
    </None>
    <None Update="BusinessObject\MessageSendingAction\MessageSendingBill\AutoMessageSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoMessageSendingObject.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\STWIssueFilterList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>STWIssueFilterList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\DirectionTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DirectionTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="StowPlan\DataObjects\AutoStowPlanContainerData.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoStowPlanContainerData.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ContainerLoadConditionStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ContainerLoadConditionStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\CommunicationsNumberQualifierList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CommunicationsNumberQualifierList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ManifestUnitList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ManifestUnitList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ServiceTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ServiceTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ModeTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ModeTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ExportTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ExportTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\TransportTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransportTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\PaymentMethodCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PaymentMethodCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\WeightUnitList.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>WeightUnitList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\VolumeUnitList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>VolumeUnitList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="StowPlan\DataObjects\AutoStowPlanSailingData.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoStowPlanSailingData.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="StowPlan\DataObjects\AutoStowPlanVesselData.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoStowPlanVesselData.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="StowPlan\DataObjects\AutoStowPlanShipmentData.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoStowPlanShipmentData.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
    <None Update="StowPlan\DataObjects\AutoStowPlanContainerStockData.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoStowPlanContainerStockData.cs</LastGenOutput>
    </None>
    <None Update="StowPlan\MessageHost\AutoVoyagePort.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoVoyagePort.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AMS.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
