<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.NO.Manifest.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.NO.Manifest.Business</AssemblyName>
    <CWEnableIsExternalInitForNetFrameworkOnly>true</CWEnableIsExternalInitForNetFrameworkOnly>
    <!--
      This is a workaround and should be removed when no longer needed
      Error: The "SubModuleGeneratorTask" task was not given a value for the required parameter "ProjectPath".
      See: https://teams.microsoft.com/l/message/19:9ebf2b2fa75e4a728d27674ca62554b8@thread.skype/1745407269951?tenantId=8b493985-e1b4-4b95-ade6-98acafdbdb01&groupId=c9fbec07-f470-451e-a107-255c9b777d30&parentMessageId=1745378044994&teamName=Product-Development%20(all%20staff)&channelName=General&createdTime=1745407269951
    -->
    <ProjectDir>$(MSBuildProjectDirectory)</ProjectDir>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.NO.Business" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.xTMessaging.Business" />
    <Reference Include="Enterprise.xTMessaging.Shared" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\NODMOEDIMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NODMOEDIMessageTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NODMOInterchangeTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NODMOInterchangeTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NODMOMessageFunctionList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NODMOMessageFunctionList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NOExportProcedureCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NOExportProcedureCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NOImportProcedureCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NOImportProcedureCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NOManifestTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NOManifestTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NOManifestTypes_Partial.cs">
      <DependentUpon>NOManifestTypes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\NODMOEDIMessageTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NODMOEDIMessageTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NODMOInterchangeTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NODMOInterchangeTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NODMOMessageFunctionList.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NODMOMessageFunctionList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NOExportProcedureCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NOExportProcedureCodeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NOImportProcedureCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NOImportProcedureCodeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NOManifestTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.NO.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NOManifestTypes.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>