// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:39,16
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:40,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:41,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:42,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:43,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:44,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.GUI.Testing.CLSMSMessageSendingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CL/Manifest/GUI.Test/Registry/SMS/CLSMSMessageSendingRegistryItemEditorTest.cs:45,20
