using System;
using System.Collections.Generic;
using System.Linq;
using CargoWise.Database.Abstractions;
using Enterprise.DbUpgrader.Resource.Version;
using Enterprise.DbUpgrader.Shared;
using Enterprise.DbUpgrader.Transformation.Common;
using Enterprise.DbUpgrader.Transformation.DataModification;
using Enterprise.DbUpgrader.Transformations.PreUpgrade;
using Microsoft.Extensions.DependencyInjection;

namespace Enterprise.DbUpgrader.Transformations.Transforms
{
	public interface ITransformationMappingProvider
	{
		Mapping[] GetAllMappings();
	}

	/// <summary>
	///  _____                _   _______ _     _       ______ _          _   _
	/// |  __ \              | | |__   __| |   (_)     |  ____(_)        | | | |
	/// | |__) |___  __ _  __| |    | |  | |__  _ ___  | |__   _ _ __ ___| |_| |
	/// |  _  // _ \/ _` |/ _` |    | |  | '_ \| / __| |  __| | | '__/ __| __| |
	/// | | \ \  __/ (_| | (_| |    | |  | | | | \__ \ | |    | | |  \__ \ |_|_|
	/// |_|  \_\___|\__,_|\__,_|    |_|  |_| |_|_|___/ |_|    |_|_|  |___/\__(_)
	///
	/// *******************************************************************
	/// **********      DO NOT CHANGE THIS FILE MANUALLY!!!      **********
	/// *******************************************************************
	///
	/// See ShelfCheckinMapper.txt for instructions on how to add and map
	/// new transformations according to the SHELF CHECK-IN process
	///
	/// </summary>
	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0001:SimplifyName", Justification = "DAT auto-generates some of the contents of this class")]
	public class TransformationMappingProvider : ITransformationMappingProvider
	{
		public Mapping[] GetAllMappings()
		{
			var mappings = new Mapping[] {
				//DO_NOT_CHANGE_THIS_LINE_DAT_WILL_MAP_TRANSFORMATIONS_BELOW
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RemoveWorkflowStatusUpdaterRegistryItems>(new VersionLabel(8280,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameWorkflowStatusUpdaterPrerequisiteDepthRegistryItem>(new VersionLabel(8280,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.GB.DeleteChiefServiceTasks_NES_GCP>(new VersionLabel(8279,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Gate.PopulateGteGateBranch>(new VersionLabel(8278,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.FixFDDServiceTaskConfigString>(new VersionLabel(8276,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.OrderManager.UpdateOrderIsReleasedFlagForInProgressOrders>(new VersionLabel(8275,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.UpdateNudgeableServiceTasksFromStmServiceTask>(new VersionLabel(8274,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.UpdateOptionsIfStaffIsDeviceOnly>(new VersionLabel(8273,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Documents.RemoveBarcodeReaderServiceRegistries>(new VersionLabel(8272,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.RenameGlbReleaseNoteReadColumnsTransformation>(new VersionLabel(8271,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RemoveEnableDocumentParsingRegistryData>(new VersionLabel(8270,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.AddAuditColumnsToEdiTokenAuthOnBoardingDataTransformation>(new VersionLabel(8269,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PopulateProcessHeaderJobCodeAndJobDescriptionFromJLW>(new VersionLabel(8268,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateEmptyCompanyNameToPlaceholderValueAndMakeInactive>(new VersionLabel(8266,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateAccChargeTaxOverrideTransportModeEmptyValue>(new VersionLabel(8265,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.UpdatePopulateCSI_DataModelWithCusEntryHeader>(new VersionLabel(8264,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.NZ.CopyAddInfoCountryOfExportToRealColumn>(new VersionLabel(8263,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.ComplianceRiskStatusCalculateJobEndDate>(new VersionLabel(8262,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateFCM_GG_ReleaseGroupTransform>(new VersionLabel(8261,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RenameAdvancePaymentRelatedTransactionCategoryCodesNew>(new VersionLabel(8260,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.ChangeStatusToErrorWhenProcessingTimeIsNotNullAndEndTimeIsNull>(new VersionLabel(8259,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.RemoveReviewProcessWithInvalidFilterType>(new VersionLabel(8258,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.PurgeOrphanRecordsFromTables>(new VersionLabel(8257,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.DropTVP_GeneralLedgerDataToUpdateColumnType>(new VersionLabel(8256,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.PurgeProcessHeaderOrphans>(new VersionLabel(8255,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.RemoveDuplicatedCSRForConsol>(new VersionLabel(8254,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.DenyAccessUnpublishedCustomizedDocumentsAndReportsByDefault>(new VersionLabel(8252,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.AdjustTimezoneOffsetDateReceived>(new VersionLabel(8251,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.CreateMissingTransitGuaranteeTransactions>(new VersionLabel(8250,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.RemoveEnableRevertToLastClearedDataRegistryItem>(new VersionLabel(8249,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.FixBRJobComInvoiceLineUCTemplate>(new VersionLabel(8248,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.FixBRInvoiceLineDIWTemplate>(new VersionLabel(8248,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.UpdateInvalidYardUnitStateByUnloadTimeAndLoadTimeChecks>(new VersionLabel(8247,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.PopulateCXH_ApplicationCode>(new VersionLabel(8245,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToRateEntryParentTableCode_Online>(new VersionLabel(8244,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.SetContainerWeightLimitTypeToAdjustedCodes>(new VersionLabel(8243,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Gate.PopulateGateVehicleMovementMainBooking>(new VersionLabel(8242,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateBECustomsRegistryNumberFountainDataTransformation>(new VersionLabel(8241,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateRegistryKeyItemsFromSection321ToLowValueEntries>(new VersionLabel(8240,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.RenameCE_EntryStatusFromNOTToNCNForICS2AsycudaManifestHeader>(new VersionLabel(8239,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateNullE6_ParentIDToEmptyForJobConsolCost>(new VersionLabel(8238,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.PurgeOrphanRecordsFromTablesSecondVersion>(new VersionLabel(8237,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateGlbSecurityForAllowFeatureEditForAnyReleaseGroupCheckPointTransform>(new VersionLabel(8236,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.GB.EnableAllApplicationsToExistingTokens>(new VersionLabel(8235,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsDocketUnloadCompletedTime>(new VersionLabel(8234,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.DeleteArchiveRelationshipRows>(new VersionLabel(8232,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateCABServiceTaskDescription>(new VersionLabel(8231,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PopulateProcessHeaderEffectiveAgreedDeliveryDate>(new VersionLabel(8230,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.UpdateIncorrectOpportunityProfitFieldsToRevenue>(new VersionLabel(8229,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.PopulateJE_ValuationDateForCADDeclarations>(new VersionLabel(8227,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.DE.MoveAddInfoCusEntryInstructionToCusGoodsLocation>(new VersionLabel(8226,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.NZ.UpdateJEContainerModeForNZ>(new VersionLabel(8225,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.ConvertTransportStatusErrorToActionRequired>(new VersionLabel(8224,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.FixUcTransformationEncoding>(new VersionLabel(8223,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.RemoveGlowCommunicationStatusRegistryItem>(new VersionLabel(8222,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.DeleteDuplicateDataForAccPeriodManagementWithCompanyStartDateAndEndDate>(new VersionLabel(8221,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.SetJLT_MethodOfCalculationAndClearJLT_RateOverrideReasonCode>(new VersionLabel(8220,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.UpdateCOEEventIsCustomizableProperty>(new VersionLabel(8219,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdateBM_GONumberForNC5ArrivalMovementHeaderIfSimplified>(new VersionLabel(8218,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Warehouse.RemoveEnableDockDoorAssignmentServiceRegistryItem>(new VersionLabel(8217,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Scim.RemoveExternalIdForSystemGroups>(new VersionLabel(8216,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.HRMS.CopyCurrentWorkPatternTimes>(new VersionLabel(8215,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.HRMS.SynchroniseEmploymentHistoryJobTitle>(new VersionLabel(8215,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.HRMS.SynchroniseStaffWorkingBasis>(new VersionLabel(8215,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.DeleteEmptyReferenceNumberAddOnValue>(new VersionLabel(8214,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.ZA.MoveJobComInvoiceLineVehicleAddInfosToCusVehicle2>(new VersionLabel(8213,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdateBM_GrossWeightUQToKilograms>(new VersionLabel(8212,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdateB0_WeightUQToKilograms>(new VersionLabel(8212,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.PopulateDIQuantityClassification>(new VersionLabel(8211,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RenameIdPUserManagementTimeoutInSecondsRegistryDataTransformation>(new VersionLabel(8210,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RemoveIdPUserManagementEndpointConfigRegistryDataTransformation>(new VersionLabel(8210,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.FixWronglyDeactivatedContacts>(new VersionLabel(8209,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.PopulateCusEntryHeaderChargesThroughCADResponse>(new VersionLabel(8207,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.PopulateCRLActionAndENSAction>(new VersionLabel(8206,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.NZ.UpdateContainerModeForNZAirJobDeclaration>(new VersionLabel(8205,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateARTMetricCount>(new VersionLabel(8204,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.CopyCommodityRiskCheckBypassFeatureToCommodityRiskAssessmentDecisionRegistryItem>(new VersionLabel(8203,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateIM_CloseTimeUtcValueForInconsistentTimestampsTransform>(new VersionLabel(8202,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateNullAO_ParentIDToEmptyForAccChargeTaxOverride>(new VersionLabel(8201,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.CleanseBadDataStmActivityLog>(new VersionLabel(8200,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateFRTAndACTMetricCount>(new VersionLabel(8199,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RemoveGlowUseIndexingServiceForModuleFiltersRegistryItem>(new VersionLabel(8198,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemovePickByLabelLabelProcessTasks>(new VersionLabel(8196,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ContainerYard.PopulateUnitLineItemForGatedInYardUnit>(new VersionLabel(8195,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Cartage.DeduplicateCartageLegByJobAndSplitDeliverySuffixV2>(new VersionLabel(8194,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameGlowRateSelectorTransformation>(new VersionLabel(8193,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateNRAStartTimeAndEndTime>(new VersionLabel(8192,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.Populate_GWP_AutoEffectiveEndDate>(new VersionLabel(8191,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.GlbWorkPatternDeleteDuplicateRecordsWithSameStaffAndEffectiveDate>(new VersionLabel(8191,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameGlowUseIndexingServiceForSearchRegistryItem>(new VersionLabel(8189,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.ModifyParentToCusInBondMoveHeaderForStmPrintJobAndStmALog>(new VersionLabel(8188,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.ResetBiIsRequiredDeleteOrphanSubscriberRegistryItem>(new VersionLabel(8187,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintKJ_ParentTableCode>(new VersionLabel(8186,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.SplitInBondQPAndWPStatus>(new VersionLabel(8183,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.CopyFiltersFromOldToNewServiceTaskModule>(new VersionLabel(8182,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateGlbCompanyCampaignBudgetItemNegativeValuesToZero>(new VersionLabel(8181,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.ReleasePackageIfNoAnyOpenVariance>(new VersionLabel(8180,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.UpdateOrgMiscServCMNegativeNumericValuesToZero>(new VersionLabel(8179,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintKI_ParentTableCode>(new VersionLabel(8178,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintWB_ParentTableCode>(new VersionLabel(8177,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.JP.MoveJE_ValueTypeToCEI_ValueType>(new VersionLabel(8176,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Workflow.RemoveProcessHeaderWithG2ParentTableCode>(new VersionLabel(8175,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.BusinessIntelligence.DropAllowAlterCDCMetaObjectsTrigger>(new VersionLabel(8174,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.ZA.MoveJobComInvoiceLineVehicleAddInfosToCusVehicle>(new VersionLabel(8173,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.EnsureCusTempStorageRegLineTransactionGrossWeightFitPrecision19Scale6>(new VersionLabel(8172,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.AddParentApplicationForEAdaptorApplicationDataTransformation>(new VersionLabel(8171,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.PopulateStmServiceTaskFromStmScheduleTask>(new VersionLabel(8170,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RemoveSwitchToNewServiceTasksModuleRegistryItem>(new VersionLabel(8170,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.AddPermissionForS2STApplicationsDataTransformation>(new VersionLabel(8169,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsPickDockDoorAssignment>(new VersionLabel(8168,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.DGActivateUN3551AndUN3552ForIATA>(new VersionLabel(8167,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.MoveCusSupportingInfoFromCusInBondHeaderToCusInBondMoveHeader>(new VersionLabel(8166,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.RemoveGlowExistingValidationAlertsPreventSave>(new VersionLabel(8165,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsPickTrolleyJobLastEditTimeAndUser>(new VersionLabel(8163,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.RenameSystemUtilizationFeeOverrideToUtilizationFeeOverride>(new VersionLabel(8162,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.CleanUpWTAOnlyContacts>(new VersionLabel(8161,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Customs.Shared.RemoveDuplicateCusClassPivotsV2>(new VersionLabel(8159,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RemoveRollUpByTaxReportingCodeRegistryItem>(new VersionLabel(8158,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateJIBrandNameOnInvoiceLine>(new VersionLabel(8157,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.PopulateCSI_DataModel>(new VersionLabel(8156,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsPickPickTypeColumn>(new VersionLabel(8155,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.RenameGlbStaffLanguageToGlbPersonLanguage>(new VersionLabel(8154,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.RemoveCA_AccountingAgeFromGenAddOnColumn>(new VersionLabel(8152,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateDeliveryID>(new VersionLabel(8151,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulatePickupID>(new VersionLabel(8151,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintPJ_ParentTableCode>(new VersionLabel(8150,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintPJ_SourceTableCode>(new VersionLabel(8150,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoBookingSailingScheduleGroup>(new VersionLabel(8149,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.PopulateCRD_DataModel>(new VersionLabel(8148,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.ChangePortCallReferenceToVesselFromNaturalKeyToForeignKey>(new VersionLabel(8147,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.RenameCPO_RV_NKVesselToCPO_VesselName>(new VersionLabel(8147,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.AddConstraintToRefDocSourceCode>(new VersionLabel(8146,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.ChangeRefComplianceCommodityAlertRiskStatusByAlertType>(new VersionLabel(8145,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.UpdateConstraintValuesCSCDrayageColumn>(new VersionLabel(8143,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.EDISyncIncidentTriageIsPublishedColumnsTransform>(new VersionLabel(8142,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.MoveExRateTypeDataFromAccJobConfigToAccJobConfigPivot>(new VersionLabel(8140,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateNRAMetrics>(new VersionLabel(8139,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.ChangeLoggingMethodToElasticSearchLoggingInSANDEnvironments>(new VersionLabel(8137,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateUS_SupplementalTariffWithOnlyNumbers>(new VersionLabel(8136,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdatePackageStateSecurityStatusWhenSendDispatchInstruction>(new VersionLabel(8135,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BusinessIntelligence.UpdateAuditMaintenanceTaskSchedule>(new VersionLabel(8133,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.BusinessIntelligence.DeleteBiUseCDCHotfixRegistry>(new VersionLabel(8132,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.UpdateCM_MessageReference>(new VersionLabel(8130,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.RenameP0V_P0_ParentColumnTransformation>(new VersionLabel(8129,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.MigrateDataToDgAttributes>(new VersionLabel(8128,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemovePackingNumberFountainsForFinalizedWarehousePackageJobs>(new VersionLabel(8127,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.UpdateBM_EntryDateFromTP5IE028Message>(new VersionLabel(8126,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateCA_K84AccountingDateAndCA_K84StatementDate>(new VersionLabel(8125,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.DeleteOrphanedStmNoteFromEDIMessage>(new VersionLabel(8124,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.RemoveAutoAssignCapabilityTasksOnChangesWithinXMinutesRegistryItem>(new VersionLabel(8123,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.RemoveTransferWorkflowComponentOnChangesWithinXMinutesRegistryItem>(new VersionLabel(8123,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateEQ_DateReceivedColumnType>(new VersionLabel(8122,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintWV_ParentTableCode>(new VersionLabel(8121,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.SetDefaultCrmOpportunityFrequencyUnit>(new VersionLabel(8120,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.SetDefaultCrmOpportunityScopeFrequencyUnit>(new VersionLabel(8120,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.PurgeStmALogOrphans>(new VersionLabel(8119,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateYardUnitDetailsForMNRSurvey>(new VersionLabel(8118,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintJ7_ParentTableCode>(new VersionLabel(8117,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.ES.PopulateCVH_BrandNameAndCVH_ModelName>(new VersionLabel(8115,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintBRS_RelatedEntityTableCode>(new VersionLabel(8114,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.FillFIC_StatusAndWIC_ProcessingTime>(new VersionLabel(8113,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CN.FixCNJobComInvoiceLineUCTemplate>(new VersionLabel(8112,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CN.FixCNInvoiceLineDIWTemplate>(new VersionLabel(8112,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ConstraintSDP_SubjectTableCode>(new VersionLabel(8110,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateFacilityForWorkOrderHeader>(new VersionLabel(8109,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.PopulateSourceForCusEntryLineFee>(new VersionLabel(8108,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CN.FixCNJobDeclarationUCTemplate>(new VersionLabel(8107,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateGlbCompanyCampaignGroupNegativeValuesToZero>(new VersionLabel(8106,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateGlbCompanyCampaignSendSettingsNegativeValuesToZero>(new VersionLabel(8106,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateOrgCommissionAgreementRecipientRateNegativeValuesToZero>(new VersionLabel(8106,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.RemoveICS2RegistryOverrides>(new VersionLabel(8105,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.HydrateClusterKeyToCusEngine>(new VersionLabel(8104,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.HydrateClusterKeyToCusVehicle>(new VersionLabel(8104,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.UpdateExcelPasswordToExcelPasswordForModifyingInSdName>(new VersionLabel(8103,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdatePackageStateSecurityStatusForHuWhenScreeningIsBypassed>(new VersionLabel(8102,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.RemoveEmbeddedImagesRegistryItems>(new VersionLabel(8101,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.RemoveClientIntelligenceEnableDeduplicationFinderRegistryItem>(new VersionLabel(8100,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateCampaignItemRecipientTableCodeValueOPP>(new VersionLabel(8098,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.eServices.UpdateRegistryForConnectionToXTServer>(new VersionLabel(8097,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.ClearRootFileExportPathRegistryItemValues>(new VersionLabel(8096,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.RemoveDeclarationException060>(new VersionLabel(8094,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.FixBRJobDeclarationUCTemplate>(new VersionLabel(8093,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.CreateEdiIdentityApplicationRecords>(new VersionLabel(8092,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoEDocUploaderGroup>(new VersionLabel(8091,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateUseOAuth2ForIncomingRegistryItem>(new VersionLabel(8090,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateUseOAuth2ForOutgoingRegistryItem>(new VersionLabel(8090,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdateBY_LinePriceAndBY_RX_NKLinePriceCurrency>(new VersionLabel(8088,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Customs.CA.PopulateSubTypeCLOForMessagesWithStatusCode39>(new VersionLabel(8087,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateYardUnitDetailsForMNRWorkOrderHeader>(new VersionLabel(8086,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.RebrandCargoWiseAccountsForOtherUsers>(new VersionLabel(8085,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddDOC_SCL_SCLNDocumentType>(new VersionLabel(8084,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateGlbCompanyCampaignNegativeValuesToZero>(new VersionLabel(8083,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Gate.PopulateVehicleMovementVehicleRegistration>(new VersionLabel(8082,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCD_ParentTableCode>(new VersionLabel(8081,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.PopulateCPO_PortCallId>(new VersionLabel(8080,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.PopulateCVO_VoyageId>(new VersionLabel(8080,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdateRCNsAndDCNsToUseHouseBill>(new VersionLabel(8079,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCLP_ParentTableCode>(new VersionLabel(8078,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.RenameAndUpdateGracePeriodForDriverSecurity>(new VersionLabel(8077,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.RenameAUP_UniversalChargeCodeNameColumnTransformation>(new VersionLabel(8076,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.ChangeProcessHeaderCompletionStatementToNVarChar512>(new VersionLabel(8075,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.MigrateMilestoneCompletionPivotToSoftKey>(new VersionLabel(8073,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateGlowAuditIndexFields>(new VersionLabel(8072,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.KR.FixKRJobDeclarationUCTemplate>(new VersionLabel(8070,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.UpdateDocumentsChargeGroupingOrRollupStyle>(new VersionLabel(8069,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.FixDocBuilderAdvancePaymentMenuItem>(new VersionLabel(8068,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.RebrandCargoWiseAccounts>(new VersionLabel(8067,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.TruncateQuoteScopeTable>(new VersionLabel(8066,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintBP_ParentTableCode>(new VersionLabel(8065,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.MoveCustomsThirdQuantityFromGenAddOnToCusInBondCargoDesc>(new VersionLabel(8064,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TR.DeleteCusTRPreviousDocument>(new VersionLabel(8063,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateRegistryImageRegistryItemClass>(new VersionLabel(8061,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RenameAdvancePaymentRelatedTransactionCategoryCodes>(new VersionLabel(8060,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.DeleteNegativeAmountAllowedOnAccountReceivableTransactionsForVN>(new VersionLabel(8059,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.RemoveCommissionsForInvalidGroupingSourceTableCode>(new VersionLabel(8058,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.SetDefaultDGLimitWeightUnitAndVolumeUnit>(new VersionLabel(8057,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Workflow.UpdateInvalidRQT_JobType>(new VersionLabel(8056,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.MasterData.RemovePatternMatchingDataForConstraints>(new VersionLabel(8055,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.MasterData.RemoveGenShapeGeographyDataForConstraints>(new VersionLabel(8055,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.GB.LinkGBNctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(8054,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateAcceptanceAndReleaseNumber>(new VersionLabel(8052,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintC5_ParentTableCode>(new VersionLabel(8051,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.DeleteDataRelatedToInvalidJobType>(new VersionLabel(8049,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.RemoveSADGenerationConfigurationRegistryItem>(new VersionLabel(8048,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.UpdateEdiTokenAuthOnBoardingDataTenantToB2C01DataTransformation>(new VersionLabel(8047,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdatePackageStateSecurityStatusConsideringTransitJobDirection>(new VersionLabel(8046,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateOidcClientIdForEdiIdentityTenantTableTransform>(new VersionLabel(8045,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.MoveKoreaTaxInvoiceDocToAccTransactionHeaderAuthorisationRecord>(new VersionLabel(8044,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CN.RemoveSelfDeclaredAndPaid>(new VersionLabel(8043,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.UpdateTenantForExistingEdiIdentityApplication>(new VersionLabel(8042,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.DeleteFreightComplianceRiskAssessmentRegistryItem>(new VersionLabel(8040,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.RemoveDuplicateStatementLineChargeForDN>(new VersionLabel(8039,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemoveExposeLocationCheckDigitsRegistryItem>(new VersionLabel(8038,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemoveEnableRfServicesRegistryItem>(new VersionLabel(8037,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.TransformSuppressedDocsAndRemoveDummyContacts>(new VersionLabel(8036,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddStockBalanceReportsbyMRN>(new VersionLabel(8035,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToRefZonePivotParentTableCode>(new VersionLabel(8034,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToRateEntryParentTableCode>(new VersionLabel(8034,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToRateLinesParentTableCode>(new VersionLabel(8034,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.DeleteInvalidUniversalJobLink>(new VersionLabel(8033,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemoveDGThresholdFeatureFlagRegistryItem>(new VersionLabel(8032,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateAddInfoForPortOfExitAndPlaceOfReport>(new VersionLabel(8030,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.MoveRequestHeaderFromCusSupportingInfoToEUMemberStateCommunications>(new VersionLabel(8029,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCSD_ParentTableCode>(new VersionLabel(8028,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BE.ChangeBE_CE_ParentTableAndCE_ParentIDFromHeaderToMovementHeaderNCTS>(new VersionLabel(8026,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.SplitHVC_ReleaseStatusByImportAndExport>(new VersionLabel(8025,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BusinessIntelligence.DeleteEdwTranslationTableLoadPeriodRegistryItem>(new VersionLabel(8024,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.LandTransport.RemoveEquipmentItemsWithInvalidParentTableCode>(new VersionLabel(8023,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Customs.Shared.RemoveDuplicateCusClassPivots>(new VersionLabel(8021,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.LandedCostTables_ParentTableCode>(new VersionLabel(8019,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RectifyLocalTaxAmountOnPivotsForReversalTaxTransactions>(new VersionLabel(8018,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.EDIDelinkInactiveSystemUserAccountsFromContactsTransform>(new VersionLabel(8017,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.RemoveYardUnitStateIfYUS_YRL_ReceiveLineIsEmpty_And_YUS_YPL_Pickup_Or_YUS_YEL_ReleaseLineAreNotEmpty>(new VersionLabel(8015,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.ClearCIN750Note>(new VersionLabel(8014,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.PopulateActiveDirectorySidAndSamAccountFullName>(new VersionLabel(8013,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddDOC_SCL_SCAADocumentType>(new VersionLabel(8011,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.PopulateAllocationRouteWizardTemplateRowLinkScheduleType>(new VersionLabel(8010,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateUnitLineItemForCYDYardUnitState>(new VersionLabel(8009,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateStatusOfDailyNoticeMessageToQUE>(new VersionLabel(8008,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddDOC_SCL_SEHBDocumentType>(new VersionLabel(8007,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintC4_ParentTableCode>(new VersionLabel(8006,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.ClearIncorrectlySetWZ_WE_OriginalPickedInventoryLine>(new VersionLabel(8005,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.DeleteEmptyCusEntryNumbers>(new VersionLabel(8004,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateCusEntryHeaderStatusAndEntryStatusAccordingToStmALog>(new VersionLabel(8003,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintB5_ParentTableCode>(new VersionLabel(8002,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.ChangeBM_GrossWeightUQValueAsKGIfEmpty>(new VersionLabel(8001,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCPN_ParentTableCode>(new VersionLabel(8000,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsDocketLineSetStatusDepartedOnPickFinalisation>(new VersionLabel(7999,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Customs.CA.RequeFailedCADMessages>(new VersionLabel(7998,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintJI_ParentTableCode>(new VersionLabel(7997,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Workflow.UpdateExternalRequestWithTypeAndReviewer>(new VersionLabel(7996,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateInvalidSU_PrimaryDocPackItemTableCodeToEmpty>(new VersionLabel(7995,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdateDefaultTransportationTypeValues>(new VersionLabel(7994,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.UpdateEnableCompliancePotentialRiskMessageBannerRegistryItem>(new VersionLabel(7992,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Documents.UpdateDocumentSigningServiceCredentialsWithProviderRegistryItemClass>(new VersionLabel(7991,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.PurgeRedundantStorageMainLogsFromStmALog>(new VersionLabel(7989,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameOptionFromESToEUAccountingIntegrationOptionsRegistryItem>(new VersionLabel(7988,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.LandTransport.PopulateLTC_ConsignmentType>(new VersionLabel(7987,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.PopulateAccountingDateAndSecurityCodeForDailyNotice>(new VersionLabel(7986,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TW.UpdateRORDutyTreatmentPaymentMethod>(new VersionLabel(7984,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.RemoveFreightEnableComplianceWiseRegistryItem>(new VersionLabel(7983,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.CreateCusInBondMoveDetailForNcts5Departure>(new VersionLabel(7982,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Cartage.DeduplicateCartageLegByJobAndSplitDeliverySuffix>(new VersionLabel(7981,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TW.FixTWJobComInvoiceLineUCTemplate>(new VersionLabel(7980,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoSailingSchedulesViewerGroup>(new VersionLabel(7978,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoFlightSchedulesViewerGroup>(new VersionLabel(7978,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoRoadSchedulesViewerGroup>(new VersionLabel(7978,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoRailSchedulesViewerGroup>(new VersionLabel(7978,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintON_ParentTableCode>(new VersionLabel(7977,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Workflow.SetStmJobQueueEventTimeUtcFromEventTime>(new VersionLabel(7976,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.MoveGoodsCatalogLocalPartNumbersToCusGoodsCatalogProductionInfo>(new VersionLabel(7974,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.DeleteProcessControllerElasticLogViewerEnabledRegistryItem>(new VersionLabel(7973,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddWebMessageViewer>(new VersionLabel(7972,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddWebMessageSender>(new VersionLabel(7972,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintBW_ParentTableCode>(new VersionLabel(7971,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.ReplaceStmMenuDocumentConfigItemSectionItemName>(new VersionLabel(7969,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateActivityTrackingStatusForSupportUser>(new VersionLabel(7968,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.DocumentScanning.RemoveStorageDocsAuditLogs>(new VersionLabel(7967,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TW.FixTWInvoiceLineDIWTemplate>(new VersionLabel(7966,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.DeleteOrphanedVoyages>(new VersionLabel(7965,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TW.InsertConsignorConsigneeAddress>(new VersionLabel(7964,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateEmptyStmNoteContextToDefaultValue>(new VersionLabel(7963,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.PopulateWebLayoutPublishersGroup>(new VersionLabel(7962,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWZ_WE_OriginalOrderLine>(new VersionLabel(7961,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintBH_ParentTableCode>(new VersionLabel(7960,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Accounting.UpdateComplianceNumberAllocationDateRegistryItem>(new VersionLabel(7959,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.RenameDtbBookingQueueServiceTaskDescription>(new VersionLabel(7958,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.SetContainerizedPackageStatusForGatedOutRTU>(new VersionLabel(7957,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.DeleteTransitWarehouseCustomerRoleTransformation>(new VersionLabel(7956,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.DeleteOrphanedStmNoteFromStmPrintJob>(new VersionLabel(7955,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.UpdateOldGuaranteesMissingEntRuleCode>(new VersionLabel(7954,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.RenameCarrierShipmentToCarrierShipmentHeaderInGlowUseIndexingForModuleList>(new VersionLabel(7953,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.DeleteDuplicateAttachedDetachedLogForGlbGroup>(new VersionLabel(7952,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.ConvertJobServiceBookedDateTimeToDateTimeOffset>(new VersionLabel(7951,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.ConvertJobServiceCompletedDateTimeToDateTimeOffset>(new VersionLabel(7951,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.MoveJSL_JL_LooseCargoToJL_JSL_BookingLine>(new VersionLabel(7950,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.UpdateVoteExamSurveyAnswerNegativeNumericValuesToZero>(new VersionLabel(7949,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TR.EnsureUniqueCusEngine>(new VersionLabel(7948,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.PopulateCEG_DataModel>(new VersionLabel(7948,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdatePackageJobToMatchRCN>(new VersionLabel(7947,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.UpdateZG_ConfirmedGuaranteeAmountFromDeltaGMessage>(new VersionLabel(7946,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateIM_CloseTimeUtcValueTransform>(new VersionLabel(7945,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCSI_ParentTableCode>(new VersionLabel(7944,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemoveGenAddonColumnShortfallStatus>(new VersionLabel(7943,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.LandTransport.DeduplicateJobDocAddressForDtbConsignmentAddresses>(new VersionLabel(7942,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.TW.DeleteTotalDutyTaxFeeAmountGenAddOnColumn>(new VersionLabel(7941,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.RenameColumn_AddUTCSuffixForIncidentMain_ResolvedTimeAndClosedDate>(new VersionLabel(7940,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.DeleteOldParallelRegistryItems>(new VersionLabel(7938,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.EDIUpdateGenPivotSwapRelation1And2Transform>(new VersionLabel(7937,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UncompressGlowFilters>(new VersionLabel(7936,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UncompressGlowSavedColumns>(new VersionLabel(7936,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.DeduplicateDeclarationReferencePerCompany>(new VersionLabel(7934,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.RenameKK_DriverLicenseNumberToKK_DocumentID>(new VersionLabel(7932,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.UpdateOrgMiscServNegativeNumericValuesToZero>(new VersionLabel(7931,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.EDIUpdateIncidentDiagnosticCriteriaPivotTransform>(new VersionLabel(7929,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.RenameCarrierShipmentTableToCarrierShipmentHeader>(new VersionLabel(7928,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateMyAccountSSOJWTTokenExchangePrivateKeyRegistryDataTransformation>(new VersionLabel(7927,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateJobChargeProFormaCostAndRevenue>(new VersionLabel(7926,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.PopulateAMOCodeFromRegistry>(new VersionLabel(7925,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.RemoveUSAirAMSOriginatorCodeRegistry>(new VersionLabel(7925,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BusinessIntelligence.DeleteAuditDuplicateDataForMasterStateAndAlterColumns>(new VersionLabel(7923,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BusinessIntelligence.DeleteEdwDuplicateDataForMasterState>(new VersionLabel(7923,0)),
				Mapping.New<Enterprise.Client.EDI.DbUpgrader.EdiDeleteAzureManagementCertificateRegistryTransform>(new VersionLabel(7922,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.CopyEnableAddAndEditLogsToEnableAddEditAndDeleteLogsItems>(new VersionLabel(7921,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.UpdateServiceTaskCreatorOptionValueFCLToCNT>(new VersionLabel(7920,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.RemoveKafkaRegistryItems>(new VersionLabel(7919,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.RenameModuleEDPRoleTransformation>(new VersionLabel(7918,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.RenameModuleEODRoleTransformation>(new VersionLabel(7918,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.SG.CopyTradersRemarksToCusSupportingInfo>(new VersionLabel(7917,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.SeedUniversalClusterKeyNumberFountain>(new VersionLabel(7916,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.RemoveEnableTransportBookingGHGCalculationRegistry>(new VersionLabel(7915,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameShipamaxRegistries>(new VersionLabel(7914,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.GB.DeleteChiefServiceTasks>(new VersionLabel(7913,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsDocketStartedReceivingTimeUtcColumn>(new VersionLabel(7912,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateCusDispositionBlankStatusKey>(new VersionLabel(7911,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateJobCO2eStatusFromTEUStatus>(new VersionLabel(7910,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateInspectionCountryCodeForUKShipments>(new VersionLabel(7909,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsDocketCanceledColumns>(new VersionLabel(7908,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.RemoveWorkTimeAndStaffHolidayWithInvalidParentTableCodes>(new VersionLabel(7907,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateExpiryCountdownStartTimeUtc>(new VersionLabel(7906,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.DocumentScanning.PopulateRT_ParseTypeInRefDocTypeTableOffline>(new VersionLabel(7904,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdateGlowFiltersToRenameETAETDArrivalDepartureDate>(new VersionLabel(7903,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdateGlowSavedColumnsToRenameETAETDArrivalDepartureDate>(new VersionLabel(7903,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.RemoveDuplicateOrgPartUnit>(new VersionLabel(7902,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.SetUnitsPerClientUQOnOrgPartRelationV2>(new VersionLabel(7901,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RemoveComplianceWiseFeatureDevelopment>(new VersionLabel(7900,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToRateEntryToAndFromSuburb>(new VersionLabel(7899,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.UpdateESCServiceTaskIsActiveToFalse>(new VersionLabel(7898,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.MoveTPM_ReferenceNumberToTPM_IdentificationNumberInCusTransportMeansForTemporaryStorageHeader>(new VersionLabel(7897,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.DeleteAllowTriggerActionsToFireForCommercialInvoiceAttachedOnDeclarationRegistry>(new VersionLabel(7894,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdateGridSettingsRevertAddingIndexRegistryItem>(new VersionLabel(7893,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.RemoveUnitAndMovementIfYUS_UnitIDIsEmpty>(new VersionLabel(7891,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.PostUpgrade.Public.Customs.ES.ChangeCusInBondMoveHeaderBMPhaseInArrivalToTSAWhereInTS>(new VersionLabel(7889,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.CopyObsoleteColumnsFromAccTaxRateToGenAddOnColumnTable>(new VersionLabel(7887,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.AddUnmatchedOrgConfigDataTransformation>(new VersionLabel(7886,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateCA_K84AccountingDateOnLVXDeclaration>(new VersionLabel(7885,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.UpdateUSOverseasTerritoriesExportStatement>(new VersionLabel(7884,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.RenameModuleESHRoleTransformation>(new VersionLabel(7883,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Warehouse.RemoveEnableOrderLinePalletIDEntryRegistryItem>(new VersionLabel(7882,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsCycleCountLocationJobIDColumn>(new VersionLabel(7881,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.DropTVP_GeneralLedgerDataToAddColumns>(new VersionLabel(7880,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.TransitWarehouse.PopulateConsignmentDestination>(new VersionLabel(7879,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Customs.CA.CorrectDutyAndTaxInInvoiceLineAddInfo>(new VersionLabel(7878,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Public.MasterData.RemovePatternMatchingDataForDummyContacts>(new VersionLabel(7877,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.ClearBMCapacityCache>(new VersionLabel(7876,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.AU.RemoveEnableNEXDOCFishRegistryItem>(new VersionLabel(7875,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.DeleteCentralizedServiceTaskHostRowFromStmServiceHost>(new VersionLabel(7874,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.TransformOrgMiscServWhsPartWeightOrDimsOnReceive>(new VersionLabel(7873,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.PopulateBM_GrossWeightUnloadedAndB0_GrossWeightUnloadedForNctsP5Arrival>(new VersionLabel(7872,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateShipmentBillTypeAndBillTerms>(new VersionLabel(7871,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdatePkgStateAndRCNCustomsStatus>(new VersionLabel(7869,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.UpdatePostcodeLengthTransformation>(new VersionLabel(7868,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateClientOrderedUnitsForPickByBOMReceiveDocketLines>(new VersionLabel(7867,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.RemoveIncorrectlyCreatedNonSubConfirmationsFromSubInstructions>(new VersionLabel(7866,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransportBookings.RemovePackageDivotsOnSubInstructions>(new VersionLabel(7866,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.UNDGDataItemIsCombustibleFalseWhenZeroFlashPoint>(new VersionLabel(7865,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.LandedCosting.LandedCostingTablesClusterKeyTransformation>(new VersionLabel(7864,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.EnableGroupByCustomAttributesRegistry>(new VersionLabel(7862,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.JP.MigrateJobDeclarationFieldsToCusEntryInstruction>(new VersionLabel(7860,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.SplitHVC_JE_DeclarationByImportAndExport>(new VersionLabel(7858,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PopulateProcessHeaderTaskLowestOpenSequenceNumber>(new VersionLabel(7857,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.UpdateTempOrganisationRequiredFieldsRegistry>(new VersionLabel(7856,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.RemoveAMSMessagingModeRegistry>(new VersionLabel(7855,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.RemoveFlagshipRegistry>(new VersionLabel(7855,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.ConvertPKGCargoToBBK>(new VersionLabel(7854,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintPW_ParentTableCode>(new VersionLabel(7853,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameServiceTaskProcessingBatchSize>(new VersionLabel(7852,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.UpdateIndexSearchFilterLayout>(new VersionLabel(7851,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintCY_ParentTableCode>(new VersionLabel(7850,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateEnableBoleroEBLAndEHBLIntegrationRegistryDataTransformation>(new VersionLabel(7849,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.PopulateCommissionHeaderJobNumber>(new VersionLabel(7846,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.ChangeDateAcceptabilityDataToNewValues>(new VersionLabel(7845,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateCD_TaxRateDescForCusUSClassification>(new VersionLabel(7843,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.ChangeHVLVUsageHXUCodeToCWE>(new VersionLabel(7842,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.RemoveLegacyEntrySnapshot>(new VersionLabel(7839,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.PopulateSqlStaffLoginPasswordHash>(new VersionLabel(7838,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.FR.RemoveSADGenerationConfigurationRegistryItem>(new VersionLabel(7837,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RemoveShowUNDGVariantInDangerousGoodsDescriptionRegistryItem>(new VersionLabel(7835,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RenameInvoiceChargesRegistryItem>(new VersionLabel(7834,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.CopyInvoiceChargesForExportRegistryItemToImportForFRCompanies>(new VersionLabel(7834,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateAviationSecurityTrainingRestrictionsEuDataTransformation>(new VersionLabel(7832,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.DocumentScanning.RemoveDuplicatedMSCJobRequiredDocuments>(new VersionLabel(7831,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.ConstraintB7_ParentTableCode>(new VersionLabel(7828,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.UpdateStatusOnAccDraftInvoiceHeaderForPostedTransactions>(new VersionLabel(7827,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdateParentPackageForRepackingPackages>(new VersionLabel(7826,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateCustomEntryNumberToMultiItem>(new VersionLabel(7825,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsPickFinalizedByColumn>(new VersionLabel(7824,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Workflow.UpdateStmJobQueueWhenItContainsInvalidStatus>(new VersionLabel(7823,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.UpdateYUS_WL_CurrentYardLocationAndYUS_UnloadTime>(new VersionLabel(7822,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RemoveJobChargeAttributesLinkToCancelledIncompleteInvoice>(new VersionLabel(7821,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RemoveJobConsolCostAttributesLinkToCancelledIncompleteInvoice>(new VersionLabel(7821,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.LandTransport.GenerateConsignmentActionPackageDivotForExistingData>(new VersionLabel(7820,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BusinessIntelligence.UpdateBiAuditApiRegistryItem>(new VersionLabel(7819,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Documents.UpdateScheduledReportTemplateForJobHistoryReportTransformation>(new VersionLabel(7818,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateClientChargeableUsageSubCodeToUpperCaseTransform>(new VersionLabel(7817,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsDocketTrimExternalReferenceLeadingWhitespace>(new VersionLabel(7816,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateLoadUnloadUserAndTimeForYardUnitState>(new VersionLabel(7815,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.DeleteRunningReportStatistic>(new VersionLabel(7813,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsPickByBOMData>(new VersionLabel(7812,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.DeleteRoleOrderManagerCustomerFromSystemDefinedGroups>(new VersionLabel(7811,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.RemoveRefCountryRecordsDoNotMatchCodeConstraint>(new VersionLabel(7810,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.DeleteInvalidJobDocumentExclusionRecord>(new VersionLabel(7809,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.RenameAC_eNettChargeCodeMapToAC_ENettChargeCodeMap>(new VersionLabel(7808,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.IE.UpdateCGL_AdditionalIdentifierForUCC5>(new VersionLabel(7807,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Gate.PopulateGateBookingFacility>(new VersionLabel(7806,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateIncidentDispositionsToClosedTransformV3>(new VersionLabel(7805,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMBoardFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMBoardSlideshowFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMControlCustomisationFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMSystemFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMComponentFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.BufferManagement.PurgeBMNCNShapeFromStmALog>(new VersionLabel(7804,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformation.DataModification.Warehouse.RemoveEnablePackingConsolidationFunctionalityRegistryItem>(new VersionLabel(7803,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.SalesAndMarketing.UpdateGlowOpportunityStagesRegistryItemClass>(new VersionLabel(7802,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Accounting.FixChargeCodeOverridesForJobTypeBRK>(new VersionLabel(7801,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateUnitLineItemForPickup>(new VersionLabel(7800,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateUnitLineItemForCYDReleaseAdviceLine>(new VersionLabel(7800,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateUnitLineItemForCYDDelivery>(new VersionLabel(7800,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.PopulateUnitLineItemForCYDReceiveAdviceLine>(new VersionLabel(7800,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Documents.ExternalStorageSizeRetrieval>(new VersionLabel(7799,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateTableJobMawbColumnJM_GC_Company>(new VersionLabel(7798,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterFiles.Organisation.Other.UpdateOrgAirlineMAWBStockManagementOHM_GC_Company>(new VersionLabel(7798,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.ProductWarehouse.RemoveAllowPickFinalizationWithUnpackedTotes>(new VersionLabel(7797,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.ResetFountainVersionToDefault>(new VersionLabel(7795,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Accounting.UpdateDefaultScheduleRunEveryForKoreaSouthEInvoicingServiceTask>(new VersionLabel(7793,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Architecture.DataProtection.ProtectedDataStatusSeedForDefaults>(new VersionLabel(7792,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateReleaseBuildHlPackagePathToPointToNewArtifactRepoAlias>(new VersionLabel(7791,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.SalesAndMarketing.RemoveCommisionAgreementItemsWhereCodeIsEmpty>(new VersionLabel(7790,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RemoveAwsPcaArnRegistryDataTransformation>(new VersionLabel(7789,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.UpdateEdiIdentityCertificateCARootDefaultValueIfIsEmptyOrS2STrustDataTransformation>(new VersionLabel(7789,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RemoveLoggingMethodsForHostedClients>(new VersionLabel(7787,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CH.DeletePermitObligationGenAddOnColumn>(new VersionLabel(7786,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateCountryCodeForUKAdditionalInspectionCode>(new VersionLabel(7785,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.EDIUpdateUsageBillingSettingsRegistryTransform>(new VersionLabel(7784,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsABCAnalysisDateFromToDateTimeOffset>(new VersionLabel(7783,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsABCAnalysisDateToToDateTimeOffset>(new VersionLabel(7783,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.DeleteRoleOrderManagerCustomerFromGroupTrackPortal>(new VersionLabel(7782,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddHVLVShipmentProfileReport>(new VersionLabel(7781,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddHVLVShipmentsItemDetailsReport>(new VersionLabel(7781,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.FillOutSystemCreateTimeUtcAndSystemCreateUserForGlbGroupLink>(new VersionLabel(7780,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.BackFillMissingDetachedAttachedLogForGlbStaffAndGlbGroup>(new VersionLabel(7780,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.EnsureUniqueCusVehicleForSingleVehicleCountries>(new VersionLabel(7779,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.PopulateCVH_DataModel>(new VersionLabel(7779,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.PL.LinkPLNctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(7778,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.RenameSRRMaximumRetryCountRegistryItem>(new VersionLabel(7776,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.AddDefaultIncidentClosedEmailTemplate>(new VersionLabel(7775,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.SetUnitsPerClientUQOnOrgPartRelation>(new VersionLabel(7774,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddDOC_SCL_SCTKDocumentType>(new VersionLabel(7773,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.AddCustomsAdditionalCTKNumberDataTransformation>(new VersionLabel(7773,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.IE.InsertNctsPhase5DepartureRegisteredCusEntryNum>(new VersionLabel(7772,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.IE.InsertNctsPhase5ArrivalRegisteredCusEntryNum>(new VersionLabel(7772,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.RenameCommercialAndOperationalMeasurementsToChargeableAndActual>(new VersionLabel(7771,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.Rename_RateEntry_ToId_FromId_WithSuburbsTransformation>(new VersionLabel(7770,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.PopulateWhsVASOrderClientColumn>(new VersionLabel(7769,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Registry.UpdateEnableInwardProcessingFunctionForFRAndDERegistryDataTransformation>(new VersionLabel(7768,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.UpdateNEOERequestRolesToNotDefault>(new VersionLabel(7767,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Asycuda.UpdateAsycudaBillPersonTypes_SystemDefinedValues>(new VersionLabel(7766,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.TransformStmALogToWhsInventoryHoldChangeLog>(new VersionLabel(7765,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateISFJobBF_JS_Shipment>(new VersionLabel(7764,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateJECarrierCodeOnJobDeclaration>(new VersionLabel(7763,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.HRMS.GlbStaffEntitlementDeleteDuplicateEntitlementCodeWithinSameRem>(new VersionLabel(7762,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.PL.DeletePuescWebServiceRegistry>(new VersionLabel(7761,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ArchiveManager.DeleteCusOutturnForDeletedJobShipment>(new VersionLabel(7760,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.DE.UpdateBM_CustomsStatusBM_PhaseNCTSPhase5Arrival>(new VersionLabel(7759,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.UpdateTotalCO2eFromCO2ePerTonne>(new VersionLabel(7757,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Gate.PopulateMovementBookingNumber>(new VersionLabel(7756,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.Contracts.SetAllowRelatedPortsToFalseWhenScheduleIsLinked>(new VersionLabel(7755,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.DocumentScanning.PopulateSC_SystemCreateUserFromLogs>(new VersionLabel(7754,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.US.UpdateDeclarationConsolidatedEntryNumber>(new VersionLabel(7753,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.MasterDataComplianceWise.UpdateComplianceCommodityRiskStatusToNotChecked>(new VersionLabel(7752,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Rating.AddConstraintToOrgProfitShareDetails>(new VersionLabel(7751,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.PopulateCSC_CargoID>(new VersionLabel(7750,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.CopyJobServiceLinkLastEditTimeToCompletedTimeWhenIsCompleted>(new VersionLabel(7749,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.OceanCarrier.UpdateCarrierShipmentCargoRoutingLegCRG_TransportModeValue>(new VersionLabel(7748,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.DeleteProductCodesLookupRoleTransformation>(new VersionLabel(7747,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.BusinessIntelligence.RecreateIndexesForAuditDb>(new VersionLabel(7746,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdatePNTSMessageStatuses>(new VersionLabel(7745,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.eServices.UseLossyUsageEDIMessageNumberFountain>(new VersionLabel(7744,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.UpdateEdiIdentityApplicationForNonExistingAzureApplication>(new VersionLabel(7743,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.ChangeCFR_ParentTableCodeAndCFR_ParentIDFromHeaderToMovementHeaderPhase5>(new VersionLabel(7741,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.UpdateCustomsDeclarationEntryStatusFilterAddFilterTypeParameter>(new VersionLabel(7740,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.Shared.UpdateShipmentCustomsEntryStatusFilterAddFilterTypeParameter>(new VersionLabel(7740,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Ecommerce.UpdateHVC_StatusFromCONToCNF>(new VersionLabel(7739,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddNeoGTMGroup>(new VersionLabel(7737,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.UpdateGoodsLocationCustomsOfficeWhereQualifierIsV>(new VersionLabel(7735,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.EU.MoveGuaranteesToCusInBondMoveHeaderForNctsP5Departure>(new VersionLabel(7733,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.eServices.UseLossySystemEDIInterchangeNumberFountain>(new VersionLabel(7732,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.eServices.UseLossySystemEDIMessageNumberFountain>(new VersionLabel(7732,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsDocketSetDocketStatusDepartedOnPickFinalisation>(new VersionLabel(7731,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Freight.ContainerYard.UpdatePickupAndReadyDateForROILine>(new VersionLabel(7729,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BE.LinkBENctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(7728,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.PostUpgrade.Public.Glow.RemoveGlowUseDependencyGraphRegistryItem>(new VersionLabel(7727,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.SetDefaultValueForDispatchLoadListReferenceNumber>(new VersionLabel(7726,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.DE.LinkDENctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(7725,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateDefaultValueOfSystemInEventVisibilityOverrideRegistryItem>(new VersionLabel(7724,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.BR.RenameOrgRelatedPartyPR_CSAStatusToPR_CustomsStatus>(new VersionLabel(7723,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.DE.ChangeNCTSPhase5BM_SpecificCircumstance>(new VersionLabel(7722,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.IE.LinkIENctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(7721,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Core.RemoveDummyContacts>(new VersionLabel(7719,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.RemoveEnforceContentSecurityPolicy>(new VersionLabel(7718,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Glow.UpdateGlowPortalsContentSecurityPolicyModeRegistryItem>(new VersionLabel(7718,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.UpdateHVLVDetailsPreScreeningConfigurationRegistryItemToAddFromToHSCode>(new VersionLabel(7717,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Freight.Forwarding.RemoveDuplicatedCMRForConsolAndContainer>(new VersionLabel(7716,0)),
				Mapping.New<Enterprise.Client.EDI.DbUpgrader.EdiCreateERQOrganisationRelatedParty>(new VersionLabel(7715,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.IT.LinkITNctsPhase5DepartureDeclarationEdiMessageToCusInbondMoveHeader>(new VersionLabel(7714,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.AddCustomsAdditionalCMRNumberDataTransformation>(new VersionLabel(7713,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Customs.CA.UpdateRegistryKeyItemsFromB3ToEntry>(new VersionLabel(7712,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ClientSpecific.EDI.UpdateIncidentDispositionsToClosedTransformV2>(new VersionLabel(7710,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.UpdatePackageStateSecurityStatusForOverpack>(new VersionLabel(7709,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.EventLog.UpdatePersonSensitiveInformationEventLogTransform>(new VersionLabel(7708,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Security.AddMarketIntelligenceGroup>(new VersionLabel(7707,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsDocketFinalisedDateTimeToDateTimeOffset>(new VersionLabel(7706,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsDocketLineFinalisedDateTimeToDateTimeOffset>(new VersionLabel(7706,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateWhsPickLinePickedDateToDateTimeOffset>(new VersionLabel(7706,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.TransitWarehouse.ClearAdjPackageRelatedJob>(new VersionLabel(7705,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.ProductWarehouse.UpdateOldUserDefinedTPCReferenceType>(new VersionLabel(7704,0)),
				Mapping.New<Enterprise.DbUpgrader.Transformations.Transforms.Registry.RenameEnableICS2FunctionsRegistryItem>(new VersionLabel(7702,0)),
			};

			return mappings
				.OrderByDescending(x => x.MappedVersion)
				.ToArray();
		}
	}

	public class Mapper : TransformationMapper
	{
		public Mapper(IUpgradeManager manager)
			: base(manager)
		{
		}

		protected override DataTransformation[] GetAllTransformations()
		{
			var mappings = GetAllMappings();
			var result = new List<DataTransformation>(mappings.Length);
			foreach (var mapping in mappings)
			{
				var transform = (DataTransformation)Activator.CreateInstance(mapping.TransformationType);
				transform.Initialise(mapping.MappedVersion, Manager);
				result.Add(transform);
			}
			return result.ToArray();
		}

		public static Mapping[] GetAllMappings()
		{
			var mappingsProvider = GlobalServiceProvider.Instance.GetService<ITransformationMappingProvider>();
			return mappingsProvider.GetAllMappings();
		}

		public IEnumerable<IPopulateAuditTimeAndUserInfo> GetAllRunningPopulateCreateTimeAndUserInfo()
		{
			return
		GetAllTransformations()
		.Where(x => x.IsRequired)
		.OfType<IPopulateAuditTimeAndUserInfo>()
		.ToList();
		}

		public IEnumerable<IRenameColumnTransformationInfo> GetAllRunningRenameColumnTransformations()
		{
			return
				GetAllTransformations()
				.Where(x => x.IsRequired)
				.OfType<RenameColumnTransformation>()
				.SelectMany(x => x.RenameColumnInfoList)
				.ToList();
		}
	}
}
