<Project>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.GUI" />
    <Reference Include="Enterprise.Customs.EU.NCTS.Business" />
    <Reference Include="Enterprise.Customs.EU.NCTS.DataTransfer" />
    <Reference Include="Enterprise.Customs.EU.NCTS.GUI" />
    <Reference Include="Enterprise.Customs.GUI" />
    <Reference Include="Enterprise.Customs.IE.Business" />
    <Reference Include="Enterprise.Customs.IE.GUI" />
    <Reference Include="Enterprise.Customs.IE.Messaging" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.IE.NCTS.Business.csproj" />
  </ItemGroup>
</Project>