<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Customs.GB.EMCS.Messaging.Test</AssemblyName>
    <RootNamespace>Enterprise.Customs.GB.EMCS.Messaging.Testing</RootNamespace>
    <OutputPath>..\..\..\..\..\..\..\Bin</OutputPath>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <None Remove="Providers\Version4_1\TestFiles\IE704.xml" />
    <None Remove="Providers\Version4_1\TestFiles\IE837.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Providers\Version4_1\TestFiles\IE704.xml" />
    <EmbeddedResource Include="Providers\Version4_1\TestFiles\IE837.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.GB.EMCS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Customs.GB.MessageContracts" />
    <Reference Include="CargoWise.Customs.GB.MessageDefinitions" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.Business.Test" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
  </ItemGroup>
</Project>