<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.DataTransfer.Test">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.DataTransfer.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.Universal.Test" />
    <Reference Include="Enterprise.Customs.US.Business" />
    <Reference Include="Enterprise.Customs.US.DataTransfer" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer.Testing" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.UniversalDataBuss.Testing" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.US.LVS.Business.csproj" />
    <ProjectReference Include="..\DataTransfer\Enterprise.Customs.US.LVS.DataTransfer.csproj" />
  </ItemGroup>
</Project>