//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.Packing.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoPkgPackageItemDivot : EnterpriseBusinessObject, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "PkgPackageItemDivot";
			public const string PK        = "KI_PK";

			public const string KI_KP_Package            = "KI_KP_Package";
			public const string KI_PackedQty             = "KI_PackedQty";
			public const string KI_ParentID              = "KI_ParentID";
			public const string KI_ParentTableCode       = "KI_ParentTableCode";
			public const string KI_SystemCreateTimeUtc   = "KI_SystemCreateTimeUtc";
			public const string KI_SystemCreateUser      = "KI_SystemCreateUser";
			public const string KI_SystemLastEditTimeUtc = "KI_SystemLastEditTimeUtc";
			public const string KI_SystemLastEditUser    = "KI_SystemLastEditUser";

			public const int KI_ParentTableCodeMaxLength = 3;
			public const int KI_SystemCreateUserMaxLength = 3;
			public const int KI_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoPkgPackageItemDivot(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(KI_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(KI_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(KI_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(KI_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return PkgPackageItemDivotSchema.PK; }
		}

		#endregion

		#region Properties

		#region KI_KP_Package

		public virtual ZGuid KI_KP_Package
		{
			get {  return new ZGuid(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_KP_Package)); }
			set
			{
				SetPropertyValue(KI_KP_PackageInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateKI_KP_Package();
				}
			}
		}

		public virtual ZPropertyInfo KI_KP_PackageInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_KP_Package); }
		}

		#endregion

		#region KI_PackedQty

		public virtual ZDecimal KI_PackedQty
		{
			get {  return new ZDecimal(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_PackedQty)); }
			set
			{
				SetPropertyValue(KI_PackedQtyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateKI_PackedQty();
				}
			}
		}

		public virtual ZPropertyInfo KI_PackedQtyInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_PackedQty); }
		}

		#endregion

		#region KI_ParentID

		public virtual ZGuid KI_ParentID
		{
			get {  return new ZGuid(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_ParentID)); }
			set
			{
				SetPropertyValue(KI_ParentIDInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateKI_ParentID();
				}
			}
		}

		public virtual ZPropertyInfo KI_ParentIDInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_ParentID); }
		}

		#endregion

		#region KI_ParentTableCode

		public virtual ZString KI_ParentTableCode
		{
			get {  return new ZString(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_ParentTableCode)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = KI_ParentTableCodeInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateKI_ParentTableCode();
				}
			}
		}

		public virtual ZPropertyInfo KI_ParentTableCodeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_ParentTableCode); }
		}

		#endregion

		#region KI_SystemCreateTimeUtc

		public virtual ZDateTime KI_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(KI_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo KI_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_SystemCreateTimeUtc); }
		}

		#endregion

		#region KI_SystemCreateUser

		public virtual ZString KI_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = KI_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo KI_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_SystemCreateUser); }
		}

		#endregion

		#region KI_SystemLastEditTimeUtc

		public virtual ZDateTime KI_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(KI_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo KI_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_SystemLastEditTimeUtc); }
		}

		#endregion

		#region KI_SystemLastEditUser

		public virtual ZString KI_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(PkgPackageItemDivotSchema.KI_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = KI_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo KI_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(PkgPackageItemDivotSchema.Constants.KI_SystemLastEditUser); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[PkgPackageItemDivotSchema.Constants.KI_KP_Package           ] = Guid.Empty;
			row[PkgPackageItemDivotSchema.Constants.KI_PackedQty            ] = (decimal)0;
			row[PkgPackageItemDivotSchema.Constants.KI_ParentID             ] = Guid.Empty;
			row[PkgPackageItemDivotSchema.Constants.KI_ParentTableCode      ] = "";
			row[PkgPackageItemDivotSchema.Constants.KI_SystemCreateTimeUtc  ] = DBNull.Value;
			row[PkgPackageItemDivotSchema.Constants.KI_SystemCreateUser     ] = "";
			row[PkgPackageItemDivotSchema.Constants.KI_SystemLastEditTimeUtc] = DBNull.Value;
			row[PkgPackageItemDivotSchema.Constants.KI_SystemLastEditUser   ] = "";
		}

		#endregion

		#region Lookups

		public PkgPackageItemDivotLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual PkgPackageItemDivotLookups GetNewLookups()
		{
			return new PkgPackageItemDivotLookups(this);
		}

		PkgPackageItemDivotLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public PkgPackageItemDivotValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual PkgPackageItemDivotValidation GetNewValidation()
		{
			return new PkgPackageItemDivotValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return KI_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return KI_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return KI_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return KI_SystemLastEditUser; }
		}

		#endregion
	}
}
