// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:196,18
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:197,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:198,27
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:199,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:200,22
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:201,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:202,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.EDIMenuTest.JobDeclaration(Enterprise.Customs.CN.Business.CNSWClientSetting@,Enterprise.Customs.Business.CusEntryInstruction@)")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/EDIMenuTest.cs:203,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:53,17
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:54,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:55,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:56,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:57,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:58,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:59,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CNSWClientSettingRegistryItemEditorTest.CreateNewValue")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/Registry/CNSW/CNSWClientSettingRegistryItemEditorTest.cs:60,30
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:199,18
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:200,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:201,27
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:202,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:203,22
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:204,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:205,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.GUI.Testing.CustomsEntriesAndEntryLinesUserControlTest.TestClickSendAcdAgrMessage_NoError")] // Enterprise/Product/Operations/Customs/CN/Core/GUI.Test/JobDeclaration/CustomsEntriesAndEntryLinesUserControlTest.cs:206,25
