// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.AutoSchema.AddTablesAndPrefixes(System.String,System.Collections.Generic.Dictionary{System.String,System.String},System.Collections.Generic.HashSet{System.String},System.Boolean)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Builder\BusinessObjectGenerator\AutoSchema.cs:129:23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.AutoProperty.IndexForColumn(System.String,System.String,System.Nullable{CargoWise.Data.RefDbTypeEnum})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Builder\BusinessObjectGenerator\AutoProperty\AutoProperty.cs:115:23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.Testing.AutoCodeTest.TestAllDbDataTypesUsedInDbAreSupported")] // Enterprise/Product/Core/Builder/BusinessObjectGenerator/AutoCode.cs:374,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.Testing.AutoSchemaTest.GetAllDatabaseTableNames")] // Enterprise/Product/Core/Builder/BusinessObjectGenerator/AutoSchema.cs:385,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.Testing.AutoPropertyTest.TestAllViewBackingColumnsAreAcknowledged")] // Enterprise/Product/Core/Builder/BusinessObjectGenerator/AutoProperty/AutoProperty.cs:935,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BusinessObjectGenerator.Testing.AutoPropertyTest.TestAllViewBackingColumnsAreAcknowledged")] // Enterprise/Product/Core/Builder/BusinessObjectGenerator/AutoProperty/AutoProperty.cs:953,23
