<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>CargoWise.RefDbRepo.Staging.NewService.Test</AssemblyName>
    <RootNamespace>CargoWise.RefDbRepo.Staging.NewService.Test</RootNamespace>
    <OutputPath>..\..\..\Bin\StagingService\</OutputPath>
    <Configurations>Debug</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <Content Include="..\NewService\CargoWise.RefDbRepo.Staging.NewService.config.json" Link="CargoWise.RefDbRepo.Staging.NewService.Test.config.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.SafeDataClient">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Common.SafeDataClient.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Web">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Common.Web.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\StagingService\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewService\NewService.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ApplicationConfiguration\ApplicationPathsAndDefaultConfigurations.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
