using CargoWise.Application;
using Enterprise.Freight.Business;
using Enterprise.Freight.QuotedBookings.Business;
using Enterprise.Integration.Freight;
using Enterprise.MasterFiles.GUI;
using Enterprise.Registry.Business;
using Enterprise.ZArchitecture.GUI;

namespace Enterprise.Freight.QuotedBookings.Module
{
	public partial class QuotedBookingFilterControl : ZFilterStripControl
	{
		void InitializeComponent()
		{
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZOrganisationFindBoxColumnStyleInfo zOrganisationFindBoxColumnStyleInfo1 = new ZOrganisationFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo1 = new ZCodeFindBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo2 = new ZCodeFindBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo3 = new ZCodeFindBoxColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new ZGuidFindBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo4 = new ZCodeFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo1 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo2 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo1 = new ZMultiControlColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo13 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo2 = new ZMultiControlColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo20 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo22 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo24 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo8 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo9 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo25 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo10 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo11 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo12 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo13 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo26 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZOrganisationFindBoxColumnStyleInfo zOrganisationFindBoxColumnStyleInfo2 = new ZOrganisationFindBoxColumnStyleInfo();
			ZOrganisationFindBoxColumnStyleInfo zOrganisationFindBoxColumnStyleInfo3 = new ZOrganisationFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo27 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo28 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo1 = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo2 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo29 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo30 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateEditColumnStyleInfo10 = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateEditColumnStyleInfo11 = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo lastMilestoneCurCompany = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo lastMilestoneCurCompanyInclRelated = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo lastMilestoneATDCurCompany = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo lastMilestoneATDCurCompanyInclRelated = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo31 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo32 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo lastMilestoneDescCurCompany = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo lastMilestoneDescCurCompanyInclRelated = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo33 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo34 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo nextMilestoneCurCompany = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo nextMilestoneCurCompanyInclRelated = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo35 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo36 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo nextMilestoneDescCurCompany = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo nextMilestoneDescCurCompanyInclRelated = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateEditColumnStyleInfo12 = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateEditColumnStyleInfo13 = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo nextMilestoneETDCurCompany = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo nextMilestoneETDCurCompanyInclRelated = new ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo14 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo15 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo16 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo17 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo18 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZDropEditColumnStyleInfo shipmentStatusDropEditColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isHazardousColumnStyleInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isTemplateColumnStyleInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isTemplateActiveColumnStyleInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo isTemplateNameColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo additionalNumbersColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo isTemperatureControlled = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo undgClassTextBoxColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo undgSubstanceTextBoxColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo37 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo38 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo3 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo39 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo40 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo41 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo42 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo5 = new ZCodeFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo43 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo44 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo45 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo46 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo hasGoodsHandlingInstructionsCheckBoxInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo hasSpecialInstructionsCheckBoxInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo47 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo48 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo49 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo50 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo51 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo52 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo53 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo54 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo55 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo57 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo58 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo59 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoNotifyParty = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZOrganisationFindBoxColumnStyleInfo zOrganisationFindBoxColumnStyleInfoNotifyParty = new ZOrganisationFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoOrderRefs = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isDirectColumnStyleInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isOneOffQuoteApprovedInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo60 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoKPI = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoSource = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoRevisionReason = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zQuotedBookingCO2Info = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnTransportMode = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnContainerMode = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zQuotedBookingCO2StatusInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfoCompTariffLevel = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zQuotedBookingCommodityInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zQuotedBookingFMCTariffIDInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZOrganisationFindBoxColumnStyleInfo zQuotedBookingCreditorInfo = new ZOrganisationFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo carrierContractNumberColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo allocationIDColumnStyleInfo = new ZGuidFindBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo isOneOffQuoteAmendmentInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo61 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo62 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo hBlDeliveryModeColumn = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo14 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo startDateColumn = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo endDateColumn = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo consignorContactColumn = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo consigneeContactColumn = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo clientContactColumn = new ZArchitecture.ZTextBoxColumnStyleInfo();
			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.SuspendLayout();
			//
			// grid
			//
			zTextBoxColumnTransportMode.ColumnName = "QuotedBooking+TransportMode";
			zTextBoxColumnTransportMode.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnTransportMode.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|8497b6c3-0e5b-4a2b-8c44-7f90efdd5f53", "Transport Mode");
			zTextBoxColumnTransportMode.IsVisible = false;

			zTextBoxColumnContainerMode.ColumnName = "QuotedBooking+ContainerMode";
			zTextBoxColumnContainerMode.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnContainerMode.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|8632f8b2-a356-4de0-a94f-4fabc4892b9b", "Container Mode");
			zTextBoxColumnContainerMode.IsVisible = false;

			zTextBoxColumnStyleInfoCompTariffLevel.ColumnName = "QuotedBooking+CompanyTariffLevel";
			zTextBoxColumnStyleInfoCompTariffLevel.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfoCompTariffLevel.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|58a108a7-5afa-47ef-8067-5298b8004014", "CT Level", "Company Tariff Level Override", "Override the Company Tariff Level to be used for Autorating Revenue");
			zTextBoxColumnStyleInfoCompTariffLevel.IsVisible = false;

			hBlDeliveryModeColumn.ColumnName = "QuotedBooking+ContainerPackModeOverride";
			hBlDeliveryModeColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			hBlDeliveryModeColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|b2b74420-6185-439a-942a-3b8246c746bc", "HBL Dlv. Mode", "HBL Delivery Mode");
			hBlDeliveryModeColumn.IsVisible = false;

			zQuotedBookingFMCTariffIDInfo.ColumnName = "QuotedBooking+FMCTariffID";
			zQuotedBookingFMCTariffIDInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zQuotedBookingFMCTariffIDInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|0298befd-54ee-4b97-bee7-7f38c7bbf0b7", "FMC TID", "FMC Tariff ID", "Federal Maritime Commission Tariff ID.");
			zQuotedBookingFMCTariffIDInfo.IsVisible = false;

			zQuotedBookingCommodityInfo.ColumnName = "QuotedBooking+Commodity";
			zQuotedBookingCommodityInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zQuotedBookingCommodityInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|c2fd56ad-a1e6-4109-8740-8e7314454776", "Commodity", "Commodity Code", "The commodity that is being quoted/moved.");
			zQuotedBookingCommodityInfo.IsVisible = false;

			zQuotedBookingCreditorInfo.ColumnName = "QuotedBooking+Creditor";
			zQuotedBookingCreditorInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zQuotedBookingCreditorInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|Creditor|aa6e28f8-7ac1-4b97-9303-541a3da12bf0", "Creditor");
			zQuotedBookingCreditorInfo.IsVisible = false;

			zTextBoxColumnStyleInfoKPI.ColumnName = "QuotedBooking+OneOffQuoteStatistics+OneOffQuoteKPI";
			zTextBoxColumnStyleInfoKPI.IsMandatory = true;
			zTextBoxColumnStyleInfoKPI.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfoKPI.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|63e8a998-caf1-4cd8-b001-9a42091b1778", "Quote KPI");
			zTextBoxColumnStyleInfoSource.ColumnName = "QuotedBooking+OneOffQuoteStatistics+OneOffQuoteSource";
			zTextBoxColumnStyleInfoSource.IsMandatory = true;
			zTextBoxColumnStyleInfoSource.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfoSource.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ed1d4f9b-720c-4768-b23f-0bc59cff9eca", "Quote Source");

			zTextBoxColumnStyleInfoRevisionReason.ColumnName = "QuotedBooking+OneOffQuoteStatistics+OneOffQuoteRevisionReason";
			zTextBoxColumnStyleInfoRevisionReason.IsMandatory = true;
			zTextBoxColumnStyleInfoRevisionReason.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfoRevisionReason.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|f02c017d-7e0a-421e-80e4-880d2f7ebcc5", "Revision Reason");
			zTextBoxColumnStyleInfo1.ColumnName = "QuotedBooking+Quote+TH_QuoteNumber";
			zTextBoxColumnStyleInfo1.IsMandatory = true;
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo2.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1b886d27-ae0d-413f-aecd-29a091b2a2d4", "Booking #");
			zTextBoxColumnStyleInfo2.ColumnName = "QuotedBooking+Booking+JS_UniqueConsignRef";
			zTextBoxColumnStyleInfo2.IsMandatory = true;
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zOrganisationFindBoxColumnStyleInfo1.BindToList = "QuotedBooking+Clients";
			zOrganisationFindBoxColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|fc3a11eb-9bd7-4432-beb4-7cdb574b1ef9", "Client");
			zOrganisationFindBoxColumnStyleInfo1.ColumnName = "QuotedBooking+ClientAddr+OA_OH";
			zTextBoxColumnStyleInfo3.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|fdcc0cd0-eaab-4ad6-9284-c817e36f6de9", "Client Name");
			zTextBoxColumnStyleInfo3.ColumnName = "QuotedBooking+ClientFullName";
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo4.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|576dae92-0f11-4aca-8b3f-bacc0fc47fed", "Mode");
			zTextBoxColumnStyleInfo4.ColumnName = "QuotedBooking+Mode";
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|992884b6-160f-458b-a4ab-3d02b4b5a95c", "Weight");
			zCalcEditColumnStyleInfo1.ColumnName = "QuotedBooking+Weight";
			zCalcEditColumnStyleInfo1.Decimals = 3;
			zCalcEditColumnStyleInfo1.GroupName = Res.GetData("QuotedBookingFilterControl|5d07889c-5352-4856-ad14-d52234108849", "Weight");
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo5.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|44687b83-9fcd-4061-b090-6e60a2d8242e", "UW");
			zTextBoxColumnStyleInfo5.ColumnName = "QuotedBooking+WeightUnit";
			zTextBoxColumnStyleInfo5.GroupName = Res.GetData("QuotedBookingFilterControl|5d07889c-5352-4856-ad14-d52234108849", "Weight");
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1ad11539-7837-48d9-b6ee-62ba17982b5d", "Volume");
			zCalcEditColumnStyleInfo2.ColumnName = "QuotedBooking+Volume";
			zCalcEditColumnStyleInfo2.Decimals = 3;
			zCalcEditColumnStyleInfo2.GroupName = Res.GetData("QuotedBookingFilterControl|b157356d-1e80-4206-af6b-8719501daa38", "Volume");
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo6.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ac54a28c-bfde-40af-a20c-64de58c7a1b4", "UV");
			zTextBoxColumnStyleInfo6.ColumnName = "QuotedBooking+VolumeUnit";
			zTextBoxColumnStyleInfo6.GroupName = Res.GetData("QuotedBookingFilterControl|b157356d-1e80-4206-af6b-8719501daa38", "Volume");
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|2d2638e5-b83a-4759-92b7-5e53d58d8787", "Chargeable");
			zCalcEditColumnStyleInfo3.ColumnName = "QuotedBooking+Chargeable";
			zCalcEditColumnStyleInfo3.Decimals = 3;
			zCalcEditColumnStyleInfo3.GroupName = Res.GetData("QuotedBookingFilterControl|16531804-b5a0-4290-a62b-80996dae425d", "Chargeable");
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCodeFindBoxColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ab9fdae4-1537-4b7b-a61c-d2ed87dcdd40", "Origin");
			zCodeFindBoxColumnStyleInfo1.ColumnName = "QuotedBooking+Origin";
			zCodeFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo2.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|d6f3660a-ba06-48fe-a4b1-03021e5008a0", "Destination");
			zCodeFindBoxColumnStyleInfo2.ColumnName = "QuotedBooking+Destination";
			zCodeFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo3.ColumnName = "QuotedBooking+Quote+CurrentOneOffQuote+TT_RL_NKViaLocation";
			zCodeFindBoxColumnStyleInfo3.IsVisible = false;
			zCodeFindBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zGuidFindBoxColumnStyleInfo1.ColumnName = "QuotedBooking+OH_Carrier";
			zGuidFindBoxColumnStyleInfo1.IsVisible = false;
			zCalcEditColumnStyleInfo4.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo4.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|92fa3278-d11b-40d7-9b57-b1b71d8c2cb6", "Packs");
			zCalcEditColumnStyleInfo4.ColumnName = "QuotedBooking+Packs";
			zCalcEditColumnStyleInfo4.Decimals = 0;
			zCalcEditColumnStyleInfo4.GroupName = Res.GetData("QuotedBookingFilterControl|2185ed62-79bf-456c-865c-e4a1fa65d2eb", "Packages");
			zCalcEditColumnStyleInfo4.IsVisible = false;
			zCalcEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo7.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|00a9fe8d-69d3-42ea-a734-1ecc7d9ec702", "Type");
			zTextBoxColumnStyleInfo7.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			zTextBoxColumnStyleInfo7.ColumnName = "QuotedBooking+PacksType";
			zTextBoxColumnStyleInfo7.GroupName = Res.GetData("QuotedBookingFilterControl|2185ed62-79bf-456c-865c-e4a1fa65d2eb", "Packages");
			zTextBoxColumnStyleInfo7.IsVisible = false;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCodeFindBoxColumnStyleInfo4.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|3bceae3c-8f84-45f6-817e-f8a127e045fb", "Service Lvl.", "Service Level");
			zCodeFindBoxColumnStyleInfo4.ColumnName = "QuotedBooking+ServiceLevel";
			zCodeFindBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo8.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|eb31fdde-3f5d-b3ac-49ed-109d5eb56b87", "Incoterm");
			zTextBoxColumnStyleInfo8.ColumnName = "QuotedBooking+PaymentTerms";
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(55);
			zTextBoxColumnStyleInfo9.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|442592bb-4205-4698-a19a-b9b2c0b1991c", "Add. Terms", "Additional Terms", "");
			zTextBoxColumnStyleInfo9.ColumnName = "QuotedBooking+AdditionalTerms";
			zTextBoxColumnStyleInfo9.IsVisible = false;
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo10.ColumnName = "QuotedBooking+Booking+JS_HouseBill";
			zCheckBoxColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|7136c04d-5516-4a3c-979f-fdd2b11c244e", "Final Print");
			zCheckBoxColumnStyleInfo1.ColumnName = "QuotedBooking+Quote+TH_IsLocked";
			zCheckBoxColumnStyleInfo1.ToolTip = "Specifies whether this quotation has been printed in final mode - and is therefor" +
	"e locked.";
			zCheckBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCheckBoxColumnStyleInfo2.ColumnName = "QuotedBooking+Quote+TH_IsOneOffQuoteConsumed";
			zCheckBoxColumnStyleInfo2.ToolTip = "Specifies whether this Spot Quote has been used for autorating purposes on a ship" +
	"ment.";
			zCheckBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|520da94b-a43c-464b-9061-49fb2991cc1e", "20GP");
			zCalcEditColumnStyleInfo5.ColumnName = "QuotedBooking+ContainerCount20GP";
			zCalcEditColumnStyleInfo5.Decimals = 0;
			zCalcEditColumnStyleInfo5.IsVisible = false;
			zCalcEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zMultiControlColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4abcec58-277b-471d-ae90-d1166d5c53a2", "Consignor");
			zMultiControlColumnStyleInfo1.ColumnName = "QuotedBooking+ConsignorNameOrPK";
			zMultiControlColumnStyleInfo1.FieldTypeColumnName = "QuotedBooking+ConsignorFieldType";
			consignorContactColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|91a17516-ecd2-4eaa-942d-f3d6433abb5e", "Consignor Contact");
			consignorContactColumn.ColumnName = "QuotedBooking+ConsignorContact";
			consignorContactColumn.IsVisible = false;
			consignorContactColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			consigneeContactColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|cee8dc34-427f-49d9-aa17-7fa85f7a02b2", "Consignee Contact");
			consigneeContactColumn.ColumnName = "QuotedBooking+ConsigneeContact";
			consigneeContactColumn.IsVisible = false;
			consigneeContactColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			clientContactColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4cd48cd2-53ba-48c8-89c3-cf203bf0b67a", "Client Contact");
			clientContactColumn.ColumnName = "QuotedBooking+ClientContact";
			clientContactColumn.IsVisible = false;
			clientContactColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|330a00d4-9c25-45c6-82ec-40907341b9c3", "Value");
			zCalcEditColumnStyleInfo6.ColumnName = "QuotedBooking+GoodsValue";
			zCalcEditColumnStyleInfo6.GroupName = Res.GetData("QuotedBookingFilterControl|a861f4ca-d553-4b60-8f84-82a62942d3ea", "Value");
			zCalcEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo12.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|449005fe-8a75-4d20-9cf2-ceb863330186", "Curr");
			zTextBoxColumnStyleInfo12.ColumnName = "QuotedBooking+GoodsCurrency";
			zTextBoxColumnStyleInfo12.GroupName = Res.GetData("QuotedBookingFilterControl|a861f4ca-d553-4b60-8f84-82a62942d3ea", "Value");
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zTextBoxColumnStyleInfo13.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|2703bdef-ec58-451b-a7ad-80f5fa6030e7", "Cargo Desc.", "Cargo Description");
			zTextBoxColumnStyleInfo13.ColumnName = "QuotedBooking+GoodsDescription";
			zTextBoxColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo14.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4ee939f9-158a-4b83-b31d-806222fd9254", "Vessel");
			zTextBoxColumnStyleInfo14.ColumnName = "QuotedBooking+Booking+JS_Calc_CurrentVessel";
			zTextBoxColumnStyleInfo14.IsVisible = false;
			zTextBoxColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo15.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|7ea59eaa-dc80-4406-a3d7-0a5efdecbb85", "Voyage/Flight");
			zTextBoxColumnStyleInfo15.ColumnName = "QuotedBooking+Booking+JS_Calc_CurrentVoyageFlight";
			zTextBoxColumnStyleInfo15.IsVisible = false;
			zDateEditColumnStyleInfo1.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|facbf36e-78bc-4082-a40d-9e99816d7916", "ETD", "Booking ETD", "Quoted Booking ETD");
			zDateEditColumnStyleInfo1.ColumnName = "QuotedBooking+Booking+JS_E_DEP";
			zDateEditColumnStyleInfo1.IsVisible = false;
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo2.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|5e5c0372-37da-4671-91e2-d6f4eeec068a", "ETA", "Booking ETA", "Quoted Booking ETA");
			zDateEditColumnStyleInfo2.ColumnName = "QuotedBooking+Booking+JS_E_ARV";
			zDateEditColumnStyleInfo2.IsVisible = false;
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo14.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|0744C9BC-3351-48BE-986E-032A04B5A5AB", "Est Pickup", "Estimated Pickup");
			zDateEditColumnStyleInfo14.ColumnName = "QuotedBooking+PickupReady";
			zDateEditColumnStyleInfo14.IsVisible = false;
			zDateEditColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo15.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|765ABA0E-7003-4431-8FE2-B61BE9FE16DB", "Est Delivery", "Estimated Delivery");
			zDateEditColumnStyleInfo15.ColumnName = "QuotedBooking+DeliveryOpen";
			zDateEditColumnStyleInfo15.IsVisible = false;
			zDateEditColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo16.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4A083D40-3FEC-4F92-A11A-B7782B9293FB", "Pickup Req. By", "Pickup Required By");
			zDateEditColumnStyleInfo16.ColumnName = "QuotedBooking+PickupClose";
			zDateEditColumnStyleInfo16.IsVisible = false;
			zDateEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo17.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|F0424688-5BE3-4315-987F-A5A335D45BD5", "Delivery Req. By", "Delivery Required By");
			zDateEditColumnStyleInfo17.ColumnName = "QuotedBooking+DeliveryClose";
			zDateEditColumnStyleInfo17.IsVisible = false;
			zDateEditColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo18.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|a9dd89c5-dbe8-4d38-adc7-f0a241d3ad27", "Delivery Due Date");
			zDateEditColumnStyleInfo18.ColumnName = "QuotedBooking+DeliveryDueDate";
			zDateEditColumnStyleInfo18.IsVisible = false;
			zDateEditColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zTextBoxColumnStyleInfo16.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|daf21c6d-d7ce-4837-8e9a-ca242a769683", "Load");
			zTextBoxColumnStyleInfo16.ColumnName = "QuotedBooking+LoadPort";
			zTextBoxColumnStyleInfo16.IsVisible = false;
			zTextBoxColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo17.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|e954a830-3321-4528-8dcc-9a40e3c8fa7b", "Disch.", "Discharge");
			zTextBoxColumnStyleInfo17.ColumnName = "QuotedBooking+DischargePort";
			zTextBoxColumnStyleInfo17.IsVisible = false;
			zTextBoxColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zMultiControlColumnStyleInfo2.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|aced2a8e-be91-4043-9c2e-c16654c78173", "Consignee");
			zMultiControlColumnStyleInfo2.ColumnName = "QuotedBooking+ConsigneeNameOrPK";
			zMultiControlColumnStyleInfo2.FieldTypeColumnName = "QuotedBooking+ConsigneeFieldType";
			zMultiControlColumnStyleInfo2.IsVisible = false;
			zTextBoxColumnStyleInfo20.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|23f12169-cc00-4f38-aad6-48d195dc3a9e", "Equip. Req.", "Equipment Required.");
			zTextBoxColumnStyleInfo20.ColumnName = "QuotedBooking+Booking+DocsAndCartage+JP_FCLPickupEquipmentNeeded";
			zTextBoxColumnStyleInfo20.IsVisible = false;
			zTextBoxColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(35);
			zTextBoxColumnStyleInfo22.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|9a45cffe-41ad-4be4-bc44-0c98e5a30c59", "Shippers Ref");
			zTextBoxColumnStyleInfo22.ColumnName = "QuotedBooking+Booking+JS_BookingReference";
			zTextBoxColumnStyleInfo22.IsVisible = false;
			zTextBoxColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo24.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ed00250f-fb7e-42c5-96a0-d2405f91d261", "Interim #");
			zTextBoxColumnStyleInfo24.ColumnName = "QuotedBooking+Booking+JS_InterimReceipt";
			zTextBoxColumnStyleInfo24.IsVisible = false;
			zDateEditColumnStyleInfo3.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|cf521a8a-a006-497c-b319-851e525c2a1f", "Recv. Date", "Receival Date");
			zDateEditColumnStyleInfo3.ColumnName = "QuotedBooking+Booking+JS_A_RCV";
			zDateEditColumnStyleInfo3.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDateEditColumnStyleInfo4.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|69abc8c5-9886-4212-9a79-ae9434ee866c", "CFS Recv.", "CFS Receival Start");
			zDateEditColumnStyleInfo4.ColumnName = "QuotedBooking+Booking+Sailing+JX_DepotReceivalCommences";
			zDateEditColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo5.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ba93da4c-162b-4e4c-b03d-4560b562b0da", "CFS Cut", "CFS Cut Off");
			zDateEditColumnStyleInfo5.ColumnName = "QuotedBooking+Booking+Sailing+JX_DepotCutOff";
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo6.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1f390995-bbb6-4d55-98f4-c9b80ed0a6b6", "CTO Recv.", "CTO Receival Start");
			zDateEditColumnStyleInfo6.ColumnName = "QuotedBooking+Booking+Sailing+JX_JA_CTOReceivalCommences";
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo7.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|64e20a16-d728-4bae-8ffc-8d7798be9f62", "CTO Cut", "CTO Cut Off");
			zDateEditColumnStyleInfo7.ColumnName = "QuotedBooking+Booking+Sailing+JX_JA_CTOCutOff";
			zDateEditColumnStyleInfo7.IsVisible = false;
			zDateEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo8.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|d70fd6df-f78b-4cde-8c8a-e43f75abe522", "Docs Cut Off");
			zDateEditColumnStyleInfo8.ColumnName = "QuotedBooking+Booking+Sailing+JX_JA_DocumentaryCutoff";
			zDateEditColumnStyleInfo8.IsVisible = false;
			zDateEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo9.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|070a7c3e-98ca-46db-b56c-4607c1d929e4", "Booked");
			zDateEditColumnStyleInfo9.ColumnName = "QuotedBooking+Booking+JS_A_BKD";
			zDateEditColumnStyleInfo9.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo9.IsVisible = false;
			zDateEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo25.ColumnName = "QuotedBooking+Booking+JS_CFSReference";
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4d800f58-4a7f-42e5-b568-ede8abe43729", "TEU");
			zCalcEditColumnStyleInfo7.ColumnName = "QuotedBooking+TEUCount";
			zCalcEditColumnStyleInfo7.IsVisible = false;
			zCalcEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|d1752bc9-f787-42cd-9f62-1962bdc22737", "Con. Count");
			zCalcEditColumnStyleInfo8.ColumnName = "QuotedBooking+ContainerCount";
			zCalcEditColumnStyleInfo8.IsVisible = false;
			zCalcEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo10.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo10.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|5a5a19c0-b87d-45bd-aee7-c86971208605", "20RE");
			zCalcEditColumnStyleInfo10.ColumnName = "QuotedBooking+ContainerCount20RE";
			zCalcEditColumnStyleInfo10.Decimals = 0;
			zCalcEditColumnStyleInfo10.IsVisible = false;
			zCalcEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo11.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo11.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|5eca309c-849c-4382-822f-c443dfd580a4", "40GP");
			zCalcEditColumnStyleInfo11.ColumnName = "QuotedBooking+ContainerCount40GP";
			zCalcEditColumnStyleInfo11.Decimals = 0;
			zCalcEditColumnStyleInfo11.IsVisible = false;
			zCalcEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo12.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo12.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|580e1ae9-c60a-4a22-997e-d71d35870309", "40RE");
			zCalcEditColumnStyleInfo12.ColumnName = "QuotedBooking+ContainerCount40RE";
			zCalcEditColumnStyleInfo12.Decimals = 0;
			zCalcEditColumnStyleInfo12.IsVisible = false;
			zCalcEditColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo13.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo13.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|d2e264d8-5475-4e6f-afc3-53d9489970a1", "Oth. Con.", "Other Con.");
			zCalcEditColumnStyleInfo13.ColumnName = "QuotedBooking+ContainerCountOther";
			zCalcEditColumnStyleInfo13.Decimals = 0;
			zCalcEditColumnStyleInfo13.IsVisible = false;
			zCalcEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo26.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|151d00fe-b2c1-4c2c-92da-9dda4744fddc", "Sales Rep");
			zTextBoxColumnStyleInfo26.ColumnName = "QuotedBooking+Job+RepSales+GS_Code";
			zTextBoxColumnStyleInfo26.IsVisible = false;
			zOrganisationFindBoxColumnStyleInfo2.CaptionResourceString = Res.GetData("39516418-6000-444e-957b-ed3236f0f386", "Booking Party");
			zOrganisationFindBoxColumnStyleInfo2.ColumnName = "QuotedBooking+BookingPartyDocumentaryAddress+Organisation+MainAddress+OA_OH";
			zOrganisationFindBoxColumnStyleInfo2.IsVisible = false;
			zOrganisationFindBoxColumnStyleInfo3.ColumnName = "QuotedBooking+Booking+JS_OH_DeliveryAgent";
			zOrganisationFindBoxColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo27.CaptionResourceString = Res.GetData("bb35ee94-94d0-43fa-95b9-9c8909f4d89b", "Booking Party Name");
			zTextBoxColumnStyleInfo27.ColumnName = "QuotedBooking+BookingPartyDocumentaryAddress+Organisation+OH_FullName";
			zTextBoxColumnStyleInfo27.IsVisible = false;
			zTextBoxColumnStyleInfo28.CaptionResourceString = Res.GetData("b7aa4ea3-6c54-45fc-b686-1fe4ab92e04b", "Pickup Agent");
			zTextBoxColumnStyleInfo28.ColumnName = "QuotedBooking+Booking+PickupAgentCompanyCode";
			zTextBoxColumnStyleInfo28.IsVisible = false;
			zDropEditColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo1.ColumnName = "QuotedBooking+Booking+JS_ReleaseType";
			zDropEditColumnStyleInfo1.IsVisible = false;
			zDropEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zDropEditColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo2.ColumnName = "QuotedBooking+HBLAWBChargesDisplay";
			zDropEditColumnStyleInfo2.IsVisible = false;
			zDropEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo29.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4bc266ac-37fa-403b-be9a-c4226bbababc", "Last Milestone");
			zTextBoxColumnStyleInfo29.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo29.ColumnName = "WorkflowItems+Milestones+LastMilestone+P9_SE_NKMilestoneEvent";
			zTextBoxColumnStyleInfo29.IsVisible = false;
			zTextBoxColumnStyleInfo30.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|dee1bdb9-ac8e-4348-8d0d-7a89838bc553", "Last Milestone (incl Rltd.)", "Last Milestone (incl Related).");
			zTextBoxColumnStyleInfo30.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo30.ColumnName = "WorkflowItems+MilestonesIncludingRelated+LastMilestone+P9_SE_NKMilestoneEvent";
			zTextBoxColumnStyleInfo30.IsVisible = false;
			zTextBoxColumnStyleInfo30.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDateEditColumnStyleInfo10.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|30564f81-8d84-49ac-bee4-900f939929e8", "Last Milestone ATD");
			zDateEditColumnStyleInfo10.ColumnName = "WorkflowItems+Milestones+LastMilestone+P9_ActualDateForBinding";
			zDateEditColumnStyleInfo10.IsVisible = false;
			zDateEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDateEditColumnStyleInfo11.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|cbc5b2d6-2e24-4700-9520-598b3be2b46f", "Last Milestone ATD (incl Rltd.)", "Last Milestone ATD (incl Related).");
			zDateEditColumnStyleInfo11.ColumnName = "WorkflowItems+MilestonesIncludingRelated+LastMilestone+P9_ActualDateForBinding";
			zDateEditColumnStyleInfo11.IsVisible = false;
			zDateEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			lastMilestoneCurCompany.CaptionResourceString = Res.GetData("dad6331e-991c-4362-9be5-c7b25dafe731", "Last Milestone Cur. Comp.", "Last Milestone Current Company", "");
			lastMilestoneCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyLastMilestone+P9_SE_NKMilestoneEvent";
			lastMilestoneCurCompany.IsVisible = false;
			lastMilestoneCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			lastMilestoneCurCompanyInclRelated.CaptionResourceString = Res.GetData("000d8246-02bc-4241-8460-34ab38c6ecce", "Last Milestone Cur. Comp. (incl Rltd.)", "Last Milestone Current Company (incl Related).", "");
			lastMilestoneCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyLastMilestone+P9_SE_NKMilestoneEvent";
			lastMilestoneCurCompanyInclRelated.IsVisible = false;
			lastMilestoneCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			lastMilestoneATDCurCompany.CaptionResourceString = Res.GetData("d1bf65c0-00c2-4b3d-a6af-2fcd937bd2a4", "Last Milestone ATD Cur. Comp.", "Last Milestone ATD Current Company", "");
			lastMilestoneATDCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyLastMilestone+P9_ActualDateForBinding";
			lastMilestoneATDCurCompany.IsVisible = false;
			lastMilestoneATDCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			lastMilestoneATDCurCompanyInclRelated.CaptionResourceString = Res.GetData("d3b0c81b-1535-4609-a50d-427f7be87d13", "Last Milestone ATD Cur. Comp. (incl Rltd.)", "Last Milestone ATD Current Company (incl Related).", "");
			lastMilestoneATDCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyLastMilestone+P9_ActualDateForBinding";
			lastMilestoneATDCurCompanyInclRelated.IsVisible = false;
			lastMilestoneATDCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			zTextBoxColumnStyleInfo31.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|313a6fc3-ab9a-412d-87a5-47ecf626811b", "Last Milestone Desc.", "Last Milestone Description");
			zTextBoxColumnStyleInfo31.ColumnName = "WorkflowItems+Milestones+LastMilestone+DescriptionWithReference";
			zTextBoxColumnStyleInfo31.IsVisible = false;
			zTextBoxColumnStyleInfo31.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo32.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|92ad140d-ed24-4386-a426-3beae6fba699", "Last Milestone Desc. (incl Rltd.)", "Last Milestone Description (incl Related).");
			zTextBoxColumnStyleInfo32.ColumnName = "WorkflowItems+MilestonesIncludingRelated+LastMilestone+DescriptionWithReference";
			zTextBoxColumnStyleInfo32.IsVisible = false;
			zTextBoxColumnStyleInfo32.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			lastMilestoneDescCurCompany.CaptionResourceString = Res.GetData("3069f0ed-01ed-4039-b221-1b5f1f8c72bf", "Last Milestone Desc. Cur. Comp.", "Last Milestone Description Current Company", "");
			lastMilestoneDescCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyLastMilestone+DescriptionWithReference";
			lastMilestoneDescCurCompany.IsVisible = false;
			lastMilestoneDescCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			lastMilestoneDescCurCompanyInclRelated.CaptionResourceString = Res.GetData("031ca243-1726-4e97-a5f2-b0772e3574ff", "Last Milestone Desc. Cur. Comp. (incl Rltd.)", "Last Milestone Description Current Company (incl Related).", "");
			lastMilestoneDescCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyLastMilestone+DescriptionWithReference";
			lastMilestoneDescCurCompanyInclRelated.IsVisible = false;
			lastMilestoneDescCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			zTextBoxColumnStyleInfo33.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|c7528c6c-091a-4383-93bf-2d60d34c5393", "Next Milestone");
			zTextBoxColumnStyleInfo33.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo33.ColumnName = "WorkflowItems+Milestones+NextMilestone+P9_SE_NKMilestoneEvent";
			zTextBoxColumnStyleInfo33.IsVisible = false;
			zTextBoxColumnStyleInfo34.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|967dec08-3f06-4236-81f7-6e2cf0377848", "Next Milestone (incl Rltd.)", "Next Milestone (incl Related).");
			zTextBoxColumnStyleInfo34.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo34.ColumnName = "WorkflowItems+MilestonesIncludingRelated+NextMilestone+P9_SE_NKMilestoneEvent";
			zTextBoxColumnStyleInfo34.IsVisible = false;
			zTextBoxColumnStyleInfo34.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			nextMilestoneCurCompany.CaptionResourceString = Res.GetData("4b28995c-c4b0-42fb-ad7d-67349d03a955", "Next Milestone Cur. Comp.", "Next Milestone Current Company", "");
			nextMilestoneCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyNextMilestone+P9_SE_NKMilestoneEvent";
			nextMilestoneCurCompany.IsVisible = false;
			nextMilestoneCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			nextMilestoneCurCompanyInclRelated.CaptionResourceString = Res.GetData("b4cd053c-4151-4670-99ab-d7bea2f46a1f", "Next Milestone Cur. Comp. (incl Rltd.)", "Next Milestone Current Company (incl Related).", "");
			nextMilestoneCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyNextMilestone+P9_SE_NKMilestoneEvent";
			nextMilestoneCurCompanyInclRelated.IsVisible = false;
			nextMilestoneCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			zTextBoxColumnStyleInfo35.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|303cb62f-7e37-47f6-8e8f-ca34d8dc6937", "Next Milestone Desc.", "Next Milestone Description");
			zTextBoxColumnStyleInfo35.ColumnName = "WorkflowItems+Milestones+NextMilestone+DescriptionWithReference";
			zTextBoxColumnStyleInfo35.IsVisible = false;
			zTextBoxColumnStyleInfo35.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo36.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|edefc37d-5e6e-4cda-aa27-7ab8e34d90fd", "Next Milestone Desc. (incl Rltd.)", "Next Milestone Description (incl Related).");
			zTextBoxColumnStyleInfo36.ColumnName = "WorkflowItems+MilestonesIncludingRelated+NextMilestone+DescriptionWithReference";
			zTextBoxColumnStyleInfo36.IsVisible = false;
			zTextBoxColumnStyleInfo36.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			nextMilestoneDescCurCompany.CaptionResourceString = Res.GetData("f3d0e281-6485-4c71-b232-d7ce0ffcd9d8", "Next Milestone Desc. Cur. Comp.", "Next Milestone Description Current Company", "");
			nextMilestoneDescCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyNextMilestone+DescriptionWithReference";
			nextMilestoneDescCurCompany.IsVisible = false;
			nextMilestoneDescCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			nextMilestoneDescCurCompanyInclRelated.CaptionResourceString = Res.GetData("c79e27f7-fb98-43e3-8493-0aa4a04586bc", "Next Milestone Desc. Cur. Comp. (incl Rltd.)", "Next Milestone Description Current Company (incl Related).", "");
			nextMilestoneDescCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyNextMilestone+DescriptionWithReference";
			nextMilestoneDescCurCompanyInclRelated.IsVisible = false;
			nextMilestoneDescCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			zDateEditColumnStyleInfo12.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ac51b0a8-a700-45f8-a08a-6300d25ceb77", "Next Milestone ETD");
			zDateEditColumnStyleInfo12.ColumnName = "WorkflowItems+Milestones+NextMilestone+P9_ScheduledDateForBinding";
			zDateEditColumnStyleInfo13.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|82ee405f-5a9b-4016-9263-646c2aab1014", "Next Milestone ETD (incl Rltd.)", "Next Milestone ETD (incl Related).");
			zDateEditColumnStyleInfo13.ColumnName = "WorkflowItems+MilestonesIncludingRelated+NextMilestone+P9_ScheduledDateForBinding";
			zDateEditColumnStyleInfo13.IsVisible = false;
			zDateEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			nextMilestoneETDCurCompany.CaptionResourceString = Res.GetData("85f596ed-9d47-4c52-b088-84ae7fb46a06", "Next Milestone ETD Cur. Comp.", "Next Milestone ETD Current Company", "");
			nextMilestoneETDCurCompany.ColumnName = "WorkflowItems+Milestones+CurrentCompanyNextMilestone+P9_ScheduledDateForBinding";
			nextMilestoneETDCurCompany.IsVisible = false;
			nextMilestoneETDCurCompany.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			nextMilestoneETDCurCompanyInclRelated.CaptionResourceString = Res.GetData("55b5e081-7b35-4df9-9621-ebb3b8e6242e", "Next Milestone ETD Cur. Comp. (incl Rltd.)", "Next Milestone ETD Current Company (incl Related).", "");
			nextMilestoneETDCurCompanyInclRelated.ColumnName = "WorkflowItems+MilestonesIncludingRelated+CurrentCompanyNextMilestone+P9_ScheduledDateForBinding";
			nextMilestoneETDCurCompanyInclRelated.IsVisible = false;
			nextMilestoneETDCurCompanyInclRelated.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(230);
			shipmentStatusDropEditColumnStyleInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			shipmentStatusDropEditColumnStyleInfo.ColumnName = "QuotedBooking+ShipmentStatus";
			shipmentStatusDropEditColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			shipmentStatusDropEditColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|596bc67d-9464-40d9-9130-4ca6f4385991", "Booking Status", "HBL Booking Status", "");
			shipmentStatusDropEditColumnStyleInfo.IsVisible = false;
			shipmentStatusDropEditColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			isHazardousColumnStyleInfo.ColumnName = "QuotedBooking+Booking+IsHazardous";
			isHazardousColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			isHazardousColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|f7cfecf9-9f77-4f93-9158-41dbd0018dcb", "Is Hazardous");
			isHazardousColumnStyleInfo.IsVisible = false;
			isHazardousColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			isTemplateColumnStyleInfo.CaptionResourceString = Res.GetData("80303fb1-b0b4-4223-bdfc-a784fdca909a", "Is Template", "Is Template Record", "Is Template Record for Universal Copy.");
			isTemplateColumnStyleInfo.ColumnName = "IsTemplate";
			isTemplateColumnStyleInfo.Width = 60;
			isTemplateColumnStyleInfo.GroupName = Res.GetData("ec25e449-4c0a-4912-bd70-a1dff4852b83", "Template Records");
			isTemplateColumnStyleInfo.IsVisible = false;
			isTemplateActiveColumnStyleInfo.CaptionResourceString = Res.GetData("8bac5588-f7fe-44ee-a69e-e2affb33e985", "Template Active");
			isTemplateActiveColumnStyleInfo.ColumnName = "TemplateRecord.STR_IsActive";
			isTemplateActiveColumnStyleInfo.GroupName = Res.GetData("ec25e449-4c0a-4912-bd70-a1dff4852b83", "Template Records");
			isTemplateActiveColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			isTemplateActiveColumnStyleInfo.IsVisible = false;
			isTemplateNameColumnStyleInfo.CaptionResourceString = Res.GetData("187ca282-faa2-49d2-a03e-983702c433ec", "Template Name");
			isTemplateNameColumnStyleInfo.ColumnName = "TemplateRecord+STR_TemplateName";
			isTemplateNameColumnStyleInfo.GroupName = Res.GetData("ec25e449-4c0a-4912-bd70-a1dff4852b83", "Template Records");
			isTemplateNameColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			isTemplateNameColumnStyleInfo.IsVisible = false;

			additionalNumbersColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4ccb672b-9460-4d25-84ef-6200c98b8158", "Additional Reference");
			additionalNumbersColumnStyleInfo.ColumnName = "QuotedBooking+Booking+NumbersAsString";
			additionalNumbersColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			additionalNumbersColumnStyleInfo.IsVisible = false;

			isTemperatureControlled.IsVisible = false;
			isTemperatureControlled.IsReadOnly = true;
			isTemperatureControlled.ColumnName = "QuotedBooking+Booking+IsTemperatureControlled";
			isTemperatureControlled.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			isTemperatureControlled.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|8ac46f27-ea24-4d2b-83eb-a2f20197ffff", "Is Temperature Controlled");

			undgClassTextBoxColumnStyleInfo.ColumnName = "QuotedBooking+Booking+JS_Calc_DGClass";
			undgClassTextBoxColumnStyleInfo.IsVisible = false;
			undgClassTextBoxColumnStyleInfo.IsReadOnly = true;
			undgClassTextBoxColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			undgClassTextBoxColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1193BB91-903D-42CD-869E-2C00A9D3BD20", "DG Class");

			undgSubstanceTextBoxColumnStyleInfo.ColumnName = "QuotedBooking+Booking+JS_Calc_DGSubstance";
			undgSubstanceTextBoxColumnStyleInfo.IsVisible = false;
			undgSubstanceTextBoxColumnStyleInfo.IsReadOnly = true;
			undgSubstanceTextBoxColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			undgSubstanceTextBoxColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|42C7B425-A6F8-4674-89C7-440D97A29697", "DG Substance");

			zTextBoxColumnStyleInfo37.ColumnName = "QuotedBooking+Job+Branch+GB_Code";
			zTextBoxColumnStyleInfo37.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|d3351248-4986-4f24-ac95-41901a957d8f", "Branch");
			zTextBoxColumnStyleInfo37.IsVisible = false;
			zTextBoxColumnStyleInfo37.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo38.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|c28db356-e41f-4f83-b80c-8c1a3c62898d", "Consignee Address");
			zTextBoxColumnStyleInfo38.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+AddressAsASingleLine";
			zTextBoxColumnStyleInfo38.IsVisible = false;
			zTextBoxColumnStyleInfo38.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(250);
			zCheckBoxColumnStyleInfo3.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4ce968b1-e514-4301-b604-82c029553879", "CN Override", "Consignee Override Address Values", "The Consignee Override Address Values.");
			zCheckBoxColumnStyleInfo3.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_AddressOverride";
			zCheckBoxColumnStyleInfo3.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zCheckBoxColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo39.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|ef8c9dc3-9aa5-435b-8a9f-71fc1c840ffc", "CN Address 1", "Consignee Address 1", "The Consignee Address Line 1.");
			zTextBoxColumnStyleInfo39.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_Address1";
			zTextBoxColumnStyleInfo39.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zTextBoxColumnStyleInfo39.IsVisible = false;
			zTextBoxColumnStyleInfo39.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo40.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|f590b6b6-b4da-4ced-a5df-0393f19ff3c3", "CN Address 2", "Consignee Address 2", "The Consignee Address Line 2.");
			zTextBoxColumnStyleInfo40.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_Address2";
			zTextBoxColumnStyleInfo40.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zTextBoxColumnStyleInfo40.IsVisible = false;
			zTextBoxColumnStyleInfo41.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|0d3adcba-22f3-41a4-8d8a-8d939ecef150", "CN City", "Consignee City", "The Consignee City.");
			zTextBoxColumnStyleInfo41.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_City";
			zTextBoxColumnStyleInfo41.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zTextBoxColumnStyleInfo41.IsVisible = false;
			zTextBoxColumnStyleInfo42.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|b7e257d4-6db3-4ab9-8059-996a5fdbc520", "CN State", "Consignee State", "The Consignee State.");
			zTextBoxColumnStyleInfo42.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_State";
			zTextBoxColumnStyleInfo42.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zTextBoxColumnStyleInfo42.IsVisible = false;
			zCodeFindBoxColumnStyleInfo5.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|0801d29a-8667-47b5-a86f-2187c8f2e1d2", "CN Country/Region", "Consignee Country/Region Code", "The Consignee Country/Region Code.");
			zCodeFindBoxColumnStyleInfo5.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_RN_NKCountryCode";
			zCodeFindBoxColumnStyleInfo5.GroupName = Res.GetData("QuotedBookingFilterControl|cc254483-83c6-4fb9-aa8c-99c0a33e880a", "Consignee Address Details");
			zCodeFindBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo43.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|e2f5cc17-c935-4cfc-a9fa-e237a83dcbc6", "Consignee Full Name");
			zTextBoxColumnStyleInfo43.ColumnName = "QuotedBooking+ConsigneeDocumentaryAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo43.IsVisible = false;
			zTextBoxColumnStyleInfo43.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(250);
			zTextBoxColumnStyleInfo44.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|6c31c8a7-daf4-4183-a868-035629b82b87", "Controlling Agent");
			zTextBoxColumnStyleInfo44.ColumnName = "QuotedBooking+Booking+ControllingAgent+OH_Code";
			zTextBoxColumnStyleInfo44.IsVisible = false;
			zTextBoxColumnStyleInfo45.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4abf83d5-8954-4733-a71a-71b9cc8144e3", "Controlling Customer");
			zTextBoxColumnStyleInfo45.ColumnName = "QuotedBooking+Booking+ControllingCustomer+OH_Code";
			zTextBoxColumnStyleInfo45.IsVisible = false;
			zTextBoxColumnStyleInfo46.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|28c90566-223a-453d-b254-65fb762cb523", "Dept");
			zTextBoxColumnStyleInfo46.ColumnName = "QuotedBooking+Job+Department+GE_Code";
			zTextBoxColumnStyleInfo46.IsVisible = false;
			zTextBoxColumnStyleInfo46.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			hasGoodsHandlingInstructionsCheckBoxInfo.ColumnName = "QuotedBooking+Booking+NotesChecker+HasGoodsHandlingInstructions";
			hasGoodsHandlingInstructionsCheckBoxInfo.IsVisible = false;
			hasGoodsHandlingInstructionsCheckBoxInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			hasGoodsHandlingInstructionsCheckBoxInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1a6d578c-177f-4b37-a848-a771e1447c3a", "Hand. Instr.", "Has Goods Handling Instructions", "There are Goods Handling Instructions");
			hasSpecialInstructionsCheckBoxInfo.ColumnName = "QuotedBooking+Booking+NotesChecker+HasSpecialInstructions";
			hasSpecialInstructionsCheckBoxInfo.IsVisible = false;
			hasSpecialInstructionsCheckBoxInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			hasSpecialInstructionsCheckBoxInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|8ac46f27-ea24-4d2b-83eb-a2f20197c89e", "Spec. Instr.", "Has Special Instructions", "There are Special Instructions");
			zTextBoxColumnStyleInfo47.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|691ff575-435a-46e1-b9f7-d293f712320f", "Invoice Status");
			zTextBoxColumnStyleInfo47.ColumnName = "QuotedBooking+Job+JH_Status";
			zTextBoxColumnStyleInfo47.IsVisible = false;
			zTextBoxColumnStyleInfo48.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|35ed4988-93dc-407a-94a0-9b6ff38def1d", "Job Operator");
			zTextBoxColumnStyleInfo48.ColumnName = "QuotedBooking+Job+JH_GS_NKRepOps";
			zTextBoxColumnStyleInfo48.IsVisible = false;
			zTextBoxColumnStyleInfo48.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo49.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|5fb00b4f-eef0-49bd-b43a-0ea4412c72c3", "Local Client Address", "The Local Client Address.");
			zTextBoxColumnStyleInfo49.ColumnName = "QuotedBooking+ClientAddr+AddressAsASingleLine";
			zTextBoxColumnStyleInfo49.IsVisible = false;
			zTextBoxColumnStyleInfo50.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|fb08f364-c7ff-4d99-9cde-8f532e230136", "LC Address 1", "Local Client Address 1", "The Local Client Address 1.");
			zTextBoxColumnStyleInfo50.ColumnName = "QuotedBooking+ClientAddr+OA_Address1";
			zTextBoxColumnStyleInfo50.GroupName = Res.GetData("QuotedBookingFilterControl|bb99a04f-6201-4690-9f97-009a1e62219f", "Local Client Address Details");
			zTextBoxColumnStyleInfo50.IsVisible = false;
			zTextBoxColumnStyleInfo51.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|4dc84dae-c250-4354-91bb-7bd8cd0bee10", "LC Address 2", "Local Client Address 2", "The Local Client Address 2.");
			zTextBoxColumnStyleInfo51.ColumnName = "QuotedBooking+ClientAddr+OA_Address2";
			zTextBoxColumnStyleInfo51.GroupName = Res.GetData("QuotedBookingFilterControl|bb99a04f-6201-4690-9f97-009a1e62219f", "Local Client Address Details");
			zTextBoxColumnStyleInfo51.IsVisible = false;
			zTextBoxColumnStyleInfo52.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|6ef076f9-4f90-4447-b009-3feb6076ca6f", "LC City", "Local Client City", "The Local Client City.");
			zTextBoxColumnStyleInfo52.ColumnName = "QuotedBooking+ClientAddr+CityFallback";
			zTextBoxColumnStyleInfo52.GroupName = Res.GetData("QuotedBookingFilterControl|bb99a04f-6201-4690-9f97-009a1e62219f", "Local Client Address Details");
			zTextBoxColumnStyleInfo52.IsVisible = false;
			zTextBoxColumnStyleInfo53.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|83209a1a-e3a0-41d7-96ac-1e72bc077dd1", "LC State", "Local Client State", "The Local Client State.");
			zTextBoxColumnStyleInfo53.ColumnName = "QuotedBooking+ClientAddr+OA_State";
			zTextBoxColumnStyleInfo53.GroupName = Res.GetData("QuotedBookingFilterControl|bb99a04f-6201-4690-9f97-009a1e62219f", "Local Client Address Details");
			zTextBoxColumnStyleInfo53.IsVisible = false;
			zTextBoxColumnStyleInfo54.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|8f2bf97b-a0b4-48dc-82d6-7535110dcdf1", "LC Country/Region", "Local Client Country/Region", "The Local Client Country/Region.");
			zTextBoxColumnStyleInfo54.ColumnName = "QuotedBooking+ClientAddr+RelatedCountry+RN_Code";
			zTextBoxColumnStyleInfo54.GroupName = Res.GetData("QuotedBookingFilterControl|bb99a04f-6201-4690-9f97-009a1e62219f", "Local Client Address Details");
			zTextBoxColumnStyleInfo54.IsVisible = false;
			zTextBoxColumnStyleInfo55.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|662e2412-516b-4b7a-8304-55037df04b2c", "LC Address Short Code", "Local Client Address Short Code", "The Local Client Address Short Code.");
			zTextBoxColumnStyleInfo55.ColumnName = "QuotedBooking+ClientAddr+OA_Code";
			zTextBoxColumnStyleInfo55.IsVisible = false;
			zTextBoxColumnStyleInfo55.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo57.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|19c807e9-2e8e-423d-b461-21936013d188", "Order Numbers");
			zTextBoxColumnStyleInfo57.ColumnName = "QuotedBooking+JS_QuoteBookingGenericOrderNumber";
			zTextBoxColumnStyleInfo57.IsVisible = false;
			zTextBoxColumnStyleInfo57.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo58.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|058f753d-29f5-4a4e-8659-f7fa7e368b7f", "Pickup CFS");
			zTextBoxColumnStyleInfo58.ColumnName = "QuotedBooking+Booking+ExportReceivingDepot+Header+OH_Code";
			zTextBoxColumnStyleInfo58.IsVisible = false;
			zTextBoxColumnStyleInfo58.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo59.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|9e2fa119-9970-4fe4-872a-19b5abb050f4", "Client Contract Number");
			zTextBoxColumnStyleInfo59.ColumnName = "QuotedBooking+Job+JH_ClientContractNumber";
			zTextBoxColumnStyleInfo59.IsVisible = false;
			zTextBoxColumnStyleInfo59.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zOrganisationFindBoxColumnStyleInfoNotifyParty.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|1fe6cfa2-17de-47e6-bad4-37201ccb26b6", "Notify Party");
			zOrganisationFindBoxColumnStyleInfoNotifyParty.ColumnName = "QuotedBooking+Booking+NotifyPartyDocumentaryAddress+Organisation+MainAddress+OA_OH";
			zOrganisationFindBoxColumnStyleInfoNotifyParty.IsVisible = false;
			zTextBoxColumnStyleInfoNotifyParty.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|e3760015-cb37-47b9-b89d-79ca5d869230", "Notify Party Name");
			zTextBoxColumnStyleInfoNotifyParty.ColumnName = "QuotedBooking+Booking+NotifyPartyDocumentaryAddress+Organisation+OH_FullName";
			zTextBoxColumnStyleInfoNotifyParty.IsVisible = false;
			zTextBoxColumnStyleInfoOrderRefs.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|70c68474-d8a2-46fe-b7a6-3ee5ba335a18", "Order References");
			zTextBoxColumnStyleInfoOrderRefs.ColumnName = "QuotedBooking+Booking+DocsAndCartage+JP_OrderItemsAsString";
			zTextBoxColumnStyleInfoOrderRefs.IsVisible = false;
			zTextBoxColumnStyleInfoOrderRefs.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			isDirectColumnStyleInfo.ColumnName = "QuotedBooking+Booking+JS_IsDirectBooking";
			isDirectColumnStyleInfo.Width = 60;
			isDirectColumnStyleInfo.IsVisible = false;
			isOneOffQuoteApprovedInfo.ColumnName = "QuotedBooking+OneOffQuoteApprovalStatus";
			isOneOffQuoteApprovedInfo.IsVisible = true;
			isOneOffQuoteApprovedInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo60.CaptionResourceString = Res.GetData("QuotationsFilterControl|6F4E95C8-480A-4E51-8469-1BB38ED2754B", "Status");
			zTextBoxColumnStyleInfo60.ColumnName = "QuotedBooking+Quote+QuoteStatus";
			zTextBoxColumnStyleInfo60.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo60.IsVisible = false;
			carrierContractNumberColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|522f0aa8-4e42-dea0-47e9-ffcf23a12d33", "Carrier Contract Number");
			carrierContractNumberColumnStyleInfo.ColumnName = "QuotedBooking.CarrierContractNumber";
			carrierContractNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			carrierContractNumberColumnStyleInfo.IsVisible = false;
			allocationIDColumnStyleInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|35d1fd14-2e82-618f-47a3-6cb12dd52144", "Allocation ID");
			allocationIDColumnStyleInfo.ColumnName = "QuotedBooking.AllocationLinePK";
			allocationIDColumnStyleInfo.IsVisible = false;
			isOneOffQuoteAmendmentInfo.ColumnName = "QuotedBooking+OneOffQuoteIsAmended";
			isOneOffQuoteAmendmentInfo.IsVisible = true;
			isOneOffQuoteAmendmentInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo61.ColumnName = "QuotedBooking+Job+JH_HoldReason";
			zTextBoxColumnStyleInfo61.IsVisible = false;
			zTextBoxColumnStyleInfo62.ColumnName = "QuotedBooking+Job+JH_ProfitLossReasonCode";
			zTextBoxColumnStyleInfo62.IsVisible = false;
			zCalcEditColumnStyleInfo14.ColumnName = "QuotedBooking+Job+JH_TotalProfitRevenueMargin";
			zCalcEditColumnStyleInfo14.IsVisible = false;

			startDateColumn.ColumnName = "QuotedBooking+StartDate";
			startDateColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			startDateColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|6a8af8c0-2a6c-4899-8bb9-548767063ebe", "Start Date");
			startDateColumn.IsVisible = false;
			startDateColumn.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;

			endDateColumn.ColumnName = "QuotedBooking+EndDate";
			endDateColumn.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			endDateColumn.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|3df8e369-1a23-4add-a8e3-5ec69b299a6a", "End Date");
			endDateColumn.IsVisible = false;
			endDateColumn.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;

			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoKPI);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoSource);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoRevisionReason);
			this.grid.ColumnStyles.Add(zTextBoxColumnTransportMode);
			this.grid.ColumnStyles.Add(zTextBoxColumnContainerMode);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoCompTariffLevel);
			this.grid.ColumnStyles.Add(zQuotedBookingCommodityInfo);
			this.grid.ColumnStyles.Add(zQuotedBookingFMCTariffIDInfo);
			this.grid.ColumnStyles.Add(zQuotedBookingCreditorInfo);
			this.grid.ColumnStyles.Add(hBlDeliveryModeColumn);

#pragma warning disable IDE0004 // Remove Unnecessary Cast
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((QuotedBooking)(null)).TotalCO2eForSorting)));
			zQuotedBookingCO2Info.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|84f36d52-c027-4602-90e1-8da1fde52d09", "CO2e (kg)");
			zQuotedBookingCO2Info.ColumnName = "QuotedBooking+TotalCO2eForSorting";
			zQuotedBookingCO2Info.IsVisible = false;
			zQuotedBookingCO2Info.IsReadOnly = true;
			zQuotedBookingCO2Info.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zQuotedBookingCO2Info.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);

			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((QuotedBooking)(null)).CO2eStatus)));
			zQuotedBookingCO2StatusInfo.CaptionResourceString = Res.GetData("QuotedBookingFilterControl|54f36d51-c027-4102-90e1-8da1fde52320", "CO2e Status");
			zQuotedBookingCO2StatusInfo.ColumnName = "QuotedBooking+CO2eStatus";
			zQuotedBookingCO2StatusInfo.IsVisible = false;
			zQuotedBookingCO2StatusInfo.IsReadOnly = true;
			zQuotedBookingCO2StatusInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zQuotedBookingCO2StatusInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
#pragma warning restore IDE0004 // Remove Unnecessary Cast

			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zOrganisationFindBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo1);
			this.grid.ColumnStyles.Add(consignorContactColumn);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo13);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo14);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo15);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo16);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo17);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo20);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo22);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo24);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo9);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo25);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo11);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo12);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo13);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo26);
			this.grid.ColumnStyles.Add(zOrganisationFindBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zOrganisationFindBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo27);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo28);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo29);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo30);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo11);
			this.grid.ColumnStyles.Add(lastMilestoneATDCurCompany);
			this.grid.ColumnStyles.Add(lastMilestoneATDCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(lastMilestoneCurCompany);
			this.grid.ColumnStyles.Add(lastMilestoneCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo31);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo32);
			this.grid.ColumnStyles.Add(lastMilestoneDescCurCompany);
			this.grid.ColumnStyles.Add(lastMilestoneDescCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo33);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo34);
			this.grid.ColumnStyles.Add(nextMilestoneCurCompany);
			this.grid.ColumnStyles.Add(nextMilestoneCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo35);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo36);
			this.grid.ColumnStyles.Add(nextMilestoneDescCurCompany);
			this.grid.ColumnStyles.Add(nextMilestoneDescCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo12);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo13);
			this.grid.ColumnStyles.Add(nextMilestoneETDCurCompany);
			this.grid.ColumnStyles.Add(nextMilestoneETDCurCompanyInclRelated);
			this.grid.ColumnStyles.Add(shipmentStatusDropEditColumnStyleInfo);
			this.grid.ColumnStyles.Add(isHazardousColumnStyleInfo);
			this.grid.ColumnStyles.Add(isTemplateColumnStyleInfo);
			this.grid.ColumnStyles.Add(isTemplateActiveColumnStyleInfo);
			this.grid.ColumnStyles.Add(isTemplateNameColumnStyleInfo);
			this.grid.ColumnStyles.Add(additionalNumbersColumnStyleInfo);
			this.grid.ColumnStyles.Add(isTemperatureControlled);
			this.grid.ColumnStyles.Add(undgClassTextBoxColumnStyleInfo);
			this.grid.ColumnStyles.Add(undgSubstanceTextBoxColumnStyleInfo);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo37);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo38);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo39);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo40);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo41);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo42);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo43);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo44);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo45);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo46);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo47);
			this.grid.ColumnStyles.Add(hasGoodsHandlingInstructionsCheckBoxInfo);
			this.grid.ColumnStyles.Add(hasSpecialInstructionsCheckBoxInfo);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo48);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo49);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo50);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo51);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo52);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo53);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo54);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo55);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo57);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo58);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo60);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo61);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo62);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo14);

			if (FreightConfigurationRegistry.Instance.EnableClientContractNumber.Value)
			{
				this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo59);
			}

			if (FreightDataRegistry.Instance.CalculateDeliveryDueDateByTransportMode.Value.IsActive)
			{
				this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo18);
			}

			if (ObjectFactory.Get<ICO2eFeatureControlHelper>().Enabled)
			{
				this.grid.ColumnStyles.Add(zQuotedBookingCO2Info);
				this.grid.ColumnStyles.Add(zQuotedBookingCO2StatusInfo);
			}

			if (ContractsPermissions.IsAllocationsVisible())
			{
				this.grid.ColumnStyles.Add(carrierContractNumberColumnStyleInfo);
				this.grid.ColumnStyles.Add(allocationIDColumnStyleInfo);
			}

			// These columns are only added to OOQ searching module
			if (IsOneOffQuote)
			{
				this.grid.ColumnStyles.Add(startDateColumn);
				this.grid.ColumnStyles.Add(endDateColumn);
				this.grid.ColumnStyles.Add(consigneeContactColumn);
				this.grid.ColumnStyles.Add(clientContactColumn);
			}

			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoNotifyParty);
			this.grid.ColumnStyles.Add(zOrganisationFindBoxColumnStyleInfoNotifyParty);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfoOrderRefs);
			this.grid.ColumnStyles.Add(isDirectColumnStyleInfo);
			this.grid.ColumnStyles.Add(isOneOffQuoteApprovedInfo);
			this.grid.ColumnStyles.Add(isOneOffQuoteAmendmentInfo);
			this.grid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.grid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(758, 174, true);
			//
			// BindingSource
			//
			this.BindingSource.DataSourceType = typeof(ViewQuotedBooking);
			//
			// QuotedBookingFilterControl
			//
			this.CaptionRenderingEnabled = true;
			this.Name = "QuotedBookingFilterControl";
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
	}
}
