<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Customs.IE.EMCS.Business</AssemblyName>
    <RootNamespace>Enterprise.Customs.IE.EMCS.Business</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.IE.MessageContracts" />
    <Reference Include="CargoWise.Customs.IE.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.EMCS.Business" />
    <Reference Include="Enterprise.Customs.IE.Business" />
    <Reference Include="Enterprise.Customs.IE.Messaging" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\EMCSFunctionalErrorCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.EMCS.Business</CustomToolNamespace>
      <LastGenOutput>EMCSFunctionalErrorCodeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGlobalConclusionOfReceiptList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGlobalConclusionOfReceiptList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSNotificationType.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSNotificationType.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EmcsRejectionReasonList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EmcsRejectionReasonList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSReminderMessageType.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.EMCS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSReminderMessageType.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.IE.EMCS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\EMCSFunctionalErrorCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSFunctionalErrorCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGlobalConclusionOfReceiptList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGlobalConclusionOfReceiptList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSNotificationType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSNotificationType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EmcsRejectionReasonList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EmcsRejectionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSReminderMessageType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSReminderMessageType.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>