<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.StlAnalysis.Load.Testing</RootNamespace>
    <AssemblyName>Enterprise.StlAnalysis.Load.Testing</AssemblyName>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Providers.Common.Test" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StlAnalysisLoad\StlAnalysisLoad.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <Reference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
</Project>