@ConfigApi_HostAddress = http://localhost:5029
@Authorization_Header = Basic VVNDOkRNJHBoYXNlMQ==

HEAD {{ConfigApi_HostAddress}}/wtg/alive
Accept: application/json

###
GET {{ConfigApi_HostAddress}}/wtg/status
Accept: application/json

###
GET {{ConfigApi_HostAddress}}/registrations/USC/USI/HYEDUSCMT?qualifier=false
Accept: application/json
Authorization: {{Authorization_Header}}

###
GET {{ConfigApi_HostAddress}}/registrations/USC/USI?value=SV9&qualifier=false
Accept: application/json
Authorization: {{Authorization_Header}}

###
