<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientEDI.GUI</AssemblyName>
    <RootNamespace>ZClientEDI.GUI</RootNamespace>
    <DisableResourceStringsAnalyzer>true</DisableResourceStringsAnalyzer>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <CWUsesDesignRef>true</CWUsesDesignRef>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="System.Resources.Extensions" />
    <PackageReference Include="WTG.AWSCertificateIntegration" />
    <PackageReference Include="WTG.Data.SqlClient.Both" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>