<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Microsoft.Xaml.Behaviors" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Main.Navigation\CargoWise.Main.Navigation.csproj" />
  </ItemGroup>
</Project>