<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CargoWise.Main.Navigation.Test</AssemblyName>
    <RootNamespace>CargoWise.Main.Navigation.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Controls\**" />
    <Compile Remove="Converters\**" />
    <Compile Remove="TestCases\**" />
    <EmbeddedResource Remove="Controls\**" />
    <EmbeddedResource Remove="Converters\**" />
    <EmbeddedResource Remove="TestCases\**" />
    <None Remove="Controls\**" />
    <None Remove="Converters\**" />
    <None Remove="TestCases\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="DragDrop\FrameworkElementDragBehaviorTest.cs" />
    <Compile Remove="DragDrop\ListBoxAdornerManagerTest.cs" />
    <Compile Remove="DragDrop\ListBoxAdornerTest.cs" />
    <Compile Remove="DragDrop\ListBoxDropBehaviorTest.cs" />
    <Compile Remove="DragDrop\UIHelperTest.cs" />
    <Compile Remove="TestExcludeWPFControlFromBasherAttribute.cs" />
    <Compile Remove="UserControlForTesting.xaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="UserControlForTesting.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Main.Navigation" />
  </ItemGroup>
</Project>