<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48</TargetFrameworks>
    <!-- TODO: WI00774883 - CA2213 Triggering when disabled in .editorconfig -->
    <NoWarn>$(NoWarn);CA2213</NoWarn>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <EmbeddedResource Include="Resources\Test\TestFile1.htm" />
    <EmbeddedResource Include="Resources\Test\TestFile2.js" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.DataProtection.SqlExtensions" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="System.Text.Json" />
    <Reference Include="CargoWise.Authentication.Primitives" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWiseOne.WebInfrastructure" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Module" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Warehouse.Environment.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Module" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.GlowInterop" />
    <Reference Include="MimeKit" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Encryption" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="WTG.WebSecurityRightShare" />
    <Reference Include="Enterprise.ZArchitecture.Modules.Testing" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WTG.AppDomainWrappers.Core" />
    <PackageReference Include="WTG.AppDomainWrappers.Runner" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.ZArchitecture.Web.Business.csproj" />
    <ProjectReference Include="..\Business.Test\Enterprise.ZArchitecture.Web.Business.Test.csproj" />
    <ProjectReference Include="..\Utilities.Test\Enterprise.ZArchitecture.Web.Utilities.Test.csproj" />
    <ProjectReference Include="..\Utilities\Enterprise.ZArchitecture.Web.Utilities.csproj" />
    <ProjectReference Include="..\Enterprise.ZArchitecture.Web.Common\Enterprise.ZArchitecture.Web.Common.csproj" />
    <ProjectReference Include="..\GlobalBase\Enterprise.ZArchitecture.Web.GlobalBase.csproj" />
    <ProjectReference Include="..\Shared\Enterprise.ZArchitecture.Web.Shared.csproj" />
    <ProjectReference Include="..\GUI\Enterprise.ZArchitecture.Web.GUI.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.configuration" />
    <Reference Include="System.Design" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>