<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Accounting.CountryCompliance.Implementation</AssemblyName>
    <RootNamespace>Enterprise.Accounting.CountryCompliance.Implementation</RootNamespace>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />

  <ItemGroup>
    <ProjectReference Include="..\Interfaces\Accounting.CountryCompliance.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Resources" />
  </ItemGroup>

  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />

  <ItemGroup>
    <AdditionalFiles Include="..\BannedSymbols.txt" />
  </ItemGroup>

</Project>