// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.Accounting.TestGLProfitAndLossMulitlingualReport.TestReportLocalAccountNumberLengthTakes20Digits")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\Accounting\GLProfitAndLossMulitlingualReport.cs:38:36
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.Accounting.TestGLProfitAndLossMulitlingualReport.TestReportLocalAccountNumberLengthTakes20Digits")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\Accounting\GLProfitAndLossMulitlingualReport.cs:45:36
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.Accounting.TestGLProfitAndLossMulitlingualReport.TestReportLocalAccountNumberLengthTakes20Digits")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\Accounting\GLProfitAndLossMulitlingualReport.cs:52:36
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.Accounting.TestGLProfitAndLossMulitlingualReport.TestReportLocalAccountNumberLengthTakes20Digits")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\Accounting\GLProfitAndLossMulitlingualReport.cs:64:27
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:29:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:30:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:31:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:37:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowNonSTFTypeApplications")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:100:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:61:17
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowNonSTFTypeApplications")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:101:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowNonSTFTypeApplications")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:102:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:69:17
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:77:17
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsEmployedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:142:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsEmployedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:143:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsNotProbationedOrProbationedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:181:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsNotProbationedOrProbationedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:182:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsNotProbationedOrProbationedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:182:79
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsNotProbationedOrProbationedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:183:50
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.MasterFiles.HRMReferredStaffReportTemplateTest.TestHRMReferredStaffReport_DoNotShowStaffsNotProbationedOrProbationedMoreThanOneMonth")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\MasterFiles\HRMReferredStaffReport.cs:183:79
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ReportTesting.Warehouse.TestWhsStockBalancesReport.TestPickAreaDoesNotBreakReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Testing\ReportTesting\ReportTesting\Warehouse\WhsStockBalances.cs:31:86
[assembly: SuppressMessage("CargoWiseOne", "EDI012:UnmaintainableProductNameCSharp", Justification = "Test code", Scope = "namespaceanddescendants", Target = "~N:Enterprise.ReportTesting")]
[assembly: SuppressMessage("CargoWiseOne", "CW1107:UseBusinessObjectFactory", Justification = "Test code", Scope = "namespaceanddescendants", Target = "~N:Enterprise.ReportTesting")]
[assembly: SuppressMessage("CargoWiseOne", "EDI007:CustomisableDataTranslationRule", Justification = "Test code", Scope = "namespaceanddescendants", Target = "~N:Enterprise.ReportTesting")]
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ReportTesting.TemplateTestCase.temporaryExclusionsListForTestIncorrectReportSelectUsage_DO_NOT_ADD_ENTRIES_TO_THIS_LIST")] // Enterprise/Product/Testing/ReportTesting/ReportTesting/TemplateTestCase.cs:596,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ReportTesting.TemplateTestCase.temporaryExclusionsListForTestReportColumnHeadingsExistIfRequired_DO_NOT_ADD_ENTRIES_TO_THIS_LIST")] // Enterprise/Product/Testing/ReportTesting/ReportTesting/TemplateTestCase.cs:626,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ReportTesting.TemplateTestCase.temporaryExclusionsListForTestEnsureSortedReportsDontUseExecCommand_DO_NOT_ADD_ENTRIES_TO_THIS_LIST")] // Enterprise/Product/Testing/ReportTesting/ReportTesting/TemplateTestCase.cs:684,27
