<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Warehouse.Transactions.Module</AssemblyName>
    <RootNamespace>Enterprise.Warehouse.Transactions.Module</RootNamespace>
    <NoWarn>$(NoWarn);CA1416;</NoWarn>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Transactions.GUI\Warehouse.Transactions.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>