//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from TransactionTypeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.NZ.TradeSingleWindow
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class TransactionTypeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Cancel = "1";
			public const string Change = "4";
			public const string Replace = "5";
			public const string Original = "9";
			public const string Receipt = "12";
			public const string Completion = "22";
			public const string Inspection = "23";
			public const string ClearanceInstructions = "24";
			public const string Confirmation = "34";
			public const string CreditAdvice = "37";
			public const string Error = "48";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string Cancel = "Cancel";
			public const string Change = "Change";
			public const string Replace = "Replace";
			public const string Original = "Original";
			public const string Receipt = "Receipt acknowledgment";
			public const string Completion = "Completion";
			public const string Inspection = "Inspection / Audit requirements";
			public const string ClearanceInstructions = "Clearance / Acceptance Instructions";
			public const string Confirmation = "Confirmation of Transaction ";
			public const string CreditAdvice = "Credit advice";
			public const string Error = "Error report";
		}

		public TransactionTypeList()
		{
			AddPair(Codes.Cancel, Descriptions.Cancel);
			AddPair(Codes.Change, Descriptions.Change);
			AddPair(Codes.Replace, Descriptions.Replace);
			AddPair(Codes.Original, Descriptions.Original);
			AddPair(Codes.Receipt, Descriptions.Receipt);
			AddPair(Codes.Completion, Descriptions.Completion);
			AddPair(Codes.Inspection, Descriptions.Inspection);
			AddPair(Codes.ClearanceInstructions, Descriptions.ClearanceInstructions);
			AddPair(Codes.Confirmation, Descriptions.Confirmation);
			AddPair(Codes.CreditAdvice, Descriptions.CreditAdvice);
			AddPair(Codes.Error, Descriptions.Error);
		}
	}
}
