// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.IPSArchiveStage.GetNextArchiveSet(CargoWise.Types.ZDateTime)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\IPSArchiveStage.cs:47:30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.PurgeAction.Purge")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\PurgeAction.cs:114:31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.STAArchiveStage.GetNextArchiveSet(CargoWise.Types.ZDateTime)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\STAArchiveStage.cs:66:31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveStage.GetWatermarkDate(Enterprise.ArchiveManager.Integration.IArchiveSet)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveStage.cs:82:30
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveSet.Load(Enterprise.ArchiveManager.Integration.IArchiveLogger)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveSet.cs:119:32
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveStage.GetNextArchiveSet(CargoWise.Types.ZDateTime)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveStage.cs:146:31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveSet.ExamineRemainsOfTempDatabaseForLogging")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveSet.cs:239:31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveSet.MarkToIgnoreForThisRun")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveSet.cs:284:30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveSet.Load(Enterprise.ArchiveManager.Integration.IArchiveLogger)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveSet.cs:98:33
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveSet.Load(Enterprise.ArchiveManager.Integration.IArchiveLogger)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\ArchiveSet.cs:132:34
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveStages.PDOPurgeStage.ExecuteGetNextArchiveSetQuery(System.String,CargoWise.Types.ZDateTime,System.Collections.Generic.List{Enterprise.ArchiveManager.Engine.ArchiveSet},CargoWise.EntityFramework.ZQuery)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ArchiveManager\Engine\Engine\PDOPurgeStage.cs:130:44
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Temp table manipulation requires direct sql", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveTableHelper.CreateTempTables(Enterprise.ArchiveManager.Engine.ArchiveStage)")]
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Temp table manipulation requires direct sql", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveTableHelper.MarkPKAsIgnored(System.Guid)")]
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Performing operations on queue table for which no bizo exists", Scope = "member", Target = "~M:Enterprise.ArchiveManager.Engine.ArchiveStage.RunDriverIfNecessary(CargoWise.Types.ZDateTime,Enterprise.ArchiveManager.Integration.IArchiveSchedule,Enterprise.ArchiveManager.Integration.IArchiveStage)~System.Boolean")]
