<Project>
  <ItemGroup>
    <Reference Include="Aga.Business" />
    <Reference Include="Aga.Controls" />
    <Reference Include="CargoWise.ActiveDirectory" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.BrandManager" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.FeatureControl.Abstractions" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Glow.CW.ApplicationCheckpoints" />
    <Reference Include="CargoWise.Glow.CW.ApplicationCheckpoints.DevIntegration" />
    <Reference Include="CargoWise.Glow.Model.Interfaces" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Macros" />
    <Reference Include="CargoWise.Macros.GUI" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.RefDataRepo.Ent.Client" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Tools.DuplicateDetector" />
    <Reference Include="CargoWise.Tools.DuplicateDetector.Common" />
    <Reference Include="CargoWise.Tools.DuplicateDetector.Standard.Common" />
    <Reference Include="CargoWise.Tools.TextStandardizer" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="CargoWise.Workflow" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.BufferManagement.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Business" />
    <Reference Include="Enterprise.ComplianceRisk.GUI" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.DataTransfer.Common.GUI" />
    <Reference Include="Enterprise.DataTransfer.Native.Integration" />
    <Reference Include="Enterprise.DeniedPartyScreening.Business" />
    <Reference Include="Enterprise.DeniedPartyScreening.Common" />
    <Reference Include="Enterprise.DeniedPartyScreening.GUI" />
    <Reference Include="Enterprise.DeniedPartyScreening.Integration" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentScanning.Business" />
    <Reference Include="Enterprise.DocumentScanning.Integration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.eTail.Integration" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.Macro" />
    <Reference Include="Enterprise.MarketingManager.Integration" />
    <Reference Include="Enterprise.MasterData.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.GUI" />
    <Reference Include="Enterprise.OutlookUtilities" />
    <Reference Include="Enterprise.ProcessManagement.Integration" />
    <Reference Include="Enterprise.Rating.Business" />
    <Reference Include="Enterprise.Recruiter.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Registry.GUI" />
    <Reference Include="Enterprise.Scheduler.Business" />
    <Reference Include="Enterprise.Security" />
    <Reference Include="Enterprise.Security.ActiveDirectory.Integration" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.ServiceManager.Business" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="Enterprise.TimeEngineScheduler.Integration" />
    <Reference Include="Enterprise.TrustedMessaging.Intergration" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.Upgrades" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.Workflow.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Favorites" />
    <Reference Include="Enterprise.ZArchitecture.GlowInterop" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.BrowserInterop" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="MailManager" />
    <Reference Include="Resources" />
    <Reference Include="WTG.AddressCleansing.Common" />
    <Reference Include="WTG.CreditCheck.Common" />
    <Reference Include="WTG.DevTools.ServiceClient.Assess" />
    <Reference Include="WTG.DevTools.ServiceClient.Common" />
    <Reference Include="WTG.ROPE.Model" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
    <Reference Include="WTG.WiseTechAcademy" />
  </ItemGroup>
</Project>