<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.UniversalDataBuss.DataObjects</RootNamespace>
    <AssemblyName>Enterprise.UniversalDataBuss.DataObjects</AssemblyName>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\UniversalDataBuss.Management\Matching\CombinationKeyMatcher.cs">
      <Link>CombinationKeyMatcher.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\CombinationKeyMatcherCore.cs">
      <Link>CombinationKeyMatcherCore.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\IMatchWithScore.cs">
      <Link>IMatchWithScore.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\IModuleMatcher.cs">
      <Link>IModuleMatcher.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\MatchingScorer.cs">
      <Link>MatchingScorer.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\ModuleMatcher.cs">
      <Link>ModuleMatcher.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\PotentialMatch.cs">
      <Link>PotentialMatch.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\Score.cs">
      <Link>Score.cs</Link>
    </Compile>
    <Compile Include="..\UniversalDataBuss.Management\Matching\ScoreResult.cs">
      <Link>ScoreResult.cs</Link>
    </Compile>
    <Compile Update="DataObjects\UniversalSchedule\ScheduleAuto.cs">
      <DependentUpon>Schedule.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\AWB\AWBHeaderAuto.cs">
      <DependentUpon>AWBHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\ContainerAuto.cs">
      <DependentUpon>Container.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\DocumentDataAuto.cs">
      <DependentUpon>DocumentData.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\InstructionAuto.cs">
      <DependentUpon>Instruction.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\PackingLineAuto.cs">
      <DependentUpon>PackingLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\ShipmentAuto.cs">
      <DependentUpon>Shipment.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\WayBillTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>WayBillTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalActivity\ActivityAuto.cs">
      <DependentUpon>Activity.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\ConversationAuto.cs">
      <DependentUpon>Conversation.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\DocumentTrackingAuto.cs">
      <DependentUpon>DocumentTracking.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\TaskSetAuto.cs">
      <DependentUpon>TaskSet.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalDocument\DocumentRequestAuto.cs">
      <DependentUpon>DocumentRequest.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalInterchangeRequeueRequest\UniversalInterchangeRequeueRequestAuto.cs">
      <DependentUpon>UniversalInterchangeRequeueRequest.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CustomsSupportingInformationAuto.cs">
      <DependentUpon>CustomsSupportingInformation.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\ConsolCostsAuto.cs">
      <DependentUpon>ConsolCosts.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\ConsolCostLineAuto.cs">
      <DependentUpon>ConsolCostLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\OriginalReferenceAuto.cs">
      <DependentUpon>OriginalReference.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalEvent\AdditionalContextAuto.cs">
      <DependentUpon>AdditionalContext.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalEvent\AttachedDocumentAuto.cs">
      <DependentUpon>AttachedDocument.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\DataContext\2012_03\WorkflowAuto.cs">
      <DependentUpon>Workflow.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\AWB\CargoSecurityDeclarationAuto.cs">
      <DependentUpon>CargoSecurityDeclaration.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\EntryInstructionAuto.cs">
      <DependentUpon>EntryInstruction.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\LandedCost\LandedCostDetailAuto.cs">
      <DependentUpon>LandedCostDetail.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\InBondMoveDetailAuto.cs">
      <DependentUpon>InBondMoveDetail.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\InBondMoveLineItemAuto.cs">
      <DependentUpon>InBondMoveLineItem.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\InBondMoveHeaderAuto.cs">
      <DependentUpon>InBondMoveHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\TransactionBatchAuto.cs">
      <DependentUpon>TransactionBatch.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\ChargeLineAuto.cs">
      <DependentUpon>ChargeLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\CashAdvanceRequestHeaderAuto.cs">
      <DependentUpon>CashAdvanceRequestHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\CashAdvanceRequestLineAuto.cs">
      <DependentUpon>CashAdvanceRequestLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\ImportMetaDataAuto.cs">
      <DependentUpon>ImportMetaData.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\JobCostingAuto.cs">
      <DependentUpon>JobCosting.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\TransactionInfoAuto.cs">
      <DependentUpon>TransactionInfo.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\PostingJournalAuto.cs">
      <DependentUpon>PostingJournal.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Order\OrderLineAuto.cs">
      <DependentUpon>OrderLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Order\OrderAuto.cs">
      <DependentUpon>Order.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\OrganizationAddressAuto.cs">
      <DependentUpon>OrganizationAddress.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalEvent\ContextAuto.cs">
      <DependentUpon>Context.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalEvent\EventAuto.cs">
      <DependentUpon>Event.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\AdditionalBillAuto.cs">
      <DependentUpon>AdditionalBill.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalCommon\UNDGAuto.cs">
      <DependentUpon>UNDG.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\HazardousMaterialAuto.cs">
      <DependentUpon>HazardousMaterial.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CustomsReferenceAuto.cs">
      <DependentUpon>CustomsReference.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\AddInfoGroupAuto.cs">
      <DependentUpon>AddInfoGroup.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\AdditionalLineTariffDetailAuto.cs">
      <DependentUpon>AdditionalLineTariffDetail.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CommercialInfoAuto.cs">
      <DependentUpon>CommercialInfo.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CommercialInvoiceHeaderAuto.cs">
      <DependentUpon>CommercialInvoiceHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CommercialInvoiceLineAuto.cs">
      <DependentUpon>CommercialInvoiceLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\EntryHeaderAuto.cs">
      <DependentUpon>EntryHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\EntryLineAuto.cs">
      <DependentUpon>EntryLine.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\LocalProcessingAuto.cs">
      <DependentUpon>LocalProcessing.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Transport\TransportLegAuto.cs">
      <DependentUpon>TransportLeg.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\TransportMeansAuto.cs">
      <DependentUpon>TransportMeans.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\Accounting\TaxFramework\TaxTransactionAuto.cs">
      <DependentUpon>TaxTransaction.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\VehicleRunAuto.cs">
      <DependentUpon>VehicleRun.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\MessageProfile\SchemaFilterAuto.cs">
      <DependentUpon>SchemaFilter.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\BillScreeningAuto.cs">
      <DependentUpon>BillScreening.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\Customs\CustomsValueInformationAuto.cs">
      <DependentUpon>CustomsValueInformation.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\ConfirmationAuto.cs">
      <DependentUpon>Confirmation.cs</DependentUpon>
    </Compile>
    <Compile Update="DataObjects\UniversalShipment\CO2e\GreenhouseGasEmissionAuto.cs">
      <DependentUpon>GreenhouseGasEmission.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="DataObjects\UniversalShipment\WayBillTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>WayBillTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.UniversalDataBuss.DataObjects.Universal</CustomToolNamespace>
    </None>
  </ItemGroup>
  <!--HACK: This import is required, but was made conditional to accomodate `TestAllCollectionPropertiesSettersAreLazy` which can't find the targets file. ref: CS01808108-->
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" Condition="Exists('$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets')" />
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>