<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Enterprise.MasterFiles.Module.Testing</RootNamespace>
    <AssemblyName>Enterprise.MasterFiles.Module.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\MasterFiles.GUI.Test\MasterFiles.GUI.Test.csproj" />
    <ProjectReference Include="..\MasterFiles.Module\MasterFiles.Module.csproj" />
    <ProjectReference Include="..\GUI\MasterFiles.GUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>