// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1068:Do Not Use Math.Round", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.Testing.DutyCalculatorStrategyTest.TestDutyAndTaxCalculation_ForImportUsingRebateCalculatorWithIsSpecifiedMotorVehicle")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/Business/LineMerger/DutyCalculatorStrategyTest.cs:1456,50
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.Testing.AsycudaManifestHeaderTest.TestSavingSetsJobReference")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/Business/AsycudaManifestHeader/AsycudaManifestHeaderTest.cs:636,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.Testing.AsycudaManifestHeaderTest.TestSavingSetsJobReference")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/Business/AsycudaManifestHeader/AsycudaManifestHeaderTest.cs:646,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.Testing.AsycudaManifestHeaderJobReferenceTest.TestOnSavingSetAMA_JobReference_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/Business/AsycudaManifestHeader/AsycudaManifestHeaderJobReferenceTest.cs:17,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.Testing.AsycudaManifestHeaderJobReferenceTest.TestOnSavingSetAMA_JobReference_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/Business/AsycudaManifestHeader/AsycudaManifestHeaderJobReferenceTest.cs:23,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ZA.Business.MessageManagers.DocumentSending.Testing.SupportingDocSendingManagerTests.TestSupportingDocSendingManagerConcurrencyException_CloseStream")] // Enterprise/Product/Operations/Customs/ZA/Business.Test/MessageManagers/DocumentSending/SupportingDocSendingManagerTests.cs:50,26
[assembly: SuppressMessage("Style", "IDE0001:Simplify Names", Justification = "Preserving intended hierarchy", Scope = "type", Target = "~M:Enterprise.Customs.ZA.Business.Testing.OrgSupplierPartDataLoadTest.TestImportingCountrySpecificFields")]
