// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.GlbStaffTest.CreateLockoutUserRecord(Enterprise.MasterFiles.Business.GlbStaff,System.Int32)~Enterprise.ZArchitecture.Business.StmLoginFailureLog")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.AccTransactionLinesTestCase.TestResetWIPReverseDateErrorMessage")] // Enterprise/Product/Operations/MasterFiles/Business/Business.Testing/Accounting/Transaction/AccTransactionLines/AccTransactionLinesTestCase.cs:1015:34
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.AccTransactionLinesTestCase.TestResetACRReverseDateErrorMessage")] // Enterprise/Product/Operations/MasterFiles/Business/Business.Testing/Accounting/Transaction/AccTransactionLines/AccTransactionLinesTestCase.cs:1066:31
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.AccTransactionLinesTestCase.TestSetReverseDateBeforeUnlinkChargeSuspenderIsSuspended")] // Enterprise/Product/Operations/MasterFiles/Business/Business.Testing/Accounting/Transaction/AccTransactionLines/AccTransactionLinesTestCase.cs:1458:38
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.GetUNLOCO(System.String)~Enterprise.MasterFiles.Business.RefUNLOCO")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestCompanyProxies")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestContactToSuppressedDocs_DontAccessOnNewOrSaving")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestDeleteOrgNoAddressesDoesNotAddNewAddress")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestDeleteVsSecurityCreation")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestDeletingOrgDeletesCompanyData")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestGetStaffAssignmentsForGlbCompany")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestIsProxyOrgOfAnyCompanyActive")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestIsProxyOrgOfAnyOrg")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestIsSameRelatedParty")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestMainAddressOnNullOrgHeader")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestNullOrgHeaderAddressCount")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestOH_CodeReadOnly")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestOrgDataReturnsValidObject")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgHeaderTest.TestSaveAndDeleteBusinessObject")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.SetUp")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestApproveMatchBySupervisorAndSaveAtomically")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestApproveMatchBySupervisorAndSaveAtomically_AfterException")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestApproveMatchBySupervisorAndSaveAtomically_NoConcurrencyFailure")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestCopyDetailsFromParent")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestCopyDetailsToOrganisation")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestCopyDetailsToOrganisation_WithLongFields")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestIsApprovedByOtherUsers")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestLinkedOrgPatternMatchAddressNotCreatedTooEarly")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestManuallySelectedOrganisation")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestMatchAndSaveAtomically")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestMatchAndSaveAtomically_AfterException")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestMatchAndSaveAtomically_NoConcurrencyFailure")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestNotifyNoMatchFoundAndSaveAtomically")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestNotifyNoMatchFoundAndSaveAtomically_AfterException")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestNotifyNoMatchFoundAndSaveAtomically_NoConcurrencyFailure")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestOrganisationsInSimilarMatchesAreDistinct")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestRegistrationNumberNotCreatedIfOwnerCodeIsEmpty")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestShouldCreateTemporaryOrganisation_WhenBothUsersAgreeOnNoMatch")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestShouldCreateTemporaryOrganisation_WhenNoSimilarOrgsFound")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestSimilarOrgMatchesSortedByRank")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest.TestSimilarOrgMatchesSortedByRank_UpdatedWhenOrganisationSaved")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.OrgMatchApprovalTest_NotInTransactioned.TestAddressToBeMatched_DuringSaveTransaction")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.RefCurrencyTest.TestLoadFromForeignCode")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.RefCurrencyTest.TestRateValidationSuspendedWhenCurrencyValidationSuspended")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.RefCurrencyTest.TestSetCustomsRate")]
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.MasterFiles.Business.Testing.RefCurrencyTest.TestUniqueIndexOfExchangeRate")]
