RefAccTaxRate:
  ZAT_SysStartTime:
    StoreGeneratedPattern=Computed
  ZAT_SysEndTime:
    StoreGeneratedPattern=Computed
RefCarrierCode:
  ZZ4_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ4_SysEndTime:
    StoreGeneratedPattern=Computed
RefCarrierCodeAttribute:
  ZZG_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZG_SysEndTime:
    StoreGeneratedPattern=Computed
RefCarrierVesselPivot:
  ZZQ_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZQ_SysEndTime:
    StoreGeneratedPattern=Computed
RefCarrierCodeLanguage:
  ZCL_SysStartTime:
    StoreGeneratedPattern=Computed
  ZCL_SysEndTime:
    StoreGeneratedPattern=Computed
RefCountry:
  RN_SysStartTime:
    StoreGeneratedPattern=Computed
  RN_SysEndTime:
    StoreGeneratedPattern=Computed
RefCountryStates:
  RW_SysStartTime:
    StoreGeneratedPattern=Computed
  RW_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusApplicability:
  ZZT_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZT_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZT_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusAUNexdocECMCode:
  ZY5_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY5_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeList:
  ZZD_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZD_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeListAttribute:
  ZZE_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZE_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeListAttributeName:
  ZXE_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXE_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeListAttributeNameLanguage:
  ZXH_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXH_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeListLanguage:
  ZXA_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXA_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeOrAttributeTransportMode:
  ZZU_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZU_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZU_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeType:
  ZZK_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZK_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCodeTypeLanguage:
  ZXI_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXI_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusCondition:
  ZX1_DataSetCode:
    StoreGeneratedPattern=Computed
  ZX1_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX1_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionType:
  ZX2_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX2_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionLanguage:
  ZXJ_DataSetCode:
    StoreGeneratedPattern=Computed
  ZXJ_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXJ_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionValue:
  ZX3_DataSetCode:
    StoreGeneratedPattern=Computed
  ZX3_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX3_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionValueType:
  ZX4_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX4_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusExcludedTradeGroup:
  ZZC_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZC_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZC_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusMap:
  ZZM_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZM_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusMapType:
  ZZP_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZP_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusNomenclatureGroup:
  ZZ5_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ5_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusNomenclatureGroupNote:
  ZZL_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZL_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusNomenclatureGroupType:
  ZZ9_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ9_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusNomenclatureLanguage:
  ZX8_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX8_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusPreference:
  ZZS_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZS_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusPreferenceLanguage:
  ZX9_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX9_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProcedure:
  ZZ6_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ6_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProcedureAttribute:
  ZXB_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXB_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRate:
  ZZ2_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZ2_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ2_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRateCode:
  ZY1_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY1_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRateCodeLanguage:
  ZXC_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXC_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRateType:
  ZZR_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZR_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRateTypeLanguage:
  ZXT_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXT_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRateUOM:
  ZXG_DataSetCode:
    StoreGeneratedPattern=Computed
  ZXG_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXG_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRuling:
  ZZX_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZX_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusRulingConfig:
  ZZY_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZY_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariff:
  ZZ1_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ1_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffAdditionalCode:
  ZY2_DataSetCode:
    StoreGeneratedPattern=Computed
  ZY2_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY2_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffAdditionalCodeCategory:
  ZY3_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY3_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffAdditionalCodeLanguage:
  ZY4_DataSetCode:
    StoreGeneratedPattern=Computed
  ZY4_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY4_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffAttribute:
  ZZ3_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZ3_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ3_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffBRCharacteristic:
  ZB1_DataSetCode:
    StoreGeneratedPattern=Computed
  ZB1_SysStartTime:
    StoreGeneratedPattern=Computed
  ZB1_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffBRCharacteristicValue:
  ZB2_DataSetCode:
    StoreGeneratedPattern=Computed
  ZB2_SysStartTime:
    StoreGeneratedPattern=Computed
  ZB2_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffBRCharacteristicAttribute:
  ZB3_DataSetCode:
    StoreGeneratedPattern=Computed
  ZB3_SysStartTime:
    StoreGeneratedPattern=Computed
  ZB3_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffLanguage:
  ZX7_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX7_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffNationalCode:
  ZZW_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZW_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffRelationship:
  ZZH_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZH_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffType:
  ZZI_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZI_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffTypeLanguage:
  ZXK_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXK_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTariffUOM:
  ZZ8_DataSetCode:
    StoreGeneratedPattern=Computed
  ZZ8_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZ8_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTaxOrFee:
  ZZF_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZF_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTaxOrFeeType:
  ZX0_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX0_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTradeGroup:
  ZZA_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZA_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTradeGroupCountry:
  ZZB_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZB_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTradeGroupLanguage:
  ZXD_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXD_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusVATApplicability:
  ZX5_DataSetCode:
    StoreGeneratedPattern=Computed
  ZX5_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX5_SysEndTime:
    StoreGeneratedPattern=Computed
RefDataGrouping:
  ZZZ_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZZ_SysEndTime:
    StoreGeneratedPattern=Computed
RefDbVersionControl:
  CreatedTimeUTC:
    StoreGeneratedPattern=Computed
SourceData:
  SDA_CreatedTime:
    StoreGeneratedPattern=Computed
RefDocOrgCusCode:
  DOC_SysStartTime:
    StoreGeneratedPattern=Computed
  DOC_SysEndTime:
    StoreGeneratedPattern=Computed
RefExchangeRateZZ:
  ZZN_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZN_SysEndTime:
    StoreGeneratedPattern=Computed
RefHarbourRate:
  ZXF_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXF_SysEndTime:
    StoreGeneratedPattern=Computed
RefLanguageText:
  RLT_SysStartTime:
    StoreGeneratedPattern=Computed
  RLT_SysEndTime:
    StoreGeneratedPattern=Computed
RefLanguageType:
  ZX6_SysStartTime:
    StoreGeneratedPattern=Computed
  ZX6_SysEndTime:
    StoreGeneratedPattern=Computed
RefLocoMap:
  RY_SysStartTime:
    StoreGeneratedPattern=Computed
  RY_SysEndTime:
    StoreGeneratedPattern=Computed
RefShippingLine:
  RSL_SysStartTime:
    StoreGeneratedPattern=Computed
  RSL_SysEndTime:
    StoreGeneratedPattern=Computed
RefShippingLineMessagingRequirement:
  RSR_SysStartTime:
    StoreGeneratedPattern=Computed
  RSR_SysEndTime:
    StoreGeneratedPattern=Computed
RefShippingLineEBLProvider:
  RSE_SysStartTime:
    StoreGeneratedPattern=Computed
  RSE_SysEndTime:
    StoreGeneratedPattern=Computed
RefShippingLineMessagingRequirementType:
  RST_SysStartTime:
    StoreGeneratedPattern=Computed
  RST_SysEndTime:
    StoreGeneratedPattern=Computed
RefTimeZone:
  R2_SysStartTime:
    StoreGeneratedPattern=Computed
  R2_SysEndTime:
    StoreGeneratedPattern=Computed
RefTimeZoneRule:
  R4_DataSetCode:
    StoreGeneratedPattern=Computed
  R4_SysStartTime:
    StoreGeneratedPattern=Computed
  R4_SysEndTime:
    StoreGeneratedPattern=Computed
RefTimeZoneSet:
  R3_SysStartTime:
    StoreGeneratedPattern=Computed
  R3_SysEndTime:
    StoreGeneratedPattern=Computed
RefUNLOCO:
  RL_SysStartTime:
    StoreGeneratedPattern=Computed
  RL_SysEndTime:
    StoreGeneratedPattern=Computed
RefUNLOCOPortMapping:
  RLM_SysStartTime:
    StoreGeneratedPattern=Computed
  RLM_SysEndTime:
    StoreGeneratedPattern=Computed
RefUNLOCOUtcOffset:
  RLO_SysStartTime:
    StoreGeneratedPattern=Computed
  RLO_SysEndTime:
    StoreGeneratedPattern=Computed
RefUNLOCORelatedPort:
  RLR_SysStartTime:
    StoreGeneratedPattern=Computed
  RLR_SysEndTime:
    StoreGeneratedPattern=Computed
RefVessel:
  RV_SysStartTime:
    StoreGeneratedPattern=Computed
  RV_SysEndTime:
    StoreGeneratedPattern=Computed
RefVesselZZ:
  ZZO_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZO_SysEndTime:
    StoreGeneratedPattern=Computed
RefVesselArrival:
  ZYA_SysStartTime:
    StoreGeneratedPattern=Computed
  ZYA_SysEndTime:
    StoreGeneratedPattern=Computed
StmNote:
  ST_SysStartTime:
    StoreGeneratedPattern=Computed
  ST_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGAttribute:
  DA_SysStartTime:
    StoreGeneratedPattern=Computed
  DA_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGAttributeZZ:
  DAZ_SysStartTime:
    StoreGeneratedPattern=Computed
  DAZ_SysEndTime:
    StoreGeneratedPattern=Computed
  DAZ_ParentPK:
    IsNullable: False
    References:
      - UNDGSubstanceADR
      - UNDGSubstanceRID
      - UNDGSubstanceADN
      - UNDGSubstanceJTT
      - UNDGSubstanceCFR
UNDGCommonData:
  DC_SysStartTime:
    StoreGeneratedPattern=Computed
  DC_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGReference:
  DR_SysStartTime:
    StoreGeneratedPattern=Computed
  DR_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstance:
  DG_SysStartTime:
    StoreGeneratedPattern=Computed
  DG_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstanceADR:
  ADR_SysStartTime:
    StoreGeneratedPattern=Computed
  ADR_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstanceRID:
  RID_SysStartTime:
    StoreGeneratedPattern=Computed
  RID_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstanceADN:
  ADN_SysStartTime:
    StoreGeneratedPattern=Computed
  ADN_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstanceJTT:
  JTT_SysStartTime:
    StoreGeneratedPattern=Computed
  JTT_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGSubstanceCFR:
  CFR_SysStartTime:
    StoreGeneratedPattern=Computed
  CFR_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionTypeLanguage:
  ZXW_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXW_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionValueTypeLanguage:
  ZXX_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXX_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProcedureLanguage:
  ZXV_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXV_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusTaxOrFeeLanguage:
  ZXU_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXU_SysEndTime:
    StoreGeneratedPattern=Computed
RefSysConfigType:
  ZRT_SysStartTime:
    StoreGeneratedPattern=Computed
  ZRT_SysEndTime:
    StoreGeneratedPattern=Computed
RefSysConfig:
  ZRC_SysStartTime:
    StoreGeneratedPattern=Computed
  ZRC_SysEndTime:
    StoreGeneratedPattern=Computed
RefComplianceList:
  RCL_SysStartTime:
    StoreGeneratedPattern=Computed
  RCL_SysEndTime:
    StoreGeneratedPattern=Computed
RefAirline:
  RM_SysStartTime:
    StoreGeneratedPattern=Computed
  RM_SysEndTime:
    StoreGeneratedPattern=Computed
RefPortPolygon:
  RPP_SysStartTime:
    StoreGeneratedPattern=Computed
  RPP_SysEndTime:
    StoreGeneratedPattern=Computed
RefApplicationAttribute:
  RAA_SysStartTime:
    StoreGeneratedPattern=Computed
  RAA_SysEndTime:
    StoreGeneratedPattern=Computed
RefApplicationAttributeType:
  RAT_SysStartTime:
    StoreGeneratedPattern=Computed
  RAT_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGCountryReference:
  DCR_SysStartTime:
    StoreGeneratedPattern=Computed
  DCR_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGCountryReferencePivot:
  DCP_SysStartTime:
    StoreGeneratedPattern=Computed
  DCP_SysEndTime:
    StoreGeneratedPattern=Computed
RefAirlineCommodityCode:
  RAC_SysStartTime:
    StoreGeneratedPattern=Computed
  RAC_SysEndTime:
    StoreGeneratedPattern=Computed
RefAirlineProductCode:
  RAR_SysStartTime:
    StoreGeneratedPattern=Computed
  RAR_SysEndTime:
    StoreGeneratedPattern=Computed
RefAirlineProductCodeCommodityCodePivot:
  RPC_SysStartTime:
    StoreGeneratedPattern=Computed
  RPC_SysEndTime:
    StoreGeneratedPattern=Computed
RefStlScript:
  STL_SysStartTime:
    StoreGeneratedPattern=Computed
  STL_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConfiguration:
  ZZJ_SysStartTime:
    StoreGeneratedPattern=Computed
  ZZJ_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusQuota:
  ZXQ_SysStartTime:
    StoreGeneratedPattern=Computed
  ZXQ_SysEndTime:
    StoreGeneratedPattern=Computed
RefFacility:
  RFT_SysStartTime:
    StoreGeneratedPattern=Computed
  RFT_SysEndTime:
    StoreGeneratedPattern=Computed
RefFacilityLocalCode:
  RFL_SysStartTime:
    StoreGeneratedPattern=Computed
  RFL_SysEndTime:
    StoreGeneratedPattern=Computed
RefStlFieldMapping:
  SFM_SysStartTime:
    StoreGeneratedPattern=Computed
  SFM_SysEndTime:
    StoreGeneratedPattern=Computed 
RefClient:
  RCT_SysStartTime:
    StoreGeneratedPattern=Computed
  RCT_SysEndTime:
    StoreGeneratedPattern=Computed 
RefCusTariffAttributeName:
  ZY6_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY6_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionCode:
  ZY7_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY7_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusConditionCodeLanguage:
  ZY8_SysStartTime:
    StoreGeneratedPattern=Computed
  ZY8_SysEndTime:
    StoreGeneratedPattern=Computed
RefMessagingBussCarrierInfo:
  ZMC_SysStartTime:
    StoreGeneratedPattern=Computed
  ZMC_SysEndTime:
    StoreGeneratedPattern=Computed
RefMessagingBussPackageInfo:
  ZMP_SysStartTime:
    StoreGeneratedPattern=Computed
  ZMP_SysEndTime:
    StoreGeneratedPattern=Computed
RefMessagingBussPackageVersion:
  ZMV_SysStartTime:
    StoreGeneratedPattern=Computed
  ZMV_SysEndTime:
    StoreGeneratedPattern=Computed
RefMaterial:
  RMC_SysStartTime:
    StoreGeneratedPattern=Computed
  RMC_SysEndTime:
    StoreGeneratedPattern=Computed
RefDamage:
  RFM_SysStartTime:
    StoreGeneratedPattern=Computed
  RFM_SysEndTime:
    StoreGeneratedPattern=Computed
RefMRComponentCode:
  RCC_SysStartTime:
    StoreGeneratedPattern=Computed
  RCC_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileType:
  XXX_SysStartTime:
    StoreGeneratedPattern=Computed
  XXX_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfile:
  XX0_SysStartTime:
    StoreGeneratedPattern=Computed
  XX0_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileAttribute:
  XXY_SysStartTime:
    StoreGeneratedPattern=Computed
  XXY_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestion:
  XQ2_SysStartTime:
    StoreGeneratedPattern=Computed
  XQ2_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestionAnswerList:
  XQ4_SysStartTime:
    StoreGeneratedPattern=Computed
  XQ4_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestionAnswerListLanguage:
  XAL_SysStartTime:
    StoreGeneratedPattern=Computed
  XAL_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestionAttribute:
  XQ3_SysStartTime:
    StoreGeneratedPattern=Computed
  XQ3_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestionLanguage:
  XQL_SysStartTime:
    StoreGeneratedPattern=Computed
  XQL_SysEndTime:
    StoreGeneratedPattern=Computed
RefCusProfileQuestionPathway:
  XQP_SysStartTime:
    StoreGeneratedPattern=Computed
  XQP_SysEndTime:
    StoreGeneratedPattern=Computed
RefUnitSection:
  RUS_SysStartTime:
    StoreGeneratedPattern=Computed
  RUS_SysEndTime:
    StoreGeneratedPattern=Computed
RefRepairCode:
  RRC_SysStartTime:
    StoreGeneratedPattern=Computed
  RRC_SysEndTime:
    StoreGeneratedPattern=Computed
RefAccElectronicProcessingFee:
  EPF_SysStartTime:
    StoreGeneratedPattern=Computed
  EPF_SysEndTime:
    StoreGeneratedPattern=Computed
RefEquipmentGrade:
  REG_SysStartTime:
    StoreGeneratedPattern=Computed
  REG_SysEndTime:
    StoreGeneratedPattern=Computed
RefGlbReleaseNote:
  ZGF_SysStartTime:
    StoreGeneratedPattern=Computed
  ZGF_SysEndTime:
    StoreGeneratedPattern=Computed
RefComplianceCommodityAlert:
  RCR_SysStartTime:
    StoreGeneratedPattern=Computed
  RCR_SysEndTime:
    StoreGeneratedPattern=Computed
UNDGVersion:
  DV_SysStartTime:
    StoreGeneratedPattern=Computed
  DV_SysEndTime:
    StoreGeneratedPattern=Computed
RefAccessorial:
  ASI_SysStartTime:
    StoreGeneratedPattern=Computed
  ASI_SysEndTime:
    StoreGeneratedPattern=Computed
