<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 33000
 -->
	<xsd:element name="meursingSubheading">
        <xsd:complexType>
            <!-- Meursing table plan id -->
            <xsd:attribute ref="at:meursingTablePlanId"/>
            <!-- Meursing heading number -->
            <xsd:attribute ref="at:headingNumber"/>
            <!-- Row/column code -->
            <xsd:attribute ref="at:rowColumnCode"/>
            <!-- Meursing subheading sequence number -->
            <xsd:attribute ref="at:subheadingSequenceNumber"/>
            <!-- Validity start date of Meursing subheading -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of Meursing subheading -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Short description of Meursing subheading -->
            <xsd:attribute ref="at:description"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
