<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 32500, 32505, 32510
 -->
	<xsd:element name="meursingHeading">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:meursingHeadingFootnoteAssociation" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="at:meursingHeadingText" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- Meursing table plan id -->
            <xsd:attribute ref="at:meursingTablePlanId"/>
            <!-- Meursing heading number -->
            <xsd:attribute ref="at:headingNumber"/>
            <!-- Row/column code -->
            <xsd:attribute ref="at:rowColumnCode"/>
            <!-- Validity start date of Meursing heading -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of Meursing heading -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="meursingHeadingFootnoteAssociation">
        <xsd:complexType>
            <!-- Footnote type -->
            <xsd:attribute ref="at:footnoteType"/>
            <!-- Footnote id -->
            <xsd:attribute ref="at:footnoteId"/>
            <!-- Start of validity of association between Meursing heading and footnote -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- End of validity of association between Meursing heading and footnote -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="meursingHeadingText">
        <xsd:complexType>
            <!-- Language id of description -->
            <xsd:attribute ref="at:languageId"/>
            <!-- Short description of Meursing heading -->
            <xsd:attribute ref="at:description"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>            
