<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
    <TargetFrameworks>$(CWNetCoreWindowsTargetFramework);net48</TargetFrameworks>
		<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
	</PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
	<ItemGroup>
		<Reference Include="CargoWise.Customs.IL.MessageContracts" />
		<Reference Include="CargoWise.Customs.IL.MessageDefinitions" />
		<Reference Include="CargoWise.Customs.Shared.MessageContracts" />
		<Reference Include="CargoWise.Definitions" />
		<Reference Include="CargoWise.Integration" />
		<Reference Include="CargoWise.Macros" />
		<Reference Include="CargoWise.ResourceStrings.Cache" />
		<Reference Include="CargoWise.Schema" />
		<Reference Include="CargoWise.ComponentModel" />
		<Reference Include="CargoWise.ApplicationContext" />
		<Reference Include="CargoWise.Shared.40" />
		<Reference Include="CargoWise.ResourceStrings" />
		<Reference Include="Enterprise.Billing.Integration" />
		<Reference Include="Enterprise.Customs.DataTransfer" />
		<Reference Include="Enterprise.Customs.DutyCalculator" />
		<Reference Include="Enterprise.Customs.ManifestBase" />
		<Reference Include="Enterprise.Customs.Universal" />
		<Reference Include="Enterprise.DocumentEngineCore" />
		<Reference Include="Enterprise.DocumentEngineIntegration" />
		<Reference Include="Enterprise.DocumentVisualizer.Core" />
		<Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
		<Reference Include="Enterprise.DocumentVisualizer.Integration" />
		<Reference Include="Enterprise.Environment" />
		<Reference Include="Enterprise.Freight.Forwarding.Documents.DataObjects" />
		<Reference Include="Enterprise.Freight.Integration" />
		<Reference Include="Enterprise.Integration" />
		<Reference Include="Enterprise.MasterFiles.Business.Test" />
		<Reference Include="Enterprise.MasterFiles.Integration" />
		<Reference Include="Enterprise.ComplianceRisk.Integration" />
		<Reference Include="Enterprise.Messaging.Business" />
		<Reference Include="Enterprise.Messaging.Integration" />
		<Reference Include="Enterprise.Registry.Business" />
		<Reference Include="Enterprise.Security.Core" />
		<Reference Include="Enterprise.ServiceManager.Shared" />
		<Reference Include="Enterprise.Services.OperationalActions.Integration" />
		<Reference Include="Enterprise.TransportBookings.Shared" />
		<Reference Include="Enterprise.Accounting.Integration" />
		<Reference Include="CargoWise.Data" />
		<Reference Include="Enterprise.Customs.Business" />
		<Reference Include="Enterprise.Customs.Common" />
		<Reference Include="Enterprise.Freight" />
		<Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
		<Reference Include="Enterprise.Freight.Common.Business" />
		<Reference Include="Enterprise.Freight.Forwarding.Business" />
		<Reference Include="Enterprise.MasterData.Common" />
		<Reference Include="Enterprise.MasterFiles.Business" />
		<Reference Include="Enterprise.UniversalDataBuss.Integration" />
		<Reference Include="Enterprise.Warehouse.Integration" />
		<Reference Include="Enterprise.xTMessaging.Business" />
		<Reference Include="Enterprise.ZArchitecture.Core" />
		<Reference Include="Enterprise.xTMessaging.Shared" />
		<Reference Include="Enterprise.ZArchitecture.Modules" />
		<Reference Include="CargoWise.Odyssey.Schema" />
		<Reference Include="Resources" />
		<Reference Include="System.Collections.Immutable" />
		<Reference Include="CargoWise.Types" />
		<Reference Include="Enterprise.ZArchitecture.Business" />
		<Reference Include="CargoWise.EntityFramework" />
		<Reference Include="CargoWise.Common" />
		<Reference Include="System.Memory" />
		<Reference Include="WTG.SecurityRights" />
		<Reference Include="WTG.StaticAnalysis.Annotation" />
		<Reference Include="ServiceManager.Integration.Abstractions" />
		<Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
		<Reference Include="Enterprise.UniversalDataBuss.Integration" />
		<Reference Include="CargoWise.eServices.Encryption.Client.Encryptor" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="CodeDescriptionPairLists\CertificateAuthoritiesList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>CertificateAuthoritiesList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\CusCodeDataTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>CusCodeDataTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILCustomsPackTypeList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ILCustomsPackTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\DeliveryOrderResponseStatusList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DeliveryOrderResponseStatusList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\DigitalSignatureFallbackList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>DigitalSignatureFallbackList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\GatepassFeedbackMessageGatepassStatusList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>GatepassFeedbackMessageGatepassStatusList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\GatepassFeedbackMessageIndicationTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>GatepassFeedbackMessageIndicationTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILEDIMessageSubTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILEDIMessageSubTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILDeclarationMessageSubTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILDeclarationMessageSubTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILDeclarationMessageTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILDeclarationMessageTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILManifestRegistryOptions.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILManifestRegistryOptions.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\CustomsExceptionLevelList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>CustomsExceptionLevelList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILMessageTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILMessageTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\AsycudaBillKindList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AsycudaBillKindList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILAdditionalInfoSubTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>ILAdditionalInfoSubTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\InvoiceTypeList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>InvoiceTypeList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\PaymentTermsList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>PaymentTermsList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\ILRateOverrideReasonList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>ILRateOverrideReasonList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\PeekWayList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>PeekWayList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\RequestedSupportingStatusList.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>RequestedSupportingStatusList.xml</DependentUpon>
		</Compile>
		<Compile Update="CodeDescriptionPairLists\TransportDocsTypeList.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>TransportDocsTypeList.xml</DependentUpon>
		</Compile>
		<None Update="CodeDescriptionPairLists\CertificateAuthoritiesList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>CertificateAuthoritiesList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\CusCodeDataTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>CusCodeDataTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\CustomsExceptionLevelList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>CustomsExceptionLevelList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILCustomsPackTypeList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>ILCustomsPackTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\DeliveryOrderResponseStatusList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>DeliveryOrderResponseStatusList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\DigitalSignatureFallbackList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>DigitalSignatureFallbackList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\GatepassFeedbackMessageGatepassStatusList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>GatepassFeedbackMessageGatepassStatusList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\GatepassFeedbackMessageIndicationTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>GatepassFeedbackMessageIndicationTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILEDIMessageSubTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILEDIMessageSubTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILDeclarationMessageSubTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILDeclarationMessageSubTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILDeclarationMessageTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILDeclarationMessageTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILManifestRegistryOptions.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILManifestRegistryOptions.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILMessageTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILMessageTypeList.cs</LastGenOutput>
			<CustomToolNamespace>Enterprise.Customs.IL.Business</CustomToolNamespace>
		</None>
		<None Update="CodeDescriptionPairLists\AsycudaBillKindList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>AsycudaBillKindList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILAdditionalInfoSubTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>ILAdditionalInfoSubTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\InvoiceTypeList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>InvoiceTypeList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\PaymentTermsList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>PaymentTermsList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\ILRateOverrideReasonList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>ILRateOverrideReasonList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\PeekWayList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>PeekWayList.cs</LastGenOutput>
		  <CustomToolNamespace>Enterprise.Customs.IL.Business</CustomToolNamespace>
		</None>
		<None Update="CodeDescriptionPairLists\RequestedSupportingStatusList.xml">
		  <Generator>CodeDescriptionPairListGenerator</Generator>
		  <LastGenOutput>RequestedSupportingStatusList.cs</LastGenOutput>
		</None>
		<None Update="CodeDescriptionPairLists\TransportDocsTypeList.xml">
			<Generator>CodeDescriptionPairListGenerator</Generator>
			<LastGenOutput>TransportDocsTypeList.cs</LastGenOutput>
		</None>
	</ItemGroup>
	<ItemGroup>
		<WCFMetadata Include="Connected Services\" />
	</ItemGroup>
	<Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
