using CargoWise.EntityFramework.Testing;
using Enterprise.ZArchitecture.Core;

namespace Enterprise.Customs.CN.Business.Testing
{
	class DutyModeListTest : TestCaseWithFactory
	{
		public void TestGetSupportedDutyModesByLevyType()
		{
			var testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "XXX");
			AssertEquals(9, testItem.Count);
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "101");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "118");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "119");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "201");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "299");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "301");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "307");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "399");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "401");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "402");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "403");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "405");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "406");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "407");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "408");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "409");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "412");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "413");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "417");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "418");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "419");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "420");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "421");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "422");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "423");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "499");
			AssertEquals(3, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "501");
			AssertEquals(2, testItem.Count);
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "502");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "503");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "506");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "510");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "601");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "602");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "603");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "605");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "606");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "608");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "609");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "611");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "698");
			AssertEquals(3, testItem.Count);
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "789");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "799");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "801");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "802");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "803");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "811");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "818");
			AssertEquals(4, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("5"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "819");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "888");
			AssertEquals(1, testItem.Count);
			Assert(testItem.ContainsCode("4"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "898");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "899");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "997");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("5"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "998");
			AssertEquals(5, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("5"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "999");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "426");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
			testItem = DutyModeList.GetSupportedDutyModesByLevyType(Factory, "927");
			AssertEquals(6, testItem.Count);
			Assert(testItem.ContainsCode("1"));
			Assert(testItem.ContainsCode("2"));
			Assert(testItem.ContainsCode("3"));
			Assert(testItem.ContainsCode("4"));
			Assert(testItem.ContainsCode("6"));
			Assert(testItem.ContainsCode("7"));
		}

		public void TestGetDutyFraction()
		{
			AssertEquals(1m, DutyModeList.GetDutyFraction(DutyModeList.Codes._1));
			AssertEquals(0.5m, DutyModeList.GetDutyFraction(DutyModeList.Codes._2));
			AssertEquals(0m, DutyModeList.GetDutyFraction(DutyModeList.Codes._3));
			AssertEquals(0m, DutyModeList.GetDutyFraction(DutyModeList.Codes._4));
			AssertEquals(1m, DutyModeList.GetDutyFraction(DutyModeList.Codes._5));
			AssertEquals(1m, DutyModeList.GetDutyFraction(DutyModeList.Codes._6));
			AssertEquals(1m, DutyModeList.GetDutyFraction(DutyModeList.Codes._7));
			AssertEquals(0.5m, DutyModeList.GetDutyFraction(DutyModeList.Codes._8));
			AssertEquals(1m, DutyModeList.GetDutyFraction(DutyModeList.Codes._9));
			Assert("Duty mode list should not be translatable", new DutyModeList() is UntranslatableCodeDescriptionPairList);
		}

		public void TestGetVATFraction()
		{
			AssertEquals(1m, DutyModeList.GetVATFraction(DutyModeList.Codes._1));
			AssertEquals(0.5m, DutyModeList.GetVATFraction(DutyModeList.Codes._2));
			AssertEquals(0m, DutyModeList.GetVATFraction(DutyModeList.Codes._3));
			AssertEquals(1m, DutyModeList.GetVATFraction(DutyModeList.Codes._4));
			AssertEquals(1m, DutyModeList.GetVATFraction(DutyModeList.Codes._5));
			AssertEquals(1m, DutyModeList.GetVATFraction(DutyModeList.Codes._6));
			AssertEquals(1m, DutyModeList.GetVATFraction(DutyModeList.Codes._7));
			AssertEquals(0.5m, DutyModeList.GetVATFraction(DutyModeList.Codes._8));
			AssertEquals(0m, DutyModeList.GetVATFraction(DutyModeList.Codes._9));
		}

		public void TestGetExciseFraction()
		{
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._1));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._2));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._3));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._4));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._5));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._6));
			AssertEquals(1m, DutyModeList.GetExciseFraction(DutyModeList.Codes._7));
			AssertEquals(0m, DutyModeList.GetExciseFraction(DutyModeList.Codes._8));
			AssertEquals(0m, DutyModeList.GetExciseFraction(DutyModeList.Codes._9));
		}

		public void TestGetDutyFractionForVAT()
		{
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._1));
			AssertEquals(0.5m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._2));
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._3));
			AssertEquals(0m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._4));
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._5));
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._6));
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._7));
			AssertEquals(1.5m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._8));
			AssertEquals(1m, DutyModeList.GetDutyFractionForVAT(DutyModeList.Codes._9));
		}
	}
}
