using System.Linq;
using CargoWise.EntityFramework.Testing;

namespace Enterprise.Customs.CN.Business.Testing
{
	class LevyTypeListTest : TestCaseWithFactory
	{
		public void TestGetProcedureCodeOnlyAllowEmptyLevyType()
		{
			var list = LevyTypeList.GetProcedureCodeOnlyAllowEmptyLevyType(true);
			AssertEquals(20, list.Length);
			Assert(list.Contains(CNRefCusProcedure.Codes._0255));
			Assert(list.Contains(CNRefCusProcedure.Codes._0258));
			Assert(list.Contains(CNRefCusProcedure.Codes._0300));
			Assert(list.Contains(CNRefCusProcedure.Codes._0456));
			Assert(list.Contains(CNRefCusProcedure.Codes._0654));
			Assert(list.Contains(CNRefCusProcedure.Codes._0657));
			Assert(list.Contains(CNRefCusProcedure.Codes._0700));
			Assert(list.Contains(CNRefCusProcedure.Codes._1233));
			Assert(list.Contains(CNRefCusProcedure.Codes._1234));
			Assert(list.Contains(CNRefCusProcedure.Codes._4400));
			Assert(list.Contains(CNRefCusProcedure.Codes._4600));
			Assert(list.Contains(CNRefCusProcedure.Codes._0500));
			Assert(list.Contains(CNRefCusProcedure.Codes._1200));
			Assert(list.Contains(CNRefCusProcedure.Codes._4500));
			Assert(list.Contains(CNRefCusProcedure.Codes._5000));
			Assert(list.Contains(CNRefCusProcedure.Codes._5033));
			Assert(list.Contains(CNRefCusProcedure.Codes._5034));
			Assert(list.Contains(CNRefCusProcedure.Codes._5100));
			Assert(list.Contains(CNRefCusProcedure.Codes._5300));
			Assert(list.Contains(CNRefCusProcedure.Codes._6033));
			list = LevyTypeList.GetProcedureCodeOnlyAllowEmptyLevyType(false);
			AssertEquals(22, list.Length);
			Assert(list.Contains(CNRefCusProcedure.Codes._0255));
			Assert(list.Contains(CNRefCusProcedure.Codes._0258));
			Assert(list.Contains(CNRefCusProcedure.Codes._0300));
			Assert(list.Contains(CNRefCusProcedure.Codes._0456));
			Assert(list.Contains(CNRefCusProcedure.Codes._0654));
			Assert(list.Contains(CNRefCusProcedure.Codes._0657));
			Assert(list.Contains(CNRefCusProcedure.Codes._0700));
			Assert(list.Contains(CNRefCusProcedure.Codes._1233));
			Assert(list.Contains(CNRefCusProcedure.Codes._1234));
			Assert(list.Contains(CNRefCusProcedure.Codes._4400));
			Assert(list.Contains(CNRefCusProcedure.Codes._4600));
			Assert(list.Contains(CNRefCusProcedure.Codes._0500));
			Assert(list.Contains(CNRefCusProcedure.Codes._1200));
			Assert(list.Contains(CNRefCusProcedure.Codes._4500));
			Assert(list.Contains(CNRefCusProcedure.Codes._5000));
			Assert(list.Contains(CNRefCusProcedure.Codes._5033));
			Assert(list.Contains(CNRefCusProcedure.Codes._5034));
			Assert(list.Contains(CNRefCusProcedure.Codes._5100));
			Assert(list.Contains(CNRefCusProcedure.Codes._5300));
			Assert(list.Contains(CNRefCusProcedure.Codes._6033));
			Assert(list.Contains(CNRefCusProcedure.Codes._1741));
			Assert(list.Contains(CNRefCusProcedure.Codes._1831));
		}

		public void TestGetProcedureAllowEmptyLevyTypes()
		{
			AssertEquals(37, LevyTypeList.procedureAllowEmptyLevyTypesForImport.Length);
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0245, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0255, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0258, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0300, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0345, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0446, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0456, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0642, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0644, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0654, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0657, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0700, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0744, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0844, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0845, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1233, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1234, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1741, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1831, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3611, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3910, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4400, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4600, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0200, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0400, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0500, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1200, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4500, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5000, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5033, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5034, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5100, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5200, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5300, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._6033, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9600, true));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3939, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0110, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0130, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0139, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0214, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0314, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0320, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0420, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0444, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0445, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0513, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0544, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0545, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0615, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0715, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0815, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1039, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1139, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1210, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1215, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1239, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1300, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1371, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1427, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1500, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1523, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1616, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2025, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2210, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2225, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2439, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2600, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2700, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2939, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3010, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3039, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3100, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3339, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3410, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3511, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3612, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4019, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4039, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4200, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4239, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4539, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4561, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5010, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5014, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5015, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5335, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5361, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9610, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9639, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9700, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9739, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9800, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9839, true));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9900, true));
			AssertEquals(38, LevyTypeList.procedureAllowEmptyLevyTypesForExport.Length);
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0243, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0245, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0255, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0258, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0300, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0345, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0446, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0456, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0642, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0644, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0654, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0657, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0700, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0744, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0844, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0845, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1233, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1234, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1741, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1831, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3611, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3910, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4400, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4600, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0200, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0400, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0500, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1200, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4500, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5000, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5033, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5034, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5100, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5200, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5300, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._6033, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9600, false));
			Assert(LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3939, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0110, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0130, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0139, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0214, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0314, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0320, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0420, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0444, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0445, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0513, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0544, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0545, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0615, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0715, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._0815, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1039, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1139, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1210, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1215, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1239, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1300, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1371, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1427, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1500, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1523, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._1616, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2025, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2210, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2225, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2439, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2600, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2700, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._2939, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3010, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3039, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3100, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3339, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3410, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3511, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._3612, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4019, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4039, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4200, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4239, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4539, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._4561, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5010, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5014, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5015, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5335, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._5361, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9610, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9639, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9700, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9739, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9800, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9839, false));
			Assert(!LevyTypeList.GetProcedureAllowEmptyLevyTypes(CNRefCusProcedure.Codes._9900, false));
		}

		public void TestRequiresManualNo()
		{
			Assert(LevyTypeList.RequiresManualNo("201"));
			Assert(LevyTypeList.RequiresManualNo("401"));
			Assert(LevyTypeList.RequiresManualNo("406"));
			Assert(LevyTypeList.RequiresManualNo("413"));
			Assert(LevyTypeList.RequiresManualNo("417"));
			Assert(LevyTypeList.RequiresManualNo("420"));
			Assert(LevyTypeList.RequiresManualNo("421"));
			Assert(LevyTypeList.RequiresManualNo("422"));
			Assert(LevyTypeList.RequiresManualNo("423"));
			Assert(LevyTypeList.RequiresManualNo("499"));
			Assert(LevyTypeList.RequiresManualNo("501"));
			Assert(LevyTypeList.RequiresManualNo("502"));
			Assert(LevyTypeList.RequiresManualNo("503"));
			Assert(LevyTypeList.RequiresManualNo("506"));
			Assert(LevyTypeList.RequiresManualNo("605"));
			Assert(LevyTypeList.RequiresManualNo("606"));
			Assert(LevyTypeList.RequiresManualNo("608"));
			Assert(LevyTypeList.RequiresManualNo("609"));
			Assert(LevyTypeList.RequiresManualNo("611"));
			Assert(LevyTypeList.RequiresManualNo("789"));
			Assert(LevyTypeList.RequiresManualNo("799"));
			Assert(LevyTypeList.RequiresManualNo("801"));
			Assert(LevyTypeList.RequiresManualNo("802"));
			Assert(LevyTypeList.RequiresManualNo("999"));
			Assert(!LevyTypeList.RequiresManualNo("101"));
			Assert(!LevyTypeList.RequiresManualNo("118"));
			Assert(!LevyTypeList.RequiresManualNo("119"));
			Assert(!LevyTypeList.RequiresManualNo("299"));
			Assert(!LevyTypeList.RequiresManualNo("301"));
			Assert(!LevyTypeList.RequiresManualNo("307"));
			Assert(!LevyTypeList.RequiresManualNo("399"));
			Assert(!LevyTypeList.RequiresManualNo("402"));
			Assert(!LevyTypeList.RequiresManualNo("403"));
			Assert(!LevyTypeList.RequiresManualNo("405"));
			Assert(!LevyTypeList.RequiresManualNo("407"));
			Assert(!LevyTypeList.RequiresManualNo("408"));
			Assert(!LevyTypeList.RequiresManualNo("409"));
			Assert(!LevyTypeList.RequiresManualNo("412"));
			Assert(!LevyTypeList.RequiresManualNo("418"));
			Assert(!LevyTypeList.RequiresManualNo("419"));
			Assert(!LevyTypeList.RequiresManualNo("510"));
			Assert(!LevyTypeList.RequiresManualNo("601"));
			Assert(!LevyTypeList.RequiresManualNo("602"));
			Assert(!LevyTypeList.RequiresManualNo("603"));
			Assert(!LevyTypeList.RequiresManualNo("698"));
			Assert(!LevyTypeList.RequiresManualNo("704"));
			Assert(!LevyTypeList.RequiresManualNo("705"));
			Assert(!LevyTypeList.RequiresManualNo("707"));
			Assert(!LevyTypeList.RequiresManualNo("710"));
			Assert(!LevyTypeList.RequiresManualNo("711"));
			Assert(!LevyTypeList.RequiresManualNo("803"));
			Assert(!LevyTypeList.RequiresManualNo("811"));
			Assert(!LevyTypeList.RequiresManualNo("818"));
			Assert(!LevyTypeList.RequiresManualNo("819"));
			Assert(!LevyTypeList.RequiresManualNo("888"));
			Assert(!LevyTypeList.RequiresManualNo("898"));
			Assert(!LevyTypeList.RequiresManualNo("899"));
			Assert(!LevyTypeList.RequiresManualNo("901"));
			Assert(!LevyTypeList.RequiresManualNo("902"));
			Assert(!LevyTypeList.RequiresManualNo("903"));
			Assert(!LevyTypeList.RequiresManualNo("904"));
			Assert(!LevyTypeList.RequiresManualNo("905"));
			Assert(!LevyTypeList.RequiresManualNo("906"));
			Assert(!LevyTypeList.RequiresManualNo("907"));
			Assert(!LevyTypeList.RequiresManualNo("908"));
			Assert(!LevyTypeList.RequiresManualNo("909"));
			Assert(!LevyTypeList.RequiresManualNo("910"));
			Assert(!LevyTypeList.RequiresManualNo("911"));
			Assert(!LevyTypeList.RequiresManualNo("997"));
			Assert(!LevyTypeList.RequiresManualNo("998"));
		}

		public void TestGetSupportedManualTypesByLevyType()
		{
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("201").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("401").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("406").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("413").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("417").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("420").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("421").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("422").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("499").FirstOrDefault());
			AssertEquals("D", LevyTypeList.GetSupportedManualTypesByLevyType("501").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("506").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("605").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("606").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("608").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("609").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("611").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("789").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("799").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("801").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("802").FirstOrDefault());
			AssertEquals("Z", LevyTypeList.GetSupportedManualTypesByLevyType("999").FirstOrDefault());
			AssertNull(LevyTypeList.GetSupportedManualTypesByLevyType("101").FirstOrDefault());
		}

		public void TestGetSupportedLevyTypeList()
		{
			var testListImp = LevyTypeList.GetSupportedLevyTypeList(Factory, true);
			AssertSame(testListImp, LevyTypeList.GetSupportedLevyTypeList(Factory, true));
			var resultList = new LevyTypeList();
			resultList.RemoveCode(LevyTypeList.Codes._510);
			AssertEquals(resultList, testListImp);
			AssertEquals(71, testListImp.Count);
			Assert(testListImp.ContainsCode("426"));
			Assert(testListImp.ContainsCode("927"));
			var testListExp = LevyTypeList.GetSupportedLevyTypeList(Factory, false);
			Assert(!ReferenceEquals(testListImp, testListExp));
			AssertSame(testListExp, LevyTypeList.GetSupportedLevyTypeList(Factory, false));
			AssertEquals(26, testListExp.Count);
			Assert(testListExp.ContainsCode("101"));
			Assert(testListExp.ContainsCode("118"));
			Assert(testListExp.ContainsCode("119"));
			Assert(testListExp.ContainsCode("201"));
			Assert(testListExp.ContainsCode("299"));
			Assert(testListExp.ContainsCode("301"));
			Assert(testListExp.ContainsCode("399"));
			Assert(testListExp.ContainsCode("402"));
			Assert(testListExp.ContainsCode("407"));
			Assert(testListExp.ContainsCode("413"));
			Assert(testListExp.ContainsCode("502"));
			Assert(testListExp.ContainsCode("503"));
			Assert(testListExp.ContainsCode("510"));
			Assert(testListExp.ContainsCode("601"));
			Assert(testListExp.ContainsCode("602"));
			Assert(testListExp.ContainsCode("603"));
			Assert(testListExp.ContainsCode("704"));
			Assert(testListExp.ContainsCode("705"));
			Assert(testListExp.ContainsCode("707"));
			Assert(testListExp.ContainsCode("710"));
			Assert(testListExp.ContainsCode("711"));
			Assert(testListExp.ContainsCode("898"));
			Assert(testListExp.ContainsCode("899"));
			Assert(testListExp.ContainsCode("997"));
			Assert(testListExp.ContainsCode("998"));
			Assert(testListExp.ContainsCode("999"));
		}

		public void TestGetSupportedLevyTypesByProcedureCode()
		{
			var testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "XXX", true);
			AssertEquals(0, testItem.Length);
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0110", true);
			AssertEquals(27, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("405"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("408"));
			Assert(testItem.Contains("409"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("413"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("423"));
			Assert(testItem.Contains("605"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("698"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("888"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			Assert(testItem.Contains("927"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0130", true);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0139", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0200", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0214", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0245", true);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("927"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0314", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0320", true);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("501"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0345", true);
			AssertEquals(20, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0400", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0420", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0444", true);
			AssertEquals(17, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0445", true);
			AssertEquals(17, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0446", true);
			AssertEquals(18, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0513", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0544", true);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0545", true);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0615", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0642", true);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0644", true);
			AssertEquals(8, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("423"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("927"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0715", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0744", true);
			AssertEquals(20, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0815", true);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0844", true);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0845", true);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1039", true);
			AssertEquals(15, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1139", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1210", true);
			AssertEquals(15, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1215", true);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("503"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1239", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1300", true);
			AssertEquals(21, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("888"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1371", true);
			AssertEquals(18, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1427", true);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1500", true);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("605"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("426"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1523", true);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("605"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1616", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1741", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1831", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2025", true);
			AssertEquals(8, testItem.Length);
			Assert(testItem.Contains("405"));
			Assert(testItem.Contains("423"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2210", true);
			AssertEquals(15, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2225", true);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("405"));
			Assert(testItem.Contains("423"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2439", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2600", true);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("605"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2700", true);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2939", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3010", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3039", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3100", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3339", true);
			AssertEquals(20, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("413"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("801"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3410", true);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3511", true);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("201"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3611", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3612", true);
			AssertEquals(10, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("413"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("698"));
			Assert(testItem.Contains("801"));
			Assert(testItem.Contains("802"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3910", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3939", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4019", true);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("506"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4039", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4200", true);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4239", true);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4539", true);
			AssertEquals(23, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("201"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("506"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4561", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5010", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5014", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5015", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5200", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5335", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5361", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9600", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9610", true);
			AssertEquals(15, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9639", true);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9700", true);
			AssertEquals(23, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("201"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("506"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("801"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9739", true);
			AssertEquals(15, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9800", true);
			AssertEquals(21, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("307"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("403"));
			Assert(testItem.Contains("406"));
			Assert(testItem.Contains("412"));
			Assert(testItem.Contains("418"));
			Assert(testItem.Contains("501"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("606"));
			Assert(testItem.Contains("608"));
			Assert(testItem.Contains("609"));
			Assert(testItem.Contains("789"));
			Assert(testItem.Contains("799"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			Assert(testItem.Contains("426"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9839", true);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9900", true);
			AssertEquals(10, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("401"));
			Assert(testItem.Contains("417"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("698"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0110", false);
			AssertEquals(11, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("413"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0130", false);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0139", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0200", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0214", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("502"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0243", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0245", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0265", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0314", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0345", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0400", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0444", false);
			AssertEquals(8, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0445", false);
			AssertEquals(8, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0446", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0466", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0513", false);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0544", false);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0545", false);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0615", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("503"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0642", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0644", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0664", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0715", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("503"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0744", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0815", false);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0844", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0845", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0864", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "0865", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1039", false);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1210", false);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1215", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("503"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1239", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1300", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1371", false);
			AssertEquals(8, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1427", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1500", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "1523", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2210", false);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2600", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "2700", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3010", false);
			AssertEquals(10, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3039", false);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3422", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3511", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("201"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3611", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3910", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "3939", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4019", false);
			AssertEquals(4, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4039", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "4561", false);
			AssertEquals(1, testItem.Length);
			Assert(testItem.Contains("299"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5010", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5014", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5015", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5200", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5335", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "5361", false);
			AssertEquals(3, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9600", false);
			AssertEquals(2, testItem.Length);
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9610", false);
			AssertEquals(6, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9700", false);
			AssertEquals(10, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("601"));
			Assert(testItem.Contains("602"));
			Assert(testItem.Contains("603"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9739", false);
			AssertEquals(7, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("301"));
			Assert(testItem.Contains("399"));
			Assert(testItem.Contains("898"));
			Assert(testItem.Contains("998"));
			Assert(testItem.Contains("999"));
			testItem = LevyTypeList.GetSupportedLevyTypesByProcedureCode(Factory, "9900", false);
			AssertEquals(5, testItem.Length);
			Assert(testItem.Contains("101"));
			Assert(testItem.Contains("299"));
			Assert(testItem.Contains("502"));
			Assert(testItem.Contains("503"));
			Assert(testItem.Contains("999"));
		}
	}
}
