<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.EU.EMCS.Module</AssemblyName>
    <RootNamespace>Enterprise.Customs.EU.EMCS.Module</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.EU.EMCS.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>