<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.ServiceManager.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.ServiceManager.GUI.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="Moq" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceManager.Common\ServiceManager.Common.csproj" />
    <ProjectReference Include="..\ServiceManager.Common.CW\ServiceManager.Common.CW.csproj" />
    <ProjectReference Include="..\ServiceManager.GUI\ServiceManager.GUI.Winzor.csproj" />
    <ProjectReference Include="..\ServiceManager.Host.Abstractions\ServiceManager.Host.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Integration.CW\ServiceManager.Integration.CW.csproj" />
    <ProjectReference Include="..\ServiceManager.Logging.Abstractions\ServiceManager.Logging.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Logging.CW\ServiceManager.Logging.CW.csproj" />
    <ProjectReference Include="..\ServiceManager.Runner\ServiceManager.Runner.csproj" />
    <ProjectReference Include="..\ServiceManager.Runner.Abstractions\ServiceManager.Runner.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Runner.CW\ServiceManager.Runner.CW.csproj" />
    <ProjectReference Include="..\ServiceManager.Shared.Abstractions\ServiceManager.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Shared.CW.Abstractions\ServiceManager.Shared.CW.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Shared.CW\ServiceManager.Shared.CW.csproj" />
    <ProjectReference Include="..\ServiceManager.Integration.Abstractions\ServiceManager.Integration.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Integration.ServiceTasks.CW\ServiceManager.Integration.ServiceTasks.CW.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>