<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Enterprise.MasterFiles.Tracking</RootNamespace>
    <AssemblyName>Enterprise.MasterFiles.Tracking</AssemblyName>
    <TargetFrameworks>net48;$(Temp_CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Shared.40" />
  </ItemGroup>
</Project>