<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.EU.EMCS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>