<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <WTGPaketPackagesRoot>$(MSBuildThisFileDirectory)\packages</WTGPaketPackagesRoot>
    <WTGPaketBuildItemsGroupName>Build</WTGPaketBuildItemsGroupName>
    <WarningLevel>4</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PaketDisableGlobalRestore>true</PaketDisableGlobalRestore>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <WTGIsTestProject Condition="$(MSBuildProjectFile.Contains('.Test.'))">true</WTGIsTestProject>
  </PropertyGroup>

  <!-- Binding redirects -->
  <PropertyGroup Condition="$(MSBuildProjectFile.Contains('.Tests.'))">
    <AutoGenerateBindingRedirects Condition="'$(AutoGenerateBindingRedirects)' == ''">true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType Condition="'$(GenerateBindingRedirectsOutputType)' == ''">true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <PropertyGroup>
    <Company>WiseTech Global</Company>
    <Copyright>Copyright WiseTech Global 2025-2026</Copyright>
    <Product>CargoWise Billing API</Product>
    <AssemblyVersion Condition="'$(QGL_BUILD_VERSION)' != ''">$(QGL_BUILD_VERSION)</AssemblyVersion>
    <AssemblyVersion Condition="'$(QGL_BUILD_VERSION)' == ''">0.0.1.0</AssemblyVersion>
    <AssemblyFileVersion Condition="'$(QGL_BUILD_VERSION)' != ''">$(QGL_BUILD_VERSION)</AssemblyFileVersion>
    <AssemblyFileVersion Condition="'$(QGL_BUILD_VERSION)' == ''" >0.0.1.0</AssemblyFileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)\CommonAssemblyInfo.cs" Link="Properties\CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WTG.BuildConfiguration.Signing" />
    <PackageReference Include="WTG.BuildConfiguration.Analysis.SYSLIB">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>build; contentfiles</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>