<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<_Server>au2wp-sews-401a.wisecloud.zone</_Server>
		<_ServiceName>AuthenticationWindowsService</_ServiceName>
		<_ProfilePropsImported>$true</_ProfilePropsImported>
		<_ServiceDisplayName>Authentication Service New - eServices</_ServiceDisplayName>
		<_DeploymentFolder>c:\eServices\Services</_DeploymentFolder>
		<_BackupFolder>c:\eServices\Backup</_BackupFolder>
		<_EncryptConfigRequired>true</_EncryptConfigRequired>
		<_EncryptedSection>connectionStrings</_EncryptedSection>
		<UserName>s_eServicesDeploy@wisecloud.zone</UserName>
		<Password>goHoYW7XyG0w0LSV0kMlXCswubQGd2U4MEuLlED/pVcKGh/JOUCLcCvfyjxR1KD6H+hcAY4RNyBN12AcQlkgZhWoIBdnYtl4Uo6wkuiImfZSiCfpmcYg+GcHf6NoeqCDRIWOtALeJwaIKe09ISbE//L0iDv8Ao2G3pXJzIG7YOI=</Password>
	</PropertyGroup>
	<ItemGroup>
		<EncryptedPassword Include="$AuthenticationDBPassword$">
			<Value>K8IT7yfQ2dnroYS+OQPlyxv0vrBj1aaIqVqdpsY7tTlKVUpBHNVm+vyk0JVi5oucZQ7JW/obEY6TV89IqlwmYhH+Ww6cFIIv/86dBRnI3x6keNYP2wMwmdhQRVeev2yeWvIsWygfY8WlxyiKvyRuP/TnugfZ4Hk5Id+S81nG9RM=</Value>
		</EncryptedPassword>
		<EncryptedPassword Include="$ediProdDBPassword$">
			<Value>SEuY+ph2A5lT3jwu1eKrmXujv5c1m3COiTbpTN+PJg2KHepwhWxvJ3m6VbRFk1LarnrWVJkahnT7e9KAIkofFMOZshaVKcB0WXWLPy5/Pex35+J9PsA77WphSSfw2fKd4S7hCVAjhTRMfx6oeluzt2bCb+TOJ1LluJwRY5x/aJw=</Value>
		</EncryptedPassword>
	</ItemGroup>
</Project>