//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.MasterFiles.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoGlbMergedPersonValidation : ZValidation
	{
		protected AutoGlbMergedPersonValidation(AutoGlbMergedPerson Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoGlbMergedPersonValidation); }
		}

		/// <summary>
		/// Add more validation to the GlbMergedPerson's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoGlbMergedPersonValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The GlbMergedPerson's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoGlbMergedPersonValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region GMP_MergedPerson

		public void ValidateGMP_MergedPerson()
		{
			ZValidationInternals.Validate(Parent.GMP_MergedPersonInfo, GetGMP_MergedPersonValidationInvoker());
		}

		RunValidationInvoker GetGMP_MergedPersonValidationInvoker()
		{
			return delegate
			{
				CheckGMP_MergedPersonIsNotEmpty();
				CheckGMP_MergedPersonIsValidZGuid();
				CheckGMP_MergedPerson();
			};
		}

		protected virtual void CheckGMP_MergedPersonIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.GMP_MergedPersonInfo);
		}

		protected virtual void CheckGMP_MergedPersonIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.GMP_MergedPersonInfo);
		}

		protected virtual void CheckGMP_MergedPerson()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region GMP_PER_Person

		public void ValidateGMP_PER_Person()
		{
			ZValidationInternals.Validate(Parent.GMP_PER_PersonInfo, GetGMP_PER_PersonValidationInvoker());
		}

		RunValidationInvoker GetGMP_PER_PersonValidationInvoker()
		{
			return delegate
			{
				CheckGMP_PER_PersonIsNotEmpty();
				CheckGMP_PER_PersonIsValidZGuid();
				CheckGMP_PER_Person();
			};
		}

		protected virtual void CheckGMP_PER_PersonIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.GMP_PER_PersonInfo);
		}

		protected virtual void CheckGMP_PER_PersonIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.GMP_PER_PersonInfo);
		}

		protected virtual void CheckGMP_PER_Person()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateGMP_MergedPerson();
				ValidateGMP_PER_Person();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoGlbMergedPerson Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
