<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_ProfilePropsImported>True</_ProfilePropsImported>
    <_Server>au2wp-sews-401a.wisecloud.zone</_Server>
    <_EncryptConfigRequired>true</_EncryptConfigRequired>
    <_EncryptedSection>connectionStrings</_EncryptedSection>
    <UserName>s_eServicesDeploy@wisecloud.zone</UserName>
    <Password>goHoYW7XyG0w0LSV0kMlXCswubQGd2U4MEuLlED/pVcKGh/JOUCLcCvfyjxR1KD6H+hcAY4RNyBN12AcQlkgZhWoIBdnYtl4Uo6wkuiImfZSiCfpmcYg+GcHf6NoeqCDRIWOtALeJwaIKe09ISbE//L0iDv8Ao2G3pXJzIG7YOI=</Password>
  </PropertyGroup>
  <ItemGroup>
    <EncryptedPassword Include="$eHubTransactionsPassword$">
      <Value>R/jWfLfs9ooHXcMSx0qBixRdL1nI7R75pP34rlCbAITAfQPBkxMQJSqGdqP9tDJcMdR6Lf21YZetAc+QyoYJ0flO4ufQk429IB6bSP5yJLQkeHGD6tpeKvOal7plYPxsVPaJ4KVvLpTcyD4i9aWkLW+2p+q6p3XPSOEK/Q3r1oU=</Value>
    </EncryptedPassword>
  </ItemGroup>
</Project>