namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.Input
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[InputBlock("XA")]
	public partial class TIBXA : MessageBlock
	{
		public TIBXA()
			: base("XA")
		{
		}

		/// <summary>
		/// A code representing the district/port of the entry summary. Valid district/port can be queried through the Extract Reference File chapter of this publication.
		/// </summary>
		[MessageBlockString(4, 3, "M")]
		public ZString DistrictPortOfEntrySummary;

		/// <summary>
		/// A unique code assigned by the U.S. Customs and Border Protection (CBP) to all active entry document preparers. The entry filer code occupies the first three positions of a CBP entry number regardless of where the entry is filed. This code must be the same as the entry filer code in the block control header record (Record Identifier B).
		/// </summary>
		[MessageBlockString(3, 7, "M")]
		public ZString BrokerNumberOrEntryFilerCode;

		/// <summary>
		/// The number assigned to the entry. For additional information on valid entry number formats, refer to Appendix E of this publication.
		/// </summary>
		[MessageBlockString(9, 10, "M", Justification = Justification.Right)]
		public ZString EntryNumber;
	}
}
