//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from HasDeliveryStatuses.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.TransportConsignment.Module
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class HasDeliveryStatuses : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string All = "All";
			public const string HasDelivery = "DLV";
			public const string HasNoDelivery = "NDL";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString All { get { return ResString.GetMultilingualString("HasDeliveryStatuses|All", "Show all Consignments"); } }
			public static MultilingualString HasDelivery { get { return ResString.GetMultilingualString("HasDeliveryStatuses|HasDelivery", "Show only Consignments with Deliveries"); } }
			public static MultilingualString HasNoDelivery { get { return ResString.GetMultilingualString("HasDeliveryStatuses|HasNoDelivery", "Show only Consignments without Deliveries"); } }
		}

		public HasDeliveryStatuses()
		{
			AddPair(Codes.All, Descriptions.All);
			AddPair(Codes.HasDelivery, Descriptions.HasDelivery);
			AddPair(Codes.HasNoDelivery, Descriptions.HasNoDelivery);
		}
	}
}
