<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
	<xs:element name="permitItemDetails">
		<xs:annotation>
			<xs:documentation>Definiert die gültigen Werte welche vom edec Schema als permitItemDetails verwendet werden.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="permitItemDetail" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Definition einem einzelnen Wert z.b. "scientificNameCITES" (Definiert die möglichen wissenschaftlichen Bezeichnungen)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entry" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Definition eines einzelnen Eintrages für die Domäne</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="value" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Wert des Eintrages z.b. "348" für "Boa constrictor imperator"</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="meaningDe" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Beschreibt die Bedeutung des Attributes "value" in der deutschen Sprache</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="meaningFr" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Beschreibt die Bedeutung des Attributes "value" in der französchen Sprache</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="meaningIt" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Beschreibt die Bedeutung des Attributes "value" in der italienischen Sprache</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="meaningEn" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>Beschreibt die Bedeutung des Attributes "value" in der englischen Sprache</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="validFrom" type="xs:date" use="required">
										<xs:annotation>
											<xs:documentation>Definiert ab welchem Datum dieser Eintrag gültig ist.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="validTo" type="xs:date" use="required">
										<xs:annotation>
											<xs:documentation>Definiert bis zu welchem Datum dieser Eintrag gültig ist.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="validForImport" type="xs:boolean" use="required">
										<xs:annotation>
											<xs:documentation>Definiert ob dieser Eintrag für Import Relevant ist (true oder false)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="validForExport" type="xs:boolean" use="required">
										<xs:annotation>
											<xs:documentation>Definiert ob dieser Eintrag für Export Relevant ist (true oder false)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Name der permitItemDetail</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>Die Versionierung der Stammdaten-XML’s ist eine fortlaufende fünfstellig Nummer</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="created" type="xs:dateTime" use="required">
				<xs:annotation>
					<xs:documentation>Erstellungszeitpunkt der Stammdaten XML-Datei</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>