version: '3'
services:

  tracking:
    build: 
      context: ../Tracking
    image: sydco-wbln-2.wtg.zone:5000/tracking:1.0.6
    env_file: ${ENVIRONMENT}.env
    # depends_on:
    #   - nats-streaming
    ports:
      - "7001:80"

  monitoring:
    build: 
      context: ../Monitoring
    image: sydco-wbln-2.wtg.zone:5000/monitoring:1.0.6
    env_file: ${ENVIRONMENT}.env
