<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.ecb.int/vocabulary/2002-08-01/eurofxref"
  elementFormDefault="qualified">  

  <xs:element name="Cube">
    <!-- The rest of your Cube element definition -->
     <xs:complexType>
           <xs:sequence>
                 <xs:element name="Cube" maxOccurs="unbounded">
                       <xs:complexType>
                             <xs:sequence>
                                   <xs:element name="Cube" maxOccurs="unbounded">
                                         <xs:complexType>
                                               <xs:attribute name="currency" type="xs:string"></xs:attribute>
                                               <xs:attribute name="rate" type="xs:double"></xs:attribute>
                                               <xs:attribute name="name" type="xs:string"></xs:attribute>
                                         </xs:complexType>
                                   </xs:element>
                             </xs:sequence>
                             <xs:attribute name="time" type="xs:date"></xs:attribute>
                       </xs:complexType>
                 </xs:element>
           </xs:sequence>
     </xs:complexType>
  </xs:element>

</xs:schema>