<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.AuditDataServices.Notification.Testing</RootNamespace>
    <AssemblyName>Enterprise.AuditDataServices.Notification.Testing</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="CargoWise.Bi.Common.Testing" />
    <Reference Include="CargoWise.Bi.ConfigLoader" />
    <Reference Include="CargoWise.Bi.Configuration" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ChangeDataCapture.Common" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Scheduler.Business" />
    <Reference Include="Enterprise.ServiceManager.Business" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="ServiceManager.Integration.NudgingClient" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="ServiceManager.Shared.Abstractions" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ArchiveManager\ArchiveManager.csproj" />
    <ProjectReference Include="..\BorderWise\BorderWise.csproj" />
    <ProjectReference Include="..\DataScience\DataScience.csproj" />
    <ProjectReference Include="..\DevTools\DevTools.csproj" />
    <ProjectReference Include="..\EServices\EServices.csproj" />
    <ProjectReference Include="..\HVLV\HVLV.csproj" />
    <ProjectReference Include="..\Notification\Notification.csproj" />
    <ProjectReference Include="..\Subscription.Testing\Subscription.Testing.csproj" />
    <ProjectReference Include="..\Subscription\Subscription.csproj" />
    <ProjectReference Include="..\Glow\Glow.csproj" />
    <ProjectReference Include="..\XT\XT.csproj" />
    <ProjectReference Include="..\Telematics\Telematics.csproj" />
    <ProjectReference Include="..\PAVE\PAVE.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
</Project>