<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <UseCommonOutputDirectory>false</UseCommonOutputDirectory>
    <OutputPath>$(WTGBinPath)$(MSBuildProjectName)-bin\</OutputPath>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <!--- Disabling reference status check since output path is not bin\winzor -->
    <CWEnableReferenceStatusSafeGuard>false</CWEnableReferenceStatusSafeGuard>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Blazor.Common.Test\CargoWise.Blazor.Common.Test.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.SessionBroker.Test.MockAppServer\CargoWise.Blazor.SessionBroker.Test.MockAppServer.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.SessionBroker\CargoWise.Blazor.SessionBroker.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.Testing.Common.Auth\CargoWise.Blazor.Testing.Common.Auth.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.Testing.Common\CargoWise.Blazor.Testing.Common.csproj" />
    <ProjectReference Include="..\TestConsoleApp\TestConsoleApp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Blazor.Client.Integration" />
    <Reference Include="CargoWise.Blazor.Client.Integration.Server" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Providers.Common" />
    <Reference Include="CargoWise.Data.Providers.Common.Test" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection.SqlExtensions" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWiseNext.Infrastructure.Authentication" />
    <Reference Include="CargoWiseNext.Infrastructure.Authentication.Test" />
    <Reference Include="CargoWiseNext.Infrastructure.Installations" />
    <Reference Include="CargoWiseNext.Infrastructure.Installations.Test" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="WTG.Logging" />
    <Reference Include="WTG.OpenIDConnect.Login" />
    <Reference Include="WTG.OAuth2.Token.TestFramework" />
    <Reference Include="WTG.OpenIDConnect.Token" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ComponentModel" />
  </ItemGroup>
  <ItemGroup>
    <None Update="MsixPackageNameFileTest\NameAttributeNotFound.appinstaller">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MsixPackageNameFileTest\MainPackageMissing.appinstaller">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MsixPackageNameFileTest\cargowiseclientsand.appinstaller">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="MsixPackageNameFileTest\cargowiseclient.appinstaller">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>