<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.US.LVS.Module</AssemblyName>
    <RootNamespace>Enterprise.Customs.US.LVS.Module</RootNamespace>
    <UseLegacyRSA>false</UseLegacyRSA>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.US.LVS.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>