<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="RefCusCodeConditionItems">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="RefCusCodeConditionItem">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CusCode" type="xs:string" />
              <xs:element name="ConditionFormulas">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="ConditionFormula" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="IsImport" type="xs:boolean" />
              <xs:element name="StartDate" type="xs:string" />
              <xs:element name="EndDate" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
