<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!--
    Packages for .net48

    This list should be very small (an exception only) as net48 uses Paket for package
    management. Most packages should be <Reference> to the paket assembly that
    has been copied to the Bin folder.

    The only packages that should be added to this list are those that perform some build action.
    These packages typically import a .props file into the project. The way we use Paket
    in Dev means these actions would not be run.

    If you are adding a new package to this list that does not perform a build action, please
    add it using Paket instead and add a <Reference> in your .csproj file.
  -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <PackageVersion Include="CargoWiseOneWebPrintClient.Content" Version="1.0.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.57.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageVersion Include="NETCompactFramework.Installers" Version="1.0.1" />
  </ItemGroup>
  <!--
    Debug-only packages for net48
  -->
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4')) and '$(IsDebugBuild)' == 'true'">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageVersion Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.2" />
  </ItemGroup>
  <!--
    Common packages for all .net versions
  -->
  <ItemGroup>
    <PackageVersion Include="CargoWise.XmlSerializer.Generator" Version="1.0.5" />
    <PackageVersion Include="WTG.AppDomainWrappers.Core" Version="2.0.5" />
    <PackageVersion Include="WTG.AppDomainWrappers.Runner" Version="2.0.5" />
    <PackageVersion Include="WTG.BuildConfiguration.Analysis.SYSLIB" Version="8.0.0" />
  </ItemGroup>
  <!--
    Used by AppDomainWrappers, which is a separate executable in Bin\AppDW
    Common\Tools\AppDomainWrappers\AppDomainWrappers.Net6\AppDomainWrappers.Net6.csproj

    When this project is upgraded to .net8 it will eventually be brought into the folder
    and this special case will no longer be needed.
  -->
  <ItemGroup Condition="$(TargetFramework) == 'net6.0'">
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.7.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.1" />
    <PackageVersion Include="System.Memory" Version="4.5.5" />
  </ItemGroup>
  <!--
    Packages for .net core (including Winzor)
  -->
  <ItemGroup Condition="'$(IsWinzorProject)' == 'true' or '$(IsNetCoreTargetFramework)' == 'true'">
    <PackageVersion Include="AWSSDK.S3" Version="3.7.404.5" />
    <PackageVersion Include="bblanchon.PDFium.Win32" Version="105.0.5159" />
    <PackageVersion Include="Castle.Core" Version="5.1.1" />
    <PackageVersion Include="Confluent.Kafka" Version="2.3.0" />
    <PackageVersion Include="CoreWCF.Http" Version="1.5.2" />
    <PackageVersion Include="Core.System.Configuration.Install" Version="1.1.0" />
    <PackageVersion Include="Core.System.ServiceProcess" Version="2.0.1" />
    <PackageVersion Include="CoreWCF.WebHttp" Version="1.5.2" />
    <PackageVersion Include="EntityFramework" Version="6.5.1" />
    <PackageVersion Include="Grpc.Tools" Version="2.57.0" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageVersion Include="MailKit" Version="4.8.0" />
    <PackageVersion Include="MessagePack" Version="2.5.140" />
    <PackageVersion Include="MessagePackAnalyzer" Version="2.5.140" />
    <PackageVersion Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components" Version="8.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="8.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.11" />
    <PackageVersion Include="Microsoft.AspNet.SignalR.Client" Version="2.4.3" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="8.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.11" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Bcl.Memory" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Bcl.TimeProvider" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Build" Version="17.8.3" />
    <PackageVersion Include="Microsoft.Build.Locator" Version="1.7.8" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.69.1" />
    <PackageVersion Include="Microsoft.IdentityModel.Abstractions" Version="8.6.0" />
    <PackageVersion Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.6.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.6.0" />
    <PackageVersion Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageVersion Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.8.14" />
    <PackageVersion Include="Microsoft.Win32.SystemEvents" Version="8.0.0" />
    <PackageVersion Include="Mono.Cecil" Version="0.11.6" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="NLog" Version="5.3.4" />
    <PackageVersion Include="NLog.WindowsEventLog" Version="5.3.4" />
    <PackageVersion Include="NUnit.Analyzers" Version="3.10.0" />
    <PackageVersion Include="OxyPlot.Blazor" Version="2.5.7" />
    <PackageVersion Include="OxyPlot.Core" Version="2.1.2" />
    <PackageVersion Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageVersion Include="Serilog.Expressions" Version="4.0.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="7.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="7.0.0" />
    <PackageVersion Include="Serilog.Formatting.Elasticsearch" Version="9.0.3" />
    <PackageVersion Include="Serilog.Settings.Configuration" Version="7.0.1" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageVersion Include="Serilog.Sinks.Confluent.Kafka" Version="1.10.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageVersion Include="Serilog.Sinks.PeriodicBatching" Version="3.1.0" />
    <PackageVersion Include="System.CodeDom" Version="8.0.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="7.0.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="8.0.1" />
    <PackageVersion Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageVersion Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageVersion Include="System.Diagnostics.EventLog" Version="8.0.1" />
    <PackageVersion Include="System.DirectoryServices" Version="8.0.0" />
    <PackageVersion Include="System.DirectoryServices.AccountManagement" Version="8.0.0" />
    <PackageVersion Include="System.DirectoryServices.Protocols" Version="8.0.0" />
    <PackageVersion Include="System.Drawing.Common" Version="8.0.0" />
    <PackageVersion Include="System.Formats.Asn1" Version="8.0.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.6.0" />
    <PackageVersion Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageVersion Include="System.Management" Version="8.0.0" />
    <PackageVersion Include="System.Memory" Version="4.5.5" />
    <PackageVersion Include="System.Private.ServiceModel" Version="4.10.3" />
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="7.0.0" />
    <PackageVersion Include="System.Resources.Extensions" Version="8.0.0" />
    <PackageVersion Include="System.Runtime.Caching" Version="8.0.0" />
    <PackageVersion Include="System.Security.Cryptography.Pkcs" Version="8.0.1" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <PackageVersion Include="System.Security.Cryptography.Xml" Version="8.0.2" />
    <PackageVersion Include="System.Security.Permissions" Version="8.0.0" />
    <PackageVersion Include="System.ServiceModel.Http" Version="8.1.1" />
    <PackageVersion Include="System.ServiceModel.NetNamedPipe" Version="8.1.1" />
    <PackageVersion Include="System.ServiceModel.Primitives" Version="8.1.1" />
    <PackageVersion Include="System.ServiceModel.Web" Version="1.0.0" />
    <PackageVersion Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageVersion Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageVersion Include="System.Text.Json" Version="8.0.5" />
    <PackageVersion Include="System.Threading.AccessControl" Version="7.0.1" />
    <PackageVersion Include="System.Windows.Extensions" Version="8.0.0" />
    <PackageVersion Include="WTG.DevTools.CodeSigning" Version="23.11.9.19" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.0.1" />
    <PackageVersion Include="WTG.RtfConverter" Version="31.250409.3" />
    <PackageVersion Include="WTG.Z.Blazor.Diagrams" Version="4.0.28" />
    <PackageVersion Include="OpenTelemetry" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.InMemory" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.9.0-beta.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Process" Version="0.5.0-beta.6" />
    <PackageVersion Include="QuickGetLatest.SignTool" Version="24.1.11.38" />
    <PackageVersion Include="WTG.AWSCertificateIntegration" Version="24.10.21.2" />
    <PackageVersion Include="WTG.AzureApplicationIntegration" Version="24.11.21.1" />
    <PackageVersion Include="WTG.Data.SqlClient.Both" Version="0.3.0" />
    <PackageVersion Include="WTG.Data.SqlClient.System" Version="0.3.0" />
    <PackageVersion Include="WTG.ErrorReporting" Version="3.0.1" />
    <PackageVersion Include="WTG.ErrorReporting.Extensions.Logging" Version="3.0.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <!--
    Debug-only testing packages for .net core (including Winzor)

    Test projects are not built in release config.
  -->
  <ItemGroup Condition="('$(IsWinzorProject)' == 'true' or '$(IsNetCoreTargetFramework)' == 'true') and '$(IsDebugBuild)' == 'true'">
    <!--
      FluentAssertions pinned. Do not change it. v8+ has an incompatible license. FluentAssertions are being removed from the code base.
      See: WI00855980 - Create FluentAssertions project safeguard and pin version
    -->
    <PackageVersion Include="FluentAssertions" Version="[6.12.2]" />
    <PackageVersion Include="bunit" Version="1.36.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.7" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="8.0.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.49.0" />
    <PackageVersion Include="Microsoft.TestPlatform" Version="17.11.1" />
    <PackageVersion Include="Microsoft.TestPlatform.ObjectModel" Version="17.11.1" />
    <PackageVersion Include="Moq" Version="4.20.70" JanitorIgnoreUntil="10000.0.0.0" />
    <PackageVersion Include="NUnit" Version="4.1.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageVersion Include="WTG.PlaywrightTesting" Version="1.250116.2" />
    <PackageVersion Include="Lib.Harmony" Version="2.3.5" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true' and '$(IsWinzorProject)' != 'true'">
    <PackageVersion Include="System.Windows.Forms" Version="0.0.14-dev.final" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsWinzorProject)' == 'true'">
    <PackageVersion Include="Polly.Core" Version="8.4.1" />
    <PackageVersion Include="Polly.Extensions" Version="8.4.1" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>
</Project>