<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>AppDomainWrappers.Net48</RootNamespace>
    <AssemblyName>AppDomainWrappers.Net48</AssemblyName>
    <ApplicationManifest>..\..\..\..\main.manifest</ApplicationManifest>
    <OutputPath>..\..\..\..\Bin\AppDW\net48\</OutputPath>
    <NoWarn>$(NoWarn);CW1157</NoWarn>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CodeAnalysis">
      <HintPath>..\..\..\..\Bin\Microsoft.CodeAnalysis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp.Scripting">
      <HintPath>..\..\..\..\Bin\Microsoft.CodeAnalysis.CSharp.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.CodeAnalysis.Scripting">
      <HintPath>..\..\..\..\Bin\Microsoft.CodeAnalysis.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\..\..\Bin\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\..\..\Bin\System.Text.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>