<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Enterprise.Builder.GenerateDbUpgraderResources</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="BuildTools" />
    <Reference Include="BuildTools.Test" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Bi.Development.Automation" />
    <Reference Include="CargoWise.Bi.Development.Common" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Generator\Generator.csproj" />
  </ItemGroup>
</Project>