//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoCusUnderbondDecValidation : ZValidation
	{
		protected AutoCusUnderbondDecValidation(AutoCusUnderbondDec Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoCusUnderbondDecValidation); }
		}

		/// <summary>
		/// Add more validation to the CusUnderbondDec's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoCusUnderbondDecValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The CusUnderbondDec's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoCusUnderbondDecValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region BU_CL

		public void ValidateBU_CL()
		{
			ZValidationInternals.Validate(Parent.BU_CLInfo, GetBU_CLValidationInvoker());
		}

		RunValidationInvoker GetBU_CLValidationInvoker()
		{
			return delegate
			{
				CheckBU_CLIsNotEmpty();
				CheckBU_CLIsValidZGuid();
				CheckBU_CL();
			};
		}

		protected virtual void CheckBU_CLIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.BU_CLInfo);
		}

		protected virtual void CheckBU_CLIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.BU_CLInfo);
		}

		protected virtual void CheckBU_CL()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region BU_ClusterKey

		public void ValidateBU_ClusterKey()
		{
			ZValidationInternals.Validate(Parent.BU_ClusterKeyInfo, GetBU_ClusterKeyValidationInvoker());
		}

		RunValidationInvoker GetBU_ClusterKeyValidationInvoker()
		{
			return delegate
			{
				CheckBU_ClusterKey();
			};
		}

		protected virtual void CheckBU_ClusterKey()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region BU_JI

		public void ValidateBU_JI()
		{
			ZValidationInternals.Validate(Parent.BU_JIInfo, GetBU_JIValidationInvoker());
		}

		RunValidationInvoker GetBU_JIValidationInvoker()
		{
			return delegate
			{
				CheckBU_JIIsNotEmpty();
				CheckBU_JIIsValidZGuid();
				CheckBU_JI();
			};
		}

		protected virtual void CheckBU_JIIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.BU_JIInfo);
		}

		protected virtual void CheckBU_JIIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.BU_JIInfo);
		}

		protected virtual void CheckBU_JI()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region BU_SequenceNumber

		public void ValidateBU_SequenceNumber()
		{
			ZValidationInternals.Validate(Parent.BU_SequenceNumberInfo, GetBU_SequenceNumberValidationInvoker());
		}

		RunValidationInvoker GetBU_SequenceNumberValidationInvoker()
		{
			return delegate
			{
				CheckBU_SequenceNumber();
			};
		}

		protected virtual void CheckBU_SequenceNumber()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region BU_Status

		public void ValidateBU_Status()
		{
			ZValidationInternals.Validate(Parent.BU_StatusInfo, GetBU_StatusValidationInvoker());
		}

		RunValidationInvoker GetBU_StatusValidationInvoker()
		{
			return delegate
			{
				CheckBU_StatusIsWesternEuropean();
				CheckBU_Status();
			};
		}

		protected virtual void CheckBU_StatusIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.BU_StatusInfo);
		}

		protected virtual void CheckBU_Status()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateBU_CL();
				ValidateBU_ClusterKey();
				ValidateBU_JI();
				ValidateBU_SequenceNumber();
				ValidateBU_Status();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoCusUnderbondDec Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
