namespace Enterprise.Customs.ASYCUDA.Module
{
	partial class ASYCUDAManifestBillFilterStripControl
	{
		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo13 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo18 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo19 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo20 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo21 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo22 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo23 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo24 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo25 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo26 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo27 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo28 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo29 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo30 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo31 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo32 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo33 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo34 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo35 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo36 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo37 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo38 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo39 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo40 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo41 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo42 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo43 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo44 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo45 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo46 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo47 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo48 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo49 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo50 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo51 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo52 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo53 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo54 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo55 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo56 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo57 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo58 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo59 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo60 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo61 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo62 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo63 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo64 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo65 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo66 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo67 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo68 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo69 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo70 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo71 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo72 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo73 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo74 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo75 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo76 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo77 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo78 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo79 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo80 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo81 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo82 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo83 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo84 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo85 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo86 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo87 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo88 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo89 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo90 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			this.grid.SuspendLayout();
			this.AddStripButton.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.SuspendLayout();
			// 
			// grid
			// 
			this.BindingSource.SetBindingMember(this.grid, ".");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)))));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_JobReference)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_MasterBill)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_BillNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_MessageStatus)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_BillStatus)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_TransportMode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_RL_NKPortOfDischarge)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_E_ARV)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_RN_NKConveyanceNationality)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_VesselName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_Voyage)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).CountryCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_MessageStatus)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.RegistrationStatus)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_E_DEP)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_RL_NKPortOfLoading)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_SystemCreateUser)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_SystemCreateTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_SystemLastEditUser)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_SystemLastEditTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_AgentType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_CustomsValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_ContainerMode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_Voyage)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_VehicleRegistration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDate)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_MasterBillIssueDate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_ManifestType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_Nature)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_CustomsOffice)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_RL_NKPortOfFirstArrival)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.ShippingAgentName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.ShippingAgentAddress)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.AMA_CarrierCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.RegistrationNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Header.RegistrationDate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RL_NKOrigin)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RL_NKFinalDestination)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZInt)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ManifestQty)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ManifestUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_GrossWeight)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_GrossWeightUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_Volume)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_VolumeUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_GoodsDescription)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Shipper.Header.OH_FullName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).Consignee.Header.OH_FullName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).NotifyParty.Header.OH_FullName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_Remarks)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_PrepaidCollect)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_FreightValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RX_NKFreightValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_TransportValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RX_NKTransportValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_InsuranceValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RX_NKInsuranceValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_CustomsValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RX_NKCustomsValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).DiscountValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).DiscountValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDecimal)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).OtherChargesValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).OtherChargesValueCurrency)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_CarrierReference)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_UCRNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).RegistrationNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).RegistrationDate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).CustomsJobNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_BillIssuer)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_BolType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipmentType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_CargoStatus)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneeName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneeStreet1)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneeStreet2)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneeCity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneeState)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RN_NKConsigneeCountry)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ConsigneePostcode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperStreet1)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperStreet2)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperCity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperState)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RN_NKShipperCountry)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_ShipperPostcode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyStreet1)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyStreet2)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyCity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyState)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_RN_NKNotifyPartyCountry)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_NotifyPartyPostcode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_GoodsLocation)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_LocationInformation)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).CustomsEntryNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).CustomsEntryNumberType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.ASYCUDA.Business.AsycudaBill)(null)).ABL_SpecialCargoCode)));
			zTextBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("CAA2BCCF-E282-4B8F-9255-BA70F816F646", "Job Reference");
			zTextBoxColumnStyleInfo1.ColumnName = "Header+AMA_JobReference";
			zTextBoxColumnStyleInfo1.IsCustomColumn = false;
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("C0343041-8C2A-4BB7-9DEC-BCC2D1FF94DA", "MBL", "Master Bill", "Master Bill No.", "Master Bill Number");
			zTextBoxColumnStyleInfo2.ColumnName = "Header+AMA_MasterBill";
			zTextBoxColumnStyleInfo2.IsCustomColumn = false;
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("8F1D41F2-9DF8-4809-8CD9-F97330C769BE", "HBL", "House Bill", "House Bill No.", "House Bill Number");
			zTextBoxColumnStyleInfo3.ColumnName = "ABL_BillNumber";
			zTextBoxColumnStyleInfo3.IsCustomColumn = false;
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("01e5afa8-5b3d-4c85-9784-48948f81c878", "Bill Msg. Status", "Bill Message Status", "");
			zTextBoxColumnStyleInfo4.ColumnName = "ABL_MessageStatus";
			zTextBoxColumnStyleInfo4.IsCustomColumn = false;
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("83FD0D5B-1421-46E6-8A0B-FA4B903F344F", "Bill Customs Status");
			zTextBoxColumnStyleInfo5.ColumnName = "ABL_BillStatus";
			zTextBoxColumnStyleInfo5.IsCustomColumn = false;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo6.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("CAA26898-72DF-4ABE-9A75-5C888F7698FE", "Transport Mode");
			zTextBoxColumnStyleInfo6.ColumnName = "Header+AMA_TransportMode";
			zTextBoxColumnStyleInfo6.IsCustomColumn = false;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("FE8BF721-771F-458C-B1D4-07BC43C49E0A", "Port of Discharge");
			zTextBoxColumnStyleInfo7.ColumnName = "Header+AMA_RL_NKPortOfDischarge";
			zTextBoxColumnStyleInfo7.IsCustomColumn = false;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDateEditColumnStyleInfo1.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("9F57A538-5D33-4324-8823-21B2FA78DB68", "ETA");
			zDateEditColumnStyleInfo1.ColumnName = "Header+AMA_E_ARV";
			zDateEditColumnStyleInfo1.IsCustomColumn = false;
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo8.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("D3197269-4850-4E2D-A631-A5C8A7CFB376", "Conveyance Ctry/Rgn.");
			zTextBoxColumnStyleInfo8.ColumnName = "Header+AMA_RN_NKConveyanceNationality";
			zTextBoxColumnStyleInfo8.IsCustomColumn = false;
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo9.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("3BCCAAAA-4119-44AD-941C-3A6F33F2E0E7", "Vessel");
			zTextBoxColumnStyleInfo9.ColumnName = "Header+AMA_VesselName";
			zTextBoxColumnStyleInfo9.IsCustomColumn = false;
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo10.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("9691B5F7-E3FF-45F3-90B1-EB3756DE9A98", "Voyage");
			zTextBoxColumnStyleInfo10.ColumnName = "Header+AMA_Voyage";
			zTextBoxColumnStyleInfo10.IsCustomColumn = false;
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(68);
			zTextBoxColumnStyleInfo11.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("7A1A0715-0337-4780-954F-915F84C849AC", "Country/Region");
			zTextBoxColumnStyleInfo11.ColumnName = "CountryCode";
			zTextBoxColumnStyleInfo11.IsCustomColumn = false;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo12.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("099B3EFD-5BEC-432D-9016-D48BA037ED3F", "Manifest Msg.Status");
			zTextBoxColumnStyleInfo12.ColumnName = "Header+AMA_MessageStatus";
			zTextBoxColumnStyleInfo12.IsCustomColumn = false;
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo13.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5CB0B9D3-79B0-4A6E-86E9-5E16BC0ADE47", "Manifest Customs Status");
			zTextBoxColumnStyleInfo13.ColumnName = "Header+RegistrationStatus";
			zTextBoxColumnStyleInfo13.IsCustomColumn = false;
			zTextBoxColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zDateEditColumnStyleInfo2.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4EA7E904-C275-4B18-A684-916C6EB3F250", "Est. Departure");
			zDateEditColumnStyleInfo2.ColumnName = "Header+AMA_E_DEP";
			zDateEditColumnStyleInfo2.IsCustomColumn = false;
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo14.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("CB90A08B-2DA7-4336-A79C-50B87A10CFE9", "Port of Loading");
			zTextBoxColumnStyleInfo14.ColumnName = "Header+AMA_RL_NKPortOfLoading";
			zTextBoxColumnStyleInfo14.IsCustomColumn = false;
			zTextBoxColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo15.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("48F3D7C9-866F-44F6-B1EC-B9D926CCC228", "Created By");
			zTextBoxColumnStyleInfo15.ColumnName = "ABL_SystemCreateUser";
			zTextBoxColumnStyleInfo15.IsCustomColumn = false;
			zTextBoxColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo3.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ECC1E052-A65E-46E0-9873-869B8084DA7B", "Created Time");
			zDateEditColumnStyleInfo3.ColumnName = "ABL_SystemCreateTimeUtc";
			zDateEditColumnStyleInfo3.IsCustomColumn = false;
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo16.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1187C1D3-3D3E-42CA-9C4C-537887ACAFE5", "Last Edit");
			zTextBoxColumnStyleInfo16.ColumnName = "ABL_SystemLastEditUser";
			zTextBoxColumnStyleInfo16.IsCustomColumn = false;
			zTextBoxColumnStyleInfo16.IsVisible = false;
			zTextBoxColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo4.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("56AEBE48-ADD9-415C-BD41-2D132EBD4DEE", "Last Edited Time");
			zDateEditColumnStyleInfo4.ColumnName = "ABL_SystemLastEditTimeUtc";
			zDateEditColumnStyleInfo4.IsCustomColumn = false;
			zDateEditColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo17.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("833bd3a7-969c-496a-bb96-2a4364b512e5", "Agent Type");
			zTextBoxColumnStyleInfo17.ColumnName = "Header+AMA_AgentType";
			zTextBoxColumnStyleInfo17.IsCustomColumn = false;
			zTextBoxColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo18.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("155fd070-5c70-48ad-86b7-dd21c3a1170d", "Customs Value");
			zTextBoxColumnStyleInfo18.ColumnName = "ABL_CustomsValue";
			zTextBoxColumnStyleInfo18.IsCustomColumn = false;
			zTextBoxColumnStyleInfo18.IsVisible = false;
			zTextBoxColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(85);
			zTextBoxColumnStyleInfo19.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("f7b1e0cc-9192-4c30-9f15-986e33855ec6", "Container Mode");
			zTextBoxColumnStyleInfo19.ColumnName = "Header+AMA_ContainerMode";
			zTextBoxColumnStyleInfo19.IsCustomColumn = false;
			zTextBoxColumnStyleInfo19.IsVisible = false;
			zTextBoxColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(101);
			zTextBoxColumnStyleInfo20.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6e73bca0-0d17-4836-96b5-4077fa42ca3b", "Flight Number");
			zTextBoxColumnStyleInfo20.ColumnName = "Header+AMA_Voyage";
			zTextBoxColumnStyleInfo20.IsCustomColumn = false;
			zTextBoxColumnStyleInfo20.IsVisible = false;
			zTextBoxColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(68);
			zTextBoxColumnStyleInfo21.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("217213e1-a47f-4842-96c5-e24d8003e009", "", "Vehicle Reg", "Vehicle Registration", "");
			zTextBoxColumnStyleInfo21.ColumnName = "Header+AMA_VehicleRegistration";
			zTextBoxColumnStyleInfo21.IsCustomColumn = false;
			zTextBoxColumnStyleInfo21.IsVisible = false;
			zTextBoxColumnStyleInfo21.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(104);
			zTextBoxColumnStyleInfo22.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5ce7619b-b8d4-4dea-b0c4-cb359354f7d8", "Issue Date");
			zTextBoxColumnStyleInfo22.ColumnName = "Header+AMA_MasterBillIssueDate";
			zTextBoxColumnStyleInfo22.IsCustomColumn = false;
			zTextBoxColumnStyleInfo22.IsVisible = false;
			zTextBoxColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo23.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("f85d25ee-a268-4e7c-88db-22b32fc32bf1", "Manifest Type");
			zTextBoxColumnStyleInfo23.ColumnName = "Header+AMA_ManifestType";
			zTextBoxColumnStyleInfo23.IsCustomColumn = false;
			zTextBoxColumnStyleInfo23.IsVisible = false;
			zTextBoxColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			zTextBoxColumnStyleInfo24.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d6753f95-8cbc-462b-afef-6b395d95510f", "Nature");
			zTextBoxColumnStyleInfo24.ColumnName = "Header+AMA_Nature";
			zTextBoxColumnStyleInfo24.IsCustomColumn = false;
			zTextBoxColumnStyleInfo24.IsVisible = false;
			zTextBoxColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo25.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("7d50de05-5991-43be-af0e-645c68e2ff3a", "Customs Office");
			zTextBoxColumnStyleInfo25.ColumnName = "Header+AMA_CustomsOffice";
			zTextBoxColumnStyleInfo25.IsCustomColumn = false;
			zTextBoxColumnStyleInfo25.IsVisible = false;
			zTextBoxColumnStyleInfo25.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(98);
			zTextBoxColumnStyleInfo26.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("91e81263-ebd6-4c09-9a6f-60c21dd24cd0", "", "First Arrival", "First Arrival Port", "");
			zTextBoxColumnStyleInfo26.ColumnName = "Header+AMA_RL_NKPortOfFirstArrival";
			zTextBoxColumnStyleInfo26.IsCustomColumn = false;
			zTextBoxColumnStyleInfo26.IsVisible = false;
			zTextBoxColumnStyleInfo26.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			zTextBoxColumnStyleInfo27.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("687a36b5-4f5a-48c9-bf38-92706d174d68", "", "Shipping Agent", "Shipping Agent Name", "");
			zTextBoxColumnStyleInfo27.ColumnName = "Header+ShippingAgentName";
			zTextBoxColumnStyleInfo27.IsCustomColumn = false;
			zTextBoxColumnStyleInfo27.IsVisible = false;
			zTextBoxColumnStyleInfo27.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(152);
			zTextBoxColumnStyleInfo28.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4c35baf1-1711-4c2e-84d2-bfefd840bda6", "", "Shipping Address", "Shipping Agent Address", "");
			zTextBoxColumnStyleInfo28.ColumnName = "Header+ShippingAgentAddress";
			zTextBoxColumnStyleInfo28.IsCustomColumn = false;
			zTextBoxColumnStyleInfo28.IsVisible = false;
			zTextBoxColumnStyleInfo28.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(275);
			zTextBoxColumnStyleInfo29.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("e7db12dd-3074-4a6f-bf72-2a411ef64c67", "Carrier Code");
			zTextBoxColumnStyleInfo29.ColumnName = "Header+AMA_CarrierCode";
			zTextBoxColumnStyleInfo29.IsCustomColumn = false;
			zTextBoxColumnStyleInfo29.IsVisible = false;
			zTextBoxColumnStyleInfo29.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo30.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("001b8616-545b-4586-aaf6-d4849d314487", "Origin");
			zTextBoxColumnStyleInfo30.ColumnName = "ABL_RL_NKOrigin";
			zTextBoxColumnStyleInfo30.IsCustomColumn = false;
			zTextBoxColumnStyleInfo30.IsVisible = false;
			zTextBoxColumnStyleInfo30.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo31.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ec266428-87da-4995-abe8-ba47ab615c5a", "Final Destination");
			zTextBoxColumnStyleInfo31.ColumnName = "ABL_RL_NKFinalDestination";
			zTextBoxColumnStyleInfo31.IsCustomColumn = false;
			zTextBoxColumnStyleInfo31.IsVisible = false;
			zTextBoxColumnStyleInfo31.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(106);
			zTextBoxColumnStyleInfo32.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ab838c8b-3160-4715-a583-50bd10bab06f", "Total Qty");
			zTextBoxColumnStyleInfo32.ColumnName = "ABL_ManifestQty";
			zTextBoxColumnStyleInfo32.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("3f02cd0a-44ae-4914-bddf-4815a1189039", "Manifest Qty");
			zTextBoxColumnStyleInfo32.IsCustomColumn = false;
			zTextBoxColumnStyleInfo32.IsVisible = false;
			zTextBoxColumnStyleInfo32.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo33.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("12a9c3d1-a08c-4b10-a024-ef34713f25c1", "Total Qty Unit");
			zTextBoxColumnStyleInfo33.ColumnName = "ABL_ManifestUQ";
			zTextBoxColumnStyleInfo33.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("3f02cd0a-44ae-4914-bddf-4815a1189039", "Manifest Qty");
			zTextBoxColumnStyleInfo33.IsCustomColumn = false;
			zTextBoxColumnStyleInfo33.IsVisible = false;
			zTextBoxColumnStyleInfo33.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo34.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("3f6e6108-52c7-4408-aa8b-c6d3e976280e", "Total Gross Weight");
			zTextBoxColumnStyleInfo34.ColumnName = "ABL_GrossWeight";
			zTextBoxColumnStyleInfo34.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("36084d46-35ca-4ba8-a9b8-1d89e1c62b2b", "Gross Weight");
			zTextBoxColumnStyleInfo34.IsCustomColumn = false;
			zTextBoxColumnStyleInfo34.IsVisible = false;
			zTextBoxColumnStyleInfo34.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(118);
			zTextBoxColumnStyleInfo35.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("e428fdb5-3061-4977-a965-943d561410fb", "Total Gross Weight Qty");
			zTextBoxColumnStyleInfo35.ColumnName = "ABL_GrossWeightUQ";
			zTextBoxColumnStyleInfo35.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("36084d46-35ca-4ba8-a9b8-1d89e1c62b2b", "Gross Weight");
			zTextBoxColumnStyleInfo35.IsCustomColumn = false;
			zTextBoxColumnStyleInfo35.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(138);
			zTextBoxColumnStyleInfo36.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("a4feb216-ae4c-433e-8020-14c3cc78cbb0", "Total Volume");
			zTextBoxColumnStyleInfo36.ColumnName = "ABL_Volume";
			zTextBoxColumnStyleInfo36.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("968e7d1f-52a8-47ff-b0d0-017168d46b34", "Volume");
			zTextBoxColumnStyleInfo36.IsCustomColumn = false;
			zTextBoxColumnStyleInfo36.IsVisible = false;
			zTextBoxColumnStyleInfo36.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(88);
			zTextBoxColumnStyleInfo37.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d90189c-5311-4313-a617-5b905a64eb9d", "Total Volume Unit");
			zTextBoxColumnStyleInfo37.ColumnName = "ABL_VolumeUQ";
			zTextBoxColumnStyleInfo37.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("968e7d1f-52a8-47ff-b0d0-017168d46b34", "Volume");
			zTextBoxColumnStyleInfo37.IsCustomColumn = false;
			zTextBoxColumnStyleInfo37.IsVisible = false;
			zTextBoxColumnStyleInfo37.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(112);
			zTextBoxColumnStyleInfo38.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ae672f19-3437-4643-99b9-1655ad46560f", "Goods Description");
			zTextBoxColumnStyleInfo38.ColumnName = "ABL_GoodsDescription";
			zTextBoxColumnStyleInfo38.IsCustomColumn = false;
			zTextBoxColumnStyleInfo38.IsVisible = false;
			zTextBoxColumnStyleInfo38.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(113);
			zTextBoxColumnStyleInfo39.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d2b7cce8-61ef-40c9-91e8-c7fa79324e9e", "Shipper");
			zTextBoxColumnStyleInfo39.ColumnName = "Shipper+Header+OH_FullName";
			zTextBoxColumnStyleInfo39.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo39.IsCustomColumn = false;
			zTextBoxColumnStyleInfo39.IsVisible = false;
			zTextBoxColumnStyleInfo39.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(201);
			zTextBoxColumnStyleInfo40.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d128ae67-9a96-4cf1-990e-2908c9e4e661", "Consignee");
			zTextBoxColumnStyleInfo40.ColumnName = "Consignee+Header+OH_FullName";
			zTextBoxColumnStyleInfo40.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo40.IsCustomColumn = false;
			zTextBoxColumnStyleInfo40.IsVisible = false;
			zTextBoxColumnStyleInfo40.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(201);
			zTextBoxColumnStyleInfo41.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("80e27866-05bd-47c1-ab4d-ce6015d566f7", "Notify Party");
			zTextBoxColumnStyleInfo41.ColumnName = "NotifyParty+Header+OH_FullName";
			zTextBoxColumnStyleInfo41.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo41.IsCustomColumn = false;
			zTextBoxColumnStyleInfo41.IsVisible = false;
			zTextBoxColumnStyleInfo41.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(201);
			zTextBoxColumnStyleInfo42.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("64b6ca7e-2c93-4640-ab60-7f18ea386679", "Remarks");
			zTextBoxColumnStyleInfo42.ColumnName = "ABL_Remarks";
			zTextBoxColumnStyleInfo42.IsCustomColumn = false;
			zTextBoxColumnStyleInfo42.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo43.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6ed67d0a-5117-4c1e-8190-0a6524915074", "Prepaid/Collect");
			zTextBoxColumnStyleInfo43.ColumnName = "ABL_PrepaidCollect";
			zTextBoxColumnStyleInfo43.IsCustomColumn = false;
			zTextBoxColumnStyleInfo43.IsVisible = false;
			zTextBoxColumnStyleInfo43.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo44.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("605da70b-f327-4fdc-828e-3c585ecca041", "Total Goods Value");
			zTextBoxColumnStyleInfo44.ColumnName = "ABL_FreightValue";
			zTextBoxColumnStyleInfo44.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("76eebb6a-5247-4198-b96f-b6d94cecc6e6", "Goods Value");
			zTextBoxColumnStyleInfo44.IsCustomColumn = false;
			zTextBoxColumnStyleInfo44.IsVisible = false;
			zTextBoxColumnStyleInfo44.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(114);
			zTextBoxColumnStyleInfo45.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("7256b932-6044-404e-a063-c1e2616c96bb", "Total Goods Value Currency");
			zTextBoxColumnStyleInfo45.ColumnName = "ABL_RX_NKFreightValueCurrency";
			zTextBoxColumnStyleInfo45.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("76eebb6a-5247-4198-b96f-b6d94cecc6e6", "Goods Value");
			zTextBoxColumnStyleInfo45.IsCustomColumn = false;
			zTextBoxColumnStyleInfo45.IsVisible = false;
			zTextBoxColumnStyleInfo45.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(165);
			zTextBoxColumnStyleInfo46.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("722de57c-ce5e-4eab-adcb-25a0a12548ca", "Total Freight Value");
			zTextBoxColumnStyleInfo46.ColumnName = "ABL_TransportValue";
			zTextBoxColumnStyleInfo46.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("05105632-f350-46cb-8937-71422fe6d894", "Transport Value");
			zTextBoxColumnStyleInfo46.IsCustomColumn = false;
			zTextBoxColumnStyleInfo46.IsVisible = false;
			zTextBoxColumnStyleInfo46.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo47.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("3f25224e-3dcc-4b82-99d1-cc2ef8bf84be", "Total Freight Value Currency");
			zTextBoxColumnStyleInfo47.ColumnName = "ABL_RX_NKTransportValueCurrency";
			zTextBoxColumnStyleInfo47.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("05105632-f350-46cb-8937-71422fe6d894", "Transport Value");
			zTextBoxColumnStyleInfo47.IsCustomColumn = false;
			zTextBoxColumnStyleInfo47.IsVisible = false;
			zTextBoxColumnStyleInfo47.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(165);
			zTextBoxColumnStyleInfo48.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("0f03fabb-2215-40e7-afb0-67cd269e549c", "Total Insurance Value");
			zTextBoxColumnStyleInfo48.ColumnName = "ABL_InsuranceValue";
			zTextBoxColumnStyleInfo48.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("50f6c727-08e1-4226-902c-e7bbb436deac", "Insurance Value");
			zTextBoxColumnStyleInfo48.IsCustomColumn = false;
			zTextBoxColumnStyleInfo48.IsVisible = false;
			zTextBoxColumnStyleInfo48.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(132);
			zTextBoxColumnStyleInfo49.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6621d4f0-53c2-42e3-86ab-29826fcc8e40", "Total Insurance Value Currency");
			zTextBoxColumnStyleInfo49.ColumnName = "ABL_RX_NKInsuranceValueCurrency";
			zTextBoxColumnStyleInfo49.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("50f6c727-08e1-4226-902c-e7bbb436deac", "Insurance Value");
			zTextBoxColumnStyleInfo49.IsCustomColumn = false;
			zTextBoxColumnStyleInfo49.IsVisible = false;
			zTextBoxColumnStyleInfo49.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			zTextBoxColumnStyleInfo50.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("db8dde5e-dcda-4010-9f62-8e5e796f3b95", "Total Customs Value");
			zTextBoxColumnStyleInfo50.ColumnName = "ABL_CustomsValue";
			zTextBoxColumnStyleInfo50.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4a19b498-e0e3-4ee4-ab6c-d525b5e67df7", "Customs Value");
			zTextBoxColumnStyleInfo50.IsCustomColumn = false;
			zTextBoxColumnStyleInfo50.IsVisible = false;
			zTextBoxColumnStyleInfo50.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(96);
			zTextBoxColumnStyleInfo51.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("77cb9c7e-8e0d-4965-80b3-57c7347d2579", "Total Customs Value Currency");
			zTextBoxColumnStyleInfo51.ColumnName = "ABL_RX_NKCustomsValueCurrency";
			zTextBoxColumnStyleInfo51.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4a19b498-e0e3-4ee4-ab6c-d525b5e67df7", "Customs Value");
			zTextBoxColumnStyleInfo51.IsCustomColumn = false;
			zTextBoxColumnStyleInfo51.IsVisible = false;
			zTextBoxColumnStyleInfo51.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(176);
			zTextBoxColumnStyleInfo52.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ffad9477-896e-4a72-b880-4961c95ef69d", "Discount Value");
			zTextBoxColumnStyleInfo52.ColumnName = "DiscountValue";
			zTextBoxColumnStyleInfo52.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d05e12b8-1d19-47b9-af34-a572b62d6658", "Discount Value");
			zTextBoxColumnStyleInfo52.IsCustomColumn = false;
			zTextBoxColumnStyleInfo52.IsVisible = false;
			zTextBoxColumnStyleInfo52.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(97);
			zTextBoxColumnStyleInfo53.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("f8e72b20-f3ca-418e-9ac5-c6e6cf1de49c", "Discount Value Currency");
			zTextBoxColumnStyleInfo53.ColumnName = "DiscountValueCurrency";
			zTextBoxColumnStyleInfo53.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d05e12b8-1d19-47b9-af34-a572b62d6658", "Discount Value");
			zTextBoxColumnStyleInfo53.IsCustomColumn = false;
			zTextBoxColumnStyleInfo53.IsVisible = false;
			zTextBoxColumnStyleInfo53.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(145);
			zTextBoxColumnStyleInfo54.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6a67a41a-cda6-4f26-b2d4-cf3fd73a8e2d", "Other Charges Value");
			zTextBoxColumnStyleInfo54.ColumnName = "OtherChargesValue";
			zTextBoxColumnStyleInfo54.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("96fb595b-058e-4b65-bc9f-789fd66a92be", "Other Charges Value");
			zTextBoxColumnStyleInfo54.IsCustomColumn = false;
			zTextBoxColumnStyleInfo54.IsVisible = false;
			zTextBoxColumnStyleInfo54.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(126);
			zTextBoxColumnStyleInfo55.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("0a523edd-8674-48eb-9310-2ece10c410f1", "Other Charges Value Currency");
			zTextBoxColumnStyleInfo55.ColumnName = "OtherChargesValueCurrency";
			zTextBoxColumnStyleInfo55.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("96fb595b-058e-4b65-bc9f-789fd66a92be", "Other Charges Value");
			zTextBoxColumnStyleInfo55.IsCustomColumn = false;
			zTextBoxColumnStyleInfo55.IsVisible = false;
			zTextBoxColumnStyleInfo55.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(174);
			zTextBoxColumnStyleInfo56.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("60b567df-392b-402c-9e28-1b950814c4f8", "Carrier Reference");
			zTextBoxColumnStyleInfo56.ColumnName = "ABL_CarrierReference";
			zTextBoxColumnStyleInfo56.IsCustomColumn = false;
			zTextBoxColumnStyleInfo56.IsVisible = false;
			zTextBoxColumnStyleInfo56.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo57.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6458dff9-3c09-4024-a70e-6c7e167de723", "UCR Number");
			zTextBoxColumnStyleInfo57.ColumnName = "ABL_UCRNumber";
			zTextBoxColumnStyleInfo57.IsCustomColumn = false;
			zTextBoxColumnStyleInfo57.IsVisible = false;
			zTextBoxColumnStyleInfo57.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo58.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("c6738c26-1c8d-461d-8c45-ba4bef1cfb32", "Bill Registration Number");
			zTextBoxColumnStyleInfo58.ColumnName = "RegistrationNumber";
			zTextBoxColumnStyleInfo58.IsCustomColumn = false;
			zTextBoxColumnStyleInfo58.IsVisible = false;
			zTextBoxColumnStyleInfo58.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDateEditColumnStyleInfo5.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("d10bdc9f-cb41-4006-8379-c6bf2d56cc0e", "", "Bill Reg Date", "Bill Registration Date", "");
			zDateEditColumnStyleInfo5.ColumnName = "RegistrationDate";
			zDateEditColumnStyleInfo5.IsCustomColumn = false;
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(125);
			zTextBoxColumnStyleInfo59.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("6273ae7a-0ea0-4fba-839a-6fce1a42c3c3", "Customs Job Number");
			zTextBoxColumnStyleInfo59.ColumnName = "CustomsJobNumber";
			zTextBoxColumnStyleInfo59.IsCustomColumn = false;
			zTextBoxColumnStyleInfo59.IsVisible = false;
			zTextBoxColumnStyleInfo59.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(129);
			zTextBoxColumnStyleInfo60.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("be70b0c5-c1bf-45a0-96fb-397cc9b6ea27", "Bill Issuer");
			zTextBoxColumnStyleInfo60.ColumnName = "ABL_BillIssuer";
			zTextBoxColumnStyleInfo60.IsCustomColumn = false;
			zTextBoxColumnStyleInfo60.IsVisible = false;
			zTextBoxColumnStyleInfo60.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo61.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("9ea43720-69db-4bc2-88c5-ba4df2784b15", "Bill Type");
			zTextBoxColumnStyleInfo61.ColumnName = "ABL_BolType";
			zTextBoxColumnStyleInfo61.IsCustomColumn = false;
			zTextBoxColumnStyleInfo61.IsVisible = false;
			zTextBoxColumnStyleInfo61.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo62.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("b7bdd822-872a-4c54-b94a-ad5564a6d416", "Shipment Type");
			zTextBoxColumnStyleInfo62.ColumnName = "ABL_ShipmentType";
			zTextBoxColumnStyleInfo62.IsCustomColumn = false;
			zTextBoxColumnStyleInfo62.IsVisible = false;
			zTextBoxColumnStyleInfo62.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo63.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("af5b801d-4623-4325-ae08-116ed984853c", "Bill Cargo Status");
			zTextBoxColumnStyleInfo63.ColumnName = "ABL_CargoStatus";
			zTextBoxColumnStyleInfo63.IsCustomColumn = false;
			zTextBoxColumnStyleInfo63.IsVisible = false;
			zTextBoxColumnStyleInfo63.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo64.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("0d1b208d-9e87-4593-953c-59a64536842c", "Consignee Name");
			zTextBoxColumnStyleInfo64.ColumnName = "ABL_ConsigneeName";
			zTextBoxColumnStyleInfo64.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo64.IsCustomColumn = false;
			zTextBoxColumnStyleInfo64.IsVisible = false;
			zTextBoxColumnStyleInfo64.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(146);
			zTextBoxColumnStyleInfo65.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("bdb9b10d-4aa3-469f-b9c5-a2c2761e84c6", "Consignee Street 1");
			zTextBoxColumnStyleInfo65.ColumnName = "ABL_ConsigneeStreet1";
			zTextBoxColumnStyleInfo65.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo65.IsCustomColumn = false;
			zTextBoxColumnStyleInfo65.IsVisible = false;
			zTextBoxColumnStyleInfo65.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo66.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("349836dd-a327-4313-bb17-5b6fec58ff9a", "Consignee Street 2");
			zTextBoxColumnStyleInfo66.ColumnName = "ABL_ConsigneeStreet2";
			zTextBoxColumnStyleInfo66.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo66.IsCustomColumn = false;
			zTextBoxColumnStyleInfo66.IsVisible = false;
			zTextBoxColumnStyleInfo66.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo67.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("f10d0774-2244-48fd-88ee-8c0fd20d057f", "Consignee City");
			zTextBoxColumnStyleInfo67.ColumnName = "ABL_ConsigneeCity";
			zTextBoxColumnStyleInfo67.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo67.IsCustomColumn = false;
			zTextBoxColumnStyleInfo67.IsVisible = false;
			zTextBoxColumnStyleInfo67.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo68.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("609575ff-30dd-46f8-b58d-b9d6664d59f1", "Consignee State");
			zTextBoxColumnStyleInfo68.ColumnName = "ABL_ConsigneeState";
			zTextBoxColumnStyleInfo68.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo68.IsCustomColumn = false;
			zTextBoxColumnStyleInfo68.IsVisible = false;
			zTextBoxColumnStyleInfo68.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(103);
			zTextBoxColumnStyleInfo69.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("7af82636-36d5-47cc-92ec-2633b5bd266d", "Consignee Country");
			zTextBoxColumnStyleInfo69.ColumnName = "ABL_RN_NKConsigneeCountry";
			zTextBoxColumnStyleInfo69.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo69.IsCustomColumn = false;
			zTextBoxColumnStyleInfo69.IsVisible = false;
			zTextBoxColumnStyleInfo69.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo70.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("37e023e5-8a4c-454d-b673-6162e34f061f", "Consignee Postcode");
			zTextBoxColumnStyleInfo70.ColumnName = "ABL_ConsigneePostcode";
			zTextBoxColumnStyleInfo70.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("4728afe1-aad5-4c1b-80c1-1c88029546c2", "Consignee");
			zTextBoxColumnStyleInfo70.IsCustomColumn = false;
			zTextBoxColumnStyleInfo70.IsVisible = false;
			zTextBoxColumnStyleInfo70.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(122);
			zTextBoxColumnStyleInfo71.ColumnName = "ABL_ShipperName";
			zTextBoxColumnStyleInfo71.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo71.IsCustomColumn = false;
			zTextBoxColumnStyleInfo71.IsVisible = false;
			zTextBoxColumnStyleInfo71.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(146);
			zTextBoxColumnStyleInfo72.ColumnName = "ABL_ShipperStreet1";
			zTextBoxColumnStyleInfo72.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo72.IsCustomColumn = false;
			zTextBoxColumnStyleInfo72.IsVisible = false;
			zTextBoxColumnStyleInfo72.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo73.ColumnName = "ABL_ShipperStreet2";
			zTextBoxColumnStyleInfo73.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo73.IsCustomColumn = false;
			zTextBoxColumnStyleInfo73.IsVisible = false;
			zTextBoxColumnStyleInfo73.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo74.ColumnName = "ABL_ShipperCity";
			zTextBoxColumnStyleInfo74.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo74.IsCustomColumn = false;
			zTextBoxColumnStyleInfo74.IsVisible = false;
			zTextBoxColumnStyleInfo74.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo75.ColumnName = "ABL_ShipperState";
			zTextBoxColumnStyleInfo75.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo75.IsCustomColumn = false;
			zTextBoxColumnStyleInfo75.IsVisible = false;
			zTextBoxColumnStyleInfo75.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(103);
			zTextBoxColumnStyleInfo76.ColumnName = "ABL_RN_NKShipperCountry";
			zTextBoxColumnStyleInfo76.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo76.IsCustomColumn = false;
			zTextBoxColumnStyleInfo76.IsVisible = false;
			zTextBoxColumnStyleInfo76.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(117);
			zTextBoxColumnStyleInfo77.ColumnName = "ABL_ShipperPostcode";
			zTextBoxColumnStyleInfo77.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("1e868c09-c9e3-46f7-8b16-16212817fed1", "Shipper");
			zTextBoxColumnStyleInfo77.IsCustomColumn = false;
			zTextBoxColumnStyleInfo77.IsVisible = false;
			zTextBoxColumnStyleInfo77.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo78.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("a8b0adda-a093-42d8-8c20-d902b4e8e2a3", "Notify Party Name");
			zTextBoxColumnStyleInfo78.ColumnName = "ABL_NotifyPartyName";
			zTextBoxColumnStyleInfo78.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo78.IsCustomColumn = false;
			zTextBoxColumnStyleInfo78.IsVisible = false;
			zTextBoxColumnStyleInfo78.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(114);
			zTextBoxColumnStyleInfo79.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("e67ae120-9856-4580-a761-f95c123b550b", "Notify Party Street 1");
			zTextBoxColumnStyleInfo79.ColumnName = "ABL_NotifyPartyStreet1";
			zTextBoxColumnStyleInfo79.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo79.IsCustomColumn = false;
			zTextBoxColumnStyleInfo79.IsVisible = false;
			zTextBoxColumnStyleInfo79.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(124);
			zTextBoxColumnStyleInfo80.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("db3f1b3f-1011-4a16-be5d-f71a36a6a0cd", "Notify Party Street 2");
			zTextBoxColumnStyleInfo80.ColumnName = "ABL_NotifyPartyStreet2";
			zTextBoxColumnStyleInfo80.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo80.IsCustomColumn = false;
			zTextBoxColumnStyleInfo80.IsVisible = false;
			zTextBoxColumnStyleInfo80.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(124);
			zTextBoxColumnStyleInfo81.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("c14246e0-8d56-49d4-b685-479f0c880fb4", "Notify Party City");
			zTextBoxColumnStyleInfo81.ColumnName = "ABL_NotifyPartyCity";
			zTextBoxColumnStyleInfo81.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo81.IsCustomColumn = false;
			zTextBoxColumnStyleInfo81.IsVisible = false;
			zTextBoxColumnStyleInfo81.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(103);
			zTextBoxColumnStyleInfo82.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5a20fa4f-270a-4ca8-8063-8e1765e9a3cb", "Notify Party State");
			zTextBoxColumnStyleInfo82.ColumnName = "ABL_NotifyPartyState";
			zTextBoxColumnStyleInfo82.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo82.IsCustomColumn = false;
			zTextBoxColumnStyleInfo82.IsVisible = false;
			zTextBoxColumnStyleInfo82.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo83.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("907cca4e-5e9a-41c3-87c3-0878bb12d228", "Notify Party Country");
			zTextBoxColumnStyleInfo83.ColumnName = "ABL_RN_NKNotifyPartyCountry";
			zTextBoxColumnStyleInfo83.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo83.IsCustomColumn = false;
			zTextBoxColumnStyleInfo83.IsVisible = false;
			zTextBoxColumnStyleInfo83.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(124);
			zTextBoxColumnStyleInfo84.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("71371b53-098c-430a-baa2-be55002fd7d9", "Notify Party Postcode");
			zTextBoxColumnStyleInfo84.ColumnName = "ABL_NotifyPartyPostcode";
			zTextBoxColumnStyleInfo84.GroupName = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5d8767d4-f828-4769-bd2f-ba6f7869d8b6", "Notify Party");
			zTextBoxColumnStyleInfo84.IsCustomColumn = false;
			zTextBoxColumnStyleInfo84.IsVisible = false;
			zTextBoxColumnStyleInfo84.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			zTextBoxColumnStyleInfo85.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ad2fad1f-37c3-457c-9fca-bc3c61e34ade", "Goods Location");
			zTextBoxColumnStyleInfo85.ColumnName = "ABL_GoodsLocation";
			zTextBoxColumnStyleInfo85.IsCustomColumn = false;
			zTextBoxColumnStyleInfo85.IsVisible = false;
			zTextBoxColumnStyleInfo85.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(99);
			zTextBoxColumnStyleInfo86.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5e0c81dd-af10-4ee1-aa64-703c0e42e4f6", "Location Information");
			zTextBoxColumnStyleInfo86.ColumnName = "ABL_LocationInformation";
			zTextBoxColumnStyleInfo86.IsCustomColumn = false;
			zTextBoxColumnStyleInfo86.IsVisible = false;
			zTextBoxColumnStyleInfo86.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(126);
			zTextBoxColumnStyleInfo87.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("73f695d5-9616-4255-a223-ca6f31b85e64", "Customs Number");
			zTextBoxColumnStyleInfo87.ColumnName = "CustomsEntryNumber";
			zTextBoxColumnStyleInfo87.IsCustomColumn = false;
			zTextBoxColumnStyleInfo87.IsVisible = false;
			zTextBoxColumnStyleInfo87.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(129);
			zTextBoxColumnStyleInfo88.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("5b8ac096-4acf-40ba-8fbd-33594db041b0", "", "Customs Entry No. Type", "Customs Entry Number Type", "");
			zTextBoxColumnStyleInfo88.ColumnName = "CustomsEntryNumberType";
			zTextBoxColumnStyleInfo88.IsCustomColumn = false;
			zTextBoxColumnStyleInfo88.IsVisible = false;
			zTextBoxColumnStyleInfo88.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(143);
			zTextBoxColumnStyleInfo89.ColumnName = "ABL_SpecialCargoCode";
			zTextBoxColumnStyleInfo89.IsCustomColumn = false;
			zTextBoxColumnStyleInfo89.IsVisible = true;
			zTextBoxColumnStyleInfo89.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo90.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ManifestBillFilterStrip|ManifestRegistrationNumber", "", "Manifest Reg Num", "Manifest Registration Number", "");
			zTextBoxColumnStyleInfo90.ColumnName = "Header+RegistrationNumber";
			zTextBoxColumnStyleInfo90.IsCustomColumn = false;
			zTextBoxColumnStyleInfo90.IsVisible = false;
			zTextBoxColumnStyleInfo90.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDateEditColumnStyleInfo6.CaptionResourceString = Enterprise.Customs.ASYCUDA.Module.Res.GetData("ManifestBillFilterStrip|RegistrationDateFilter", "", "Manifest Reg Date", "Manifest Registration Date", "");
			zDateEditColumnStyleInfo6.ColumnName = "Header+RegistrationDate";
			zDateEditColumnStyleInfo6.IsCustomColumn = false;
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(125);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo13);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo18);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo19);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo20);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo21);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo22);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo23);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo24);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo25);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo26);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo27);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo28);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo90);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo29);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo30);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo31);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo32);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo33);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo34);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo35);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo36);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo37);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo38);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo39);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo40);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo41);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo42);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo43);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo44);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo45);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo46);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo47);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo48);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo49);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo50);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo51);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo52);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo53);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo54);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo55);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo56);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo57);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo58);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo59);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo60);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo61);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo62);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo63);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo64);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo65);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo66);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo67);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo68);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo69);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo70);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo71);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo72);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo73);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo74);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo75);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo76);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo77);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo78);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo79);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo80);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo81);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo82);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo83);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo84);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo85);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo86);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo87);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo88);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo89);
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Enterprise.Customs.ASYCUDA.Business.AsycudaBill);
			// 
			// ASYCUDAManifestBillFilterStripControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Name = "ASYCUDAManifestBillFilterStripControl";
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			this.grid.ResumeLayout(false);
			this.grid.PerformLayout();
			this.AddStripButton.ResumeLayout(true);
			this.AddStripButton.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion
	}
}
