<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.US.eManifest.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.US.eManifest.Business</AssemblyName>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.BufferManagement.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.US.Business" />
    <Reference Include="Enterprise.Customs.US.DataTransfer" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.NumberFountain" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Business\ShipmentAction\AutoShipmentAction.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoShipmentAction.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\AmendmentReasonCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AmendmentReasonCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ConveyanceReferences.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ConveyanceReferences.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ConveyanceTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ConveyanceTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\CrewACEIdTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CrewACEIdTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\CrewTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CrewTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\CusCodeDataTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CusCodeDataTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\EquipmentTypeFilterList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EquipmentTypeFilterList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\EquipmentTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EquipmentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\EquipmentTypesPartial.cs">
      <DependentUpon>EquipmentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\FDAFreightIndicators.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>FDAFreightIndicators.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\MessageActionCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageActionCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\PackageTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PackageTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\RegistrationInfoTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>RegistrationInfoTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ShipmentEntryStatusList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ShipmentEntryStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ShipmentEntryStatusListPartial.cs">
      <DependentUpon>ShipmentEntryStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ShipmentAmendmentCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ShipmentAmendmentCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ShipmentAmendmentCodesPartial.cs">
      <DependentUpon>ShipmentAmendmentCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TripEntryStatusList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TripEntryStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TripEntryStatusListPartial.cs">
      <DependentUpon>TripEntryStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ErrorReasons.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ErrorReasons.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\IITEntityIndicatorCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>IITEntityIndicatorCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\InbondTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>InbondTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\PartyIdTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PartyIdTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\PartyTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PartyTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\PortCodeTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PortCodeTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ServiceTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ServiceTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ShipmentTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ShipmentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TransitDirectionCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TransitDirectionCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TransportModes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TransportModes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TravelDocumentTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TravelDocumentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\TravelDocumentTypesPartial.cs">
      <DependentUpon>TravelDocumentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\MessageTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageTypes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Business\ShipmentAction\AutoShipmentAction.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoShipmentAction.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\AmendmentReasonCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AmendmentReasonCodes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ConveyanceReferences.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ConveyanceReferences.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ConveyanceTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ConveyanceTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\CrewACEIdTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CrewACEIdTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\CrewTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CrewTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\CusCodeDataTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CusCodeDataTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\EquipmentTypeFilterList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EquipmentTypeFilterList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\FDAFreightIndicators.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>FDAFreightIndicators.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\MessageActionCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageActionCodes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\PackageTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PackageTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\RegistrationInfoTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>RegistrationInfoTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ShipmentEntryStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ShipmentEntryStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ShipmentAmendmentCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ShipmentAmendmentCodes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\TripEntryStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TripEntryStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ErrorReasons.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ErrorReasons.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\EquipmentTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EquipmentTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\IITEntityIndicatorCodes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>IITEntityIndicatorCodes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\InbondTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>InbondTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\PartyIdTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PartyIdTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\PartyTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PartyTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\PortCodeTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PortCodeTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ServiceTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ServiceTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ShipmentTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ShipmentTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\TransitDirectionCodes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransitDirectionCodes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\TransportModes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransportModes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\TravelDocumentTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TravelDocumentTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\MessageTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.eManifest.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>