//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from ImportGoodsApplicationTypeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.BR.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class ImportGoodsApplicationTypeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Consumption = "1";
			public const string IncorporationAssets = "2";
			public const string Industrialization = "3";
			public const string Resale = "4";
			public const string Other = "5";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString Consumption { get { return ResString.GetMultilingualString("ImportGoodsApplicationTypeList|Consumption", "Consumption"); } }
			public static MultilingualString IncorporationAssets { get { return ResString.GetMultilingualString("ImportGoodsApplicationTypeList|IncorporationAssets", "Incorporation into Fixed Assets"); } }
			public static MultilingualString Industrialization { get { return ResString.GetMultilingualString("ImportGoodsApplicationTypeList|Industrialization", "Industrialization"); } }
			public static MultilingualString Resale { get { return ResString.GetMultilingualString("ImportGoodsApplicationTypeList|Resale", "Resale"); } }
			public static MultilingualString Other { get { return ResString.GetMultilingualString("ImportGoodsApplicationTypeList|Other", "Other"); } }
		}

		public ImportGoodsApplicationTypeList()
		{
			AddPair(Codes.Consumption, Descriptions.Consumption);
			AddPair(Codes.IncorporationAssets, Descriptions.IncorporationAssets);
			AddPair(Codes.Industrialization, Descriptions.Industrialization);
			AddPair(Codes.Resale, Descriptions.Resale);
			AddPair(Codes.Other, Descriptions.Other);
		}
	}
}
