<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputPath>..\..\..\..\..\..\Bin\</OutputPath>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Enterprise.Warehouse.Web.Testing</RootNamespace>
    <AssemblyName>Enterprise.Warehouse.Web.Testing</AssemblyName>
    <SignAssembly>false</SignAssembly>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.ApplicationContext.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ComponentModel">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.ComponentModel.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Database.Shared">
      <HintPath>..\..\..\..\..\..\bin\CargoWise.Database.Shared.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Database.TestFramework">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Database.TestFramework.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Definitions">
      <HintPath>..\..\..\..\..\..\bin\CargoWise.Definitions.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Integration">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.IO">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.IO.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings.Cache">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.ResourceStrings.Cache.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Shared.40">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Shared.40.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.ResourceStrings.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Types">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Types.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.BarcodeParsing.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.BarcodeParsing.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.BarcodeParsing.Business.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.BarcodeParsing.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.BarcodeParsingEngine">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.BarcodeParsingEngine.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DataTransfer.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.DataTransfer.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DeniedPartyScreening.Common">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.DeniedPartyScreening.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DbUpgrader.Shared">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.DbUpgrader.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngine">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.DocumentEngine.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineCore">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.DocumentEngineCore.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineIntegration">
      <HintPath>..\..\..\..\..\..\bin\Enterprise.DocumentEngineIntegration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.EConversation.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.EConversation.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Environment">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Environment.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Common.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Freight.Common.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.MasterFiles.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Packing.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Packing.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Packing.Business.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Packing.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Packing.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Packing.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ProductionRules.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ProductionRules.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Rating.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Rating.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Registry.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Registry.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Semaphores.Common">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Semaphores.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.TransportCommon.Registry">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.TransportCommon.Registry.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.TransportCommon.Shared">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.TransportCommon.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Cartonisation.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Cartonisation.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Environment.Business.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Environment.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.Business.Testing">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.Business.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.PickByLabel">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.PickByLabel.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.PickByLabel.Testing">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.PickByLabel.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.TrolleyPicking.Testing">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.TrolleyPicking.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.GlowInterop">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.GlowInterop.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Shared.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Shared.Test.dll</HintPath>
    </Reference>
    <Reference Include="Moq">
      <HintPath>..\..\..\..\..\..\Bin\Moq.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\..\..\..\..\Bin\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\..\..\..\..\bin\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="WTG.Foundation.Cryptography">
      <HintPath>..\..\..\..\..\..\Bin\WTG.Foundation.Cryptography.dll</HintPath>
    </Reference>
    <Reference Include="WTG.Foundation.Http">
      <HintPath>..\..\..\..\..\..\Bin\WTG.Foundation.Http.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Security.Core">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Security.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.TransportBookings.Shared">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.TransportBookings.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Environment.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Environment.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Integration">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.TrolleyPicking">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.TrolleyPicking.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\..\..\..\Bin\Resources.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="WTG.RTUS.Interface">
      <HintPath>..\..\..\..\..\..\Bin\WTG.RTUS.Interface.dll</HintPath>
    </Reference>
    <Reference Include="WTG.RTUS.Printing">
      <HintPath>..\..\..\..\..\..\Bin\WTG.RTUS.Printing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Licensing.Core">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Licensing.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Integration.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Warehouse.Integration.Test.dll</HintPath>
    </Reference>
    <Reference Include="WTG.Foundation.Cryptography.UserSecrets">
      <HintPath>..\..\..\..\..\..\Bin\WTG.Foundation.Cryptography.UserSecrets.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GlobalBase">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GlobalBase.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Semaphores.Common.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.Semaphores.Common.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI.Test">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Shared">
      <HintPath>..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Shared.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Web\Warehouse.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="WebService\TestFiles\*.*" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="WebService\TestFiles\BlankAndroidVersion.txt" />
  </ItemGroup>
</Project>