//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from NZContainerCodeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.NZ.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class NZContainerCodeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string _1 = "1";
			public const string _10 = "10";
			public const string _11 = "11";
			public const string _12 = "12";
			public const string _13 = "13";
			public const string _14 = "14";
			public const string _15 = "15";
			public const string _16 = "16";
			public const string _17 = "17";
			public const string _18 = "18";
			public const string _19 = "19";
			public const string _2 = "2";
			public const string _20 = "20";
			public const string _20G0 = "20G0";
			public const string _20G1 = "20G1";
			public const string _20H0 = "20H0";
			public const string _20P1 = "20P1";
			public const string _20T0 = "20T0";
			public const string _20T1 = "20T1";
			public const string _20T2 = "20T2";
			public const string _20T3 = "20T3";
			public const string _20T4 = "20T4";
			public const string _20T5 = "20T5";
			public const string _20T6 = "20T6";
			public const string _20T7 = "20T7";
			public const string _20T8 = "20T8";
			public const string _21 = "21";
			public const string _22 = "22";
			public const string _22B0 = "22B0";
			public const string _22G0 = "22G0";
			public const string _22G1 = "22G1";
			public const string _22H0 = "22H0";
			public const string _22K2 = "22K2";
			public const string _22P0 = "22P0";
			public const string _22P1 = "22P1";
			public const string _22P3 = "22P3";
			public const string _22P4 = "22P4";
			public const string _22P7 = "22P7";
			public const string _22P8 = "22P8";
			public const string _22P9 = "22P9";
			public const string _22PP = "22PP";
			public const string _22R0 = "22R0";
			public const string _22R1 = "22R1";
			public const string _22R7 = "22R7";
			public const string _22R9 = "22R9";
			public const string _22S1 = "22S1";
			public const string _22T0 = "22T0";
			public const string _22T1 = "22T1";
			public const string _22T2 = "22T2";
			public const string _22T3 = "22T3";
			public const string _22T4 = "22T4";
			public const string _22T5 = "22T5";
			public const string _22T6 = "22T6";
			public const string _22T7 = "22T7";
			public const string _22T8 = "22T8";
			public const string _22U1 = "22U1";
			public const string _22U6 = "22U6";
			public const string _22V0 = "22V0";
			public const string _22V2 = "22V2";
			public const string _22V3 = "22V3";
			public const string _23 = "23";
			public const string _24 = "24";
			public const string _25 = "25";
			public const string _25G0 = "25G0";
			public const string _25G1 = "25G1";
			public const string _25R0 = "25R0";
			public const string _25R1 = "25R1";
			public const string _25T3 = "25T3";
			public const string _25T4 = "25T4";
			public const string _26 = "26";
			public const string _26G0 = "26G0";
			public const string _26H0 = "26H0";
			public const string _27 = "27";
			public const string _28 = "28";
			public const string _28T8 = "28T8";
			public const string _28U1 = "28U1";
			public const string _28V0 = "28V0";
			public const string _29 = "29";
			public const string _29P0 = "29P0";
			public const string _2EG0 = "2EG0";
			public const string _3 = "3";
			public const string _30 = "30";
			public const string _31 = "31";
			public const string _32 = "32";
			public const string _33 = "33";
			public const string _34 = "34";
			public const string _35 = "35";
			public const string _36 = "36";
			public const string _37 = "37";
			public const string _38 = "38";
			public const string _39 = "39";
			public const string _4 = "4";
			public const string _40 = "40";
			public const string _41 = "41";
			public const string _42 = "42";
			public const string _42G0 = "42G0";
			public const string _42G1 = "42G1";
			public const string _42H0 = "42H0";
			public const string _42P0 = "42P0";
			public const string _42P1 = "42P1";
			public const string _42P3 = "42P3";
			public const string _42P4 = "42P4";
			public const string _42P6 = "42P6";
			public const string _42P8 = "42P8";
			public const string _42P9 = "42P9";
			public const string _42R1 = "42R1";
			public const string _42R3 = "42R3";
			public const string _42R9 = "42R9";
			public const string _42S1 = "42S1";
			public const string _42T2 = "42T2";
			public const string _42T5 = "42T5";
			public const string _42T6 = "42T6";
			public const string _42T8 = "42T8";
			public const string _42U1 = "42U1";
			public const string _42U6 = "42U6";
			public const string _43 = "43";
			public const string _44 = "44";
			public const string _45 = "45";
			public const string _45B3 = "45B3";
			public const string _45G0 = "45G0";
			public const string _45G1 = "45G1";
			public const string _45P0 = "45P0";
			public const string _45P3 = "45P3";
			public const string _45P8 = "45P8";
			public const string _45R0 = "45R0";
			public const string _45R1 = "45R1";
			public const string _45R7 = "45R7";
			public const string _45R8 = "45R8";
			public const string _45R9 = "45R9";
			public const string _45U1 = "45U1";
			public const string _45U6 = "45U6";
			public const string _46H0 = "46H0";
			public const string _48T8 = "48T8";
			public const string _48T9 = "48T9";
			public const string _49P0 = "49P0";
			public const string _4CG0 = "4CG0";
			public const string _4EG1 = "4EG1";
			public const string _5 = "5";
			public const string _6 = "6";
			public const string _7 = "7";
			public const string _8 = "8";
			public const string _9 = "9";
			public const string L0G1 = "L0G1";
			public const string L2G1 = "L2G1";
			public const string L5G1 = "L5G1";
			public const string ULD = "ULD";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString _1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_1", "Dime coated tank"); } }
			public static MultilingualString _10 { get { return ResString.GetMultilingualString("NZContainerCodeList|_10", "Non-working reefer 40 ft"); } }
			public static MultilingualString _11 { get { return ResString.GetMultilingualString("NZContainerCodeList|_11", "Box pallet"); } }
			public static MultilingualString _12 { get { return ResString.GetMultilingualString("NZContainerCodeList|_12", "Euro pallet"); } }
			public static MultilingualString _13 { get { return ResString.GetMultilingualString("NZContainerCodeList|_13", "Scandinavian pallet"); } }
			public static MultilingualString _14 { get { return ResString.GetMultilingualString("NZContainerCodeList|_14", "Trailer"); } }
			public static MultilingualString _15 { get { return ResString.GetMultilingualString("NZContainerCodeList|_15", "Non-working reefer 20 ft"); } }
			public static MultilingualString _16 { get { return ResString.GetMultilingualString("NZContainerCodeList|_16", "Exchangeable pallet"); } }
			public static MultilingualString _17 { get { return ResString.GetMultilingualString("NZContainerCodeList|_17", "Semi-trailer"); } }
			public static MultilingualString _18 { get { return ResString.GetMultilingualString("NZContainerCodeList|_18", "Tank container 20 ft."); } }
			public static MultilingualString _19 { get { return ResString.GetMultilingualString("NZContainerCodeList|_19", "Tank container 30 ft."); } }
			public static MultilingualString _2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_2", "Epoxy coated tank"); } }
			public static MultilingualString _20 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20", "Tank container 40 ft."); } }
			public static MultilingualString _20G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20G0", "20 GENERAL PURPOSE CONT G0"); } }
			public static MultilingualString _20G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20G1", "20 GENERAL PURPOSE CONT G1"); } }
			public static MultilingualString _20H0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20H0", "20 INSULATED CONTAINER"); } }
			public static MultilingualString _20P1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20P1", "20 FLAT (FIXED ENDS)"); } }
			public static MultilingualString _20T0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T0", "20 TANK CONTAINER T0"); } }
			public static MultilingualString _20T1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T1", "20 TANK CONTAINER T1"); } }
			public static MultilingualString _20T2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T2", "20 TANK CONTAINER T2"); } }
			public static MultilingualString _20T3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T3", "20 TANK CONTAINER T3"); } }
			public static MultilingualString _20T4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T4", "20 TANK CONTAINER T4"); } }
			public static MultilingualString _20T5 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T5", "20 TANK CONTAINER T5"); } }
			public static MultilingualString _20T6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T6", "20 TANK CONTAINER T6"); } }
			public static MultilingualString _20T7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T7", "20 TANK CONTAINER T7"); } }
			public static MultilingualString _20T8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_20T8", "20 TANK CONTAINER T8"); } }
			public static MultilingualString _21 { get { return ResString.GetMultilingualString("NZContainerCodeList|_21", "Container General Purpose 20 ft."); } }
			public static MultilingualString _22 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22", "Container General Purpose 30 ft."); } }
			public static MultilingualString _22B0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22B0", "22 BULK CONTAINER"); } }
			public static MultilingualString _22G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22G0", "22 GENERAL PURPOSE CONT G0"); } }
			public static MultilingualString _22G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22G1", "22 GENERAL PURPOSE CONT G1"); } }
			public static MultilingualString _22H0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22H0", "22 INSULATED CONTAINER"); } }
			public static MultilingualString _22K2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22K2", "20 FOODSTUFF TANK CONTAINER"); } }
			public static MultilingualString _22P0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P0", "23 PLATFORM CONTAINER P0"); } }
			public static MultilingualString _22P1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P1", "22 FLAT (FIXED ENDS)"); } }
			public static MultilingualString _22P3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P3", "22 FLAT (COLLAPSIBLE) P3"); } }
			public static MultilingualString _22P4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P4", "22 FLAT (COLLAPSIBLE) P4"); } }
			public static MultilingualString _22P7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P7", "22 FLAT (GENSET CARRIER)"); } }
			public static MultilingualString _22P8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P8", "22 FLAT (COLL.FLUSH FOLDING)"); } }
			public static MultilingualString _22P9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22P9", "22 FLAT (COLLAPSIBLE) P9"); } }
			public static MultilingualString _22PP { get { return ResString.GetMultilingualString("NZContainerCodeList|_22PP", "20 INTERMODAL POWER PACK GEN"); } }
			public static MultilingualString _22R0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22R0", "21 REEFER CONT R0"); } }
			public static MultilingualString _22R1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22R1", "22 REEFER CONTAINER"); } }
			public static MultilingualString _22R7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22R7", "22 BUILT-IN GEN PWR SPLY REEF"); } }
			public static MultilingualString _22R9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22R9", "22 REEFER CONT.(NO FOOD)"); } }
			public static MultilingualString _22S1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22S1", "22 NAMED CARGO CONTAINER"); } }
			public static MultilingualString _22T0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T0", "22 TANK CONTAINER T0"); } }
			public static MultilingualString _22T1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T1", "22 TANK CONTAINER T1"); } }
			public static MultilingualString _22T2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T2", "22 TANK CONTAINER"); } }
			public static MultilingualString _22T3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T3", "22 TANK CONTAINER T3"); } }
			public static MultilingualString _22T4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T4", "22 TANK CONTAINER T4"); } }
			public static MultilingualString _22T5 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T5", "22 TANK CONTAINER T5"); } }
			public static MultilingualString _22T6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T6", "22 TANK CONTAINER T6"); } }
			public static MultilingualString _22T7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T7", "22 TANK CONTAINER T7"); } }
			public static MultilingualString _22T8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22T8", "22 TANK CONTAINER T8"); } }
			public static MultilingualString _22U1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22U1", "22 OPEN TOP CONTAINER"); } }
			public static MultilingualString _22U6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22U6", "22 HARDTOP CONTAINER"); } }
			public static MultilingualString _22V0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22V0", "22 VENTILATED CONTAINER V0"); } }
			public static MultilingualString _22V2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22V2", "22 VENTILATED CONTAINER V2"); } }
			public static MultilingualString _22V3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_22V3", "22 VENTILATED CONTAINER V3"); } }
			public static MultilingualString _23 { get { return ResString.GetMultilingualString("NZContainerCodeList|_23", "Container General Purpose 40 ft."); } }
			public static MultilingualString _24 { get { return ResString.GetMultilingualString("NZContainerCodeList|_24", "Refrigerator tank 20 ft."); } }
			public static MultilingualString _25 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25", "Refrigerator tank 30 ft."); } }
			public static MultilingualString _25G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25G0", "25 GP-CONTAINER OVER-HEIGHT"); } }
			public static MultilingualString _25G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25G1", "26 GP-CONTAINER G1"); } }
			public static MultilingualString _25R0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25R0", "25 REEFER CONTAINER R0"); } }
			public static MultilingualString _25R1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25R1", "25 REEFER CONTAINER R1"); } }
			public static MultilingualString _25T3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25T3", "20 HIGH CUBE TANK DG LIQUID"); } }
			public static MultilingualString _25T4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_25T4", "20 HIGH CUBE TANK DG LIQUID"); } }
			public static MultilingualString _26 { get { return ResString.GetMultilingualString("NZContainerCodeList|_26", "Refrigerator tank 40 ft."); } }
			public static MultilingualString _26G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_26G0", "26 GP-CONTAINER OVER-HEIGHT"); } }
			public static MultilingualString _26H0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_26H0", "26 INSULATED CONTAINER"); } }
			public static MultilingualString _27 { get { return ResString.GetMultilingualString("NZContainerCodeList|_27", "Tank container IC 20 ft."); } }
			public static MultilingualString _28 { get { return ResString.GetMultilingualString("NZContainerCodeList|_28", "Tank container IC 30 ft."); } }
			public static MultilingualString _28T8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_28T8", "28 TANK FOR GAS"); } }
			public static MultilingualString _28U1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_28U1", "28 OPEN TOP (HALF HEIGHT)"); } }
			public static MultilingualString _28V0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_28V0", "28 VE-HALF-HEIGHT =1448 MM"); } }
			public static MultilingualString _29 { get { return ResString.GetMultilingualString("NZContainerCodeList|_29", "Tank container IC 40 ft."); } }
			public static MultilingualString _29P0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_29P0", "29 PLATFORM"); } }
			public static MultilingualString _2EG0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_2EG0", "2E HIGH CUBE CONT. =2.5M WIDE"); } }
			public static MultilingualString _3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_3", "IMO1"); } }
			public static MultilingualString _30 { get { return ResString.GetMultilingualString("NZContainerCodeList|_30", "Refrigerator tank IC 20 ft."); } }
			public static MultilingualString _31 { get { return ResString.GetMultilingualString("NZContainerCodeList|_31", "Temperature controlled 30 ft"); } }
			public static MultilingualString _32 { get { return ResString.GetMultilingualString("NZContainerCodeList|_32", "Refrigerator tank IC 40 ft."); } }
			public static MultilingualString _33 { get { return ResString.GetMultilingualString("NZContainerCodeList|_33", "Movable case: L < 6,15m"); } }
			public static MultilingualString _34 { get { return ResString.GetMultilingualString("NZContainerCodeList|_34", "Movable case: 6,15m<L<7,82m"); } }
			public static MultilingualString _35 { get { return ResString.GetMultilingualString("NZContainerCodeList|_35", "Movable case: 7,82m<L<9,15m"); } }
			public static MultilingualString _36 { get { return ResString.GetMultilingualString("NZContainerCodeList|_36", "Movable case: 9,15m<L<10,90m"); } }
			public static MultilingualString _37 { get { return ResString.GetMultilingualString("NZContainerCodeList|_37", "Movable case: 10,90m<L< 13,75m"); } }
			public static MultilingualString _38 { get { return ResString.GetMultilingualString("NZContainerCodeList|_38", "Tote bin"); } }
			public static MultilingualString _39 { get { return ResString.GetMultilingualString("NZContainerCodeList|_39", "Temperature controlled 20 ft"); } }
			public static MultilingualString _4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_4", "IMO2"); } }
			public static MultilingualString _40 { get { return ResString.GetMultilingualString("NZContainerCodeList|_40", "Temperature controlled 40 ft"); } }
			public static MultilingualString _41 { get { return ResString.GetMultilingualString("NZContainerCodeList|_41", "Non-working reefer 30 ft"); } }
			public static MultilingualString _42 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42", "Dual trailers"); } }
			public static MultilingualString _42G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42G0", "42 GENERAL PURPOSE CONT G0"); } }
			public static MultilingualString _42G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42G1", "42 GENERAL PURPOSE CONT G1"); } }
			public static MultilingualString _42H0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42H0", "42 INSULATED CONTAINER"); } }
			public static MultilingualString _42P0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P0", "42 PLATFORM CONTAINER P0"); } }
			public static MultilingualString _42P1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P1", "42 FLAT (FIXED ENDS)"); } }
			public static MultilingualString _42P3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P3", "42 FLAT (COLLAPSIBLE) P3"); } }
			public static MultilingualString _42P4 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P4", "42 FLAT (COLLAPSIBLE) P4"); } }
			public static MultilingualString _42P6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P6", "42 FLAT SPACE SAVER"); } }
			public static MultilingualString _42P8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P8", "42 FLAT (COLL.FLUSH FOLDING)"); } }
			public static MultilingualString _42P9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42P9", "42 FLAT (COLLAPSIBLE) P9"); } }
			public static MultilingualString _42R1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42R1", "42 REEFER CONTAINER"); } }
			public static MultilingualString _42R3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42R3", "42 REEFER CONT.(DIESEL GEN.)"); } }
			public static MultilingualString _42R9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42R9", "42 REEFER CONT.(NO FOOD)"); } }
			public static MultilingualString _42S1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42S1", "42 NAMED CARGO CONTAINER"); } }
			public static MultilingualString _42T2 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42T2", "42 TANK CONTAINER T2"); } }
			public static MultilingualString _42T5 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42T5", "42 TANK CONTAINER T5"); } }
			public static MultilingualString _42T6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42T6", "42 TANK CONTAINER T6"); } }
			public static MultilingualString _42T8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42T8", "42 TANK CONTAINER T8"); } }
			public static MultilingualString _42U1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42U1", "42 OPEN TOP CONTAINER"); } }
			public static MultilingualString _42U6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_42U6", "42 HARDTOP CONTAINER"); } }
			public static MultilingualString _43 { get { return ResString.GetMultilingualString("NZContainerCodeList|_43", "Open top IL 20 ft"); } }
			public static MultilingualString _44 { get { return ResString.GetMultilingualString("NZContainerCodeList|_44", "Closed top IL 20 ft"); } }
			public static MultilingualString _45 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45", "Closed top IL 40 ft"); } }
			public static MultilingualString _45B3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45B3", "45 BULK CONTAINER"); } }
			public static MultilingualString _45G0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45G0", "45 HIGH CUBE CONT G0"); } }
			public static MultilingualString _45G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45G1", "45 HIGH CUBE CONT G1"); } }
			public static MultilingualString _45P0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45P0", "45 PLATFORM CONTAINER P0"); } }
			public static MultilingualString _45P3 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45P3", "45 FLAT (COLLAPSIBLE)"); } }
			public static MultilingualString _45P8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45P8", "45 FLAT (COLL.FLUSH FOLDING)"); } }
			public static MultilingualString _45R0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45R0", "44 REEFER CONT R0"); } }
			public static MultilingualString _45R1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45R1", "45 REEFER HIGHCUBE CONTAINER"); } }
			public static MultilingualString _45R7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45R7", "40 HIGH CUBE REEFER CONTAINER"); } }
			public static MultilingualString _45R8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45R8", "45 REEFER CONTAINER R8"); } }
			public static MultilingualString _45R9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45R9", "45 REEFER CONT.(NO FOOD)"); } }
			public static MultilingualString _45U1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45U1", "45 OPEN TOP CONTAINER"); } }
			public static MultilingualString _45U6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_45U6", "45 HIGH CUBE HARDTOP CONT."); } }
			public static MultilingualString _46H0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_46H0", "46 INSULATED CONTAINER"); } }
			public static MultilingualString _48T8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_48T8", "48 TANK FOR GAS"); } }
			public static MultilingualString _48T9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_48T9", "40 FOOT TANK FOR GAS CONTAINER"); } }
			public static MultilingualString _49P0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_49P0", "49 PLATFORM"); } }
			public static MultilingualString _4CG0 { get { return ResString.GetMultilingualString("NZContainerCodeList|_4CG0", "4C GP CONTAINER (WIDTH 2.5 M)"); } }
			public static MultilingualString _4EG1 { get { return ResString.GetMultilingualString("NZContainerCodeList|_4EG1", "40 HIGH CUBE DRY SHIPPING CONT"); } }
			public static MultilingualString _5 { get { return ResString.GetMultilingualString("NZContainerCodeList|_5", "IMO3"); } }
			public static MultilingualString _6 { get { return ResString.GetMultilingualString("NZContainerCodeList|_6", "Pressurized tank"); } }
			public static MultilingualString _7 { get { return ResString.GetMultilingualString("NZContainerCodeList|_7", "Refrigerated tank"); } }
			public static MultilingualString _8 { get { return ResString.GetMultilingualString("NZContainerCodeList|_8", "Semi-refrigerated"); } }
			public static MultilingualString _9 { get { return ResString.GetMultilingualString("NZContainerCodeList|_9", "Stainless steel tank"); } }
			public static MultilingualString L0G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|L0G1", "45 HIGH CUBE CONT G1"); } }
			public static MultilingualString L2G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|L2G1", "452 HIGH CUBE CONT."); } }
			public static MultilingualString L5G1 { get { return ResString.GetMultilingualString("NZContainerCodeList|L5G1", "455 HIGH CUBE CONT."); } }
			public static MultilingualString ULD { get { return ResString.GetMultilingualString("NZContainerCodeList|ULD", "UNIT LOAD DEVICE / AIRCAN"); } }
		}

		public NZContainerCodeList()
		{
			AddPair(Codes._1, Descriptions._1);
			AddPair(Codes._10, Descriptions._10);
			AddPair(Codes._11, Descriptions._11);
			AddPair(Codes._12, Descriptions._12);
			AddPair(Codes._13, Descriptions._13);
			AddPair(Codes._14, Descriptions._14);
			AddPair(Codes._15, Descriptions._15);
			AddPair(Codes._16, Descriptions._16);
			AddPair(Codes._17, Descriptions._17);
			AddPair(Codes._18, Descriptions._18);
			AddPair(Codes._19, Descriptions._19);
			AddPair(Codes._2, Descriptions._2);
			AddPair(Codes._20, Descriptions._20);
			AddPair(Codes._20G0, Descriptions._20G0);
			AddPair(Codes._20G1, Descriptions._20G1);
			AddPair(Codes._20H0, Descriptions._20H0);
			AddPair(Codes._20P1, Descriptions._20P1);
			AddPair(Codes._20T0, Descriptions._20T0);
			AddPair(Codes._20T1, Descriptions._20T1);
			AddPair(Codes._20T2, Descriptions._20T2);
			AddPair(Codes._20T3, Descriptions._20T3);
			AddPair(Codes._20T4, Descriptions._20T4);
			AddPair(Codes._20T5, Descriptions._20T5);
			AddPair(Codes._20T6, Descriptions._20T6);
			AddPair(Codes._20T7, Descriptions._20T7);
			AddPair(Codes._20T8, Descriptions._20T8);
			AddPair(Codes._21, Descriptions._21);
			AddPair(Codes._22, Descriptions._22);
			AddPair(Codes._22B0, Descriptions._22B0);
			AddPair(Codes._22G0, Descriptions._22G0);
			AddPair(Codes._22G1, Descriptions._22G1);
			AddPair(Codes._22H0, Descriptions._22H0);
			AddPair(Codes._22K2, Descriptions._22K2);
			AddPair(Codes._22P0, Descriptions._22P0);
			AddPair(Codes._22P1, Descriptions._22P1);
			AddPair(Codes._22P3, Descriptions._22P3);
			AddPair(Codes._22P4, Descriptions._22P4);
			AddPair(Codes._22P7, Descriptions._22P7);
			AddPair(Codes._22P8, Descriptions._22P8);
			AddPair(Codes._22P9, Descriptions._22P9);
			AddPair(Codes._22PP, Descriptions._22PP);
			AddPair(Codes._22R0, Descriptions._22R0);
			AddPair(Codes._22R1, Descriptions._22R1);
			AddPair(Codes._22R7, Descriptions._22R7);
			AddPair(Codes._22R9, Descriptions._22R9);
			AddPair(Codes._22S1, Descriptions._22S1);
			AddPair(Codes._22T0, Descriptions._22T0);
			AddPair(Codes._22T1, Descriptions._22T1);
			AddPair(Codes._22T2, Descriptions._22T2);
			AddPair(Codes._22T3, Descriptions._22T3);
			AddPair(Codes._22T4, Descriptions._22T4);
			AddPair(Codes._22T5, Descriptions._22T5);
			AddPair(Codes._22T6, Descriptions._22T6);
			AddPair(Codes._22T7, Descriptions._22T7);
			AddPair(Codes._22T8, Descriptions._22T8);
			AddPair(Codes._22U1, Descriptions._22U1);
			AddPair(Codes._22U6, Descriptions._22U6);
			AddPair(Codes._22V0, Descriptions._22V0);
			AddPair(Codes._22V2, Descriptions._22V2);
			AddPair(Codes._22V3, Descriptions._22V3);
			AddPair(Codes._23, Descriptions._23);
			AddPair(Codes._24, Descriptions._24);
			AddPair(Codes._25, Descriptions._25);
			AddPair(Codes._25G0, Descriptions._25G0);
			AddPair(Codes._25G1, Descriptions._25G1);
			AddPair(Codes._25R0, Descriptions._25R0);
			AddPair(Codes._25R1, Descriptions._25R1);
			AddPair(Codes._25T3, Descriptions._25T3);
			AddPair(Codes._25T4, Descriptions._25T4);
			AddPair(Codes._26, Descriptions._26);
			AddPair(Codes._26G0, Descriptions._26G0);
			AddPair(Codes._26H0, Descriptions._26H0);
			AddPair(Codes._27, Descriptions._27);
			AddPair(Codes._28, Descriptions._28);
			AddPair(Codes._28T8, Descriptions._28T8);
			AddPair(Codes._28U1, Descriptions._28U1);
			AddPair(Codes._28V0, Descriptions._28V0);
			AddPair(Codes._29, Descriptions._29);
			AddPair(Codes._29P0, Descriptions._29P0);
			AddPair(Codes._2EG0, Descriptions._2EG0);
			AddPair(Codes._3, Descriptions._3);
			AddPair(Codes._30, Descriptions._30);
			AddPair(Codes._31, Descriptions._31);
			AddPair(Codes._32, Descriptions._32);
			AddPair(Codes._33, Descriptions._33);
			AddPair(Codes._34, Descriptions._34);
			AddPair(Codes._35, Descriptions._35);
			AddPair(Codes._36, Descriptions._36);
			AddPair(Codes._37, Descriptions._37);
			AddPair(Codes._38, Descriptions._38);
			AddPair(Codes._39, Descriptions._39);
			AddPair(Codes._4, Descriptions._4);
			AddPair(Codes._40, Descriptions._40);
			AddPair(Codes._41, Descriptions._41);
			AddPair(Codes._42, Descriptions._42);
			AddPair(Codes._42G0, Descriptions._42G0);
			AddPair(Codes._42G1, Descriptions._42G1);
			AddPair(Codes._42H0, Descriptions._42H0);
			AddPair(Codes._42P0, Descriptions._42P0);
			AddPair(Codes._42P1, Descriptions._42P1);
			AddPair(Codes._42P3, Descriptions._42P3);
			AddPair(Codes._42P4, Descriptions._42P4);
			AddPair(Codes._42P6, Descriptions._42P6);
			AddPair(Codes._42P8, Descriptions._42P8);
			AddPair(Codes._42P9, Descriptions._42P9);
			AddPair(Codes._42R1, Descriptions._42R1);
			AddPair(Codes._42R3, Descriptions._42R3);
			AddPair(Codes._42R9, Descriptions._42R9);
			AddPair(Codes._42S1, Descriptions._42S1);
			AddPair(Codes._42T2, Descriptions._42T2);
			AddPair(Codes._42T5, Descriptions._42T5);
			AddPair(Codes._42T6, Descriptions._42T6);
			AddPair(Codes._42T8, Descriptions._42T8);
			AddPair(Codes._42U1, Descriptions._42U1);
			AddPair(Codes._42U6, Descriptions._42U6);
			AddPair(Codes._43, Descriptions._43);
			AddPair(Codes._44, Descriptions._44);
			AddPair(Codes._45, Descriptions._45);
			AddPair(Codes._45B3, Descriptions._45B3);
			AddPair(Codes._45G0, Descriptions._45G0);
			AddPair(Codes._45G1, Descriptions._45G1);
			AddPair(Codes._45P0, Descriptions._45P0);
			AddPair(Codes._45P3, Descriptions._45P3);
			AddPair(Codes._45P8, Descriptions._45P8);
			AddPair(Codes._45R0, Descriptions._45R0);
			AddPair(Codes._45R1, Descriptions._45R1);
			AddPair(Codes._45R7, Descriptions._45R7);
			AddPair(Codes._45R8, Descriptions._45R8);
			AddPair(Codes._45R9, Descriptions._45R9);
			AddPair(Codes._45U1, Descriptions._45U1);
			AddPair(Codes._45U6, Descriptions._45U6);
			AddPair(Codes._46H0, Descriptions._46H0);
			AddPair(Codes._48T8, Descriptions._48T8);
			AddPair(Codes._48T9, Descriptions._48T9);
			AddPair(Codes._49P0, Descriptions._49P0);
			AddPair(Codes._4CG0, Descriptions._4CG0);
			AddPair(Codes._4EG1, Descriptions._4EG1);
			AddPair(Codes._5, Descriptions._5);
			AddPair(Codes._6, Descriptions._6);
			AddPair(Codes._7, Descriptions._7);
			AddPair(Codes._8, Descriptions._8);
			AddPair(Codes._9, Descriptions._9);
			AddPair(Codes.L0G1, Descriptions.L0G1);
			AddPair(Codes.L2G1, Descriptions.L2G1);
			AddPair(Codes.L5G1, Descriptions.L5G1);
			AddPair(Codes.ULD, Descriptions.ULD);
		}
	}
}
