<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.DE.NCTS.Module.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.DE.NCTS.GUI.csproj" />
    <ProjectReference Include="..\Module\Enterprise.Customs.DE.NCTS.Module.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>