//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.MasterFiles.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoStmNumberRange : EnterpriseBusinessObject, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "StmNumberRange";
			public const string PK        = "SNR_PK";

			public const string SNR_Name                   = "SNR_Name";
			public const string SNR_Owner                  = "SNR_Owner";
			public const string SNR_SystemCreateTimeUtc    = "SNR_SystemCreateTimeUtc";
			public const string SNR_SystemCreateUser       = "SNR_SystemCreateUser";
			public const string SNR_SystemLastEditTimeUtc  = "SNR_SystemLastEditTimeUtc";
			public const string SNR_SystemLastEditUser     = "SNR_SystemLastEditUser";
			public const string SNR_ThresholdRunOutWarning = "SNR_ThresholdRunOutWarning";

			public const int SNR_NameMaxLength = 35;
			public const int SNR_SystemCreateUserMaxLength = 3;
			public const int SNR_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoStmNumberRange(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(SNR_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(SNR_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(SNR_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(SNR_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return StmNumberRangeSchema.PK; }
		}

		#endregion

		#region Properties

		#region SNR_Name

		public virtual ZString SNR_Name
		{
			get {  return new ZString(GetValueFromRowSafely(StmNumberRangeSchema.SNR_Name)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = SNR_NameInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateSNR_Name();
				}
			}
		}

		public virtual ZPropertyInfo SNR_NameInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_Name); }
		}

		#endregion

		#region SNR_Owner

		public virtual ZGuid SNR_Owner
		{
			get {  return new ZGuid(GetValueFromRowSafely(StmNumberRangeSchema.SNR_Owner)); }
			set
			{
				SetPropertyValue(SNR_OwnerInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateSNR_Owner();
				}
			}
		}

		public virtual ZPropertyInfo SNR_OwnerInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_Owner); }
		}

		#endregion

		#region SNR_SystemCreateTimeUtc

		public virtual ZDateTime SNR_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(StmNumberRangeSchema.SNR_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(SNR_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo SNR_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_SystemCreateTimeUtc); }
		}

		#endregion

		#region SNR_SystemCreateUser

		public virtual ZString SNR_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(StmNumberRangeSchema.SNR_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = SNR_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo SNR_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_SystemCreateUser); }
		}

		#endregion

		#region SNR_SystemLastEditTimeUtc

		public virtual ZDateTime SNR_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(StmNumberRangeSchema.SNR_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(SNR_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo SNR_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_SystemLastEditTimeUtc); }
		}

		#endregion

		#region SNR_SystemLastEditUser

		public virtual ZString SNR_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(StmNumberRangeSchema.SNR_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = SNR_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo SNR_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_SystemLastEditUser); }
		}

		#endregion

		#region SNR_ThresholdRunOutWarning

		public virtual ZLong SNR_ThresholdRunOutWarning
		{
			get {  return new ZLong(GetValueFromRowSafely(StmNumberRangeSchema.SNR_ThresholdRunOutWarning)); }
			set
			{
				SetPropertyValue(SNR_ThresholdRunOutWarningInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateSNR_ThresholdRunOutWarning();
				}
			}
		}

		public virtual ZPropertyInfo SNR_ThresholdRunOutWarningInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(StmNumberRangeSchema.Constants.SNR_ThresholdRunOutWarning); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[StmNumberRangeSchema.Constants.SNR_Name                  ] = "";
			row[StmNumberRangeSchema.Constants.SNR_Owner                 ] = Guid.Empty;
			row[StmNumberRangeSchema.Constants.SNR_SystemCreateTimeUtc   ] = DBNull.Value;
			row[StmNumberRangeSchema.Constants.SNR_SystemCreateUser      ] = "";
			row[StmNumberRangeSchema.Constants.SNR_SystemLastEditTimeUtc ] = DBNull.Value;
			row[StmNumberRangeSchema.Constants.SNR_SystemLastEditUser    ] = "";
			row[StmNumberRangeSchema.Constants.SNR_ThresholdRunOutWarning] = (long)0;
		}

		#endregion

		#region Lookups

		public StmNumberRangeLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual StmNumberRangeLookups GetNewLookups()
		{
			return new StmNumberRangeLookups(this);
		}

		StmNumberRangeLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public StmNumberRangeValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual StmNumberRangeValidation GetNewValidation()
		{
			return new StmNumberRangeValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return SNR_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return SNR_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return SNR_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return SNR_SystemLastEditUser; }
		}

		#endregion
	}
}
