<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
	<ItemGroup>
		<WeaverFiles Include="..\..\..\Bin\Common\Fody\netstandard2.0\CargoWise.RefDbRepo.Common.Customization.Fody.dll" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="CargoWise.RefDbRepo.Common.Customization.Fody">
			<HintPath>..\..\..\Bin\Common\Fody\netstandard2.0\CargoWise.RefDbRepo.Common.Customization.Fody.dll</HintPath>
		</Reference>
		<Reference Include="CargoWise.RefDbRepo.Staging.ApplicationConfig">
			<HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.ApplicationConfig.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
