<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Accounting.CountryCompliance.Interfaces</AssemblyName>
    <RootNamespace>Enterprise.Accounting.CountryCompliance.Interfaces</RootNamespace>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Resources" />
  </ItemGroup>
  
  <ItemGroup>
    <AdditionalFiles Include="..\BannedSymbols.txt" />
  </ItemGroup>

  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />

</Project>