<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Accounting.GUI.Testing</AssemblyName>
    <RootNamespace>Enterprise.Accounting.GUI.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
    <Configurations>Debug;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounting.Module\Enterprise.Accounting.Module.Winzor.csproj" />
    <ProjectReference Include="..\Accounting.TaxFramework\GUI\Accounting.TaxFramework.GUI.Winzor.csproj" />
    <ProjectReference Include="..\GUI\Enterprise.Accounting.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Async" />
    <Reference Include="Enterprise.Accounting.Export" />
    <Reference Include="Enterprise.Accounting.GeneralLedgerData.Business" />
    <Reference Include="Enterprise.Accounting.RulesEngine.Facts" />
    <Reference Include="Enterprise.Accounting.Business.Presentation" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>