<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.ZA.Manifest.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.ZA.Manifest.Business</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.ZA.Business" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Edifact.D99B" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
	  <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BusinessObject\AsycudaBill\AsycudaBillCountry.cs">
      <DependentUpon>AsycudaBill.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObject\AsycudaBill\AsycudaBillCountryValidation.cs">
      <DependentUpon>AsycudaBillValidationForRegularBill.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObject\AsycudaManifestHeader\AsycudaManifestHeader.Country.cs">
      <DependentUpon>AsycudaManifestHeader.cs</DependentUpon>
    </Compile>
    <Compile Update="BusinessObject\AsycudaManifestHeader\AsycudaManifestHeaderValidation.Country.cs">
      <DependentUpon>AsycudaManifestHeaderValidation.cs</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\LandedPurposeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LandedPurposeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaDataTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaDataTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaEmptyFullIndicatorList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaEmptyFullIndicatorList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaLRNTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaLRNTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaManifestTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaManifestTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaManifestTypes_Partial.cs">
      <DependentUpon>ZaManifestTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaOccupations.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaOccupations.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaReasonForMovement.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaReasonForMovement.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaShipmentTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaShipmentTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaTravelDocumentTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaTravelDocumentTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ZaTravellerTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ZaTravellerTypes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\LandedPurposeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>LandedPurposeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ZaDataTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaDataTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ZaEmptyFullIndicatorList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaEmptyFullIndicatorList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ZaLRNTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaLRNTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ZaManifestTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaManifestTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ZaOccupations.xml">
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaOccupations.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ZaReasonForMovement.xml">
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaReasonForMovement.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ZaShipmentTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaShipmentTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ZaTravelDocumentTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaTravelDocumentTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ZaTravellerTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.ZA.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ZaTravellerTypes.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>