<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ActiveDirectory.TestFramework" />
    <Reference Include="CargoWise.Async" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Data.Providers.Common" />
    <Reference Include="CargoWise.Data.Providers.Common.Test" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection.Administration.SqlServer" />
    <Reference Include="CargoWise.DataProtection.SqlExtensions" />
    <Reference Include="CargoWise.DataProtection.TestFramework" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Microsoft.Bcl.AsyncInterfaces" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="System.DirectoryServices" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Setup\Enterprise.AlwaysOn.Setup.csproj" />
  </ItemGroup>
</Project>