<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Staging.CLASETMessageProcessor.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Staging.CLASETMessageProcessor.Test</AssemblyName>
    <Configurations>Debug;</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <OutputPath>..\..\..\Bin\Staging\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
    <Reference Include="Edifact">
      <HintPath>..\..\..\Bin\Staging\net8.0\Edifact.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Edifact.D09B">
      <HintPath>..\..\..\Bin\Staging\net8.0\Enterprise.Edifact.D09B.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="TestData\SGCLASET Test CHSCODE_CPDCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test CPCCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test CTYCODE_PRTCODE 2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test CTYCODE_PRTCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test LOCCODE_CPDCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test CPDCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test CTYCODE_CPCCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET Test LOCCODE_CPCCODE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_ALL.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_CHSCODE.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_CPCCODE_NO_DES.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_CPCCODE.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_CTYCODE.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_LOCCODE.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestData\SGCLASET XML_CUSCOM_PRTCODE.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CHSCODE_CPDCODE\RefCusTariffZZ_SG_Commodity Codes_00007_20190128.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CPCCODE\RefCusProcedureZZ_SG_Procedure Codes_00012_20190221.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\ProcessCommodityTerminatedWithoutReleaseDate\RefCusTariffZZ_SG_Commodity Codes_1_00001_20190101.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\ProcessCommodityTerminated\RefCusTariffZZ_SG_Commodity Codes_00001_20190102.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\ProcessCommodity\RefCusTariffZZ_SG_Commodity Codes_00001_20190102.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CPDCODE\RefCusTariffZZ_SG_Commodity Codes_01000_20180329.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CTYCODE_CPCCODE\RefCusProcedureZZ_SG_Procedure Codes_00017_20170615.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CTYCODE_PRTCODE 2\RefCusCodeListZZ_SG_Port Codes_00034_20171026.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\CTYCODE_PRTCODE\RefCusCodeListZZ_SG_Port Codes_00034_20171026.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\LOCCODE_CPDCODE\RefCusCodeListZZ_SG_Facility Codes_00033_20171020.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\LOCCODE_CPDCODE\RefCusTariffZZ_SG_Commodity Codes_00033_20171020.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\LOCCODE_CPCCODE\RefCusCodeListZZ_SG_Facility Codes_00036_20171030.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\LOCCODE_CPCCODE\RefCusProcedureZZ_SG_Procedure Codes_00036_20171030.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\SGCLASET XML_CUSCOM_CPCCODE_NO_DES\RefCusTariffZZ_SG_Commodity Codes_00008_20220509.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSCOM_CPCCODE\RefCusProcedureZZ_SG_Procedure Codes_00029_20201019.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSCOM_LOCCODE\RefCusCodeListZZ_SG_Facility Codes_00005_20110225.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSCOM_PRTCODE\RefCusCodeListZZ_SG_Port Codes_00003_20110217.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSTOMS_ALL\RefCusCodeListZZ_SG_Facility Codes_00001_20110214.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSTOMS_ALL\RefCusCodeListZZ_SG_Port Codes_00001_20110214.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSTOMS_ALL\RefCusProcedureZZ_SG_Procedure Codes_00001_20110214.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="XMLResult\XML_CUSTOMS_ALL\RefCusTariffZZ_SG_Commodity Codes_00001_20110214.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CLASETMessageProcessor\CLASETMessageProcessor.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>