// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.Universal.JobDeclarationDataObjectReader`4.UntickOverrideFreightDefaultsIfSameWithXML(System.EventArgs,System.Object)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\Universal\Reader\JobDeclarationDataObjectReader.cs:868:33
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.ShipmentDeclarationValueObjectDataAdapter.NewBusinessObject(Enterprise.DataTransfer.Xml.XsdVersion1.Shipment,Enterprise.DataTransfer.Integration.IValueObjectImportContext)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\ShipmentDeclarationValueObjectDataAdapter.cs:82:10
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.GroupInvoiceValueObjectDataAdapterTest.TestExportToValueObjectGroupInvoice")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\GroupInvoiceValueObjectDataAdapter.cs:147:31
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.ShipmentDeclarationValueObjectDataAdapter.GetJobDeclaration(Enterprise.DataTransfer.Integration.IValueObjectImportContext)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\ShipmentDeclarationValueObjectDataAdapter.cs:212:10
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.GroupInvoiceValueObjectDataAdapterTest.TestAddExportEvent")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\GroupInvoiceValueObjectDataAdapter.cs:180:31
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.DeclarationValueObjectDataAdapter.ImportFromBranchDetails(Enterprise.Customs.Business.BaseJobDeclaration,Enterprise.DataTransfer.Xml.XsdVersion1.DeclarationBranch,Enterprise.DataTransfer.Integration.IValueObjectImportContext)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\DeclarationXmlDataAdapter.cs:1377:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.DeclarationValueObjectDataAdapter.ImportShipmentDetails(Enterprise.Customs.Business.BaseJobDeclaration,Enterprise.DataTransfer.Xml.XsdVersion1.Consol,Enterprise.DataTransfer.Xml.XsdVersion1.Shipment,Enterprise.DataTransfer.Integration.IValueObjectImportContext)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\DeclarationXmlDataAdapter.cs:1023:26
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.Testing.DeclarationValueObjectDataAdapterTest.TestAddExportEvent")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\DeclarationXmlDataAdapter.cs:5427:36
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.Testing.DeclarationValueObjectDataAdapterTest.TestGetMatchedOrganisation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\DeclarationXmlDataAdapter.cs:5790:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.DataTransfer.DeclarationValueObjectDataAdapter.ImportFromBranchDetails(BaseJobDeclaration,Enterprise.DataTransfer.Xml.XsdVersion1.DeclarationBranch,Enterprise.DataTransfer.Integration.IValueObjectImportContext)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\DataTransfer\DataTransfer\ValueObjectDataAdapters\DeclarationXmlDataAdapter.cs:1377:24
