<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <RootNamespace>Enterprise.Customs.ES.ExitControl.GUI.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.MasterFiles.GUI" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Moq" />
    <Reference Include="Enterprise.MasterFiles.GUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.ES.ExitControl.GUI.csproj" />
  </ItemGroup>
</Project>