<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 37500
 -->
	<xsd:element name="quotaBalanceEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Old balance -->
            <xsd:attribute ref="at:oldBalance"/>
            <!-- New balance -->
            <xsd:attribute ref="at:newBalance"/>
            <!-- Imported amount -->
            <xsd:attribute ref="at:importedAmount"/>
            <!-- Quota event occurrence timestamp  -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Last import date in allocation -->
            <xsd:attribute ref="at:lastImportDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>
