<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 37505, 37510, 37515, 37520, 37525, 37530
 -->            
    <xsd:element name="quotaUnblockingEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Unblocking date -->
            <xsd:attribute ref="at:unblockingDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="quotaCriticalEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp  -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Quota critical state -->
            <xsd:attribute ref="at:quotaCriticalStateCode"/>
            <!-- Critical state change date -->
            <xsd:attribute ref="at:criticalDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="quotaExhaustionEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp  -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Exhaustion date -->
            <xsd:attribute ref="at:exhaustionDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="quotaReopeningEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp  -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Reopening date -->
            <xsd:attribute ref="at:reopeningDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="quotaUnsuspensionEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Unsuspension date -->
            <xsd:attribute ref="at:unsuspensionDate"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="quotaClosedAndBalanceTransferredEvent">
        <xsd:complexType>
            <!-- Quota definition SID -->
            <xsd:attribute ref="at:SIDQuotaDefinition"/>
            <!-- Quota event occurrence timestamp  -->
            <xsd:attribute ref="at:occurrenceTimestamp"/>
            <!-- Closing Date -->
            <xsd:attribute ref="at:closingDate"/>
            <!-- Transferred amount -->
            <xsd:attribute ref="at:transferredAmount"/>
            <!-- Target quota definition SID -->
            <xsd:attribute ref="at:SIDTargetDefinition"/>
            <!-- Represent the national column X_END_OCCURRENCE_TIMESTAMP -->
            <xsd:attribute ref="at:endOccurrenceTimestamp"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>
