<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0</TargetFrameworks>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\Bin\XT.REST.Deployment</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\Bin\XT.REST.Deployment</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.7.0" />
    <PackageReference Include="AzureSign.Core" Version="6.0.0" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="17.12.6" ExcludeAssets="runtime" />
    <PackageReference Include="RSAKeyVaultProvider" Version="2.1.1" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.0-rc.2.24473.5" />
    <PackageReference Include="WTG.DevTools.Common" Version="24.8.28.21" />
    <PackageReference Include="XH.Framework.Deployment.XT" Version="10.0.5" />
	<PackageReference Include="Docker.DotNet" Version="3.125.15" />
	<PackageReference Include="SharpCompress" Version="0.37.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Build.Framework" />
  </ItemGroup>

  <ItemGroup>
    <None Update="XT.REST.Deployment.tasks">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>