<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Providers.Common" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.BarcodeParsing.Business" />
    <Reference Include="Enterprise.BarcodeParsingEngine" />
    <Reference Include="Enterprise.BufferManagement.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.US.Business" />
    <Reference Include="Enterprise.Customs.US.Messaging.Business" />
    <Reference Include="Enterprise.DeniedPartyScreening.Common" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngine.Macros" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.AWB.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.NumberFountain" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Rating.Integration" />
    <Reference Include="Enterprise.Rating.Rateable" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportCommon.Business" />
    <Reference Include="Enterprise.TransportCommon.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Microsoft.SqlServer.Types" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="WTG.Ecommerce.Business" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TransportBookings.Business" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Workflow" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BarcodeParsing\ETailTargetFields.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ETailTargetFields.xml</DependentUpon>
    </Compile>
    <Compile Update="Common\CodeDescriptionPairList\EcommercePortals.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EcommercePortals.xml</DependentUpon>
    </Compile>
    <Compile Update="Customs\CodeDescriptionPairList\CustomsModuleCodes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CustomsModuleCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="BusinessObjects\HVLVConsignment\HVLVConsignmentPreScreeningStatusCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>HVLVConsignmentPreScreeningStatusCodes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Integration\Enterprise.eTail.Integration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="BusinessObjects\HVLVConsignment\HVLVConsignmentResourceStrings.xml" />
    <EmbeddedResource Include="BusinessObjects\HVLVItem\HVLVItemResourceStrings.xml" />
    <EmbeddedResource Include="BusinessObjects\HVLVBookingHeader\HVLVBookingHeaderResourceStrings.xml" />
    <EmbeddedResource Include="BusinessObjects\HVLVOriginLoadList\HVLVOriginLoadListResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="BarcodeParsing\ETailTargetFields.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ETailTargetFields.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.eTail.Business</CustomToolNamespace>
    </None>
    <None Update="BusinessObjects\HVLVConsignment\HVLVConsignmentPreScreeningStatusCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>HVLVConsignmentPreScreeningStatusCodes.cs</LastGenOutput>
    </None>
    <EmbeddedResource Include="BusinessObjects\HVLVItemLine\HVLVItemLineResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Common\CodeDescriptionPairList\EcommercePortals.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EcommercePortals.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.eTail.Business</CustomToolNamespace>
    </None>
    <None Update="Customs\CodeDescriptionPairList\CustomsModuleCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CustomsModuleCodes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.eTail.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>