use eHubTransactions

CREATE TABLE eHubClient
(
	CC_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_CC_PK DEFAULT (newid()),
	CC_ID VARCHAR(36) NOT NULL,
	CC_Odyssey_OH UNIQUEIDENTIFIER NOT NULL
	
	CONSTRAINT PK_UX__CC_PK PRIMARY KEY  CLUSTERED ( CC_PK )
)

CREATE TABLE eHubDocumentType
(
	DT_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_DT_PK DEFAULT (newid()),
	DT_Code VARCHAR(5) NOT NULL,
	DT_Description NVARCHAR(100) NULL,
	
	CONSTRAINT PK_UX__DT_PK PRIMARY KEY  CLUSTERED ( DT_PK )
)

CREATE TABLE eHubDocumentTypeMapping
(
	DM_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_DM_PK DEFAULT (newid()),
	DM_CC_Sender UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_DM_CC_Sender_FK2_eHubClient_RRR_121 
											FOREIGN KEY  (DM_CC_Sender) REFERENCES eHubClient ( CC_PK ),
	DM_CC_Recipient UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_DM_CC_Recipient_FK2_eHubClient_RRR_121 
											FOREIGN KEY  (DM_CC_Recipient) REFERENCES eHubClient ( CC_PK ),
	DM_DT_Source UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_DM_DT_Source_FK2_eHubDocumentType_RRR_121
											FOREIGN KEY  (DM_DT_Source) REFERENCES eHubDocumentType ( DT_PK ),
	DM_DT_Target UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_DM_DT_Target_FK2_eHubDocumentType_RRR_121
											FOREIGN KEY  (DM_DT_Target) REFERENCES eHubDocumentType ( DT_PK ),
											
	CONSTRAINT PK_UX__DM_PK PRIMARY KEY  CLUSTERED ( DM_PK )
)

CREATE TABLE eHubTransformationMapping
(
	TM_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_TM_PK DEFAULT (newid()),
	TM_DT_Source UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_TM_DT_Source_FK2_eHubDocumentType_RRR_121
											FOREIGN KEY  (TM_DT_Source) REFERENCES eHubDocumentType ( DT_PK ),
	TM_DT_Target UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubDocumentTypeMapping_TM_DT_Target_FK2_eHubDocumentType_RRR_121
											FOREIGN KEY  (TM_DT_Target) REFERENCES eHubDocumentType ( DT_PK ),

	TM_XSLT text NOT NULL,
	
	CONSTRAINT PK_UX__TM_PK PRIMARY KEY  CLUSTERED ( TM_PK )
)

CREATE TABLE eHubDocument
(
	DC_PK uniqueidentifier NOT NULL CONSTRAINT DF_DC_PK DEFAULT (newid()),
	DC_Content ntext NOT NULL,
	
	CONSTRAINT PK_UX__DC_PK PRIMARY KEY  CLUSTERED ( DC_PK )
)

CREATE TABLE eHubInboxEnvelope
(
	IE_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_IE_PK DEFAULT (newid()),
	IE_ID VARCHAR(36) NOT NULL,
	IE_CC_Sender UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubEnvelope_IE_CC_Sender_FK2_eHubClient_RRR_121 
											FOREIGN KEY  (IE_CC_Sender) REFERENCES eHubClient ( CC_PK ),
	IE_SenderApplicationVersion varchar(10) NOT NULL,
	IE_Version VARCHAR(10) NOT NULL,
	IE_Original NTEXT NOT NULL,

	CONSTRAINT PK_UX__IE_PK PRIMARY KEY  CLUSTERED ( IE_PK )
)

CREATE TABLE eHubInboxEnvelopeStatus
(
	IS_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_IS_PK DEFAULT (newid()),
	IS_IE UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubInboxEnvelopeStatus_IS_IE_FK2_eHubInboxEnvelope_RRR_121 
											FOREIGN KEY  (IS_IE) REFERENCES eHubInboxEnvelope ( IE_PK ),
	IS_Status VARCHAR(3) NOT NULL,
	IS_UTC DATETIME NOT NULL
	
	CONSTRAINT PK_UX__IS_PK PRIMARY KEY  CLUSTERED ( IS_PK )
)

CREATE TABLE eHubOutboxEnvelope
(
	OI_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_OI_PK DEFAULT (newid()),
	OI_ID VARCHAR(36) NOT NULL,
	OI_CC_Recipient UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubOutboxEnvelope_OI_CC_Recipient_FK2_eHubClient_RRR_121 
											FOREIGN KEY  (OI_CC_Recipient) REFERENCES eHubClient ( CC_PK ),
	
	OI_DC_Document UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubOutboxEnvelope_DC_DC_Document_FK2_eHubDocument_RRR_121 
											FOREIGN KEY  (OI_DC_Document) REFERENCES eHubDocument ( DC_PK ),
	
	OI_IE_Inbox UNIQUEIDENTIFIER NULL CONSTRAINT eHubOutboxEnvelope_OI_IE_Inbox_FK2_eHubInboxEnvelope_RRR_121 
											FOREIGN KEY  (OI_IE_Inbox) REFERENCES eHubInboxEnvelope ( IE_PK ),

	CONSTRAINT PK_UX__OI_PK PRIMARY KEY  CLUSTERED ( OI_PK )
)

CREATE TABLE eHubOutboxEnvelopeArchive
(
	OA_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_OA_PK DEFAULT (newid()),
	OA_CC_Recipient UNIQUEIDENTIFIER NOT NULL CONSTRAINT eHubOutboxEnvelope_OA_CC_Recipient_FK2_eHubClient_RRR_121 
											FOREIGN KEY  (OA_CC_Recipient) REFERENCES eHubClient ( CC_PK ),
	
	OA_DC_Document UNIQUEIDENTIFIER NULL, --Index to be add
	
	OA_IE_Inbox UNIQUEIDENTIFIER NULL, --No index needed for now
	OA_ArchiveUTC DATETIME NOT NULL

	CONSTRAINT PK_UX__OA_PK PRIMARY KEY  CLUSTERED ( OA_PK )
)






