using System.Data;
using CargoWise.RefDbRepo.Common.DbUpgrade;

namespace CargoWise.RefDbRepo.Service.UpgradeManagerRunner
{
	public class AddRulesWI00196189Transformation : DataTransformation, IDataTransformationTask
	{
		public AddRulesWI00196189Transformation(int version) : base(version)
		{
		}

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:ReviewSqlQueriesForSecurityVulnerabilities")]
		public void Run(IDbTransaction trans)
		{
			var sql = @"
DECLARE @ZZ1_PK UNIQUEIDENTIFIER
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '41071110') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'41071110','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '41071210') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'41071210','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '41071910') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'41071910','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480220') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480220','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '48024020') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'48024020','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480254') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480254','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480255') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480255','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480256') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480256','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480257') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480257','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480258') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480258','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '480525') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'480525','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '48059') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'48059','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '48102905') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'48102905','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '481031') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'481031','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '481032') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'481032','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '481151') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'481151','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52081') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52081','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52082') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52082','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52083') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52083','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52084') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52084','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52085') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52085','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52091') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52091','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52092') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52092','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52093') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52093','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52094') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52094','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52095') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52095','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52101') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52101','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52102') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52102','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52103') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52103','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52104') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52104','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52105') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52105','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52111') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52111','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52113') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52113','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52114') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52114','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52115') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52115','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52121') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52121','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '52122') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'52122','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '540720') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'540720','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '54074') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'54074','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '54075') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'54075','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '540769') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'540769','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '54077') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'54077','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '54078') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'54078','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '54079') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'54079','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55131') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55131','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55132') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55132','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55133') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55133','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55134') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55134','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55141') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55141','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55142') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55142','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '55144') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'55144','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '551511') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'551511','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '580137') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'580137','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '59061015') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'59061015','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '60063190') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'60063190','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '60063290') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'60063290','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '60063390') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'60063390','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '60063490') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'60063490','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '63052090') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'63052090','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '701952') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'701952','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END
IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU1' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZI_TariffType = (select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1') and t.ZZ1_TariffCode = '70195910') = 0  BEGIN  SELECT @ZZ1_PK = newid();  INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'70195910','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU1','SM','ZA');  END

IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU2' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZZ_NKDataGrouping = 'ZA' and t.ZZ1_TariffCode = '59070080') = 0  
BEGIN  
	SELECT @ZZ1_PK = null
	SELECT Top 1 @ZZ1_PK = ZZ1_PK FROM RefCusTariffRule t WHERE t.ZZ1_ZZZ_NKDataGrouping = 'ZA' and t.ZZ1_TariffCode = '59070080'
	IF (@ZZ1_PK is null)
		BEGIN
			SELECT @ZZ1_PK = newid();
			INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'59070080','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  
		END
	INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU2','SM','ZA');  
END

IF (SELECT COUNT(1) FROM RefCusTariffRule t JOIN RefCusTariffUOMRule uom on uom.ZZ8_ZZ1_Tariff = t.ZZ1_PK and uom.ZZ8_Type = 'RU2' and uom.ZZ8_UOM = 'SM' and uom.ZZ8_ZZZ_NKDataGrouping = 'ZA' WHERE t.ZZ1_ZZZ_NKDataGrouping = 'ZA' and t.ZZ1_TariffCode = '39191041') = 0  
BEGIN  
	SELECT @ZZ1_PK = null
	SELECT Top 1 @ZZ1_PK = ZZ1_PK FROM RefCusTariffRule t WHERE t.ZZ1_ZZZ_NKDataGrouping = 'ZA' and t.ZZ1_TariffCode = '39191041'
	IF (@ZZ1_PK is null)
		BEGIN
			SELECT @ZZ1_PK = newid();
			INSERT INTO RefCusTariffRule (ZZ1_PK,ZZ1_TariffCode,ZZ1_ZZZ_NKDataGrouping,ZZ1_ZZI_TariffType)  VALUES (@ZZ1_PK,'39191041','ZA',(select ZZI_PK From RefCusTariffType Where ZZI_TariffType = '1P1'));  
		END
	INSERT INTO RefCusTariffUOMRule (ZZ8_ZZ1_Tariff,ZZ8_Type,ZZ8_UOM,ZZ8_ZZZ_NKDataGrouping)   VALUES (@ZZ1_PK,'RU2','SM','ZA');  
END
";

			using (var cmd = trans.Connection?.CreateCommand())
			{
				cmd.Connection = trans.Connection;
				cmd.Transaction = trans;
				cmd.CommandText = sql;
				cmd.ExecuteNonQuery();
			}
		}
	}
}
