<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.DataConverters</AssemblyName>
    <RootNamespace>Enterprise.DataConverters</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
    <Reference Include="System.Data.OleDb" />
  </ItemGroup>
</Project>