<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <RootNamespace>CargoWise.RefDbRepo.STLBillingCollector.TestDummyCollectors</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.STLBillingCollector.TestDummyCollectors</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
