<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.DataTransfer" />
    <Reference Include="Enterprise.DataTransfer.GUI" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.DbUpgrader.Shared" />
    <Reference Include="Enterprise.DbUpgrader.Shared.Testing" />
    <Reference Include="Enterprise.Freight.Common.GUI" />
    <Reference Include="Enterprise.Freight.DataTransfer" />
    <Reference Include="Enterprise.Freight.GUI" />
    <Reference Include="Enterprise.Freight.Module" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="System.Resources.Extensions" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LocalCartage.GUI\Enterprise.Freight.LocalCartage.GUI.csproj" />
    <ProjectReference Include="..\LocalCartage.Module\Enterprise.Freight.LocalCartage.Module.csproj" />
  </ItemGroup>
</Project>