<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Freight.LocalCartage.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.Freight.LocalCartage.Module.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LocalCartage.GUI\Enterprise.Freight.LocalCartage.GUI.Winzor.csproj" />
    <ProjectReference Include="..\LocalCartage.Module\Enterprise.Freight.LocalCartage.Module.Winzor.csproj" />
    <ProjectReference Include="..\LocalCartage.Integration\Enterprise.Freight.LocalCartage.Integration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>