<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 20000, 20005, 20010
 -->
	<xsd:element name="footnote">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:footnoteDescriptionPeriod" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- Footnote type -->
            <xsd:attribute ref="at:footnoteType"/>
            <!-- Footnote id -->
        	<xsd:attribute ref="at:footnoteId"/>
            <!-- Validity start date of footnote code -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of footnote code -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="footnoteDescriptionPeriod">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:footnoteDescription" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- SID of footnote description period -->
            <xsd:attribute ref="at:SID"/>
            <!-- Validity start date of footnote description -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of footnote description -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="footnoteDescription">
        <xsd:complexType>
            <!-- Language id of description -->
            <xsd:attribute ref="at:languageId"/>
            <!-- Long description of footnote -->
            <xsd:attribute ref="at:description"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>
