<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rct="http://agriculture.gov.au/nexdoc/common/rex/CommonTypes_1.0" xmlns:ct="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" targetNamespace="http://agriculture.gov.au/nexdoc/CancelRexSoap_1.0" elementFormDefault="qualified">
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" schemaLocation="common/CommonTypes.xsd" />
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/rex/CommonTypes_1.0" schemaLocation="common/rex/CommonTypes.xsd" />
  <xsd:element name="CancelRex">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="identification" type="rct:RexSubmissionIdentificationType" />
        <xsd:element name="reason" type="ct:AlphaNumeric100Type" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="CancelRexResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="cancelRexResponse" type="rct:CancelRexMessageResponse" maxOccurs="1" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>