<?xml version="1.0" encoding="Windows-1252"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ct="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" targetNamespace="http://agriculture.gov.au/nexdoc/EndorsementInquirySoap_1.0" elementFormDefault="qualified">
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/rex/CommonTypes_1.0" schemaLocation="common/rex/CommonTypes.xsd" />
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" schemaLocation="common/CommonTypes.xsd" />
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/EnumTypes_1.0" schemaLocation="common/EnumTypes.xsd" />
  <xsd:element name="EndorsementInquiry">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="reason" type="ct:AlphaNumeric254Type" />
        <xsd:element name="endorsementText" type="ct:AlphaNumeric254Type" />
        <xsd:element name="productDetails" minOccurs="0">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="country" type="ct:CountryType" />
              <xsd:element name="commodityType" type="ct:CommodityType" />
              <xsd:element name="productType" type="ct:ProductType" />
              <xsd:element name="packType" type="ct:PackageType" />
              <xsd:element name="preservationType" type="ct:PreservationType" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
        <xsd:element name="document" minOccurs="0" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="name" type="ct:AlphaNumeric200Type" />
              <xsd:element name="mimeType" type="ct:AlphaNumeric100Type" />
              <xsd:element name="data" type="xsd:base64Binary" minOccurs="0" />
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="EndorsementInquiryResponse">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="serviceRequestIdentifier" type="xsd:string" minOccurs="0" />
        <xsd:element name="serviceRequestStatus" type="xsd:string" minOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>