<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:this="http://agriculture.gov.au/nexdoc/ExporterSoap_1.0" xmlns:ct="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" targetNamespace="http://agriculture.gov.au/nexdoc/ExporterSoap_1.0" elementFormDefault="qualified">
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" schemaLocation="common/CommonTypes.xsd" />
  <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/EnumTypes_1.0" schemaLocation="common/EnumTypes.xsd" />
  <xsd:element name="RegisterNewClient">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="authentication" type="ct:TokenType" maxOccurs="1" minOccurs="0" />
        <xsd:element name="clientDetails" type="this:ClientGroupNewClient" maxOccurs="1" minOccurs="1" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="ClientGroupNewClient">
    <xsd:annotation>
      <xsd:documentation>Details for a new client in the client group.</xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element minOccurs="1" maxOccurs="1" name="clientName" type="ct:AlphaNumeric254Type" />
      <xsd:element minOccurs="0" maxOccurs="1" name="description" type="ct:AlphaNumeric254Type" />
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>