//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Workflow.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoProcessFieldChangeRuleValidation : ZValidation
	{
		protected AutoProcessFieldChangeRuleValidation(AutoProcessFieldChangeRule Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoProcessFieldChangeRuleValidation); }
		}

		/// <summary>
		/// Add more validation to the ProcessFieldChangeRule's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoProcessFieldChangeRuleValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The ProcessFieldChangeRule's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoProcessFieldChangeRuleValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region PFR_Description

		public void ValidatePFR_Description()
		{
			ZValidationInternals.Validate(Parent.PFR_DescriptionInfo, GetPFR_DescriptionValidationInvoker());
		}

		RunValidationInvoker GetPFR_DescriptionValidationInvoker()
		{
			return delegate
			{
				CheckPFR_Description();
			};
		}

		protected virtual void CheckPFR_Description()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region PFR_GroupName

		public void ValidatePFR_GroupName()
		{
			ZValidationInternals.Validate(Parent.PFR_GroupNameInfo, GetPFR_GroupNameValidationInvoker());
		}

		RunValidationInvoker GetPFR_GroupNameValidationInvoker()
		{
			return delegate
			{
				CheckPFR_GroupName();
			};
		}

		protected virtual void CheckPFR_GroupName()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region PFR_IsActive

		public void ValidatePFR_IsActive()
		{
			ZValidationInternals.Validate(Parent.PFR_IsActiveInfo, GetPFR_IsActiveValidationInvoker());
		}

		RunValidationInvoker GetPFR_IsActiveValidationInvoker()
		{
			return delegate
			{
				CheckPFR_IsActive();
			};
		}

		protected virtual void CheckPFR_IsActive()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region PFR_ProcessType

		public void ValidatePFR_ProcessType()
		{
			ZValidationInternals.Validate(Parent.PFR_ProcessTypeInfo, GetPFR_ProcessTypeValidationInvoker());
		}

		RunValidationInvoker GetPFR_ProcessTypeValidationInvoker()
		{
			return delegate
			{
				CheckPFR_ProcessTypeIsWesternEuropean();
				CheckPFR_ProcessType();
			};
		}

		protected virtual void CheckPFR_ProcessTypeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.PFR_ProcessTypeInfo);
		}

		protected virtual void CheckPFR_ProcessType()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region PFR_Reference

		public void ValidatePFR_Reference()
		{
			ZValidationInternals.Validate(Parent.PFR_ReferenceInfo, GetPFR_ReferenceValidationInvoker());
		}

		RunValidationInvoker GetPFR_ReferenceValidationInvoker()
		{
			return delegate
			{
				CheckPFR_ReferenceIsWesternEuropean();
				CheckPFR_Reference();
			};
		}

		protected virtual void CheckPFR_ReferenceIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.PFR_ReferenceInfo);
		}

		protected virtual void CheckPFR_Reference()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region PFR_SE_NKEvent

		public void ValidatePFR_SE_NKEvent()
		{
			ZValidationInternals.Validate(Parent.PFR_SE_NKEventInfo, GetPFR_SE_NKEventValidationInvoker());
		}

		RunValidationInvoker GetPFR_SE_NKEventValidationInvoker()
		{
			return delegate
			{
				CheckPFR_SE_NKEventIsWesternEuropean();
				CheckPFR_SE_NKEvent();
			};
		}

		protected virtual void CheckPFR_SE_NKEventIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.PFR_SE_NKEventInfo);
		}

		protected virtual void CheckPFR_SE_NKEvent()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidatePFR_Description();
				ValidatePFR_GroupName();
				ValidatePFR_IsActive();
				ValidatePFR_ProcessType();
				ValidatePFR_Reference();
				ValidatePFR_SE_NKEvent();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoProcessFieldChangeRule Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
