<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Freight.Forwarding.Registry</RootNamespace>
    <AssemblyName>Enterprise.Freight.Forwarding.Registry</AssemblyName>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Forwarding\CargoIMPPhase2MSUEventCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CargoIMPPhase2MSUEventCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Forwarding\CargoIMPPhase2ServiceProviderList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CargoIMPPhase2ServiceProviderList.xml</DependentUpon>
    </Compile>
    <Compile Update="Forwarding\CargoIMPSentMessageVersionsList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CargoIMPSentMessageVersionsList.xml</DependentUpon>
    </Compile>
    <Compile Update="Forwarding\DpsStatusUpdateSetting\DpsStatusUpdateOptions.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DpsStatusUpdateOptions.xml</DependentUpon>
    </Compile>
    <Compile Update="Forwarding\HouseBillsNumberValidation\AutoHouseBillsNumberValidation.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoHouseBillsNumberValidation.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Forwarding\CargoIMPPhase2MSUEventCodeList.xml">
      <CustomToolNamespace>Enterprise.Freight.Forwarding.Registry</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CargoIMPPhase2MSUEventCodeList.cs</LastGenOutput>
    </None>
    <None Update="Forwarding\CargoIMPPhase2ServiceProviderList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CargoIMPPhase2ServiceProviderList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.Forwarding.Registry</CustomToolNamespace>
    </None>
    <None Update="Forwarding\CargoIMPSentMessageVersionsList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CargoIMPSentMessageVersionsList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.Forwarding.Registry</CustomToolNamespace>
    </None>
    <None Update="Forwarding\DpsStatusUpdateSetting\DpsStatusUpdateOptions.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DpsStatusUpdateOptions.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.Forwarding.Registry</CustomToolNamespace>
    </None>
    <None Update="Forwarding\HouseBillsNumberValidation\AutoHouseBillsNumberValidation.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoHouseBillsNumberValidation.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Freight.Forwarding.Registry</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>