//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from SpecificationStandardList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.AE.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class SpecificationStandardList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string GCCStandard = "1";
			public const string NonGCCStandard = "2";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString GCCStandard { get { return ResString.GetMultilingualString("SpecificationStandardList|GCCStandard", "GCC Standard"); } }
			public static MultilingualString NonGCCStandard { get { return ResString.GetMultilingualString("SpecificationStandardList|NonGCCStandard", "Non GCC Standard"); } }
		}

		public SpecificationStandardList()
		{
			AddPair(Codes.GCCStandard, Descriptions.GCCStandard);
			AddPair(Codes.NonGCCStandard, Descriptions.NonGCCStandard);
		}
	}
}
