<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 94000 and 94005
	Export all entries which are valid at the requested queryDateStart or later.
 -->
    <xsd:include schemaLocation="PreferenceCodeData.xsd"/>

	<xsd:redefine schemaLocation="../../BaseDataExport.xsd">
		<xsd:complexType name="parameters">
	        <xsd:complexContent>
	            <xsd:extension base="at:parameters">
	                <xsd:sequence>
	                    <xsd:element ref="at:queryDateStart" minOccurs="0" maxOccurs="1"/>
	                    <xsd:element ref="at:queryDateEnd" minOccurs="0" maxOccurs="1"/>
	                </xsd:sequence>
	            </xsd:extension>
	        </xsd:complexContent>
	    </xsd:complexType>
    	<!-- redefinition of items -->
        <xsd:complexType name="items">
            <xsd:complexContent>
                <xsd:extension base="at:items">
                    <xsd:choice minOccurs="0" maxOccurs="unbounded">
                        <xsd:element ref="at:preferenceCode"/>
                    </xsd:choice>
                </xsd:extension>
            </xsd:complexContent>
     	</xsd:complexType>
	</xsd:redefine>

</xsd:schema>
