// ----------------------------------------------------------------------
// <auto-generated>
//      This code is auto-generated by the awesome NonPersistentBusinessObjectGenerator(tm)
//      Any changes to this file will be lost when the generator is next run.
// </auto-generated>
// ----------------------------------------------------------------------
using System;
using System.ComponentModel;
using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.Environment;

namespace Enterprise.Customs.FR.Business.OperationalActions
{
	
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoSendCancellationMessageDataObject : NonPersistentBusinessObject
	{
		#region Schema
		public class Schema
		{
			public const string InvalidationMotivation = "InvalidationMotivation";
			public const int InvalidationMotivationMaxLength = 5;
			public const string InvalidationReason = "InvalidationReason";
			public const int InvalidationReasonMaxLength = 512;
		}
		#endregion
		protected AutoSendCancellationMessageDataObject()
		{
		}
		protected AutoSendCancellationMessageDataObject(BusinessObjectFactory factory) : base(factory)
		{
		}
		#region InvalidationMotivation
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Customs.FR.Business.OperationalActions.SendCancellationMessageDataObject|InvalidationMotivation", Caption="Motivation")]
		[MaxLength(Schema.InvalidationMotivationMaxLength)]
		public virtual ZString InvalidationMotivation
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return invalidationMotivation;
			}
			set
			{
				CheckMaximumLength(InvalidationMotivationInfo, value);
				SetNonPersistentPropertyValue(InvalidationMotivationInfo, ref invalidationMotivation, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateInvalidationMotivation();
				}
			}
		}
		public virtual ZPropertyInfo InvalidationMotivationInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.InvalidationMotivation);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString invalidationMotivation;
		#endregion
		#region InvalidationReason
		[CargoWiseOne.ResourceStrings.ResourceStringData("NPBO:Enterprise.Customs.FR.Business.OperationalActions.SendCancellationMessageDataObject|InvalidationReason", Caption="Reason")]
		[MaxLength(Schema.InvalidationReasonMaxLength)]
		public virtual ZString InvalidationReason
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return invalidationReason;
			}
			set
			{
				CheckMaximumLength(InvalidationReasonInfo, value);
				SetNonPersistentPropertyValue(InvalidationReasonInfo, ref invalidationReason, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					Validation.ValidateInvalidationReason();
				}
			}
		}
		public virtual ZPropertyInfo InvalidationReasonInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.InvalidationReason);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZString invalidationReason;
		#endregion
		#region Validation
		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore();
		}
		public SendCancellationMessageDataObjectValidation Validation
		{
			get
			{
				return GetNewValidation();
			}
		}
		protected virtual SendCancellationMessageDataObjectValidation GetNewValidation()
		{
			return new SendCancellationMessageDataObjectValidation(this);
		}
		#endregion
	}
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoSendCancellationMessageDataObjectValidation : ZValidation
	{
		public AutoSendCancellationMessageDataObjectValidation(AutoSendCancellationMessageDataObject parent) : base(parent)
		{
			this.parent = parent;
			this.ZValidationInternals = this;
			this.ParentListInternals = parent;
		}
		public void Add(AutoSendCancellationMessageDataObjectValidation validation)
		{
			ZValidationInternals.Add(validation);
		}
		public void Remove(AutoSendCancellationMessageDataObjectValidation validation)
		{
			ZValidationInternals.Remove(validation);
		}
		#region ValidateAll
		public override void ValidateAll()
		{
			IDisposable suspender = ParentListInternals.SuspendListChanged();
			try
			{
				ValidateAllCore();
			}
			finally
			{
				suspender.Dispose();
			}
		}
		protected virtual void ValidateAllCore()
		{
			ValidateInvalidationMotivation();
			ValidateInvalidationReason();
		}
		#endregion
		#region InvalidationMotivation
		public void ValidateInvalidationMotivation()
		{
			ZValidationInternals.Validate(Parent.InvalidationMotivationInfo, new RunValidationInvoker(this.InvalidationMotivationValidationInvoker));
		}
		private void InvalidationMotivationValidationInvoker()
		{
			CheckInvalidationMotivationIsWesternEuropean();
			CheckInvalidationMotivation();
		}
		protected virtual void CheckInvalidationMotivationIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.InvalidationMotivationInfo);
		}
		protected virtual void CheckInvalidationMotivation()
		{
		}
		#endregion
		#region InvalidationReason
		public void ValidateInvalidationReason()
		{
			ZValidationInternals.Validate(Parent.InvalidationReasonInfo, new RunValidationInvoker(this.InvalidationReasonValidationInvoker));
		}
		private void InvalidationReasonValidationInvoker()
		{
			CheckInvalidationReasonIsWesternEuropean();
			CheckInvalidationReason();
		}
		protected virtual void CheckInvalidationReasonIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.InvalidationReasonInfo);
		}
		protected virtual void CheckInvalidationReason()
		{
		}
		#endregion
		#region Implementation
		public override Type AutoValidationType
		{
			get
			{
				return typeof(AutoSendCancellationMessageDataObjectValidation);
			}
		}
		public AutoSendCancellationMessageDataObject Parent
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return parent;
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private AutoSendCancellationMessageDataObject parent;
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private IValidationInternals ZValidationInternals;
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ISingleElementListInternal ParentListInternals;
		#endregion
	}
}
