<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Enterprise.WebCFS.Business.Test</AssemblyName>
    <RootNamespace>Enterprise.WebCFS.Business.Testing</RootNamespace>
    <OutputPath>..\..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.EntityFramework.Testing">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.Testing.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Integration">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings.Cache">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ResourceStrings.Cache.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.CarbonEmissions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Common.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Common.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Types">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Types.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\..\..\Bin\Resources.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebCFS.Business\WebCFS.Business.csproj" />
  </ItemGroup>
</Project>