// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveRunnerV2NonTransactionedTest.TestWhenHARRunnerV2HasException_ThenRollbackAllTransactionChanges")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveRunnerV2NonTransactionedTest.cs:18,96
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveRunnerV2NonTransactionedTest.ArrangeShipmentToBeArchived(Enterprise.Freight.Forwarding.Business.ForwardingShipment)")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveRunnerV2NonTransactionedTest.cs:61,23
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveServiceTaskSnapshotTest.TestHARRunnerV2TransactionFailure_ShouldRollbackAllChanges")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveServiceTaskTest.cs:2443,24
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveServiceTaskSnapshotTest.HVLVDataArchiveServiceTaskWithTestingRunner.RunTask(System.Threading.CancellationToken)")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveServiceTaskTest.cs:2466,83
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveServiceTaskTest.TestDeleteArchivedHVLVItem_NoTrigger")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveServiceTaskTest.cs:259,21
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVDataArchiveServiceTaskTest.TestWhenHARRunnerV2_ThenValidResult")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVDataArchiveServiceTaskTest.cs:352,69
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVBookingHeaderCleanupServiceTaskTest.TestMultipleBatchDeletion")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVBookingHeaderCleanupServiceTaskTest.cs:26,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVBookingHeaderCleanupServiceTaskTest.TestLogging")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVBookingHeaderCleanupServiceTaskTest.cs:57,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVBookingHeaderCleanupServiceTaskTest.TestOnlyDeletesHeadersWithNoConsignments")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVBookingHeaderCleanupServiceTaskTest.cs:101,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVBookingHeaderCleanupServiceTaskTest.TestDifferentTimesOfEdit")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVBookingHeaderCleanupServiceTaskTest.cs:149,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVOriginLoadListProcessorServiceTaskTest.TestServiceTaskHandlesClusterKeyClashes")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVOriginLoadListProcessorServiceTaskTest.cs:582,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.eTail.ServiceTasks.Testing.HVLVOriginLoadListProcessorServiceTaskTest.TestServiceTaskHandlesClusterKeyClashes")] // Enterprise/Product/Operations/eTail/ServiceTasks.Testing/HVLVOriginLoadListProcessorServiceTaskTest.cs:610,3
