<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.EUReferenceData.Tests</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.EUReferenceData.Tests</AssemblyName>
    <Configurations>Debug</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <OutputPath>..\..\..\bin\UniversalXMLProducers</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.UniversalXMLProducers.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.UniversalXMLProducers.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AES\TestFiles\**\*.xml" />
    <EmbeddedResource Include="AES\TestFiles\**\*.zip" />
    <EmbeddedResource Include="CCI\TestFiles\**\*.xml" />
    <EmbeddedResource Include="CCI\TestFiles\**\*.zip" />
    <EmbeddedResource Include="CUSNumbers\TestFiles\**\*.html" />
    <EmbeddedResource Include="CUSNumbers\TestFiles\**\*.xml" />
    <EmbeddedResource Include="CUSNumbers\TestFiles\**\*.zip" />
    <EmbeddedResource Include="CustomsMeursing\TestFiles\**\*.json" />
    <EmbeddedResource Include="CustomsMeursing\TestFiles\**\*.xslx" />
    <EmbeddedResource Include="CustomsMeursing\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\AdditionalInformationCodeSubset\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\AdditionalInformationCodeSubset\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\AdditionalSupplyChainActorRoleCode\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\AdditionalSupplyChainActorRoleCode\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\DocumentTypeCommon\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\DocumentTypeCommon\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\HRCMScreeningMethod\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\HRCMScreeningMethod\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\ICS2FunctionalErrorCodes\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\ICS2FunctionalErrorCodes\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\KindOfPackages\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\KindOfPackages\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\MethodOfPayment\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\MethodOfPayment\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\TypeOfGoods\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\TypeOfGoods\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\TypeOfMeansOfTransport\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\TypeOfMeansOfTransport\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\StateSubset\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\StateSubset\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\CountryCodeICS2MS\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\CountryCodeICS2MS\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\UnLocodeExtended\TestFiles\**\*.xml" />
    <EmbeddedResource Include="ICS2\UnLocodeExtended\TestFiles\**\*.zip" />
    <EmbeddedResource Include="ICS2\Translation\TestFiles\*.json" />
    <EmbeddedResource Include="NCTSCodeLists\TestFiles\**\*.xml" />
    <EmbeddedResource Include="NCTSCodeLists\TestFiles\**\*.zip" />
    <EmbeddedResource Include="NCTSTradeGroups\TestFiles\**\*.xml" />
    <EmbeddedResource Include="NCTSTradeGroups\TestFiles\**\*.zip" />
    <EmbeddedResource Include="OfficeCodes\TestFiles\**\*.html" />
    <EmbeddedResource Include="OfficeCodes\TestFiles\**\*.txt" />
    <EmbeddedResource Include="OfficeCodes\TestFiles\**\*.xml" />
    <EmbeddedResource Include="OfficeCodes\TestFiles\**\*.zip" />
    <EmbeddedResource Include="RefCusCodeTypes\TestFiles\**\*.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EUReferenceData.Business\EUReferenceData.Business.csproj" />
    <ProjectReference Include="..\EUReferenceData.CmdLine\EUReferenceData.CmdLine.csproj" />
    <ProjectReference Include="..\EUReferenceData.Services\EUReferenceData.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CustomsMeursing\TestFiles\Additional agricultural duties - Meursing.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="CustomsMeursing\TestFiles\Geographical areas composition.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="ICS2\MethodOfPayment\TestFiles\Input\RD_ICS2_TransportChargesMethodOfPayment.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

  </ItemGroup>

  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>