//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.MasterFiles.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoStmMenuMenuPivotLookups : ZLookups
	{
		protected AutoStmMenuMenuPivotLookups(AutoStmMenuMenuPivot Parent) : base(Parent)
		{
		}

		#region Inwards

		public virtual StmMenuItemCollection Inwards
		{
			get { return new StmMenuItemCollection(Factory); }
		}

		#endregion

		#region Outwards

		public virtual StmMenuItemCollection Outwards
		{
			get { return new StmMenuItemCollection(Factory); }
		}

		#endregion
	}
}
