<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>$(NoWarn);CS8002</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="Moq" />
    <PackageReference Include="WTG.PlaywrightTesting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Blazor.Common\CargoWise.Blazor.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWiseNext.Infrastructure.Installations" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="CargoWise.Async" />
    <Reference Include="CargoWiseNext.Infrastructure.Authentication" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.ComponentModel" />
  </ItemGroup>
</Project>