<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Moq" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounting.Module\Enterprise.Accounting.Module.csproj" />
    <ProjectReference Include="..\GUI\Enterprise.Accounting.GUI.csproj" />
  </ItemGroup>
</Project>