// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.Accounting.Module.Testing.AccountingFilterStripCreatorTest.DummyAccountingFilterStripHolderWithConfigOverrideNames.Enterprise#Accounting#Integration#IAccountingFilterStripHolder#AccountingFilterStripConfiguration")] // Enterprise/Product/Operations/Accounting/Accounting.Module.Testing/AccountingFilterStrip/AccountingFilterStripCreatorTest.cs:599,83
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.Accounting.Module.Testing.AccountingFilterStripCreatorTest.DummyAccountingFilterStripHolderWithConfigOverrideNames.Enterprise#Accounting#Integration#IAccountingFilterStripHolder#AccountingFilterStripConfiguration")] // Enterprise/Product/Operations/Accounting/Accounting.Module.Testing/AccountingFilterStrip/AccountingFilterStripCreatorTest.cs:600,80
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.Accounting.Module.Testing.AccountingFilterStripCreatorTest.DummyAccountingFilterStripHolderWithConfigOverrideNames.Enterprise#Accounting#Integration#IAccountingFilterStripHolder#AccountingFilterStripConfiguration")] // Enterprise/Product/Operations/Accounting/Accounting.Module.Testing/AccountingFilterStrip/AccountingFilterStripCreatorTest.cs:599,83
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.Accounting.Module.Testing.AccountingFilterStripCreatorTest.DummyAccountingFilterStripHolderWithConfigOverrideNames.Enterprise#Accounting#Integration#IAccountingFilterStripHolder#AccountingFilterStripConfiguration")] // Enterprise/Product/Operations/Accounting/Accounting.Module.Testing/AccountingFilterStrip/AccountingFilterStripCreatorTest.cs:600,80
