<Project>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.GUI" />
    <Reference Include="Enterprise.Customs.EU.Module" />
    <Reference Include="Enterprise.Customs.GUI" />
    <Reference Include="Enterprise.Customs.Module" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Module" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.SE.Business.csproj" />
  </ItemGroup>
</Project>