<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://cfia-airs.inspection.gc.ca">
  <xs:element name="ValidateTransactionResult">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="999" name="CommodityGroup">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Commodity" minOccurs="0" maxOccurs="999"><!--maxOccurs="999" was removed in latest xsd but it seems that that is not correct-->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Error" minOccurs="0">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="250" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="commodityId" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:minLength value="1" />
                        <xs:maxLength value="50" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="commodityGroupId" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:minLength value="1" />
                  <xs:maxLength value="50" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="errorCount" use="required" type="xs:integer" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="errorCount" use="required" type="xs:integer" />
    </xs:complexType>
  </xs:element>
</xs:schema>