<xs:schema targetNamespace="http://www.cargowise.com/Schemas/Universal" version="1.0" xmlns:cw="http://www.cargowise.com/Schemas/Universal" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="UniversalCommonSchema.xsd" />
	<xs:element name="NativeContainerSetSchema">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RefContainer" type="cw:RefContainer" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RefContainer">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ContainerType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CubicCapacity" minOccurs="0" type="xs:decimal" />
			<xs:element name="Description" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="35" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FreightRateClass" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GrossWeight" minOccurs="0" type="xs:decimal" />
			<xs:element name="HandlingRateClass" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="HasTynes" minOccurs="0" type="xs:boolean" />
			<xs:element name="HasVents" minOccurs="0" type="xs:boolean" />
			<xs:element name="Height" minOccurs="0" type="xs:decimal" />
			<xs:element name="IATARateClass" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
			<xs:element name="IsHighCube" minOccurs="0" type="xs:boolean" />
			<xs:element name="IsIso" minOccurs="0" type="xs:boolean" />
			<xs:element name="ISOType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Length" minOccurs="0" type="xs:decimal" />
			<xs:element name="PK" type="xs:string" />
			<xs:element name="ShippingMode" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="StorageClass" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="TareWeight" minOccurs="0" type="xs:decimal" />
			<xs:element name="TEU" minOccurs="0" type="xs:decimal" />
			<xs:element name="USContainerCode" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="2" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Width" minOccurs="0" type="xs:decimal" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="RefEquipment">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="TwoWayInfo" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AddCheckBox1" minOccurs="0" type="xs:boolean" />
			<xs:element name="AddFlag1" minOccurs="0" type="xs:boolean" />
			<xs:element name="AddReference1" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="AddReference2" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CapacityInTEU" minOccurs="0" type="xs:short" />
			<xs:element name="CubicCapacity" minOccurs="0" type="xs:decimal" />
			<xs:element name="CubicUnit" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="2" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Description" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="35" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DisposalDate" minOccurs="0" type="xs:dateTime" />
			<xs:element name="EquipmentGroup" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="EquipmentType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GateTransponder1" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GateTransponder2" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GateTransponder3" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GeoProviderID" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="64" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GeoProviderType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
			<xs:element name="IsVehicle" minOccurs="0" type="xs:boolean" />
			<xs:element name="PackCapacity" minOccurs="0" type="xs:int" />
			<xs:element name="PackType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
			<xs:element name="PurchaseDate" minOccurs="0" type="xs:dateTime" />
			<xs:element name="RegExpriy" minOccurs="0" type="xs:dateTime" />
			<xs:element name="Registration" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="RegState" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ShortCode" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="TareWeight" minOccurs="0" type="xs:decimal" />
			<xs:element name="TollPass" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="15" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VIN" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="WeightCapacity" minOccurs="0" type="xs:decimal" />
			<xs:element name="WeightUnit" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="2" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GlbBranch" type="cw:GlbBranch" />
			<xs:element name="GlbCompany" type="cw:GlbCompany" />
			<xs:element name="GlbStaff" type="cw:GlbStaff" />
			<xs:element name="PreferredDriver" type="cw:PreferredDriver" />
			<xs:element name="RoadContainerType" type="cw:RoadContainerType" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="RefContainerStock">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="ContainerNum" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="OwnerType" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
			<xs:element name="Owner" type="cw:Owner" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="GlbBranch">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="GlbCompany">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="GlbStaff">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="LoginName" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="35" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="PreferredDriver">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="LoginName" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="35" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="RoadContainerType">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
	<xs:complexType name="Owner">
		<xs:sequence>
			<xs:element name="Key" type="cw:TableKey" />
			<xs:element name="Code" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PK" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="Action" type="cw:Action" />
	</xs:complexType>
</xs:schema>