CREATE TABLE AutoSchema
(
	AS_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_AutoSchema_AS_PK DEFAULT (NEWID()),
	AS_SchemaName VARCHAR(200) NOT NULL,
	AS_Schema XML NOT NULL,
	AS_TableCode VARCHAR(3) NOT NULL

	CONSTRAINT [PK_AutoSchema_AS_PK] PRIMARY KEY NONCLUSTERED (AS_PK)
)
GO
ALTER TABLE AutoSchema ADD CONSTRAINT [CK_AutoSchema_AS_SchemaName] CHECK (AS_SchemaName <> '')
GO
ALTER TABLE AutoSchema ADD CONSTRAINT [CK_AutoSchema_AS_TableCode] CHECK (AS_TableCode <> '')
