CREATE TABLE RefCurrency (
	RX_PK UNIQUEIDENTIFIER NOT NULL,
	RX_Code CHAR(3) NOT NULL CONSTRAINT DF_RX_Code DEFAULT (''),
	RX_IsActive BIT NOT NULL CONSTRAINT DF_RX_IsActive DEFAULT (1),
	RX_Symbol NVARCHAR(3) NOT NULL CONSTRAINT DF_RX_Symbol DEFAULT (''),
	RX_Desc NVARCHAR(35) NOT NULL CONSTRAINT DF_RX_Desc DEFAULT (''),
	RX_UnitName VARCHAR(20) NOT NULL CONSTRAINT DF_RX_UnitName DEFAULT (''),
	RX_SubUnitName VARCHAR(20) NOT NULL CONSTRAINT DF_RX_SubUnitName DEFAULT (''),
	RX_SubUnitRatio INT NOT NULL CONSTRAINT DF_RX_SubUnitRatio DEFAULT ((100)),
	RX_ISOSubUnitRatio INT NOT NULL CONSTRAINT DF_RX_ISOSubUnitRatio DEFAULT 0,
 CONSTRAINT PK_UX__RX_PK PRIMARY KEY CLUSTERED (RX_PK ASC)
)
GO
