CREATE TABLE RefCusTaxOrFee (
	ZZF_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RefCusTaxOrFee DEFAULT (NEWID()),
	ZZF_Code VARCHAR(4) NOT NULL,
	ZZF_Description NVARCHAR(500) NOT NULL,
	ZZF_Value DECIMAL(19,8) NOT NULL CONSTRAINT DF_RefCusTaxOrFee_ZZF_Value DEFAULT (0),
	ZZF_StartDate DATETIME NOT NULL CONSTRAINT DF_RefCusTaxOrFee_ZZF_StartDate DEFAULT GetUtcDate(),
	ZZF_EndDate DATETIME NOT NULL CONSTRAINT DF_RefCusTaxOrFee_ZZF_EndDate DEFAULT '2079-06-06 23:59',
	ZZF_ZZZ_NKDataGrouping VARCHAR(3) NOT NULL,
	ZZF_Minimum DECIMAL(19,8) NOT NULL CONSTRAINT DF_RefCusTaxOrFee_ZZF_Minimum DEFAULT (0),
	ZZF_Maximum DECIMAL(19,8) NOT NULL CONSTRAINT DF_RefCusTaxOrFee_Maximum DEFAULT (0),
	ZZF_Threshold DECIMAL(19,8) NOT NULL CONSTRAINT DF_RefCusTaxOrFee_Threshold DEFAULT (0),
	ZZF_ZX0_NKTaxOrFeeType VARCHAR(3) NOT NULL CONSTRAINT DF_RefCusTaxOrFee_ZZF_ZX0_NKTaxOrFeeType DEFAULT 'OTH',
	CONSTRAINT PK_RefCusTaxOrFee PRIMARY KEY CLUSTERED (ZZF_PK ASC),
	CONSTRAINT CK_RefCusTaxOrFee_ZZF_StartDate_ZZF_EndDate CHECK (ZZF_StartDate<=ZZF_EndDate),
)
GO
