CREATE TABLE [dbo].[RefTimeZoneSet](
	[R3_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefTimeZoneSet_R3_PK] DEFAULT (NEWID()),
	[R3_TimeZoneSetName] VARCHAR(35) NOT NULL CONSTRAINT [DF_RefTimeZoneSet_R3_TimeZoneSetName] DEFAULT (''),
	[R3_IsActive] BIT NOT NULL CONSTRAINT [DF_RefTimeZoneSet_R3_IsActive] DEFAULT(1),
	CONSTRAINT PK_RefTimeZoneSet_R3_PK PRIMARY KEY CLUSTERED (R3_PK ASC),
)
GO
