CREATE TABLE [RefUNLOCORelatedPort](
	[RLR_PK] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT [DF_RefUNLOCORelatedPort_RLR_PK] DEFAULT (NEWID()),
	[RLR_GroupNumber] [SMALLINT] NOT NULL,
	[RLR_RL_NKRelatedPort] [VARCHAR](5) NOT NULL CONSTRAINT [DF_RefUNLOCORelatedPort_RLR_RL_NKRelatedPort]  DEFAULT (''),
	CONSTRAINT [PK_RefUNLOCORelatedPort] PRIMARY KEY NONCLUSTERED ([RLR_PK]),
	CONSTRAINT RefUNLOCORelatedPort_RLR_RL_NKRelatedPort CHECK  ((LEN([RLR_RL_NKRelatedPort])=(5)))
)
GO
