CREATE TABLE [UNDGAttribute] (
   [DA_PK] UNIQUEIDENTIFIER NOT NULL,
   [DA_Language] VARCHAR(3) NOT NULL CONSTRAINT DF_UNDGAttribute_DA_Language DEFAULT '',
   [DA_Type] VARCHAR(3) NOT NULL CONSTRAINT DF_UNDGAttribute_DA_Type DEFAULT '',
   [DA_Index] VARCHAR(6) NOT NULL CONSTRAINT DF_UNDGAttribute_DA_Index DEFAULT '',
   [DA_Descriptor] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_UNDGAttribute_DA_Descriptor DEFAULT '',
   [DA_DG] UNIQUEIDENTIFIER NOT NULL,
   CONSTRAINT [PK_UNDGAttribute] PRIMARY KEY NONCLUSTERED  ([DA_PK] ASC),
   CONSTRAINT [FK_UNDGAttribute_UNDGSubstance] FOREIGN KEY(DA_DG) REFERENCES UNDGSubstance (DG_PK) ON DELETE CASCADE,
)
GO
CREATE NONCLUSTERED INDEX [IX_UNDGAttribute_DA_DG] ON [UNDGAttribute] (DA_DG)
