<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AssemblyName>Enterprise.DocumentScanning.GUI</AssemblyName>
    <RootNamespace>Enterprise.DocumentScanning.GUI</RootNamespace>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <UseLegacyRsa>false</UseLegacyRsa>
    <CWUsesDesignRef>true</CWUsesDesignRef>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Launch\**" />
    <Compile Remove="Scanning\**" />
    <EmbeddedResource Remove="Launch\**" />
    <EmbeddedResource Remove="Scanning\**" />
    <None Remove="Launch\**" />
    <None Remove="Scanning\**" />
    <Compile Remove="MouseMessageFilter.cs" />
    <Compile Remove="OCR\CursorConstrainingForm.cs" />
    <Compile Remove="OCR\CursorConstrainingForm.Designer.cs" />
    <Compile Remove="RulerPanel.cs" />
    <Compile Remove="RulerPanel.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Winzor\BArchitecture.GUI\WinzorFramework.csproj" />
    <ProjectReference Include="..\..\..\..\Architecture\GUI\Enterprise.ZArchitecture.GUI\Enterprise.ZArchitecture.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.DocumentScanning.Business" />
    <Reference Include="CargoWise.Interop" />
  </ItemGroup>
</Project>