<?xml version="1.0" encoding="UTF-8"?>
<!-- Prepared by WWA EI Support -->
	<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
		<xs:element name="FileBL">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="FileBLEnvelope">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="SenderID" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="50" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="ReceiverID" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="6" />
											<xs:maxLength value="100" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="Password" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:minLength value="6" />
											<xs:maxLength value="100" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="Type" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="40" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="Version" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="8" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="EnvelopeID" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="40" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="FileBLDetails">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="FileNumber" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="25" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="TypeOfMove" nillable="false">
									<!-- Date: Dec 12,2014:Based on feedback received from Transglory, changed maxLength value= 1 from maxLength value=2 -->
									<xs:annotation>
										<xs:documentation>L=LCL, F=FCL</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="1" />
											<xs:enumeration value="L" />
											<xs:enumeration value="F" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="Coload" nillable="false">
									<!-- Date: Dec 12,2014:Based on feedback received from Transglory, changed maxLength value= 1 from maxLength value=2 -->
									<xs:annotation>
										<xs:documentation>Y=Yes, N=No</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="1" />
											<xs:enumeration value="Y" />
											<xs:enumeration value="N" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="Mode" nillable="false">
									<xs:annotation>
										<xs:documentation>O=Ocean, A=Air</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="1" />
											<xs:enumeration value="O" />
											<xs:enumeration value="A" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="MasterBLNumber" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="30" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the maxLength value to 30 from 16 -->
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="SenderEmail" nillable="false">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="50" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="MasterBarcodeNumber" nillable="true" minOccurs="0">
									<!-- New Field -->
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:maxLength value="40" />
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="SailingDetails">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="ImoNumber" minOccurs="0">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="7" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="SCAC" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="4" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="VesselName" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Voyage" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="10" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="EtdOrigin" type="xs:date" nillable="false" />
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtsLoadPort" type="xs:date" nillable="false" />
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtaTransshipmentPort1" type="xs:date" nillable="true" minOccurs="0" />  <!-- Added New fields for Transshipment Ports -->
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtaTransshipmentPort2" type="xs:date" nillable="true" minOccurs="0" />  <!-- Added New fields for Transshipment Ports -->
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtaTransshipmentPort3" type="xs:date" nillable="true" minOccurs="0" />  <!-- Added New fields for Transshipment Ports -->
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtaDischarge" type="xs:date" nillable="false" />
											<!-- Changed Data Type from String to Date -->
											<xs:element name="EtaFinalDestination" type="xs:date" nillable="false" />
											<!-- Changed Data Type from String to Date -->
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="RoutingDetails">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="OriginCode">
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="OriginName">
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											<xs:element name="LoadCode">
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="LoadName">
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											<xs:element name="TransshipmentPort1" nillable="true" minOccurs="0" >   <!-- Added New fields for Transshipment Ports -->  
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="TransshipmentPort1Name" nillable="true" minOccurs="0" >  <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											<xs:element name="TransshipmentPort2" nillable="true" minOccurs="0" >   <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="TransshipmentPort2Name" nillable="true" minOccurs="0" >   <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											
											<xs:element name="TransshipmentPort3" nillable="true" minOccurs="0" >   <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="TransshipmentPort3Name" nillable="true" minOccurs="0" >  <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											<xs:element name="DischargeCode">
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="DischargeName">
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
											<xs:element name="DestinationCode">
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="DestinationName">
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="ContainerDetails" maxOccurs="unbounded">
									<!-- Restructured Tags, Added Support for Mutliple containers -->
									<xs:complexType>
										<xs:sequence>
											<xs:element name="ContainerNumber" nillable="false">
												<!-- Date: Dec 12,2014:Based on feedback received from Transglory, made container number,size and type mandatory data -->
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="11" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="SealNumber" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="20" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="ContainerSize" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="3" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="ContainerType" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="45" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Weight" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:decimal">
														<xs:totalDigits value="10" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Volume" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:decimal">
														<xs:totalDigits value="10" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="UOM" nillable="false">
												<xs:annotation>
													<xs:documentation>"E"=English; "M"=Metric</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="1" />
														<xs:minLength value="1" />
														<xs:enumeration value="E" />
														<xs:enumeration value="M" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="BillOfLadingDetails" maxOccurs="unbounded"> <!--Date : Dec 18,2014 : We have taken BillOfLadingDetails out of ContainerDetails for better structuring of schema.-->
									<xs:complexType>
										<xs:sequence>
											<xs:element name="BillOfLadingNumber" nillable="false">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="20" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="CustomerAlias" nillable="true" minOccurs="0"> <!-- We have made this field optional -->
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="0" />
														<xs:maxLength value="25" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Type">
												<xs:annotation>
													<xs:documentation>L=Line BL, H=House BL</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="1" />
														<xs:maxLength value="1" />
														<xs:enumeration value="L" />
														<xs:enumeration value="H" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="ReleaseType">
												<xs:annotation>
													<xs:documentation>E=Express release, O=Originals required</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:minLength value="1" />
														<xs:maxLength value="1" />
														<xs:enumeration value="E" />
														<xs:enumeration value="O" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="FPI" nillable="false"> <!-- FPI Freight Payment Indicator added on 12 Dec 18--> 
											<xs:annotation>
												<xs:documentation>"P" = Prepaid "C" = Collect</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="1"/>
													<xs:enumeration value="P"/>
													<xs:enumeration value="C"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
											<xs:element name="NumberOfOriginals">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="2" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="Terms" minOccurs="0">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="10" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<xs:element name="BLReleasePoint">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="20" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
                      <xs:element name="HBLDocumentURL" type="xs:anyURI" nillable="true" minOccurs="0"/>
                      <!-- New Field Added-->
                      <xs:element name="DocumentationDetails" nillable="true" minOccurs="0" >
                        <!-- Date: April 2,2019:Based on feedback received during WWA IT Meet 2019 added Documentation Details -->
                        <xs:complexType>
                          <xs:sequence>
                            <xs:element name="DocumentType" type="xs:string" nillable="true" minOccurs="0"/>
                            <xs:element name="ContentType" type="xs:string" nillable="true" minOccurs="0"/>
                            <xs:element name="ImageURL" type="xs:anyURI" nillable="true" minOccurs="0"/>
                          </xs:sequence>
                        </xs:complexType>
                      </xs:element>
											<xs:element name="ReferenceDetails" nillable="false">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="ShipperReference" nillable="true" minOccurs="0">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ConsigneeReference" nillable="true" minOccurs="0">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="NotifyReference" nillable="true" minOccurs="0">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ForwarderReference" nillable="true" minOccurs="0">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="CustomsReference" nillable="true" minOccurs="0">
															<!-- Date: Dec 12,2014:Based on feedback received from CFR, made this data optional as all members can not provide this data -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="AddressDetails" maxOccurs="unbounded">
												<!-- Restructured Tags, Reduced number of Tags -->
												<xs:complexType>
													<xs:sequence>
														<xs:element name="AddressID" nillable="false">
															<xs:annotation>
																<xs:documentation>
																	  "SH" = Shipper Exporter Details
																	  "CN" = Consignee Details
																	  "NP" = Notify Party Details
																	  "AG" = Agent Details
																	  "FW" = Forwarder Details
																</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="2" />
																	<xs:minLength value="2" />
																	<xs:enumeration value="SH" />
																	<xs:enumeration value="CN" />
																	<xs:enumeration value="NP" />
																	<xs:enumeration value="AG" />
																	<xs:enumeration value="FW" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Name" maxOccurs="unbounded"> <!-- Date: 11th Jan 2015:Based on feedback received , changed maxOccurs="unbounded" -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />    
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Address" maxOccurs="unbounded"> <!-- Date: 11th Jan 2015:Based on feedback received , maxOccurs="unbounded" -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />  <!-- Value changed from 40 to 50 - Sept 18 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="CityName">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />   <!-- Value changed from 40 to 50 - Sept 18 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="StateProvince">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />   <!-- Value changed from 40 to 50 - Sept 18 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="PostalCode">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />    <!-- Value changed from 40 to 50 - Sept 18 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="CountryName">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />  <!-- Value changed from 40 to 50 - Sept 18 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="GovtReferenceNumber" maxOccurs="unbounded"  nillable="true">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="GovtRefType" maxOccurs="unbounded" nillable="true"> <!-- Added separate tags for Govt Ref and value -Sept 18 -->
																<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />  
																</xs:restriction>
																</xs:simpleType>
																</xs:element>
															<xs:element name="GovtRefValue" maxOccurs="unbounded" nillable="true">  <!-- Added separate tags for Govt Ref and value -Sept 18 -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />  
																</xs:restriction>
															</xs:simpleType>
															</xs:element>
														</xs:sequence>
														</xs:complexType>
													</xs:element>
													</xs:sequence>
												</xs:complexType>	
											</xs:element>
											<xs:element name="RoutingDetails">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="OriginCode">
															<xs:annotation>
																<xs:documentation>UN code.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="5" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="OriginName">
															<xs:annotation>
																<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<!-- Date: Mar 03,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtdOrigin" type="xs:date" nillable="false" /> <!-- Newly added in Routing details -->
														
														<xs:element name="LoadCode">
															<xs:annotation>
																<xs:documentation>UN code.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="5" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="LoadName">
															<xs:annotation>
																<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<!-- Date: Mar 10,2015:Based on feedback received from Transglory, chnaged maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtsLoadPort" type="xs:date" nillable="false" />    <!-- Newly added in Routing details -->
														
														<xs:element name="TransshipmentPort1" nillable="true" >   <!-- Added New fields for Transshipment Ports -->  
												<xs:annotation>
													<xs:documentation>UN code.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
														<xs:element name="TransshipmentPort1Name" nillable="true" >  <!-- Added New fields for Transshipment Ports -->
												<xs:annotation>
													<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
												</xs:annotation>
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
														<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtaTransshipmentPort1" type="xs:date" nillable="true" minOccurs="0"/> <!-- Newly added in Routing details -->
														<xs:element name="TransshipmentPort2" nillable="true" >   <!-- Added New fields for Transshipment Ports -->
														<xs:annotation>
															<xs:documentation>UN code.</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
														<xs:element name="TransshipmentPort2Name" nillable="true" >   <!-- Added New fields for Transshipment Ports -->
														<xs:annotation>
															<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="50" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtaTransshipmentPort2" type="xs:date" nillable="true" minOccurs="0" /> <!-- Newly added in Routing details -->
														<xs:element name="TransshipmentPort3" nillable="true" >   <!-- Added New fields for Transshipment Ports -->
														<xs:annotation>
															<xs:documentation>UN code.</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:maxLength value="5" />
													</xs:restriction>
												</xs:simpleType>
											</xs:element>
														<xs:element name="TransshipmentPort3Name" nillable="true" >  <!-- Added New fields for Transshipment Ports -->
														<xs:annotation>
															<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
															<xs:maxLength value="50" />
														</xs:restriction>
														</xs:simpleType>
													</xs:element>
											<!-- Date: Mar 10,2015:Based on feedback received from Transglory, changed maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtaTransshipmentPort3" type="xs:date" nillable="true" minOccurs="0"/><!-- Newly added in Routing details -->		
														
														<xs:element name="DischargeCode">
															<xs:annotation>
																<xs:documentation>UN code.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="5" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="DischargeName">
															<xs:annotation>
																<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<!-- Date: Mar 10,2015:Based on feedback received from Transglory, chnaged maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtaDischarge" type="xs:date" nillable="false" /> <!-- Newly added in Routing details -->
														
														<xs:element name="DestinationCode">
															<xs:annotation>
																<xs:documentation>UN code.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="5" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="DestinationName">
															<xs:annotation>
																<xs:documentation>If UN code is not available, Name should be printed if UN code is not available.</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<!-- Date: Mar 10,2015:Based on feedback received from Transglory, chnaged maxLength value= 50 from maxLength value=30 -->
														<xs:element name="EtaDestination" type="xs:date" nillable="false" /> <!-- Newly added in Routing details -->
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="ContainerDetails" maxOccurs="unbounded"> <!-- Date : Dec 18,2014: Based on members feedback we chnaged the Tag Name to ContainerDetails from CargoDetails to accomodate the scenario where one HBL can have multiple containers-->
												<xs:complexType>
													<xs:sequence>
														<xs:element name="ContainerNumber" nillable="false"> <!-- Date : Dec 18,2014 : Added ContainerNumber Field to identify shipment belongs to which container-->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="11" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="BookingDetails" minOccurs="0" maxOccurs="unbounded" nillable ="true">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="BookingStation">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="5" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="BookingNumber">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="20" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="WWAShipmentReference"> <!-- Added New field for WWAShipmentReference -->
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="25" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="LotNo">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="20" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
														<xs:element name="CargoDetails" minOccurs="0" maxOccurs="unbounded">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="Pieces" nillable="false">
																		<!-- Date: Dec 12,2014: Corrected Tag Property based on Mesco's feedback -->
																		<xs:simpleType>
																			<xs:restriction base="xs:integer">
																				<!-- Date: Dec 12,2014:Based on feedback received from Transglory, chnaged restriction base to Integer from String as peieces can not be string value -->
																				<xs:totalDigits value="6" /> <!-- Date: Dec 12,2014:Based on feedback received from Transglory, changed the property to totalDigits from maxLength -->
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="BarcodeNumber" maxOccurs="unbounded" nillable="true" minOccurs="0">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="40" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="Packaging" nillable="false">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="25" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the maxLength value to 25from 20 -->
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="Commodity" maxOccurs="unbounded" nillable="false"> 
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="85" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="HSCode" nillable="true"  minOccurs="0" maxOccurs="unbounded">  <!-- Date: 11th Jan 2015:Based on feedback received , changed maxOccurs="unbounded" -->
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="14" />
																				<xs:minLength value="0" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="NCM" nillable="true" minOccurs="0" maxOccurs="unbounded"> <!-- Date: 11th Jan 2015:Based on feedback received , changed maxOccurs="unbounded" -->
																		<!-- New Field Added, Required only for Brazil Shipments-->
																		<xs:annotation>
																			<xs:documentation>Used for Brazil's Mercosur Common Nomenclature </xs:documentation>
																		</xs:annotation>
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="12" />
																				<xs:minLength value="0" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="Weight" nillable="false">
																		<xs:simpleType>
																			<xs:restriction base="xs:decimal">
																				<xs:totalDigits value="10" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="Volume" nillable="false">
																		<xs:simpleType>
																			<xs:restriction base="xs:decimal">
																				<xs:totalDigits value="10" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="UOM" nillable="false">
																		<xs:annotation>
																			<xs:documentation>"E"=English; "M"=Metric</xs:documentation>
																		</xs:annotation>
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="1" />
																				<xs:minLength value="1" />
																				<xs:enumeration value="E" />
																				<xs:enumeration value="M" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="Marks" maxOccurs="unbounded" nillable="false">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="85" />
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="CargoImageURL" type="xs:anyURI" nillable="true" minOccurs="0" maxOccurs="unbounded" />
																	<xs:element name="HazardousFlag" nillable="false">
																		<xs:annotation>
																			<xs:documentation>"Y"=Yes; "N"=No</xs:documentation>
																		</xs:annotation>
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:maxLength value="1" />
																				<xs:enumeration value="N" />
																				<xs:enumeration value="Y" />
																				<xs:enumeration value="L" />       <!-- stands for LQ = Limited Quntity-->
																				<xs:enumeration value="E" />       <!-- stands for EQ = Excepted Quntity-->
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:element>
																	<xs:element name="HazardousDetails" minOccurs="0" maxOccurs="unbounded">
																		<xs:annotation>
																			<xs:documentation>If HazardousFlag="Y" then HazardousDetails is mandatory!</xs:documentation>
																		</xs:annotation>
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="HazardousClass" type="xs:float" nillable="false" />
																				<xs:element name="Flashpoint" minOccurs="0">
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="10" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="FlashpointFlag" minOccurs="0">
																					<xs:annotation>
																						<xs:documentation>"F" = Fahrenheit "C" = Centigrade</xs:documentation>
																					</xs:annotation>
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:minLength value="0" />
																							<xs:maxLength value="1" />
																							<xs:enumeration value="C" />
																							<xs:enumeration value="F" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="HazardousContent" nillable="true" minOccurs="0">
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="40" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="ShippingName" nillable="false">
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="40" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="UNNumber" nillable="false">
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="10" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="PackingGroup" nillable="true" minOccurs="0">
																				<!-- New Optional Field Added, 16-09-2015-->
																				<xs:annotation>
																						<xs:documentation>"Class I" = GreatDanger "Class II" = MediumDanger "Class III" = MinorDanger </xs:documentation>
																					</xs:annotation>
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="3" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="PackageCount" nillable="true" minOccurs="0">
																				<!-- New Optional Field Added, 16-09-2015-->
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:minLength value="1"/>
																							<xs:maxLength value="8"/>
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="PackageType" nillable="true" minOccurs="0">
																				<!-- New Optional Field Added, 16-09-2015-->
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="20" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="NetWeight" nillable="true" minOccurs="0">
																				<!-- New Optional Field Added, 16-09-2015-->									
																					<xs:simpleType>
																						<xs:restriction base="xs:decimal">
																							<xs:totalDigits value="10" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="EmergencyPhoneNumber" nillable="true" minOccurs="0">
																				<!-- New Optional Field Added, 16-09-2015-->
																					<xs:simpleType>
																						<xs:restriction base="xs:string">
																							<xs:maxLength value="15" />
																						</xs:restriction>
																					</xs:simpleType>
																				</xs:element>
																				<xs:element name="HazCargoImageURL" type="xs:anyURI" nillable="true" minOccurs="0" maxOccurs="unbounded" />
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="GeneralBlDetails" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="Marks" maxOccurs="unbounded">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="85" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Description" maxOccurs="unbounded">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="85" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="TaxID" nillable="true" minOccurs="0">
															<!-- Date: Dec 12,2014:Based on feedback received from CFR, made this data optional as all members can not provide this data -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="30" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="ChargeDetails" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="ChargeCode" nillable="true" minOccurs="0"> <!-- New Segment added, Date: Mar 10,2015:Based on feedback received from Mesco, added this field -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="20"/> <!--Based on feedback from Teamglobal/AGS  increased from 5 to 20-->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ChargeName" nillable="true" minOccurs="0"> <!-- New Segment added, Date: Mar 10,2015:Based on feedback received from Mesco, added this field -->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ChargeDescription" nillable="false"> <!-- Increased maxLength to 100 from 50-->
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="100" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="PrepaidCollect" nillable="false">
															<!-- Date: Dec 12,2014:Based on feedback received from Transglory, added enumaration values. -->
															<xs:annotation>
																<xs:documentation>P=Prepaid, C=Collect</xs:documentation>
															</xs:annotation>
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="1" />
																	<xs:enumeration value="P" />
																	<xs:enumeration value="C" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Rate" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:decimal">
																	<xs:totalDigits value="25" />
																	<xs:fractionDigits value="2" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Basis" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="7" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ForeignAmount" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:decimal">
																	<xs:totalDigits value="35" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the maxLength value to 35from 7 -->
																	<xs:fractionDigits value="2" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="ExchangeRate" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:decimal">
																	<xs:totalDigits value="20" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the maxLength value to 20from 7 -->
																	<xs:fractionDigits value="6" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the fraction digit value to 6 from 2 -->
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="LocalAmount" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:decimal">
																	<xs:totalDigits value="35" /> <!-- Date: 11th Jan 2015:Based on feedback received , changed the maxLength value to 35from 7 -->
																	<xs:fractionDigits value="2" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="Currency" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="7" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
														<xs:element name="PCName" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="40" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element name="CommentDetails" minOccurs="0" maxOccurs="3">
												<xs:complexType>
													<xs:sequence>
														<xs:element name="Remarks" nillable="false">
															<xs:simpleType>
																<xs:restriction base="xs:string">
																	<xs:maxLength value="50" />
																</xs:restriction>
															</xs:simpleType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
</xs:schema>