<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ShipmentStatus">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Envelope">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="SenderID" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ReceiverID" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="6"/>
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Password" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="6"/>
										<xs:maxLength value="100"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="40"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Version" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="8"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="EnvelopeID" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="40"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ShipmentStatusDetails" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						    <xs:element name="ApplicationType" nillable="false">
								<xs:annotation>
								<xs:documentation>WE=WWA-EDI,WO=WWAOnline,WS=WebServices,MN=Manual,MO=MemberWebsite,ME=MemberEDI</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
								<xs:restriction base="xs:string">
								<xs:maxLength value="2"/>
								</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="TypeOfMove" nillable="true">
                                				<xs:annotation>
                               					<xs:documentation>L=LCL, F=FCL</xs:documentation>
                               					</xs:annotation>
                                				<xs:simpleType>
                                				<xs:restriction base="xs:string">
                                				<xs:maxLength value="2"/>
                                				</xs:restriction>
                                				</xs:simpleType>
                            				</xs:element>
							<xs:element name="ShipperReference" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="30"/>
										<xs:minLength value="0"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ForwarderReference" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ConsigneeReference" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CommunicationReference" nillable="true" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PickupReference" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="BookingNumber" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="PrimaryBookingNumber" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="WWAShipmentReference" nillable="true" minOccurs="0" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="LotNumber" nillable="false" >
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="HouseBillOfLadingNumber" nillable="true" minOccurs="0">
								<xs:annotation>
									<xs:documentation>HouseBillOfLadingNumber is mandatory if Status code = 60, 70 or 80</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CarrierBookingNumber" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
								</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="FileNumber" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="30"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ReleaseType" nillable="true" minOccurs="0">
								<xs:annotation>
									<xs:documentation>E=Express release, O=Originals required if status code=50</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="1"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ArrivalNoticeNumber" nillable="true" minOccurs="0" maxOccurs="unbounded">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ContainerNumber" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="12"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ContainerSize" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ContainerType" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="ContainerCode" nillable="true">
							<xs:annotation>
									<xs:documentation>This segment will have information about ISO standard Conatiner Code</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SealNumber" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
                            <xs:element name="CarrierSCAC" nillable="true" minOccurs="0">
                                <xs:annotation>
                                </xs:annotation>
                                        <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                        <xs:minLength value="0"/>
                                                        <xs:maxLength value="10"/>
                                                </xs:restriction>
                                        </xs:simpleType>
                            </xs:element>
							<xs:element name="OceanVessel" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="50"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Voyage" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="10"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="IMONumber" nillable="true" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="7"/>
										<xs:maxLength value="8"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="CustomerAlias" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="15"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="StatusCode" nillable="false">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="4"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="StatusLocationCode" nillable="false">
								<xs:annotation>
									<xs:documentation>If Status Code = 60, 70 or 80 then HouseBillOfLadingNumber is mandatory</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="5"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="StatusLocationName" nillable="true">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="0"/>
										<xs:maxLength value="35"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RoutingDetails">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ReceivingWarehouse" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="5"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="CutoffReceivingWarehouse" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:date"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PlaceOfReceipt" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="5"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ETSPlaceOfReceipt" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:date"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PortOfLoading" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="5"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ETSPortOfLoading" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:date"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PortOfDischarge" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="5"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ETAPortOfDischarge" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:date"/>
											</xs:simpleType>
										</xs:element>
										<xs:element name="PlaceOfDelivery" nillable="false">
										<xs:simpleType>
											<xs:restriction base="xs:string">
											<xs:maxLength value="5"/>
											</xs:restriction>
										</xs:simpleType>
										</xs:element>
										<xs:element name="ETAPlaceOfDelivery" type="xs:date" nillable="false"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="StatusDateTimeDetails">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Date" type="xs:date" nillable="false"/>
										<xs:element name="Time" type="xs:time" nillable="false"/>
										<xs:element name="TimeZone" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="4"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="CargoDetails">
	                            				 <xs:complexType>
		                            				<xs:sequence>
									    <xs:element name="Pieces" nillable="false">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									    <xs:element name="WeightLBS" type="xs:float" nillable="false"/>
									    <xs:element name="VolumeCBF" type="xs:float" nillable="false"/>
									    <xs:element name="WeightKG" type="xs:float" nillable="false"/>
									    <xs:element name="VolumeCBM" type="xs:float" nillable="false"/>
									    <xs:element name="HazardousFlag" nillable="false">
									    <xs:annotation>
										    <xs:documentation>"Y"=Yes; "N"=No</xs:documentation>
									    </xs:annotation>
										    <xs:simpleType>
										    <xs:restriction base="xs:string">
										    <xs:maxLength value="1"/>
										    <xs:enumeration value="N"/>
										    <xs:enumeration value="Y"/>
										    </xs:restriction>
										    </xs:simpleType>
									    </xs:element>
									    <xs:element name="HazardousDetails" minOccurs="0">
										    <xs:complexType>
										    <xs:sequence>
											<xs:element name="Pieces" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
												</xs:restriction>
											</xs:simpleType>
										    </xs:element>
			    						    <xs:element name="HazWeightLBS" type="xs:float" nillable="true"/>
									        <xs:element name="HazVolumeCBF" type="xs:float" nillable="true"/>
									        <xs:element name="HazWeightKG" type="xs:float" nillable="true"/>
									        <xs:element name="HazVolumeCBM" type="xs:float" nillable="true"/>
										    </xs:sequence>
										    </xs:complexType>
									    </xs:element>
								    </xs:sequence>
							    </xs:complexType>
						    </xs:element>
							<xs:element name="ExceptionTypeDetails" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>If StatusCode = 21, then ExceptionType is mandatory</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ExceptionID" nillable="true">
											<xs:annotation>
												<xs:documentation>Weight Volume Pieces Destination</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="12"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="UOM">
											<xs:annotation>
												<xs:documentation>"E"=English; "M"=Metric</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ValueReceived" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="0"/>
													<xs:maxLength value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ValueBooked" nillable="true">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="0"/>
													<xs:maxLength value="15"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="DocumentationDetails" minOccurs="0">
								<xs:annotation>
									<xs:documentation>If StatusCode = 10, 20, 21, 50, 60, 70, then DocumentationDetails is Mandatory</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element name="ImageLink" type="xs:anyURI" nillable="true" minOccurs="0"/>
										<xs:element name="Image" type="xs:base64Binary" nillable="true" minOccurs="0"/>
										<xs:element name="ContentType" type="xs:string" nillable="true" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>




