// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.MasterFiles.GUI.Testing.ZMilestonesOrExceptionsUserControlTest.Form")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Milestones/ZMilestonesOrExceptionsUserControlTest.cs:100,34
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefCityTownFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefCityTown/RefCityTownFormTest.cs:22,30
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.UpdateMultipleJobDocAddressesFormBasherTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/AdministrationPanel/Addresses/UpdateMultipleJobDocAddressesFormBasherTest.cs:11,48
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.SalesTeamFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Sales/SalesTeam/SalesTeamFormTest.cs:107,61
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RichTextEmailDisplayZFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Organisation/UserControls/RichTextEmailDisplayZFormTest.cs:74,110
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.WorkflowEventFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Events/WorkflowEventFormTest.cs:15,17
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefPostCodeFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefPostCode/RefPostCodeFormTest.cs:24,30
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.ProcessTaskTemplateFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/ProcessTaskTemplate/ProcessTaskTemplateFormTest.cs:115,37
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.DocLoginMessageWithPIAInvFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Accounting/AccUnpaidPIAInvoices/DocLoginMessageWithPIAInvFormTest.cs:27,65
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefCityTownFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefCityTown/RefCityTownFormTest.cs:22,30
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.WorkflowEventFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Events/WorkflowEventFormTest.cs:15,17
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.MasterFiles.GUI.Testing.ZMilestonesOrExceptionsUserControlTest.Form")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Milestones/ZMilestonesOrExceptionsUserControlTest.cs:100,34
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.DocLoginMessageWithPIAInvFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Accounting/AccUnpaidPIAInvoices/DocLoginMessageWithPIAInvFormTest.cs:27,65
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefPostCodeFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefPostCode/RefPostCodeFormTest.cs:24,30
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.ProcessTaskTemplateFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/ProcessTaskTemplate/ProcessTaskTemplateFormTest.cs:115,37
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.UpdateMultipleJobDocAddressesFormBasherTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/AdministrationPanel/Addresses/UpdateMultipleJobDocAddressesFormBasherTest.cs:11,48
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RichTextEmailDisplayZFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Organisation/UserControls/RichTextEmailDisplayZFormTest.cs:74,110
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.SalesTeamFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Sales/SalesTeam/SalesTeamFormTest.cs:107,61
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.SalesTeamFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Sales/SalesTeam/SalesTeamFormTest.cs:107,61
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.UpdateMultipleJobDocAddressesFormBasherTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/AdministrationPanel/Addresses/UpdateMultipleJobDocAddressesFormBasherTest.cs:11,48
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.DocLoginMessageWithPIAInvFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Accounting/AccUnpaidPIAInvoices/DocLoginMessageWithPIAInvFormTest.cs:27,65
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.MasterFiles.GUI.Testing.ZMilestonesOrExceptionsUserControlTest.Form")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Milestones/ZMilestonesOrExceptionsUserControlTest.cs:100,34
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.WorkflowEventFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/Events/WorkflowEventFormTest.cs:15,17
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.ProcessTaskTemplateFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Workflow/ProcessTaskTemplate/ProcessTaskTemplateFormTest.cs:115,37
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefPostCodeFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefPostCode/RefPostCodeFormTest.cs:24,30
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RichTextEmailDisplayZFormTest.GetFormToBashCore")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/Organisation/UserControls/RichTextEmailDisplayZFormTest.cs:74,110
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MasterFiles.GUI.Testing.RefCityTownFormTest.TestFormCaption")] // Enterprise/Product/Operations/MasterFiles/MasterFiles.GUI.Test/ReferenceFiles/RefCityTown/RefCityTownFormTest.cs:22,30
