<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.MasterFiles.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.MasterFiles.GUI.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
    <Configurations>Debug;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Global\GlbStaff\ChangePassword\ValueConverter\**" />
    <EmbeddedResource Remove="Global\GlbStaff\ChangePassword\ValueConverter\**" />
    <None Remove="Global\GlbStaff\ChangePassword\ValueConverter\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\MasterFiles.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Accounting\AccTemplateFileStorage\TestDocs\Test.xslt">
      <LogicalName>Test.xslt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Business\MasterFiles.Business\Testing\sample_signature.PNG">
      <LogicalName>sample_signature.PNG</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Business\MasterFiles.Business\Testing\sample_signature2.PNG">
      <LogicalName>sample_signature2.PNG</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\..\Common\Tools\OutlookUtilities\OutlookUtilities.Test\Testing\TestOutlookMsg.msg" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
    <Reference Include="WinzorTestFramework" />
    <Reference Include="CargoWise.Interop" />
  </ItemGroup>
</Project>