<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.MasterFiles.GUI.Test</RootNamespace>
    <AssemblyName>Enterprise.MasterFiles.GUI.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Moq" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="CargoWise.Interop" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\MasterFiles.GUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Accounting\AccTemplateFileStorage\TestDocs\Test.xslt">
      <LogicalName>Test.xslt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Business\MasterFiles.Business\Testing\sample_signature.PNG">
      <LogicalName>sample_signature.PNG</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Business\MasterFiles.Business\Testing\sample_signature2.PNG">
      <LogicalName>sample_signature2.PNG</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\..\Common\Tools\OutlookUtilities\OutlookUtilities.Test\Testing\TestOutlookMsg.msg" />
  </ItemGroup>
</Project>