<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.FsisEstNumbersCrawler.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.FsisEstNumbersCrawler.Test</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug</Configurations>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\MPI_2307_byNumber.csv" />
    <None Remove="Resources\MPI_TestSmallData.csv" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FsisEstNumbersCrawler\FsisEstNumbersCrawler.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs" AutoGen="True" DesignTimeSharedInput="True" DependentUpon="Settings.settings" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="  CargoWise.RefDbRepo.UniversalXMLProducers.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.UniversalXMLProducers.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="CargoWise.RefDbRepo.FsisEstNumbersCrawler.Test.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Meat, Poultry and Egg Product Inspection Directory _ Food Safety and Inspection Service.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\MPI_2307_byNumber.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\MPI_TestSmallData.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\MPI_Directory_by_Establishment_Name.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\testfile.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\WiseTechGlobal.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\USReferenceData.Business\USReferenceData.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\articles.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\articles.xls">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>