// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.ClientSharedComponents.Registry.ServiceLevelRegistryBusinessObject.ServiceLevelCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\ClientSharedComponents\ClientSharedComponents\Registry\Business\ServiceLevels\ServiceLevelRegistryBusinessObject.cs:152:40
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ClientSharedComponents.SharedTestHelper.CreateOrderLine(CargoWise.Types.ZString,CargoWise.Types.ZShort,CargoWise.Types.ZShort)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\ClientSharedComponents\ClientSharedComponents\SharedTestHelper.cs:151:22
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ClientSharedComponents.BoolFieldAttribute.mTrueCollection")] // Enterprise/ClientExtensions/ClientSharedComponents/ClientSharedComponents/DataTransfer/FieldAttributes/BoolFieldAttribute.cs:54,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ClientSharedComponents.BoolFieldAttribute.mFalseCollection")] // Enterprise/ClientExtensions/ClientSharedComponents/ClientSharedComponents/DataTransfer/FieldAttributes/BoolFieldAttribute.cs:55,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ClientSharedComponents.BoolFieldAttribute.mTrueCollection")] // Enterprise/ClientExtensions/ClientSharedComponents/ClientSharedComponents/DataTransfer/FieldAttributes/BoolFieldAttribute.cs:54,27
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ClientSharedComponents.BoolFieldAttribute.mFalseCollection")] // Enterprise/ClientExtensions/ClientSharedComponents/ClientSharedComponents/DataTransfer/FieldAttributes/BoolFieldAttribute.cs:55,27
