<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Enterprise.ZArchitecture.Web.GlobalBase</AssemblyName>
    <RootNamespace>Enterprise.ZArchitecture.Web.GlobalBase</RootNamespace>
    <OutputPath>..\..\..\..\Bin\</OutputPath>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Database.Shared">
      <HintPath>..\..\..\..\Bin\CargoWise.Database.Shared.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.DataProtection.SqlExtensions">
      <HintPath>..\..\..\..\bin\CargoWise.DataProtection.SqlExtensions.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Reflection">
      <HintPath>..\..\..\..\Bin\CargoWise.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Shared.40">
      <HintPath>..\..\..\..\Bin\CargoWise.Shared.40.dll</HintPath>
    </Reference>
    <Reference Include="CargoWiseOne.WebInfrastructure">
      <HintPath>..\..\..\..\Bin\CargoWiseOne.WebInfrastructure.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Initialisation">
      <HintPath>..\..\..\..\Bin\Enterprise.Initialisation.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data.Providers.Common">
      <HintPath>..\..\..\..\Bin\CargoWise.Data.Providers.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.DataProtection">
      <HintPath>..\..\..\..\Bin\CargoWise.DataProtection.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.DataProtection.SqlExtensions">
      <HintPath>..\..\..\..\Bin\CargoWise.DataProtection.SqlExtensions.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Environment">
      <HintPath>..\..\..\..\Bin\Enterprise.Environment.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Semaphores.Common">
      <HintPath>..\..\..\..\Bin\Enterprise.Semaphores.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
    <Reference Include="WTG.StaticAnalysis.Annotation">
      <HintPath>..\..\..\..\Bin\WTG.StaticAnalysis.Annotation.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.ZArchitecture.Web.Business.csproj" />
    <ProjectReference Include="..\Enterprise.ZArchitecture.Web.Common\Enterprise.ZArchitecture.Web.Common.csproj" />
    <ProjectReference Include="..\Utilities\Enterprise.ZArchitecture.Web.Utilities.csproj" />
    <ProjectReference Include="..\Shared\Enterprise.ZArchitecture.Web.Shared.csproj" />
  </ItemGroup>
</Project>