<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.Client.WFN.ServiceTasks.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <None Remove="Import\TestFiles\Test.xml" />
    <None Remove="Import\TestFiles\WrongXmlFile.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Import\TestFiles\Test.xml">
      <LogicalName>Import.TestFiles.Test.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Import\TestFiles\WrongXmlFile.xml">
      <LogicalName>Import.TestFiles.WrongXmlFile.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientWFN.ServiceTasks\ZClientWFN.ServiceTasks.csproj" />
    <ProjectReference Include="..\ZClientWFN\ZClientWFN.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" /> 
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Test" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.ClientSharedComponents" />
    <Reference Include="CargoWise.Data" /> 
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.DataTransfer" />
    <Reference Include="Enterprise.DataTransfer.Test" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.DataTransfer" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.DataTransfer" />
    <Reference Include="Enterprise.MasterData.Common" /> 
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Registry.Business.Test" /> 
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
</Project>