<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ContractManagement.GUI.Test</RootNamespace>
    <AssemblyName>Enterprise.ContractManagement.GUI.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <CWEnableIsExternalInitForNetFrameworkOnly>true</CWEnableIsExternalInitForNetFrameworkOnly>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\ContractManagement.GUI\ContractManagement.GUI.csproj" />
  </ItemGroup> 
  <ItemGroup>
    <Reference Include="Moq" />
  </ItemGroup>
</Project>