<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ChinaStandard_GBT24589_1_Payrolls_ENG"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:Enterprise ="http://sxbw.audit.gov.cn/AccountingSoftwareDataInterfaceStandard/2010/SOE/XMLSchema"
	xmlns ="http://sxbw.audit.gov.cn/AccountingSoftwareDataInterfaceStandard/2010/SOE/XMLSchema"
	targetNamespace="http://sxbw.audit.gov.cn/AccountingSoftwareDataInterfaceStandard/2010/SOE/XMLSchema"
	elementFormDefault="qualified"  attributeFormDefault="unqualified">
	<xs:include schemaLocation="ChinaStandard_GBT24589_1_StandardElements_ENG.xsd"/>
	<xs:element name="StaffPayroll">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PayrollPeriods"  maxOccurs="unbounded" />
				<xs:element ref="PayrollItems" maxOccurs="unbounded" />
				<xs:element ref="StaffPayrollList"  maxOccurs="unbounded" />
				<xs:element ref="StaffPayrollDetails"  maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="locID" use="optional" fixed="U05"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="PayrollPeriods">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PayrollYear">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollYearType">
								<xs:attribute ref="locID" use="optional" fixed="050101"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollPeriod">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollPeriodType">
								<xs:attribute ref="locID" use="optional" fixed="050102"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollPeriodStartDate">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollPeriodStartDateType">
								<xs:attribute ref="locID" use="optional" fixed="050103"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollPeriodEndDate">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollPeriodEndDateType">
								<xs:attribute ref="locID" use="optional" fixed="050104"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				
			</xs:sequence>
			<xs:attribute ref="locID" use="optional" fixed="T501"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="PayrollItems">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="PayrollTypeName">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollTypeNameType">
								<xs:attribute ref="locID" use="optional" fixed="050201"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollItemCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollItemCodeType">
								<xs:attribute ref="locID" use="optional" fixed="050202"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollItemName">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollItemNameType">
								<xs:attribute ref="locID" use="optional" fixed="050203"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="locID" use="optional" fixed="T502"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="StaffPayrollList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StaffCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="StaffCodeType">
								<xs:attribute ref="locID" use="optional" fixed="010801"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="StaffType">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="StaffTypeType">
								<xs:attribute ref="locID" use="optional" fixed="050301"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DepartmentCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="DepartmentCodeType">
								<xs:attribute ref="locID" use="optional" fixed="010701"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollTypeName">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollTypeNameType">
								<xs:attribute ref="locID" use="optional" fixed="050201"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollYear">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollYearType">
								<xs:attribute ref="locID" use="optional" fixed="050101"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollPeriod">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollPeriodType">
								<xs:attribute ref="locID" use="optional" fixed="050102"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="FinancialYear">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="FinancialYearType">
								<xs:attribute ref="locID" use="optional" fixed="010110"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Period">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PeriodType">
								<xs:attribute ref="locID" use="optional" fixed="010201"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="CurrencyCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="CurrencyCodeType">
								<xs:attribute ref="locID" use="optional" fixed="010501"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="locID" use="optional" fixed="T503"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="StaffPayrollDetails">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StaffCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="StaffCodeType">
								<xs:attribute ref="locID" use="optional" fixed="010801"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollTypeName">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollTypeNameType">
								<xs:attribute ref="locID" use="optional" fixed="050201"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollYear">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollYearType">
								<xs:attribute ref="locID" use="optional" fixed="050101"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollPeriod">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollPeriodType">
								<xs:attribute ref="locID" use="optional" fixed="050102"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollItemCode">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollItemCodeType">
								<xs:attribute ref="locID" use="optional" fixed="050202"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="PayrollAmount">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="PayrollAmountType">
								<xs:attribute ref="locID" use="optional" fixed="050401"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute ref="locID" use="optional" fixed="T504"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
