<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.DataTransfer.SystemMerge.GUI</AssemblyName>
    <RootNamespace>Enterprise.DataTransfer.SystemMerge.GUI</RootNamespace>
    <EnableWinzorTests>false</EnableWinzorTests>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
</Project>