<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>Enterprise.ResourceStrings.Cmd</RootNamespace>
    <AssemblyName>Enterprise.ResourceStrings.Cmd</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Initialisation" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\ResourceStrings.Business.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
</Project>