// <auto-generated/>
using System.Drawing;
using CargoWiseOne.ResourceStrings;
using Enterprise.Warehouse.Environment.Business;
using Enterprise.Warehouse.Transactions.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.GUI;

namespace Enterprise.Warehouse.Transactions.GUI.WhsPicksAwaitingReplenishment
{
	public partial class WhsPicksAwaitingReplenishmentForm : ZChildForm
	{
		#region Constructors

		public WhsPicksAwaitingReplenishmentForm(WhsPick pick)
			: base(pick)
		{
			InitializeComponent();
		}

		#endregion

		WhsPick Pick => (WhsPick)BusinessEntity;
		public void PicksAwaitingGrid_ColourDecidingForTest(object sender, ColourDecidingEventArgs e) => PicksAwaitingGrid_ColourDeciding(sender, e);

		public override string FormCaption =>
			Res.GetString("WhsPicksAwaitingReplenishmentForm|BB49995B-BCB9-4327-AF86-3C9174692F88", "Fixed Pick Faces Awaiting Replenishment");

		void PicksAwaitingGrid_ColourDeciding(object sender, ColourDecidingEventArgs e)
		{
			var pickFaceAwaitingReplenishment = e.ObjectAtRow as WhsPickFaceAwaitingReplenishmentView;
			if (pickFaceAwaitingReplenishment != null)
			{
				if (pickFaceAwaitingReplenishment.WWP_WP == Pick.PK)
				{
					e.Colour = Color.SkyBlue;
				}
			}
		}
	}
}
