<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.DataPurge.Test</AssemblyName>
    <RootNamespace>Enterprise.DataPurge.Test</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <CWEnableIsExternalInitForNetFrameworkOnly>true</CWEnableIsExternalInitForNetFrameworkOnly>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\DataPurge\DataPurge.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="Moq" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>