<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientMFI.Test</AssemblyName>
    <RootNamespace>Enterprise.Client.MFI.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientMFI\ZClientMFI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\BL.CSCLON0301001.freighted.txt">
      <LogicalName>BL.CSCLON0301001.freighted.txt</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\COMOBL.JJ0938JMND30.doc">
      <LogicalName>COMOBL.JJ0938JMND30.doc</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\OBL.CSCL0495883.doc">
      <LogicalName>OBL.CSCL0495883.doc</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\OBL.CSCL0495883.doc_20061101060024">
      <LogicalName>OBL.CSCL0495883.doc_20061101060024</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\ORD.MFITEST.A18374XG.May06.txt">
      <LogicalName>ORD.MFITEST.A18374XG.May06.txt</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\ORG.MFITEST.pdf">
      <LogicalName>ORG.MFITEST.pdf</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\TLX.HKGSYDH08706H01.tif">
      <LogicalName>TLX.HKGSYDH08706H01.tif</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AutoeDocAllocation\TestFiles\TSP.TSTConNote.POD.msg">
      <LogicalName>TSP.TSTConNote.POD.msg</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Export\Consol\TestFiles\MultiConsolOutput.csv">
      <LogicalName>Export.Console.MultiConsolOutput.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Export\Consol\TestFiles\output.csv">
      <LogicalName>Export.Console.output.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Import\TestFiles\CaroTransExpectedResultsTestFile.xml">
      <LogicalName>Import.CaroTransExpectedResultsTestFile.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Import\TestFiles\CaroTransExpectedResultsTestFile_Whidbey.xml">
      <LogicalName>Import.CaroTransExpectedResultsTestFile_Whidbey.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Import\TestFiles\CaroTransOrderTestFile.cti">
      <LogicalName>Import.CaroTransOrderTestFile.cti</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="CaroTrans\Import\TestFiles\CaroTransTestFile.dat">
      <LogicalName>Import.CaroTransTestFile.dat</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="DataImportExport\TestFiles\EmptyDateLines_Sample.csv">
      <LogicalName>DataImportExport.EmptyDateLines_Sample.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="DataImportExport\TestFiles\InvalidData_Sample.csv">
      <LogicalName>DataImportExport.InvalidData_Sample.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="DataImportExport\TestFiles\ValidData_Sample.csv">
      <LogicalName>DataImportExport.ValidData_Sample.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="OrgImportFromMFICSVFile\TestFiles\Organisation Sample File.csv">
      <LogicalName>OrgImportFromMFICSFile.Organisation Sample File.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\Documents\MFIDocuments.xml">
      <LogicalName>MFIDocuments.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>