using Enterprise.ZArchitecture;

namespace Enterprise.Customs.BR.GUI
{
	public partial class NFeExportForm
	{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		#region Windows Form Designer generated code

		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		new void InitializeComponent()
		{
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo13 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo9 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo10 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo11 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo12 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo13 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo18 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo14 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo15 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo16 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo19 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo17 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo18 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo19 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo20 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo21 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo20 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo22 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo23 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo21 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo24 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo25 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo26 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo27 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo28 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo29 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo30 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo22 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo31 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo32 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo33 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo34 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo23 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo35 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo36 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo37 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo38 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo39 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo40 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo41 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo24 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo25 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo26 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo27 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo28 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo29 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiLineTextBoxColumnInfo zMultiLineTextBoxColumnInfo1 = new Enterprise.ZArchitecture.GUI.ZMultiLineTextBoxColumnInfo();
			this.CloseButton = new Enterprise.ZArchitecture.GUI.ZButton();
			this.HeaderGroupBox = new Enterprise.ZArchitecture.GUI.ZGroupBox();
			this.HeaderGrid = new Enterprise.ZArchitecture.ZGrid();
			this.LinesGroupBox = new Enterprise.ZArchitecture.GUI.ZGroupBox();
			this.LinesGrid = new Enterprise.ZArchitecture.ZGrid();
			this.ExportDataButton = new Enterprise.ZArchitecture.GUI.ZButton();
			this.ButtonsPanel = new Enterprise.ZArchitecture.GUI.ZPanel();
			this.SaveFileDialog = new Enterprise.ZArchitecture.GUI.ZSaveFileDialog();
			((System.ComponentModel.ISupportInitialize)(this.MessageStatusBarPanel)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.ErrorStatusBarPanel)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.HeaderGroupBox.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.HeaderGrid)).BeginInit();
			this.HeaderGrid.SuspendLayout();
			this.LinesGroupBox.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.LinesGrid)).BeginInit();
			this.LinesGrid.SuspendLayout();
			this.ButtonsPanel.SuspendLayout();
			this.SuspendLayout();
			// 
			// MainStatusBar
			// 
			this.MainStatusBar.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 552, true);
			this.MainStatusBar.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(692, 24, true);
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Enterprise.Customs.BR.Business.NFeExportObject);
			// 
			// CloseButton
			// 
			this.CloseButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.CloseButton.CaptionResourceString = Enterprise.Customs.BR.GUI.Res.GetData("193ef8c4-18e4-4be8-bba1-bab5f8518902", "Close");
			this.CloseButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.CloseButton.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(606, 6, true);
			this.CloseButton.Name = "CloseButton";
			this.CloseButton.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(75, 23, true);
			this.CloseButton.TabIndex = 13;
			this.CloseButton.ToolTipCaption = null;
			this.CloseButton.UseVisualStyleBackColor = true;
			this.CloseButton.Click += new System.EventHandler(this.CloseButton_Click);
			// 
			// HeaderGroupBox
			// 
			this.HeaderGroupBox.CaptionResourceString = Enterprise.Customs.BR.GUI.Res.GetData("179ba1a7-da20-4c75-8e4a-1c9873ebfad9", "Entries");
			this.HeaderGroupBox.Controls.Add(this.HeaderGrid);
			this.HeaderGroupBox.Dock = System.Windows.Forms.DockStyle.Top;
			this.HeaderGroupBox.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.HeaderGroupBox.Name = "HeaderGroupBox";
			this.HeaderGroupBox.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(692, 153, true);
			this.HeaderGroupBox.TabIndex = 8;
			this.HeaderGroupBox.TabStop = false;
			// 
			// HeaderGrid
			// 
			this.HeaderGrid.AllowNavigation = false;
			this.BindingSource.SetBindingMember(this.HeaderGrid, "Entries");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).ReferenceNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).EntryNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).EntryNumberIssueDate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).ReleaseDate)));
			this.HeaderGrid.CaptionVisible = false;
			zTextBoxColumnStyleInfo1.ColumnName = "ReferenceNumber";
			zTextBoxColumnStyleInfo1.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo2.ColumnName = "EntryNumber";
			zTextBoxColumnStyleInfo2.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDateEditColumnStyleInfo1.ColumnName = "EntryNumberIssueDate";
			zDateEditColumnStyleInfo1.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo1.DefaultCollectionIndex = 0;
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo2.ColumnName = "ReleaseDate";
			zDateEditColumnStyleInfo2.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo2.DefaultCollectionIndex = 0;
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			this.HeaderGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.HeaderGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.HeaderGrid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.HeaderGrid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.HeaderGrid.Dock = System.Windows.Forms.DockStyle.Fill;
			this.HeaderGrid.GridId = "8afa1417-b14c-4534-adff-0510fe9ed258";
			this.HeaderGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.HeaderGrid.LayoutKey = "NFEGrid";
			this.HeaderGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(3, 16, true);
			this.HeaderGrid.Name = "HeaderGrid";
			this.HeaderGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(686, 134, true);
			this.HeaderGrid.TabIndex = 0;
			// 
			// LinesGroupBox
			// 
			this.LinesGroupBox.CaptionResourceString = Enterprise.Customs.BR.GUI.Res.GetData("d750ced3-9d0c-46fa-8038-b519967be9c8", "Invoice Lines");
			this.LinesGroupBox.Controls.Add(this.LinesGrid);
			this.LinesGroupBox.Dock = System.Windows.Forms.DockStyle.Fill;
			this.LinesGroupBox.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 153, true);
			this.LinesGroupBox.Name = "LinesGroupBox";
			this.LinesGroupBox.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(692, 364, true);
			this.LinesGroupBox.TabIndex = 9;
			this.LinesGroupBox.TabStop = false;
			// 
			// LinesGrid
			// 
			this.LinesGrid.AllowNavigation = false;
			this.BindingSource.SetBindingMember(this.LinesGrid, "Entries.Lines");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZShort)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).InvoiceLineNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).InvoiceNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ProductCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).TariffCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).GoodsDescription)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).Nve)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).SupplierName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ManufacturerIndicator)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ManufacturerName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).Addition)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).InvoiceQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).InvoiceQuantityUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CustomsQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CustomsQuantityUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).FOBValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).FreightValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).InsuranceValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CIFValue)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).GrossWeight)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).NetWeight)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).DutyTaxRegime)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).DutyRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).DutyAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPITaxRegime)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPIBaseAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPIRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPIAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPISpecialRateUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPISpecialRateQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IPISpecialRateAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISCofinsTaxRegime)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISBaseAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISSpecialRateUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISSpecialRateQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).PISSpecialRateAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsBaseAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsSpecialRateUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsSpecialRateQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).CofinsSpecialRateAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSTaxRegime)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSBaseAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSReductionPercentage)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).IcmsTotalAmountReduction)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).FCPRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).FCPAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ICMSLegalBase)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).SiscomexUsageFee)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingBaseAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingRate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingSpecialRateUQ)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingSpecialRateQuantity)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AntidumpingSpecialRateAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).AfrmmAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ImportLicenseFineAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).EICAmount)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).OrderNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).OrderLineNumberAndSubLine)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).ConcessionActNumber)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).Permits)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.Customs.BR.Business.NFeInvoiceLineExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeEntryExportObject)(((System.Collections.IList)(((Enterprise.Customs.BR.Business.NFeExportObject)(null)).Entries)).SyncRoot)).Lines)).SyncRoot)).Complement)));
			this.LinesGrid.CaptionVisible = false;
			zTextBoxColumnStyleInfo3.ColumnName = "InvoiceLineNumber";
			zTextBoxColumnStyleInfo3.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo4.ColumnName = "InvoiceNumber";
			zTextBoxColumnStyleInfo4.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo5.ColumnName = "ProductCode";
			zTextBoxColumnStyleInfo5.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo6.ColumnName = "TariffCode";
			zTextBoxColumnStyleInfo6.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo7.ColumnName = "GoodsDescription";
			zTextBoxColumnStyleInfo7.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zTextBoxColumnStyleInfo8.ColumnName = "Nve";
			zTextBoxColumnStyleInfo8.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zTextBoxColumnStyleInfo9.ColumnName = "SupplierName";
			zTextBoxColumnStyleInfo9.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(85);
			zTextBoxColumnStyleInfo10.ColumnName = "ManufacturerIndicator";
			zTextBoxColumnStyleInfo10.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zTextBoxColumnStyleInfo11.ColumnName = "ManufacturerName";
			zTextBoxColumnStyleInfo11.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zTextBoxColumnStyleInfo12.ColumnName = "Addition";
			zTextBoxColumnStyleInfo12.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo1.ColumnName = "InvoiceQuantity";
			zCalcEditColumnStyleInfo1.Decimals = 5;
			zCalcEditColumnStyleInfo1.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo13.ColumnName = "InvoiceQuantityUQ";
			zTextBoxColumnStyleInfo13.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo2.ColumnName = "CustomsQuantity";
			zCalcEditColumnStyleInfo2.Decimals = 5;
			zCalcEditColumnStyleInfo2.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo14.ColumnName = "CustomsQuantityUQ";
			zTextBoxColumnStyleInfo14.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo3.ColumnName = "FOBValue";
			zCalcEditColumnStyleInfo3.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo4.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo4.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo4.ColumnName = "FreightValue";
			zCalcEditColumnStyleInfo4.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo5.ColumnName = "InsuranceValue";
			zCalcEditColumnStyleInfo5.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo6.ColumnName = "CIFValue";
			zCalcEditColumnStyleInfo6.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo7.ColumnName = "GrossWeight";
			zCalcEditColumnStyleInfo7.Decimals = 3;
			zCalcEditColumnStyleInfo7.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo15.ColumnName = "GrossWeightUQ";
			zTextBoxColumnStyleInfo15.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zCalcEditColumnStyleInfo8.ColumnName = "NetWeight";
			zCalcEditColumnStyleInfo8.Decimals = 3;
			zCalcEditColumnStyleInfo8.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo16.ColumnName = "NetWeightUQ";
			zTextBoxColumnStyleInfo16.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zTextBoxColumnStyleInfo17.ColumnName = "DutyTaxRegime";
			zTextBoxColumnStyleInfo17.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo9.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo9.ColumnName = "DutyRate";
			zCalcEditColumnStyleInfo9.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCalcEditColumnStyleInfo10.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo10.ColumnName = "DutyAmount";
			zCalcEditColumnStyleInfo10.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo18.ColumnName = "IPITaxRegime";
			zTextBoxColumnStyleInfo18.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo11.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo11.ColumnName = "IPIBaseAmount";
			zCalcEditColumnStyleInfo11.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo12.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo12.ColumnName = "IPIRate";
			zCalcEditColumnStyleInfo12.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCalcEditColumnStyleInfo13.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo13.ColumnName = "IPIAmount";
			zCalcEditColumnStyleInfo13.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo19.ColumnName = "IPISpecialRateUQ";
			zTextBoxColumnStyleInfo19.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo14.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo14.ColumnName = "IPISpecialRateQuantity";
			zCalcEditColumnStyleInfo14.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo15.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo15.ColumnName = "IPISpecialRateAmount";
			zCalcEditColumnStyleInfo15.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo20.ColumnName = "PISCofinsTaxRegime";
			zTextBoxColumnStyleInfo20.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zCalcEditColumnStyleInfo16.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo16.ColumnName = "PISBaseAmount";
			zCalcEditColumnStyleInfo16.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo17.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo17.ColumnName = "PISRate";
			zCalcEditColumnStyleInfo17.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo18.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo18.ColumnName = "PISAmount";
			zCalcEditColumnStyleInfo18.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo21.ColumnName = "PISSpecialRateUQ";
			zTextBoxColumnStyleInfo21.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo21.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo19.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo19.ColumnName = "PISSpecialRateQuantity";
			zCalcEditColumnStyleInfo19.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo20.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo20.ColumnName = "PISSpecialRateAmount";
			zCalcEditColumnStyleInfo20.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo21.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo21.ColumnName = "CofinsBaseAmount";
			zCalcEditColumnStyleInfo21.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo21.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			zCalcEditColumnStyleInfo22.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo22.ColumnName = "CofinsRate";
			zCalcEditColumnStyleInfo22.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo23.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo23.ColumnName = "CofinsAmount";
			zCalcEditColumnStyleInfo23.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo22.ColumnName = "CofinsSpecialRateUQ";
			zTextBoxColumnStyleInfo22.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo24.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo24.ColumnName = "CofinsSpecialRateQuantity";
			zCalcEditColumnStyleInfo24.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo25.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo25.ColumnName = "CofinsSpecialRateAmount";
			zCalcEditColumnStyleInfo25.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo25.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo23.ColumnName = "ICMSTaxRegime";
			zTextBoxColumnStyleInfo23.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo26.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo26.ColumnName = "ICMSBaseAmount";
			zCalcEditColumnStyleInfo26.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo26.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo27.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo27.ColumnName = "ICMSRate";
			zCalcEditColumnStyleInfo27.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo27.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCalcEditColumnStyleInfo28.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo28.ColumnName = "ICMSReductionPercentage";
			zCalcEditColumnStyleInfo28.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo28.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(125);
			zCalcEditColumnStyleInfo29.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo29.ColumnName = "IcmsTotalAmountReduction";
			zCalcEditColumnStyleInfo29.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo29.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zCalcEditColumnStyleInfo30.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo30.ColumnName = "ICMSAmount";
			zCalcEditColumnStyleInfo30.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo30.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo31.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo31.ColumnName = "FCPRate";
			zCalcEditColumnStyleInfo31.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo31.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo32.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo32.ColumnName = "FCPAmount";
			zCalcEditColumnStyleInfo32.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo32.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo24.ColumnName = "ICMSLegalBase";
			zTextBoxColumnStyleInfo24.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo33.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo33.ColumnName = "SiscomexUsageFee";
			zCalcEditColumnStyleInfo33.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo33.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo34.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo34.ColumnName = "AntidumpingBaseAmount";
			zCalcEditColumnStyleInfo34.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo34.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(140);
			zCalcEditColumnStyleInfo35.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo35.ColumnName = "AntidumpingRate";
			zCalcEditColumnStyleInfo35.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo35.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zCalcEditColumnStyleInfo36.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo36.ColumnName = "AntidumpingAmount";
			zCalcEditColumnStyleInfo36.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo36.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			zTextBoxColumnStyleInfo25.ColumnName = "AntidumpingSpecialRateUQ";
			zTextBoxColumnStyleInfo25.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo25.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo37.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo37.ColumnName = "AntidumpingSpecialRateQuantity";
			zCalcEditColumnStyleInfo37.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo37.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo38.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo38.ColumnName = "AntidumpingSpecialRateAmount";
			zCalcEditColumnStyleInfo38.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo38.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zCalcEditColumnStyleInfo39.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo39.ColumnName = "AfrmmAmount";
			zCalcEditColumnStyleInfo39.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo39.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo40.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo40.ColumnName = "ImportLicenseFineAmount";
			zCalcEditColumnStyleInfo40.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo40.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zCalcEditColumnStyleInfo41.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo41.ColumnName = "EICAmount";
			zCalcEditColumnStyleInfo41.DefaultCollectionIndex = 0;
			zCalcEditColumnStyleInfo41.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo26.ColumnName = "OrderNumber";
			zTextBoxColumnStyleInfo26.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo26.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo27.ColumnName = "OrderLineNumberAndSubLine";
			zTextBoxColumnStyleInfo27.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo27.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo28.ColumnName = "ConcessionActNumber";
			zTextBoxColumnStyleInfo28.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo28.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(200);
			zTextBoxColumnStyleInfo29.ColumnName = "Permits";
			zTextBoxColumnStyleInfo29.DefaultCollectionIndex = 0;
			zTextBoxColumnStyleInfo29.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			zMultiLineTextBoxColumnInfo1.ColumnName = "Complement";
			zMultiLineTextBoxColumnInfo1.DefaultCollectionIndex = 0;
			zMultiLineTextBoxColumnInfo1.MinimumEditControlWidth = 300;
			zMultiLineTextBoxColumnInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo13);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo9);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo10);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo18);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo11);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo12);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo13);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo19);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo14);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo15);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo20);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo16);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo17);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo18);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo21);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo19);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo20);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo21);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo22);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo23);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo22);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo24);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo25);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo23);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo26);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo27);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo28);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo29);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo30);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo31);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo32);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo24);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo33);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo34);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo35);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo36);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo25);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo37);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo38);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo39);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo40);
			this.LinesGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo41);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo26);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo27);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo28);
			this.LinesGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo29);
			this.LinesGrid.ColumnStyles.Add(zMultiLineTextBoxColumnInfo1);
			this.LinesGrid.Dock = System.Windows.Forms.DockStyle.Fill;
			this.LinesGrid.GridId = "1e8dd666-fcd2-49cf-8335-b968acb4f991";
			this.LinesGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.LinesGrid.LayoutKey = "LinesGrid";
			this.LinesGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(3, 16, true);
			this.LinesGrid.Name = "LinesGrid";
			this.LinesGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(686, 345, true);
			this.LinesGrid.TabIndex = 0;
			// 
			// ExportDataButton
			// 
			this.ExportDataButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
			this.ExportDataButton.CaptionResourceString = Enterprise.Customs.BR.GUI.Res.GetData("d3e2c8dc-20c6-4a81-b93b-3b37d02aaae2", "Export Data");
			this.ExportDataButton.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(525, 6, true);
			this.ExportDataButton.Name = "ExportDataButton";
			this.ExportDataButton.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(75, 23, true);
			this.ExportDataButton.TabIndex = 12;
			this.ExportDataButton.ToolTipCaption = null;
			this.ExportDataButton.UseVisualStyleBackColor = true;
			this.ExportDataButton.Click += new System.EventHandler(this.ExportDataButton_Click);
			// 
			// ButtonsPanel
			// 
			this.ButtonsPanel.Controls.Add(this.ExportDataButton);
			this.ButtonsPanel.Controls.Add(this.CloseButton);
			this.ButtonsPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.ButtonsPanel.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 517, true);
			this.ButtonsPanel.Name = "ButtonsPanel";
			this.ButtonsPanel.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(692, 35, true);
			this.ButtonsPanel.TabIndex = 11;
			// 
			// SaveFileDialog
			// 
			this.SaveFileDialog.AddExtension = true;
			this.SaveFileDialog.CheckFileExists = false;
			this.SaveFileDialog.CheckPathExists = true;
			this.SaveFileDialog.CreatePrompt = false;
			this.SaveFileDialog.DefaultExt = "xls";
			this.SaveFileDialog.DereferenceLinks = true;
			this.SaveFileDialog.Filter = "Excel files (*.xls;*.xlsx)|*.xls;*.xlsx";
			this.SaveFileDialog.FilterIndex = 1;
			this.SaveFileDialog.InitialDirectory = "";
			this.SaveFileDialog.OverwritePrompt = true;
			this.SaveFileDialog.RestoreDirectory = false;
			this.SaveFileDialog.ShowHelp = false;
			this.SaveFileDialog.SupportMultiDottedExtensions = false;
			this.SaveFileDialog.Title = "";
			this.SaveFileDialog.ValidateNames = true;
			// 
			// NFeExportForm
			// 
			this.AutoAddPreviousNextButtons = false;
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
			this.CancelButton = this.CloseButton;
			this.CaptionRenderingEnabled = true;
			this.CaptionResourceString = Enterprise.Customs.BR.GUI.Res.GetData("1d270fad-0c4f-4aed-888c-04167e27801a", "Data Output Wizard");
			this.ClientSize = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(692, 576, true);
			this.Controls.Add(this.LinesGroupBox);
			this.Controls.Add(this.ButtonsPanel);
			this.Controls.Add(this.HeaderGroupBox);
			this.DataSourceType = typeof(Enterprise.Customs.BR.Business.NFeExportObject);
			this.MinimumSize = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(577, 443, true);
			this.Name = "NFeExportForm";
			this.ShowInTaskbar = false;
			this.Controls.SetChildIndex(this.HeaderGroupBox, 0);
			this.Controls.SetChildIndex(this.MainStatusBar, 0);
			this.Controls.SetChildIndex(this.ButtonsPanel, 0);
			this.Controls.SetChildIndex(this.LinesGroupBox, 0);
			((System.ComponentModel.ISupportInitialize)(this.MessageStatusBarPanel)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.ErrorStatusBarPanel)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.HeaderGroupBox.ResumeLayout(false);
			this.HeaderGroupBox.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.HeaderGrid)).EndInit();
			this.HeaderGrid.ResumeLayout(false);
			this.HeaderGrid.PerformLayout();
			this.LinesGroupBox.ResumeLayout(false);
			this.LinesGroupBox.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.LinesGrid)).EndInit();
			this.LinesGrid.ResumeLayout(false);
			this.LinesGrid.PerformLayout();
			this.ButtonsPanel.ResumeLayout(false);
			this.ButtonsPanel.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();

		}

		#endregion

		internal Enterprise.ZArchitecture.GUI.ZButton CloseButton;
		internal ZArchitecture.GUI.ZGroupBox HeaderGroupBox;
		internal ZArchitecture.ZGrid HeaderGrid;
		internal ZArchitecture.GUI.ZGroupBox LinesGroupBox;
		internal ZArchitecture.ZGrid LinesGrid;
		internal ZArchitecture.GUI.ZButton ExportDataButton;
		internal ZArchitecture.GUI.ZPanel ButtonsPanel;
		internal Enterprise.ZArchitecture.GUI.ZSaveFileDialog SaveFileDialog;
	}
}
