//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Universal
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoCusRefTradeGroupViewValidation : ZValidation
	{
		protected AutoCusRefTradeGroupViewValidation(AutoCusRefTradeGroupView Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoCusRefTradeGroupViewValidation); }
		}

		/// <summary>
		/// Add more validation to the CusRefTradeGroupView's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoCusRefTradeGroupViewValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The CusRefTradeGroupView's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoCusRefTradeGroupViewValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region ZZA_DataSet

		public void ValidateZZA_DataSet()
		{
			ZValidationInternals.Validate(Parent.ZZA_DataSetInfo, GetZZA_DataSetValidationInvoker());
		}

		RunValidationInvoker GetZZA_DataSetValidationInvoker()
		{
			return delegate
			{
				CheckZZA_DataSetIsNotEmpty();
				CheckZZA_DataSetIsWesternEuropean();
				CheckZZA_DataSet();
			};
		}

		protected virtual void CheckZZA_DataSetIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_DataSetInfo);
		}

		protected virtual void CheckZZA_DataSetIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZA_DataSetInfo);
		}

		protected virtual void CheckZZA_DataSet()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_Description

		public void ValidateZZA_Description()
		{
			ZValidationInternals.Validate(Parent.ZZA_DescriptionInfo, GetZZA_DescriptionValidationInvoker());
		}

		RunValidationInvoker GetZZA_DescriptionValidationInvoker()
		{
			return delegate
			{
				CheckZZA_DescriptionIsNotEmpty();
				CheckZZA_Description();
			};
		}

		protected virtual void CheckZZA_DescriptionIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_DescriptionInfo);
		}

		protected virtual void CheckZZA_Description()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_EndDate

		public void ValidateZZA_EndDate()
		{
			ZValidationInternals.Validate(Parent.ZZA_EndDateInfo, GetZZA_EndDateValidationInvoker());
		}

		RunValidationInvoker GetZZA_EndDateValidationInvoker()
		{
			return delegate
			{
				CheckZZA_EndDateIsNotEmpty();
				CheckZZA_EndDateIsValidZDateTime();
				CheckZZA_EndDateIsValidZDateTimeRange();
				CheckZZA_EndDate();
			};
		}

		protected virtual void CheckZZA_EndDateIsValidZDateTime()
		{
			TypeValidation.CheckValidSmallDateTime(Parent.ZZA_EndDateInfo);
		}

		protected virtual void CheckZZA_EndDateIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_EndDateInfo);
		}

		protected virtual void CheckZZA_EndDateIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.ZZA_EndDateInfo);
		}

		protected virtual void CheckZZA_EndDate()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_IsSystem

		public void ValidateZZA_IsSystem()
		{
			ZValidationInternals.Validate(Parent.ZZA_IsSystemInfo, GetZZA_IsSystemValidationInvoker());
		}

		RunValidationInvoker GetZZA_IsSystemValidationInvoker()
		{
			return delegate
			{
				CheckZZA_IsSystem();
			};
		}

		protected virtual void CheckZZA_IsSystem()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_StartDate

		public void ValidateZZA_StartDate()
		{
			ZValidationInternals.Validate(Parent.ZZA_StartDateInfo, GetZZA_StartDateValidationInvoker());
		}

		RunValidationInvoker GetZZA_StartDateValidationInvoker()
		{
			return delegate
			{
				CheckZZA_StartDateIsNotEmpty();
				CheckZZA_StartDateIsValidZDateTime();
				CheckZZA_StartDateIsValidZDateTimeRange();
				CheckZZA_StartDate();
			};
		}

		protected virtual void CheckZZA_StartDateIsValidZDateTime()
		{
			TypeValidation.CheckValidSmallDateTime(Parent.ZZA_StartDateInfo);
		}

		protected virtual void CheckZZA_StartDateIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_StartDateInfo);
		}

		protected virtual void CheckZZA_StartDateIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.ZZA_StartDateInfo);
		}

		protected virtual void CheckZZA_StartDate()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_TradeGroup

		public void ValidateZZA_TradeGroup()
		{
			ZValidationInternals.Validate(Parent.ZZA_TradeGroupInfo, GetZZA_TradeGroupValidationInvoker());
		}

		RunValidationInvoker GetZZA_TradeGroupValidationInvoker()
		{
			return delegate
			{
				CheckZZA_TradeGroupIsNotEmpty();
				CheckZZA_TradeGroupIsWesternEuropean();
				CheckZZA_TradeGroup();
			};
		}

		protected virtual void CheckZZA_TradeGroupIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_TradeGroupInfo);
		}

		protected virtual void CheckZZA_TradeGroupIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZA_TradeGroupInfo);
		}

		protected virtual void CheckZZA_TradeGroup()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZA_ZZZ_NKDataGrouping

		public void ValidateZZA_ZZZ_NKDataGrouping()
		{
			ZValidationInternals.Validate(Parent.ZZA_ZZZ_NKDataGroupingInfo, GetZZA_ZZZ_NKDataGroupingValidationInvoker());
		}

		RunValidationInvoker GetZZA_ZZZ_NKDataGroupingValidationInvoker()
		{
			return delegate
			{
				CheckZZA_ZZZ_NKDataGroupingIsNotEmpty();
				CheckZZA_ZZZ_NKDataGroupingIsWesternEuropean();
				CheckZZA_ZZZ_NKDataGrouping();
			};
		}

		protected virtual void CheckZZA_ZZZ_NKDataGroupingIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZA_ZZZ_NKDataGroupingInfo);
		}

		protected virtual void CheckZZA_ZZZ_NKDataGroupingIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZA_ZZZ_NKDataGroupingInfo);
		}

		protected virtual void CheckZZA_ZZZ_NKDataGrouping()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateZZA_DataSet();
				ValidateZZA_Description();
				ValidateZZA_EndDate();
				ValidateZZA_IsSystem();
				ValidateZZA_StartDate();
				ValidateZZA_TradeGroup();
				ValidateZZA_ZZZ_NKDataGrouping();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoCusRefTradeGroupView Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
