<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="Enterprise.DbUpgrader.Resource" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Version\Enterprise.DbUpgrader.Resource.Version.csproj" />
  </ItemGroup>
</Project>