<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Staging.NewSchedulers.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Staging.NewSchedulers.Test</AssemblyName>
    <OutputPath>..\..\..\Bin\Staging\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.ProcessorRunner">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.ProcessorRunner.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schedulers.Common">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Schedulers.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="TestConfiguration\TestJobs.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewSchedulers\NewSchedulers.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
