<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.MailManager.Integration</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Microsoft.Identity.Client" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>