<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Staging.DbUpgrader</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Staging.DbUpgrader</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>Debug;Release;UAT</Configurations>
    <OutputPath>..\..\..\Bin\Staging\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.DbUpgrade">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.DbUpgrade.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.ErrorReporting">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.ErrorReporting.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DataFiles\Country_names.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DataFiles\Currencies.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CargoWise.RefDbRepo.Staging.DbUpgrader.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ShelfCheckinDataTransformationMapper.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ShelfCheckinPreUpgradeTransformationMapper.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>