using CargoWise.EntityFramework;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.GUI;

namespace Enterprise.Freight.Forwarding.Module
{
	public partial class PackLinesFilterControl : ZFilterStripControl
	{
		void InitializeComponent()
		{
			ZArchitecture.ZTextBoxColumnStyleInfo packlineIDTextColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo packageCountTextColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo packageTypeDropEditColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZGuidDropEditColumnStyleInfo containerDropEditColumnStyleInfo = new ZGuidDropEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo linePriceColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo actualWeightColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo actualWeightUQColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo actualVolumeColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo actualVolumeUQColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo loadingMetersColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo itemNumberColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo endItemNumberColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo lengthColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo widthColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo heightColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo unitOfDimensionColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo outturnColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo outturnedWeightColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo outturnedVolumeColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZMultiLineTextBoxColumnInfo outturnCommentColumnStyleInfo = new ZMultiLineTextBoxColumnInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo pillagedColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo damagedColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo refNumberColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo inspectionTypeCodeColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo descriptionColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo originColumnStyleInfo = new ZCodeFindBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo commodityCodeColumnStyleInfo = new ZCodeFindBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo nmfcColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZMultiLineTextBoxColumnInfo detailedDescriptionColumnStyleInfo = new ZMultiLineTextBoxColumnInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo containerPackingOrderColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo exportRefNumberColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo vehicleMakeColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo vehicleModelColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo vehicleYearColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo vehicleColorColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo importRefNumberColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo vehicleNumberOfDoorsColumnStyleInfo = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo vehicleTransmissionColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo marksAndNumbersColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo departureTransitWarehouseExcludedColumnStyleInfo = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo originTransitWarehouseStatusColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo lastKnownTransitWarehouseStatusColumnStyleInfo = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo lastKnownWarehouseStatusDateTimeColumnStyleInfo = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo lastKnownTransitWarehouseColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();

			packlineIDTextColumnStyleInfo.CaptionResourceString = Enterprise.Freight.Forwarding.Module.Res.GetData("0586461b-043a-178a-4a4c-318556718ec3", "Pack Line Id");
			packlineIDTextColumnStyleInfo.ColumnName = "JL_PackLineID";
			packlineIDTextColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			packlineIDTextColumnStyleInfo.IsReadOnly = true;
			packageCountTextColumnStyleInfo.ColumnName = "JL_PackageCount";
			packageCountTextColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			packageCountTextColumnStyleInfo.IsReadOnly = true;
			packageCountTextColumnStyleInfo.Decimals = 0;
			packageCountTextColumnStyleInfo.IsMandatory = true;
			packageCountTextColumnStyleInfo.MaxValue = 1000000;
			packageTypeDropEditColumnStyleInfo.ColumnName = "JL_F3_NKPackType";
			packageTypeDropEditColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			packageTypeDropEditColumnStyleInfo.IsReadOnly = true;
			containerDropEditColumnStyleInfo.ColumnName = "JL_JC";
			containerDropEditColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			containerDropEditColumnStyleInfo.IsReadOnly = true;
			linePriceColumnStyleInfo.BindToDecimalPlaces = null;
			linePriceColumnStyleInfo.ColumnName = "JL_LinePrice";
			linePriceColumnStyleInfo.IsVisible = false;
			linePriceColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			actualWeightColumnStyleInfo.BindToDecimalPlaces = null;
			actualWeightColumnStyleInfo.ColumnName = "JL_ActualWeight";
			actualWeightColumnStyleInfo.IsMandatory = true;
			actualWeightColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			actualWeightUQColumnStyleInfo.ColumnName = "JL_ActualWeightUQ";
			actualWeightUQColumnStyleInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			actualWeightUQColumnStyleInfo.IsVisible = false;
			actualWeightUQColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			actualVolumeColumnStyleInfo.BindToDecimalPlaces = null;
			actualVolumeColumnStyleInfo.ColumnName = "JL_ActualVolume";
			actualVolumeColumnStyleInfo.IsMandatory = true;
			actualVolumeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			actualVolumeUQColumnStyleInfo.ColumnName = "JL_ActualVolumeUQ";
			actualVolumeUQColumnStyleInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			actualVolumeUQColumnStyleInfo.IsVisible = false;
			actualVolumeUQColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			loadingMetersColumnStyleInfo.BindToDecimalPlaces = null;
			loadingMetersColumnStyleInfo.ColumnName = "JL_LoadingMeters";
			loadingMetersColumnStyleInfo.Decimals = 3;
			loadingMetersColumnStyleInfo.IsVisible = false;
			loadingMetersColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			itemNumberColumnStyleInfo.BindToDecimalPlaces = null;
			itemNumberColumnStyleInfo.ColumnName = "JL_ItemNo";
			itemNumberColumnStyleInfo.Decimals = 0;
			itemNumberColumnStyleInfo.IsVisible = false;
			itemNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(55);
			endItemNumberColumnStyleInfo.BindToDecimalPlaces = null;
			endItemNumberColumnStyleInfo.ColumnName = "JL_EndItemNo";
			endItemNumberColumnStyleInfo.Decimals = 0;
			endItemNumberColumnStyleInfo.IsVisible = false;
			endItemNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(55);
			lengthColumnStyleInfo.BindToDecimalPlaces = null;
			lengthColumnStyleInfo.ColumnName = "JL_Length";
			lengthColumnStyleInfo.IsVisible = false;
			lengthColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			widthColumnStyleInfo.BindToDecimalPlaces = null;
			widthColumnStyleInfo.ColumnName = "JL_Width";
			widthColumnStyleInfo.IsVisible = false;
			widthColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			heightColumnStyleInfo.BindToDecimalPlaces = null;
			heightColumnStyleInfo.ColumnName = "JL_Height";
			heightColumnStyleInfo.IsVisible = false;
			heightColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			unitOfDimensionColumnStyleInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			unitOfDimensionColumnStyleInfo.ColumnName = "JL_UnitOfDimension";
			unitOfDimensionColumnStyleInfo.IsVisible = false;
			unitOfDimensionColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			outturnColumnStyleInfo.BindToDecimalPlaces = null;
			outturnColumnStyleInfo.ColumnName = "JL_Outturn";
			outturnColumnStyleInfo.Decimals = 0;
			outturnColumnStyleInfo.IsVisible = false;
			outturnColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			outturnedWeightColumnStyleInfo.BindToDecimalPlaces = null;
			outturnedWeightColumnStyleInfo.ColumnName = "JL_OutturnedWeight";
			outturnedWeightColumnStyleInfo.IsVisible = false;
			outturnedWeightColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			outturnedVolumeColumnStyleInfo.BindToDecimalPlaces = null;
			outturnedVolumeColumnStyleInfo.ColumnName = "JL_OutturnedVolume";
			outturnedVolumeColumnStyleInfo.IsVisible = false;
			outturnedVolumeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			outturnCommentColumnStyleInfo.ColumnName = "JL_OutturnComment";
			outturnCommentColumnStyleInfo.IsVisible = false;
			outturnCommentColumnStyleInfo.MinimumEditControlWidth = 300;
			outturnCommentColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(180);
			pillagedColumnStyleInfo.BindToDecimalPlaces = null;
			pillagedColumnStyleInfo.ColumnName = "JL_Pillaged";
			pillagedColumnStyleInfo.Decimals = 0;
			pillagedColumnStyleInfo.IsVisible = false;
			pillagedColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			damagedColumnStyleInfo.BindToDecimalPlaces = null;
			damagedColumnStyleInfo.ColumnName = "JL_Damaged";
			damagedColumnStyleInfo.Decimals = 0;
			damagedColumnStyleInfo.IsVisible = false;
			damagedColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(52);
			refNumberColumnStyleInfo.ColumnName = "JL_RefNumber";
			refNumberColumnStyleInfo.IsVisible = false;
			refNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			inspectionTypeCodeColumnStyleInfo.CaptionResourceString = Enterprise.Freight.Forwarding.Module.Res.GetData("914d7066-c1cf-748f-40cc-d9242e675e23", "Inspection");
			inspectionTypeCodeColumnStyleInfo.ColumnName = "JL_InspectionTypeCode";
			inspectionTypeCodeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			descriptionColumnStyleInfo.ColumnName = "JL_Description";
			descriptionColumnStyleInfo.IsVisible = false;
			descriptionColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			originColumnStyleInfo.ColumnName = "JL_RN_NKOrigin";
			originColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			commodityCodeColumnStyleInfo.ColumnName = "JL_RH_NKCommodityCode";
			commodityCodeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			nmfcColumnStyleInfo.ColumnName = "CommodityCode+RH_FN_NKNMFC";
			nmfcColumnStyleInfo.IsReadOnly = true;
			nmfcColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			detailedDescriptionColumnStyleInfo.ColumnName = "JL_DetailedDescription";
			detailedDescriptionColumnStyleInfo.IsVisible = false;
			detailedDescriptionColumnStyleInfo.MinimumEditControlWidth = 300;
			detailedDescriptionColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			containerPackingOrderColumnStyleInfo.BindToDecimalPlaces = null;
			containerPackingOrderColumnStyleInfo.ColumnName = "JL_ContainerPackingOrder";
			containerPackingOrderColumnStyleInfo.Decimals = 0;
			containerPackingOrderColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(55);
			exportRefNumberColumnStyleInfo.ColumnName = "JL_ExportRefNumber";
			exportRefNumberColumnStyleInfo.IsVisible = false;
			exportRefNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			vehicleMakeColumnStyleInfo.ColumnName = "JL_VehicleMake";
			vehicleMakeColumnStyleInfo.IsVisible = false;
			vehicleMakeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			vehicleModelColumnStyleInfo.ColumnName = "JL_VehicleModel";
			vehicleModelColumnStyleInfo.IsVisible = false;
			vehicleModelColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			vehicleYearColumnStyleInfo.BindToDecimalPlaces = null;
			vehicleYearColumnStyleInfo.ColumnName = "JL_VehicleYear";
			vehicleYearColumnStyleInfo.IsVisible = false;
			vehicleYearColumnStyleInfo.ShowGroupSeparators = false;
			vehicleYearColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			vehicleColorColumnStyleInfo.ColumnName = "JL_VehicleColor";
			vehicleColorColumnStyleInfo.IsVisible = false;
			vehicleColorColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			importRefNumberColumnStyleInfo.ColumnName = "JL_ImportRefNumber";
			importRefNumberColumnStyleInfo.IsVisible = false;
			importRefNumberColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			vehicleNumberOfDoorsColumnStyleInfo.BindToDecimalPlaces = null;
			vehicleNumberOfDoorsColumnStyleInfo.ColumnName = "JL_VehicleNumberOfDoors";
			vehicleNumberOfDoorsColumnStyleInfo.IsVisible = false;
			vehicleNumberOfDoorsColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			vehicleTransmissionColumnStyleInfo.ColumnName = "JL_VehicleTransmission";
			vehicleTransmissionColumnStyleInfo.IsVisible = false;
			vehicleTransmissionColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			marksAndNumbersColumnStyleInfo.ColumnName = "JL_MarksAndNumbers";
			marksAndNumbersColumnStyleInfo.IsVisible = false;
			marksAndNumbersColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			departureTransitWarehouseExcludedColumnStyleInfo.ColumnName = "JL_DepartureTransitWarehouseExcluded";
			departureTransitWarehouseExcludedColumnStyleInfo.IsVisible = false;
			departureTransitWarehouseExcludedColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			originTransitWarehouseStatusColumnStyleInfo.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			originTransitWarehouseStatusColumnStyleInfo.ColumnName = "JL_OriginTransitWarehouseStatus";
			originTransitWarehouseStatusColumnStyleInfo.IsVisible = false;
			originTransitWarehouseStatusColumnStyleInfo.IsReadOnly = true;
			originTransitWarehouseStatusColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			lastKnownTransitWarehouseStatusColumnStyleInfo.ColumnName = "JL_LastKnownTransitWarehouseStatus";
			lastKnownTransitWarehouseStatusColumnStyleInfo.IsVisible = false;
			lastKnownTransitWarehouseStatusColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			lastKnownWarehouseStatusDateTimeColumnStyleInfo.ColumnName = "JL_LastKnownTransitWarehouseStatusDateTime";
			lastKnownWarehouseStatusDateTimeColumnStyleInfo.IsVisible = false;
			lastKnownWarehouseStatusDateTimeColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			lastKnownTransitWarehouseColumnStyleInfo.ColumnName = "LastKnownTransitWarehouseAddress.Header.OH_Code";
			lastKnownTransitWarehouseColumnStyleInfo.CaptionResourceString = Enterprise.Freight.Forwarding.Module.Res.GetData("70370a45-c783-7d90-46e5-87a3565e1a02", "Last Known Transit Warehouse");
			lastKnownTransitWarehouseColumnStyleInfo.IsVisible = false;
			lastKnownTransitWarehouseColumnStyleInfo.IsReadOnly = true;
			lastKnownTransitWarehouseColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);

			this.grid.ColumnStyles.Add(packlineIDTextColumnStyleInfo);
			this.grid.ColumnStyles.Add(packageCountTextColumnStyleInfo);
			this.grid.ColumnStyles.Add(packageTypeDropEditColumnStyleInfo);
			this.grid.ColumnStyles.Add(containerDropEditColumnStyleInfo);
			this.grid.ColumnStyles.Add(linePriceColumnStyleInfo);
			this.grid.ColumnStyles.Add(actualWeightColumnStyleInfo);
			this.grid.ColumnStyles.Add(actualWeightUQColumnStyleInfo);
			this.grid.ColumnStyles.Add(actualVolumeColumnStyleInfo);
			this.grid.ColumnStyles.Add(actualVolumeUQColumnStyleInfo);
			this.grid.ColumnStyles.Add(loadingMetersColumnStyleInfo);
			this.grid.ColumnStyles.Add(itemNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(endItemNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(lengthColumnStyleInfo);
			this.grid.ColumnStyles.Add(widthColumnStyleInfo);
			this.grid.ColumnStyles.Add(heightColumnStyleInfo);
			this.grid.ColumnStyles.Add(unitOfDimensionColumnStyleInfo);
			this.grid.ColumnStyles.Add(outturnColumnStyleInfo);
			this.grid.ColumnStyles.Add(outturnedWeightColumnStyleInfo);
			this.grid.ColumnStyles.Add(outturnedVolumeColumnStyleInfo);
			this.grid.ColumnStyles.Add(outturnCommentColumnStyleInfo);
			this.grid.ColumnStyles.Add(pillagedColumnStyleInfo);
			this.grid.ColumnStyles.Add(damagedColumnStyleInfo);
			this.grid.ColumnStyles.Add(refNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(inspectionTypeCodeColumnStyleInfo);
			this.grid.ColumnStyles.Add(descriptionColumnStyleInfo);
			this.grid.ColumnStyles.Add(originColumnStyleInfo);
			this.grid.ColumnStyles.Add(commodityCodeColumnStyleInfo);
			this.grid.ColumnStyles.Add(nmfcColumnStyleInfo);
			this.grid.ColumnStyles.Add(detailedDescriptionColumnStyleInfo);
			this.grid.ColumnStyles.Add(containerPackingOrderColumnStyleInfo);
			this.grid.ColumnStyles.Add(exportRefNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleMakeColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleModelColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleYearColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleColorColumnStyleInfo);
			this.grid.ColumnStyles.Add(importRefNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleNumberOfDoorsColumnStyleInfo);
			this.grid.ColumnStyles.Add(vehicleTransmissionColumnStyleInfo);
			this.grid.ColumnStyles.Add(marksAndNumbersColumnStyleInfo);
			this.grid.ColumnStyles.Add(departureTransitWarehouseExcludedColumnStyleInfo);
			this.grid.ColumnStyles.Add(originTransitWarehouseStatusColumnStyleInfo);
			this.grid.ColumnStyles.Add(lastKnownTransitWarehouseStatusColumnStyleInfo);
			this.grid.ColumnStyles.Add(lastKnownWarehouseStatusDateTimeColumnStyleInfo);
			this.grid.ColumnStyles.Add(lastKnownTransitWarehouseColumnStyleInfo);

			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();

			this.grid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 3, true);
			this.grid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(758, 592, true);

			// 
			// PackLinesFilterControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Name = "PackLinesFilterControl";
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(758, 595, true);
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
	}
}
