<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0018;SYSLIB0050;SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="AppDomainWrappers.Net" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data.Test" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection.TestFramework" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Licensing" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Reflection" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.DocumentScanning.Integration" />
    <Reference Include="Microsoft.Extensions.Logging.Abstractions" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Semaphores.Common.Test" />
    <Reference Include="CargoWise.Async" />
    <Reference Include="CargoWise.BrandManager" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Macros" />
    <Reference Include="CargoWise.Organizations.PatternMatching" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="BuildTools" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CryptoUtilities" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.NumberFountain" />
    <Reference Include="Enterprise.RemoteDesktopServices.Shared" />
    <Reference Include="Enterprise.Semaphores.Common" />
    <Reference Include="Enterprise.Semaphores.Common.Test" />
    <Reference Include="Enterprise.Upgrades" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="MailManager.Integration" />
    <Reference Include="ICSharpCode.SharpZipLib" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="Resources" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="System.IdentityModel.Tokens.Jwt" />    
    <Reference Include="WTG.DevTools.Common" />
    <Reference Include="WTG.DevTools.Definitions" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
    <Reference Include="CargoWise.Common.Testing" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="Microsoft.SqlServer.Types" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="WTG.ErrorReporting" />
    <Reference Include="CargoWise.ResourceStrings.Cache.Test" />
    <Reference Include="Enterprise.DbUpgrader.Shared.Testing" />
    <Reference Include="Enterprise.ZArchitecture.Modules.Testing" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Runtime.Caching" />
    <PackageReference Include="System.ServiceModel.Primitives" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="Microsoft.JScript" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Diagnostics.DiagnosticSource" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
    <Reference Include="System.Text.Json" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Utilities\TestFiles\*.rtf" />
    <None Remove="ErrorReporting\Testing\*.zip" />
    <EmbeddedResource Include="AssemblyMetaData\TestFiles\*.xml" />
    <EmbeddedResource Include="Environment\Email\TestFiles\TestHtml2Text.htm" />
    <EmbeddedResource Include="Utilities\TestFiles\*.rtf" />
    <EmbeddedResource Include="ErrorReporting\Testing\*.zip" />
    <EmbeddedResource Include="Testing\DbCommitTrackerExemptionBaseline.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Enterprise.ZArchitecture.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Baseline\DBDeprecatedFeatureBaseline.txt">
      <LogicalName>DBDeprecatedFeatureBaseline.txt</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Testing\DummyConfig.xml">
      <LogicalName>DummyConfig.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>