//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.LandedCosting.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoLandedLineCostItemValidation : ZValidation
	{
		protected AutoLandedLineCostItemValidation(AutoLandedLineCostItem Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoLandedLineCostItemValidation); }
		}

		/// <summary>
		/// Add more validation to the LandedLineCostItem's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoLandedLineCostItemValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The LandedLineCostItem's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoLandedLineCostItemValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region LZ_ClusterKey

		public void ValidateLZ_ClusterKey()
		{
			ZValidationInternals.Validate(Parent.LZ_ClusterKeyInfo, GetLZ_ClusterKeyValidationInvoker());
		}

		RunValidationInvoker GetLZ_ClusterKeyValidationInvoker()
		{
			return delegate
			{
				CheckLZ_ClusterKey();
			};
		}

		protected virtual void CheckLZ_ClusterKey()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region LZ_CostAmount

		public void ValidateLZ_CostAmount()
		{
			ZValidationInternals.Validate(Parent.LZ_CostAmountInfo, GetLZ_CostAmountValidationInvoker());
		}

		RunValidationInvoker GetLZ_CostAmountValidationInvoker()
		{
			return delegate
			{
				CheckLZ_CostAmountIsValidMoney();
				CheckLZ_CostAmount();
			};
		}

		protected virtual void CheckLZ_CostAmountIsValidMoney()
		{
			TypeValidation.CheckValidMoney(Parent.LZ_CostAmountInfo, 19, 4);
		}

		protected virtual void CheckLZ_CostAmount()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region LZ_CostType

		public void ValidateLZ_CostType()
		{
			ZValidationInternals.Validate(Parent.LZ_CostTypeInfo, GetLZ_CostTypeValidationInvoker());
		}

		RunValidationInvoker GetLZ_CostTypeValidationInvoker()
		{
			return delegate
			{
				CheckLZ_CostTypeIsWesternEuropean();
				CheckLZ_CostType();
			};
		}

		protected virtual void CheckLZ_CostTypeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.LZ_CostTypeInfo);
		}

		protected virtual void CheckLZ_CostType()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region LZ_LH

		public void ValidateLZ_LH()
		{
			ZValidationInternals.Validate(Parent.LZ_LHInfo, GetLZ_LHValidationInvoker());
		}

		RunValidationInvoker GetLZ_LHValidationInvoker()
		{
			return delegate
			{
				CheckLZ_LHIsNotEmpty();
				CheckLZ_LHIsValidZGuid();
				CheckLZ_LH();
			};
		}

		protected virtual void CheckLZ_LHIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.LZ_LHInfo);
		}

		protected virtual void CheckLZ_LHIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.LZ_LHInfo);
		}

		protected virtual void CheckLZ_LH()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateLZ_ClusterKey();
				ValidateLZ_CostAmount();
				ValidateLZ_CostType();
				ValidateLZ_LH();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoLandedLineCostItem Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
