//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from ValueAnalysisTradeStatusList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.MarketingManager.Module
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class ValueAnalysisTradeStatusList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string EstimateActivePipelinePa_Status = "ACT";
			public const string EstimateSuccessfulCommittedPa_Status = "SUC";
			public const string EstimateUnsuccessfulPa_Status = "UNS";
			public const string TradedIs_Traded = "TRA";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString EstimateActivePipelinePa_Status { get { return ResString.GetMultilingualString("ValueAnalysisTradeStatusList|EstimateActivePipelinePa_Status", "Estimate Active/Pipeline (PA_Status)"); } }
			public static MultilingualString EstimateSuccessfulCommittedPa_Status { get { return ResString.GetMultilingualString("ValueAnalysisTradeStatusList|EstimateSuccessfulCommittedPa_Status", "Estimate Successful/Committed (PA_Status)"); } }
			public static MultilingualString EstimateUnsuccessfulPa_Status { get { return ResString.GetMultilingualString("ValueAnalysisTradeStatusList|EstimateUnsuccessfulPa_Status", "Estimate Unsuccessful (PA_Status)"); } }
			public static MultilingualString TradedIs_Traded { get { return ResString.GetMultilingualString("ValueAnalysisTradeStatusList|TradedIs_Traded", "Traded (Is_Traded)"); } }
		}

		public ValueAnalysisTradeStatusList()
		{
			AddPair(Codes.EstimateActivePipelinePa_Status, Descriptions.EstimateActivePipelinePa_Status);
			AddPair(Codes.EstimateSuccessfulCommittedPa_Status, Descriptions.EstimateSuccessfulCommittedPa_Status);
			AddPair(Codes.EstimateUnsuccessfulPa_Status, Descriptions.EstimateUnsuccessfulPa_Status);
			AddPair(Codes.TradedIs_Traded, Descriptions.TradedIs_Traded);
		}
	}
}
