using CargoWise.EntityFramework.Testing;
using CargoWise.Types;
using Enterprise.Customs.US.Business;
using Enterprise.Freight.Agency.Business;
using Enterprise.Freight.Business;
using Enterprise.MasterFiles.Business;
using Enterprise.MasterFiles.Business.Testing;

namespace Enterprise.Customs.US.AMS.Business.Testing
{
	abstract class LinkedSailingBillsImportedTest : TestCaseWithFactory
	{
		protected CusInBondHeader header;
		protected JobVoyage voyage;
		protected JobSailing sailing;
		protected BillOfLading fCLSailingBill;
		protected BillOfLading fCLSailingBill2;
		protected BillOfLading rOROSailingBill;
		protected BillOfLading bulkSailingBill;
		protected OrgHeader consignor;
		protected OrgHeader consignee;
		protected OrgHeader notifyParty;
		protected RefContainer rContainer;
		protected BillOfLadingContainer sailingContainer;
		protected AgencyShipmentContainer vehicle;
		protected AgencyShipmentContainer topPack;
		protected OrgContact contact;
		protected BillOfLadingPackLine sailingPackLine;
		protected override void SetUp()
		{
			base.SetUp();
			var carrier = Factory.New<USCarrierCombined>();
			carrier.UI_Code = "SCAC";
			carrier.UI_ModeOfTransportation = "11";
			var exchangeRate = Factory.New<RefExchangeRate>();
			exchangeRate.RE_RX_NKExCurrency = Core.Constants.CurrencyCodes.UnitedStates;
			exchangeRate.RE_GC = GlbCompany.CurrentCompany.PK;
			exchangeRate.RE_StartDate = ZDateTime.Today.AddDays(-10);
			exchangeRate.RE_ExpiryDate = ZDateTime.Today.AddDays(10);
			exchangeRate.RE_ExRateType = Enterprise.Core.Constants.ExchangeRateTypes.Code.CustomsRate;
			exchangeRate.RE_SellRate = 0.5m;
			var vessel = Factory.NewWithValidTestData<RefVessel>();
			vessel.RV_Name = "AALSMEERGRACHT";
			voyage = Factory.New<JobVoyage>();
			voyage.JV_VoyageFlight = "123SD";
			voyage.JV_RV_NKVessel = vessel.RV_FK;
			var origin = voyage.Origins.AddNew();
			origin.JA_RL_NKPortOfLoading = "AUSYD";
			origin.JA_E_DEP = new ZDateTime(2006, 4, 10);
			var destination = voyage.Destinations.AddNew();
			destination.JB_RL_NKPortOfDischarge = "NZAKL";
			destination.JB_E_ARV = new ZDateTime(2006, 4, 20);
			voyage.GenerateSailings();
			sailing = voyage.Sailings[0];
			consignor = Factory.New<OrgHeader>();
			consignee = Factory.New<OrgHeader>();
			notifyParty = Factory.New<OrgHeader>();
			fCLSailingBill = Factory.New<BillOfLading>();
			fCLSailingBill.JS_PackingMode = Core.Constants.ContainerModes.FCL;
			fCLSailingBill.JS_NKLoadPort = "AUSYD";
			fCLSailingBill.JS_JX = sailing.PK;
			fCLSailingBill.JS_HouseBill = "AAA";
			var shippingLine = Factory.New<OrgHeader>();
			shippingLine.CustomsCodes.AddNew(OrgCusCode.CodeTypes.CarrierCode, "SCAC", Core.Constants.CountryCodes.UnitedStates);
			fCLSailingBill.JS_OA_BookedShippingLineAddress = shippingLine.MainAddress.PK;
			fCLSailingBill.ConsignorDocumentaryAddress.OrganisationPK = consignor.PK;
			fCLSailingBill.ConsigneeDocumentaryAddress.OrganisationPK = consignee.PK;
			fCLSailingBill.NotifyPartyDocumentaryAddress.OrganisationPK = notifyParty.PK;
			fCLSailingBill2 = Factory.New<BillOfLading>();
			fCLSailingBill2.JS_PackingMode = Core.Constants.ContainerModes.FCL;
			fCLSailingBill2.JS_NKLoadPort = "AUSYD";
			fCLSailingBill2.JS_JX = sailing.PK;
			fCLSailingBill2.JS_HouseBill = "SCACBN001"; // "SCAC" is valid carrier code.
			var shippingLine2 = Factory.New<OrgHeader>();
			shippingLine2.CustomsCodes.AddNew(OrgCusCode.CodeTypes.CarrierCode, "SCAC", Core.Constants.CountryCodes.UnitedStates);
			fCLSailingBill2.JS_OA_BookedShippingLineAddress = shippingLine2.MainAddress.PK;
			fCLSailingBill2.ConsignorDocumentaryAddress.OrganisationPK = consignor.PK;
			fCLSailingBill2.ConsigneeDocumentaryAddress.OrganisationPK = consignee.PK;
			fCLSailingBill2.NotifyPartyDocumentaryAddress.OrganisationPK = notifyParty.PK;
			rContainer = Factory.New<RefContainer>();
			sailingContainer = fCLSailingBill.RealContainers.AddNew();
			sailingContainer.JC_ContainerNum = "ABCD1111";
			sailingContainer.JC_RC = rContainer.PK;
			sailingContainer.JC_SealNum = "123";
			sailingContainer.JC_AdditionalSealNum = "321";
			contact = Factory.New<OrgContact>();
			sailingPackLine = fCLSailingBill.OuterPackLines.AddNew();
			sailingContainer.PackLines.Add(sailingPackLine);
			sailingPackLine.JL_HarmonisedCode = "01011000";
			sailingPackLine.JL_ActualWeight = 1000m;
			sailingPackLine.JL_ActualWeightUQ = "KG";
			sailingPackLine.JL_F3_NKPackType = "PLT";
			sailingPackLine.JL_PackageCount = 11;
			sailingPackLine.JL_DetailedDescription = "DESCRIPTION";
			sailingPackLine.JL_MarksAndNumbers = "MARKS AND NUMBERS";
			var subs = Factory.New<UNDGSubstance>();
			subs.DG_UNNO = "!!5%";
			subs.DG_Variant = "";
			subs.DG_Standard = UNDGSubstanceLookups.UNDGSubstanceStandardTypes.IMO;
			var undg = sailingPackLine.UNDGs.AddNew();
			undg.DI_DG = subs.PK;
			undg.LinkDefault(subs);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			var subs2 = Factory.New<UNDGSubstance>();
			subs2.DG_UNNO = "!!6%";
			subs2.DG_Variant = "";
			subs2.DG_Standard = UNDGSubstanceLookups.UNDGSubstanceStandardTypes.IMO;
			undg = sailingPackLine.UNDGs.AddNew();
			undg.DI_DG = subs2.PK;
			undg.LinkDefault(subs2);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			rOROSailingBill = Factory.New<BillOfLading>();
			rOROSailingBill.JS_PackingMode = Core.Constants.ContainerModes.RollOnRollOff;
			vehicle = rOROSailingBill.Vehicles.AddNew();
			rOROSailingBill.JS_NKLoadPort = "AUSYD";
			rOROSailingBill.JS_JX = sailing.PK;
			rOROSailingBill.JS_HouseBill = "BBB";
			rOROSailingBill.JS_OA_BookedShippingLineAddress = shippingLine.MainAddress.PK;
			rOROSailingBill.JS_ActualWeight = 1m;
			rOROSailingBill.JS_UnitOfWeight = Core.Constants.Weight.Kilograms;
			rOROSailingBill.JS_ActualVolume = 2m;
			rOROSailingBill.JS_UnitOfVolume = Core.Constants.Volume.CubicFeet;
			rOROSailingBill.JS_OuterPacks = 3;
			rOROSailingBill.JS_F3_NKPackType = Core.Constants.PkgUnit.Box;
			vehicle.JC_HarmonisedCode = "01011001";
			vehicle.JC_GrossWeight = 1m;
			vehicle.JC_GrossWeightUQ = Core.Constants.Weight.Kilograms;
			vehicle.JC_ContainerCount = 2;
			vehicle.JC_Description = "VEHICLE";
			vehicle.JC_MarksAndNumbers = "VEHICLE MARKS & NUMBERS";
			vehicle.JC_ContainerNum = "VIN";
			vehicle.JC_F3_NKPackType = Core.Constants.PkgUnit.Unit;
			vehicle.JC_GoodsValue = 100m;
			vehicle.JC_RX_NKGoodsCurrency = GlbCompany.CurrentCompany.GC_RX_NKLocalCurrency;
			undg = vehicle.UNDGs.AddNew();
			undg.DI_DG = subs.PK;
			undg.LinkDefault(subs);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			undg = vehicle.UNDGs.AddNew();
			undg.DI_DG = subs2.PK;
			undg.LinkDefault(subs2);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			bulkSailingBill = Factory.New<BillOfLading>();
			bulkSailingBill.JS_PackingMode = Core.Constants.ContainerModes.Bulk;
			bulkSailingBill.JS_NKLoadPort = "AUSYD";
			bulkSailingBill.JS_JX = sailing.PK;
			bulkSailingBill.JS_HouseBill = "CCC";
			bulkSailingBill.JS_OA_BookedShippingLineAddress = shippingLine.MainAddress.PK;
			bulkSailingBill.JS_ActualWeight = 1m;
			bulkSailingBill.JS_UnitOfWeight = Core.Constants.Weight.Kilograms;
			bulkSailingBill.JS_ActualVolume = 2m;
			bulkSailingBill.JS_UnitOfVolume = Core.Constants.Volume.CubicFeet;
			bulkSailingBill.JS_OuterPacks = 3;
			bulkSailingBill.JS_F3_NKPackType = Core.Constants.PkgUnit.Box;
			topPack = bulkSailingBill.TopLevelPacks.AddNew();
			topPack.JC_HarmonisedCode = "01011002";
			topPack.JC_GrossWeight = 1m;
			topPack.JC_GrossWeightUQ = Core.Constants.Weight.Kilograms;
			topPack.JC_ContainerCount = 2;
			topPack.JC_Description = "TOP PACK";
			topPack.JC_MarksAndNumbers = "TOP PACK MAKRS & NUMBERS";
			topPack.JC_F3_NKPackType = Core.Constants.PkgUnit.Box;
			topPack.JC_GoodsValue = 100m;
			topPack.JC_RX_NKGoodsCurrency = GlbCompany.CurrentCompany.GC_RX_NKLocalCurrency;
			undg = topPack.UNDGs.AddNew();
			undg.DI_DG = subs.PK;
			undg.LinkDefault(subs);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			undg = topPack.UNDGs.AddNew();
			undg.DI_DG = subs2.PK;
			undg.LinkDefault(subs2);
			undg.DI_DGFlashPoint = 1.2m;
			undg.DI_OC_DGContact = contact.PK;
			header = Factory.New<CusInBondHeader>();
			header.ChangeSailing(sailing.PK);
		}
	}
}
