<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientEDI.Test</AssemblyName>
    <RootNamespace>ZClientEDI.Test</RootNamespace>
    <NoWarn>$(NoWarn);CW1200</NoWarn>
    <EnableWinzorTests>true</EnableWinzorTests>
    <UseLegacyRsa>false</UseLegacyRsa>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="WTG.AWSCertificateIntegration" />
    <PackageReference Include="WTG.AzureApplicationIntegration" />
    <PackageReference Include="WTG.ErrorReporting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientEDI\ZClientEDI.Winzor.csproj" />
    <ProjectReference Include="..\ZClientEDI.ElasticSearchAdaptor\ZClientEDI.ElasticSearchAdaptor.csproj" />
    <ProjectReference Include="..\ZClientEDI.GUI.Test\ZClientEDI.GUI.Test.Winzor.csproj" />
    <ProjectReference Include="..\ZClientEDI.GUI\ZClientEDI.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common.Testing" />
    <Reference Include="WinzorFramework" />
    <Reference Include="Enterprise.BufferManagement.Business" />
    <Reference Include="Enterprise.BufferManagement.Business.Test" />
    <Reference Include="WTG.AzureApplicationIntegration.Testing" />
    <Reference Include="CargoWise.Main.Navigation" />
    <Reference Include="WTG.TestHelpers" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Escrow\repo.zip" />
    <EmbeddedResource Include="Mail\TestFiles\image1000.jpg" />
    <EmbeddedResource Include="Org4BELEV.xml" />
    <EmbeddedResource Include="OrgARJIMPBNE.xml" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestEventLogsHandler1.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestEventLogsInput.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestEventLogsInput1.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestEventsInput.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestEventsInput1.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestLoadNeededInformationOutput1.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLConvertedIssueXMLOutput.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLConvertedIssueXMLOutput_NotHavingCallStackData.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLConverterInput.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLConverterInput_NotHavingCallStackData.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLExtractDataOutput.txt" />
    <EmbeddedResource Include="ServiceTasks\EventLogs\TestFiles\TestXMLExtractDataOutput_NotHavingCallStackData.txt" />
    <EmbeddedResource Include="ServiceTasks\IncidentAssociation\incident_similarity_matrix_expected.csv.gz" />
    <EmbeddedResource Include="IncidentManager\BatchProcessor\SupportIncident\IntegrationIncidents.json" />
    <EmbeddedResource Include="ServiceTasks\ELearningDocument\Data\hello_world.pdf" />
    <EmbeddedResource Include="ServiceTasks\ELearningDocument\Data\1ACC001.pdf" />
    <EmbeddedResource Include="ServiceTasks\ELearningDocument\Data\ElearningDocumentDescriptionBigPayload.json" />
    <EmbeddedResource Include="IncidentManager\BatchProcessor\SupportIncident\ELearningDocumentDescriptionMockData.json" />
    <EmbeddedResource Include="ServiceTasks\IncidentLinkHealthCheck\Data\ELearningDocumentBorderWiseUserGuides.json" />
    <EmbeddedResource Include="ServiceTasks\IncidentLinkHealthCheck\Data\ELearningDocumentTechnicalAdvisoryNotes.json" />
    <EmbeddedResource Include="..\ZClientEDI\ServiceTasks\TestFiles\*" />
    <EmbeddedResource Include="..\ZClientEDI.Business\AutoDeploy\TestFiles\DummyUpgradePackageCS.zip" />
    <EmbeddedResource Include="ServiceTasks\IncidentLinkHealthCheck\Data\MessageWithoutLinks.txt" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdAdd.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdUpdate.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdDelete.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestAdd.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestDelete.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestUpdate.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdFromBlank.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestFromBlank.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestToInactive.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdToInactive.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestToActive.xml" />
    <EmbeddedResource Include="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdToActive.xml" />
    <EmbeddedResource Include="..\ZClientEDI.Business.Test\IssueManager\SampleFiles\*" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Escrow\repo.zip" />
    <None Remove="Mail\TestFiles\image1000.jpg" />
    <None Remove="Org4BELEV.xml" />
    <None Remove="OrgARJIMPBNE.xml" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestEventLogsHandler1.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestEventLogsInput.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestEventLogsInput1.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestEventsInput.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestEventsInput1.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestLoadNeededInformationOutput1.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLConvertedIssueXMLOutput.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLConvertedIssueXMLOutput_NotHavingCallStackData.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLConverterInput.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLConverterInput_NotHavingCallStackData.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLExtractDataOutput.txt" />
    <None Remove="ServiceTasks\EventLogs\TestFiles\TestXMLExtractDataOutput_NotHavingCallStackData.txt" />
    <None Remove="ServiceTasks\IncidentAssociation\incident_similarity_matrix_expected.csv.gz" />
    <None Remove="IncidentManager\BatchProcessor\SupportIncident\IntegrationIncidents.json" />
    <None Remove="ServiceTasks\ELearningDocument\Data\hello_world.pdf" />
    <None Remove="ServiceTasks\ELearningDocument\Data\1ACC001.pdf" />
    <None Remove="ServiceTasks\ELearningDocument\Data\ElearningDocumentDescriptionBigPayload.json" />
    <None Remove="IncidentManager\BatchProcessor\SupportIncident\ELearningDocumentDescriptionMockData.json" />
    <None Remove="ServiceTasks\IncidentLinkHealthCheck\Data\ELearningDocumentBorderWiseUserGuides.json" />
    <None Remove="ServiceTasks\IncidentLinkHealthCheck\Data\ELearningDocumentTechnicalAdvisoryNotes.json" />
    <None Remove="..\ZClientEDI\ServiceTasks\TestFiles\*" />
    <None Remove="..\ZClientEDI.Business\AutoDeploy\TestFiles\DummyUpgradePackageCS.zip" />
    <None Remove="ServiceTasks\IncidentLinkHealthCheck\Data\MessageWithoutLinks.txt" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdAdd.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdUpdate.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdDelete.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestAdd.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestDelete.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestUpdate.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdFromBlank.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestFromBlank.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestToInactive.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdToInactive.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeTestToActive.xml" />
    <None Remove="ServiceTasks\XTAuditSubscriber\TestFiles\InterchangeProdToActive.xml" />
  </ItemGroup>
</Project>