<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.MasterData.GUI.Test</RootNamespace>
    <AssemblyName>Enterprise.MasterData.GUI.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Moq" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Runtime.Caching" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MasterData.GUI\MasterData.GUI.csproj" />
  </ItemGroup>
</Project>