<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Staging.IFTRINMessageProcessor</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Staging.IFTRINMessageProcessor</AssemblyName>
    <Configurations>Debug;Release;UAT</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <OutputPath>..\..\..\Bin\Staging\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="CargoWise.RefDbRepo.Staging.IFTRINMessageProcessor.config.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.TypeProvider">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.TypeProvider.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.ApplicationConfig">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.ApplicationConfig.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
    <Reference Include="Edifact">
      <HintPath>..\..\..\Bin\Staging\net8.0\Edifact.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Edifact.D09B">
      <HintPath>..\..\..\Bin\Staging\net8.0\Enterprise.Edifact.D09B.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <Compile Update="Processor\SG\XML\CustomsExchangeRate.cs">
      <DependentUpon>CustomsExchangeRate.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Processor\SG\XML\CommonAggregateComponents-2.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="Processor\SG\XML\CommonBasicComponents-2.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="Processor\SG\XML\CustomsExchangeRate.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="Processor\SG\XML\TradenetResponse.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="CargoWise.RefDbRepo.Staging.IFTRINMessageProcessor.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Processor\SG\XML\Schemas.xml" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>