<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Configurations>Debug;Release;UAT</Configurations>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.SEReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.SEReferenceData.Business</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <ProjectReference Include="..\SEReferenceData.Services\SEReferenceData.Services.csproj" />
  </ItemGroup>
</Project>