<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of all TARIC records included in the incremental object trader export
	Export all entries which have been created, updated or deleted since the last ObjectTraderExport or
	IncrementalObjectTraderExport
 -->
    <xsd:include schemaLocation="adco/AdditionalCodeData.xsd"/>
    <xsd:include schemaLocation="cert/CertificateData.xsd"/>
    <xsd:include schemaLocation="erno/ExportRefundNomenclatureData.xsd"/>
    <xsd:include schemaLocation="foot/FootnoteData.xsd"/>
    <xsd:include schemaLocation="gear/GeographicalAreaData.xsd"/>
    <xsd:include schemaLocation="gono/DeclarableGoodsNomenclatureData.xsd"/>
    <xsd:include schemaLocation="gono/GoodsNomenclatureData.xsd"/>
    <xsd:include schemaLocation="gono/GoodsNomenclatureGroupData.xsd"/>
    <xsd:include schemaLocation="lookup/LookupTableData.xsd"/>
    <xsd:include schemaLocation="meae/MeasureData.xsd"/>
    <xsd:include schemaLocation="meae/MeasureActionData.xsd"/>
    <xsd:include schemaLocation="meae/MeasureConditionCodeData.xsd"/>
    <xsd:include schemaLocation="meae/MeasureData.xsd"/>
    <xsd:include schemaLocation="meae/MeasureTypeData.xsd"/>
    <xsd:include schemaLocation="meat/MeasurementData.xsd"/>
    <xsd:include schemaLocation="meat/MeasurementUnitData.xsd"/>
    <xsd:include schemaLocation="meat/MeasurementUnitQualifierData.xsd"/>
    <xsd:include schemaLocation="meur/MeursingAdditionalCodeData.xsd"/>
    <xsd:include schemaLocation="meur/MeursingHeadingData.xsd"/>
    <xsd:include schemaLocation="meur/MeursingSubheadingData.xsd"/>
    <xsd:include schemaLocation="meur/MeursingTablePlanData.xsd"/>
    <xsd:include schemaLocation="moun/MonetaryExchangePeriodData.xsd"/>
    <xsd:include schemaLocation="prco/PreferenceCodeData.xsd"/>
    <xsd:include schemaLocation="qdat/QuotaBalanceEventData.xsd"/>
    <xsd:include schemaLocation="qdat/QuotaDefinitionData.xsd"/>
    <xsd:include schemaLocation="qdat/QuotaEventData.xsd"/>
    <xsd:include schemaLocation="qdat/QuotaOrderNumberData.xsd"/>
    <xsd:include schemaLocation="regu/RegulationData.xsd"/>
    <xsd:include schemaLocation="relief/ReliefCodeData.xsd"/>
    <xsd:include schemaLocation="taxcd/TaxCodeData.xsd"/>
    <xsd:include schemaLocation="../BaseDataExport.xsd"/>
</xsd:schema>
