//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise.Tracking.Web.ImporterSecurityFiling {
    
    
    public partial class ImporterSecurityFilingDetails {
        
        /// <summary>
        /// DefaultBody control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DefaultBody;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// OuterContentPane control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl OuterContentPane;
        
        /// <summary>
        /// TitleLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel TitleLabel;
        
        /// <summary>
        /// ZtextlabelJobRefNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZtextlabelJobRefNo;
        
        /// <summary>
        /// CustomsStatusDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel CustomsStatusDescription;
        
        /// <summary>
        /// ButtonsDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ButtonsDiv;
        
        /// <summary>
        /// EditISF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button EditISF;
        
        /// <summary>
        /// DeleteISF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button DeleteISF;
        
        /// <summary>
        /// DuplicateISF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button DuplicateISF;
        
        /// <summary>
        /// DocsMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.Tracking.Web.ZDocumentsMenu DocsMenu;
        
        /// <summary>
        /// DetailsControls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DetailsControls;
        
        /// <summary>
        /// SharedDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SharedDetails;
        
        /// <summary>
        /// CustomsRefLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CustomsRefLabel;
        
        /// <summary>
        /// ZTextLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabel1;
        
        /// <summary>
        /// StatusLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StatusLabel;
        
        /// <summary>
        /// ZTextLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabel2;
        
        /// <summary>
        /// ActionReasonCodeArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow ActionReasonCodeArea;
        
        /// <summary>
        /// ActionReasonCodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ActionReasonCodeLabel;
        
        /// <summary>
        /// ActionReasonCodeZTextLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ActionReasonCodeZTextLabel3;
        
        /// <summary>
        /// FirstAcceptedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label FirstAcceptedLabel;
        
        /// <summary>
        /// ZTextLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel ZTextLabel3;
        
        /// <summary>
        /// LastAcceptedLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LastAcceptedLabel;
        
        /// <summary>
        /// ZDateTimeLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel ZDateTimeLabel1;
        
        /// <summary>
        /// ReferenceDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid ReferenceDataGrid;
        
        /// <summary>
        /// EntryTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label EntryTypeLabel;
        
        /// <summary>
        /// EntryTypeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel EntryTypeTextLabel;
        
        /// <summary>
        /// ShipmentTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ShipmentTypeLabel;
        
        /// <summary>
        /// ShipmentTypeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipmentTypeTextLabel;
        
        /// <summary>
        /// TransportModeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label TransportModeLabel;
        
        /// <summary>
        /// TransportModeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel TransportModeTextLabel;
        
        /// <summary>
        /// CarrierSCACLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CarrierSCACLabel;
        
        /// <summary>
        /// CarrierSCACTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel CarrierSCACTextLabel;
        
        /// <summary>
        /// ImporterLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ImporterLabel;
        
        /// <summary>
        /// ImporterZTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ImporterZTextLabel;
        
        /// <summary>
        /// LabelOwnerRef control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelOwnerRef;
        
        /// <summary>
        /// ZTextLabelOwnerRef control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabelOwnerRef;
        
        /// <summary>
        /// RoutingDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl RoutingDetails;
        
        /// <summary>
        /// LabelETD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelETD;
        
        /// <summary>
        /// ZTextLabelETD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel ZTextLabelETD;
        
        /// <summary>
        /// LabelLoadPort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelLoadPort;
        
        /// <summary>
        /// ZTextLabelLoadPort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabelLoadPort;
        
        /// <summary>
        /// LabelETA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelETA;
        
        /// <summary>
        /// ZTextLabelETA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel ZTextLabelETA;
        
        /// <summary>
        /// LabelDiscPort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelDiscPort;
        
        /// <summary>
        /// ZTextLabelDiscPort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabelDiscPort;
        
        /// <summary>
        /// LabelVessel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelVessel;
        
        /// <summary>
        /// ZTextLabelVessel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabelVessel;
        
        /// <summary>
        /// LabelVoyageFlight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabelVoyageFlight;
        
        /// <summary>
        /// ZTextLabelVoyageFlight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabelVoyageFlight;
        
        /// <summary>
        /// ISF10Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ISF10Details;
        
        /// <summary>
        /// ImporterDetailsTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable ImporterDetailsTable;
        
        /// <summary>
        /// ImporterDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell ImporterDetails;
        
        /// <summary>
        /// ImporterIdTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ImporterIdTypeLabel;
        
        /// <summary>
        /// BF_ImporterCodeType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BF_ImporterCodeType;
        
        /// <summary>
        /// ImporterIDLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ImporterIDLabel;
        
        /// <summary>
        /// BF_ImporterCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BF_ImporterCode;
        
        /// <summary>
        /// ImporterFullNameInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow ImporterFullNameInfo;
        
        /// <summary>
        /// ImporterFullNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ImporterFullNameLabel;
        
        /// <summary>
        /// ImporterFullName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ImporterFullName;
        
        /// <summary>
        /// DOBLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DOBLabel;
        
        /// <summary>
        /// BF_DateOfBirth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel BF_DateOfBirth;
        
        /// <summary>
        /// CountryOfIssueLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CountryOfIssueLabel;
        
        /// <summary>
        /// BF_CountryOfIssue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BF_CountryOfIssue;
        
        /// <summary>
        /// CneeDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell CneeDetails;
        
        /// <summary>
        /// CneeIdType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CneeIdType;
        
        /// <summary>
        /// CneeIdTypeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel CneeIdTypeTextLabel;
        
        /// <summary>
        /// CneeID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CneeID;
        
        /// <summary>
        /// CneeIDTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel CneeIDTextLabel;
        
        /// <summary>
        /// ConsigneeFullNameInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow ConsigneeFullNameInfo;
        
        /// <summary>
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;
        
        /// <summary>
        /// ZTextLabel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabel4;
        
        /// <summary>
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// ZDateTimeLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZDateTimeLabel ZDateTimeLabel2;
        
        /// <summary>
        /// Label3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// ZTextLabel5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ZTextLabel5;
        
        /// <summary>
        /// BondDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow BondDetails;
        
        /// <summary>
        /// BondHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow BondHolder;
        
        /// <summary>
        /// BondHolderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BondHolderLabel;
        
        /// <summary>
        /// BF_BondNumberOrHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BF_BondNumberOrHolder;
        
        /// <summary>
        /// BondActivityCodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BondActivityCodeLabel;
        
        /// <summary>
        /// BondActivityCodeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BondActivityCodeTextLabel;
        
        /// <summary>
        /// BondTypeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BondTypeLabel;
        
        /// <summary>
        /// BondTypeTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BondTypeTextLabel;
        
        /// <summary>
        /// BondSuretyCodeLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BondSuretyCodeLabel;
        
        /// <summary>
        /// BF_SuretyCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BF_SuretyCode;
        
        /// <summary>
        /// BondEntryNumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BondEntryNumber;
        
        /// <summary>
        /// BondEntryNumberTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BondEntryNumberTextLabel;
        
        /// <summary>
        /// ISF5Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ISF5Details;
        
        /// <summary>
        /// Locations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Locations;
        
        /// <summary>
        /// UnloadPortLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label UnloadPortLabel;
        
        /// <summary>
        /// UnloadPortTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel UnloadPortTextLabel;
        
        /// <summary>
        /// DeliveryPortLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DeliveryPortLabel;
        
        /// <summary>
        /// DeliveryPortTextLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel DeliveryPortTextLabel;
        
        /// <summary>
        /// Milestones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.Tracking.Web.MilestonesControl Milestones;
        
        /// <summary>
        /// TrackingEvents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.Tracking.Web.EventsControl TrackingEvents;
        
        /// <summary>
        /// OrganisationsDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl OrganisationsDetails;
        
        /// <summary>
        /// ShipToPartyAddressHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ShipToPartyAddressHolder;
        
        /// <summary>
        /// ShipToLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ShipToLabel;
        
        /// <summary>
        /// ShipToPartyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyName;
        
        /// <summary>
        /// ShipToPartyContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyContact;
        
        /// <summary>
        /// ShipToPartyAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyAddress1;
        
        /// <summary>
        /// ShipToPartyAddress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyAddress2;
        
        /// <summary>
        /// ShipToPartyCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyCity;
        
        /// <summary>
        /// ShipToPartyState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyState;
        
        /// <summary>
        /// ShipToPartyPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyPost;
        
        /// <summary>
        /// ShipToPartyCountryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyCountryCode;
        
        /// <summary>
        /// ShipToGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow ShipToGovRegNoArea;
        
        /// <summary>
        /// ShipToPartyRegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyRegNoType;
        
        /// <summary>
        /// ShipToPartyRegNum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipToPartyRegNum;
        
        /// <summary>
        /// BuyingPartyAddressHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl BuyingPartyAddressHolder;
        
        /// <summary>
        /// BuyingPartyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BuyingPartyLabel;
        
        /// <summary>
        /// BuyungPartyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyName;
        
        /// <summary>
        /// BuyungPartyContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyContact;
        
        /// <summary>
        /// BuyungPartyAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyAddress1;
        
        /// <summary>
        /// BuyungPartyAddress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyAddress2;
        
        /// <summary>
        /// BuyungPartyCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyCity;
        
        /// <summary>
        /// BuyungPartyState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyState;
        
        /// <summary>
        /// BuyungPartyPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyPost;
        
        /// <summary>
        /// BuyungPartyCountryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyCountryCode;
        
        /// <summary>
        /// BuyingPartyGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow BuyingPartyGovRegNoArea;
        
        /// <summary>
        /// BuyungPartyRegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyRegNoType;
        
        /// <summary>
        /// BuyungPartyRegNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BuyungPartyRegNo;
        
        /// <summary>
        /// BookingPartyAddressHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl BookingPartyAddressHolder;
        
        /// <summary>
        /// BookingPartyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label BookingPartyLabel;
        
        /// <summary>
        /// BookingPartyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyName;
        
        /// <summary>
        /// BookingPartyContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyContact;
        
        /// <summary>
        /// BookingPartyAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyAddress1;
        
        /// <summary>
        /// BookingPartyAddress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyAddress2;
        
        /// <summary>
        /// BookingPartyCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyCity;
        
        /// <summary>
        /// BookingPartyState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyState;
        
        /// <summary>
        /// BookingPartyPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyPost;
        
        /// <summary>
        /// BookingPartyCountryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyCountryCode;
        
        /// <summary>
        /// BookingPartyGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow BookingPartyGovRegNoArea;
        
        /// <summary>
        /// BookingPartyRegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyRegNoType;
        
        /// <summary>
        /// BookingPartyRegNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel BookingPartyRegNo;
        
        /// <summary>
        /// SellingPartyAddressHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl SellingPartyAddressHolder;
        
        /// <summary>
        /// SellingPartyLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label SellingPartyLabel;
        
        /// <summary>
        /// SellingPartyName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyName;
        
        /// <summary>
        /// SellingPartyContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyContact;
        
        /// <summary>
        /// SellingPartyAddressLine1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyAddressLine1;
        
        /// <summary>
        /// SellingPartyAddressLine2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyAddressLine2;
        
        /// <summary>
        /// SellingPartyCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyCity;
        
        /// <summary>
        /// SellingPartyState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyState;
        
        /// <summary>
        /// SellingPartyPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyPost;
        
        /// <summary>
        /// SellingPartyContryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel SellingPartyContryCode;
        
        /// <summary>
        /// SellingPartyGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow SellingPartyGovRegNoArea;
        
        /// <summary>
        /// RegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel RegNoType;
        
        /// <summary>
        /// RegNoCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel RegNoCode;
        
        /// <summary>
        /// StuffingLocationHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl StuffingLocationHolder;
        
        /// <summary>
        /// StuffingLocationLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label StuffingLocationLabel;
        
        /// <summary>
        /// StuffingLocationName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationName;
        
        /// <summary>
        /// StuffingLocationContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationContact;
        
        /// <summary>
        /// StuffingLocationAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationAddress1;
        
        /// <summary>
        /// StuffingLocationAddress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationAddress2;
        
        /// <summary>
        /// StuffingLocationCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationCity;
        
        /// <summary>
        /// StuffingLocationState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationState;
        
        /// <summary>
        /// StuffingLocationPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationPost;
        
        /// <summary>
        /// StuffingLocationCountryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationCountryCode;
        
        /// <summary>
        /// StuffingLocationGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow StuffingLocationGovRegNoArea;
        
        /// <summary>
        /// StuffingLocationRegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationRegNoType;
        
        /// <summary>
        /// StuffingLocationRegNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel StuffingLocationRegNo;
        
        /// <summary>
        /// ConsolidatorAddressHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConsolidatorAddressHolder;
        
        /// <summary>
        /// ConsolidatorLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ConsolidatorLabel;
        
        /// <summary>
        /// ConsolidatorName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorName;
        
        /// <summary>
        /// ConsolidatorContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorContact;
        
        /// <summary>
        /// ConsolidatorAddress1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorAddress1;
        
        /// <summary>
        /// ConsolidatorAddress2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorAddress2;
        
        /// <summary>
        /// ConsolidatorCity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorCity;
        
        /// <summary>
        /// ConsolidatorPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorPost;
        
        /// <summary>
        /// ConsolidatorState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorState;
        
        /// <summary>
        /// ConsolidatorCountryCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorCountryCode;
        
        /// <summary>
        /// ConsolidatorGovRegNoArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow ConsolidatorGovRegNoArea;
        
        /// <summary>
        /// ConsolidatorRegNoType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorRegNoType;
        
        /// <summary>
        /// ConsolidatorRegNo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ConsolidatorRegNo;
        
        /// <summary>
        /// LowValueDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl LowValueDetails;
        
        /// <summary>
        /// ShipSubTypeDropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel ShipSubTypeDropDown;
        
        /// <summary>
        /// EstimatedValueEditBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZNumericLabel EstimatedValueEditBox;
        
        /// <summary>
        /// EstimatedQtyEditBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZNumericLabel EstimatedQtyEditBox;
        
        /// <summary>
        /// EstimatedQuantityUQDropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel EstimatedQuantityUQDropDown;
        
        /// <summary>
        /// EstimatedWeightEditBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZNumericLabel EstimatedWeightEditBox;
        
        /// <summary>
        /// EstimatedWeightUQDropDown control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZTextLabel EstimatedWeightUQDropDown;
        
        /// <summary>
        /// Grids control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Grids;
        
        /// <summary>
        /// AddressesDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid AddressesDataGrid;
        
        /// <summary>
        /// LinesDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid LinesDataGrid;
        
        /// <summary>
        /// ContainersDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid ContainersDataGrid;
        
        /// <summary>
        /// AdditionalShipToAddressesDataGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid AdditionalShipToAddressesDataGrid;
        
        /// <summary>
        /// DocumentsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Enterprise.ZArchitecture.Web.GUI.WebControls.ZGrid DocumentsGrid;
    }
}
