<Project>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.AU.Declaration.Business" />
    <Reference Include="Enterprise.Customs.AU.Declaration.GUI" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.GUI" />
    <Reference Include="Enterprise.DataTransfer" />
    <Reference Include="Enterprise.DataTransfer.GUI" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
  </ItemGroup>
</Project>