//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from LicenceTypeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Client.EDI.LicenceKeyBuilder.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class LicenceTypeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string CPU = "CPU";
			public const string SRV = "SRV";
			public const string STL = "STL";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string CPU = "CPU Licence";
			public const string SRV = "Per Server Licence";
			public const string STL = "Per Seat Licence";
		}

		public LicenceTypeList()
		{
			AddPair(Codes.CPU, Descriptions.CPU);
			AddPair(Codes.SRV, Descriptions.SRV);
			AddPair(Codes.STL, Descriptions.STL);
		}
	}
}
