<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0014</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.FeatureControl.Abstractions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DeniedPartyScreening.Common" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="WTG.Foundation.Http" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="StmEntityScreeningLog\StmEntityScreeningLogResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.DeniedPartyScreening.Integration\Enterprise.DeniedPartyScreening.Integration.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="CoreWCF.WebHttp" />
    <PackageReference Include="System.ServiceModel.Primitives" />
    <PackageReference Include="System.ServiceModel.Web" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>