<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>CargoWise.RefDbRepo.VNReferenceData.Business</AssemblyName>
    <RootNamespace>CargoWise.RefDbRepo.VNReferenceData.Business</RootNamespace>
    <Configurations>Debug;Release;UAT</Configurations>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <OutputPath>..\..\..\bin\UniversalXMLProducers\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>$(NoWarn);CA1416;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.UniversalXMLProducers.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.UniversalXMLProducers.Common.dll</HintPath>
    </Reference>
    <Reference Include="FlexCel">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\FlexCel.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ImageProcessingConfig.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.bigrams">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.fold">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.lm">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.nn">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.params">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.size">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.cube.word-freq">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.tesseract_cube.nn">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>