namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.Input
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[InputBlock("PG12")]
	public partial class PGAPG12 : MessageBlock
	{
		public PGAPG12()
			: base("PG12")
		{
		}

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 5, "M")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 6, "M")]
		public ZString DocumentQualifier;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 9, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter1;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 10, "C")]
		public ZString DocumentQualifier1;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 13, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter2;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 14, "C")]
		public ZString DocumentQualifier2;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 17, "")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter3;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 18, "C")]
		public ZString DocumentQualifier3;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 21, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter4;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 22, "C")]
		public ZString DocumentQualifier4;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 25, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter5;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 26, "C")]
		public ZString DocumentQualifier5;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 29, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter6;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 30, "C")]
		public ZString DocumentQualifier6;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 33, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter7;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 34, "C")]
		public ZString DocumentQualifier7;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 37, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter8;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 38, "C")]
		public ZString DocumentQualifier8;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 41, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter9;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 42, "C")]
		public ZString DocumentQualifier9;

		/// <summary>
		/// A code of Y (yes) indicating that the importer has a copy of a document needed to import a product that is under a government agency jurisdiction.
		/// </summary>
		[MessageBlockString(1, 45, "C")]
		public ZString ImportersSubstantiatingSignedDocumentSignedConfirmationLetter10;

		/// <summary>
		/// This code indicates the type of document that the importer has signed.
		/// </summary>
		[MessageBlockString(3, 46, "C")]
		public ZString DocumentQualifier10;

		/// <summary>
		/// This number corresponds to the box number/letter on an agency form (DOT Form HS-7) or the numbers in note 5. First two characters represent the agency: Example “DT” =National Highway Safety Transportation Admin, Last three characters represent the box number: examples, DT2A, DT5, FC1, FC5A, FDRA1, FDRA2.
		/// </summary>
		[MessageBlockString(5, 49, "C")]
		public ZString ConformanceDeclaration;

		/// <summary>
		/// A code of Y (yes) indicating that the filer certifies the data. No other code is accepted.
		/// </summary>
		[MessageBlockString(1, 54, "C")]
		public ZString DeclarationCertification;

		/// <summary>
		/// This number corresponds to the box number/letter on an agency form (DOT Form HS-7) or the numbers in note 5. First two characters represent the agency: “DT” =National Highway Safety Transportation Last three characters represent the box number: examples, DT2A, DT5, FC1, FC5A, FDRA1, FDRA2.
		/// </summary>
		[MessageBlockString(5, 55, "C")]
		public ZString ConformanceDeclaration1;

		/// <summary>
		/// A code of Y (yes) indicating that the filer certifies the data. No other code is accepted.
		/// </summary>
		[MessageBlockString(1, 60, "C")]
		public ZString DeclarationCertification1;

		/// <summary>
		/// This number corresponds to the box number/letter on an agency form (DOT Form HS-7) or the numbers in note 5. First two characters represent the agency: “DT” =National Highway Safety Transportation Admin. Last three characters represent the box number: examples, DT2A, DT5, FC1, FC5A, FDRA1, FDRA2.
		/// </summary>
		[MessageBlockString(5, 61, "C")]
		public ZString ConformanceDeclaration2;

		/// <summary>
		/// A code of Y (yes) indicating that the filer certifies the data. No other code is accepted.
		/// </summary>
		[MessageBlockString(1, 66, "C")]
		public ZString DeclarationCertification2;
	}
}
