<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.DocumentScanning.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.DocumentScanning.Module.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentScanning.Module\DocumentScanning.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
    <Reference Include="Enterprise.DocumentScanning.GUI" />
  </ItemGroup>
</Project>