//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.MasterFiles.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoGlbStaffCostCentre : EnterpriseBusinessObject, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "GlbStaffCostCentre";
			public const string PK        = "GSK_PK";

			public const string GSK_EndDate               = "GSK_EndDate";
			public const string GSK_GB_Branch             = "GSK_GB_Branch";
			public const string GSK_GE_Department         = "GSK_GE_Department";
			public const string GSK_GS_Staff              = "GSK_GS_Staff";
			public const string GSK_StartDate             = "GSK_StartDate";
			public const string GSK_SystemCreateTimeUtc   = "GSK_SystemCreateTimeUtc";
			public const string GSK_SystemCreateUser      = "GSK_SystemCreateUser";
			public const string GSK_SystemLastEditTimeUtc = "GSK_SystemLastEditTimeUtc";
			public const string GSK_SystemLastEditUser    = "GSK_SystemLastEditUser";

			public const int GSK_SystemCreateUserMaxLength = 3;
			public const int GSK_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoGlbStaffCostCentre(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSK_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSK_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSK_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(GSK_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return GlbStaffCostCentreSchema.PK; }
		}

		#endregion

		#region Properties

		#region GSK_EndDate

		public virtual ZDate GSK_EndDate
		{
			get {  return new ZDate(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_EndDate), DateTimeKind.Local); }
			set
			{
				SetPropertyValue(GSK_EndDateInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSK_EndDate();
				}
			}
		}

		public virtual ZPropertyInfo GSK_EndDateInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_EndDate); }
		}

		#endregion

		#region GSK_GB_Branch

		[RelatedBusinessObject("Branch")]
		[List("Lookups.Branches")]
		public virtual ZGuid GSK_GB_Branch
		{
			get {  return new ZGuid(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_GB_Branch)); }
			set
			{
				SetPropertyValue(GSK_GB_BranchInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSK_GB_Branch();
				}
			}
		}

		public virtual GlbBranch Branch
		{
			get { return (GlbBranch) Factory.Load(typeof(GlbBranch), GSK_GB_Branch); }
		}

		public virtual ZPropertyInfo GSK_GB_BranchInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_GB_Branch); }
		}

		#endregion

		#region GSK_GE_Department

		[RelatedBusinessObject("Department")]
		[List("Lookups.Departments")]
		public virtual ZGuid GSK_GE_Department
		{
			get {  return new ZGuid(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_GE_Department)); }
			set
			{
				SetPropertyValue(GSK_GE_DepartmentInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSK_GE_Department();
				}
			}
		}

		public virtual GlbDepartment Department
		{
			get { return (GlbDepartment) Factory.Load(typeof(GlbDepartment), GSK_GE_Department); }
		}

		public virtual ZPropertyInfo GSK_GE_DepartmentInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_GE_Department); }
		}

		#endregion

		#region GSK_GS_Staff

		[RelatedBusinessObject("Staff")]
		[List("Lookups.Staff")]
		public virtual ZGuid GSK_GS_Staff
		{
			get {  return new ZGuid(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_GS_Staff)); }
			set
			{
				SetPropertyValue(GSK_GS_StaffInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSK_GS_Staff();
				}
			}
		}

		public virtual GlbStaff Staff
		{
			get { return (GlbStaff) Factory.Load(typeof(GlbStaff), GSK_GS_Staff); }
		}

		public virtual ZPropertyInfo GSK_GS_StaffInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_GS_Staff); }
		}

		#endregion

		#region GSK_StartDate

		public virtual ZDate GSK_StartDate
		{
			get {  return new ZDate(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_StartDate), DateTimeKind.Local); }
			set
			{
				SetPropertyValue(GSK_StartDateInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateGSK_StartDate();
				}
			}
		}

		public virtual ZPropertyInfo GSK_StartDateInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_StartDate); }
		}

		#endregion

		#region GSK_SystemCreateTimeUtc

		public virtual ZDateTime GSK_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(GSK_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo GSK_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_SystemCreateTimeUtc); }
		}

		#endregion

		#region GSK_SystemCreateUser

		public virtual ZString GSK_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSK_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo GSK_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_SystemCreateUser); }
		}

		#endregion

		#region GSK_SystemLastEditTimeUtc

		public virtual ZDateTime GSK_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(GSK_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo GSK_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_SystemLastEditTimeUtc); }
		}

		#endregion

		#region GSK_SystemLastEditUser

		public virtual ZString GSK_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(GlbStaffCostCentreSchema.GSK_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = GSK_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo GSK_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(GlbStaffCostCentreSchema.Constants.GSK_SystemLastEditUser); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[GlbStaffCostCentreSchema.Constants.GSK_EndDate              ] = DBNull.Value;
			row[GlbStaffCostCentreSchema.Constants.GSK_GB_Branch            ] = DBNull.Value;
			row[GlbStaffCostCentreSchema.Constants.GSK_GE_Department        ] = Guid.Empty;
			row[GlbStaffCostCentreSchema.Constants.GSK_GS_Staff             ] = Guid.Empty;
			row[GlbStaffCostCentreSchema.Constants.GSK_StartDate            ] = DBNull.Value;
			row[GlbStaffCostCentreSchema.Constants.GSK_SystemCreateTimeUtc  ] = DBNull.Value;
			row[GlbStaffCostCentreSchema.Constants.GSK_SystemCreateUser     ] = "";
			row[GlbStaffCostCentreSchema.Constants.GSK_SystemLastEditTimeUtc] = DBNull.Value;
			row[GlbStaffCostCentreSchema.Constants.GSK_SystemLastEditUser   ] = "";
		}

		#endregion

		#region Lookups

		public GlbStaffCostCentreLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual GlbStaffCostCentreLookups GetNewLookups()
		{
			return new GlbStaffCostCentreLookups(this);
		}

		GlbStaffCostCentreLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public GlbStaffCostCentreValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual GlbStaffCostCentreValidation GetNewValidation()
		{
			return new GlbStaffCostCentreValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return GSK_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return GSK_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return GSK_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return GSK_SystemLastEditUser; }
		}

		#endregion
	}
}
