<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <EmbeddedResource Include="IEEnterpriseApplicationConfiguration.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Customs.IE.MessageContracts" />
    <Reference Include="CargoWise.Customs.IE.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.DutyCalculator" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.EMCS.Business" />
    <Reference Include="Enterprise.Customs.EU.ExitControl.Business" />
    <Reference Include="Enterprise.Customs.EU.NCTS.Business" />
    <Reference Include="Enterprise.Customs.ExitControlBase.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.xTMessaging.Shared" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="FlexCel" />
    <Reference Include="System.Text.Json" />
    <Reference Include="Resources" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="System.Memory" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\AISRefundTypeList.cs">
      <DependentUpon>AISRefundTypeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\AdditionalSupplyChainActorRoleCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AdditionalSupplyChainActorRoleCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\AISChargeCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AISChargeCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\DeclarationApplicationSearchFilterCodeList.cs">
      <DependentUpon>DeclarationApplicationSearchFilterCodeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\RepresentativeStatusCodeList.cs">
      <DependentUpon>RepresentativeStatusCodeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ImportDeclarationApplicationCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ImportDeclarationApplicationCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ReExportDeclarationTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReExportDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\RegionOfDestinationList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RegionOfDestinationList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\TemporaryStorageDeclarationTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TemporaryStorageDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\IETemporaryStorageMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IETemporaryStorageMessageTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\OverallControlTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OverallControlTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\XmlErrorCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>XmlErrorCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ExitSummaryDeclarationTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExitSummaryDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ExportDeclarationTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ExportDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\IEExportCustomsChargeTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IEExportCustomsChargeTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ImportDeclarationTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ImportDeclarationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageSubTypeListExp.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageSubTypeListExp.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\AESFlagCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AESFlagCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\AESFlagCodeListPartial.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AESFlagCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PaymentMethodList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PaymentMethodList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PreviousDocumentTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PreviousDocumentTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\WarehouseTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>WarehouseTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CusLineTariffDetail\AutoCusLineTariffDetail.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoCusLineTariffDetail.xml</DependentUpon>
    </Compile>
    <Compile Update="Declaration\JobComInvoiceLine\AutoJobComInvoiceLine.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoJobComInvoiceLine.xml</DependentUpon>
    </Compile>
    <Compile Update="Message\MessageSendingActions\AIS\Common\RefundApplication\AutoRefundApplicationDocumentSendingObject.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoRefundApplicationDocumentSendingObject.xml</DependentUpon>
    </Compile>
    <Compile Update="Message\MessageSendingActions\Documents\AdditionalInfoSendingObjects\AutoAdditionalInfoSendingObject.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoAdditionalInfoSendingObject.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\AISRefundTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <LastGenOutput>AISRefundTypeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\AdditionalSupplyChainActorRoleCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AdditionalSupplyChainActorRoleCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\AISChargeCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AISChargeCodeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ExportDeclarationTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ExportDeclarationTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\DeclarationApplicationSearchFilterCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <LastGenOutput>DeclarationApplicationSearchFilterCodeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\RepresentativeStatusCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <LastGenOutput>RepresentativeStatusCodeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\ImportDeclarationApplicationCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ImportDeclarationApplicationCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ImportDeclarationTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ImportDeclarationTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\AESFlagCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AESFlagCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\OverallControlTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>OverallControlTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\PreviousDocumentTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PreviousDocumentTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\PaymentMethodList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PaymentMethodList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\RegionOfDestinationList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>RegionOfDestinationList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\TemporaryStorageDeclarationTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TemporaryStorageDeclarationTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business.CusTempStorage</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\IETemporaryStorageMessageTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>IETemporaryStorageMessageTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business.CusTempStorage</CustomToolNamespace>
    </None>
    <None Update="CusLineTariffDetail\AutoCusLineTariffDetail.xml">
      <Generator>AddInfoPartialWrapperGenerator</Generator>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <LastGenOutput>AutoCusLineTariffDetail.cs</LastGenOutput>
    </None>
    <None Update="Declaration\JobComInvoiceLine\AutoJobComInvoiceLine.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business.Declaration</CustomToolNamespace>
      <Generator>AddInfoPartialWrapperGenerator</Generator>
      <LastGenOutput>AutoJobComInvoiceLine.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Messaging\Enterprise.Customs.IE.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\XmlErrorCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>XmlErrorCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ExitSummaryDeclarationTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ExitSummaryDeclarationTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\IEExportCustomsChargeTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>IEExportCustomsChargeTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\ReExportDeclarationTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\WarehouseTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>WarehouseTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
    </None>
    <None Update="Message\MessageSendingActions\AIS\Common\RefundApplication\AutoRefundApplicationDocumentSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <LastGenOutput>AutoRefundApplicationDocumentSendingObject.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
    <None Update="Message\MessageSendingActions\Documents\AdditionalInfoSendingObjects\AutoAdditionalInfoSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoAdditionalInfoSendingObject.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>