<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <OutputPath>..\..\..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Shared.40">
      <HintPath>..\..\..\..\..\..\bin\CargoWise.Shared.40.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Service References\AccountingTransactionExportServiceReference\Reference.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Reference.svcmap</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadataStorage Include="Service References\AccountingTransactionExportServiceReference\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Service References\AccountingTransactionExportServiceReference\Reference.svcmap">
      <Generator>WCF Proxy Generator</Generator>
      <LastGenOutput>Reference.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>