<?xml version="1.0" encoding="UTF-8"?>
<!-- Customized Korea South e-Invoicing XML elements -->
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="urn:kr:or:kec:standard:Tax:ReusableAggregateBusinessInformationEntitySchemaModule:1:0"
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	targetNamespace="urn:kr:or:kec:standard:Tax:ReusableAggregateBusinessInformationEntitySchemaModule:1:0"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xsd:include schemaLocation="TaxInvoiceSchemaModule_1.0.xsd"/>
	<xsd:element name="TaxInvoiceSet" type="TaxInvoiceSetType"/>
	<xsd:complexType name="TaxInvoiceSetType">
		<xsd:sequence>
			<xsd:element name="TaxInvoice" type="TaxInvoiceType"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>
