<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Warehouse.Yard.Module.Test</RootNamespace>
    <AssemblyName>Enterprise.Warehouse.Yard.Module.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\Yard.GUI\Yard.GUI.csproj" />
    <ProjectReference Include="..\Yard.Module\Yard.Module.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>