<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>CargoWise.Bi.Maintenance</RootNamespace>
    <AssemblyName>CargoWise.Bi.Maintenance</AssemblyName>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DbUpgrader.Foundation" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.DbHealth.Check" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>