<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.TransportBookings.GUI</AssemblyName>
    <RootNamespace>Enterprise.TransportBookings.GUI</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransportBooking.Business\TransportBookings.Business.csproj" />
    <ProjectReference Include="..\TransportBookings.Business.Test\TransportBookings.Business.Test.csproj" Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>