<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <DeploymentPropsImported>true</DeploymentPropsImported>
    <Server Condition="'$(Server)'==''">SYDSP-SBTS-X.sand.wtg.zone</Server>
    <DatabaseServer Condition="'$(DatabaseServer)'==''">$(Server)</DatabaseServer>
    <UserId Condition="'$(UserId)'==''">\DevAdmin</UserId>
    <Password Condition="'$(Password)'==''">ObDm++ALTvLhe+W+aGyOlbD1qW7japITWbDRfNNzfrjuZCJ8XOyAFdxn7hkZQtLBVdmySVmT6nT5m9rcbrJ3r5x86YtRH42S4dUBfj5XEydLmHREo6lW9KjVOux+FCHJPBuWo7eTBze8bdPRTarrxqZ+fjqGlEJDgx/+87EEP+w=</Password>
    <AccountName Condition="'$(AccountName)'==''">\DevAdmin</AccountName>
    <AccountPassword Condition="'$(AccountPassword)'==''">ObDm++ALTvLhe+W+aGyOlbD1qW7japITWbDRfNNzfrjuZCJ8XOyAFdxn7hkZQtLBVdmySVmT6nT5m9rcbrJ3r5x86YtRH42S4dUBfj5XEydLmHREo6lW9KjVOux+FCHJPBuWo7eTBze8bdPRTarrxqZ+fjqGlEJDgx/+87EEP+w=</AccountPassword>
    <ConnectionString>Data Source=localhost;Initial Catalog=eHubTransactions;Integrated Security=True;Connect Timeout=120</ConnectionString>
  </PropertyGroup>
</Project>