<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <GlobalsImported>$true</GlobalsImported>

        <Server Condition="'$(Server)'==''">$(COMPUTERNAME)</Server>
        <DatabaseServer Condition="'$(DatabaseServer)'==''">$(Server)</DatabaseServer>
        <UserId Condition="'$(UserId)'==''">$(Server)\DevAdmin</UserId>
        <Password Condition="'$(Password)'==''">3hubRock$</Password>
        <AccountName Condition="'$(AccountName)'==''">\DevAdmin</AccountName>
        <AccountPassword Condition="'$(AccountPassword)'==''">3hubRock$</AccountPassword>
        <BinPath Condition="'$(BinPath)'==''">Bin</BinPath>
        <Dir>$(BinPath)</Dir>

        <BizTalkApplicationUsersGroup>BizTalk Application Users</BizTalkApplicationUsersGroup>
        <BizTalkUsersGroup>BizTalk Server Administrators</BizTalkUsersGroup>
        <BizTalkIsolatedUsersGroup>BizTalk Isolated Host Users</BizTalkIsolatedUsersGroup>
        <BizTalkCorporateUsersDev>corporate\Biztalkhostusersdev</BizTalkCorporateUsersDev>
        <IsHostTrused>false</IsHostTrused>

        <EdiSubFolder>Edi</EdiSubFolder>
        <ProductsSubFolder>Products</ProductsSubFolder>

        <EdiBizTalkBinPath>$(BinPath)\$(EdiSubFolder)</EdiBizTalkBinPath>
        <ProductsBizTalkBinPath>$(BinPath)\$(ProductsSubFolder)</ProductsBizTalkBinPath>

        <BizTalkApplication1>BizTalk Application 1</BizTalkApplication1>
        <EdiApplication>BizTalk EDI Application</EdiApplication>
        <eHubApplication>CargoWise.eHub</eHubApplication>
        <ProductsApplication>CargoWise.eHub.Products</ProductsApplication>

        <GacAllowedMaxFileNameLength>92</GacAllowedMaxFileNameLength>
    </PropertyGroup>
</Project>