// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.EU.Business.Declaration.CusEUEntryHeaderTypeDecider.GetEUEntryHeaderCountryCode(System.Data.DataRow,CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\EU\Core\Business\Declaration\CusEUEntryHeader\CusEUEntryHeaderTypeDecider.cs:25:47
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.EU.Business.Declaration.CusEUEntryInstructionTypeDecider.GetEUEntryInstructionCountryCode(System.Data.DataRow,CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\EU\Core\Business\Declaration\CusEUEntryInstruction\CusEUEntryInstructionTypeDecider.cs:27:57
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusAuthorizationUsage.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusAuthorisations/CusAuthorisationUsage/CusAuthorizationUsage.cs:35,58
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageJobHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC5/CusTempStorageJobHeader/CusTempStorageJobHeader.cs:41,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusPermitHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusPermit/CusPermitHeader/CusPermitHeader.cs:22,68
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusContainer.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusContainer/TypeSafeCusContainer.cs:47,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusGuaranteeHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusGuarantee/CusGuaranteeHeader/CusGuaranteeHeader.cs:20,71
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageDec.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC5/CusTempStorageDec/CusTempStorageDec.cs:22,54
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageRegLineTransaction.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/CusTempStorageRegLineTransaction/CusTempStorageRegLineTransaction.cs:26,69
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusEntryHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusEntryHeader/CusEntryHeader.cs:42,55
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.JobComInvoiceGroupHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/JobComInvoiceGroupHeader/JobComInvoiceGroupHeader.cs:18,65
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.MasterFiles.CusClassPartPivot.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/MasterFiles/CusClassPartPivot/CusClassPartPivot.cs:39,58
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusGuaranteeRule.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusGuarantee/CusGuaranteeRule/CusGuaranteeRule.cs:13,69
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageLine.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC5/CusTempStorageLine/CusTempStorageLine.cs:32,55
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusEntryHeaderCharges.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusEntryHeaderCharges/CusEntryHeaderCharges.cs:17,62
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusExitDetail.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusExitDetail/CusExitDetail.cs:19,50
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusGoodsLocation.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusGoodsLocation/CusGoodsLocation.cs:21,57
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusGoodsLocation.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC6/CusGoodsLocation/CusGoodsLocation.cs:14,58
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusEUEntryHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusEUEntryHeader/CusEUEntryHeader.cs:44,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageRegHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/CusTempStorageRegHeader/CusTempStorageRegHeader.cs:26,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusExitItem.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusExitItem/CusExitItem.cs:17,48
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusExitItemPackage.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusExitItem/Package/CusExitItemPackage.cs:20,59
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.PackingGroup.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/PackingGroup/PackingGroup.cs:22,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.JobDeclaration.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/JobDeclaration/JobDeclaration.cs:66,55
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageLineItem.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC5/CusTempStorageLineItem/CusTempStorageLineItem.cs:17,59
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusExitControlHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusExitControlHeader/CusExitControlHeader.cs:19,57
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusEntryInstruction.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusEntryInstruction/CusEntryInstruction.cs:47,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.JobComInvoiceHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/JobComInvoiceHeader/JobComInvoiceHeader.cs:45,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.CusEntryLine.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/CusEntryLine/CusEntryLine.cs:23,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.TemporaryStorageBill.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC6/TemporaryStorageHeader/TemporaryStorageBill.cs:20,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.TemporaryStorageHeader.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/UCC6/TemporaryStorageHeader/TemporaryStorageHeader.cs:38,63
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.Declaration.JobComInvoiceLine.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/Declaration/JobComInvoiceLine/JobComInvoiceLine.cs:72,58
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.EU.Business.CusTempStorage.CusTempStorageRegLine.TypeDecider")] // Enterprise/Product/Operations/Customs/EU/Core/Business/CusTempStorage/CusTempStorageRegLine/CusTempStorageRegLine.cs:22,58
[assembly: SuppressMessage("CargoWiseOne", "EDI003:Business Object Property Max Length Validation", Justification = "Baseline WI00752625", Scope = "member", Target = "~M:Enterprise.Customs.EU.Business.OperationalActions.UpdatePreviousDocumentsOperationalActionRunner.UpdatePreviousDocuments(Enterprise.Customs.EU.Business.OperationalActions.DeclarationUpdatePreviousDocumentsApplicator,Enterprise.Customs.EU.Business.Declaration.JobDeclaration,Enterprise.Services.OperationalActions.Support.IOperationalActionSectionLog)")] // Enterprise/Product/Operations/Customs/EU/Core/Business/OperationalActions/UpdatePreviousDocumentsOperationalActionRunner.cs:27,49
[assembly: SuppressMessage("CargoWiseOne", "EDI003:Business Object Property Max Length Validation", Justification = "Baseline WI00752625", Scope = "member", Target = "~M:Enterprise.Customs.EU.Business.OperationalActions.UpdatePreviousDocumentsOperationalActionRunner.UpdatePreviousDocuments(Enterprise.Customs.EU.Business.OperationalActions.DeclarationUpdatePreviousDocumentsApplicator,Enterprise.Customs.EU.Business.Declaration.JobDeclaration,Enterprise.Services.OperationalActions.Support.IOperationalActionSectionLog)")] // Enterprise/Product/Operations/Customs/EU/Core/Business/OperationalActions/UpdatePreviousDocumentsOperationalActionRunner.cs:46,46
