<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.US.AIM.Messaging</RootNamespace>
    <AssemblyName>Enterprise.Customs.US.AIM.Messaging</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.US.Messaging.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairList\AIMArrivalStatusCodes.cs">
      <DependentUpon>AIMArrivalStatusCodes.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairList\AIMErrorCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AIMErrorCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\AIMFreightStatusCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AIMFreightStatusCodes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\AIMTransferStatusCodes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AIMTransferStatusCodes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairList\AIMArrivalStatusCodes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AIMArrivalStatusCodes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.US.AIM.Messaging</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\AIMErrorCodes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AIM.Messaging</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AIMErrorCodes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\AIMFreightStatusCodes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AIM.Messaging</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AIMFreightStatusCodes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\AIMTransferStatusCodes.xml">
      <CustomToolNamespace>Enterprise.Customs.US.AIM.Messaging</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AIMTransferStatusCodes.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>