//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.Customs.Universal.Internal
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoRefCusTariffRelationship : EnterpriseBusinessObject
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "RefDatabase_RefCusTariffRelationship";
			public const string PK        = "ZZH_PK";

			public const string ZZH_TariffCode     = "ZZH_TariffCode";
			public const string ZZH_ZZ1_Tariff     = "ZZH_ZZ1_Tariff";
			public const string ZZH_ZZI_TariffType = "ZZH_ZZI_TariffType";

			public const int ZZH_TariffCodeMaxLength = 35;
		}

		#endregion

		protected AutoRefCusTariffRelationship(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return RefCusTariffRelationshipSchema.PK; }
		}

		#endregion

		#region Properties

		#region ZZH_TariffCode

		public virtual ZString ZZH_TariffCode
		{
			get {  return new ZString(GetValueFromRowSafely(RefCusTariffRelationshipSchema.ZZH_TariffCode)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = ZZH_TariffCodeInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZZH_TariffCode();
				}
			}
		}

		public virtual ZPropertyInfo ZZH_TariffCodeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefCusTariffRelationshipSchema.Constants.ZZH_TariffCode); }
		}

		#endregion

		#region ZZH_ZZ1_Tariff

		public virtual ZGuid ZZH_ZZ1_Tariff
		{
			get {  return new ZGuid(GetValueFromRowSafely(RefCusTariffRelationshipSchema.ZZH_ZZ1_Tariff)); }
			set
			{
				SetPropertyValue(ZZH_ZZ1_TariffInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZZH_ZZ1_Tariff();
				}
			}
		}

		public virtual ZPropertyInfo ZZH_ZZ1_TariffInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefCusTariffRelationshipSchema.Constants.ZZH_ZZ1_Tariff); }
		}

		#endregion

		#region ZZH_ZZI_TariffType

		public virtual ZGuid ZZH_ZZI_TariffType
		{
			get {  return new ZGuid(GetValueFromRowSafely(RefCusTariffRelationshipSchema.ZZH_ZZI_TariffType)); }
			set
			{
				SetPropertyValue(ZZH_ZZI_TariffTypeInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateZZH_ZZI_TariffType();
				}
			}
		}

		public virtual ZPropertyInfo ZZH_ZZI_TariffTypeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(RefCusTariffRelationshipSchema.Constants.ZZH_ZZI_TariffType); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[RefCusTariffRelationshipSchema.Constants.ZZH_TariffCode    ] = "";
			row[RefCusTariffRelationshipSchema.Constants.ZZH_ZZ1_Tariff    ] = Guid.Empty;
			row[RefCusTariffRelationshipSchema.Constants.ZZH_ZZI_TariffType] = Guid.Empty;
		}

		#endregion

		#region Lookups

		public RefCusTariffRelationshipLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual RefCusTariffRelationshipLookups GetNewLookups()
		{
			return new RefCusTariffRelationshipLookups(this);
		}

		RefCusTariffRelationshipLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public RefCusTariffRelationshipValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual RefCusTariffRelationshipValidation GetNewValidation()
		{
			return new RefCusTariffRelationshipValidation(this);
		}

		#endregion
	}
}
