using CargoWise.Data;
using CargoWise.DbUpgrader.Scripts.Definitions.Accounting.ARAP;
using NUnit.Framework;

namespace Enterprise.Build.Database.Script.Public.Accounting.ARAP
{
	[TestedType(typeof(ARAPTransactionsSP))]
	class ARAPTransactionsSPTest : DbCreateScriptTest
	{
		public void TestSampleCall()
		{
			TestConnection.ExecuteNonQuery("INSERT INTO dbo.AccPeriodManagement (AM_PK, AM_Period, AM_Year, AM_StartDate,AM_EndDate,AM_IsSubLedgerClosed,AM_IsGeneralLedgerClosed, AM_GC_Company) values (NEWID(), 200507,2005,'01/01/2005','1/31/2005 23:59',1,1,'878D7ACA-FFC3-49FC-9710-969CA0C0F2AC') INSERT INTO dbo.AccTransactionHeader (AH_PK,AH_Ledger,AH_TransactionType,AH_TransactionNum,AH_TransactionCount,AH_TransactionReference,AH_Desc,AH_InvoiceDate,AH_TransactionCategory,AH_DueDate,AH_InvoiceAmount,AH_GSTAmount,AH_WithholdingTax,AH_OSTotal,AH_RX_NKTransactionCurrency,AH_ExchangeRate,AH_AgePeriod,AH_PostPeriod,AH_PostDate,AH_ChequeOrReference,AH_ReceiptType,AH_CashBasisGSTIndicator,AH_CashBasisGSTRealisedToGL,AH_ChequeDrawer,AH_DrawerBank,AH_DrawerBranch,AH_InvoiceApproved,AH_ConsolidatedInvoiceRef,AH_FullyPaidDate,AH_InvoicePrinted,AH_IsCancelled,AH_DateClearedInCashbook,AH_NotAllocated,AH_OutstandingAmount,AH_PostedToEFT,AH_PostToGL,AH_ReceiptBatchNo,AH_TransactionCreatedByMatching,AH_InvoiceTerm,AH_InvoiceTermDays,AH_POST1,AH_POST2,AH_POST3,AH_POST4,AH_AB,AH_OH,AH_JH,AH_GB,AH_GE,AH_AG,AH_TransactionBelongsToGroup,AH_AH_InvoiceStatement,AH_PostedInternal,AH_GC,AH_SystemCreateUser)VALUES(newID(),'AP','DSC','00005013',1,'','DIRECT PAYMENT','01/05/2005 3:44:00:000PM','','01/05/2005 3:44:00:000PM',-30.0000,-1.0000,0.0000,-31.0000,'AUD',1.000000000,0,0,'01/05/2005  3:44:00:000PM','CASH','CSH',0,0,'CASH','','',0,'Test Ref 2',NULL,0,0,NULL,0,1.0000,0,1,'',0,'',0,0,0,0,0,NULL,'C3F842EF-3BE5-448C-BED3-0017B232C624',NULL,'FDD429D2-648C-4895-8F9F-06E90DED2BE5','2B67864D-42E9-4A43-A9C8-09D2083C4227',NULL,NULL,NULL,0,'878D7ACA-FFC3-49FC-9710-969CA0C0F2AC','E')");

			var result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = '200507', @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = '', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = '',  @PostDateTo = '', @DueDateFrom = '',  @DueDateTo = '', @InvoiceDateFrom = '',  @InvoiceDateTo = '', @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");

			AssertEquals("Result should have rows", 1, result.Rows.Count);
			AssertEquals("Field Description should be DIRECT PAYMENT", "DIRECT PAYMENT", result.Rows[0][9].ToString());
			AssertEquals("Field InvoiseRef2 should be Test Ref 2", "Test Ref 2", result.Rows[0][10].ToString());
			AssertEquals("Create User", "E", result.Rows[0]["OperatorInitials"].ToString());

			AssertEquals("Field[87] Name should be ComplianceSubType", "ComplianceSubType", result.Columns[87].ColumnName);
			AssertEquals("Field[88] Name should be ComplianceNumber", "ComplianceNumber", result.Columns[88].ColumnName);
			AssertEquals("Field ComplianceSubType should be Empty", "", result.Rows[0][87].ToString().Trim());
			AssertEquals("Field ComplianceNumber should be Empty", "", result.Rows[0][88].ToString().Trim());

			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = '2005-01-05',  @PostDateTo = '2005-01-06', @DueDateFrom = null,  @DueDateTo = null, @InvoiceDateFrom = null,  @InvoiceDateTo = null, @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 1, result.Rows.Count);
			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = '2005-01-05',  @PostDateTo = '2005-01-05', @DueDateFrom = null,  @DueDateTo = null, @InvoiceDateFrom = null,  @InvoiceDateTo = null, @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 0, result.Rows.Count);
			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = null,  @PostDateTo = null, @DueDateFrom = '2005-01-05',  @DueDateTo = '2005-01-06', @InvoiceDateFrom = null,  @InvoiceDateTo = null, @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 1, result.Rows.Count);
			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = null,  @PostDateTo = null, @DueDateFrom = '2005-01-05',  @DueDateTo = '2005-01-05', @InvoiceDateFrom = null,  @InvoiceDateTo = null, @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 0, result.Rows.Count);
			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = null,  @PostDateTo = null, @DueDateFrom = null,  @DueDateTo = null, @InvoiceDateFrom = '2005-01-05',  @InvoiceDateTo = '2005-01-06', @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 1, result.Rows.Count);
			result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = null, @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = 'Y', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = null,  @PostDateTo = null, @DueDateFrom = null,  @DueDateTo = null, @InvoiceDateFrom = '2005-01-05',  @InvoiceDateTo = '2005-01-05', @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");
			AssertEquals("Result should have rows", 0, result.Rows.Count);
		}

		public void TestWhenPostDateToIsNull()
		{
			TestConnection.ExecuteNonQuery("INSERT INTO dbo.AccPeriodManagement (AM_PK, AM_Period, AM_Year, AM_StartDate,AM_EndDate,AM_IsSubLedgerClosed,AM_IsGeneralLedgerClosed, AM_GC_Company) values (NEWID(), 200507,2005,'01/01/2005','1/31/2005 23:59',1,1,'878D7ACA-FFC3-49FC-9710-969CA0C0F2AC') INSERT INTO dbo.AccTransactionHeader (AH_PK,AH_Ledger,AH_TransactionType,AH_TransactionNum,AH_TransactionCount,AH_TransactionReference,AH_Desc,AH_InvoiceDate,AH_TransactionCategory,AH_DueDate,AH_InvoiceAmount,AH_GSTAmount,AH_WithholdingTax,AH_OSTotal,AH_RX_NKTransactionCurrency,AH_ExchangeRate,AH_AgePeriod,AH_PostPeriod,AH_PostDate,AH_ChequeOrReference,AH_ReceiptType,AH_CashBasisGSTIndicator,AH_CashBasisGSTRealisedToGL,AH_ChequeDrawer,AH_DrawerBank,AH_DrawerBranch,AH_InvoiceApproved,AH_ConsolidatedInvoiceRef,AH_FullyPaidDate,AH_InvoicePrinted,AH_IsCancelled,AH_DateClearedInCashbook,AH_NotAllocated,AH_OutstandingAmount,AH_PostedToEFT,AH_PostToGL,AH_ReceiptBatchNo,AH_TransactionCreatedByMatching,AH_InvoiceTerm,AH_InvoiceTermDays,AH_POST1,AH_POST2,AH_POST3,AH_POST4,AH_AB,AH_OH,AH_JH,AH_GB,AH_GE,AH_AG,AH_TransactionBelongsToGroup,AH_AH_InvoiceStatement,AH_PostedInternal,AH_GC,AH_SystemCreateUser)VALUES(newID(),'AP','DSC','00005013',1,'','DIRECT PAYMENT','01/05/2005 3:44:00:000PM','','01/05/2005 3:44:00:000PM',-30.0000,-1.0000,0.0000,-31.0000,'AUD',1.000000000,0,0,'01/05/2005  3:44:00:000PM','CASH','CSH',0,0,'CASH','','',0,'Test Ref 2',NULL,0,0,NULL,0,1.0000,0,1,'',0,'',0,0,0,0,0,NULL,'C3F842EF-3BE5-448C-BED3-0017B232C624',NULL,'FDD429D2-648C-4895-8F9F-06E90DED2BE5','2B67864D-42E9-4A43-A9C8-09D2083C4227',NULL,NULL,NULL,0,'878D7ACA-FFC3-49FC-9710-969CA0C0F2AC','E')");

			var result = DataUtils.GetDataTableFromQuery(TestConnection, "EXEC ARAPTransactionsSP @Period = '200507', @Company = '878D7ACA-FFC3-49FC-9710-969CA0C0F2AC', @Branch = 'FDD429D2-648C-4895-8F9F-06E90DED2BE5', @OrgList = null, @OrgGroupList = null, @BranchList = null, @CountryList = null, @ExCountryList = null, @SalesRepList = null, @OverLimitOnly = '', @AgeingOption = 'PER', @Day1 = '', @Day2 = '', @Day3 = '', @Day4 = '', @AccountsRelationShip = null, @ConsolidatedCategory = null, @SalesRepRoll = null, @SummaryOnly = null, @LedgerType = 'AP', @AgedByInvoiceDate = '', @CurrencyList = null, @IncludeDisbursement = '', @DisbursementTranOnly = '', @SettlementGroupList = null, @CreditRating = null, @ShowInInvoicedCurrency = '', @ShowLocalEquivalentTotal = '', @ShowAllTransactions = '', @PaymentStatus = '', @TransactionTypeList = 'DSC', @PostDateFrom = '',  @PostDateTo = null, @DueDateFrom = '',  @DueDateTo = '', @InvoiceDateFrom = '',  @InvoiceDateTo = '', @NotInActiveBatchTranOnly = 'Y', @GroupBy = '', @OrderBy = '', @OrgBranch = null,  @ShowAddUser = 'Y', @ShowOnlyAggregated = '', @CurrentDateTime = '7/27/2012 14:00', @ShowLineAmounts = ''");

			AssertEquals("Result should have rows", 1, result.Rows.Count);
		}
	}
}

