<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DocBuilderTemplateMerge.Testing</RootNamespace>
    <AssemblyName>Enterprise.DocBuilderTemplateMerge.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="FlexCel" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocBuilderTemplateMerge\DocBuilderTemplateMerge.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\DocBuilderTemplateMerge\Testing\*" />
  </ItemGroup>
</Project>