<Project>
    <ItemGroup>
        <Reference Include="CargoWise.ApplicationContext" />
        <Reference Include="CargoWise.Bi.Common" />
        <Reference Include="CargoWise.Bi.Deployment.ReportingServices" />
        <Reference Include="CargoWise.Bi.Registration" />
        <Reference Include="CargoWise.BrandManager" />
        <Reference Include="CargoWise.Common" />
        <Reference Include="CargoWise.ComponentModel" />
        <Reference Include="CargoWise.Data" />
        <Reference Include="CargoWise.DataProtection" />
        <Reference Include="CargoWise.DataProtection.SqlExtensions" />
        <Reference Include="CargoWise.Data.Providers.Common" />
        <Reference Include="CargoWise.Database.Shared" />
        <Reference Include="CargoWise.eHub.Adapter" />
        <Reference Include="CargoWise.eHub.Common" />
        <Reference Include="CargoWise.EntityFramework" />
        <Reference Include="CargoWise.EventReference" />
        <Reference Include="CargoWise.Definitions" />
        <Reference Include="CargoWise.Authentication.Primitives" />
        <Reference Include="CargoWise.Authentication.Glow.Ticketing" />
        <Reference Include="CargoWise.Glow.Model.Interfaces" />
        <Reference Include="CargoWise.Integration" />
        <Reference Include="CargoWise.IO" />
        <Reference Include="CargoWise.PAVE.Common.DTO" />
        <Reference Include="CargoWise.PAVE.Common.Interfaces" />
        <Reference Include="CargoWise.Reflection" />
        <Reference Include="CargoWise.ResourceStrings.Cache" />
        <Reference Include="CargoWise.Service.Traditional.Interface" />
        <Reference Include="CargoWise.Services.Calendar" />
        <Reference Include="CargoWise.Tools.DuplicateDetector" />
        <Reference Include="CargoWise.Workflow" />
        <Reference Include="CargoWise.ResourceStrings" />
        <Reference Include="CargoWise.Schema" />
        <Reference Include="CargoWise.Shared.40" />
        <Reference Include="CargoWise.Types" />
        <Reference Include="CargoWiseOne.WebInfrastructure" />
        <Reference Include="Enterprise.Accounting.APAutomation" />
        <Reference Include="Enterprise.Accounting.Business" />
        <Reference Include="Enterprise.Accounting.Integration" />
        <Reference Include="Enterprise.Billing.Integration" />
        <Reference Include="Enterprise.BufferManagement.Service" />
        <Reference Include="Enterprise.BufferManagement.Service.Shared" />
        <Reference Include="Enterprise.ComplianceRisk.Integration" />
        <Reference Include="Enterprise.Customs.Business" />
        <Reference Include="Enterprise.Customs.Common" />
        <Reference Include="Enterprise.Dash.Integration" />
        <Reference Include="Enterprise.Dash.Business" />
        <Reference Include="Enterprise.DataTransfer.Common" />
        <Reference Include="Enterprise.DeniedPartyScreening.Business" />
        <Reference Include="Enterprise.DeniedPartyScreening.Common" />
        <Reference Include="Enterprise.DeniedPartyScreening.GUI" />
        <Reference Include="Enterprise.DeniedPartyScreening.Integration" />
        <Reference Include="Enterprise.DocumentEngine" />
        <Reference Include="Enterprise.DocumentEngineCore" />
        <Reference Include="Enterprise.DocumentEngineIntegration" />
        <Reference Include="Enterprise.DocumentScanning.Business" />
        <Reference Include="Enterprise.DocumentScanning.Integration" />
        <Reference Include="Enterprise.DocumentScanning.Web" />
        <Reference Include="Enterprise.eHubMessaging.Business" />
        <Reference Include="Enterprise.Environment" />
        <Reference Include="Enterprise.eTail.Business" />
        <Reference Include="Enterprise.eTail.Integration" />
        <Reference Include="Enterprise.Freight" />
        <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
        <Reference Include="Enterprise.Freight.Common.Business" />
        <Reference Include="Enterprise.Freight.Forwarding.Business" />
        <Reference Include="Enterprise.Freight.Integration" />
        <Reference Include="Enterprise.Integration" />
        <Reference Include="Enterprise.Licensing.Core" />
        <Reference Include="Enterprise.MasterData.Business" />
        <Reference Include="Enterprise.MasterData.Common" />
        <Reference Include="Enterprise.MasterFiles.Business" />
        <Reference Include="Enterprise.MasterFiles.Business.Test" />
        <Reference Include="Enterprise.MasterFiles.DataTransfer" />
        <Reference Include="Enterprise.MasterFiles.Integration" />
        <Reference Include="Enterprise.MasterFiles.Tracking" />
        <Reference Include="Enterprise.Messaging.Business" />
        <Reference Include="Enterprise.Messaging.Integration" />
        <Reference Include="Enterprise.Packing.Business" />
        <Reference Include="Enterprise.Packing.Integration" />
        <Reference Include="Enterprise.Rating.Business" />
        <Reference Include="Enterprise.Rating.CarrierConnect" />
        <Reference Include="Enterprise.Rating.Integration" />
        <Reference Include="Enterprise.Registry.Business" />
        <Reference Include="Enterprise.Security" />
        <Reference Include="Enterprise.Security.Core" />
        <Reference Include="Enterprise.Tracking.Business" />
        <Reference Include="Enterprise.TransportBookings.Shared" />
        <Reference Include="Enterprise.TransportCommon.Shared" />
        <Reference Include="Enterprise.TransportConsignment.DataTransfer" />
        <Reference Include="Enterprise.TransportConsignment.Integration" />
        <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
        <Reference Include="Enterprise.UniversalDataBuss.Integration" />
        <Reference Include="Enterprise.UniversalDataBuss.Management" />
        <Reference Include="Enterprise.Warehouse.GateManagement.DataTransfer" />
        <Reference Include="Enterprise.Warehouse.GateManagement.Integration" />
        <Reference Include="Enterprise.Warehouse.Integration" />
        <Reference Include="Enterprise.ZArchitecture.Business" />
        <Reference Include="Enterprise.ZArchitecture.Core" />
        <Reference Include="Enterprise.ZArchitecture.GlowInterop" />
        <Reference Include="Enterprise.ZArchitecture.GUI" />
        <Reference Include="Enterprise.ZArchitecture.Modules" />
        <Reference Include="CargoWise.Odyssey.Schema" />
        <Reference Include="Enterprise.ZArchitecture.Web.Business" />
        <Reference Include="Enterprise.ZArchitecture.Web.Common" />
        <Reference Include="Enterprise.ZArchitecture.Web.GlobalBase" />
        <Reference Include="Enterprise.ZArchitecture.Web.GUI" />
        <Reference Include="Enterprise.ZArchitecture.Web.Utilities" />
        <Reference Include="FluentValidation" />
        <Reference Include="ICSharpCode.SharpZipLib" />
        <Reference Include="Microsoft.IdentityModel.Tokens" />
        <Reference Include="Newtonsoft.Json" />
        <Reference Include="Resources" />
        <Reference Include="ServiceManager.Integration.Abstractions" />
        <Reference Include="ServiceManager.Shared.CW" />
        <Reference Include="System.IdentityModel.Tokens.Jwt" />
        <Reference Include="System.Net.Http.Formatting" />
        <Reference Include="System.Web.Http.WebHost" />
        <Reference Include="WTG.Foundation.FrameworkExtensions" />
        <Reference Include="WTG.OpenIDConnect.Token" />
        <Reference Include="WTG.StaticAnalysis.Annotation" />
    </ItemGroup>
</Project>
