// ----------------------------------------------------------------------
// <auto-generated>
//      This code is auto-generated by the awesome NonPersistentBusinessObjectGenerator(tm)
//      Any changes to this file will be lost when the generator is next run.
// </auto-generated>
// ----------------------------------------------------------------------
using System;
using System.ComponentModel;
using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.Environment;

namespace Enterprise.Client.EDI.Registry.Business
{
	
	[System.CodeDom.Compiler.GeneratedCode("NonPersistentBusinessObjectGenerator", "1.0")]
	public abstract class AutoInternalIncidentLicenceSettings : Enterprise.Registry.Business.RegistryBusinessObjectTemplate, IObsoleteValidation
	{
		#region Schema
		public class Schema
		{
			public const string EdiProd_LicencePK = "EdiProd_LicencePK";
			public const string UAT_ALP_LicencePK = "UAT_ALP_LicencePK";
			public const string UAT_DPR_LicencePK = "UAT_DPR_LicencePK";
			public const string UAT_STD_LicencePK = "UAT_STD_LicencePK";
			public const string UAT_GPC_LicencePK = "UAT_GPC_LicencePK";
			public const string UAT_GPR_LicencePK = "UAT_GPR_LicencePK";
		}
		#endregion
		protected AutoInternalIncidentLicenceSettings()
		{
		}
		protected AutoInternalIncidentLicenceSettings(BusinessObjectFactory factory) : base(factory)
		{
		}
		protected AutoInternalIncidentLicenceSettings(Enterprise.ZArchitecture.Environment.FallbackLevel fallbackLevel) : base(fallbackLevel)
		{
		}
		protected AutoInternalIncidentLicenceSettings(Enterprise.ZArchitecture.Environment.FallbackLevel fallbackLevel, BusinessObjectFactory factory) : base(fallbackLevel, factory)
		{
		}
		#region EdiProd_LicencePK
		public virtual ZGuid EdiProd_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return ediProd_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(EdiProd_LicencePKInfo, ref ediProd_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateEdiProd_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo EdiProd_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.EdiProd_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid ediProd_LicencePK;
		public virtual void ValidateEdiProd_LicencePK()
		{
			EdiProd_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(EdiProd_LicencePKInfo);
		}
		#endregion
		#region UAT_ALP_LicencePK
		public virtual ZGuid UAT_ALP_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return uAT_ALP_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(UAT_ALP_LicencePKInfo, ref uAT_ALP_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateUAT_ALP_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo UAT_ALP_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.UAT_ALP_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid uAT_ALP_LicencePK;
		public virtual void ValidateUAT_ALP_LicencePK()
		{
			UAT_ALP_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(UAT_ALP_LicencePKInfo);
		}
		#endregion
		#region UAT_DPR_LicencePK
		public virtual ZGuid UAT_DPR_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return uAT_DPR_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(UAT_DPR_LicencePKInfo, ref uAT_DPR_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateUAT_DPR_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo UAT_DPR_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.UAT_DPR_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid uAT_DPR_LicencePK;
		public virtual void ValidateUAT_DPR_LicencePK()
		{
			UAT_DPR_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(UAT_DPR_LicencePKInfo);
		}
		#endregion
		#region UAT_STD_LicencePK
		public virtual ZGuid UAT_STD_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return uAT_STD_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(UAT_STD_LicencePKInfo, ref uAT_STD_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateUAT_STD_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo UAT_STD_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.UAT_STD_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid uAT_STD_LicencePK;
		public virtual void ValidateUAT_STD_LicencePK()
		{
			UAT_STD_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(UAT_STD_LicencePKInfo);
		}
		#endregion
		#region UAT_GPC_LicencePK
		public virtual ZGuid UAT_GPC_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return uAT_GPC_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(UAT_GPC_LicencePKInfo, ref uAT_GPC_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateUAT_GPC_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo UAT_GPC_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.UAT_GPC_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid uAT_GPC_LicencePK;
		public virtual void ValidateUAT_GPC_LicencePK()
		{
			UAT_GPC_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(UAT_GPC_LicencePKInfo);
		}
		#endregion
		#region UAT_GPR_LicencePK
		public virtual ZGuid UAT_GPR_LicencePK
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return uAT_GPR_LicencePK;
			}
			set
			{
				SetNonPersistentPropertyValue(UAT_GPR_LicencePKInfo, ref uAT_GPR_LicencePK, value);
				if (IsValidationSuspended)
				{
				}
				else
				{
					ValidateUAT_GPR_LicencePK();
				}
			}
		}
		public virtual ZPropertyInfo UAT_GPR_LicencePKInfo
		{
			get
			{
				return this.GetZPropertyInfo(Schema.UAT_GPR_LicencePK);
			}
		}
		[System.Diagnostics.DebuggerBrowsableAttribute(System.Diagnostics.DebuggerBrowsableState.Never)]
		private ZGuid uAT_GPR_LicencePK;
		public virtual void ValidateUAT_GPR_LicencePK()
		{
			UAT_GPR_LicencePKInfo.ClearAllNotifications();
			TypeValidation.CheckValidGuid(UAT_GPR_LicencePKInfo);
		}
		#endregion
		#region Validation
		protected override void RunPreSaveValidationCore()
		{
			ValidateEdiProd_LicencePK();
			ValidateUAT_ALP_LicencePK();
			ValidateUAT_DPR_LicencePK();
			ValidateUAT_STD_LicencePK();
			ValidateUAT_GPC_LicencePK();
			ValidateUAT_GPR_LicencePK();
			base.RunPreSaveValidationCore();
		}
		#endregion
		#region Implementation
		protected override void CopyValuesToClone(Enterprise.Registry.Business.RegistryBusinessObjectTemplate clone)
		{
			AutoInternalIncidentLicenceSettings target = ((AutoInternalIncidentLicenceSettings)(clone));
			base.CopyValuesToClone(target);
			target.ediProd_LicencePK = ediProd_LicencePK;
			target.uAT_ALP_LicencePK = uAT_ALP_LicencePK;
			target.uAT_DPR_LicencePK = uAT_DPR_LicencePK;
			target.uAT_STD_LicencePK = uAT_STD_LicencePK;
			target.uAT_GPC_LicencePK = uAT_GPC_LicencePK;
			target.uAT_GPR_LicencePK = uAT_GPR_LicencePK;
		}
		#endregion
		#region Xml Serialisation
		protected override void WriteElements(System.Xml.XmlWriter writer)
		{
			writer.WriteStartElement("EdiProd_LicencePK");
			writer.WriteValue(EdiProd_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("UAT_ALP_LicencePK");
			writer.WriteValue(UAT_ALP_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("UAT_DPR_LicencePK");
			writer.WriteValue(UAT_DPR_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("UAT_STD_LicencePK");
			writer.WriteValue(UAT_STD_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("UAT_GPC_LicencePK");
			writer.WriteValue(UAT_GPC_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("UAT_GPR_LicencePK");
			writer.WriteValue(UAT_GPR_LicencePK.ToString());
			writer.WriteEndElement();
			writer.WriteStartElement("LicenceEnterpriseKeys");
			WriteLicenceEnterpriseKeys(writer);
			writer.WriteEndElement();
		}
		protected override void ReadElements(Enterprise.Registry.Business.XmlReaderWrapper readerWrapper)
		{
			System.Xml.XmlReader reader = readerWrapper.Reader;
			try
			{
				isDeserialising = true;
				try
				{
					EdiProd_LicencePK = new ZGuid(reader.ReadElementString("EdiProd_LicencePK"));
				}
				catch (FormatException )
				{
					EdiProd_LicencePK = ZGuid.Empty;
				}
				try
				{
					UAT_ALP_LicencePK = new ZGuid(reader.ReadElementString("UAT_ALP_LicencePK"));
				}
				catch (FormatException )
				{
					UAT_ALP_LicencePK = ZGuid.Empty;
				}
				try
				{
					UAT_DPR_LicencePK = new ZGuid(reader.ReadElementString("UAT_DPR_LicencePK"));
				}
				catch (FormatException )
				{
					UAT_DPR_LicencePK = ZGuid.Empty;
				}
				try
				{
					UAT_STD_LicencePK = new ZGuid(reader.ReadElementString("UAT_STD_LicencePK"));
				}
				catch (FormatException )
				{
					UAT_STD_LicencePK = ZGuid.Empty;
				}
				try
				{
					UAT_GPC_LicencePK = new ZGuid(reader.ReadElementString("UAT_GPC_LicencePK"));
				}
				catch (FormatException )
				{
					UAT_GPC_LicencePK = ZGuid.Empty;
				}
				try
				{
					UAT_GPR_LicencePK = new ZGuid(reader.ReadElementString("UAT_GPR_LicencePK"));
				}
				catch (FormatException )
				{
					UAT_GPR_LicencePK = ZGuid.Empty;
				}
				ReadLicenceEnterpriseKeys(reader);
			}
			finally
			{
				isDeserialising = false;
			}
		}
		protected bool IsDeserialising
		{
			[System.Diagnostics.DebuggerStepThrough]
			get
			{
				return isDeserialising;
			}
		}
		private bool isDeserialising;
		protected abstract void WriteLicenceEnterpriseKeys(System.Xml.XmlWriter writer);
		protected abstract void ReadLicenceEnterpriseKeys(System.Xml.XmlReader reader);
		#endregion
	}
}
