<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.UniversalXMLProducers.USSIMDataPopulator.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.UniversalXMLProducers.USSIMDataPopulator.Test</AssemblyName>
    <Configurations>Debug</Configurations>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.DbUpgrade">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.DbUpgrade.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Include="TestFiles\Download1b888426-c871-77bc-496f-e457f38be151\PDFSnippet.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="TestFiles\Downloadbcd5d4a5-4890-f7ac-4e8c-eacd3d163ddd\TestFiles.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="TestFiles\Download290949ab-ebde-2fb5-4678-20c2ca670eaa\XlsxSnippet.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\USSIMDataPopulator\USSIMDataPopulator.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="CargoWise.RefDbRepo.UniversalXMLProducers.USSIMDataPopulator.Test.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFiles\DownloadD7177A76-9C34-4892-B1D5-67A3F852C80C\ThreeAlphaCodes.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>