<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.Customs.Module.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module\Enterprise.Customs.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="BaseJobDeclaration\OrderNumberOwnersRefSpecificFieldSubGroupTest_OrCategories.sql" />
  </ItemGroup>
</Project>