<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <RootNamespace>Enterprise.Customs.Module.Test</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.TransportCommon.Business" />
    <Reference Include="Moq" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="BaseJobDeclaration\OrderNumberOwnersRefSpecificFieldSubGroupTest_OrCategories.sql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module\Enterprise.Customs.Module.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
  </ItemGroup>
</Project>