<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Enterprise.Accounting.DataTransfer.Testing</AssemblyName>
    <RootNamespace>Enterprise.Accounting.DataTransfer.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\..\..\..\..\Bin\</OutputPath>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DEBUGFAST|AnyCPU'">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_CanceledTransaction.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_CEX.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_CRE1.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_CRE2.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_CRE3.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP1.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP2.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP3.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP_Original.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_EXP_TaxBranch.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_TransactionBelongsToGroup_Apportionments.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_TransactionBelongsToGroup_MLI.xml" />
    <None Remove="AccBatchRequest\Testing\AccBatchRequests_ZeroTax.xml" />
    <None Remove="BankStatement\Testing\ANZ_NZ_BankStatement.csv" />
    <None Remove="BankStatement\Testing\ANZ_NZ_BankStatement_ForTest.csv" />
    <None Remove="BankStatement\Testing\InvalidBankStatement_Character.xml" />
    <None Remove="BankStatement\Testing\InvalidBankStatement_Currency.xml" />
    <None Remove="BankStatement\Testing\InvalidBankStatement_Format.xml" />
    <None Remove="BankStatement\Testing\InvalidBankStatement_NewSchema.xml" />
    <None Remove="BankStatement\Testing\InvalidBankStatement_StatementDate.xml" />
    <None Remove="BankStatement\Testing\NabBankStatement.csv" />
    <None Remove="BankStatement\Testing\ValidBankStatement.xml" />
    <None Remove="BankStatement\Testing\ValidBankStatement_NewSchema.xml" />
    <None Remove="BankStatement\Testing\WestpacNZBankStatement.CSV" />
    <None Remove="BankStatement\Testing\WestpacNZBankStatementINVALIDCOLUMNS.CSV" />
    <None Remove="ComplianceReport\SAFT\TestFiles\SAFT1_30\SAFT-NO GeneralLedgerAccounts.xml" />
    <None Remove="EInvoicing\Egypt\Xml\AmendingCreditNote.xml" />
    <None Remove="EInvoicing\Egypt\Xml\CreditNote.xml" />
    <None Remove="EInvoicing\Egypt\Xml\InvoiceAUD.xml" />
    <None Remove="EInvoicing\Egypt\Xml\InvoiceEGP.xml" />
    <None Remove="EInvoicing\Egypt\Xml\ReversingCreditNote.xml" />
    <None Remove="EInvoicing\Egypt\Xml\ReversingInvoice.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ApplicationContext.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Async">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Async.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.BrandManager">
      <HintPath>..\..\..\..\..\Bin\CargoWise.BrandManager.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ComponentModel">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ComponentModel.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Database.Shared">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Database.Shared.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Definitions">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Definitions.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework.Testing">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.Testing.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.FeatureControl.Abstractions">
      <HintPath>..\..\..\..\..\Bin\CargoWise.FeatureControl.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Integration">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.IO">
      <HintPath>..\..\..\..\..\Bin\CargoWise.IO.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings.Cache">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ResourceStrings.Cache.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Shared.40">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Shared.40.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Types">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Types.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.UniversalCopy">
      <HintPath>..\..\..\..\..\Bin\CargoWise.UniversalCopy.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Windows.UI">
      <HintPath>..\..\..\..\..\bin\CargoWise.Windows.UI.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ResourceStrings.dll</HintPath>
    </Reference>
    <Reference Include="DocumentWrappers">
      <HintPath>..\..\..\..\..\Bin\DocumentWrappers.dll</HintPath>
    </Reference>
    <Reference Include="DocumentWrappersCore">
      <HintPath>..\..\..\..\..\Bin\DocumentWrappersCore.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Accounting.CountryCompliance.Interfaces">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Accounting.CountryCompliance.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Accounting.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Accounting.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Accounting.Netting">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Accounting.Netting.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Billing.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Billing.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Billing.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Billing.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ComplianceRisk.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ComplianceRisk.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Common">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DataTransfer">
      <HintPath>..\..\..\..\..\bin\Enterprise.DataTransfer.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DataTransfer.GUI">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DataTransfer.GUI.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DataTransfer.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DataTransfer.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DataTransfer.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DataTransfer.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngine">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DocumentEngine.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineCore">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DocumentEngineCore.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineIntegration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DocumentEngineIntegration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.EConversation.Business">
      <HintPath>..\..\..\..\..\bin\Enterprise.EConversation.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.eHubMessaging.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.eHubMessaging.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Environment">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Environment.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight">
      <HintPath>..\..\..\..\..\bin\Enterprise.Freight.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.CarbonEmissions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Agency.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Agency.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Common.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Common.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.DataTransfer">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.DataTransfer.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.DataTransfer">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.DataTransfer.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.LocalCartage.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.LocalCartage.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.LogWalker">
      <HintPath>..\..\..\..\..\Bin\Enterprise.LogWalker.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.LogWalker.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.LogWalker.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterData.Common">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterData.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Integration.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Integration.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Messaging.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Messaging.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Messaging.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Messaging.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Packing.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Packing.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Rating.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Rating.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Registry.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Registry.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ResourceStrings.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ResourceStrings.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Security.Core">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Security.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ServiceManager.Shared">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ServiceManager.Shared.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test">
      <HintPath>..\..\..\..\..\Bin\ServiceManager.Integration.ServiceTasks.CW.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ServiceManager.Tasks.StandardXMLProcessor">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ServiceManager.Tasks.StandardXMLProcessor.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Services.OperationalActions.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Services.OperationalActions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Services.ServiceHost">
      <HintPath>..\..\..\..\..\bin\Enterprise.Services.ServiceHost.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.TransportBookings.Shared">
      <HintPath>..\..\..\..\..\Bin\Enterprise.TransportBookings.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects">
      <HintPath>..\..\..\..\..\Bin\Enterprise.UniversalDataBuss.DataObjects.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.UniversalDataBuss.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.Management">
      <HintPath>..\..\..\..\..\Bin\Enterprise.UniversalDataBuss.Management.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.ServiceTasks">
      <HintPath>..\..\..\..\..\bin\Enterprise.UniversalDataBuss.ServiceTasks.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.Testing">
      <HintPath>..\..\..\..\..\Bin\Enterprise.UniversalDataBuss.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO">
      <HintPath>..\..\..\..\..\Bin\Enterprise.UniversalDataBuss.XmlIO.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.GUI">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.GUI.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.SqlServer.Types">
      <HintPath>..\..\..\..\..\bin\Microsoft.SqlServer.Types.dll</HintPath>
    </Reference>
    <Reference Include="Moq">
      <HintPath>..\..\..\..\..\Bin\Moq.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\..\Bin\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore.ExtendedAssertions">
      <HintPath>..\..\..\..\..\Bin\NUnitCore.ExtendedAssertions.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\..\..\Bin\Resources.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Shared.Abstractions">
      <HintPath>..\..\..\..\..\Bin\ServiceManager.Shared.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\..\..\..\Bin\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.Http">
      <HintPath>..\..\..\..\..\bin\System.Web.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services" />
    <Reference Include="ServiceManager.Integration.Abstractions">
      <HintPath>..\..\..\..\..\Bin\ServiceManager.Integration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW">
      <HintPath>..\..\..\..\..\Bin\ServiceManager.Integration.ServiceTasks.CW.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_CanceledTransaction.xml">
      <LogicalName>AccBatchRequests_CanceledTransaction.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_CEX.xml">
      <LogicalName>AccBatchRequests_CEX.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_CRE1.xml">
      <LogicalName>AccBatchRequests_CRE1.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_CRE2.xml">
      <LogicalName>AccBatchRequests_CRE2.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_CRE3.xml">
      <LogicalName>AccBatchRequests_CRE3.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP.xml">
      <LogicalName>AccBatchRequests_EXP.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP1.xml">
      <LogicalName>AccBatchRequests_EXP1.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP2.xml">
      <LogicalName>AccBatchRequests_EXP2.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP3.xml">
      <LogicalName>AccBatchRequests_EXP3.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP_Original.xml">
      <LogicalName>AccBatchRequests_EXP_Original.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_EXP_TaxBranch.xml">
      <LogicalName>AccBatchRequests_EXP_TaxBranch.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_TransactionBelongsToGroup_Apportionments.xml">
      <LogicalName>AccBatchRequests_TransactionBelongsToGroup_Apportionments.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_TransactionBelongsToGroup_MLI.xml">
      <LogicalName>AccBatchRequests_TransactionBelongsToGroup_MLI.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="AccBatchRequest\Testing\AccBatchRequests_ZeroTax.xml">
      <LogicalName>AccBatchRequests_ZeroTax.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\ANZ_NZ_BankStatement.csv">
      <LogicalName>ANZ_NZ_BankStatement.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\ANZ_NZ_BankStatement_ForTest.csv">
      <LogicalName>ANZ_NZ_BankStatement_ForTest.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\InvalidBankStatement_Character.xml">
      <LogicalName>InvalidBankStatement_Character.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\InvalidBankStatement_Currency.xml">
      <LogicalName>InvalidBankStatement_Currency.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\InvalidBankStatement_Format.xml">
      <LogicalName>InvalidBankStatement_Format.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\InvalidBankStatement_NewSchema.xml">
      <LogicalName>InvalidBankStatement_NewSchema.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\InvalidBankStatement_StatementDate.xml">
      <LogicalName>InvalidBankStatement_StatementDate.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\NabBankStatement.csv">
      <LogicalName>NabBankStatement.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\ValidBankStatement.xml">
      <LogicalName>ValidBankStatement.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\ValidBankStatement_NewSchema.xml">
      <LogicalName>ValidBankStatement_NewSchema.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\WestpacNZBankStatement.CSV">
      <LogicalName>WestpacNZBankStatement.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="BankStatement\Testing\WestpacNZBankStatementINVALIDCOLUMNS.CSV">
      <LogicalName>WestpacNZBankStatementINVALIDCOLUMNS.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="ComplianceReport\SAFT\TestFiles\SAFT1_30\SAFT-NO GeneralLedgerAccounts.xml" />
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\AmendingCreditNote.xml">
      <LogicalName>AmendingCreditNote.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\CreditNote.xml">
      <LogicalName>CreditNote.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\InvoiceAUD.xml">
      <LogicalName>InvoiceAUD.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\InvoiceEGP.xml">
      <LogicalName>InvoiceEGP.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\ReversingCreditNote.xml">
      <LogicalName>ReversingCreditNote.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="EInvoicing\Egypt\Xml\ReversingInvoice.xml">
      <LogicalName>ReversingInvoice.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_022022_Small.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_022022_TaxRateAsFraction.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_022022_WrongData.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_022022_WrongFileStructure.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_022022_ValidationIsSuspended.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_StartDateInvalidFormat.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_EndDateInvalidFormat.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_RateWithInvalidCulture.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_OrganizationWithNonNumericCharacters.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_DistinctNumberOfColumnsInFormat.txt" />
    <EmbeddedResource Include="OrganisationTaxRateFileImport\TestFiles\PadronesCABA_PipeDelimiter.txt" />
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT19581_2004\DataAdapter\TestXML\ChinaStandard2004.xml">
      <LogicalName>ChinaStandard2004.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT19581_2004\DataAdapter\TestXML\EmptyChinaStandard2004.xml">
      <LogicalName>EmptyChinaStandard2004.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\ARAPData.xml">
      <LogicalName>ARAPData.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\EmptyARAPData.xml">
      <LogicalName>EmptyARAPData.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\EmptyFixedAssets.xml">
      <LogicalName>EmptyFixedAssets.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\EmptyGeneralLedger.xml">
      <LogicalName>EmptyGeneralLedger.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\EmptyPayrolls.xml">
      <LogicalName>EmptyPayrolls.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\EmptyReferenceFiles.xml">
      <LogicalName>EmptyReferenceFiles.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\FixedAssets.xml">
      <LogicalName>FixedAssets.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\GeneralLedger.xml">
      <LogicalName>GeneralLedger.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\Payrolls.xml">
      <LogicalName>Payrolls.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\DataInterface\ChinaStandard_GBT24589_1\DataAdapter\TestXML\ReferenceFiles.xml">
      <LogicalName>ReferenceFiles.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\EmptyJournal.xml">
      <LogicalName>EmptyJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\FullyPopulatedFCBJournal.xml">
      <LogicalName>FullyPopulatedFCBJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\FullyPopulatedJournal.xml">
      <LogicalName>FullyPopulatedJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\GJLJournalWithInvalidCurrency.xml">
      <LogicalName>GJLJournalWithInvalidCurrency.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\GJLJournalWithMultipleSubAccounts.xml">
      <LogicalName>GJLJournalWithMultipleSubAccounts.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\InvalidGLJournal.xml">
      <LogicalName>InvalidGLJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\PopulatedNoteJournal.xml">
      <LogicalName>PopulatedNoteJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\PopulatedReversingJournal.xml">
      <LogicalName>PopulatedReversingJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\SemiPopulatedJournal.xml">
      <LogicalName>SemiPopulatedJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidAJLJournal.xml">
      <LogicalName>ValidAJLJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidFCBJournal.xml">
      <LogicalName>ValidFCBJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJL2Journals.xml">
      <LogicalName>ValidGJL2Journals.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJLJournaBrnDept.xml">
      <LogicalName>ValidGJLJournaBrnDept.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJLJournal.xml">
      <LogicalName>ValidGJLJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJLJournalWithCurrency.xml">
      <LogicalName>ValidGJLJournalWithCurrency.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJLJournalWithDifferentDecimalPlaces.xml">
      <LogicalName>ValidGJLJournalWithDifferentDecimalPlaces.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidGJLJournalWithoutCurrency.XML">
      <LogicalName>ValidGJLJournalWithoutCurrency.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidNJLJournal.xml">
      <LogicalName>ValidNJLJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\GLJournal\Testing\ValidRJLJournal.xml">
      <LogicalName>ValidRJLJournal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\BackwardCompatibilitySaveTaxTransaction.xml">
      <LogicalName>BackwardCompatibilitySaveTaxTransaction.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\EmptyIncompleteInvoice.xml">
      <LogicalName>EmptyIncompleteInvoice.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoice.xml">
      <LogicalName>FullyPopulatedIncompleteInvoice.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoiceAfterAddExchangeRate.xml">
      <LogicalName>FullyPopulatedIncompleteInvoiceAfterAddExchangeRate.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoiceBeforeAddExchangeRate.xml">
      <LogicalName>FullyPopulatedIncompleteInvoiceBeforeAddExchangeRate.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoiceBeforeLocalAmountsAdded.xml">
      <LogicalName>FullyPopulatedIncompleteInvoiceBeforeLocalAmountsAdded.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoiceBeforeVATRecoverableAdded.xml">
      <LogicalName>FullyPopulatedIncompleteInvoiceBeforeVATRecoverableAdded.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\FullyPopulatedIncompleteInvoiceMultipleConsolCost.xml">
      <LogicalName>FullyPopulatedIncompleteInvoiceMultipleConsolCost.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\IncompleteTransaction\Testing\SemiPopulatedIncompleteInvoice.xml">
      <LogicalName>SemiPopulatedIncompleteInvoice.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\ARAPPayments\Testing\EmptyPayment.xml">
      <LogicalName>EmptyPayment.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\BalanceConversion\Testing\Joutnal.xml">
      <LogicalName>Joutnal.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\Invoice\Testing\ARInvoiceWithJob.xml">
      <LogicalName>ARInvoiceWithJob.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\Invoice\Testing\EmptyInvoice_Whidbey.xml">
      <LogicalName>EmptyInvoice_Whidbey.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\Invoice\Testing\FullyPopulatedInvoice.xml">
      <LogicalName>FullyPopulatedInvoice.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\TxnHeader\Invoice\Testing\SemiPopulatedInvoice_Whidbey.xml">
      <LogicalName>SemiPopulatedInvoice_Whidbey.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\WipAccrual\Testing\PostedAccrual.xml">
      <LogicalName>PostedAccrual.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\WipAccrual\Testing\PostedWIP.xml">
      <LogicalName>PostedWIP.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\WipAccrual\Testing\ReversedAccrual.xml">
      <LogicalName>ReversedAccrual.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="..\Accounting.DataTransfer\WipAccrual\Testing\ReversedWIP.xml">
      <LogicalName>ReversedWIP.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Content Include="ComplianceReport\TW.VAT\TestFiles\PurchaseAndSalesVAT.txt" />
    <Content Include="ComplianceReport\TW.VAT\TestFiles\ZeroRatedSalesVAT.txt" />
    <Content Include="ComplianceReport\TW.VAT\TestFiles\ZeroRatedSalesVATForZNGSubType.txt" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounting.DataTransfer\Accounting.DataTransfer.csproj" />
    <ProjectReference Include="..\Accounting.TaxFramework\Business\Accounting.TaxFramework.Business.csproj" />
    <ProjectReference Include="..\Accounting.Utility.Testing\Accounting.Utility.Testing.csproj" />
    <ProjectReference Include="..\Business.Testing\Accounting.Business.Testing.csproj" />
    <ProjectReference Include="..\Business\Accounting.Business.csproj" />
    <ProjectReference Include="..\Export\Accounting.Export.csproj" />
  </ItemGroup>
</Project>