<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Freight.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.Freight.Module.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
    <Configurations>Debug;DEBUGFAST</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Freight.GUI\Enterprise.Freight.GUI.Winzor.csproj" />
    <ProjectReference Include="..\Freight.Module\Enterprise.Freight.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.Freight.DataTransfer" />
    <Reference Include="Enterprise.Freight.OnlineSailingSchedules" />
    <Reference Include="Enterprise.Freight.SailingScheduleDataVendor" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>