<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Services\OcmPoc.Core.Services.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageInterfaces\OcmPoc.Infrastructure.MessageInterfaces.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageHistory.SqlServer\OcmPoc.Infrastructure.MessageHistory.SqlServer.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageQueue.Rabbit\OcmPoc.Infrastructure.MessageQueue.Rabbit.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageInterfaces\OcmPoc.Infrastructure.MessageInterfaces.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageRepository.Mongo\OcmPoc.Infrastructure.MessageRepository.Mongo.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MessageTracking.Kafka\OcmPoc.Infrastructure.MessageTracking.Kafka.csproj" />
    <ProjectReference Include="..\..\Miscellaneous\Utils\OcmPoc.Utils.csproj" />
  </ItemGroup>

</Project>
