<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.TransportCommon.DataTransfer.Testing</RootNamespace>
    <AssemblyName>Enterprise.TransportCommon.DataTransfer.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Test" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer.Testing" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Business" />
    <Reference Include="Enterprise.Packing.Business.Test" />
    <Reference Include="Enterprise.Packing.DataTransfer" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.UniversalDataBuss.Testing" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransportCommon.Business.Test\TransportCommon.Business.Test.csproj" />
    <ProjectReference Include="..\TransportCommon.Business\TransportCommon.Business.csproj" />
    <ProjectReference Include="..\TransportCommon.Shared\TransportCommon.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransportCommon.DataTransfer\TransportCommon.DataTransfer.csproj" />
  </ItemGroup>
</Project>