<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://www.backend-rates.ezv.admin.ch/xmldaily" 
	xmlns="https://www.backend-rates.ezv.admin.ch/xmldaily"
	elementFormDefault="qualified">
	<xs:element name="wechselkurse">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="datum" type="xs:string" />
				<xs:element name="zeit" type="xs:string" />
				<xs:element name="gueltigkeit" type="xs:string" />
				<xs:element name="devise" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="land_de" type="xs:string" />
							<xs:element name="land_fr" type="xs:string" />
							<xs:element name="land_it" type="xs:string" />
							<xs:element name="land_en" type="xs:string" />
							<xs:element name="waehrung" type="xs:string" />
							<xs:element name="kurs" type="xs:double" />
						</xs:sequence>
						<xs:attribute name="code" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
