<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Warehouse.GateManagement.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.Warehouse.GateManagement.GUI.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GateManagement.GUI\GateManagement.GUI.Winzor.csproj" />
    <ProjectReference Include="..\Business\GateManagement.Business.csproj" />
    <ProjectReference Include="..\GateManagement.Integration\GateManagement.Integration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.Warehouse.Environment.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="WinzorFramework" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="CargoWise.Odyssey.Schema" />
  </ItemGroup>
</Project>