<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Warehouse.GateManagement.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.Warehouse.GateManagement.GUI.Test</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GateManagement.GUI\GateManagement.GUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings.Cache.Test" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Warehouse.Environment.Business"/>
    <Reference Include="Enterprise.Warehouse.Integration" />
  </ItemGroup>
</Project>
