<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <RootNamespace>Enterprise.Customs.GB.Module.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.EU.GUI" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Moq" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.GB.Business.csproj" />
    <ProjectReference Include="..\Ccsuk.Test\Enterprise.Customs.GB.Ccsuk.Test.csproj" />
    <ProjectReference Include="..\Ccsuk\Enterprise.Customs.GB.Ccsuk.csproj" />
    <ProjectReference Include="..\CDS\Enterprise.Customs.GB.CDS.csproj" />
    <ProjectReference Include="..\Chief\Enterprise.Customs.GB.Chief.csproj" />
    <ProjectReference Include="..\GUI\Enterprise.Customs.GB.GUI.csproj" />
    <ProjectReference Include="..\Module\Enterprise.Customs.GB.Module.csproj" />
    <ProjectReference Include="..\Registry\Enterprise.Customs.GB.Registry.csproj" />
  </ItemGroup>
</Project>