<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.UniversalCopy" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Moq" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Agency.GUI\Enterprise.Freight.Agency.GUI.csproj" />
    <ProjectReference Include="..\Agency.Module\Enterprise.Freight.Agency.Module.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
</Project>