//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Universal
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoRefCusNomenclatureGroupTypeValidation : ZValidation
	{
		protected AutoRefCusNomenclatureGroupTypeValidation(AutoRefCusNomenclatureGroupType Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoRefCusNomenclatureGroupTypeValidation); }
		}

		/// <summary>
		/// Add more validation to the RefCusNomenclatureGroupType's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoRefCusNomenclatureGroupTypeValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The RefCusNomenclatureGroupType's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoRefCusNomenclatureGroupTypeValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region ZZ9_Description

		public void ValidateZZ9_Description()
		{
			ZValidationInternals.Validate(Parent.ZZ9_DescriptionInfo, GetZZ9_DescriptionValidationInvoker());
		}

		RunValidationInvoker GetZZ9_DescriptionValidationInvoker()
		{
			return delegate
			{
				CheckZZ9_DescriptionIsNotEmpty();
				CheckZZ9_Description();
			};
		}

		protected virtual void CheckZZ9_DescriptionIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZ9_DescriptionInfo);
		}

		protected virtual void CheckZZ9_Description()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region ZZ9_GroupType

		public void ValidateZZ9_GroupType()
		{
			ZValidationInternals.Validate(Parent.ZZ9_GroupTypeInfo, GetZZ9_GroupTypeValidationInvoker());
		}

		RunValidationInvoker GetZZ9_GroupTypeValidationInvoker()
		{
			return delegate
			{
				CheckZZ9_GroupTypeIsNotEmpty();
				CheckZZ9_GroupTypeIsWesternEuropean();
				CheckZZ9_GroupType();
			};
		}

		protected virtual void CheckZZ9_GroupTypeIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.ZZ9_GroupTypeInfo);
		}

		protected virtual void CheckZZ9_GroupTypeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.ZZ9_GroupTypeInfo);
		}

		protected virtual void CheckZZ9_GroupType()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateZZ9_Description();
				ValidateZZ9_GroupType();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoRefCusNomenclatureGroupType Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
