using CargoWise.Types;

namespace Enterprise.Integration
{
	public static partial class Forwarding
	{
		public interface IForwardingContainer
		{
			ZGuid PK { get; }
			ZString JC_Additional2SealNum { get; set; }
			ZString JC_Additional2SealParty { get; set; }
			ZString JC_AdditionalSealNum { get; set; }
			ZString JC_AdditionalSealParty { get; set; }
			ZDecimal JC_AirVentFlow { get; set; }
			ZString JC_AirVentFlowRateUnit { get; set; }
			ZDateTime JC_ArrivalCartageAdvised { get; set; }
			ZDateTime JC_ArrivalCartageComplete { get; set; }
			ZString JC_ArrivalCartageRef { get; set; }
			ZDateTime JC_ArrivalDeliveryRequiredBy { get; set; }
			ZDateTime JC_ArrivalEstimatedDelivery { get; set; }
			ZBool JC_ArrivalPickupByRail { get; set; }
			ZDateTime JC_ArrivalSlotDateTime { get; set; }
			ZString JC_ArrivalSlotReference { get; set; }
			ZShort JC_ContainerCount { get; set; }
			ZString JC_ContainerImportDORelease { get; set; }
			ZString JC_ContainerJobID { get; set; }
			ZString JC_ContainerMode { get; set; }
			ZString JC_ContainerNotes { get; set; }
			ZString JC_ContainerNum { get; set; }
			ZString JC_ContainerQuality { get; set; }
			ZString JC_ContainerRating { get; set; }
			ZString JC_ContainerStatus { get; set; }
			ZString JC_ContainerStorageLocation { get; set; }
			ZDateTime JC_ContainerYardEmptyPickupGateOut { get; set; }
			ZDateTime JC_ContainerYardEmptyReturnGateIn { get; set; }
			ZDecimal JC_CostSpotRate { get; set; }
			ZString JC_CostSpotRateMode { get; set; }
			ZString JC_DeliveryMode { get; set; }
			ZShort JC_DeliverySequence { get; set; }
			ZDateTime JC_DepartureCartageAdvised { get; set; }
			ZDateTime JC_DepartureCartageComplete { get; set; }
			ZString JC_DepartureCartageRef { get; set; }
			ZBool JC_DepartureDeliveryByRail { get; set; }
			ZString JC_DepartureDockReceipt { get; set; }
			ZDateTime JC_DepartureEstimatedPickup { get; set; }
			ZDateTime JC_DepartureSlotDateTime { get; set; }
			ZString JC_DepartureSlotReference { get; set; }
			ZString JC_Description { get; set; }
			ZDecimal JC_DunnageWeight { get; set; }
			ZDateTime JC_EmptyReadyForReturn { get; set; }
			ZDateTime JC_EmptyRequired { get; set; }
			ZDateTime JC_EmptyReturnedBy { get; set; }
			ZString JC_ExportDepotCustomsReference { get; set; }
			ZString JC_F3_NKPackType { get; set; }
			ZDateTime JC_FCLAvailable { get; set; }
			ZBool JC_FCLHeldInTransitStaging { get; set; }
			ZDateTime JC_FCLOnBoardVessel { get; set; }
			ZBool JC_FCLStorageArrivedUnderbond { get; set; }
			ZDateTime JC_ArrivalCTOStorageStartDate { get; set; }
			ZString JC_FCLStorageModuleOnlyMaster { get; set; }
			ZDateTime JC_FCLStorageUnderbondCleared { get; set; }
			ZDateTime JC_FCLUnloadFromVessel { get; set; }
			ZDateTime JC_FCLWharfGateIn { get; set; }
			ZDateTime JC_FCLWharfGateOut { get; set; }
			ZDecimal JC_GatewaySellSpotRate { get; set; }
			ZString JC_GatewaySellSpotRateMode { get; set; }
			ZDecimal JC_GoodsValue { get; set; }
			ZDecimal JC_GrossVolume { get; set; }
			ZString JC_GrossVolumeUQ { get; set; }
			ZDecimal JC_GrossWeight { get; set; }
			ZString JC_GrossWeightUQ { get; set; }
			ZDateTime JC_GrossWeightVerificationDateTime { get; set; }
			ZString JC_GrossWeightVerificationStatus { get; set; }
			ZString JC_GrossWeightVerificationType { get; set; }
			ZString JC_HarmonisedCode { get; set; }
			ZByte JC_HumidityPercent { get; set; }
			ZBool JC_IsCFSRegistered { get; set; }
			ZBool JC_IsControlledAtmosphere { get; set; }
			ZBool JC_IsDamaged { get; set; }
			ZBool JC_IsEmptyContainer { get; set; }
			ZBool JC_IsSealOk { get; set; }
			ZBool JC_IsShipperOwned { get; set; }
			ZGuid JC_JK { get; set; }
			ZGuid JC_JS_FCLBookingOnlyLink { get; set; }
			ZGuid JC_JX { get; set; }
			ZDateTime JC_LCLAvailable { get; set; }
			ZDateTime JC_LCLStorageCommences { get; set; }
			ZDateTime JC_LCLUnpack { get; set; }
			ZString JC_MarksAndNumbers { get; set; }
			ZGuid JC_OA_ArrivalContainerYardAddress { get; set; }
			ZGuid JC_OA_DepartureContainerYardAddress { get; set; }
			ZGuid JC_OH_CFSClient { get; set; }
			ZGuid JC_OH_ShippingLine { get; set; }
			ZDecimal JC_OverhangBack { get; set; }
			ZDecimal JC_OverhangRight { get; set; }
			ZBool JC_OverrideFCLAvailableStorage { get; set; }
			ZBool JC_OverrideLCLAvailableStorage { get; set; }
			ZDateTime JC_PackDate { get; set; }
			ZString JC_Purpose { get; set; }
			ZGuid JC_RC { get; set; }
			ZGuid JC_RCA_AllocationLine { get; set; }
			ZString JC_RefrigGeneratorID { get; set; }
			ZString JC_ReleaseNum { get; set; }
			ZString JC_RH_NKContainerCommodityCode { get; set; }
			ZString JC_RX_NKCostSpotRateCurrency { get; set; }
			ZString JC_RX_NKGatewaySellSpotRateCurrency { get; set; }
			ZString JC_RX_NKGoodsCurrency { get; set; }
			ZString JC_RX_NKSellSpotRateCurrency { get; set; }
			ZString JC_SealNum { get; set; }
			ZString JC_SealParty { get; set; }
			ZDecimal JC_SellSpotRate { get; set; }
			ZString JC_SellSpotRateMode { get; set; }
			ZDecimal JC_SetPointTemp { get; set; }
			ZString JC_SetPointTempUnit { get; set; }
			ZString JC_StowagePosition { get; set; }
			ZDateTime JC_SystemCreateTimeUtc { get; set; }
			ZString JC_SystemCreateUser { get; set; }
			ZDateTime JC_SystemLastEditTimeUtc { get; set; }
			ZString JC_SystemLastEditUser { get; set; }
			ZDecimal JC_TareWeight { get; set; }
			ZString JC_TempRecorderSerialNo { get; set; }
			ZDecimal JC_TotalHeight { get; set; }
			ZDecimal JC_TotalLength { get; set; }
			ZString JC_TotalUnitOfMeasure { get; set; }
			ZDecimal JC_TotalWidth { get; set; }
			ZString JC_TrainWagonNumber { get; set; }
			ZString JC_UnpackGang { get; set; }
			ZString JC_UnpackShed { get; set; }
			ZString JC_VehicleColor { get; set; }
			ZString JC_VehicleMake { get; set; }
			ZString JC_VehicleModel { get; set; }
			ZByte JC_VehicleNumberOfDoors { get; set; }
			ZString JC_VehicleTransmission { get; set; }
			ZShort JC_VehicleYear { get; set; }
			ZDecimal JC_VolumeCapacity { get; set; }
			ZString JC_VolumeCapacityUQ { get; set; }
			ZDecimal JC_WeightCapacity { get; set; }
			ZString JC_WeightCapacityUQ { get; set; }
		}
	}
}
