namespace Enterprise.Customs.EFTA.TemporaryStorageRegister.Business;

public interface ITemporaryStorageRegisterTransactionDataProvider
{
	IEnumerable<TemporaryStorageRegisterTransactionData> GetTemporaryStorageRegisterTransactionData();
}
