<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Jeff.Liang\.nuget\packages\;C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages;C:\Program Files\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">6.8.1</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="C:\Users\Jeff.Liang\.nuget\packages\" />
    <SourceRoot Include="C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages\" />
    <SourceRoot Include="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\" />
  </ItemGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0001.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0001.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0001.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0004.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0004.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0004.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0005.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0005.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0005.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0006.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0006.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0006.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0007.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0007.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0007.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0008.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0008.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0008.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0009.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0009.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0009.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0010.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0010.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0010.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0011.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0011.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0011.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0012.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0012.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0012.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0013.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0013.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0013.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0014.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0014.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0014.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0015.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0015.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0015.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0016.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0016.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0016.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0017.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0017.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0017.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0018.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0018.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0018.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0019.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0019.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0019.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0020.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0020.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0020.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0021.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0021.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0021.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0022.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0022.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0022.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0023.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0023.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0023.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0024.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0024.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0024.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0025.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0025.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0025.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0026.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0026.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0026.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0027.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0027.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0027.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0028.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0028.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0028.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0029.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0029.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0029.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0030.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0030.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0030.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0031.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0031.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0031.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0032.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0032.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0032.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0033.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0033.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0033.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0034.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0034.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0034.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0035.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0035.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0035.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0036.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0036.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0036.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0037.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0037.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0037.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0038.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0038.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0038.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0039.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0039.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0039.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0040.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0040.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0040.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0041.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0041.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0041.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0042.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0042.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0042.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0043.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0043.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0043.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0044.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0044.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0044.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0045.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0045.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0045.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0047.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0047.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0047.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0048.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0048.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0048.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0049.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0049.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0049.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0050.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0050.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0050.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0051.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0051.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0051.txt</Link>
    </Content>
    <Content Include="$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0052.txt" Condition="Exists('$(NuGetPackageRoot)wtg.buildconfiguration.analysis.syslib\8.0.0\contentFiles\any\netstandard2.0\SYSLIBBannedSymbols\BannedSymbols.SYSLIB0052.txt')">
      <NuGetPackageId>WTG.BuildConfiguration.Analysis.SYSLIB</NuGetPackageId>
      <NuGetPackageVersion>8.0.0</NuGetPackageVersion>
      <NuGetItemType>Content</NuGetItemType>
      <Pack>false</Pack>
      <Private>False</Private>
      <Link>SYSLIBBannedSymbols\BannedSymbols.SYSLIB0052.txt</Link>
    </Content>
  </ItemGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)nunit\4.1.0\build\NUnit.props" Condition="Exists('$(NuGetPackageRoot)nunit\4.1.0\build\NUnit.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.testplatform.testhost\17.11.1\build\netcoreapp3.1\Microsoft.TestPlatform.TestHost.props" Condition="Exists('$(NuGetPackageRoot)microsoft.testplatform.testhost\17.11.1\build\netcoreapp3.1\Microsoft.TestPlatform.TestHost.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.codecoverage\17.11.1\build\netstandard2.0\Microsoft.CodeCoverage.props" Condition="Exists('$(NuGetPackageRoot)microsoft.codecoverage\17.11.1\build\netstandard2.0\Microsoft.CodeCoverage.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.net.test.sdk\17.11.1\build\netcoreapp3.1\Microsoft.NET.Test.Sdk.props" Condition="Exists('$(NuGetPackageRoot)microsoft.net.test.sdk\17.11.1\build\netcoreapp3.1\Microsoft.NET.Test.Sdk.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.aspnetcore.components.webassembly.authentication\8.0.10\buildTransitive\Microsoft.AspNetCore.Components.WebAssembly.Authentication.props" Condition="Exists('$(NuGetPackageRoot)microsoft.aspnetcore.components.webassembly.authentication\8.0.10\buildTransitive\Microsoft.AspNetCore.Components.WebAssembly.Authentication.props')" />
  </ImportGroup>
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgMicrosoft_CodeAnalysis_BannedApiAnalyzers Condition=" '$(PkgMicrosoft_CodeAnalysis_BannedApiAnalyzers)' == '' ">C:\Users\Jeff.Liang\.nuget\packages\microsoft.codeanalysis.bannedapianalyzers\3.3.4</PkgMicrosoft_CodeAnalysis_BannedApiAnalyzers>
  </PropertyGroup>
</Project>