<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreWindowsTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.IL.Manifest.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.IL.Manifest.Business</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Customs.IL.MessageContracts" />
    <Reference Include="CargoWise.Customs.IL.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.IL.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Billing.Integration" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="BusinessObjects\AsycudaPackedItems\AutoAsycudaLinkPackage.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoAsycudaLinkPackage.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILBillConditionList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILBillConditionList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILEmptyFullIndicatorList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILEmptyFullIndicatorList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILManifestTypes.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILManifestTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILManifestTypes_partial.cs">
      <DependentUpon>ILManifestTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILPackStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILPackStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILStatementCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILStatementCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILContentListForIsDirectDelivery.cs">
      <DependentUpon>ILContentListForIsDirectDelivery.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILStatementCodeListForActionCode.cs">
      <DependentUpon>ILStatementCodeListForActionCode.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILStatementCodeListForCargoType.cs">
      <DependentUpon>ILStatementCodeListForCargoType.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILStatementCodeListForExporterIDType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILStatementCodeListForExporterIDType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILUnloadedStates.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILUnloadedStates.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairList\ILSealTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ILSealTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Message\MessageSender\Manifest\AutoAsycudaManifestMessageSendingObject.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoAsycudaManifestMessageSendingObject.xml</DependentUpon>
    </Compile>
    <Compile Update="Message\MessageSender\Manifest\AutoAsycudaManifestQueryMessageSendingObject.cs">
      <DependentUpon>AutoAsycudaManifestQueryMessageSendingObject.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="BusinessObjects\AsycudaPackedItems\AutoAsycudaLinkPackage.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoAsycudaLinkPackage.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ILBillConditionList.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILBillConditionList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ILEmptyFullIndicatorList.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILEmptyFullIndicatorList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ILManifestTypes.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILManifestTypes.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ILPackStatusList.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILPackStatusList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ILStatementCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILStatementCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ILContentListForIsDirectDelivery.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <LastGenOutput>ILContentListForIsDirectDelivery.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairList\ILStatementCodeListForActionCode.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <LastGenOutput>ILStatementCodeListForActionCode.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairList\ILStatementCodeListForCargoType.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <LastGenOutput>ILStatementCodeListForCargoType.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairList\ILStatementCodeListForExporterIDType.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILStatementCodeListForExporterIDType.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairList\ILUnloadedStates.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILUnloadedStates.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairList\ILSealTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ILSealTypeList.cs</LastGenOutput>
    </None>
    <None Update="Message\MessageSender\Manifest\AutoAsycudaManifestMessageSendingObject.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoAsycudaManifestMessageSendingObject.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
    </None>
    <None Update="Message\MessageSender\Manifest\AutoAsycudaManifestQueryMessageSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.IL.Manifest.Business</CustomToolNamespace>
      <LastGenOutput>AutoAsycudaManifestQueryMessageSendingObject.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
