<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Customs.IE.MessageDefinitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.IE.Messaging" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\NCTSIncomingMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTSIncomingMessageTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NCTSOutgoingArrivalMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTSOutgoingArrivalMessageTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NCTSOutgoingDepartureMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTSOutgoingDepartureMessageTypeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\NCTSOutgoingMessageTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTSOutgoingMessageTypeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\NCTSIncomingMessageTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.IE.NCTS.Messaging</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTSIncomingMessageTypeList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\NCTSOutgoingArrivalMessageTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTSOutgoingArrivalMessageTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.NCTS.Messaging</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\NCTSOutgoingDepartureMessageTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTSOutgoingDepartureMessageTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.NCTS.Messaging</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\NCTSOutgoingMessageTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTSOutgoingMessageTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.IE.NCTS.Messaging</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>