// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1124:new CachedProperty", Scope = "namespaceanddescendants", Target = "~N:Enterprise.Customs.US.Business", Justification = "Properties using CachedProperty should use CachedValueHelper.")]
[assembly: SuppressMessage("CargoWiseOne", "CW1123:new CachedValue", Scope = "namespaceanddescendants", Target = "~N:Enterprise.Customs.US.Business", Justification = "Properties using CachedValue should use CachedValueHelper.")]
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~T:Enterprise.Customs.US.Business.Reports.InvoiceLineProductMatchDataSet")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Reports\InvoiceLineProductMatchDataSet.cs:2:127
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~T:Enterprise.Customs.US.Business.Reports.InvoiceLineProductMatchDataSet.InvoiceLineProductMatchDataSetDataTable")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Reports\InvoiceLineProductMatchDataSet.cs:5:128
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.ImportMessageSendingActionCollection.PopulateElements(System.Func{Enterprise.Customs.US.Business.CusEntryHeader,System.Boolean})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\MessageAction\ImportMessageSendingAction\Common\ImportMessageSendingActionCollection.cs:517:32
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.QueryTariff.ValidateRange")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\ReferenceFiles\QueryTariff.cs:132:24
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.MessageBuildingBlocks.BIRD.BRDDT.GetTime(CargoWise.Types.ZString,System.Int32@,System.Int32@,System.Int32@)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\CBPMessageBuildingBlocks\BIRD\BRDDT.cs:45:37
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.MessageBuildingBlocks.BIRD.BRDDT.GetTime(CargoWise.Types.ZString,System.Int32@,System.Int32@,System.Int32@)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\CBPMessageBuildingBlocks\BIRD\BRDDT.cs:45:52
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.MessageBuildingBlocks.BIRD.BRDDT.GetTime(CargoWise.Types.ZString,System.Int32@,System.Int32@,System.Int32@)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\CBPMessageBuildingBlocks\BIRD\BRDDT.cs:45:69
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.OGAAgencyRequirementCollectionCollectionTests.TestPopulate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\JobComInvoiceLine\PGA\OGAAgencyRequirementCollection.cs:235:213
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.OGAAgencyRequirementCollectionCollectionTests.TestPopulate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\JobComInvoiceLine\PGA\OGAAgencyRequirementCollection.cs:171:92
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.OGAAgencyRequirementCollectionCollectionTests.TestPopulate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\JobComInvoiceLine\PGA\OGAAgencyRequirementCollection.cs:172:93
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.OGAAgencyRequirementCollectionCollectionTests.TestPopulate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\JobComInvoiceLine\PGA\OGAAgencyRequirementCollection.cs:243:93
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.OGAAgencyRequirementCollectionCollectionTests.TestPopulate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\JobComInvoiceLine\PGA\OGAAgencyRequirementCollection.cs:255:94
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.StatementHeaderAccountingIntegrationTest.TestDoNotPopupPaidedErrorWhenEstimateDateEntered")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\Statement\CusStatementHeader\CusStatementHeader.cs:2723:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.Testing.StatementHeaderAccountingIntegrationTest.TestDoNotPopupPaidedErrorWhenEstimateDateEntered")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\US\Business\Business\Business\Statement\CusStatementHeader\CusStatementHeader.cs:2728:37
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.US.Business.GlbExternalPassword.TypeDecider")] // Enterprise/Product/Operations/Customs/US/Business/Business/GlbExternalPassword/GlbExternalPassword.cs:52,60
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.US.Business.MQEDIMessage.TypeDecider")] // Enterprise/Product/Operations/Customs/US/Business/Business/Business/EDIMessage/Shared/MQEDIMessage.cs:47,53
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.US.Business.EDIMessage.TypeDecider")] // Enterprise/Product/Operations/Customs/US/Business/Business/Business/EDIMessage/Shared/EDIMessage.cs:9,51
[assembly: SuppressMessage("CargoWiseOne", "EDI003:Business Object Property Max Length Validation", Justification = "Baseline WI00752625", Scope = "member", Target = "~M:Enterprise.Customs.US.Business.ReconFlatFileDataTransferProcessor.LocateEntry(Enterprise.Customs.US.Business.ReconFlattenedDataLine,Enterprise.Customs.US.Business.ReconDeclaration)")] // Enterprise/Product/Operations/Customs/US/Business/Business/Recon/ReconDataImport/ReconFlatFileDataTransferProcessor.cs:15,35
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.US.Business.CusStatementHeader.MonthlyDeletedLines")] // Enterprise/Product/Operations/Customs/US/Business/Business/Business/Statement/CusStatementHeader/CusStatementHeader.cs:552,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.US.DataRegistry.Business.ManagedAccount.BankAccountList")] // Enterprise/Product/Operations/Customs/US/Business/Business/Registry/ManagedAccounts/BrokersAccount.cs:182,5
