CREATE VIEW UNDGSubstanceRIDTableView_V2 AS
SELECT RID_PK,
RID_IsActive,
RID_UNNO,
RID_Variant,
RID_PSN,
RID_Class,
RID_ClassificationCode,
RID_PG,
RID_Labels,
RID_SpecialProvisions,
RID_LQMaxAmt,
RID_LQMaxAmtUQ,
RID_LQ2MaxAmt,
RID_LQ2MaxAmtUQ,
RID_ExceptedQuantityCode,
RID_PackIns,
RID_IBCIns,
RID_PackProv,
RID_MixedPackProv,
RID_BulkContainerTankIns,
RID_BulkContainerTankProv,
RID_TankCode,
RID_TankSpecProv,
RID_TransportCategory,
RID_CarriagePackagesSpecialProv,
RID_CarriageBulkSpecialProv,
RID_ColisExpressCode,
RID_HazardIDNumber,
RID_CarriageLoadingSpecialProv,
RID_MinCW1Version,
RID_MaxCW1Version
FROM UNDGSubstanceRID
