namespace Enterprise.Accounting.Business.AccountingCriticalValidationDependency
{
	public interface IAccountingCriticalValidationDependencyFactory
	{
		IAccountingCriticalValidationInfoCollectionHelper GetAccountingCriticalValidationInfoCollectionHelper();
	}
}
