<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Macros" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentVisualizer.Business" />
    <Reference Include="Enterprise.DocumentVisualizer.Core" />
    <Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
    <Reference Include="Enterprise.DocumentVisualizer.Integration" />
    <Reference Include="Enterprise.eTail.Business" />
    <Reference Include="Enterprise.eTail.Integration" />
    <Reference Include="Enterprise.ExcelTemplates.Integration" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Documents.DataObjects" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
