<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="Resources" />
    <Reference Include="Xware.Xt.Grpc.Config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Lists\EDIInterchangePriorityList.cs">
      <DependentUpon>EDIInterchangePriorityList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Lists\EDIInterchangeTransportTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIInterchangeTransportTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EDIMessageSubTypeXMLElementList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIMessageSubTypeXMLElementList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EInvoiceAPICommandList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EInvoiceAPICommandList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\GenericMessageDeliveryInterchangeTypeList.cs">
      <DependentUpon>GenericMessageDeliveryInterchangeTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Lists\GEPProviderAPICommandList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GEPProviderAPICommandList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\HttpXmlResultStatusList.cs">
      <DependentUpon>HttpXmlResultStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Lists\TelematicsMessageList.cs">
      <DependentUpon>TelematicsMessageList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Lists\ApplicationCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ApplicationCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EDIInterchangeStatusList.cs">
      <DependentUpon>EDIInterchangeStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Lists\EDIInterchangeTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIInterchangeTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EDIMessageStatusList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIMessageStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EDIMessageSubTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIMessageSubTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\EDIMessageTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EDIMessageTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\NativeDataTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>NativeDataTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\SystemMessageList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SystemMessageList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\ReceiveTransmitList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ReceiveTransmitList.xml</DependentUpon>
    </Compile>
    <Compile Update="Lists\HTTPXMLApplicationCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>HTTPXMLApplicationCodeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Lists\GEPProviderAPICommandList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>GEPProviderAPICommandList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\HTTPXMLApplicationCodeList.xml">
      <LastGenOutput>HTTPXMLApplicationCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="Lists\EDIInterchangePriorityList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIInterchangePriorityList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\EDIInterchangeTransportTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <LastGenOutput>EDIInterchangeTransportTypeList.cs</LastGenOutput>
    </None>
    <None Update="Lists\EDIMessageSubTypeXMLElementList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIMessageSubTypeXMLElementList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\EInvoiceAPICommandList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EInvoiceAPICommandList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\GenericMessageDeliveryInterchangeTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>GenericMessageDeliveryInterchangeTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\HttpXmlResultStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>HttpXmlResultStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\TelematicsMessageList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TelematicsMessageList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\ApplicationCodeList.xml">
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ApplicationCodeList.cs</LastGenOutput>
    </None>
    <None Update="Lists\EDIInterchangeStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIInterchangeStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\EDIInterchangeTypeList.xml">
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIInterchangeTypeList.cs</LastGenOutput>
    </None>
    <None Update="Lists\EDIMessageStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIMessageStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\EDIMessageSubTypeList.xml">
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIMessageSubTypeList.cs</LastGenOutput>
    </None>
    <None Update="Lists\EDIMessageTypeList.xml">
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EDIMessageTypeList.cs</LastGenOutput>
    </None>
    <None Update="Lists\NativeDataTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NativeDataTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
    <None Update="Lists\ReceiveTransmitList.xml">
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ReceiveTransmitList.cs</LastGenOutput>
    </None>
    <None Update="Lists\SystemMessageList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SystemMessageList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Messaging.Integration</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>