<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <CWEnableIsExternalInitForNetFrameworkOnly>true</CWEnableIsExternalInitForNetFrameworkOnly>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data.SqlProxy.Interface" />
    <Reference Include="CargoWise.Async" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data.HttpClient" />
    <Reference Include="CargoWise.Data.Providers.Common" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DataLink" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection.SqlExtensions" />
    <Reference Include="CargoWise.DataProtection.Administration" />
    <Reference Include="CargoWise.DataProtection.Administration.SqlServer" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Microsoft.Bcl.AsyncInterfaces" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling" />
    <Reference Include="Microsoft.SqlServer.Types" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Memory" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <Reference Include="System.ServiceModel.Primitives" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>