<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.BlazorWinFormsInterop.Interfaces</AssemblyName>
    <RootNamespace>Enterprise.BlazorWinFormsInterop.Interfaces</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>