<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.AU.ServiceTasks.Testing</RootNamespace>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.AU.Declaration.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common.Business.Test" />
    <Reference Include="Enterprise.Customs.ServiceTasks" />
    <Reference Include="Enterprise.Customs.ServiceTasks.Tests" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Core.Test" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceTasks\Enterprise.Customs.AU.ServiceTasks.csproj" />
  </ItemGroup>
</Project>