// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.TestUpdateLock")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:83,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.TestUpdateLock")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:93,5
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.TestMultipleAUCompaniesFindsOneWithKeyFile")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:229,38
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.ClearRefDb")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:262,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.AssertRefRowsInDB(CargoWise.Types.ZString,System.Int32)")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:271,24
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.AssertServiceTaskLogContainsEntry(System.String)")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:282,37
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.AU.ServiceTasks.Testing.ReferenceFilesServiceTaskTest.ReferenceFilesServiceTaskTestObject.RunFullUpdate(CargoWise.Data.DbConnection,System.DateTime,Enterprise.MasterFiles.Business.CMRReferenceFileUpdateLog)")] // Enterprise/Product/Operations/Customs/AU/ServiceTasks/ServiceTasks.Tests/ReferenceFiles/ReferenceFilesServiceTaskTest.cs:363,26
