using CargoWise.EntityFramework.Testing;
using Enterprise.MasterFiles.Business;
using Enterprise.Messaging.Business;
using Enterprise.UniversalDataBuss.Management;
using Enterprise.UniversalDataBuss.Management.Testing;
using UniversalEvent = Enterprise.UniversalDataBuss.DataObjects.Universal.Event;

namespace Enterprise.Customs.ASYCUDA.Business.UniversalDataTransfer.Testing
{
	public abstract class AsycudaUniversalEventMessageProcessorTest : TestCaseWithFactory
	{
		protected override void SetUp()
		{
			base.SetUp();
			logger = new XmlSessionTracker(new ServiceTaskLogForTesting());

			newGroup = Factory.New<GlbGroup>();
			newGroup.GG_Code = "NG1";
			groupStaff = newGroup.Staff.AddNew();
			groupStaff.GS_Code = "NS1";
			groupStaff.GS_LoginName = "NS1";
			groupStaff.GS_EmailAddress = "ns1@cargowise.com";

			senderStaff = newGroup.Staff.AddNew();
			senderStaff.GS_Code = "NS2";
			senderStaff.GS_LoginName = "NS2";
			senderStaff.GS_EmailAddress = "ns2@cargowise.com";

			message = Factory.New<AsycudaEDIMessage>();
			message.EM_MessageText = SuccessMessageText;
			message.EM_ReceiveTransmit = EDIInterchange.Direction.Receive;
			message.EM_SystemCreateUser = "NS2";
			universalEvent = message.GetEM_MessageTextReader().Parse<UniversalEvent>();
			header = CreateManifestHeader();
		}

		protected virtual AsycudaManifestHeader CreateManifestHeader() => (AsycudaManifestHeader)Factory.New<Integration.Customs.ASYCUDA.SGAccess.IAsycudaManifestHeader>();

		protected internal static string SuccessMessageText => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
      <Event>
        <DataContext>
          <Workflow>
            <ActionPurpose Description=""AIRAEP SG ACCESS"">AEP</ActionPurpose>
          </Workflow>
          <DataSource>
            <DataProvider>SGA</DataProvider>
          </DataSource>
          <DataTargetCollection>
            <DataTarget>
              <Key>MAN0000130</Key>
              <Type>AsycudaManifest</Type>
            </DataTarget>
          </DataTargetCollection>
        </DataContext>
        <EventTime>2017-10-10T22:53:05</EventTime>
        <EventType>MRR</EventType>
        <EventReference>|MSB=ORG|MST=MGE</EventReference>
        <IsEstimate>false</IsEstimate>
        <ContextCollection>
          <Context>
            <Type>ManifestCountry</Type>
            <Value>SG</Value>
          </Context>
          <Context>
            <Type>ResponseNumber</Type>
            <Value>01</Value>
          </Context>
          <Context>
            <Type>ResponseTime</Type>
            <Value>20171011064231</Value>
          </Context>
          <Context>
            <Type>UENNumber</Type>
            <Value>198801949D</Value>
          </Context>
          <Context>
            <Type>OriginalCreateDate</Type>
            <Value>20171010</Value>
          </Context>
          <Context>
            <Type>OriginalSerialNumber</Type>
            <Value>0068</Value>
          </Context>
          <Context>
            <Type>BatchDate</Type>
            <Value>20171010</Value>
          </Context>
          <Context>
            <Type>BatchNumber</Type>
            <Value>0040</Value>
          </Context>
          <Context>
            <Type>MasterBill</Type>
            <Value>8434767687</Value>
            <SubContextCollection>
              <SubContext>
                <Type>HouseBill</Type>
                <Value>HJFGKSD</Value>
                <SubContextCollection>
                  <SubContext>
                    <Type>ConsignmentReference</Type>
                    <Value>1</Value>
                    <SubContextCollection>
                      <SubContext>
                        <Type>ConsignmentNumber</Type>
                        <Value>00001</Value>
                      </SubContext>
                      <SubContext>
                        <Type>MessageStatusCode</Type>
                        <Value>REG</Value>
                      </SubContext>
                      <SubContext>
                        <Type>ConsignmentStatus</Type>
                        <Value>CR</Value>
                      </SubContext>
                      <SubContext>
                        <Type>ManifestPermitNumber</Type>
                        <Value>EUPS17J110001</Value>
                      </SubContext>
                    </SubContextCollection>
                  </SubContext>
                  <SubContext>
                    <Type>ConsignmentReference</Type>
                    <Value>2</Value>
                    <SubContextCollection>
                      <SubContext>
                        <Type>ConsignmentNumber</Type>
                        <Value>00002</Value>
                      </SubContext>
                      <SubContext>
                        <Type>MessageStatusCode</Type>
                        <Value>REG</Value>
                      </SubContext>
                      <SubContext>
                        <Type>ConsignmentStatus</Type>
                        <Value>CR</Value>
                      </SubContext>
                      <SubContext>
                        <Type>ManifestPermitNumber</Type>
                        <Value>EUPS17J110001</Value>
                      </SubContext>
                    </SubContextCollection>
                  </SubContext>
                  <SubContext>
                    <Type>MessageStatusCode</Type>
                    <Value>REG</Value>
                  </SubContext>
                  <SubContext>
                    <Type>ConsignmentStatus</Type>
                    <Value>CR</Value>
                  </SubContext>
                  <SubContext>
                    <Type>ManifestPermitNumber</Type>
                    <Value>EUPS17J110001</Value>
                  </SubContext>
                </SubContextCollection>
              </SubContext>
              <SubContext>
                <Type>MessageStatusCode</Type>
                <Value>REG</Value>
              </SubContext>
            </SubContextCollection>
          </Context>
        </ContextCollection>
      </Event>
    </UniversalEvent>";

		protected internal static string ErrorMessageText => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
	<Event>
		<DataContext>
			<Workflow>
				<ActionPurpose Description=""AIRERR SG ACCESS"">ERR</ActionPurpose>
			</Workflow>
			<DataSource>
				<DataProvider>SGA</DataProvider>
			</DataSource>
			<DataTargetCollection>
				<DataTarget>
					<Key>MAN0000131</Key>
					<Type>AsycudaManifest</Type>
				</DataTarget>
			</DataTargetCollection>
		</DataContext>
		<EventTime>2017-10-11T21:58:05</EventTime>
		<EventType>MRR</EventType>
		<EventReference>MST=MGI</EventReference>
		<IsEstimate>false</IsEstimate>
		<ContextCollection>
			<Context>
				<Type>ManifestCountry</Type>
				<Value>SG</Value>
			</Context>
			<Context>
				<Type>OriginalInterchangeNumber</Type>
				<Value>3889</Value>
			</Context>
			<Context>
				<Type>MessageType</Type>
				<Value>AIRPCM</Value>
			</Context>
			<Context>
				<Type>UENNumber</Type>
				<Value>198801949D</Value>
			</Context>
			<Context>
				<Type>OriginalCreateDate</Type>
				<Value>20171011</Value>
			</Context>
			<Context>
				<Type>OriginalSerialNumber</Type>
				<Value>0150</Value>
			</Context>
			<Context>
				<Type>MasterBill</Type>
				<Value>5464564646</Value>
				<SubContextCollection>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>N13</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>SEGMENT MUST START WITH A DATA ELEMENT</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>N13</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>SEGMENT MUST START WITH A DATA ELEMENT</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>N14</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>HSCODE IS MANDATORY,PLEASE CHECK CIF/FOB AND GOODS TYPE/FLIGHT NO</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>MEA</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>SNT</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>MOA</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>MessageStatusCode</Type>
						<Value>ERR</Value>
					</SubContext>
				</SubContextCollection>
			</Context>
		</ContextCollection>
	</Event>
</UniversalEvent>
";

		protected internal static string NonSGAMessageText => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
	<Event>
		<DataContext>
			<Workflow>
				<ActionPurpose Description=""AIRERR SG ACCESS"">ERR</ActionPurpose>
			</Workflow>
			<DataSource>
				<DataProvider>DUM</DataProvider>
			</DataSource>
			<DataTargetCollection>
				<DataTarget>
					<Key>MAN0000131</Key>
					<Type>AsycudaManifest</Type>
				</DataTarget>
			</DataTargetCollection>
		</DataContext>
		<EventTime>2017-10-11T21:58:05</EventTime>
		<EventType>MRR</EventType>
		<EventReference>MST=MGI</EventReference>
		<IsEstimate>false</IsEstimate>
		<ContextCollection>
			<Context>
				<Type>ManifestCountry</Type>
				<Value>SG</Value>
			</Context>
			<Context>
				<Type>OriginalInterchangeNumber</Type>
				<Value>3889</Value>
			</Context>
			<Context>
				<Type>MessageType</Type>
				<Value>AIRPCM</Value>
			</Context>
			<Context>
				<Type>UENNumber</Type>
				<Value>198801949D</Value>
			</Context>
			<Context>
				<Type>OriginalCreateDate</Type>
				<Value>20171011</Value>
			</Context>
			<Context>
				<Type>OriginalSerialNumber</Type>
				<Value>0150</Value>
			</Context>
			<Context>
				<Type>MasterBill</Type>
				<Value>5464564646</Value>
				<SubContextCollection>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>N13</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>SEGMENT MUST START WITH A DATA ELEMENT</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>N14</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>HSCODE IS MANDATORY,PLEASE CHECK CIF/FOB AND GOODS TYPE/FLIGHT NO</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>MEA</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>FGHJFGHJ</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>1</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>02738</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>SNT</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber2</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>MOA</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>MessageStatusCode</Type>
						<Value>ERR</Value>
					</SubContext>
				</SubContextCollection>
			</Context>
		</ContextCollection>
	</Event>
</UniversalEvent>
";

		protected internal static string InvalidMessageText => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
      <Event>
        <DataContext>
          <Workflow>
            <ActionPurpose Description=""AIRERR SG ACCESS"">ERR</ActionPurpose>
          </Workflow>
          <DataSource>
            <DataProvider>SGA</DataProvider>
          </DataSource>
          <DataTargetCollection>
            <DataTarget>
              <Key>MAN0000003</Key>
              <Type>AsycudaManifest</Type>
            </DataTarget>
          </DataTargetCollection>
        </DataContext>
        <EventTime>2017-11-10T18:04:49</EventTime>
        <EventType>MRR</EventType>
        <EventReference>MST=MGE</EventReference>
        <IsEstimate>false</IsEstimate>
        <ContextCollection>
          <Context>
            <Type>ManifestCountry</Type>
            <Value>SG</Value>
          </Context>
          <Context>
            <Type>OriginalInterchangeNumber</Type>
            <Value>4010</Value>
          </Context>
          <Context>
            <Type>MessageType</Type>
            <Value>AIRAED</Value>
          </Context>
          <Context>
            <Type>UENNumber</Type>
            <Value>198801949D</Value>
          </Context>
          <Context>
            <Type>OriginalCreateDate</Type>
            <Value>20171110</Value>
          </Context>
          <Context>
            <Type>OriginalSerialNumber</Type>
            <Value>0091</Value>
          </Context>
          <Context>
            <Type>MasterBill</Type>
            <Value>40688643730</Value>
            <SubContextCollection>
              <SubContext>
                <Type>HouseBill</Type>
                <Value>908YV2HYLCY</Value>
                <SubContextCollection>
                  <SubContext>
                    <Type>MessageStatusCode</Type>
                    <Value>ERR</Value>
                  </SubContext>
                </SubContextCollection>
              </SubContext>
              <SubContext>
                <Type>MessageStatusCode</Type>
                <Value>ERR</Value>
              </SubContext>
            </SubContextCollection>
          </Context>
        </ContextCollection>
      </Event>
    </UniversalEvent>";

		protected internal static string MessageWithCycleDateAndNumber => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
	<Event>
		<DataContext>
			<Workflow>
				<ActionPurpose Description=""AIRERR SG ACCESS"">ERR</ActionPurpose>
			</Workflow>
			<DataSource>
				<DataProvider>SGA</DataProvider>
			</DataSource>
			<DataTargetCollection>
				<DataTarget>
					<Key>MAN0000164</Key>
					<Type>AsycudaManifest</Type>
				</DataTarget>
			</DataTargetCollection>
		</DataContext>
		<EventTime>2018-04-01T11:13:24</EventTime>
		<EventType>MRR</EventType>
		<EventReference>MST=MGE</EventReference>
		<IsEstimate>false</IsEstimate>
		<ContextCollection>
			<Context>
				<Type>ManifestCountry</Type>
				<Value>SG</Value>
			</Context>
			<Context>
				<Type>OriginalInterchangeNumber</Type>
				<Value>11462</Value>
			</Context>
			<Context>
				<Type>MessageType</Type>
				<Value>AIRAED</Value>
			</Context>
			<Context>
				<Type>UENNumber</Type>
				<Value>198801949D</Value>
			</Context>
			<Context>
				<Type>OriginalCreateDate</Type>
				<Value>20180401</Value>
			</Context>
			<Context>
				<Type>OriginalSerialNumber</Type>
				<Value>7113</Value>
			</Context>
			<Context>
				<Type>CycleDate</Type>
				<Value>2018-01-02T00:00:00.0000000</Value>
			</Context>
			<Context>
				<Type>CycleNumber</Type>
				<Value>01000001</Value>
			</Context>
			<Context>
				<Type>MasterBill</Type>
				<Value>08122223333</Value>
				<SubContextCollection>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>BILL1</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00001</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R01</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESCRIPTION 1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00002</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R02</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESC 2</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>BILL1</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00001</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R03</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESCRIPTION 3</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00002</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R02</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESC 2</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>MessageStatusCode</Type>
						<Value>ERR</Value>
					</SubContext>
				</SubContextCollection>
			</Context>
		</ContextCollection>
	</Event>
</UniversalEvent>";

		protected internal static string MessageWithBatchDateAndNumber => @"<UniversalEvent version=""2.0"" xmlns=""http://www.cargowise.com/Schemas/Universal/2012/11"">
	<Event>
		<DataContext>
			<Workflow>
				<ActionPurpose Description=""AIRERR SG ACCESS"">ERR</ActionPurpose>
			</Workflow>
			<DataSource>
				<DataProvider>SGA</DataProvider>
			</DataSource>
			<DataTargetCollection>
				<DataTarget>
					<Key>MAN0000165</Key>
					<Type>AsycudaManifest</Type>
				</DataTarget>
			</DataTargetCollection>
		</DataContext>
		<EventTime>2018-04-01T11:13:24</EventTime>
		<EventType>MRR</EventType>
		<EventReference>MST=MGE</EventReference>
		<IsEstimate>false</IsEstimate>
		<ContextCollection>
			<Context>
				<Type>ManifestCountry</Type>
				<Value>SG</Value>
			</Context>
			<Context>
				<Type>OriginalInterchangeNumber</Type>
				<Value>11462</Value>
			</Context>
			<Context>
				<Type>MessageType</Type>
				<Value>AIRAED</Value>
			</Context>
			<Context>
				<Type>UENNumber</Type>
				<Value>198801949D</Value>
			</Context>
			<Context>
				<Type>OriginalCreateDate</Type>
				<Value>20180401</Value>
			</Context>
			<Context>
				<Type>OriginalSerialNumber</Type>
				<Value>7113</Value>
			</Context>
			<Context>
				<Type>BatchDate</Type>
				<Value>2018-01-03T00:00:00.0000000</Value>
			</Context>
			<Context>
				<Type>BatchNumber</Type>
				<Value>1000002</Value>
			</Context>
			<Context>
				<Type>MasterBill</Type>
				<Value>0115588445588</Value>
				<SubContextCollection>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>BILL2</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00001</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R01</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESCRIPTION 1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00002</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R02</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESC 2</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>HouseBill</Type>
						<Value>BILL2</Value>
						<SubContextCollection>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00001</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R03</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESCRIPTION 3</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>ConsignmentReference</Type>
								<Value>3</Value>
								<SubContextCollection>
									<SubContext>
										<Type>ConsignmentNumber</Type>
										<Value>00002</Value>
									</SubContext>
									<SubContext>
										<Type>MessageStatusCode</Type>
										<Value>ERR</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorCode</Type>
										<Value>R02</Value>
									</SubContext>
									<SubContext>
										<Type>ErrorDescription</Type>
										<Value>TEST ERROR DESC 2</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentGroup</Type>
										<Value>2</Value>
									</SubContext>
									<SubContext>
										<Type>GroupOccuranceNumber1</Type>
										<Value>1</Value>
									</SubContext>
									<SubContext>
										<Type>SegmentTag</Type>
										<Value>CTY</Value>
									</SubContext>
									<SubContext>
										<Type>OrdinalNumber1</Type>
										<Value>14</Value>
									</SubContext>
								</SubContextCollection>
							</SubContext>
							<SubContext>
								<Type>MessageStatusCode</Type>
								<Value>ERR</Value>
							</SubContext>
						</SubContextCollection>
					</SubContext>
					<SubContext>
						<Type>MessageStatusCode</Type>
						<Value>ERR</Value>
					</SubContext>
				</SubContextCollection>
			</Context>
		</ContextCollection>
	</Event>
</UniversalEvent>";

		protected XmlSessionTracker logger;

		protected GlbGroup newGroup;
		protected GlbStaff groupStaff;
		protected GlbStaff senderStaff;

		protected AsycudaEDIMessage message;
		protected AsycudaManifestHeader header;
		protected UniversalEvent universalEvent;
	}
}
