using Enterprise.ZArchitecture.Core;

namespace Enterprise.Freight.Agency.Module
{
	public partial class AgencyBookingFilterControl
	{
		private void InitializeComponent()
		{
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo13 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo18 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo19 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo20 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo21 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo22 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo23 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo24 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo25 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo26 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo27 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo28 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo additionalNumbersColumnStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo29 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo30 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.SuspendLayout();
			// 
			// grid
			// 
			zTextBoxColumnStyleInfo1.Caption = null;
			zTextBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|1d186d88-598d-44f9-abe6-78a5c2a80684", "Shipment #");
			zTextBoxColumnStyleInfo1.ColumnName = "JS_UniqueConsignRef";
			zTextBoxColumnStyleInfo1.IsMandatory = true;
			zTextBoxColumnStyleInfo2.Caption = null;
			zTextBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|f9a56618-44a1-4402-9c03-cf2ad6e5cf2a", "Ocean Bill");
			zTextBoxColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo2.ColumnName = "JS_HouseBill";
			zMultiControlColumnStyleInfo1.Caption = null;
			zMultiControlColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|a33b965f-8024-4338-af12-9954ecaea6f4", "Booking Party");
			zMultiControlColumnStyleInfo1.ColumnName = "BookingPartyNameOrPK";
			zMultiControlColumnStyleInfo1.FieldTypeColumnName = "BookingPartyFieldType";
			zMultiControlColumnStyleInfo2.Caption = null;
			zMultiControlColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|d207c05d-d6eb-46e1-8a76-fdd481a59045", "Consignor");
			zMultiControlColumnStyleInfo2.ColumnName = "ConsignorNameOrPK";
			zMultiControlColumnStyleInfo2.FieldTypeColumnName = "ConsignorFieldType";
			zMultiControlColumnStyleInfo2.IsVisible = false;
			zMultiControlColumnStyleInfo3.Caption = null;
			zMultiControlColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|12ada181-b30d-4075-b518-9de018eb45d8", "Consignee");
			zMultiControlColumnStyleInfo3.ColumnName = "ConsigneeNameOrPK";
			zMultiControlColumnStyleInfo3.FieldTypeColumnName = "ConsigneeFieldType";
			zMultiControlColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo3.Caption = null;
			zTextBoxColumnStyleInfo3.CaptionResourceString = null;
			zTextBoxColumnStyleInfo3.ColumnName = "JS_ShipmentStatus";
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(45);
			zTextBoxColumnStyleInfo4.Caption = null;
			zTextBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|c4cbcf22-5be3-4ea8-ba96-1e691b712ed2", "Vessel");
			zTextBoxColumnStyleInfo4.ColumnName = "Sailing+JX_JV_NKVessel";
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo5.Caption = null;
			zTextBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|6bf28509-2773-454c-b7a8-241357e439d3", "Voyage No.");
			zTextBoxColumnStyleInfo5.ColumnName = "Sailing+JX_JV_VoyageFlight";
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo6.Caption = null;
			zTextBoxColumnStyleInfo6.CaptionResourceString = null;
			zTextBoxColumnStyleInfo6.ColumnName = "JS_RL_NKOrigin";
			zTextBoxColumnStyleInfo6.IsVisible = false;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo7.Caption = null;
			zTextBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|de4ba009-5861-40ae-923b-11fdbb9c2198", "Load");
			zTextBoxColumnStyleInfo7.ColumnName = "JS_NKLoadPort";
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo8.Caption = null;
			zTextBoxColumnStyleInfo8.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|54ee6148-3e0b-40a9-85e1-d1d85ea65ac2", "Disch.");
			zTextBoxColumnStyleInfo8.ColumnName = "JS_NKDischargePort";
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo9.Caption = null;
			zTextBoxColumnStyleInfo9.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|edd15aa4-265f-49af-970e-746885b18158", "Dest.");
			zTextBoxColumnStyleInfo9.ColumnName = "JS_RL_NKDestination";
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo10.Caption = null;
			zTextBoxColumnStyleInfo10.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|f099a5a3-ad1e-4cda-8f2e-304f33e55791", "Cargo Desc.");
			zTextBoxColumnStyleInfo10.ColumnName = "JS_GoodsDescription";
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.Caption = null;
			zCalcEditColumnStyleInfo1.CaptionResourceString = null;
			zCalcEditColumnStyleInfo1.ColumnName = "JS_OuterPacks";
			zCalcEditColumnStyleInfo1.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|5810fab3-bad9-4cb3-8174-40b0df6a92cd", "Packs");
			zCalcEditColumnStyleInfo1.IsVisible = false;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo11.Caption = null;
			zTextBoxColumnStyleInfo11.CaptionResourceString = null;
			zTextBoxColumnStyleInfo11.ColumnName = "JS_F3_NKPackType";
			zTextBoxColumnStyleInfo11.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|5810fab3-bad9-4cb3-8174-40b0df6a92cd", "Packs");
			zTextBoxColumnStyleInfo11.IsVisible = false;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(35);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.Caption = null;
			zCalcEditColumnStyleInfo2.CaptionResourceString = null;
			zCalcEditColumnStyleInfo2.ColumnName = "JS_ActualWeight";
			zCalcEditColumnStyleInfo2.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|442da15f-4dc6-421e-a5cd-c7c655616841", "Weight");
			zCalcEditColumnStyleInfo2.IsVisible = false;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo12.Caption = null;
			zTextBoxColumnStyleInfo12.CaptionResourceString = null;
			zTextBoxColumnStyleInfo12.ColumnName = "JS_UnitOfWeight";
			zTextBoxColumnStyleInfo12.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|442da15f-4dc6-421e-a5cd-c7c655616841", "Weight");
			zTextBoxColumnStyleInfo12.IsVisible = false;
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.Caption = null;
			zCalcEditColumnStyleInfo3.CaptionResourceString = null;
			zCalcEditColumnStyleInfo3.ColumnName = "JS_ActualVolume";
			zCalcEditColumnStyleInfo3.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|e83b8eb7-18a6-4f32-8b06-f278edf00a84", "Volume");
			zCalcEditColumnStyleInfo3.IsVisible = false;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo13.Caption = null;
			zTextBoxColumnStyleInfo13.CaptionResourceString = null;
			zTextBoxColumnStyleInfo13.ColumnName = "JS_UnitOfVolume";
			zTextBoxColumnStyleInfo13.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|e83b8eb7-18a6-4f32-8b06-f278edf00a84", "Volume");
			zTextBoxColumnStyleInfo13.IsVisible = false;
			zTextBoxColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zTextBoxColumnStyleInfo14.Caption = null;
			zTextBoxColumnStyleInfo14.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|bb7e7cf7-2823-4fc0-9b75-d31f0f52acb4", "Cargo Type");
			zTextBoxColumnStyleInfo14.ColumnName = "JS_PackingMode";
			zTextBoxColumnStyleInfo14.IsVisible = false;
			zTextBoxColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zDateEditColumnStyleInfo1.Caption = null;
			zDateEditColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|d13bc7ae-539c-425c-a54b-85a9e0b35eb5", "ETD");
			zDateEditColumnStyleInfo1.ColumnName = "Sailing+JX_JA_E_DEP";
			zDateEditColumnStyleInfo1.IsVisible = false;
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo2.Caption = null;
			zDateEditColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|a9edac1f-49f0-4f00-a63e-874cfd0ec4f1", "ETA");
			zDateEditColumnStyleInfo2.ColumnName = "Sailing+JX_JB_E_ARV";
			zDateEditColumnStyleInfo2.IsVisible = false;
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zTextBoxColumnStyleInfo15.Caption = null;
			zTextBoxColumnStyleInfo15.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|ea8c4d0c-dbcd-4b9f-adfa-bb705c6046df", "Cnr. Contact");
			zTextBoxColumnStyleInfo15.ColumnName = "ConsignorContact";
			zTextBoxColumnStyleInfo15.IsVisible = false;
			zTextBoxColumnStyleInfo16.Caption = null;
			zTextBoxColumnStyleInfo16.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|3388d029-107e-4350-8789-01ef972e27fb", "Shippers Ref");
			zTextBoxColumnStyleInfo16.ColumnName = "JS_BookingReference";
			zTextBoxColumnStyleInfo16.IsVisible = false;
			zDateEditColumnStyleInfo3.Caption = null;
			zDateEditColumnStyleInfo3.CaptionResourceString = null;
			zDateEditColumnStyleInfo3.ColumnName = "JS_A_BKD";
			zDateEditColumnStyleInfo3.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDateEditColumnStyleInfo4.Caption = null;
			zDateEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|7a68834d-42d9-4c54-bc40-aff751a9d722", "CFS Recv.", "CFS Receival Start");
			zDateEditColumnStyleInfo4.ColumnName = "Sailing+JX_DepotReceivalCommences";
			zDateEditColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo5.Caption = null;
			zDateEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|be0acdf6-0ea5-400a-97c3-975cef830aff", "CFS Cut", "CFS Cut Off");
			zDateEditColumnStyleInfo5.ColumnName = "Sailing+JX_DepotCutOff";
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo6.Caption = null;
			zDateEditColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|863f879c-ee17-480a-918a-8ec7ef7fbe6e", "CTO Recv.", "CTO Receival Start");
			zDateEditColumnStyleInfo6.ColumnName = "Sailing+JX_JA_CTOReceivalCommences";
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo7.Caption = null;
			zDateEditColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|3b20239a-e685-4a97-ae8b-edc58dcda966", "CTO Cut", "CTO Cut Off");
			zDateEditColumnStyleInfo7.ColumnName = "Sailing+JX_JA_CTOCutOff";
			zDateEditColumnStyleInfo7.IsVisible = false;
			zDateEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zTextBoxColumnStyleInfo17.Caption = null;
			zTextBoxColumnStyleInfo17.CaptionResourceString = null;
			zTextBoxColumnStyleInfo17.ColumnName = "Job+JH_Status";
			zTextBoxColumnStyleInfo17.IsVisible = false;
			zTextBoxColumnStyleInfo18.Caption = null;
			zTextBoxColumnStyleInfo18.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|d1fb9732-e7a8-4279-8d70-0123f76296f2", "Booking Ref", "The booking reference or release number.");
			zTextBoxColumnStyleInfo18.ColumnName = "JS_CFSReference";
			zTextBoxColumnStyleInfo18.IsVisible = false;
			zTextBoxColumnStyleInfo19.Caption = null;
			zTextBoxColumnStyleInfo19.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|2c18409b-cf98-488e-a8dc-eaf07e6f7a42", "Consignor Name", "Consignor Company Name", "");
			zTextBoxColumnStyleInfo19.ColumnName = "ConsignorDocumentaryAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo19.IsVisible = false;
			zTextBoxColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo20.Caption = null;
			zTextBoxColumnStyleInfo20.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|02b5cea8-f655-47bf-a6da-a74c03fe0a0f", "Consignor Address");
			zTextBoxColumnStyleInfo20.ColumnName = "ConsignorDocumentaryAddress+AddressAsASingleLine";
			zTextBoxColumnStyleInfo20.IsVisible = false;
			zTextBoxColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo21.Caption = null;
			zTextBoxColumnStyleInfo21.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|c2ccf09e-1522-483f-968c-5af5fd3ddb55", "Consignee Name", "Consignee Company Name", "");
			zTextBoxColumnStyleInfo21.ColumnName = "ConsigneeDocumentaryAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo21.IsVisible = false;
			zTextBoxColumnStyleInfo21.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo22.Caption = null;
			zTextBoxColumnStyleInfo22.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|6d2c1694-71bb-46f9-ac78-2b6f544beba1", "Consignee Address");
			zTextBoxColumnStyleInfo22.ColumnName = "ConsigneeDocumentaryAddress+AddressAsASingleLine";
			zTextBoxColumnStyleInfo22.IsVisible = false;
			zTextBoxColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo23.Caption = null;
			zTextBoxColumnStyleInfo23.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|2ee7abf2-6a11-4099-8a81-7a74d717e255", "Booking Party Name", "Booking Party Company Name", "");
			zTextBoxColumnStyleInfo23.ColumnName = "BookingPartyDocumentaryAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo23.IsVisible = false;
			zTextBoxColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo24.Caption = null;
			zTextBoxColumnStyleInfo24.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|e3d202e5-105d-49c4-b7cc-ec282a3c5f6a", "Booking Party Address");
			zTextBoxColumnStyleInfo24.ColumnName = "BookingPartyDocumentaryAddress+AddressAsASingleLine";
			zTextBoxColumnStyleInfo24.IsVisible = false;
			zTextBoxColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo25.Caption = null;
			zTextBoxColumnStyleInfo25.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|e4e9d3be-fd00-47ad-85d1-2da66ccbc579", "Local Client");
			zTextBoxColumnStyleInfo25.ColumnName = "Job+LocalCharges+OH_Code";
			zTextBoxColumnStyleInfo25.IsVisible = false;
			zTextBoxColumnStyleInfo26.Caption = null;
			zTextBoxColumnStyleInfo26.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|4f2a3935-cb8e-4a04-9aa2-60fc280383b9", "Local Client Name", "Local Client Company Name", "");
			zTextBoxColumnStyleInfo26.ColumnName = "Job+LocalCharges+OH_FullName";
			zTextBoxColumnStyleInfo26.IsVisible = false;
			zTextBoxColumnStyleInfo26.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zTextBoxColumnStyleInfo27.Caption = null;
			zTextBoxColumnStyleInfo27.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|295df51d-55cd-4861-8a18-cea262113363", "Local Client Address");
			zTextBoxColumnStyleInfo27.ColumnName = "Job+LocalChargesAddr+AddressAsASingleLine";
			zTextBoxColumnStyleInfo27.IsVisible = false;
			zTextBoxColumnStyleInfo27.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zTextBoxColumnStyleInfo28.ColumnName = "JS_RS_NKServiceLevel";
			zTextBoxColumnStyleInfo28.IsVisible = false;
			zTextBoxColumnStyleInfo28.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			additionalNumbersColumnStyleInfo.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("AgencyBookingFilterControl|21a00e27-b523-46d1-9896-70083d66ade9", "Additional Reference");
			additionalNumbersColumnStyleInfo.ColumnName = "NumbersAsString";
			additionalNumbersColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			additionalNumbersColumnStyleInfo.IsVisible = false;
			zTextBoxColumnStyleInfo29.ColumnName = "Job+JH_HoldReason";
			zTextBoxColumnStyleInfo29.IsVisible = false;
			zTextBoxColumnStyleInfo30.ColumnName = "Job+JH_ProfitLossReasonCode";
			zTextBoxColumnStyleInfo30.IsVisible = false;
			zCalcEditColumnStyleInfo4.ColumnName = "Job+JH_TotalProfitRevenueMargin";
			zCalcEditColumnStyleInfo4.IsVisible = false;
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo13);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo18);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo19);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo20);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo21);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo22);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo23);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo24);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo25);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo26);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo27);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo28);
			this.grid.ColumnStyles.Add(additionalNumbersColumnStyleInfo);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo29);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo30);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.grid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 176, true);
			this.grid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(720, 408, true);
			this.grid.TabIndex = 16;
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Enterprise.Freight.Agency.Business.AgencyShipment);
			// 
			// AgencyBookingFilterControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Name = "AgencyBookingFilterControl";
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(720, 584, true);
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();

		}
	}
}
