<Project>
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Registry.GUI" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="FlexCel" />
  </ItemGroup>
</Project>