<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
    <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\NCTS5ArrivalCustomsStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTS5ArrivalCustomsStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\NCTS5DepartureCustomsStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NCTS5DepartureCustomsStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\UnloadingRemarkCodeList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>UnloadingRemarkCodeList.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.CH.MessageContracts" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.CH.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.NCTS.Business" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\DecisionStateList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DecisionStateList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\DeparturePhaseList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DeparturePhaseList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NCTS5ArrivalCustomsStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTS5ArrivalCustomsStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NCTS5DepartureCustomsStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NCTS5DepartureCustomsStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NctsMovementHeaderTransactionStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NctsMovementHeaderTransactionStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\UnloadingRemarkCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UnloadingRemarkCodeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\DecisionStateList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DecisionStateList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\DeparturePhaseList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DeparturePhaseList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\NctsMovementHeaderTransactionStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NctsMovementHeaderTransactionStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.NCTS.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>