<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>EDI-Release-private.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Hawking.Xslt.Nupack.csproj.vspscc" />
    <None Remove="Templates\ClassTemplate.txt" />
    <None Remove="Templates\ProjectTemplate.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\ClassTemplate.txt" />
    <EmbeddedResource Include="Templates\ProjectTemplate.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineArgumentsParser" Version="3.0.18" />
    <PackageReference Include="Hawking.Unity" Version="1.0.0" />
    <PackageReference Include="Hawking.Xslt.Compiler" Version="1.0.0" />
    <PackageReference Include="Hawking.Xslt.ExtensionObjects" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />
    <PackageReference Include="NuGet.Packer" Version="1.2.10" />
    <PackageReference Include="Unity.Abstractions" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
