<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>CargoWise.Bi.Development.Automation</RootNamespace>
    <AssemblyName>CargoWise.Bi.Development.Automation</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\SchemaSync\SchemaSync.csproj" />
    <ProjectReference Include="..\SsasBuilder\SsasBuilder.csproj" />
  </ItemGroup>
</Project>