namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.ACE.Output
{
	using CargoWise.Types;

	[ApplicationIdentifier(ACEApplicationIdentifierCodeList.Codes.CargoManifestEntryReleaseStatusQueryResponse)]
	[OutputBlock("WSC", "1")]
	public class ACEQWSC_1 : ACEQWSC
	{
	}

	[Resources.AutoGeneratedSourceCode]
	[OutputBlock("WSC")]
	public partial class ACEQWSC : MessageBlock
	{
		public ACEQWSC()
			: base("WSC")
		{
		}

		/// <summary>
		/// The two or three character identifier of the importing air carrier.
		/// </summary>
		[MessageBlockString(3, 4, "M")]
		public ZString ImportingCarrierCode;

		/// <summary>
		/// If less than five characters are transmitted, the data is "normalized" to five positions to facilitate matches with entries.
		/// </summary>
		[MessageBlockString(5, 7, "M")]
		public ZString FlightNumber;

		/// <summary>
		/// Six-character date in MMDDYY (month, day, year) format representing the date the importing carrier expects the flight to arrive in the U.S.
		/// </summary>
		[MessageBlockDate(12, "M", "MMddyy")]
		public ZDate ScheduledArrivalDate;

		/// <summary>
		/// The first three positions identify the air carrier, the next eight are a sequential number.
		/// </summary>
		[MessageBlockString(11, 18, "M")]
		public ZString AirWaybillNumber;

		/// <summary>
		/// An alpha character indicating the "split" identifier associated to a split master air waybill.
		/// </summary>
		[MessageBlockString(1, 29, "C")]
		public ZString PartIndicator;

		/// <summary>
		/// The quantity associated with the master air waybill.
		/// </summary>
		[MessageBlockInt(5, 30, "M")]
		public ZInt ManifestQuantity;

		/// <summary>
		/// The quantity associated with a specific split. If there is a part indicator this record is mandatory.
		/// </summary>
		[MessageBlockInt(5, 35, "C")]
		public ZInt BoardedQuantity;

		/// <summary>
		/// The house air waybill is associated to an Air Waybill number and may be used to define the query. It may be sent only in conjunction with an Air Waybill Number. If the number is less than 12 positions, it is left justified.
		/// </summary>
		[MessageBlockString(12, 40, "O")]
		public ZString HouseAirWaybillNumber;

		/// <summary>
		/// An alpha character indicating the "split" identifier associated to a split house air waybill.
		/// </summary>
		[MessageBlockString(1, 52, "C")]
		public ZString PartIndicator1;

		/// <summary>
		/// The quantity associated with the house air waybill.
		/// </summary>
		[MessageBlockInt(5, 53, "C")]
		public ZInt ManifestQuantity1;

		/// <summary>
		/// The quantity associated with a specific split. If there is a part indicator this record is mandatory.
		/// </summary>
		[MessageBlockInt(5, 58, "C")]
		public ZInt BoardedQuantity1;

		/// <summary>
		/// An 11 or 9-digit in-bond number
		/// </summary>
		[MessageBlockString(11, 63, "C")]
		public ZString InbondNumber;

		/// <summary>
		/// A code indicating the status of the in-bond.
		/// </summary>
		[MessageBlockString(2, 74, "C")]
		public ZString InbondStatus;

		/// <summary>
		/// A code indicating the type of in-bond movement
		/// </summary>
		[MessageBlockString(2, 76, "C")]
		public ZString InbondEntryType;

		/// <summary>
		/// A code indicating which version of the WSC record is being sent to the trade.
		/// </summary>
		[MessageBlockString(1, 78, "C")]
		public ZString WSCRecordVersion;
	}
}
