<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Licensing" />
    <Reference Include="CargoWise.ProductRegistration.Service" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Encryption" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Client\Enterprise.ProductRegistration.Client.csproj" />
    <ProjectReference Include="..\Common\Enterprise.ProductRegistration.Common.csproj" />
  </ItemGroup>
</Project>