<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="FrenchEntryLineChildSnapshot">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CusEntryLine" maxOccurs="unbounded" minOccurs="1" >
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LineNumber" type="xs:int" />
							<xs:element maxOccurs="unbounded" name="ChildData" minOccurs="1" >
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Code" type="xs:string" maxOccurs="1"/>
										<xs:element minOccurs="0" maxOccurs="1" name="Reference" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="Type" type="ChildType" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="ChildType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CAN" />
			<xs:enumeration value="CAC" />
			<xs:enumeration value="DOC" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
