<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.JAS.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common.Testing" />
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Business\Testing\TestTransactionGenerator.cs" />
    <EmbeddedResource Include="Business\Testing\TestUNCandUOCSetter.cs" />
    <EmbeddedResource Include="Business\Matching\MatchedDataImporter\TestFiles\AUCOR.out" />
    <EmbeddedResource Include="Business\Matching\MatchedDataImporter\TestFiles\EmptyFile.out" />
    <EmbeddedResource Include="Business\Matching\MatchedDataImporter\TestFiles\FileWithSomeInvalidLines.out" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientJAS\ZClientJAS.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
  </ItemGroup>
</Project>