<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputPath>..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dynamic\Enterprise.ZArchitecture.Dynamic.csproj" />
  </ItemGroup>
</Project>