// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingRegistryDataTypeTest.cs:16,89
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingRegistryDataTypeTest.cs:17,91
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingRegistryItemTest.TestOnAllValuesSavedAction")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingRegistryItemTest.cs:49,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestAllEmpty")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:89,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestValidateMachineName")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:96,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestValidateSendToFolder")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:111,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestValidateSendToFolder")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:113,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestValidateMachineNameWithCompanyPK")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:139,50
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.TestValidateMachineNameWithCompanyPK")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:141,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWNCATKClientSettingTest.SetUp")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Registry/ClientSetting/TWNCATKClientSettingTest.cs:167,32
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.JobDeclarationValidationAbstractTest.TestJE_GS_NKCusAgent")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/JobDeclaration/JobDeclarationValidationTest.cs:360,39
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.JobDeclarationTest.TestEntryNumberAllocationMutexLockInfo_NullUser")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/JobDeclaration/JobDeclarationTest.cs:767,4
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.JobDeclarationTest.TestJE_GS_NKCusAgent")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/JobDeclaration/JobDeclarationTest.cs:1122,39
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.NX5105MessageSendingObjectTest.TestDeclaration_RepresentativePersonName")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/MessageSending/NX5105/NX5105MessageSendingObjectTest.cs:464,39
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.NCATKMessageSendingObjectValidationTest.TestCheckTWNCATKClientSetting")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/MessageSending/ControllingMessage/NCATK/NCATKMessageSendingObjectValidationTest.cs:21,32
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.ImportCustomsDeclarationDocumentWrapperAbstractTest.GenerateEntryHeader(System.String)")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/DocumentWrappers/NX5105/ImportCustomsDeclarationDocumentWrapperTest.cs:3271,39
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.CusInBondHeaderTest.TestEntryNumberAllocationMutexLockInfo_NullUser")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/InBond/CusInBondHeader/CusInBondHeaderTest.cs:873,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWMessageTestCase.TestSavingSetsEM_MessageNum_NoDuplicateReferenceException")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/EDIMessage/TWMessageTestCase.cs:20,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWMessageTestCase.TestSavingSetsEM_MessageNum_NoDuplicateReferenceException")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/EDIMessage/TWMessageTestCase.cs:26,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWMessageTestCase.TestPopulateMessageNumberIfNeeded")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/EDIMessage/TWMessageTestCase.cs:43,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.TW.Business.Testing.TWMessageTestCase.TestPopulateMessageNumberIfNeeded")] // Enterprise/Product/Operations/Customs/TW/Core/Business.Test/Business/EDIMessage/TWMessageTestCase.cs:62,4
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~P:Enterprise.Customs.TW.Business.Testing.ExportIncoTermAndCustomsChargeFactoryTest.IncoTermAndCustomsChargeConfigurationFilename")]
