<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ProductionRules.Integration</RootNamespace>
    <AssemblyName>Enterprise.ProductionRules.Integration</AssemblyName>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="WTG.ProductionRules.Core" />
  </ItemGroup>
</Project>