@MessagesApi_HostAddress = http://localhost:5213
@Authorization_Header = Basic VVNDOkRNJHBoYXNlMQ==

HEAD {{MessagesApi_HostAddress}}/wtg/alive
Accept: application/json

###
GET {{MessagesApi_HostAddress}}/wtg/status
Accept: application/json

###
GET {{MessagesApi_HostAddress}}/messages/USC
Accept: application/octet-stream
Authorization: {{Authorization_Header}}

###
POST {{MessagesApi_HostAddress}}/messages/USC
Accept: application/json
Content-Type: application/octet-stream
Authorization: {{Authorization_Header}}

Hello World!
###