//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from FiscalReferenceCodeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.DE.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class FiscalReferenceCodeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string FR1 = "FR1";
			public const string FR2 = "FR2";
			public const string FR3 = "FR3";
			public const string FR5 = "FR5";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString FR1 { get { return ResString.GetMultilingualString("FiscalReferenceCodeList|FR1", "VAT No. of Importer"); } }
			public static MultilingualString FR2 { get { return ResString.GetMultilingualString("FiscalReferenceCodeList|FR2", "VAT No. of Acquirer"); } }
			public static MultilingualString FR3 { get { return ResString.GetMultilingualString("FiscalReferenceCodeList|FR3", "VAT No. of Tax Representative"); } }
			public static MultilingualString FR5 { get { return ResString.GetMultilingualString("FiscalReferenceCodeList|FR5", "IOSS No. of Seller"); } }
		}

		public FiscalReferenceCodeList()
		{
			AddPair(Codes.FR1, Descriptions.FR1);
			AddPair(Codes.FR2, Descriptions.FR2);
			AddPair(Codes.FR3, Descriptions.FR3);
			AddPair(Codes.FR5, Descriptions.FR5);
		}
	}
}
