<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.Warehouse.Cartonisation.Business</RootNamespace>
    <AssemblyName>Enterprise.Warehouse.Cartonisation.Business</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Integration\Warehouse.Cartonisation.Integration.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>