<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.DataTransfer" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentScanning.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="System.Memory" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Business\JobDeclaration\SetEntryStatusDetail\AutoSetEntryStatusDetail.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoSetEntryStatusDetail.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EntryPermitTypeList.cs">
      <DependentUpon>EntryPermitTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\GuaranteeStatusList.cs">
      <DependentUpon>GuaranteeStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <None Update="Business\JobDeclaration\SetEntryStatusDetail\AutoSetEntryStatusDetail.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <CustomToolNamespace>Enterprise.Customs.AsycudaCustoms.Business</CustomToolNamespace>
      <LastGenOutput>AutoSetEntryStatusDetail.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EntryPermitTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EntryPermitTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.AsycudaCustoms.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\GuaranteeStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>GuaranteeStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.AsycudaCustoms.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>