<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_DeploymentPropsImported>$true</_DeploymentPropsImported>
	  <_Server>au2wt-siis-401b.test.wisecloud.zone</_Server>
	  <_SiteName>xt-healthcheck-test.cargowise.net</_SiteName>
    <_ServiceName>CustomsServers</_ServiceName>
    <_AppPoolName>$(_SiteName)</_AppPoolName>
		<_UsingSitePhysicalPath>True</_UsingSitePhysicalPath>
		<UserName>eServicesAdmin</UserName>
	  <Password>Ka5YM5uXB5JEXPMx5f1MCbJDnspQZj4T82DGlommYtOAcmuXrQa6jtsXk23IbhnobeOrJAoFdjK5k7DumxygE7CXgqfjW605hfPWss1B0K+pqMR/wfMy1u8crA3x+j0wA2fTKY2viUGZSaJ59nzI/uJnftrxwNFsh/sH56hqmmY=</Password>
  </PropertyGroup>
  <ItemGroup>
    <_Binding Include="1">
      <IPAddress>*</IPAddress>
      <Port>80</Port>
      <Protocol>http</Protocol>
    </_Binding>
  </ItemGroup>
</Project>