<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>

    <!-- TODO: figure out why xml serialization generation is not happy in net8. See: WI00874705 - Investigate Xml Serialization failing in net core -->
    <CWGenerateXmlSerializationAssemblies Condition="$(TargetFramework.StartsWith('net4'))">true</CWGenerateXmlSerializationAssemblies>

    <RootNamespace>ServiceManager.Integration.ServiceTasks.CW</RootNamespace>
    <AssemblyName>ServiceManager.Integration.ServiceTasks.CW</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\ServiceManager.Integration.Abstractions\ServiceManager.Integration.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
  </ItemGroup>
</Project>