<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.MasterFiles.Business.SpecTesting</RootNamespace>
    <AssemblyName>Enterprise.MasterFiles.Business.SpecTesting</AssemblyName>
    <Configurations>Debug;DEBUGFAST</Configurations>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="WTG.TestHelpers.SpecTesting" />
    <Reference Include="Resources" />
    <Reference Include="NUnitCore" />
    <Reference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Spec/**/*.json" />
    <EmbeddedResource Include="Spec/**/*.txt" />
    <EmbeddedResource Include="Spec/**/*.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MasterFiles.Business\MasterFiles.Business.csproj" />
  </ItemGroup>
</Project>