<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.OceanCarrier.Module</AssemblyName>
    <RootNamespace>Enterprise.OceanCarrier.Module</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.OceanCarrier.GUI.Winzor.csproj" />
  </ItemGroup>
</Project>