<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ResourceStrings.Maintenance.Test</RootNamespace>
    <AssemblyName>Enterprise.ResourceStrings.Maintenance.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <None Remove="DoNotTranslate.txt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="DoNotTranslate.txt" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BuildTools" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache.Test" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Dat.Integration" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.Upgrades" />
    <Reference Include="Enterprise.ResourceStrings.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Test" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Mono.Cecil" />
    <Reference Include="NUnitCore" />
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Maintenance\ResourceStrings.Maintenance.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Design" />
  </ItemGroup>
</Project>