//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.ComplianceRisk.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoComplianceJobEntityCache : EnterpriseBusinessObject, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "ComplianceJobEntityCache";
			public const string PK        = "CJE_PK";

			public const string CJE_COR_ComplianceRisk    = "CJE_COR_ComplianceRisk";
			public const string CJE_EntityID              = "CJE_EntityID";
			public const string CJE_EntityTableCode       = "CJE_EntityTableCode";
			public const string CJE_SystemCreateTimeUtc   = "CJE_SystemCreateTimeUtc";
			public const string CJE_SystemCreateUser      = "CJE_SystemCreateUser";
			public const string CJE_SystemLastEditTimeUtc = "CJE_SystemLastEditTimeUtc";
			public const string CJE_SystemLastEditUser    = "CJE_SystemLastEditUser";

			public const int CJE_EntityTableCodeMaxLength = 3;
			public const int CJE_SystemCreateUserMaxLength = 3;
			public const int CJE_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoComplianceJobEntityCache(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(CJE_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(CJE_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(CJE_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(CJE_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return ComplianceJobEntityCacheSchema.PK; }
		}

		#endregion

		#region Properties

		#region CJE_COR_ComplianceRisk

		public virtual ZGuid CJE_COR_ComplianceRisk
		{
			get {  return new ZGuid(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_COR_ComplianceRisk)); }
			set
			{
				SetPropertyValue(CJE_COR_ComplianceRiskInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateCJE_COR_ComplianceRisk();
				}
			}
		}

		public virtual ZPropertyInfo CJE_COR_ComplianceRiskInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_COR_ComplianceRisk); }
		}

		#endregion

		#region CJE_EntityID

		public virtual ZGuid CJE_EntityID
		{
			get {  return new ZGuid(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_EntityID)); }
			set
			{
				SetPropertyValue(CJE_EntityIDInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateCJE_EntityID();
				}
			}
		}

		public virtual ZPropertyInfo CJE_EntityIDInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_EntityID); }
		}

		#endregion

		#region CJE_EntityTableCode

		public virtual ZString CJE_EntityTableCode
		{
			get {  return new ZString(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_EntityTableCode)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = CJE_EntityTableCodeInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateCJE_EntityTableCode();
				}
			}
		}

		public virtual ZPropertyInfo CJE_EntityTableCodeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_EntityTableCode); }
		}

		#endregion

		#region CJE_SystemCreateTimeUtc

		public virtual ZDateTime CJE_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(CJE_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo CJE_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_SystemCreateTimeUtc); }
		}

		#endregion

		#region CJE_SystemCreateUser

		public virtual ZString CJE_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = CJE_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo CJE_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_SystemCreateUser); }
		}

		#endregion

		#region CJE_SystemLastEditTimeUtc

		public virtual ZDateTime CJE_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(CJE_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo CJE_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_SystemLastEditTimeUtc); }
		}

		#endregion

		#region CJE_SystemLastEditUser

		public virtual ZString CJE_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(ComplianceJobEntityCacheSchema.CJE_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = CJE_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo CJE_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(ComplianceJobEntityCacheSchema.Constants.CJE_SystemLastEditUser); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[ComplianceJobEntityCacheSchema.Constants.CJE_COR_ComplianceRisk   ] = Guid.Empty;
			row[ComplianceJobEntityCacheSchema.Constants.CJE_EntityID             ] = Guid.Empty;
			row[ComplianceJobEntityCacheSchema.Constants.CJE_EntityTableCode      ] = "";
			row[ComplianceJobEntityCacheSchema.Constants.CJE_SystemCreateTimeUtc  ] = DBNull.Value;
			row[ComplianceJobEntityCacheSchema.Constants.CJE_SystemCreateUser     ] = "";
			row[ComplianceJobEntityCacheSchema.Constants.CJE_SystemLastEditTimeUtc] = DBNull.Value;
			row[ComplianceJobEntityCacheSchema.Constants.CJE_SystemLastEditUser   ] = "";
		}

		#endregion

		#region Lookups

		public ComplianceJobEntityCacheLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual ComplianceJobEntityCacheLookups GetNewLookups()
		{
			return new ComplianceJobEntityCacheLookups(this);
		}

		ComplianceJobEntityCacheLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public ComplianceJobEntityCacheValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual ComplianceJobEntityCacheValidation GetNewValidation()
		{
			return new ComplianceJobEntityCacheValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return CJE_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return CJE_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return CJE_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return CJE_SystemLastEditUser; }
		}

		#endregion
	}
}
