<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <AssemblyName>SourceSafeTestProject2</AssemblyName>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SourceSafeTestProject2</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="NUnitCore" />
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App.ico" />
  </ItemGroup>
</Project>