//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Data;

using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.MasterFiles.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0"), CodeProperty(AccWithholdingSchema.Constants.AW_Code), DescriptionProperty(AccWithholdingSchema.Constants.AW_Description), IsActiveProperty(AccWithholdingSchema.Constants.AW_IsActive), PreventDelete(true)]
	public abstract class AutoAccWithholding : EnterpriseBusinessObject, ICancellable, IAuditDetails
	{
		#region Schema

		public abstract class Schema
		{
			public const string TableName = "AccWithholding";
			public const string PK        = "AW_PK";

			public const string AW_Code                  = "AW_Code";
			public const string AW_Description           = "AW_Description";
			public const string AW_GC                    = "AW_GC";
			public const string AW_IsActive              = "AW_IsActive";
			public const string AW_Rate                  = "AW_Rate";
			public const string AW_RN_NKCountry          = "AW_RN_NKCountry";
			public const string AW_SystemCreateTimeUtc   = "AW_SystemCreateTimeUtc";
			public const string AW_SystemCreateUser      = "AW_SystemCreateUser";
			public const string AW_SystemLastEditTimeUtc = "AW_SystemLastEditTimeUtc";
			public const string AW_SystemLastEditUser    = "AW_SystemLastEditUser";

			public const int AW_CodeMaxLength = 10;
			public const int AW_DescriptionMaxLength = 35;
			public const int AW_RN_NKCountryMaxLength = 2;
			public const int AW_SystemCreateUserMaxLength = 3;
			public const int AW_SystemLastEditUserMaxLength = 3;
		}

		#endregion

		protected AutoAccWithholding(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(AW_SystemCreateTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(AW_SystemCreateUser), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(AW_SystemLastEditTimeUtc), ConcurrencyPolicy.Ignore);
			ConcurrencyInfo.SetConcurrencyPolicy(this, nameof(AW_SystemLastEditUser), ConcurrencyPolicy.Ignore);
		}

		#region PK

		public override SchemaGuidColumn PKSchemaColumn
		{
			get { return AccWithholdingSchema.PK; }
		}

		#endregion

		#region Properties

		#region AW_Code

		public virtual ZString AW_Code
		{
			get {  return new ZString(GetValueFromRowSafely(AccWithholdingSchema.AW_Code)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = AW_CodeInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_Code();
				}
			}
		}

		public virtual ZPropertyInfo AW_CodeInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_Code); }
		}

		#endregion

		#region AW_Description

		public virtual ZString AW_Description
		{
			get {  return new ZString(GetValueFromRowSafely(AccWithholdingSchema.AW_Description)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = AW_DescriptionInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_Description();
				}
			}
		}

		public virtual ZPropertyInfo AW_DescriptionInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_Description); }
		}

		#endregion

		#region AW_GC

		[RelatedBusinessObject("Company")]
		[List("Lookups.Companies")]
		public virtual ZGuid AW_GC
		{
			get {  return new ZGuid(GetValueFromRowSafely(AccWithholdingSchema.AW_GC)); }
			set
			{
				SetPropertyValue(AW_GCInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_GC();
				}
			}
		}

		public virtual GlbCompany Company
		{
			get { return (GlbCompany) Factory.Load(typeof(GlbCompany), AW_GC); }
		}

		public virtual ZPropertyInfo AW_GCInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_GC); }
		}

		#endregion

		#region AW_IsActive

		public virtual bool IsCancelled
		{
			get { return !AW_IsActive; }
			set { AW_IsActive = !value; }
		}

		public virtual bool IsCancelledHasChanged
		{
			get { return AW_IsActiveInfo.HasChanges; }
		}

		public virtual string CanCancel()
		{
			return null;
		}

		public virtual string CanReactivate()
		{
			return null;
		}

		public virtual ZBool AW_IsActive
		{
			get {  return new ZBool(GetValueFromRowSafely(AccWithholdingSchema.AW_IsActive)); }
			set
			{
				SetPropertyValue(AW_IsActiveInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_IsActive();
				}
			}
		}

		public virtual ZPropertyInfo AW_IsActiveInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_IsActive); }
		}

		#endregion

		#region AW_Rate

		public virtual ZDecimal AW_Rate
		{
			get {  return new ZDecimal(GetValueFromRowSafely(AccWithholdingSchema.AW_Rate)); }
			set
			{
				SetPropertyValue(AW_RateInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_Rate();
				}
			}
		}

		public virtual ZPropertyInfo AW_RateInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_Rate); }
		}

		#endregion

		#region AW_RN_NKCountry

		[RelatedBusinessObject("Country")]
		[List("Lookups.Countries")]
		public virtual ZString AW_RN_NKCountry
		{
			get {  return new ZString(GetValueFromRowSafely(AccWithholdingSchema.AW_RN_NKCountry)); }
			set
			{
				value = value.TrimEndSpaceTab();
				value = value.ToUpperInvariant();
				var zPropertyInfo = AW_RN_NKCountryInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateAW_RN_NKCountry();
				}
			}
		}

		public virtual RefCountry Country
		{
			get { return (RefCountry) Factory.LoadFromNaturalKey(typeof(RefCountry), RefCountrySchema.RN_Code, AW_RN_NKCountry); }
		}

		public virtual ZPropertyInfo AW_RN_NKCountryInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_RN_NKCountry); }
		}

		#endregion

		#region AW_SystemCreateTimeUtc

		public virtual ZDateTime AW_SystemCreateTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(AccWithholdingSchema.AW_SystemCreateTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(AW_SystemCreateTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo AW_SystemCreateTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_SystemCreateTimeUtc); }
		}

		#endregion

		#region AW_SystemCreateUser

		public virtual ZString AW_SystemCreateUser
		{
			get {  return new ZString(GetValueFromRowSafely(AccWithholdingSchema.AW_SystemCreateUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = AW_SystemCreateUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo AW_SystemCreateUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_SystemCreateUser); }
		}

		#endregion

		#region AW_SystemLastEditTimeUtc

		public virtual ZDateTime AW_SystemLastEditTimeUtc
		{
			get {  return new ZDateTime(GetValueFromRowSafely(AccWithholdingSchema.AW_SystemLastEditTimeUtc), DateTimeKind.Utc); }
			set
			{
				SetPropertyValue(AW_SystemLastEditTimeUtcInfo, value);

			}
		}

		public virtual ZPropertyInfo AW_SystemLastEditTimeUtcInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_SystemLastEditTimeUtc); }
		}

		#endregion

		#region AW_SystemLastEditUser

		public virtual ZString AW_SystemLastEditUser
		{
			get {  return new ZString(GetValueFromRowSafely(AccWithholdingSchema.AW_SystemLastEditUser)); }
			set
			{
				value = value.TrimEndSpaceTab();
				var zPropertyInfo = AW_SystemLastEditUserInfo;
				CheckMaximumLength(zPropertyInfo, value);
				SetPropertyValue(zPropertyInfo, value);

			}
		}

		public virtual ZPropertyInfo AW_SystemLastEditUserInfo
		{
			[System.Diagnostics.DebuggerStepThrough()]
			get { return GetZPropertyInfo(AccWithholdingSchema.Constants.AW_SystemLastEditUser); }
		}

		#endregion

		#endregion

		#region Set Default Values

		protected override void SetDefaultValues()
		{
			base.SetDefaultValues();

			DataRow row = ((IBusinessObjectInternals)this).Row;
			row[AccWithholdingSchema.Constants.AW_Code                 ] = "";
			row[AccWithholdingSchema.Constants.AW_Description          ] = "";
			row[AccWithholdingSchema.Constants.AW_GC                   ] = DBNull.Value;
			row[AccWithholdingSchema.Constants.AW_IsActive             ] = true;
			row[AccWithholdingSchema.Constants.AW_Rate                 ] = (decimal)0;
			row[AccWithholdingSchema.Constants.AW_RN_NKCountry         ] = "";
			row[AccWithholdingSchema.Constants.AW_SystemCreateTimeUtc  ] = DBNull.Value;
			row[AccWithholdingSchema.Constants.AW_SystemCreateUser     ] = "";
			row[AccWithholdingSchema.Constants.AW_SystemLastEditTimeUtc] = DBNull.Value;
			row[AccWithholdingSchema.Constants.AW_SystemLastEditUser   ] = "";
		}

		#endregion

		#region Lookups

		public AccWithholdingLookups Lookups
		{
			get
			{
				if (fLookups == null || !IsLookupsCachedInBase)
				{
					fLookups = GetNewLookups();
				}

				return fLookups;
			}
		}

		protected virtual AccWithholdingLookups GetNewLookups()
		{
			return new AccWithholdingLookups(this);
		}

		AccWithholdingLookups fLookups;

		#endregion

		#region Validation

		protected override void RunPreSaveValidationCore()
		{
			Validation.ValidateAll();
			base.RunPreSaveValidationCore(); // call RunPreSaveValidationCore() on all children then fire OnNotificationsChanged()
		}

		public AccWithholdingValidation Validation
		{
			get { return GetNewValidation(); }
		}

		protected virtual AccWithholdingValidation GetNewValidation()
		{
			return new AccWithholdingValidation(this);
		}

		#endregion

		#region IAuditDetails

		ZDateTime IAuditDetails.SystemCreateTimeUtc
		{
			get { return AW_SystemCreateTimeUtc; }
		}

		ZString IAuditDetails.SystemCreateUser
		{
			get { return AW_SystemCreateUser; }
		}

		ZDateTime IAuditDetails.SystemLastEditTimeUtc
		{
			get { return AW_SystemLastEditTimeUtc; }
		}

		ZString IAuditDetails.SystemLastEditUser
		{
			get { return AW_SystemLastEditUser; }
		}

		#endregion
	}
}
