<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarketingManager.Module\Enterprise.MarketingManager.Module.csproj" />
    <ProjectReference Include="..\MarketingManager.GUI\Enterprise.MarketingManager.GUI.csproj" />
    <ProjectReference Include="..\MarketingManager.GUI.Test\Enterprise.MarketingManager.GUI.Test.csproj" />
  </ItemGroup>
</Project>