<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Warehouse.Environment.Business</RootNamespace>
    <AssemblyName>Enterprise.Warehouse.Environment.Business</AssemblyName>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DocumentEngine.Shared" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Warehouse.Cartonisation.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeLists\CartonizationOptimizationModes.cs">
      <DependentUpon>CartonizationOptimizationModes.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeLists\ApprovedKnownStatus.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ApprovedKnownStatus.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\AreaTypes.cs">
      <DependentUpon>AreaTypes.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeLists\CycleCountGranularities.cs">
      <DependentUpon>CycleCountGranularities.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeLists\DynamicPickFaceAssignmentStatus.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DynamicPickFaceAssignmentStatus.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\LocationClasses.cs">
      <DependentUpon>LocationClasses.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeLists\PickFaceStatuses.cs">
      <DependentUpon>PickFaceStatuses.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeLists\LocationStatus.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LocationStatus.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\DetailedTrackingMethod.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DetailedTrackingMethod.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\SortPathMethods.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SortPathMethods.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\US\TSAStatus.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TSAStatus.xml</DependentUpon>
    </Compile>
    <EmbeddedResource Include="WhsArea\WhsAreaResourceStrings.xml" />
    <EmbeddedResource Include="WhsLocationType\WhsLocationTypeResourceStrings.xml" />
    <EmbeddedResource Include="WhsLocation\WhsLocationViewResourceStrings.xml" />
    <EmbeddedResource Include="WhsRow\WhsRowResourceStrings.xml" />
    <EmbeddedResource Include="WhsWarehouse\WhsWarehouseResourceStrings.xml" />
    <EmbeddedResource Include="WhsClientParametersByWarehouse\WhsClientParameterByWarehouseResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeLists\CartonizationOptimizationModes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CartonizationOptimizationModes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\ApprovedKnownStatus.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ApprovedKnownStatus.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\AreaTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AreaTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\CycleCountGranularities.xml">
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
      <LastGenOutput>CycleCountGranularities.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeLists\DynamicPickFaceAssignmentStatus.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DynamicPickFaceAssignmentStatus.cs</LastGenOutput>
    </None>
    <None Update="CodeLists\LocationClasses.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>LocationClasses.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\PickFaceStatuses.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PickFaceStatuses.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\LocationStatus.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>LocationStatus.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\DetailedTrackingMethod.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
      <LastGenOutput>DetailedTrackingMethod.cs</LastGenOutput>
    </None>
    <None Update="CodeLists\SortPathMethods.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SortPathMethods.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists</CustomToolNamespace>
    </None>
    <None Update="CodeLists\US\TSAStatus.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TSAStatus.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Warehouse.Environment.CodeLists.US</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="WhsCartonGroupSizeLink\WhsCartonGroupSizeLinkResourceStrings.xml" />
    <EmbeddedResource Include="WhsSalesChannel\WhsSalesChannelResourceStrings.xml" />
    <EmbeddedResource Include="WhsUNDGLimit\WhsUNDGLimitResourceStrings.xml" />
    <EmbeddedResource Include="WhsPutawayGroup\WhsPutawayGroupResourceStrings.xml" />
    <EmbeddedResource Include="WhsDynamicPickFaceView\WhsDynamicPickFaceViewResourceStrings.xml" />
    <EmbeddedResource Include="WhsPickFace\WhsPickFaceResourceStrings.xml" />
    <EmbeddedResource Include="WhsPickFaceView\WhsPickFaceViewResourceStrings.xml" />
    <EmbeddedResource Include="WhsCartonGroup\WhsCartonGroupResourceStrings.xml" />
    <EmbeddedResource Include="WhsCartonSize\WhsCartonSizeResourceStrings.xml" />
    <EmbeddedResource Include="WhsProductStyleColour\WhsProductStyleColourResourceStrings.xml" />
    <EmbeddedResource Include="WhsProductStyleClassification\WhsProductStyleClassificationResourceStrings.xml" />
    <EmbeddedResource Include="WhsProductStyleSize\WhsProductStyleSizeResourceStrings.xml" />
    <EmbeddedResource Include="WhsProductStyle\WhsProductStyleResourceStrings.xml" />
    <EmbeddedResource Include="WhsClientPickPackParamsByWhs\WhsClientPickPackParamsByWhsResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Warehouse.Environment.Core\Warehouse.Environment.Core.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>