<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.TSF.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappers.Test" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="NUnitCore" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.Definitions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientTSF\ZClientTSF.csproj" />
  </ItemGroup>
</Project>