<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.NZ.Manifest.Business</RootNamespace>
    <AssemblyName>Enterprise.Customs.NZ.Manifest.Business</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.NZ.Business" />
    <Reference Include="Enterprise.Customs.NZ.TradeSingleWindow" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Agency.Business" />
	  <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\NZManifestTypes.cs">
      <DependentUpon>NZManifestTypes.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\NZManifestTypes_Partial.cs">
      <DependentUpon>NZManifestTypes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\NZManifestTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>NZManifestTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.NZ.Manifest.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>