<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.eManifest.Integration</RootNamespace>
    <AssemblyName>Enterprise.eManifest.Integration</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.eTail.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
  </ItemGroup>
</Project>