// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:26,17
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:27,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:28,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:29,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:30,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:31,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:32,30
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CN.Module.Testing.SendACDAOperationalActionMethodApplicatorTest.TestApply")] // Enterprise/Product/Operations/Customs/CN/Core/Module.Test/EntryHeader/SendACDAOperationalActionMethodApplicatorTest.cs:33,24
