<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_ProfilePropsImported>$true</_ProfilePropsImported>
    <_Server>AU2SP-STWC-401.sand.wtg.zone</_Server>
    <UserName>s_eServicesDeploy@wtg.zone</UserName>
    <Password>Z/FqwFtxIl2NWe/QomHAjP3XxZa6iqF4vWSlpfMjx+mKqlzeEdPedOaSUcjEcIOAJVUFXe5V/c9VuOx0eurkbXJwbaG4tElBcUbBvWQ4OqmmLOuYNVWATFyJD5sfEPBJFn0tNGTZ9tOOghkDqbTh2a/3OVkxo7Lt/EUUuoc9B/I=</Password>
  </PropertyGroup>
  <ItemGroup>
    <_Binding Include="1_Override">
      <Port>80</Port>
      <Protocol>http</Protocol>
    </_Binding>
  </ItemGroup>
</Project>