<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Enterprise.Customs.ES.TemporaryStorage.GUI.Testing</RootNamespace>
    <AssemblyName>Enterprise.Customs.ES.TemporaryStorage.GUI.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.ES.TemporaryStorage.GUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Moq" />
  </ItemGroup>
</Project>