<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DocumentEngine.Macros.Testing</RootNamespace>
    <AssemblyName>Enterprise.DocumentEngine.Macros.Testing</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Macros" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentEngine.Macros\DocumentEngine.Macros.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="mainfreight-menu-filters.txt" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>