<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.cargowise.com/Schemas/WWA" xmlns:b="http://schemas.microsoft.com/BizTalk/2003" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.cargowise.com/Schemas/WWA" attributeFormDefault="unqualified">
  <xs:element name="Acknowledgement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="AcknowledgementEnvelope">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SenderID" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="100"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="ReceiverID" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="100"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Password" nillable="false" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:minLength value="6"/>
                    <xs:maxLength value="100"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Type" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Version" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="8"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="EnvelopeID" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="50"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="AcknowledgementDetails" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CustomerReference" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="CommunicationReference" nillable="false">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="WWAReference" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="30"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="AcknowledgementType" nillable="false">
                <xs:annotation>
                  <xs:documentation>"BKG" = Booking "BOL" = BL instructions</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="5"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="BookingNumber" nillable="true">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="20"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="AcknowledgementStatus" nillable="false">
                <xs:annotation>
                  <xs:documentation>"A" = Accept "R" = Reject</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="1"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Remarks">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="250"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>