<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.ZArchitecture.Business.Benchmark.Test</AssemblyName>
    <WarningsAsErrors>;NU1605</WarningsAsErrors>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.ZArchitecture.Benchmark.Framework\Enterprise.ZArchitecture.Benchmark.Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Benchmark.Framework" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="NUnitCore" />
    <Reference Include="nunit.framework" />
  </ItemGroup>
</Project>