<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DbUpgrader.Data.BaseData.RefZone.Testing</RootNamespace>
    <AssemblyName>Enterprise.DbUpgrader.Data.BaseData.RefZone.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="Enterprise.DbUpgrader.Data.Shared" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\RefZone\RefZone.csproj" />
  </ItemGroup>
</Project>