// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.BGMSegmentWithReferenceAndDates.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/BGMSegmentWithReferenceAndDates.cs:50,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.Connection.HandShakeResponse.ExpectedMessageType")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/Connection/Responses/HandShakeResponse.cs:69,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.CcsukEdifactMessageFactory.factory")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/CcsukEdifactMessageFactory.cs:10,24
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.DOCSegmentWith8Elements.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/DOCSegmentWith8Elements.cs:40,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.LOCSegmentWithLotsOfLocations.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/LOCSegmentWithLotsOfLocations.cs:58,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.RFFSegmentWithDatetime.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/RFFSegmentWithDatetime.cs:38,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.MOASegmentWithFunction.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/MOASegmentWithFunction.cs:42,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.Connection.HandShake.HandShakeIdentifier")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/Connection/Shared/HandShake.cs:9,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.BusinessObjects.CusAwbIsReadOnlyHelper.CACsTAWB_ColumnThree")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/BusinessObjects/Helpers/CusAwbIsReadOnlyHelper.cs:270,32
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.Connection.ServiceMessage.ServiceMessageIdentifier")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/Connection/Requests/ServiceMessage.cs:63,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.Messaging.TDTSegmentWithDatetime.SegmentFakeName")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/Messaging/Fake912Segments/TDTSegmentWithDatetime.cs:56,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.Connection.CcsukSession.tcpIpSenderReceiver")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/Connection/Shared/CcsukSession.cs:155,29
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Customs.GB.Ccsuk.Connection.CcsukSession.instance")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/Connection/Shared/CcsukSession.cs:156,22
[assembly: SuppressMessage("CargoWiseOne", "EDI003:Business Object Property Max Length Validation", Justification = "Baseline WI00752625", Scope = "member", Target = "~P:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.BusinessObjects.CusHawbToShipmentSynchroniser.Enterprise#Freight#Business#IUpdateFromShipment#GoodsDescription")] // Enterprise/Product/Operations/Customs/GB/Core/Ccsuk/AirCargoInventory/BusinessObjects/CusHAWB/CusHawbToShipmentSynchroniser.cs:99,32
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.BusinessObjects.CusHAWB.Splits")]
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.BusinessObjects.CusMAWB.Splits")]
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Customs.GB.Ccsuk.AirCargoInventory.BusinessObjects.ShipmentToManyHawbsPluginHelper.Hawbs")]
