<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_ProfilePropsImported>$true</_ProfilePropsImported>
    <_Server>au2wp-seug-401b.wisecloud.zone</_Server>
    <_SiteName>ehub-usage.wisegrid.net</_SiteName>
    <_AppPoolName>$(_SiteName)</_AppPoolName>
    <UserName>s_eServicesDeploy@wisecloud.zone</UserName>
    <Password>goHoYW7XyG0w0LSV0kMlXCswubQGd2U4MEuLlED/pVcKGh/JOUCLcCvfyjxR1KD6H+hcAY4RNyBN12AcQlkgZhWoIBdnYtl4Uo6wkuiImfZSiCfpmcYg+GcHf6NoeqCDRIWOtALeJwaIKe09ISbE//L0iDv8Ao2G3pXJzIG7YOI=</Password>
    <_EncryptConfigRequired>true</_EncryptConfigRequired>
    <_EncryptedSection>connectionStrings,sensitiveAppSettings</_EncryptedSection>
  </PropertyGroup>
	<ItemGroup>
		<_Binding Include="1_Override">
			<IPAddress>*</IPAddress>
			<Port>80</Port>
			<Protocol>http</Protocol>
			<HostHeader>$(_SiteName)</HostHeader>
		</_Binding>
		<_Binding Include="2">
			<IPAddress>*</IPAddress>
			<Port>80</Port>
			<Protocol>http</Protocol>
			<HostHeader>ehub-usage.wisegrid.net</HostHeader>
		</_Binding>
	</ItemGroup>
	<ItemGroup>
		<EncryptedPassword Include="$eHubTransactionsPassword$">
			<Value>DEVAFSA/JtfKaBX9631qfUcxyJFolWH2K66eacr7Of2j4QXud0orgTw/83zUGyswXwIRw/o/CzhqME1rSbHyKxgMQMe2v4y/U4acrxmDkFtflws0YKcfpu+ffKwJ2zki3mSXg9vnvuvelxG7EHO6r0KAY67/aRiPFrg7DLMC9KE=</Value>
		</EncryptedPassword>
		<EncryptedPassword Include="$GatewayKafkaSaslPassword$">
			<Value>DLG8U5yREJbJX25yoxitso1HtTmi7eSpQrlDwMhFsbPJc5C09KTOFvLNahveh9ZBbJErPSVBAEtQj+YJ/kn3/tPUahgbduP4EZUgNNBjt+7panxTmW8fGbl83fx3tKpI+tgltWm6qYeSto5VTrYIECBv0DZl2D3xKweh+BTevkQ=</Value>
		</EncryptedPassword>
    <EncryptedPassword Include="$BillingKafkaPassword$">
      <Value>ZwRzkFDMKKh2NzBNVXdDFg6gheS1m2myE0ErnLUcU3MpMJzWk2i2fdN32e/gJ3rNL/HpHike9adQeeIWJQDzIBK0D+XQ+UEZPtiRDac43mOqH7oJPxTnCKJP+L3wt6+en0vDOlF8KgfP08qJ7L/rnOxWBb7hPY9UxwjIcVPnWDw=</Value>
    </EncryptedPassword>
	</ItemGroup>
</Project>