<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.MarketingManager.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.MarketingManager.GUI.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
    <NoWarn>$(NoWarn);CS0067;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="GlbCompanyCampaign\Charts\ReadReceiptChart\ColorCollectionTest.cs" />
    <Compile Remove="GlbCompanyCampaign\Charts\ReadReceiptChart\IndexedColourSelectorTest.cs" />
    <Compile Remove="GlbCompanyCampaign\DripMarketing\StringToNumConverterTest.cs" />
    <Compile Remove="GlbCompanyCampaign\DripMarketing\BooleanToVisibilityConverterTest.cs" />
    <Compile Remove="GlbCompanyCampaign\DripMarketing\TouchSummaryTest.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MarketingManager.GUI\Enterprise.MarketingManager.GUI.Winzor.csproj" />
    <Reference Include="Enterprise.MarketingManager.ServiceTask" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="HtmlEditor\Test File\" />
  </ItemGroup>
</Project>