// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:496,117
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:519,97
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:543,118
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:496,117
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:519,97
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.MarketingManager.GUI.Testing.SalesAnalysisChartViewModelTest.TestMultiLanguages")] // Enterprise/Product/Operations/MarketingManager/MarketingManager.GUI.Test/SalesHeader/Chart/SalesAnalysisChartViewModelTest.cs:543,118
