//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from 'AutoCusEntryHeader.xml' by AddInfoPartialWrapperGenerator Custom Tool.
//     Do not edit this file, because changes will be lost next time it is generated.
// </auto-generated>
//------------------------------------------------------------------------------

using CargoWise.EntityFramework;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.Customs.SG.V4.Business
{
	[Resources.AutoGeneratedSourceCode]
	public abstract partial class AutoCusEntryHeader : Customs.Business.CusEntryHeader, Enterprise.Customs.Business.IAddInfoManagerWithSchema
	{
		protected AutoCusEntryHeader(BusinessObjectFactory factory, System.Data.DataRow row)
			: base(factory, row)
		{
		}

		#region Schema
		public new partial class Schema : Customs.Business.CusEntryHeader.Schema
		{
			public const string SG_PreviousEntryStatus = SGAddInfoSchema.Constants.SG_PreviousEntryStatus;
		}
		#endregion

		#region AddInfo Properties

		#region SG_PreviousEntryStatus

		public virtual ZString SG_PreviousEntryStatus
		{
			get { return AddInfo.SG_PreviousEntryStatus; }
			set { AddInfo.SG_PreviousEntryStatus = value; }
		}

		public virtual ZPropertyInfo SG_PreviousEntryStatusInfo
		{
			get { return GetWrappedZPropertyInfo(Schema.SG_PreviousEntryStatus, x => AddInfo.SG_PreviousEntryStatusInfo); }
		}

		#endregion

		#endregion

		#region AddInfo object/Validation and Lookups objects

		public AddInfoCusEntryHeaderLookups AddInfoLookups
		{
			get { return AddInfo.Lookups; }
		}

		public AddInfoCusEntryHeaderValidation AddInfoValidation
		{
			get { return AddInfo.Validation; }
		}

		AddInfoCusEntryHeader AddInfo
		{
			get
			{
				if (fAddInfo == null)
				{
					fAddInfo = new AddInfoCusEntryHeader(CH_AddInfoInfo);
					RegisterEditableChildObject(fAddInfo);
					RegisterListChangedCalledRefreshBinding(fAddInfo);
				}
				return fAddInfo;
			}
		}
		AddInfoCusEntryHeader fAddInfo;

		#endregion

		#region IAddInfoManagerWithSchema Members

		Enterprise.Customs.Business.IAddInfo Enterprise.Customs.Business.IAddInfoManager.AddInfo
		{
			get { return AddInfo; }
		}

		ITableSchema Enterprise.Customs.Business.IAddInfoManagerWithSchema.AddInfoSchema => SGAddInfoSchema.Instance;

		#endregion
	}
}
