<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Core</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
</Project>