namespace Enterprise.Freight.Agency.Module
{
	partial class BillContainersFilterControl
	{
		private void InitializeComponent()
		{
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo6 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo7 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo18 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			importReleaseNumberColumnStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo emptyReturnReferenceColumnStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo additionalNumbersColumnStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();

			((System.ComponentModel.ISupportInitialize)(this.grid)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.SuspendLayout();
			// 
			// grid
			// 
			zTextBoxColumnStyleInfo1.Caption = null;
			zTextBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|f7b1f035-34bf-4781-91f4-51da2ca3f93f", "Shipment #", "Shipment Number.");
			zTextBoxColumnStyleInfo1.ColumnName = "Booking+JS_UniqueConsignRef";
			zTextBoxColumnStyleInfo1.IsVisible = false;
			zTextBoxColumnStyleInfo2.Caption = null;
			zTextBoxColumnStyleInfo2.CaptionResourceString = null;
			zTextBoxColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo2.ColumnName = "JC_ContainerNum";
			zGuidFindBoxColumnStyleInfo1.Caption = null;
			zGuidFindBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|66cc635b-1c05-4a19-bd49-05e694d433fe", "Type");
			zGuidFindBoxColumnStyleInfo1.ColumnName = "JC_RC";
			zGuidFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCodeFindBoxColumnStyleInfo1.Caption = null;
			zCodeFindBoxColumnStyleInfo1.CaptionResourceString = null;
			zCodeFindBoxColumnStyleInfo1.ColumnName = "Booking+Sailing+Voyage+JV_RV_NKVessel";
			zTextBoxColumnStyleInfo3.Caption = null;
			zTextBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|cce71a2b-48a4-412b-b348-9c1e9d23f767", "Voyage");
			zTextBoxColumnStyleInfo3.ColumnName = "Booking+Sailing+Voyage+JV_VoyageFlight";
			zTextBoxColumnStyleInfo4.Caption = null;
			zTextBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|47a0755c-db61-4034-9dd7-146df2702761", "Bill Of Lading");
			zTextBoxColumnStyleInfo4.ColumnName = "Booking+JS_HouseBill";
			zDateEditColumnStyleInfo1.Caption = null;
			zDateEditColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|b58e91f2-6cd0-408e-bf58-bacd17d8d7c2", "Availability");
			zDateEditColumnStyleInfo1.ColumnName = "Booking+Sailing+Destination+JB_AvailabilityDate";
			zDateEditColumnStyleInfo1.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo1.IsVisible = false;
			zDateEditColumnStyleInfo2.Caption = null;
			zDateEditColumnStyleInfo2.CaptionResourceString = null;
			zDateEditColumnStyleInfo2.ColumnName = "JC_EmptyReturnedBy";
			zDateEditColumnStyleInfo2.IsVisible = false;
			zDateEditColumnStyleInfo3.Caption = null;
			zDateEditColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|ce61561f-fcd0-4964-a611-556348e3a9a9", "Wharf Gate Out", "Wharf Gate Out", "When the container left the wharf.");
			zDateEditColumnStyleInfo3.ColumnName = "JC_FCLWharfGateOut";
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo4.Caption = null;
			zDateEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|3df5db9c-2222-4b9a-b1be-6bc3fbbb79da", "Empty Ret.", "Empty Returned", "The date the empty container was returned to the yard.");
			zDateEditColumnStyleInfo4.ColumnName = "JC_ContainerYardEmptyReturnGateIn";
			zDateEditColumnStyleInfo4.IsVisible = false;
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.Caption = null;
			zCalcEditColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|bffcb52d-3f42-4ea7-aa1d-80733b0f5a78", "Imp. Free", "Import Free Days", "The number of import detention free days.");
			zCalcEditColumnStyleInfo1.ColumnName = "JC_Calc_ImportDetentionFreeDays";
			zCalcEditColumnStyleInfo1.Decimals = 0;
			zCalcEditColumnStyleInfo1.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|2bd8f009-5e2d-479c-8a8f-de48ced2a341", "Import Detention");
			zCalcEditColumnStyleInfo1.IsVisible = false;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.Caption = null;
			zCalcEditColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|2efd0953-d552-474f-851b-f7fba9164a06", "Imp. Over.", "Import Overdue Days", "The number of days this container is into import detention.");
			zCalcEditColumnStyleInfo2.ColumnName = "JC_Calc_ImportDetentionOverdueDays";
			zCalcEditColumnStyleInfo2.Decimals = 0;
			zCalcEditColumnStyleInfo2.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|2bd8f009-5e2d-479c-8a8f-de48ced2a341", "Import Detention");
			zCalcEditColumnStyleInfo2.IsVisible = false;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.Caption = null;
			zCalcEditColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|0dd12c8e-76d1-4ac5-b82c-55b4a82f1245", "Exp. Free", "Export Free Days", "The number of export detention free days.");
			zCalcEditColumnStyleInfo3.ColumnName = "JC_Calc_ExportDetentionFreeDays";
			zCalcEditColumnStyleInfo3.Decimals = 0;
			zCalcEditColumnStyleInfo3.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|9be8fdf1-22ee-49a4-80e2-3e778c936ced", "Export Detention");
			zCalcEditColumnStyleInfo3.IsVisible = false;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo4.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo4.Caption = null;
			zCalcEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|204fe611-7b13-4ec1-8971-ab370f0e66ea", "Exp. Over.", "Export Overdue Days", "The number of days this container is into export detention.");
			zCalcEditColumnStyleInfo4.ColumnName = "JC_Calc_ExportDetentionOverdueDays";
			zCalcEditColumnStyleInfo4.Decimals = 0;
			zCalcEditColumnStyleInfo4.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|9be8fdf1-22ee-49a4-80e2-3e778c936ced", "Export Detention");
			zCalcEditColumnStyleInfo4.IsVisible = false;
			zCalcEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zMultiControlColumnStyleInfo1.Caption = null;
			zMultiControlColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|324ea220-cc76-4835-b495-e26a20bed4ef", "Booking Party");
			zMultiControlColumnStyleInfo1.ColumnName = "Booking+BookingPartyNameOrPK";
			zMultiControlColumnStyleInfo1.FieldTypeColumnName = "Booking+BookingPartyFieldType";
			zMultiControlColumnStyleInfo1.IsVisible = false;
			zMultiControlColumnStyleInfo2.Caption = null;
			zMultiControlColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|e7757405-b1f4-42ff-ad55-ce9c69867b03", "Consignor");
			zMultiControlColumnStyleInfo2.ColumnName = "Booking+ConsignorNameOrPK";
			zMultiControlColumnStyleInfo2.FieldTypeColumnName = "Booking+ConsignorFieldType";
			zMultiControlColumnStyleInfo2.IsVisible = false;
			zMultiControlColumnStyleInfo3.Caption = null;
			zMultiControlColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|74986bcb-052f-4c55-ba52-e6a4a889555c", "Consignee");
			zMultiControlColumnStyleInfo3.ColumnName = "Booking+ConsigneeNameOrPK";
			zMultiControlColumnStyleInfo3.FieldTypeColumnName = "Booking+ConsigneeFieldType";
			zMultiControlColumnStyleInfo3.IsVisible = false;
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.Caption = null;
			zCalcEditColumnStyleInfo5.CaptionResourceString = null;
			zCalcEditColumnStyleInfo5.ColumnName = "JC_Calc_NetWeight";
			zCalcEditColumnStyleInfo5.Decimals = 3;
			zCalcEditColumnStyleInfo5.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|fd3099f5-19f8-4864-bbc9-0a0dee0c28b3", "Weight");
			zCalcEditColumnStyleInfo5.IsVisible = false;
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.Caption = null;
			zCalcEditColumnStyleInfo6.CaptionResourceString = null;
			zCalcEditColumnStyleInfo6.ColumnName = "JC_GrossWeight";
			zCalcEditColumnStyleInfo6.Decimals = 3;
			zCalcEditColumnStyleInfo6.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|fd3099f5-19f8-4864-bbc9-0a0dee0c28b3", "Weight");
			zCalcEditColumnStyleInfo6.IsVisible = false;
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.Caption = null;
			zCalcEditColumnStyleInfo8.CaptionResourceString = null;
			zCalcEditColumnStyleInfo8.ColumnName = "JC_TareWeight";
			zCalcEditColumnStyleInfo8.Decimals = 3;
			zCalcEditColumnStyleInfo8.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|fd3099f5-19f8-4864-bbc9-0a0dee0c28b3", "Weight");
			zCalcEditColumnStyleInfo8.IsVisible = false;
			zDropEditColumnStyleInfo1.Caption = null;
			zDropEditColumnStyleInfo1.CaptionResourceString = null;
			zDropEditColumnStyleInfo1.ColumnName = "JC_GrossWeightUQ";
			zDropEditColumnStyleInfo1.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|fd3099f5-19f8-4864-bbc9-0a0dee0c28b3", "Weight");
			zDropEditColumnStyleInfo1.IsVisible = false;
			zDropEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo5.Caption = null;
			zTextBoxColumnStyleInfo5.CaptionResourceString = null;
			zTextBoxColumnStyleInfo5.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo5.ColumnName = "Booking+JS_RL_NKOrigin";
			zTextBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo2.Caption = null;
			zCodeFindBoxColumnStyleInfo2.CaptionResourceString = null;
			zCodeFindBoxColumnStyleInfo2.ColumnName = "Booking+JS_RL_NKDestination";
			zCodeFindBoxColumnStyleInfo2.IsVisible = false;
			zCodeFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo3.Caption = null;
			zCodeFindBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|4496ee22-08a2-4606-80e1-96a2aaf5790f", "Load Port");
			zCodeFindBoxColumnStyleInfo3.ColumnName = "Booking+JS_NKLoadPort";
			zCodeFindBoxColumnStyleInfo3.IsVisible = false;
			zCodeFindBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo4.Caption = null;
			zCodeFindBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|52cb61da-a11e-4441-8d84-6149a81edbc2", "Disc. Port", "Discharge Port", "");
			zCodeFindBoxColumnStyleInfo4.ColumnName = "Booking+JS_NKDischargePort";
			zCodeFindBoxColumnStyleInfo4.IsVisible = false;
			zCodeFindBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDropEditColumnStyleInfo2.Caption = null;
			zDropEditColumnStyleInfo2.CaptionResourceString = null;
			zDropEditColumnStyleInfo2.ColumnName = "JC_ContainerQuality";
			zDropEditColumnStyleInfo2.IsVisible = false;
			zDropEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCheckBoxColumnStyleInfo1.Caption = null;
			zCheckBoxColumnStyleInfo1.CaptionResourceString = null;
			zCheckBoxColumnStyleInfo1.ColumnName = "JC_IsEmptyContainer";
			zCheckBoxColumnStyleInfo1.IsVisible = false;
			zCheckBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCheckBoxColumnStyleInfo2.Caption = null;
			zCheckBoxColumnStyleInfo2.CaptionResourceString = null;
			zCheckBoxColumnStyleInfo2.ColumnName = "JC_IsShipperOwned";
			zCheckBoxColumnStyleInfo2.IsVisible = false;
			zCheckBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo5.Caption = null;
			zCodeFindBoxColumnStyleInfo5.CaptionResourceString = null;
			zCodeFindBoxColumnStyleInfo5.ColumnName = "JC_RH_NKContainerCommodityCode";
			zCodeFindBoxColumnStyleInfo5.IsVisible = false;
			zCodeFindBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(65);
			importReleaseOrderStatusStyleInfo.Caption = null;
			importReleaseOrderStatusStyleInfo.ColumnName = "JC_ImportReleaseOrderStatus";
			importReleaseOrderStatusStyleInfo.IsVisible = false;
			zGuidFindBoxColumnStyleInfo2.BindToList = "Lookups+ContainerYard_List";
			zGuidFindBoxColumnStyleInfo2.Caption = null;
			zGuidFindBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|a485b829-1fdf-423e-aca1-3a92e0966e38", "Exp. Yard", "Empty Pickup From", "The yard address where the empty container can be collected.");
			zGuidFindBoxColumnStyleInfo2.ColumnName = "JC_OA_DepartureContainerYardAddress_ZAddress+OrgPK";
			zGuidFindBoxColumnStyleInfo2.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|aaf520d4-5dba-45f1-b550-be851b15732a", "Empty Pickup From");
			zGuidFindBoxColumnStyleInfo2.IsVisible = false;
			zGuidDropEditColumnStyleInfo1.Caption = null;
			zGuidDropEditColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|4fa350a5-86d7-42d2-bde1-a424a4bfc68b", "Address", "Empty Pickup From Address", "The yard address where the empty container can be collected.");
			zGuidDropEditColumnStyleInfo1.ColumnName = "JC_OA_DepartureContainerYardAddress";
			zGuidDropEditColumnStyleInfo1.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|aaf520d4-5dba-45f1-b550-be851b15732a", "Empty Pickup From");
			zGuidDropEditColumnStyleInfo1.IsVisible = false;
			zGuidFindBoxColumnStyleInfo3.BindToList = "Lookups+ContainerYard_List";
			zGuidFindBoxColumnStyleInfo3.Caption = null;
			zGuidFindBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|0f5197e9-42dc-4d41-b77d-a571a9d21007", "Imp. Yard", "Empty Return To", "The yard address where the empty container is to be returned.");
			zGuidFindBoxColumnStyleInfo3.ColumnName = "JC_OA_ArrivalContainerYardAddress_ZAddress+OrgPK";
			zGuidFindBoxColumnStyleInfo3.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|8cf9e37b-e53b-44dd-813c-5e9e3f664460", "Empty Return To");
			zGuidFindBoxColumnStyleInfo3.IsVisible = false;
			zGuidDropEditColumnStyleInfo2.Caption = null;
			zGuidDropEditColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|6bab6fbc-3f2a-47a9-a258-1150fe6b2e8b", "Address", "Empty Return To Address", "The yard address where the empty container is to be returned.");
			zGuidDropEditColumnStyleInfo2.ColumnName = "JC_OA_ArrivalContainerYardAddress";
			zGuidDropEditColumnStyleInfo2.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|8cf9e37b-e53b-44dd-813c-5e9e3f664460", "Empty Return To");
			zGuidDropEditColumnStyleInfo2.IsVisible = false;
			zTextBoxColumnStyleInfo7.Caption = null;
			zTextBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|7d2ddb7a-1f25-4449-b8c5-047b7b0943dc", "Booking Ref", "The booking reference.");
			zTextBoxColumnStyleInfo7.ColumnName = "Booking+JS_CFSReference";
			zTextBoxColumnStyleInfo7.IsVisible = false;
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.Caption = null;
			zCalcEditColumnStyleInfo7.CaptionResourceString = null;
			zCalcEditColumnStyleInfo7.ColumnName = "JC_SetPointTemp";
			zCalcEditColumnStyleInfo7.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|594cd546-893d-4e41-826a-aae423b3e13a", "Temperature");
			zCalcEditColumnStyleInfo7.IsVisible = false;
			zDropEditColumnStyleInfo3.Caption = null;
			zDropEditColumnStyleInfo3.CaptionResourceString = null;
			zDropEditColumnStyleInfo3.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo3.ColumnName = "JC_SetPointTempUnit";
			zDropEditColumnStyleInfo3.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|594cd546-893d-4e41-826a-aae423b3e13a", "Temperature");
			zDropEditColumnStyleInfo3.IsVisible = false;
			zDropEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zDropEditColumnStyleInfo4.ColumnName = "JC_SealParty";
			zDropEditColumnStyleInfo4.IsVisible = false;
			zDropEditColumnStyleInfo5.ColumnName = "JC_AdditionalSealParty";
			zDropEditColumnStyleInfo5.IsVisible = false;
			zDropEditColumnStyleInfo6.ColumnName = "JC_Additional2SealParty";
			zDropEditColumnStyleInfo6.IsVisible = false;
			zTextBoxColumnStyleInfo8.Caption = null;
			zTextBoxColumnStyleInfo8.CaptionResourceString = null;
			zTextBoxColumnStyleInfo8.ColumnName = "JC_SealNum";
			zTextBoxColumnStyleInfo8.IsVisible = false;
			zGuidFindBoxColumnStyleInfo4.Caption = null;
			zGuidFindBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|90da6972-9b8b-41e9-a7cc-90e57cfcf4c6", "Arv CTO", "Arrival CTO", "The CTO where the vessel is expected to arrive.");
			zGuidFindBoxColumnStyleInfo4.ColumnName = "Booking+Sailing+Destination+JB_Calc_ArrivalCTOAddressOrg";
			zGuidFindBoxColumnStyleInfo4.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|a62251df-1074-48a1-be1c-76af833ff005", "Arrival CTO");
			zGuidFindBoxColumnStyleInfo4.IsVisible = false;
			zTextBoxColumnStyleInfo9.Caption = null;
			zTextBoxColumnStyleInfo9.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|d6187115-d413-452e-b85c-7fc9da0012eb", "Address", "Arrival CTO Address", "The CTO address where the vessel is expected to arrive.");
			zTextBoxColumnStyleInfo9.ColumnName = "Booking+Sailing+Destination+JB_Calc_ArrivalCTOAddressCode";
			zTextBoxColumnStyleInfo9.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|a62251df-1074-48a1-be1c-76af833ff005", "Arrival CTO");
			zTextBoxColumnStyleInfo9.IsVisible = false;
			zGuidFindBoxColumnStyleInfo5.Caption = null;
			zGuidFindBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|3e49f17a-7f90-492b-b93a-8c1767351cde", "Dep. CTO", "Departure CTO", "The CTO where the vessel is expected to depart.");
			zGuidFindBoxColumnStyleInfo5.ColumnName = "Booking+Sailing+Origin+JA_Calc_DepartureCTOAddressOrg";
			zGuidFindBoxColumnStyleInfo5.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|5d60836c-2704-443a-9228-0369742d2e66", "Departure CTO");
			zGuidFindBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo10.Caption = null;
			zTextBoxColumnStyleInfo10.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|6c65a39c-12b6-40bd-822b-02803e995ee2", "Address", "Departure CTO Address", "The CTO address where the vessel is expected to depart.");
			zTextBoxColumnStyleInfo10.ColumnName = "Booking+Sailing+Origin+JA_Calc_DepartureCTOAddressCode";
			zTextBoxColumnStyleInfo10.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|5d60836c-2704-443a-9228-0369742d2e66", "Departure CTO");
			zTextBoxColumnStyleInfo10.IsVisible = false;
			zTextBoxColumnStyleInfo11.Caption = null;
			zTextBoxColumnStyleInfo11.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|d13c0e89-14e2-4450-8315-655578506da5", "Local Client");
			zTextBoxColumnStyleInfo11.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo11.ColumnName = "Booking+Job+LocalCharges+OH_Code";
			zTextBoxColumnStyleInfo11.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|56e7a726-7465-4f9a-b8fe-f30402e267c2", "Local Client");
			zTextBoxColumnStyleInfo11.IsVisible = false;
			zTextBoxColumnStyleInfo12.Caption = null;
			zTextBoxColumnStyleInfo12.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|59da8b64-cddc-4594-bab6-5244fdb0d0e6", "Local Client Company Name");
			zTextBoxColumnStyleInfo12.ColumnName = "Booking+Job+LocalCharges+OH_FullName";
			zTextBoxColumnStyleInfo12.GroupName = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|56e7a726-7465-4f9a-b8fe-f30402e267c2", "Local Client");
			zTextBoxColumnStyleInfo12.IsVisible = false;
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			importReleaseNumberColumnStyleInfo.Caption = null;
			importReleaseNumberColumnStyleInfo.CaptionResourceString = null;
			importReleaseNumberColumnStyleInfo.ColumnName = "JC_ContainerImportDORelease";
			importReleaseNumberColumnStyleInfo.IsVisible = false;
			zTextBoxColumnStyleInfo14.Caption = null;
			zTextBoxColumnStyleInfo14.CaptionResourceString = null;
			zTextBoxColumnStyleInfo14.ColumnName = "JC_AdditionalSealNum";
			zTextBoxColumnStyleInfo14.IsVisible = false;
			zTextBoxColumnStyleInfo15.Caption = null;
			zTextBoxColumnStyleInfo15.CaptionResourceString = null;
			zTextBoxColumnStyleInfo15.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo15.ColumnName = "JC_ContainerMode";
			zTextBoxColumnStyleInfo15.IsVisible = false;
			zTextBoxColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo16.Caption = null;
			zTextBoxColumnStyleInfo16.ColumnName = "JC_DepartureDockReceipt";
			zTextBoxColumnStyleInfo16.IsVisible = false;
			zTextBoxColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo5.Caption = null;
			zDateEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|c967f367-2e51-4d4e-9225-3e25fb19d4c0", "ETD");
			zDateEditColumnStyleInfo5.ColumnName = "Booking+Sailing+JX_JA_E_DEP";
			zDateEditColumnStyleInfo5.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo6.Caption = null;
			zDateEditColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|4a999cfd-67c5-4b76-94bc-1a038c49f78a", "ETA");
			zDateEditColumnStyleInfo6.ColumnName = "Booking+Sailing+JX_JB_E_ARV";
			zDateEditColumnStyleInfo6.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo7.Caption = null;
			zDateEditColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|4b814d1a-a51d-4e28-b27f-b33d2f91911e", "ATD");
			zDateEditColumnStyleInfo7.ColumnName = "Booking+Sailing+Origin+JA_A_DEP";
			zDateEditColumnStyleInfo7.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo7.IsVisible = false;
			zDateEditColumnStyleInfo8.Caption = null;
			zDateEditColumnStyleInfo8.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|129af97b-dca4-4ce7-a0ac-20a3db3715d7", "ATA");
			zDateEditColumnStyleInfo8.ColumnName = "Booking+Sailing+Destination+JB_A_ARV";
			zDateEditColumnStyleInfo8.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo8.IsVisible = false;
			zCheckBoxColumnStyleInfo3.ColumnName = "JC_IsDamaged";
			zCheckBoxColumnStyleInfo3.IsVisible = false;
			zCheckBoxColumnStyleInfo4.ColumnName = "JC_IsSealOk";
			zCheckBoxColumnStyleInfo4.IsVisible = false;
			zCheckBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|587b932a-db07-4b40-85fd-0e588b1d81af", "Temp. Controlled");
			zCheckBoxColumnStyleInfo5.ColumnName = "JC_IsControlledAtmosphere";
			zCheckBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo17.ColumnName = "JC_TempRecorderSerialNo";
			zTextBoxColumnStyleInfo17.IsVisible = false;
			zDropEditColumnStyleInfo7.ColumnName = "JC_ContainerStatus";
			zDropEditColumnStyleInfo7.IsVisible = false;
			zTextBoxColumnStyleInfo18.ColumnName = "JC_Additional2SealNum";
			zTextBoxColumnStyleInfo18.IsVisible = false;
			emptyReturnReferenceColumnStyleInfo.ColumnName = "JC_EmptyReturnReference";
			emptyReturnReferenceColumnStyleInfo.IsVisible = false;
			additionalNumbersColumnStyleInfo.CaptionResourceString = Enterprise.Freight.Agency.Module.Res.GetData("BillContainersFilterControl|08e223d8-ee42-44d4-85c7-4ce160072126", "Additional Reference");
			additionalNumbersColumnStyleInfo.ColumnName = "AdditionalReferenceNumbersAsString";
			additionalNumbersColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			additionalNumbersColumnStyleInfo.IsVisible = false;
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zMultiControlColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(importReleaseOrderStatusStyleInfo);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo1);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo2);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.grid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.grid.ColumnStyles.Add(importReleaseNumberColumnStyleInfo);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(zDateEditColumnStyleInfo8);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo6);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo3);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo4);
			this.grid.ColumnStyles.Add(zCheckBoxColumnStyleInfo5);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.grid.ColumnStyles.Add(zTextBoxColumnStyleInfo18);
			this.grid.ColumnStyles.Add(zDropEditColumnStyleInfo7);
			this.grid.ColumnStyles.Add(emptyReturnReferenceColumnStyleInfo);
			this.grid.ColumnStyles.Add(additionalNumbersColumnStyleInfo);
			this.grid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(758, 194, true);
			// 
			// BillContainersFilterControl
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
			this.CaptionRenderingEnabled = true;
			this.Name = "BillContainersFilterControl";
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(758, 346, true);
			((System.ComponentModel.ISupportInitialize)(this.grid)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo importReleaseOrderStatusStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
		Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo importReleaseNumberColumnStyleInfo = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
	}
}
