<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.DEReferenceData.Tests</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.DEReferenceData.Tests</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.XmlProducer.Common">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.XmlProducer.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DEReferenceData.Business\DEReferenceData.Business.csproj" />
    <ProjectReference Include="..\DEReferenceData.Services\DEReferenceData.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\IMPORT_10.0_CODELISTS_DOWNLOAD_LINKS.uri" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_C0754_TRANSPORT_DOCUMENT_TYPES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_C0754_TRANSPORT_DOCUMENT_TYPES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_C0754_TRANSPORT_DOCUMENT_TYPES.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Output\RefExchangeRateZZ_DE_Listed.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Output\RefExchangeRateZZ_DE_UnListed.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\NCTS_10.1_CODELISTS_DOWNLOAD_LINKS.uri" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0037_CN_CODES.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0037_CN_CODES_FAULTY.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0011_MEMBER_STATES.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0011_MEMBER_STATES_FAULTY.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0017_PACK_TYPES.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0017_PACK_TYPES_FAULTY.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0036_PRODUCT_CODES.zip" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Input\EMCS_CL0036_PRODUCT_CODES_FAULTY.zip" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A2060_METHOD_OF_PAYMENT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A2060_METHOD_OF_PAYMENT_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\EXPORT_3.0_CODELISTS_DOWNLOAD_LINKS.uri" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\IMPORT_10.1_CODELISTS_DOWNLOAD_LINKS.uri" />
    <EmbeddedResource Include="Services\DeTariffs\TestFiles\*" />
    <EmbeddedResource Include="Business\DeTariffs\TestFiles\**\*" />
    <EmbeddedResource Include="Services\TestFiles\EXPORT_CODELISTS_DOWNLOAD_LINKS_UNION.uri" />
    <EmbeddedResource Include="Services\TestFiles\EXPORT_CODELISTS_DOWNLOAD_LINKS_PRIMARY.uri" />
    <EmbeddedResource Include="Services\TestFiles\EXPORT_CODELISTS_DOWNLOAD_LINKS_SECONDARY.uri" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0200_TARIC_CODES_AND_CERTIFICATES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0200_TARIC_CODES_AND_CERTIFICATES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0255_ZELOS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0255_ZELOS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_DC44I_TARIC_CODES_AND_CERTIFICATES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\EMCS_CODELISTS_DOWNLOAD_PAGE.html" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Output\RefCusCodeListZZ_DE_EMCS_EMCCN_CN_CODES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\EMCS_CODELISTS_DOWNLOAD_PAGE_FAULTY.html" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0600_DEPARTURE_AIRPORTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0600_DEPARTURE_AIRPORTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_EUIAT_DEPARTURE_AIRPORTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Output\RefCusCodeListZZ_DE_EMCS_EMCMS_MEMBER_STATES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0810_COUNTRY_LIST_SPECIFIC_SANCTIONS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0810_COUNTRY_LIST_SPECIFIC_SANCTIONS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_I0810_COUNTRY_LIST_SPECIFIC_SANCTIONS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0139_PRODUCT_NUMBERS_OILS_AND_GASES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0139_PRODUCT_NUMBERS_OILS_AND_GASES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_I0139_PRODUCT_NUMBERS_OILS_AND_GASES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EX17_DESTINATION_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0806_COUNTRY_LIST_CO.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0806_COUNTRY_LIST_CO_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0811_COUNTRY_LIST_EU.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0811_COUNTRY_LIST_EU_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0812_COUNTRY_LIST_CO_REEXPORT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_I0812_COUNTRY_LIST_CO_REEXPORT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0812_COUNTRY_LIST_CO_REEXPORT_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_MOP_METHOD_OF_PAYMENT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1150_TRANSACTION_NATURE.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_TRNAT_TRANSACTION_NATURE.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1150_TRANSACTION_NATURE_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0700_CUSTOMS_DECLARATION_UNITS_OF_QUANTITY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0700_CUSTOMS_DECLARATION_UNITS_OF_QUANTITY_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_CUSUQ_CUSTOMS_DECLARATION_UNITS_OF_QUANTITY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Output\RefCusCodeListZZ_DE_EMCS_EMCPK_PACK_TYPES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Emcs\TestFiles\Output\RefCusCodeListZZ_DE_EMCS_EPC_PRODUCT_CODES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0009_COUNTRY_CODES_COMMON_TRANSIT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0009_COUNTRY_CODES_COMMON_TRANSIT_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_C0009_COUNTRY_CODES_COMMON_TRANSIT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0010_COUNTRY_CODES_COMMUNITY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_NC010_COUNTRY_CODES_COMMUNITY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0010_COUNTRY_CODES_COMMUNITY_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0809_COUNTRY_LIST_REIMPORT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0809_COUNTRY_LIST_REIMPORT_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_I0809_COUNTRY_LIST_REIMPORT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0008_COUNTRY_CODES_FULL_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_C0008_COUNTRY_CODES_FULL_LIST_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_NC008_COUNTRY_CODES_FULL_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IMPORT_A2055_ECONOMIC_CONDITIONS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A2055_ECONOMIC_CONDITIONS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A2055_ECONOMIC_CONDITIONS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1314_EU_MEMBER_STATES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Generic\TestFiles\Output\RefCusCodeListZZ_DE_CO17_DESTINATION_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1314_EU_MEMBER_STATES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Generic\TestFiles\Output\RefCusCodeListZZ_DE_CO15_ORIGIN_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0010_COUNTRY_CODES_COMMUNITY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0010_COUNTRY_CODES_COMMUNITY_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EX15_ORIGIN_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_IM17_DESTINATION_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Output\RefCusCodeListZZ_DE_IM15_ORIGIN_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0300_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_I0300_COUNTRY_LIST_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1300_EFTA_COUNTRIES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Import\TestFiles\Input\IMPORT_A1300_EFTA_COUNTRIES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Generic\TestFiles\Output\RefCusCodeListZZ_DE_EU15_ORIGIN_COUNTRY_LIST.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0941_TRANSPORT_DOCUMENT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0941_TRANSPORT_DOCUMENT_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_TD44E_TRANSPORT_DOCUMENT.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0352_CURRENCY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0352_CURRENCY_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_CURRE_CURRENCY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0921_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0921_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0922_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0922_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_DC44E_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0931_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0932_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0931_PREVIOUS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0932_PREVIOUS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_DC40E_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0911_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0912_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_AR44E_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0911_ADDITIONAL_REFERENCES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0912_ADDITIONAL_REFERENCES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0923_SUPPORTING_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0923_SUPPORTING_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0925_SUPPORTING_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0925_SUPPORTING_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0926_SUPPORTING_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0926_SUPPORTING_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_DC44N_SUPPORTING_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_DC40N_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0933_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0935_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0936_PREVIOUS_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0933_PREVIOUS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0935_PREVIOUS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0936_PREVIOUS_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0943_TRANSPORT_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0943_TRANSPORT_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0945_TRANSPORT_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0945_TRANSPORT_DOCUMENTS_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_TD44N_TRANSPORT_DOCUMENTS.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0901_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0901_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0902_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0902_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_AI44E_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0913_ADDITIONAL_REFERENCES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0913_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0915_ADDITIONAL_REFERENCES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0915_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0916_ADDITIONAL_REFERENCES_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0916_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_AR44N_ADDITIONAL_REFERENCES.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0900_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_I0900_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Output\RefCusCodeListZZ_DE_EXPORT_AI44X_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0903_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0905_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0906_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0903_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0905_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Input\NCTS_I0906_ADDITIONAL_INFORMATION_FAULTY.xml" />
    <EmbeddedResource Include="Business\CodeLists\Ncts\TestFiles\Output\RefCusCodeListZZ_DE_NCTS_AI44N_ADDITIONAL_INFORMATION.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Output\RefExchangeRateZZ_DE_IATA.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0207_COUNTRY_LIST_EX.xml" />
    <EmbeddedResource Include="Business\CodeLists\Export\TestFiles\Input\EXPORT_C0207_COUNTRY_LIST_EX_FAULTY.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Input\UnlistedExchangeRatesResourceDetails.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Input\ListedExchangeRatesResourceDetails.xml" />
    <EmbeddedResource Include="Business\ExchangeRates\TestFiles\Input\IATAExchangeRatesResourceDetails.xml" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>