CREATE TABLE RefCusProcedure
(
ZZ6_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_PK DEFAULT (NEWID()),
ZZ6_Category VARCHAR(3) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_Category DEFAULT (''),
ZZ6_ProcedureCode VARCHAR(5) NOT NULL,
ZZ6_PreviousProcedureCode VARCHAR(5) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_PreviousProcedureCode DEFAULT (''),
ZZ6_Concession VARCHAR(50) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_Concession DEFAULT (''),
ZZ6_Description NVARCHAR(MAX) NOT NULL,
ZZ6_ZZZ_NKDataGrouping VARCHAR(3) NOT NULL,
ZZ6_ShipmentType VARCHAR(50) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_ShipmentType DEFAULT (''),
ZZ6_CalculateDuty BIT NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_CalculateDuty DEFAULT (1),
ZZ6_Group VARCHAR(200) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_Group DEFAULT (''),
ZZ6_LandedCost BIT NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_LandedCost DEFAULT (0),
ZZ6_IntoWarehouse CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoWarehouse DEFAULT ('N'),
ZZ6_OutOfWarehouse CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutOfWarehouse DEFAULT ('N'),
ZZ6_StartDate SMALLDATETIME not null CONSTRAINT DF_RefCusProcedure_ZZ6_StartDate DEFAULT GetUtcDate(),
ZZ6_EndDate SMALLDATETIME not null CONSTRAINT DF_RefCusProcedure_ZZ6_EndDate DEFAULT '2079-06-06 23:59',
ZZ6_IntoTemporaryImport CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoTemporaryImport DEFAULT ('N'),
ZZ6_OutOfTemporaryImport CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutOfTemporaryImport DEFAULT ('N'),
ZZ6_IntoTemporaryExport CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoTemporaryExport DEFAULT ('N'),
ZZ6_OutOfTemporaryExport CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutOfTemporaryExport DEFAULT ('N'),
ZZ6_IntoInwardProcessing CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoInwardProcessing DEFAULT ('N'),
ZZ6_OutOfInwardProcessing CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutOfInwardProcessing DEFAULT ('N'),
ZZ6_IntoOutwardProcessing CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoOutwardProcessing DEFAULT ('N'),
ZZ6_OutofOutwardProcessing CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutofOutwardProcessing DEFAULT ('N'),
ZZ6_CalculateVAT BIT NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_CalculateVAT DEFAULT (1),
ZZ6_IsGuaranteeConsumed CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IsGuaranteeConsumed DEFAULT ('N'),
ZZ6_IsGuaranteeReleased CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IsGuaranteeReleased DEFAULT ('N'),
ZZ6_IsTransit CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IsTransit DEFAULT ('N'),
ZZ6_IntoVATWarehouse CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_IntoVATWarehouse DEFAULT ('N'),
ZZ6_OutOfVATWarehouse CHAR(1) NOT NULL CONSTRAINT DF_RefCusProcedure_ZZ6_OutOfVATWarehouse DEFAULT ('N'),
CONSTRAINT PK_RefCusProcedure PRIMARY KEY CLUSTERED( ZZ6_PK ASC ),
CONSTRAINT CK_RefCusProcedure_ZZ6_ProcedureCode CHECK (ZZ6_ProcedureCode <> ''),
CONSTRAINT CK_RefCusProcedure_ZZ6_Description CHECK (ZZ6_Description <>''),
CONSTRAINT CK_RefCusProcedure_ZZ6_StartDate_ZZ6_EndDate CHECK (ZZ6_StartDate < ZZ6_EndDate),
CONSTRAINT CK_RefCusProcedure_ZZ6_ZZZ_NKDataGrouping CHECK (ZZ6_ZZZ_NKDataGrouping <>''),
CONSTRAINT FK_RefCusProcedure_RefDataGrouping FOREIGN KEY (ZZ6_ZZZ_NKDataGrouping) REFERENCES RefDataGrouping (ZZZ_DataGrouping),
CONSTRAINT CK_RefCusProcedure_ZZ6_IntoWarehouse CHECK ((ZZ6_IntoWarehouse='Y' AND ZZ6_IntoOutwardProcessing<>'Y' AND ZZ6_IntoInwardProcessing<>'Y' AND (ZZ6_IntoTemporaryImport<>'Y' AND ZZ6_IntoTemporaryExport<>'Y')) OR (ZZ6_IntoWarehouse='N' OR ZZ6_IntoWarehouse='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_OutOfWarehouse CHECK ((ZZ6_OutOfWarehouse='Y' AND ZZ6_OutofOutwardProcessing<>'Y' AND (ZZ6_OutOfTemporaryImport<>'Y' AND ZZ6_OutOfTemporaryExport<>'Y') AND ZZ6_OutOfInwardProcessing<>'Y') OR (ZZ6_OutOfWarehouse='N' OR ZZ6_OutOfWarehouse='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_IsGuaranteeConsumed CHECK ([ZZ6_IsGuaranteeConsumed]='Y' OR [ZZ6_IsGuaranteeConsumed]='N' OR [ZZ6_IsGuaranteeConsumed]='I'),
CONSTRAINT CK_RefCusProcedure_ZZ6_IsGuaranteeReleased CHECK ([ZZ6_IsGuaranteeReleased]='Y' OR [ZZ6_IsGuaranteeReleased]='N' OR [ZZ6_IsGuaranteeReleased]='I'),
CONSTRAINT CK_RefCusProcedure_ZZ6_IsTransit CHECK ([ZZ6_IsTransit]='Y' OR [ZZ6_IsTransit]='N' OR [ZZ6_IsTransit]='I'),
CONSTRAINT CK_RefCusProcedure_ZZ6_IntoTemporaryImport CHECK ((ZZ6_IntoTemporaryImport='Y' AND ZZ6_IntoTemporaryExport<>'Y' AND ZZ6_IntoWarehouse<>'Y' AND ZZ6_IntoInwardProcessing<>'Y' AND ZZ6_IntoOutwardProcessing<>'Y') OR (ZZ6_IntoTemporaryImport='N' OR ZZ6_IntoTemporaryImport='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_IntoTemporaryExport CHECK ((ZZ6_IntoTemporaryExport='Y' AND ZZ6_IntoTemporaryImport<>'Y' AND ZZ6_IntoWarehouse<>'Y' AND ZZ6_IntoInwardProcessing<>'Y' AND ZZ6_IntoOutwardProcessing<>'Y') OR (ZZ6_IntoTemporaryExport='N' OR ZZ6_IntoTemporaryExport='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_OutOfTemporaryImport CHECK ((ZZ6_OutOfTemporaryImport='Y' AND ZZ6_OutOfTemporaryExport<>'Y' AND ZZ6_OutOfWarehouse<>'Y' AND ZZ6_OutOfInwardProcessing<>'Y' AND ZZ6_OutofOutwardProcessing<>'Y') OR (ZZ6_OutOfTemporaryImport='N' OR ZZ6_OutOfTemporaryImport='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_OutOfTemporaryExport CHECK ((ZZ6_OutOfTemporaryExport='Y' AND ZZ6_OutOfTemporaryImport<>'Y' AND ZZ6_OutOfWarehouse<>'Y' AND ZZ6_OutOfInwardProcessing<>'Y' AND ZZ6_OutofOutwardProcessing<>'Y') OR (ZZ6_OutOfTemporaryExport='N' OR ZZ6_OutOfTemporaryExport='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_IntoInwardProcessing CHECK ((ZZ6_IntoInwardProcessing='Y' AND ZZ6_IntoWarehouse<>'Y' AND (ZZ6_IntoTemporaryImport<>'Y' AND ZZ6_IntoTemporaryExport<>'Y') AND ZZ6_IntoOutwardProcessing<>'Y') OR (ZZ6_IntoInwardProcessing='N' OR ZZ6_IntoInwardProcessing='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_OutOfInwardProcessing CHECK ((ZZ6_OutOfInwardProcessing='Y' AND ZZ6_OutOfWarehouse<>'Y' AND (ZZ6_OutOfTemporaryImport<>'Y' AND ZZ6_OutOfTemporaryExport<>'Y') AND ZZ6_OutofOutwardProcessing<>'Y') OR (ZZ6_OutOfInwardProcessing='N' OR ZZ6_OutOfInwardProcessing='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_IntoOutwardProcessing CHECK ((ZZ6_IntoOutwardProcessing='Y' AND ZZ6_IntoWarehouse<>'Y' AND ZZ6_IntoInwardProcessing<>'Y' AND (ZZ6_IntoTemporaryImport<>'Y' AND ZZ6_IntoTemporaryExport<>'Y')) OR (ZZ6_IntoOutwardProcessing='N' OR ZZ6_IntoOutwardProcessing='I')),
CONSTRAINT CK_RefCusProcedure_ZZ6_OutofOutwardProcessing CHECK ((ZZ6_OutofOutwardProcessing='Y' AND ZZ6_OutOfWarehouse<>'Y' AND (ZZ6_OutOfTemporaryImport<>'Y' AND ZZ6_OutOfTemporaryExport<>'Y') AND ZZ6_OutOfInwardProcessing<>'Y') OR (ZZ6_OutofOutwardProcessing='N' OR ZZ6_OutofOutwardProcessing='I'))
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusProcedure_ZZ6_ZZZ_NKDataGrouping_ZZ6_ProcedureCode_ZZ6_PreviousProcedureCode_ZZ6_Concession_ZZ6_Category ON RefCusProcedure( ZZ6_ZZZ_NKDataGrouping, ZZ6_ProcedureCode, ZZ6_PreviousProcedureCode, ZZ6_Concession, ZZ6_Category )
GO
