CREATE TABLE [RefUNLOCO](
	[RL_PK] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT [DF_RefUNLOCO_RL_PK] DEFAULT (NEWID()),
	[RL_Code] [VARCHAR](5) NOT NULL CONSTRAINT [DF_RefUNLOCO_RL_Code]  DEFAULT (''),
	CONSTRAINT [PK_RefUNLOCO] PRIMARY KEY CLUSTERED ([RL_PK] ASC)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefUNLOCO_RL_Code] ON [RefUNLOCO] ([RL_Code] ASC)
GO
