CREATE TABLE [RefUNLOCORelatedPort](
	[RLR_PK] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT [DF_RefUNLOCORelatedPort_RLR_PK] DEFAULT (NEWID()),
	[RLR_GroupNumber] [SMALLINT] NOT NULL,
	[RLR_RL_NKRelatedPort] [VARCHAR](5) NOT NULL,
	CONSTRAINT [PK_RefUNLOCORelatedPort] PRIMARY KEY NONCLUSTERED ([RLR_PK]),
	CONSTRAINT [FK_RefUNLOCORelatedPort_RefUNLOCO] FOREIGN KEY ([RLR_RL_NKRelatedPort]) REFERENCES [RefUNLOCO] ([RL_Code]),
)
GO
CREATE UNIQUE CLUSTERED INDEX [IX_RefUNLOCORelatedPort_RLR_GroupNumber_RLR_RL_NKRelatedPort] ON [RefUNLOCORelatedPort] ([RLR_GroupNumber] ASC, [RLR_RL_NKRelatedPort] ASC)
GO
CREATE NONCLUSTERED INDEX [IX_RefUNLOCORelatedPort_RLR_RL_NKRelatedPort] ON [RefUNLOCORelatedPort] ([RLR_RL_NKRelatedPort] ASC)
GO
