CREATE TABLE [RefUNLOCOUtcOffset](
	[RLO_PK] [UNIQUEIDENTIFIER] NOT NULL,
	[RLO_RL_NKCode] [VARCHAR](5) NOT NULL CONSTRAINT [DF_RefUNLOCOUtcOffset_RLO_RL_NKCode]  DEFAULT (''),
	[RLO_StartTimeUtc] [SMALLDATETIME] NOT NULL,
	[RLO_EndTimeUtc] [SMALLDATETIME] NOT NULL,
	[RLO_OffsetMinutesFromUtc] [SMALLINT] NOT NULL CONSTRAINT [DF_RefUNLOCOUtcOffset_RLO_OffsetMinutesFromUtc]  DEFAULT ((0)),
	CONSTRAINT [PK_RefUNLOCOUtcOffset] PRIMARY KEY ([RLO_PK]),
	CONSTRAINT [RefUNLOCOUtcOffset_RLO_EndTimeUtc] CHECK  (([RLO_EndTimeUtc]>[RLO_StartTimeUtc])),
	CONSTRAINT [RefUNLOCOUtcOffset_RLO_RL_NKCode] CHECK  ((LEN([RLO_RL_NKCode])=(5))),
	CONSTRAINT [FK_RefUNLOCOUtcOffset_RefUNLOCO] FOREIGN KEY([RLO_RL_NKCode]) REFERENCES RefUNLOCO ([RL_Code])
)
GO
CREATE NONCLUSTERED INDEX [IX_RefUNLOCOUtcOffset_RLO_RL_NKCode] ON [RefUNLOCOUtcOffset] ([RLO_RL_NKCode] ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefUNLOCOUtcOffset_RLO_RL_NKCode_RLO_StartTimeUtc] ON [RefUNLOCOUtcOffset] (RLO_RL_NKCode ASC,RLO_StartTimeUtc ASC)
GO
