CREATE TABLE RefVesselZZ 
(
ZZO_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RefVesselZZ_ZZO_PK DEFAULT (NEWID()),
ZZO_Code VARCHAR(35) NOT NULL,
ZZO_RadioCallSign VARCHAR(10) NOT NULL CONSTRAINT DF_RefVesselZZ_ZZO_RadioCallSign DEFAULT (''),
ZZO_VesselType VARCHAR(3) NOT NULL CONSTRAINT DF_RefVesselZZ_ZZO_VesselType DEFAULT (''),
ZZO_RN_NKCountryOfReg VARCHAR(2) NOT NULL CONSTRAINT DF_RefVesselZZ_ZZO_RN_NKCountryOfReg DEFAULT (''),
ZZO_LloydsNumber VARCHAR(7) NOT NULL CONSTRAINT DF_RefVesselZZ_ZZO_LloydsNumber DEFAULT (''),
ZZO_ZZZ_NKDataGrouping VARCHAR(3) NOT NULL,
CONSTRAINT PK_RefVesselZZ PRIMARY KEY CLUSTERED (ZZO_PK ASC),
CONSTRAINT CK_RefVesselZZ_ZZO_Code CHECK (ZZO_Code <> ''),
CONSTRAINT CK_RefVesselZZ_ZZO_ZZZ_NKDataGrouping CHECK (ZZO_ZZZ_NKDataGrouping <> ''),
CONSTRAINT FK_RefVesselZZ_RefDataGrouping FOREIGN KEY (ZZO_ZZZ_NKDataGrouping) REFERENCES RefDataGrouping (ZZZ_DataGrouping)
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefVesselZZ_ZZO_Code_ZZO_ZZZ_NKDataGrouping_ZZO_RadioCallSign ON RefVesselZZ(ZZO_Code ASC, ZZO_ZZZ_NKDataGrouping ASC, ZZO_RadioCallSign ASC)
GO
CREATE NONCLUSTERED INDEX IX_RefVesselZZ_ZZO_ZZZ_NKDataGrouping ON RefVesselZZ(ZZO_ZZZ_NKDataGrouping ASC)
GO
CREATE NONCLUSTERED INDEX IX_RefVesselZZ_ZZO_RadioCallSign_ZZO_ZZZ_NKDataGrouping ON RefVesselZZ(ZZO_RadioCallSign ASC, ZZO_ZZZ_NKDataGrouping ASC)
GO
