//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from EADPrintProcedureCodeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.ES.Business.Declaration
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class EADPrintProcedureCodeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string _0NoEADPrint = "0";
			public const string _1EADPrintedByCustomsAuthorities = "1";
			public const string _2EADCanBePrintedByDeclarant = "2";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString _0NoEADPrint { get { return ResString.GetMultilingualString("EADPrintProcedureCodeList|_0NoEADPrint", "[0] No EAD Print"); } }
			public static MultilingualString _1EADPrintedByCustomsAuthorities { get { return ResString.GetMultilingualString("EADPrintProcedureCodeList|_1EADPrintedByCustomsAuthorities", "[1] EAD printed by Customs authorities or through the Virtual Office"); } }
			public static MultilingualString _2EADCanBePrintedByDeclarant { get { return ResString.GetMultilingualString("EADPrintProcedureCodeList|_2EADCanBePrintedByDeclarant", "[2] EAD can be printed by declarant or through the Virtual Office"); } }
		}

		public EADPrintProcedureCodeList()
		{
			AddPair(Codes._0NoEADPrint, Descriptions._0NoEADPrint);
			AddPair(Codes._1EADPrintedByCustomsAuthorities, Descriptions._1EADPrintedByCustomsAuthorities);
			AddPair(Codes._2EADCanBePrintedByDeclarant, Descriptions._2EADCanBePrintedByDeclarant);
		}
	}
}
