<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.Staging.Schedulers.Common.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.Staging.Schedulers.Common.Test</AssemblyName>
    <OutputPath>..\..\..\Bin\Staging\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Common">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.Schema_New">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.Schema_New.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.SafeDataClient">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Common.SafeDataClient.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Staging.ProcessorRunner">
      <HintPath>..\..\..\Bin\Staging\net8.0\CargoWise.RefDbRepo.Staging.ProcessorRunner.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Schedulers.Common\Schedulers.Common.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
