<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.DataTransfer" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>