<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Compile Remove="Winzor\**" />
    <EmbeddedResource Remove="Winzor\**" />
    <None Remove="Winzor\**" />
    <Page Remove="Winzor\**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Xaml.Behaviors" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <ItemGroup>
    <AdditionalFiles Remove="Winzor\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="cargowise-main-navigation-webcompiler.config.json" />
  </ItemGroup>
</Project>