<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.GlobalCommercialInvoice.Integration.Test</RootNamespace>
    <AssemblyName>Enterprise.GlobalCommercialInvoice.Integration.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>