//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using CargoWise.Common;
using CargoWise.ComponentModel;
using CargoWise.EntityFramework;
using CargoWise.EntityFramework.Extensions;
using CargoWise.Schema;
using CargoWise.Types;
using Enterprise.ZArchitecture.Schema;

namespace Enterprise.Customs.CN.Business
{
	[System.CodeDom.Compiler.GeneratedCode("CargoWise.EntityFramework", "1.0")]
	public abstract class AutoCNJobComInvoiceLine : Customs.Business.BaseJobComInvoiceLine, Customs.Business.IAddInfoManagerWithSchema, IOriginalValueProvider, IConcurrencyExceptionDecorator, IAddInfoSchemaProvider
	{
		#region Schema

		public new class Schema : Customs.Business.BaseJobComInvoiceLine.Schema
		{
			public const string JI_CIQEndUse                 = "JI_CIQEndUse";
			public const string JI_CIQExpiryDate             = "JI_CIQExpiryDate";
			public const string JI_CIQOriginState            = "JI_CIQOriginState";
			public const string JI_CIQQualityGuaranteePeriod = "JI_CIQQualityGuaranteePeriod";
			public const string JI_CIQTariff                 = "JI_CIQTariff";
			public const string JI_DestinationDistrict       = "JI_DestinationDistrict";
			public const string JI_DestinationRegion         = "JI_DestinationRegion";
			public const string JI_DutyMode                  = "JI_DutyMode";
			public const string JI_NameOfGoods               = "JI_NameOfGoods";
			public const string JI_NameOfGoods2              = "JI_NameOfGoods2";
			public const string JI_NonDangerousChemicalFlag  = "JI_NonDangerousChemicalFlag";
			public const string JI_OrigContainerFlag         = "JI_OrigContainerFlag";
			public const string JI_OriginDistrict            = "JI_OriginDistrict";
			public const string JI_OriginRegion              = "JI_OriginRegion";
			public const string JI_PackageTypeOfUNDG         = "JI_PackageTypeOfUNDG";
			public const string JI_ProductManualNo           = "JI_ProductManualNo";
			public const string JI_ProductManualNo2          = "JI_ProductManualNo2";
			public const string JI_ProductVersion            = "JI_ProductVersion";
			public const string JI_TradeQuantity             = "JI_TradeQuantity";
			public const string JI_TradeUnitQty              = "JI_TradeUnitQty";

			public const int JI_CIQEndUseMaxLength = 2;
			public const int JI_CIQOriginStateMaxLength = 6;
			public const int JI_CIQTariffMaxLength = 13;
			public const int JI_DestinationDistrictMaxLength = 5;
			public const int JI_DestinationRegionMaxLength = 6;
			public const int JI_NameOfGoodsMaxLength = 50;
			public const int JI_NameOfGoods2MaxLength = 50;
			public const int JI_OriginDistrictMaxLength = 5;
			public const int JI_OriginRegionMaxLength = 6;
			public const int JI_PackageTypeOfUNDGMaxLength = 36;
			public const int JI_ProductVersionMaxLength = 32;
			public const int JI_TradeUnitQtyMaxLength = 3;
		}

		public ITableSchema AddInfoTableSchema => CNJobComInvoiceLineSchema.Instance;

		#endregion

		protected AutoCNJobComInvoiceLine(BusinessObjectFactory Factory, DataRow Row) : base(Factory, Row)
		{
			addInfo = new Enterprise.Customs.Business.AddInfoWrapper<AutoCNJobComInvoiceLine>(this
				, addInfoPropertyName: Schema.JI_AddInfo, getAddInfoNamesMapping: () => AddInfoNamesMapping
				, nAddInfoPropertyName: Schema.JI_NAddInfo, getNAddInfoNamesMapping: () => NAddInfoNamesMapping);
		}

		#region Base Behaviour Overrides

		public override void OnLoaded()
		{
			base.OnLoaded();
			AddInfoParser.Deserialise(JI_AddInfo, AddInfoNamesMapping, true);
			AddInfoParser.Deserialise(JI_NAddInfo, NAddInfoNamesMapping, true);
		}

		protected override void OnFactorySaving()
		{
			if (HasChangesNotIncludingChildren)
			{
				using (GetValidationSuspender())
				{
					addInfo.UpdateRelatedPropertyInfo();
				}
			}
			base.OnFactorySaving();
		}

		public override void OnSaved(bool saveSucceeded)
		{
			if (saveSucceeded)
			{
				AddInfoNamesMapping.Values.ForEach(x => x.OriginalValue = x.Value);
				NAddInfoNamesMapping.Values.ForEach(x => x.OriginalValue = x.Value);
			}
			base.OnSaved(saveSucceeded);
		}

		protected override void CopyAdditionalPersistentValuesFrom(BusinessObject sourceObject, BusinessObjectCloneArgs args)
		{
			base.CopyAdditionalPersistentValuesFrom(sourceObject, args);
			if (sourceObject is AutoCNJobComInvoiceLine source)
			{
				AddInfoParser.CopyAddInfoPropertyData(this, args, (AddInfoNamesMapping, source.AddInfoNamesMapping), (NAddInfoNamesMapping, source.NAddInfoNamesMapping));
			}
		}

		#endregion

		#region Mappings
		IDictionary<string, IAddInfoPropertyData> AddInfoNamesMapping
		{
			get
			{
				return addInfoNamesMapping ?? (addInfoNamesMapping = GetAddInfoNamesMapping());
			}
		}
		IDictionary<string, IAddInfoPropertyData> addInfoNamesMapping;

		protected virtual IDictionary<string, IAddInfoPropertyData> GetAddInfoNamesMapping() => new Dictionary<string, IAddInfoPropertyData>
		{
			{"CIQEndUse", JI_CIQEndUseData},
			{"CIQExpiryDate", JI_CIQExpiryDateData},
			{"CIQOriginState", JI_CIQOriginStateData},
			{"CIQQualityGuaranteePeriod", JI_CIQQualityGuaranteePeriodData},
			{"CIQTariff", JI_CIQTariffData},
			{"DestinationDistrict", JI_DestinationDistrictData},
			{"DestinationRegion", JI_DestinationRegionData},
			{"DutyMode", JI_DutyModeData},
			{"NonDangerousChemicalFlag", JI_NonDangerousChemicalFlagData},
			{"OrigContainerFlag", JI_OrigContainerFlagData},
			{"OriginDistrict", JI_OriginDistrictData},
			{"OriginRegion", JI_OriginRegionData},
			{"PackageTypeOfUNDG", JI_PackageTypeOfUNDGData},
			{"ProductManualNo", JI_ProductManualNoData},
			{"ProductManualNo2", JI_ProductManualNo2Data},
			{"ProductVersion", JI_ProductVersionData},
			{"TradeQuantity", JI_TradeQuantityData},
			{"TradeUnitQty", JI_TradeUnitQtyData},
		};

		IDictionary<string, IAddInfoPropertyData> NAddInfoNamesMapping
		{
			get
			{
				return nAddInfoNamesMapping ?? (nAddInfoNamesMapping = GetNAddInfoNamesMapping());
			}
		}
		IDictionary<string, IAddInfoPropertyData> nAddInfoNamesMapping;

		protected virtual IDictionary<string, IAddInfoPropertyData> GetNAddInfoNamesMapping() => new Dictionary<string, IAddInfoPropertyData>
		{
			{"NameOfGoods", JI_NameOfGoodsData},
			{"NameOfGoods2", JI_NameOfGoods2Data},
		};

		IDictionary<string, IAddInfoPropertyData> AddInfoPropertyNamesMapping
		{
			get
			{
				if (addInfoPropertyNamesMapping == null)
				{
					addInfoPropertyNamesMapping = new Dictionary<string, IAddInfoPropertyData>();
					AddInfoColumnMappings.Values.ForEach(x => x.ForEach(y => addInfoPropertyNamesMapping.Add(y.Key, y.Value)));
				}
				return addInfoPropertyNamesMapping;
			}
		}
		IDictionary<string, IAddInfoPropertyData> addInfoPropertyNamesMapping;

		IDictionary<string, IDictionary<string, IAddInfoPropertyData>> AddInfoColumnMappings
		{
			get
			{
				if (addInfoColumnMappings == null)
				{
					addInfoColumnMappings = new Dictionary<string, IDictionary<string, IAddInfoPropertyData>>();
					addInfoColumnMappings.Add(Schema.JI_AddInfo, AddInfoNamesMapping);
					addInfoColumnMappings.Add(Schema.JI_NAddInfo, NAddInfoNamesMapping);
				}
				return addInfoColumnMappings;
			}
		}
		IDictionary<string, IDictionary<string, IAddInfoPropertyData>> addInfoColumnMappings;

		public string GetAddInfoString() => AddInfoParser.Serialise(AddInfoNamesMapping);

		public string GetNAddInfoString() => AddInfoParser.Serialise(NAddInfoNamesMapping);

		#endregion

		#region Properties

		public virtual ZString JI_CIQEndUse
		{
			get => JI_CIQEndUseData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_CIQEndUseInfo, ref JI_CIQEndUseData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_CIQEndUse();
				}
			}
		}
		public ZPropertyInfo JI_CIQEndUseInfo => GetZPropertyInfo(Schema.JI_CIQEndUse);
		AddInfoPropertyData<ZString> JI_CIQEndUseData => cIQEndUseData ?? (cIQEndUseData = new AddInfoPropertyData<ZString>(Schema.JI_CIQEndUse));
		AddInfoPropertyData<ZString> cIQEndUseData;

		public virtual ZDateTime JI_CIQExpiryDate
		{
			get => JI_CIQExpiryDateData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_CIQExpiryDateInfo, ref JI_CIQExpiryDateData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_CIQExpiryDate();
				}
			}
		}
		public ZPropertyInfo JI_CIQExpiryDateInfo => GetZPropertyInfo(Schema.JI_CIQExpiryDate);
		AddInfoPropertyData<ZDateTime> JI_CIQExpiryDateData => cIQExpiryDateData ?? (cIQExpiryDateData = new AddInfoPropertyData<ZDateTime>(Schema.JI_CIQExpiryDate));
		AddInfoPropertyData<ZDateTime> cIQExpiryDateData;

		public virtual ZString JI_CIQOriginState
		{
			get => JI_CIQOriginStateData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_CIQOriginStateInfo, ref JI_CIQOriginStateData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_CIQOriginState();
				}
			}
		}
		public ZPropertyInfo JI_CIQOriginStateInfo => GetZPropertyInfo(Schema.JI_CIQOriginState);
		AddInfoPropertyData<ZString> JI_CIQOriginStateData => cIQOriginStateData ?? (cIQOriginStateData = new AddInfoPropertyData<ZString>(Schema.JI_CIQOriginState));
		AddInfoPropertyData<ZString> cIQOriginStateData;

		public virtual ZInt JI_CIQQualityGuaranteePeriod
		{
			get => JI_CIQQualityGuaranteePeriodData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_CIQQualityGuaranteePeriodInfo, ref JI_CIQQualityGuaranteePeriodData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_CIQQualityGuaranteePeriod();
				}
			}
		}
		public ZPropertyInfo JI_CIQQualityGuaranteePeriodInfo => GetZPropertyInfo(Schema.JI_CIQQualityGuaranteePeriod);
		AddInfoPropertyData<ZInt> JI_CIQQualityGuaranteePeriodData => cIQQualityGuaranteePeriodData ?? (cIQQualityGuaranteePeriodData = new AddInfoPropertyData<ZInt>(Schema.JI_CIQQualityGuaranteePeriod));
		AddInfoPropertyData<ZInt> cIQQualityGuaranteePeriodData;

		public virtual ZString JI_CIQTariff
		{
			get => JI_CIQTariffData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_CIQTariffInfo, ref JI_CIQTariffData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_CIQTariff();
				}
			}
		}
		public ZPropertyInfo JI_CIQTariffInfo => GetZPropertyInfo(Schema.JI_CIQTariff);
		AddInfoPropertyData<ZString> JI_CIQTariffData => cIQTariffData ?? (cIQTariffData = new AddInfoPropertyData<ZString>(Schema.JI_CIQTariff));
		AddInfoPropertyData<ZString> cIQTariffData;

		public virtual ZString JI_DestinationDistrict
		{
			get => JI_DestinationDistrictData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_DestinationDistrictInfo, ref JI_DestinationDistrictData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_DestinationDistrict();
				}
			}
		}
		public ZPropertyInfo JI_DestinationDistrictInfo => GetZPropertyInfo(Schema.JI_DestinationDistrict);
		AddInfoPropertyData<ZString> JI_DestinationDistrictData => destinationDistrictData ?? (destinationDistrictData = new AddInfoPropertyData<ZString>(Schema.JI_DestinationDistrict));
		AddInfoPropertyData<ZString> destinationDistrictData;

		public virtual ZString JI_DestinationRegion
		{
			get => JI_DestinationRegionData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_DestinationRegionInfo, ref JI_DestinationRegionData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_DestinationRegion();
				}
			}
		}
		public ZPropertyInfo JI_DestinationRegionInfo => GetZPropertyInfo(Schema.JI_DestinationRegion);
		AddInfoPropertyData<ZString> JI_DestinationRegionData => destinationRegionData ?? (destinationRegionData = new AddInfoPropertyData<ZString>(Schema.JI_DestinationRegion));
		AddInfoPropertyData<ZString> destinationRegionData;

		public virtual ZString JI_DutyMode
		{
			get => JI_DutyModeData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_DutyModeInfo, ref JI_DutyModeData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_DutyMode();
				}
			}
		}
		public ZPropertyInfo JI_DutyModeInfo => GetZPropertyInfo(Schema.JI_DutyMode);
		AddInfoPropertyData<ZString> JI_DutyModeData => dutyModeData ?? (dutyModeData = new AddInfoPropertyData<ZString>(Schema.JI_DutyMode));
		AddInfoPropertyData<ZString> dutyModeData;

		public virtual ZString JI_NameOfGoods
		{
			get => JI_NameOfGoodsData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_NameOfGoodsInfo, ref JI_NameOfGoodsData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_NameOfGoods();
				}
			}
		}
		public ZPropertyInfo JI_NameOfGoodsInfo => GetZPropertyInfo(Schema.JI_NameOfGoods);
		AddInfoPropertyData<ZString> JI_NameOfGoodsData => nameOfGoodsData ?? (nameOfGoodsData = new AddInfoPropertyData<ZString>(Schema.JI_NameOfGoods));
		AddInfoPropertyData<ZString> nameOfGoodsData;

		public virtual ZString JI_NameOfGoods2
		{
			get => JI_NameOfGoods2Data.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_NameOfGoods2Info, ref JI_NameOfGoods2Data.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_NameOfGoods2();
				}
			}
		}
		public ZPropertyInfo JI_NameOfGoods2Info => GetZPropertyInfo(Schema.JI_NameOfGoods2);
		AddInfoPropertyData<ZString> JI_NameOfGoods2Data => nameOfGoods2Data ?? (nameOfGoods2Data = new AddInfoPropertyData<ZString>(Schema.JI_NameOfGoods2));
		AddInfoPropertyData<ZString> nameOfGoods2Data;

		public virtual ZBool JI_NonDangerousChemicalFlag
		{
			get => JI_NonDangerousChemicalFlagData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_NonDangerousChemicalFlagInfo, ref JI_NonDangerousChemicalFlagData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_NonDangerousChemicalFlag();
				}
			}
		}
		public ZPropertyInfo JI_NonDangerousChemicalFlagInfo => GetZPropertyInfo(Schema.JI_NonDangerousChemicalFlag);
		AddInfoPropertyData<ZBool> JI_NonDangerousChemicalFlagData => nonDangerousChemicalFlagData ?? (nonDangerousChemicalFlagData = new AddInfoPropertyData<ZBool>(Schema.JI_NonDangerousChemicalFlag));
		AddInfoPropertyData<ZBool> nonDangerousChemicalFlagData;

		public virtual ZString JI_OrigContainerFlag
		{
			get => JI_OrigContainerFlagData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_OrigContainerFlagInfo, ref JI_OrigContainerFlagData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_OrigContainerFlag();
				}
			}
		}
		public ZPropertyInfo JI_OrigContainerFlagInfo => GetZPropertyInfo(Schema.JI_OrigContainerFlag);
		AddInfoPropertyData<ZString> JI_OrigContainerFlagData => origContainerFlagData ?? (origContainerFlagData = new AddInfoPropertyData<ZString>(Schema.JI_OrigContainerFlag));
		AddInfoPropertyData<ZString> origContainerFlagData;

		public virtual ZString JI_OriginDistrict
		{
			get => JI_OriginDistrictData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_OriginDistrictInfo, ref JI_OriginDistrictData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_OriginDistrict();
				}
			}
		}
		public ZPropertyInfo JI_OriginDistrictInfo => GetZPropertyInfo(Schema.JI_OriginDistrict);
		AddInfoPropertyData<ZString> JI_OriginDistrictData => originDistrictData ?? (originDistrictData = new AddInfoPropertyData<ZString>(Schema.JI_OriginDistrict));
		AddInfoPropertyData<ZString> originDistrictData;

		public virtual ZString JI_OriginRegion
		{
			get => JI_OriginRegionData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_OriginRegionInfo, ref JI_OriginRegionData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_OriginRegion();
				}
			}
		}
		public ZPropertyInfo JI_OriginRegionInfo => GetZPropertyInfo(Schema.JI_OriginRegion);
		AddInfoPropertyData<ZString> JI_OriginRegionData => originRegionData ?? (originRegionData = new AddInfoPropertyData<ZString>(Schema.JI_OriginRegion));
		AddInfoPropertyData<ZString> originRegionData;

		public virtual ZString JI_PackageTypeOfUNDG
		{
			get => JI_PackageTypeOfUNDGData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_PackageTypeOfUNDGInfo, ref JI_PackageTypeOfUNDGData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_PackageTypeOfUNDG();
				}
			}
		}
		public ZPropertyInfo JI_PackageTypeOfUNDGInfo => GetZPropertyInfo(Schema.JI_PackageTypeOfUNDG);
		AddInfoPropertyData<ZString> JI_PackageTypeOfUNDGData => packageTypeOfUNDGData ?? (packageTypeOfUNDGData = new AddInfoPropertyData<ZString>(Schema.JI_PackageTypeOfUNDG));
		AddInfoPropertyData<ZString> packageTypeOfUNDGData;

		public virtual ZInt JI_ProductManualNo
		{
			get => JI_ProductManualNoData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_ProductManualNoInfo, ref JI_ProductManualNoData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_ProductManualNo();
				}
			}
		}
		public ZPropertyInfo JI_ProductManualNoInfo => GetZPropertyInfo(Schema.JI_ProductManualNo);
		AddInfoPropertyData<ZInt> JI_ProductManualNoData => productManualNoData ?? (productManualNoData = new AddInfoPropertyData<ZInt>(Schema.JI_ProductManualNo));
		AddInfoPropertyData<ZInt> productManualNoData;

		public virtual ZInt JI_ProductManualNo2
		{
			get => JI_ProductManualNo2Data.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_ProductManualNo2Info, ref JI_ProductManualNo2Data.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_ProductManualNo2();
				}
			}
		}
		public ZPropertyInfo JI_ProductManualNo2Info => GetZPropertyInfo(Schema.JI_ProductManualNo2);
		AddInfoPropertyData<ZInt> JI_ProductManualNo2Data => productManualNo2Data ?? (productManualNo2Data = new AddInfoPropertyData<ZInt>(Schema.JI_ProductManualNo2));
		AddInfoPropertyData<ZInt> productManualNo2Data;

		public virtual ZString JI_ProductVersion
		{
			get => JI_ProductVersionData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_ProductVersionInfo, ref JI_ProductVersionData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_ProductVersion();
				}
			}
		}
		public ZPropertyInfo JI_ProductVersionInfo => GetZPropertyInfo(Schema.JI_ProductVersion);
		AddInfoPropertyData<ZString> JI_ProductVersionData => productVersionData ?? (productVersionData = new AddInfoPropertyData<ZString>(Schema.JI_ProductVersion));
		AddInfoPropertyData<ZString> productVersionData;

		public virtual ZDecimal JI_TradeQuantity
		{
			get => JI_TradeQuantityData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_TradeQuantityInfo, ref JI_TradeQuantityData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_TradeQuantity();
				}
			}
		}
		public ZPropertyInfo JI_TradeQuantityInfo => GetZPropertyInfo(Schema.JI_TradeQuantity);
		AddInfoPropertyData<ZDecimal> JI_TradeQuantityData => tradeQuantityData ?? (tradeQuantityData = new AddInfoPropertyData<ZDecimal>(Schema.JI_TradeQuantity));
		AddInfoPropertyData<ZDecimal> tradeQuantityData;

		public virtual ZString JI_TradeUnitQty
		{
			get => JI_TradeUnitQtyData.Value;
			set
			{
				SetNonPersistentPropertyValue(JI_TradeUnitQtyInfo, ref JI_TradeUnitQtyData.Value, value);
				if (!IsValidationSuspended)
				{
					Validation.ValidateJI_TradeUnitQty();
				}
			}
		}
		public ZPropertyInfo JI_TradeUnitQtyInfo => GetZPropertyInfo(Schema.JI_TradeUnitQty);
		AddInfoPropertyData<ZString> JI_TradeUnitQtyData => tradeUnitQtyData ?? (tradeUnitQtyData = new AddInfoPropertyData<ZString>(Schema.JI_TradeUnitQty));
		AddInfoPropertyData<ZString> tradeUnitQtyData;

		#endregion

		#region Original Value

		public IZType GetOriginalValue(ZPropertyInfo info)
		{
			return AddInfoPropertyNamesMapping.TryGetValue(info.Name.Substring(info.BizObj.TablePrefix.Length + 1), out var addInfoPropertyData)
				? addInfoPropertyData.OriginalValue
				: info.Value;
		}

		#endregion

		#region Validation

		public new AutoCNJobComInvoiceLineValidation Validation => (AutoCNJobComInvoiceLineValidation)base.Validation;

		#endregion

		#region IAddInfoManagerWithSchema Members

		Enterprise.Customs.Business.IAddInfo Enterprise.Customs.Business.IAddInfoManager.AddInfo => addInfo;
		readonly Enterprise.Customs.Business.IAddInfo addInfo;

		ITableSchema Enterprise.Customs.Business.IAddInfoManagerWithSchema.AddInfoSchema => CNJobComInvoiceLineSchema.Instance;

		#endregion

		#region Concurrency Handling

		protected override void OnConcurrencyExceptionCore(IEnumerable<IPropertyRecord> propertyRecords)
		{
			base.OnConcurrencyExceptionCore(propertyRecords);
			AddInfoParser.HandleConcurrencyException(propertyRecords, GetZPropertyInfo, AddInfoColumnMappings);
		}

		protected override void OnConcurrencyExceptionAfterMergeCore(IEnumerable<IPropertyRecord> propertyRecords)
		{
			AddInfoColumnMappings.ForEach(x => AddInfoParser.Deserialise((ZString)this[x.Key], x.Value, true));
			base.OnConcurrencyExceptionAfterMergeCore(propertyRecords);
		}

		public void AppendDecoratedDisplayName(StringBuilder stringBuilder, IPropertyRecord record)
		{
			AddInfoParser.AppendDecoratedDisplayName(stringBuilder, record, GetZPropertyInfo, AddInfoColumnMappings);
		}

		#endregion
	}
}
