<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Builder.Generator.Test</RootNamespace>
    <CodeAnalysisRuleAssemblies>\rules</CodeAnalysisRuleAssemblies>
    <CodeAnalysisIgnoreBuiltInRuleSets>false</CodeAnalysisIgnoreBuiltInRuleSets>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <None Remove="DatabaseObjectGenerator\TestFiles\ZZDummyBizo\ZZDummyBizo.model.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="DatabaseObjectGenerator\TestFiles\ZZDummyBizo\ZZDummyBizo.model.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BuildTools" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DataProtection.Administration.SqlServer" />
    <Reference Include="CargoWise.DataProtection.SqlExtensions" />
    <Reference Include="CargoWise.DbUpgrader.Scripts.Abstractions" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DbUpgrader.Data.Documents" />
    <Reference Include="Enterprise.DbUpgrader.Data.Shared" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Microsoft.Bcl.AsyncInterfaces" />
    <Reference Include="Microsoft.Extensions.DependencyInjection" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <Reference Include="NUnitCore" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <Reference Include="System.Windows.Forms.Primitives" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Generator\Generator.csproj" />
  </ItemGroup>
</Project>