<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <DefineConstants Condition="'$(CanNetCoreLibBeReferencedFromWinzor)' == 'true'">$(DefineConstants);USE_NET_CORE_LIBS_IN_WINZOR</DefineConstants>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.DAT.json" />
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.IntegrationTest.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.DAT.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.IntegrationTest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Blazor.Common.Data\CargoWise.Blazor.Common.Data.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.Common\CargoWise.Blazor.Common.csproj" />
    <ProjectReference Include="..\CargoWise.Blazor.Testing.Common\CargoWise.Blazor.Testing.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Data.Providers.Common" />
    <Reference Include="CargoWise.Data.Providers.Common.Test" />
    <Reference Include="System.Windows.Forms">
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
</Project>