<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.CustomerService.GUI\Enterprise.CustomerService.GUI.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>