<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>WinzorFramework.Samples</AssemblyName>
    <RootNamespace>WinzorFramework.Samples</RootNamespace>
    <DisableResourceStringsAnalyzer>true</DisableResourceStringsAnalyzer>
    <CWEnableReferenceStatusSafeGuard>false</CWEnableReferenceStatusSafeGuard>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj\**" />
    <Content Remove="obj\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BArchitecture.GUI\WinzorFramework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Blazor.Client.Integration" />
    <Reference Include="CargoWise.Blazor.Client.Integration.Server" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <Target Name="CopyJs" BeforeTargets="Build">
    <Copy SourceFiles="$(OutputPath)wwwroot\client.js" DestinationFolder="wwwroot" />
  </Target>
</Project>