<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.NO.Module.Test</RootNamespace>
    <AssemblyName>Enterprise.Customs.NO.Module.Test</AssemblyName>
    <OutputPath>$(WTGBinRoot)</OutputPath>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.NO.GUI.csproj" />
    <ProjectReference Include="..\Module\Enterprise.Customs.NO.Module.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>