<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.MasterFiles.Business.SpecTesting.Regenerate</RootNamespace>
    <AssemblyName>MasterFiles.Business.SpecTesting.Regenerate</AssemblyName>
    <OutputType>Exe</OutputType>
    <Configurations>Debug;DEBUGFAST</Configurations>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Initialisation" />
    <Reference Include="CargoWise.Main" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="WTG.TestHelpers.SpecTesting" />
    <Reference Include="Newtonsoft.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MasterFiles.Business.SpecTesting\MasterFiles.Business.SpecTesting.csproj" />
    <ProjectReference Include="..\MasterFiles.Business\MasterFiles.Business.csproj" />
  </ItemGroup>
</Project>