<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Warehouse.Transit.DataTransfer.Universal.Testing</RootNamespace>
    <AssemblyName>Enterprise.Warehouse.Transit.DataTransfer.Universal.Testing</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.IO" />
    <Reference Include="CargoWise.Macros" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.AU.Declaration.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.Universal.Test" />
    <Reference Include="Enterprise.DataTransfer" />
    <Reference Include="Enterprise.DeniedPartyScreening.Common" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentVisualizer.Business" />
    <Reference Include="Enterprise.DocumentVisualizer.Core" />
    <Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
    <Reference Include="Enterprise.DocumentVisualizer.Integration" />
    <Reference Include="Enterprise.DocumentVisualizer.Testing" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Test" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.LogWalker" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer" />
    <Reference Include="Enterprise.MasterFiles.DataTransfer.Testing" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Business" />
    <Reference Include="Enterprise.Packing.Business.Test" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TransportBookings.Business.Test" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.UniversalDataBuss.Testing" />
    <Reference Include="Enterprise.Warehouse.Environment.Business" />
    <Reference Include="Enterprise.Warehouse.Environment.Business.Test" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Schema" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Resources.Shared" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransitWarehouse.Business.Testing\TransitWarehouse.Business.Testing.csproj" />
    <ProjectReference Include="..\TransitWarehouse.Business\TransitWarehouse.Business.csproj" />
    <ProjectReference Include="..\TransitWarehouse.DataTransfer\TransitWarehouse.DataTransfer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Universal\TestFiles\*.xml" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>
