// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Reference", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Testing")]
[assembly: SuppressMessage("Reference", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Testing")]
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.DirectoryDataTypeTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/DirectoryRegistryDataType.cs:44,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.UnmatchedOrganisationTest.DoAdditionalPreparations")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateUNMATCHEDOrgScripts.cs:124,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.AssertGetAuditColumnValue(System.Guid,System.Guid,System.DateTime,System.DateTime)")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:949,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestSetBinaryValueWithAuditDetails")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:927,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestSetBinaryValueWithEmptyGuid")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:859,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestSetBinaryValueWithEmptyGuid")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:869,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestSetBinaryValueWithEmptyGuid")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:886,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestGetBinaryExceptionHandlerThrowsExceptionWhenTimeoutExpired")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1036,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestGetBinaryExceptionHandlerGetsTheRegistryManuallyIfNoStoredProcedure")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1045,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.AssertHasValue(System.Guid,System.Guid,System.Boolean)")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1121,30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestClearValueDoesNotDeleteRecord")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1137,30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestClearValueDoesNotDeleteRecord")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1145,31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.BaseRegistryItemTest.TestClearValueDoesNotDeleteRecord")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:1151,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UriRegistryDataTypeWithAutoPrefixingTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/UriRegistryDataType.cs:129,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UriRegistryDataTypeWithoutAutoPrefixingTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/UriRegistryDataType.cs:156,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UriRegistryDataTypeWithoutQueryStringTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/UriRegistryDataType.cs:181,96
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.EmailDef.EmailDefTest.TestGetGlbGroupAllPK")] // Enterprise/Architecture/Core/Core/Environment/Email/EmailDef.cs:944,31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.EmailDef.EmailDefTest.TestGetGlbGroupAllPK")] // Enterprise/Architecture/Core/Core/Environment/Email/EmailDef.cs:950,31
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.EmailDef.EmailDefTest.TestGetGlbGroupAllPK")] // Enterprise/Architecture/Core/Core/Environment/Email/EmailDef.cs:957,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.LocalDirectoryRegistryDataTypeTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/LocalPathRegistryDataType.cs:43,56
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.LocalDirectoryRegistryDataTypeTest.GetValidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/LocalPathRegistryDataType.cs:51,38
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.LocalDirectoryRegistryDataTypeTest.GetValidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/LocalPathRegistryDataType.cs:51,72
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.LocalDirectoryRegistryDataTypeTest.GetValidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/LocalPathRegistryDataType.cs:52,38
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.LocalDirectoryRegistryDataTypeTest.GetValidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/LocalPathRegistryDataType.cs:52,72
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TransactionStatusListener.EndTest(NUnit.Framework.TestCase,System.DateTime)")] // Enterprise/Architecture/Core/Core/Testing/TransactionStatusListener.cs:18,5
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ExceptionFullTracerTest.TestStripLineNoAndFilename")] // Enterprise/Architecture/Core/Core/ErrorReporting/ExceptionFullTracer.cs:252,76
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ExceptionFullTracerTest.TestStripLineNoAndFilename")] // Enterprise/Architecture/Core/Core/ErrorReporting/ExceptionFullTracer.cs:253,68
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.TestGetUserNameAndTimeOfLastEditOrDeleteOfARecordForWrongDateCast")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:354,28
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.TestGetUserNameAndTimeOfLastEditOrDeleteOfARecordFromRow")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:389,28
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.TestGetUserNameAndTimeOfLastEditOrDeleteOfARecordFromRow")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:402,27
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.TestGetUserNameAndTimeOfLastEditOrDeleteOfARecordFromDeletedRow")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:448,28
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.GetAuditLogRowCount(System.String)")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:498,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.IsEventLogged(System.String,System.Guid,System.DateTime,System.String)")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:512,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EventManagerTest.GetBranchAndDepartmentFromLastEvent(System.String,System.Guid,System.String@,System.String@)")] // Enterprise/Architecture/Core/Core/Utilities/Events/EventManager.cs:534,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.RunInExtraTransactionAttribute.SetUp(NUnit.Framework.TestCase)")] // Enterprise/Architecture/Core/Core/Testing/RunInExtraTransactionAttribute.cs:11,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.RunInExtraTransactionAttribute.TearDown(NUnit.Framework.TestCase)")] // Enterprise/Architecture/Core/Core/Testing/RunInExtraTransactionAttribute.cs:16,3
[assembly: SuppressMessage("CargoWiseOne", "CW1071:Do Not Use GC.WaitForPendingFinalizers or .GetTotalMemory(true)", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.UntransactionedTest.TestUnobservedTaskExceptionsAreReportedSilently")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:725,6
[assembly: SuppressMessage("CargoWiseOne", "CW1071:Do Not Use GC.WaitForPendingFinalizers or .GetTotalMemory(true)", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestUnobservedTaskExceptionsAreHandled")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2343,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.UntransactionedTest.TestReportStillCreatedIfExceptionReportedInRolledBackTransaction")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:644,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.UntransactionedTest.TestReportStillCreatedIfExceptionReportedInRolledBackTransaction")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:652,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.UntransactionedTest.GetNumStmErrorReports")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:659,21
[assembly: SuppressMessage("CargoWiseOne", "CW1056:Do Not Use GC.Collect()", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.UntransactionedTest.TestUnobservedTaskExceptionsAreReportedSilently")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:724,6
[assembly: SuppressMessage("CargoWiseOne", "CW1056:Do Not Use GC.Collect()", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestUnobservedTaskExceptionsAreHandled")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2342,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.GetNumErrorReports")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2563,21
[assembly: SuppressMessage("CargoWiseOne", "CW1079:Do not compare on Exception.Message", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestUnobservedTaskExceptionsAreHandled")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2348,88
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleAppManagerNotRunningException_FromUnhandledException")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1205,124
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleAppManagerNotRunningException_FromUnhandledException")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1206,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleAppManagerNotRunningException_FromUnhandledException")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1207,215
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleAppManagerNotRunningException_FromUnhandledException")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1208,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleCannotLoadFileOrAssembly")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1182,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestFileLoadExceptionShowingMessageIfUserInteractive")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:1054,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestCorruptedInstallationExceptionHandling")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2215,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestCorruptedInstallationExceptionHandling")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2226,17
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.BaseExceptionReporter.Test.TestHandleUseVfpOleDbProviderIn64BitPlatformException")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:2509,17
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ExceptionQueuerTest.Internal_TestQueueExceptionEmailForLaterSending(System.String,System.String)")] // Enterprise/Architecture/Core/Core/ErrorReporting/ExceptionQueuer.cs:124,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ExceptionQueuerTest.Internal_TestQueueExceptionEmailForLaterSending(System.String,System.String)")] // Enterprise/Architecture/Core/Core/ErrorReporting/ExceptionQueuer.cs:132,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.FtpUriRegistryDataTypeTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/FtpUriRegistryDataType.cs:49,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Core.Environment.Semaphores.Testing.EnterpriseHeartbeatInfoFactoryTest.GetMainConnectionHostProcessId")] // Enterprise/Architecture/Core/Core/Environment/Environment/Semaphores/EnterpriseHeartbeatInfoFactory.cs:78,19
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.UtcDateTimeCacheTest.TestRefreshDateTimeDatabaseUpgradeExceptionsCaught")] // Enterprise/Architecture/Core/Core/Environment/TimeZone/UtcDateTimeCache.cs:364,70
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.UtcDateTimeCacheTest.TestHandlingDbInUse")] // Enterprise/Architecture/Core/Core/Environment/TimeZone/UtcDateTimeCache.cs:438,28
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.AccountingPeriodManagerTest.TestGetPeriod")] // Enterprise/Architecture/Core/Core/Environment/Environment/AccountingPeriodManager.cs:48,30
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ClientOverrideInitUninitTestListenerTest.TestResetSecurityAfterDisposeTemporaryUserContextForClientExtension")] // Enterprise/Architecture/Core/Core/Testing/ClientOverrideInitUninitTestListener.cs:121,28
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ClientOverrideInitUninitTestListenerTest.TestNotResetSecurityAfterDisposeTemporaryUserContext")] // Enterprise/Architecture/Core/Core/Testing/ClientOverrideInitUninitTestListener.cs:136,26
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ClientOverrideInitUninitTestListenerTest.TestResetSecurityAfterDisposeTemporaryUserContextForClientExtension")] // Enterprise/Architecture/Core/Core/Testing/ClientOverrideInitUninitTestListener.cs:125,26
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ClientOverrideInitUninitTestListenerTest.TestNotResetSecurityAfterDisposeTemporaryUserContext")] // Enterprise/Architecture/Core/Core/Testing/ClientOverrideInitUninitTestListener.cs:140,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.TestTransactionAlreadyOpen")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:98,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.TestTransactionAlreadyOpen")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:113,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.MockLeavesDBTransactionOpenTest.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:262,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTest.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:187,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTest.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:189,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTest.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:199,6
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTestForWebEnvironment.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:220,26
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTestForWebEnvironment.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:222,6
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:NUnit.Framework.TestCaseHelper.MetaTestCaseForTransactionedTestCase.CreatesCommandOutsideTransactionAndRunsCommandInsideTransactionTestForWebEnvironment.TestMock")] // Enterprise/Architecture/Core/Core/Testing/TestCaseHelper.cs:232,7
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Core.Environment.Testing.UserTest.TestGetGlowActiveUserSessions")] // Enterprise/Architecture/Core/Core/Environment/Environment/ActiveUser/ActiveUserQuery.cs:318,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Core.Environment.Testing.UserTest.TestGetGlowActiveUserSessions")] // Enterprise/Architecture/Core/Core/Environment/Environment/ActiveUser/ActiveUserQuery.cs:333,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.CodeDescriptionPairListTest.TestFilterReferenceTypesMatchTypesOfRefDocTypesInDb")] // Enterprise/Architecture/Core/Core/CodeDescriptionPair/CodeDescriptionPairList.cs:3910,20
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.NativeXMLSupportTillDateDataTypeTest.GetInvalidSamples")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/NativeXMLSupportTillDateDataType.cs:44,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.RawDataRegistryTest.TestPasswordControl")] // Enterprise/Architecture/Core/Core/Environment/Registry/RawDataRegistry.cs:15124,19
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.SafeEventLogExtensionsTest.TestSafeWriteEntry_NoSource")] // Enterprise/Architecture/Core/Core/Environment/Notifications/SafeEventLogExtensions.cs:316,16
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.SafeEventLogExtensionsTest.TestSafeWriteEntry_NoSource")] // Enterprise/Architecture/Core/Core/Environment/Notifications/SafeEventLogExtensions.cs:316,84
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestClearCacheWorksForFilterCriteria")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:5498,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestClearCacheWorksForFilterCriteria")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:5499,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestEnterpriseCDDateThrowsNoException")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:6268,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestDMImportConfigurationSettingsStruct")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:6683,35
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestGetDMImportConfigurationSettingsStruct")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:6700,38
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestGetDMImportConfigurationSettingsStruct")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:6704,82
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.DataRegistryTest.TestDMImportConfigurationSettingsStructDefaultValues")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataRegistry.cs:6720,16
[assembly: SuppressMessage("CargoWiseOne", "CW1079:Do not compare on Exception.Message", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Startup.Testing.BackgroundApplicationStartupTaskTest.TestErrorsAreReported")] // Enterprise/Architecture/Core/Core/Utilities/IApplicationStartupTask.cs:247,87
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.CommandLineArgEncoderTest.TestEnquoteArgumentIfNeeded")] // Enterprise/Architecture/Core/Core/Utilities/CommandLineArgEncoder.cs:82,16
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.CommandLineArgEncoderTest.TestEnquoteArgumentIfNeeded")] // Enterprise/Architecture/Core/Core/Utilities/CommandLineArgEncoder.cs:82,76
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.CommandLineArgEncoderTest.TestEnquoteArgumentIfNeeded")] // Enterprise/Architecture/Core/Core/Utilities/CommandLineArgEncoder.cs:84,16
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.CommandLineArgEncoderTest.TestEnquoteArgumentIfNeeded")] // Enterprise/Architecture/Core/Core/Utilities/CommandLineArgEncoder.cs:84,83
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UnattendedUserNotificationTest.SetupAdminStaffEmailAddress")] // Enterprise/Architecture/Core/Core/Environment/Notifications/UnattendedUserNotification.cs:846,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UnattendedUserNotificationTest.SetupAllStaffEmailAddress")] // Enterprise/Architecture/Core/Core/Environment/Notifications/UnattendedUserNotification.cs:859,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UnattendedUserNotificationTest.ClearStmErrorReports")] // Enterprise/Architecture/Core/Core/Environment/Notifications/UnattendedUserNotification.cs:880,20
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.UnattendedUserNotificationTest.TestShowErrorMessageContainsSoftwareVersion")] // Enterprise/Architecture/Core/Core/Environment/Notifications/UnattendedUserNotification.cs:673,53
[assembly: SuppressMessage("CargoWiseOne", "CW1078:Do not use Process.Start to open a file or url, use WebUrlLauncher or FileOpener for proper integration with Remote Desktop Services. False alarm if you are running a process for a reason other than to open a file or url.", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TestTemporaryDirectory.StartProcmon")] // Enterprise/Architecture/Core/Core/Testing/TestTemporaryDirectory.cs:62,3
[assembly: SuppressMessage("CargoWiseOne", "CW1078:Do not use Process.Start to open a file or url, use WebUrlLauncher or FileOpener for proper integration with Remote Desktop Services. False alarm if you are running a process for a reason other than to open a file or url.", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TestTemporaryDirectory.StartProcmon")] // Enterprise/Architecture/Core/Core/Testing/TestTemporaryDirectory.cs:64,24
[assembly: SuppressMessage("CargoWiseOne", "CW1078:Do not use Process.Start to open a file or url, use WebUrlLauncher or FileOpener for proper integration with Remote Desktop Services. False alarm if you are running a process for a reason other than to open a file or url.", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TestTemporaryDirectory.StartProcmon")] // Enterprise/Architecture/Core/Core/Testing/TestTemporaryDirectory.cs:65,27
[assembly: SuppressMessage("CargoWiseOne", "CW1078:Do not use Process.Start to open a file or url, use WebUrlLauncher or FileOpener for proper integration with Remote Desktop Services. False alarm if you are running a process for a reason other than to open a file or url.", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TestTemporaryDirectory.StopProcmon")] // Enterprise/Architecture/Core/Core/Testing/TestTemporaryDirectory.cs:77,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:218,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:219,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:220,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:221,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:222,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.CreateSystemOrgScriptsTest.PrepareTestData")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/CreateSystemOrgScripts.cs:223,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.FountainTestListener.GetLossyFountainNamesToReset")] // Enterprise/Architecture/Core/Core/Testing/FountainTestListener.cs:145,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.FountainTestListener.ReadExistingFountains")] // Enterprise/Architecture/Core/Core/Testing/FountainTestListener.cs:103,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.FountainTestListener.DeleteFountains(System.Collections.Generic.IReadOnlyCollection{System.Int32},System.Collections.Generic.IReadOnlyCollection{Enterprise.ZArchitecture.Core.Testing.FountainTestListener.FountainPair})")] // Enterprise/Architecture/Core/Core/Testing/FountainTestListener.cs:94,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.FountainTestListener.FountainTestListenerTest.TestFountainsExistance(System.String,System.Collections.Generic.IReadOnlyList{System.Int32})")] // Enterprise/Architecture/Core/Core/Testing/FountainTestListener.cs:362,22
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.FountainTestListener.FountainTestListenerTest.CreateFountains(System.String)")] // Enterprise/Architecture/Core/Core/Testing/FountainTestListener.cs:431,22
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.NumberFountainProxyTest.TestGenerateCacheDoesNotCommitTransaction")] // Enterprise/Architecture/Core/Core/Environment/NumberFountainProxy/NumberFountainProxy.cs:163,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.NumberFountainProxyTest.TestGenerateCacheDoesNotCommitTransaction")] // Enterprise/Architecture/Core/Core/Environment/NumberFountainProxy/NumberFountainProxy.cs:171,6
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.Testing.NumberFountainProxyTest.TestGenerateCacheDoesNotCommitTransaction")] // Enterprise/Architecture/Core/Core/Environment/NumberFountainProxy/NumberFountainProxy.cs:178,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.OverrideLevels.Testing.OverrideLevelTestCase`1.TestGetPkOfEntry")] // Enterprise/Architecture/Core/Core/Environment/Registry/OverrideLevels/IOverrideLevel.cs:213,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.TimeZoneInfoTest.TestIsDaylightSavingWithDataReaderOpen_ShouldTryOnNewConnection")] // Enterprise/Architecture/Core/Core/Environment/TimeZone/TimeZoneInfo.cs:474,24
[assembly: SuppressMessage("CargoWiseOne", "CW1079:Do not compare on Exception.Message", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.ExceptionExtenderTest.TestCheckAllInnerExceptions")] // Enterprise/Architecture/Core/Core/ErrorReporting/ExceptionExtenderTest.cs:89,78
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.TopLevelExceptionHandlerTests.TestConnectionClosedException")] // Enterprise/Architecture/Core/Core/ErrorReporting/TopLevelExceptionHandler.cs:2385,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.Testing.CurrentUserChangerTest.TestChangingUsers_WithBranchAndDepartment")] // Enterprise/Architecture/Core/Core/Testing/CurrentUserChanger.cs:55,36
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.Testing.Testing.CurrentUserChangerTest.TestChangingUsers_WithBranchAndDepartment")] // Enterprise/Architecture/Core/Core/Testing/CurrentUserChanger.cs:60,40
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.TimeZoneConstants.AbbreviatedMonths")] // Enterprise/Architecture/Core/Core/Environment/TimeZone/TimeZoneConstants.cs:22,34
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.CommittedDbUpdatesListener.Instance")] // Enterprise/Architecture/Core/Core/Testing/CommittedDbUpdatesListener.cs:13,52
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.SecurityAccessDeniedException.fMessage")] // Enterprise/Architecture/Core/Core/ErrorReporting/Exceptions/SecurityAccessDeniedException.cs:25,16
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.SendEmail.fInstance")] // Enterprise/Architecture/Core/Core/Environment/Email/ISendEmail.cs:16,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.OrgPatternLanguageSetting.factoryInstance")] // Enterprise/Architecture/Core/Core/Utilities/OrgPatternMatch/OrgPatternLanguageSetting.cs:8,43
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemDictionary.instance")] // Enterprise/Architecture/Core/Core/Environment/Registry/Internal/RegistryItemDictionary.cs:120,32
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.SourceControlInstanceTestListener.Instance")] // Enterprise/Architecture/Core/Core/Testing/SourceControlInstanceTestListener.cs:9,59
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.EnvProxy.env")] // Enterprise/Architecture/Core/Core/Environment/Environment/Base/EnvProxy.cs:26,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.ExceptionReporterTestListener.fInstance")] // Enterprise/Architecture/Core/Core/Testing/ExceptionReporterTestListener.cs:163,49
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.NotificationTestListener.fInstance")] // Enterprise/Architecture/Core/Core/Testing/NotificationTestListener.cs:24,34
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.SafeEventLogExtensions.useTestEmail")] // Enterprise/Architecture/Core/Core/Environment/Notifications/SafeEventLogExtensions.cs:132,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Wow.is64BitOS")] // Enterprise/Architecture/Core/Core/Utilities/Wow.cs:42,15
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.ClientOverrideInitUninitTestListener.fInstance")] // Enterprise/Architecture/Core/Core/Testing/ClientOverrideInitUninitTestListener.cs:31,46
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryRefresh.refreshFrequency")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryRefresh.cs:29,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryRefresh.reGetValueTime")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryRefresh.cs:28,18
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.BuildXmlInstanceTestListener.Instance")] // Enterprise/Architecture/Core/Core/Testing/BuildXmlInstanceTestListener.cs:9,54
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryConstants.Packing.NonAutoPrintingDataContexts")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryConstants.cs:13,50
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.WebTrackerCustomImage.SupportedFileTypes")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/WebCustomImagesRegistryDataType.cs:45,34
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.TransactionStatusListener.Instance")] // Enterprise/Architecture/Core/Core/Testing/TransactionStatusListener.cs:8,51
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.Testing.RegistryItemFallBackValueAccessorTest.UniqueNameIndex")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemFallBackValueAccessor/RegistryItemFallBackValueAccessor.cs:710,13
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DesignerSafeObjectFactory.isConfigured")] // Enterprise/Architecture/Core/Core/DesignerSafeObjectFactory.cs:53,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.Globals.fIsDBUpgSkipped")] // Enterprise/Architecture/Core/Core/Environment/Notifications/Globals.cs:328,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.Testing.TempFilesTestListener.Instance")] // Enterprise/Architecture/Core/Core/Testing/TempFilesTestListener.cs:13,47
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.BaseExceptionReporter.ContactNominatedCallerMessage")] // Enterprise/Architecture/Core/Core/ErrorReporting/BaseExceptionReporter.cs:211,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.BinaryRegistryDataType.MagicNullBytes")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/BinaryRegistryDataType.cs:62,25
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.ReleaseInfo.instance")] // Enterprise/Architecture/Core/Core/Utilities/Versioning/ReleaseInfo.cs:175,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DateTimeFormatStrings.throwExceptionOnUnknownDateFormatString")] // Enterprise/Architecture/Core/Core/Environment/TimeZone/DateTimeFormatStrings.cs:106,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryDataAccessor.disabled")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryDataAccessor.cs:668,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.User.factory")] // Enterprise/Architecture/Core/Core/Environment/Environment/User.cs:108,31
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.User.WebTransientPassword")] // Enterprise/Architecture/Core/Core/Environment/Environment/User.cs:87,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.OFont.hasReported")] // Enterprise/Architecture/Core/Core/UI/OFont.cs:158,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.lastReportedMessage")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:311,25
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.lastReportedKey")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:310,22
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.releaseTimeSpan")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:300,18
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.lastReportedOccurrences")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:312,40
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.eventReportedWithinASession")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:309,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.reportFirst")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:301,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.accumulateTimeSpan")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:299,18
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.reporter")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:297,37
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.threshold")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:303,13
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.DigestReporterTest.timeProvider")] // Enterprise/Architecture/Core/Core/DigestNotification/DigestReporterTest.cs:296,26
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.china")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:76,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.germany")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:97,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.hongKong")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:103,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.unitedKingdomg")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:109,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.unitedArabEmirates")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:44,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.malaysia")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:115,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.newZealand")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:121,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.india")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:133,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.iceLand")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:127,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.singapore")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:139,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.southAfrica")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:145,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.switzerland")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:151,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.ireland")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:157,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.netherlands")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:163,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.belgium")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:169,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.italy")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:175,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.australia")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:50,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryItemSet.CountryFilterPKs.canada")] // Enterprise/Architecture/Core/Core/Environment/Registry/RegistryItemSet.cs:63,28
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.ImageRegistryDataType.MagicNullImage")] // Enterprise/Architecture/Core/Core/Environment/Registry/DataTypesAndValidators/ImageRegistryDataType.cs:206,34
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Core.FormattedRtfString.EmptyRtfPartArray")] // Enterprise/Architecture/Core/Core/Utilities/TextFormatting/FormattedRtfString.cs:109,37
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.CreateCalls")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:47,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.RecipientId")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:51,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.MessageStream")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:50,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.CreateSecureCalls")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:46,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.Factory")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:48,38
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.XmlMessageBody")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:52,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.DebugOnlyOutgoingSystemMessage.MessageName")] // Enterprise/Architecture/Core/Core/Environment/SystemMessage/IOutgoingSystemMessage.cs:49,23
[assembly: SuppressMessage("CargoWiseOne", "EDI001:Resource String Static Reference Rule", Justification = "Baseline WI00613594", Scope = "member", Target = "~F:Enterprise.ZArchitecture.Environment.RegistryFindBoxCollection.GlbGroup")] // Enterprise/Architecture/Core/Core/Environment/Registry/EditorInfos/GuidFindBoxRegistryEditorInfo.cs:39,51
[assembly: SuppressMessage("CargoWiseOne", "CW1173:Do Not Invoke Res Underscore GetString", Justification = "Baseline", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.ParameterizedStringRegistryItem.Deserialise(System.String)")] // Enterprise/Architecture/Core/Core/Environment/Registry/TypedRegistryItems/ParameterizedStringRegistryItem.cs:48,12
[assembly: SuppressMessage("CargoWiseOne", "CW1173:Do Not Invoke Res Underscore GetString", Justification = "Baseline", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Environment.TranslatableRegistryItemValueCaptionSource.GetRuntimeCaptions(CargoWiseOne.ResourceStrings.IResString,System.Object)")] // Enterprise/Architecture/Core/Core/Environment/Registry/TranslatableRegistryItemValueCaptionSource.cs:49,14
[assembly: SuppressMessage("CargoWiseOne", "CW1173:Do Not Invoke Res Underscore GetString", Justification = "Baseline", Scope = "member", Target = "~M:Enterprise.ZArchitecture.Core.EnumExtensions.GetCaption(System.Enum)")] // Enterprise/Architecture/Core/Core/Utilities/EnumExtension.cs:18,10
