<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
	Representation of TARIC record 21500, 21505
 -->
	<xsd:element name="measurementUnitQualifier">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:measurementUnitQualifierDescription" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- Measurement unit qualifier code -->
            <xsd:attribute ref="at:measurementUnitQualifierCode"/>
            <!-- Validity start date of measurement unit qualifier code -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of measurement unit qualifier code -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the national column X_NATIONAL_ABBREV -->
            <xsd:attribute ref="at:nationalAbbreviation"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="measurementUnitQualifierDescription">
        <xsd:complexType>
            <!-- Language id of description -->
            <xsd:attribute ref="at:languageId"/>
            <!-- Short description of measurement unit qualifier -->
            <xsd:attribute ref="at:description"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>
