<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="SalesProductFormLayoutData"
		targetNamespace="http://cargowise.com/SalesProductFormLayoutData.xsd"
		elementFormDefault="qualified"
		xmlns="http://cargowise.com/SalesProductFormLayoutData.xsd"
		xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="SalesProductGridColumnDefinitionData">
		<xs:sequence>
			<xs:element name="GenCustomColumnDefinitionFk" type="xs:string" />
			<xs:element name="Order" type="xs:int" />
			<xs:element name="IsVisible" type="xs:boolean" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SalesProductFieldLayoutDefinitionData">
		<xs:sequence>
			<xs:element name="GenCustomColumnDefinitionFk" type="xs:string" />
			<xs:element name="Order" type="xs:int" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="SalesProductFormLayoutData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TradeLaneCustomColumnDefinitionFks" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="TradeLaneGridColumnDefinitionData" type="SalesProductGridColumnDefinitionData" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="TradeLaneFieldLayoutDefinitionData" type="SalesProductFieldLayoutDefinitionData" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="TradeDetailCustomColumnDefinitionFks" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="TradeDetailGridColumnDefinitionData" type="SalesProductGridColumnDefinitionData" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>
