<?xml version="1.0"?>
<xs:schema xmlns:ax23="http://_10.version.schemas.xml.globalmessagingdictionary.enterprisemessagingmodel.sars.gov.za/xsd" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://customs.bean.ita.interfile.co.za/xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation=".\SupportingDocumentV10_messagingdictionary_enterprisemessagingmodel_sars_gov_za_xsd_1.xsd" namespace="http://_10.version.schemas.xml.globalmessagingdictionary.enterprisemessagingmodel.sars.gov.za/xsd" />
  <xs:complexType name="ContentManagementRequestBean">
    <xs:sequence>
      <xs:element minOccurs="0" name="content" nillable="true" type="ax23:ContentManagementResponse" />
      <xs:element minOccurs="0" name="documentNo" type="xs:int" />
      <xs:element minOccurs="0" name="documentTotal" type="xs:int" />
      <xs:element minOccurs="0" name="token" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="tradeAuthentication" nillable="true" xmlns:q1="http://customs.bean.ita.interfile.co.za/xsd" type="q1:TradeAuthenticationBean" />
      <xs:element minOccurs="0" name="uniqueTranNo" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TradeAuthenticationBean">
    <xs:sequence>
      <xs:element minOccurs="0" name="AACID" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="customsCode" nillable="true" type="xs:string" />
      <xs:element minOccurs="0" name="name" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>