worker_processes  1;
events {
    worker_connections  1024;
}
http {
    upstream message-cache {
        server message-cache-1;
        server message-cache-2;
        server message-cache-3;
    }
server {
        listen          80;
        access_log      /dev/null;
        location / {
            proxy_pass      http://message-cache;
        }
    }
}