worker_processes  1;
events {
    worker_connections  1024;
}
http {
    upstream yyyyyy {
        least_conn;
        server yyyyyy-1;
        server yyyyyy-2;
        server yyyyyy-3;
    }
server {
        listen          80;
        access_log      /dev/null;
        location / {
            proxy_pass      http://yyyyyy;
        }
    }
}