<xs:schema targetNamespace="http://www.cargowise.com/Schemas/Universal" version="1.0" xmlns:cw="http://www.cargowise.com/Schemas/Universal" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="UniversalCommonSchema.xsd" />
  <xs:element name="Declaration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="JobDeclaration" type="cw:JobDeclaration" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="JobDeclaration">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2048" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="AgentsReference" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ApplicationCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="AutoWeightApportion" minOccurs="0" type="xs:boolean" />
      <xs:element name="ConsolidatedCargoStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ContainerCount" minOccurs="0" type="xs:int" />
      <xs:element name="ContainerMode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="DateAtFinalDestination" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DateAtOrigin" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DateOfArrival" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DateOfFirstArrival" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DeclarationReference" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EFTMode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryAuthorisationDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="EntryStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntrySubmittedDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="ExportDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="ExportGoodsType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Folio" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GoodsDescription" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="128" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="HouseBill" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsCancelled" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPersonalEffects" minOccurs="0" type="xs:boolean" />
      <xs:element name="LandedCostByCost" minOccurs="0" type="xs:short" />
      <xs:element name="LandedCostByUnits" minOccurs="0" type="xs:short" />
      <xs:element name="LandedCostByVolume" minOccurs="0" type="xs:short" />
      <xs:element name="LandedCostByWeight" minOccurs="0" type="xs:short" />
      <xs:element name="LloydsIMO" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="7" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MasterBill" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MergeBy" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MessageStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MessageSubType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MessageType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="OperationalStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="OverrideFreightDefaults" minOccurs="0" type="xs:boolean" />
      <xs:element name="OwnerRef" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PaymentMethod" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="ScreeningStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ShipmentIncoTerm" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemCreateTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemCreateUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemLastEditTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemLastEditUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TotalNoOfPacks" minOccurs="0" type="xs:int" />
      <xs:element name="TotalNoOfPacksDecimal" minOccurs="0" type="xs:decimal" />
      <xs:element name="TotalNoOfPacksPackType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TotalNoOfPieces" minOccurs="0" type="xs:int" />
      <xs:element name="TotalNoOfPiecesLanded" minOccurs="0" type="xs:int" />
      <xs:element name="TotalVolume" minOccurs="0" type="xs:decimal" />
      <xs:element name="TotalVolumeUnit" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TotalWeight" minOccurs="0" type="xs:decimal" />
      <xs:element name="TotalWeightUnit" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TransportMode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="UseOwnerRefAsQuarantineRef" minOccurs="0" type="xs:boolean" />
      <xs:element name="VoyageFlightNo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="WarehouseReleaseDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="WarehouseReleaseStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GlbBranch" type="cw:GlbBranch" />
      <xs:element name="CusAgent" type="cw:CusAgent" />
      <xs:element name="JobShipment" type="cw:JobShipment" />
      <xs:element name="Forwarder" type="cw:Forwarder" />
      <xs:element name="Importer" type="cw:Importer" />
      <xs:element name="ShippingLine" type="cw:ShippingLine" />
      <xs:element name="Supplier" type="cw:Supplier" />
      <xs:element name="FinalDestination" type="cw:FinalDestination" />
      <xs:element name="Origin" type="cw:Origin" />
      <xs:element name="PortOfArrival" type="cw:PortOfArrival" />
      <xs:element name="PortOfFirstArrival" type="cw:PortOfFirstArrival" />
      <xs:element name="PortOfLoading" type="cw:PortOfLoading" />
      <xs:element name="ServiceLevel" type="cw:ServiceLevel" />
      <xs:element name="Vessel" type="cw:Vessel" />
      <xs:element name="JobComInvoiceHeaderCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobComInvoiceHeader" type="cw:JobComInvoiceHeader" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CusContainerCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusContainer" type="cw:CusContainer" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CusEntryHeaderCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusEntryHeader" type="cw:CusEntryHeader" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CusEntryNumCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusEntryNum" type="cw:CusEntryNum" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CusDecHouseBillCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusDecHouseBill" type="cw:CusDecHouseBill" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="JobDocsAndCartageCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobDocsAndCartage" type="cw:JobDocsAndCartage" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="LandedCostHeaderCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LandedCostHeader" type="cw:LandedCostHeader" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobComInvoiceHeader">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2048" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FOBValue" minOccurs="0" type="xs:decimal" />
      <xs:element name="GroupInvoice" minOccurs="0" type="xs:boolean" />
      <xs:element name="IncoTerm" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="InvoiceAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="InvoiceCurrExRate" minOccurs="0" type="xs:decimal" />
      <xs:element name="InvoiceCurrExRateType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="InvoiceCurrLandedCostExRate" minOccurs="0" type="xs:decimal" />
      <xs:element name="InvoiceDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="InvoiceDisplaySequence" minOccurs="0" type="xs:int" />
      <xs:element name="InvoiceNumber" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MessageStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NoOfPacks" minOccurs="0" type="xs:decimal" />
      <xs:element name="OverrideFOB" minOccurs="0" type="xs:boolean" />
      <xs:element name="PaymentAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="PaymentDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PaymentExRate" minOccurs="0" type="xs:decimal" />
      <xs:element name="PaymentNo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="StandAloneInvoiceDirection" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ValuationDateOverride" minOccurs="0" type="xs:dateTime" />
      <xs:element name="Volume" minOccurs="0" type="xs:decimal" />
      <xs:element name="VolumeUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Weight" minOccurs="0" type="xs:decimal" />
      <xs:element name="WeightUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="RelatedHouseBill" type="cw:RelatedHouseBill" />
      <xs:element name="GlbBranch" type="cw:GlbBranch" />
      <xs:element name="GroupInvoiceFK" type="cw:GroupInvoiceFK" />
      <xs:element name="Buyer" type="cw:Buyer" />
      <xs:element name="Supplier" type="cw:Supplier" />
      <xs:element name="IncoTermNamedPort" type="cw:IncoTermNamedPort" />
      <xs:element name="DefaultOrigin" type="cw:DefaultOrigin" />
      <xs:element name="Invoice_Currency" type="cw:Invoice_Currency" />
      <xs:element name="JobComInvoiceLineCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobComInvoiceLine" type="cw:JobComInvoiceLine" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobComInvoiceLine">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2048" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="BondedWhsQuantity" minOccurs="0" type="xs:decimal" />
      <xs:element name="BondedWhsUnitQty" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ConcessionOrder" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ContainerMode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib2" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib3" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib4" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib5" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib6" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="80" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomDate1" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDate2" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDate3" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDate4" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDate5" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDecimal1" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomDecimal2" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomDecimal3" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomDecimal4" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomDecimal5" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomFlag3" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomFlag4" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomFlag5" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomsQuantity" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomsUnitQty" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomTextBlob1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:element>
      <xs:element name="Description" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="525" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ExtraInfoForClassification" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:element>
      <xs:element name="HazMatCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="HazMatCodeQualifier" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="1" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="InvoiceQuantity" minOccurs="0" type="xs:decimal" />
      <xs:element name="InvoiceUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="LineNo" minOccurs="0" type="xs:int" />
      <xs:element name="LinePrice" minOccurs="0" type="xs:decimal" />
      <xs:element name="NetWeight" minOccurs="0" type="xs:decimal" />
      <xs:element name="NetWeightUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="OrderNumber" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ParentLine" minOccurs="0" type="xs:int" />
      <xs:element name="PartAttrib1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartAttrib2" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartAttrib3" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartNo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Tariff" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Volume" minOccurs="0" type="xs:decimal" />
      <xs:element name="VolumeUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Weight" minOccurs="0" type="xs:decimal" />
      <xs:element name="WeightUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CountryOfOrigin" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CusClassification" type="cw:CusClassification" />
      <xs:element name="JobOrderLine" type="cw:JobOrderLine" />
      <xs:element name="OrgSupplierPart" type="cw:OrgSupplierPart" />
      <xs:element name="ClassUsageCommentReviewer" type="cw:GlbStaff" />
      <xs:element name="Commodity_Code" type="cw:Commodity_Code" />
      <xs:element name="LandedCostHistoryCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LandedCostHistory" type="cw:LandedCostHistory" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusContainer">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="1024" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ContainerNumber" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ContainerSize" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ContainerUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomDate1" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDecimal1" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="FCL_LCL_AIR" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="MessageStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Seal" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SecondSeal" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Weight" minOccurs="0" type="xs:decimal" />
      <xs:element name="WeightUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="JobContainer" type="cw:JobContainer" />
      <xs:element name="RefContainer" type="cw:RefContainer" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusEntryHeader">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2048" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="BGMReference" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryReleaseDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="EntryStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntrySubmittedDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="HighestLineNumber" minOccurs="0" type="xs:int" />
      <xs:element name="MessageType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Status" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="TotalPaid" minOccurs="0" type="xs:decimal" />
      <xs:element name="PrimeEntry" type="cw:PrimeEntry" />
      <xs:element name="CusEntryHeaderChargesCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusEntryHeaderCharges" type="cw:CusEntryHeaderCharges" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CusEntryLineCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusEntryLine" type="cw:CusEntryLine" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusEntryHeaderCharges">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="ChargeAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="ChargeType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusEntryLine">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="512" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="AdValoremTariff" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomsPostedStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomsValue" minOccurs="0" type="xs:decimal" />
      <xs:element name="Description" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="512" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="DutyPercent" minOccurs="0" type="xs:decimal" />
      <xs:element name="ExtraInfoForClassification" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:element>
      <xs:element name="FlatAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="FlatAmountUQ" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="LineNumber" minOccurs="0" type="xs:int" />
      <xs:element name="ParentTrailer" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="1" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="WarehouseUnitValue" minOccurs="0" type="xs:decimal" />
      <xs:element name="CusEntryLineFeeCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="CusEntryLineFee" type="cw:CusEntryLineFee" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusEntryLineFee">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="ChargeAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="ChargeType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusEntryNum">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Category" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryIsSystemGenerated" minOccurs="0" type="xs:boolean" />
      <xs:element name="EntryLineReference" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryNum" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="EntryType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ExpiryDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="IssueDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="ParentTable" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="CountryCode" type="cw:CountryCode" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusDecHouseBill">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="AddInfo" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2048" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="BillNum" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="BillType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GUIPresentationRecord" minOccurs="0" type="xs:boolean" />
      <xs:element name="IssueDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="MessageStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="NoOfPacks" minOccurs="0" type="xs:decimal" />
      <xs:element name="PackType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="ParentBill" type="cw:ParentBill" />
      <xs:element name="JobShipment" type="cw:JobShipment" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobDocsAndCartage">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="ArrivalCartageRef" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib1" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomAttrib2" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CustomDate1" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDate2" minOccurs="0" type="xs:dateTime" />
      <xs:element name="CustomDecimal1" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomDecimal2" minOccurs="0" type="xs:decimal" />
      <xs:element name="CustomFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="CustomFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="DeliveryCartageAdvised" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DeliveryCartageCompleted" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DeliveryLabourCharge" minOccurs="0" type="xs:decimal" />
      <xs:element name="DeliveryLabourTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DeliveryRequiredBy" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DemurrageOnDeliveryCharge" minOccurs="0" type="xs:decimal" />
      <xs:element name="DemurrageOnDeliveryTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DemurrageOnPickupCharge" minOccurs="0" type="xs:decimal" />
      <xs:element name="DemurrageOnPickupTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="EstimatedDelivery" minOccurs="0" type="xs:dateTime" />
      <xs:element name="EstimatedPickup" minOccurs="0" type="xs:dateTime" />
      <xs:element name="ExportStatement" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FCLAvailable" minOccurs="0" type="xs:dateTime" />
      <xs:element name="FCLDeliveryEquipmentNeeded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FCLPickupEquipmentNeeded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FCLStorageCommences" minOccurs="0" type="xs:dateTime" />
      <xs:element name="HasProhibitedPackaging" minOccurs="0" type="xs:boolean" />
      <xs:element name="InsuranceRequired" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsContingencyRelease" minOccurs="0" type="xs:boolean" />
      <xs:element name="LCLAirStorageCharge" minOccurs="0" type="xs:decimal" />
      <xs:element name="LCLAirStorageDaysOrHours" minOccurs="0" type="xs:short" />
      <xs:element name="LCLAvailable" minOccurs="0" type="xs:dateTime" />
      <xs:element name="LCLDatesOverrideConsol" minOccurs="0" type="xs:boolean" />
      <xs:element name="LCLStorageCommences" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PickupCartageAdvised" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PickupCartageCompleted" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PickupLabourCharge" minOccurs="0" type="xs:decimal" />
      <xs:element name="PickupLabourTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PickupRequiredBy" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="PrintOptionForPackagesOnAWB" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="DeliveryCartageCoAddr" type="cw:DeliveryCartageCoAddr" />
      <xs:element name="PickupCartageCoAddr" type="cw:PickupCartageCoAddr" />
      <xs:element name="JobOrderItemCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobOrderItem" type="cw:JobOrderItem" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="JobServiceCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="JobService" type="cw:JobService" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobOrderItem">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="OrderReference" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="25" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Sequence" minOccurs="0" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobService">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Booked" minOccurs="0" type="xs:dateTime" />
      <xs:element name="Completed" minOccurs="0" type="xs:dateTime" />
      <xs:element name="Duration" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="References" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ServiceCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ServiceCount" minOccurs="0" type="xs:decimal" />
      <xs:element name="ServiceNote" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="256" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GlbCompany" type="cw:GlbCompany" />
      <xs:element name="Location" type="cw:Location" />
      <xs:element name="Contractor" type="cw:Contractor" />
      <xs:element name="RefEquipment" type="cw:RefEquipment" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="LandedCostHeader">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="DateOfEntry" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DateOfProcessing" minOccurs="0" type="xs:dateTime" />
      <xs:element name="DefaultEstimatedDutyRate" minOccurs="0" type="xs:decimal" />
      <xs:element name="EstimatedLandedCostComment" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="128" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="LandedCostType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
      <xs:element name="GlbCompany" type="cw:GlbCompany" />
      <xs:element name="LandCostInputCollection">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="LandCostInput" type="cw:LandCostInput" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="LandCostInput">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="ChargeDescription" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CostAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="DistributeCostBy" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsParentGroupInvoice" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserEntered" minOccurs="0" type="xs:boolean" />
      <xs:element name="LandedCostGroup" minOccurs="0" type="xs:short" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="ServiceExRate" minOccurs="0" type="xs:decimal" />
      <xs:element name="ChargeCode" type="cw:ChargeCode" />
      <xs:element name="CostCurrency" type="cw:CostCurrency" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="LandedCostHistory">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="DutyPercent" minOccurs="0" type="xs:decimal" />
      <xs:element name="EntryFees" minOccurs="0" type="xs:decimal" />
      <xs:element name="Excise" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup1" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup2" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup3" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup4" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup5" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroup6" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostGroupMisc" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostHistoryLineType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="LandedCostMarginPercent1" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostMarginPercent2" minOccurs="0" type="xs:decimal" />
      <xs:element name="LandedCostMarginPercent3" minOccurs="0" type="xs:decimal" />
      <xs:element name="OtherOrFlatDutyAmount" minOccurs="0" type="xs:decimal" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="QuarantineFees" minOccurs="0" type="xs:decimal" />
      <xs:element name="SpecialTax1" minOccurs="0" type="xs:decimal" />
      <xs:element name="SpecialTax2" minOccurs="0" type="xs:decimal" />
      <xs:element name="SpecialTax3" minOccurs="0" type="xs:decimal" />
      <xs:element name="TotalDuty" minOccurs="0" type="xs:decimal" />
      <xs:element name="OrgSupplierPart" type="cw:OrgSupplierPart" />
      <xs:element name="CountryOfEntry" type="cw:CountryOfEntry" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Importer">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FullName" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsBroker" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsCompetitor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignee" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsContainerPark" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsEmailUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFaxUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsForwarder" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFumigationContractor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsGlobalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLineHaulProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLocalTransport" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMailOut" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMiscFreightServices" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNationalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNewsLetter" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPersonalEffectsAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailHead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRoadFreightDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSalesLead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingConsortium" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTempAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTransportClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUnpackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag3" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag4" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag5" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag6" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag7" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag8" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsWarehouseClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="Language" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartialBusiness" minOccurs="0" type="xs:boolean" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Prospect" minOccurs="0" type="xs:boolean" />
      <xs:element name="ScreeningStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemCreateTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemCreateUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemLastEditTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemLastEditUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Supplier">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FullName" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsBroker" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsCompetitor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignee" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsContainerPark" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsEmailUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFaxUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsForwarder" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFumigationContractor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsGlobalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLineHaulProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLocalTransport" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMailOut" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMiscFreightServices" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNationalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNewsLetter" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPersonalEffectsAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailHead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRoadFreightDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSalesLead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingConsortium" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTempAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTransportClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUnpackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag3" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag4" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag5" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag6" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag7" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag8" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsWarehouseClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="Language" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartialBusiness" minOccurs="0" type="xs:boolean" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Prospect" minOccurs="0" type="xs:boolean" />
      <xs:element name="ScreeningStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemCreateTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemCreateUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemLastEditTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemLastEditUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="ShippingLine">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FullName" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsBroker" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsCompetitor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignee" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsContainerPark" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsEmailUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFaxUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsForwarder" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFumigationContractor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsGlobalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLineHaulProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLocalTransport" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMailOut" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMiscFreightServices" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNationalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNewsLetter" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPersonalEffectsAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailHead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRoadFreightDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSalesLead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingConsortium" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTempAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTransportClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUnpackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag3" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag4" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag5" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag6" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag7" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag8" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsWarehouseClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="Language" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartialBusiness" minOccurs="0" type="xs:boolean" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Prospect" minOccurs="0" type="xs:boolean" />
      <xs:element name="ScreeningStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemCreateTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemCreateUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemLastEditTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemLastEditUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Forwarder">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="FullName" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="50" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="IsActive" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsAirWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsBroker" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsCompetitor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignee" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsConsignor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsContainerPark" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsEmailUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFaxUpdate" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsForwarder" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsFumigationContractor" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsGlobalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLineHaulProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsLocalTransport" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMailOut" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsMiscFreightServices" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNationalAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsNewsLetter" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsPersonalEffectsAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailHead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRailProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsRoadFreightDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSalesLead" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaCTO" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsSeaWholesaler" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingConsortium" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingLine" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsShippingProvider" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTempAccount" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsTransportClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUnpackDepot" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag1" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag2" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag3" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag4" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag5" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag6" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag7" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsUserFlag8" minOccurs="0" type="xs:boolean" />
      <xs:element name="IsWarehouseClient" minOccurs="0" type="xs:boolean" />
      <xs:element name="Language" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PartialBusiness" minOccurs="0" type="xs:boolean" />
      <xs:element name="PK" type="xs:string" />
      <xs:element name="Prospect" minOccurs="0" type="xs:boolean" />
      <xs:element name="ScreeningStatus" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemCreateTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemCreateUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="SystemLastEditTime" minOccurs="0" type="xs:dateTime" />
      <xs:element name="SystemLastEditUser" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="GlbBranch">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusAgent">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="LoginName" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobShipment">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="UniqueConsignRef" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="20" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="FinalDestination">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Origin">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="PortOfArrival">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="PortOfFirstArrival">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="PortOfLoading">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="ServiceLevel">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Vessel">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="RelatedHouseBill">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="GroupInvoiceFK">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Buyer">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="IncoTermNamedPort">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="DefaultOrigin">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Invoice_Currency">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CusClassification">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="ClassificationType" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="CountryCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:element>
      <xs:element name="LookupCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="35" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobOrderLine">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="JobOrderHeader" type="xs:string" />
      <xs:element name="LineNo" minOccurs="0" type="xs:int" />
      <xs:element name="SubLineNo" minOccurs="0" type="xs:int" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="OrgSupplierPart">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Commodity_Code">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="4" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="JobContainer">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="RefContainer">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="PrimeEntry">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CountryCode">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="ParentBill">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="DeliveryCartageCoAddr">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="OrgHeader" type="xs:string" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="25" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="PickupCartageCoAddr">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="OrgHeader" type="xs:string" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="25" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="GlbCompany">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Location">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="OrgHeader" type="xs:string" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="25" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="Contractor">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="RefEquipment">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Registration" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="ShortCode" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="ChargeCode">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="GlbCompany" type="xs:string" />
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CostCurrency">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="CountryOfEntry">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="2" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
  <xs:complexType name="ClosestPort">
    <xs:sequence>
      <xs:element name="Key" type="cw:TableKey" />
      <xs:element name="Code" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="5" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="PK" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Action" type="cw:Action" />
  </xs:complexType>
</xs:schema>
