//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from FDAEntryLevelDispositionCodeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.US.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class FDAEntryLevelDispositionCodeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string _01 = "01";
			public const string _02 = "02";
			public const string _03 = "03";
			public const string _04 = "04";
			public const string _05 = "05";
			public const string _06 = "06";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string _01 = "FDA REVIEW";
			public const string _02 = "FDA HOLD";
			public const string _03 = "FDA DO NOT DEVAN";
			public const string _04 = "FDA EXAM/SAMPLE";
			public const string _05 = "FDA RELEASE";
			public const string _06 = "FDA MAY PROCEED";
		}

		public FDAEntryLevelDispositionCodeList()
		{
			AddPair(Codes._01, Descriptions._01);
			AddPair(Codes._02, Descriptions._02);
			AddPair(Codes._03, Descriptions._03);
			AddPair(Codes._04, Descriptions._04);
			AddPair(Codes._05, Descriptions._05);
			AddPair(Codes._06, Descriptions._06);
		}
	}
}
