//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from StatementLineFilterByOptionList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.US.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class StatementLineFilterByOptionList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string All = "ALL";
			public const string LinesWithAPDiscrepany = "APD";
			public const string LinesWithARDiscrepany = "ARD";
			public const string LinesWithDiscrepany = "LWD";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string All = "Show All Lines With Disbursement";
			public const string LinesWithAPDiscrepany = "Show Lines With AP Discrepancies";
			public const string LinesWithARDiscrepany = "Show Lines With AR Discrepancies";
			public const string LinesWithDiscrepany = "Show Lines With Discrepancies";
		}

		public StatementLineFilterByOptionList()
		{
			AddPair(Codes.All, Descriptions.All);
			AddPair(Codes.LinesWithAPDiscrepany, Descriptions.LinesWithAPDiscrepany);
			AddPair(Codes.LinesWithARDiscrepany, Descriptions.LinesWithARDiscrepany);
			AddPair(Codes.LinesWithDiscrepany, Descriptions.LinesWithDiscrepany);
		}
	}
}
