<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Enterprise.Rating.Web.SelfHost</RootNamespace>
    <AssemblyName>Enterprise.Rating.Web.SelfHost</AssemblyName>
    <OutputPath>..\..\..\..\..\..\bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Owin.Hosting">
      <HintPath>..\..\..\..\..\..\bin\Microsoft.Owin.Hosting.dll</HintPath>
    </Reference>
    <Reference Include="Owin">
      <HintPath>..\..\..\..\..\..\bin\Owin.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rating.Web\Rating.Web.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>