<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <OutputPath>..\..\bin\Plugin.Tests</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Plugin\CargoWise.Billing.CollectorService.Plugin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Billing.API">
      <HintPath>..\..\bin\CargoWise.Billing.API\$(TargetFramework)\CargoWise.Billing.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Kafka.API">
      <HintPath>..\..\bin\CargoWise.Billing.API\$(TargetFramework)\CargoWise.Billing.Kafka.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Client">
      <HintPath>..\..\bin\CargoWise.Billing.Client\$(TargetFramework)\CargoWise.Billing.Client.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>