<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.TransportBookings.ServiceTasks.Test</RootNamespace>
    <AssemblyName>Enterprise.TransportBookings.ServiceTasks.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.DbUpgrader.Shared" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Freight.LocalCartage.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Packing.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.TransportCommon.Business" />
    <Reference Include="Enterprise.TransportCommon.Registry" />
    <Reference Include="Enterprise.TransportCommon.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TransportBooking.Business\TransportBookings.Business.csproj" />
    <ProjectReference Include="..\TransportBookings.Business.Test\TransportBookings.Business.Test.csproj" />
    <ProjectReference Include="..\TransportBookings.Business.Common\TransportBookings.Shared.csproj" />
    <ProjectReference Include="..\TransportBookings.ServiceTasks\TransportBookings.ServiceTasks.csproj" />
  </ItemGroup>
</Project>