<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://agriculture.gov.au/nexdoc/WithdrawalRexSoap_1.0" elementFormDefault="qualified"
            xmlns:ct="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0"
            xmlns:cw="http://agriculture.gov.au/nexdoc/common/rex/CommonTypes_1.0">

    <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/CommonTypes_1.0" schemaLocation="common/CommonTypes.xsd"/>
    <xsd:import namespace="http://agriculture.gov.au/nexdoc/common/rex/CommonTypes_1.0" schemaLocation="common/rex/CommonTypes.xsd"/>

    <!-- SOAP root payload -->
    <xsd:element name="WithdrawalRex">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="identification" type="cw:RexSubmissionIdentificationType" maxOccurs="1" minOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="WithdrawalRexResponse">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="withdrawalRexResponse" type="cw:WithdrawalRexMessageResponse" maxOccurs="1"
                             minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>
