// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~P:Enterprise.DocumentScanning.Business.Test.TestingConstants.TestDirectory")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAsImage")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAddFromFilesystem")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAddNewDocumentAfterScanning")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAddNewDocumentAfterScanningWithAutoAllocatableDoc")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAddNewDocumentAfterScanningWithMSCDoc_ShouldBeAutoAllocatable")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.AllocateDocumentsManagerTest.TestAddNewDocumentAfterScanningWithOutOfMemoryExceptionIsHandled")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.ArchiveeDocsManagerTest.TestTotalSizeDoesNotUseExtraMemory")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BarcodeSorterTest.TestBarcodeRecognizedForNoisyPoints")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BarcodeSorterTest.TestProcessPageForBarcodesUsingDocTypeBarcode")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BarcodeSorterTest.TestProcessPageForBarcodesWithStandardBarcode")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BatchImportManagerTest.TestImportWithBadImageFileThatThrowsExternalException")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BatchImportManagerTest.TestImportFileWithoutDeleteAuthority")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BatchImportManagerTest.TestImportWithFileWithAllocationInformationInBarcodesAndWrongInFileName")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.BatchImportManagerTest.TestImportWithFileWithAllocationInformationInBarcodesAndJobFromFilenameNotExists")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileAccessExceptionTest.TestConstructor")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileImporterTest.TestImportFromDirectory")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileImporterTest.TestFileCount")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileListFormatterTest.TestFormatListToString")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileListFormatterTest.TestFormatListToStringWithFullPathNames")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.FileListFormatterTest.TestFormatListToStringWithFileNameContainsInvalidCharacter")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentUtilitiesTest.TestConvertFileToTiffForMultipageFilesWithByteArray")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentUtilitiesTest.TestConvertFileToTiffForMultipageFiles")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentUtilitiesTest.TestAppendMultiPageImageToFile")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentUtilitiesTest.TestCopySelectedPages")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.Test.TestSC_FilenameTruncated")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.Test.TestSC_DataTypeTruncated")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.StorageFileCollectionViewTest.TestSC_FilenameTruncated")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.StorageFileCollectionViewTest.TestSC_DataTypeTruncated")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.StorageDocsTest.TestSC_ImageData")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentSplitManagerTest.TestSplitDocumentWithPdfiumException")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.StorageDocsCollectionHelperTest.TestGetMostRecentEDoc")]
[assembly: SuppressMessage("CargoWiseOne", "CW1051:Do not use BaseSourcePath", Justification = "<Pending>", Scope = "member", Target = "~F:Enterprise.DocumentScanning.Business.Test.DocumentUtilTest.TestRepositoryPath")]
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocumentDbMergerTest.TestInitialiseOnSingleUserDBMode")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/DocumentDbManager/DbMerger/DocumentDbMergerTest.cs:862,28
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestFileUploadStreamBufferSize")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:151,4
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestFileUploadStreamBufferSize")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:152,4
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableCommercialInvoiceDocumentParsingHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:246,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableCommercialInvoiceDocumentParsingHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:247,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableAccountsPayableInvoiceDocumentParsingHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:263,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableAccountsPayableInvoiceDocumentParsingHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:264,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestDocumentParserUrlHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:280,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestDocumentParserUrlHelper(System.Boolean)")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:281,5
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableDocumentParsing")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:33,4
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Test.DocManagerRegistryTest.TestEnableDocumentParsing")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/Registries/DocManagerRegistryTest.cs:34,4
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentScanning.Business.Testing.BatchImportManagerTest.TestImportWithBadImageFileOnEmail")] // Enterprise/Product/Documents/DocumentScanning/DocumentScanning.Business.Test/BatchProcessor/BatchImportManagerTest.cs:745,49
