using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1017", Justification = "Standalone tool. ZArchitecture DPI-awareness checks not done")]
[assembly: SuppressMessage("CargoWiseOne", "CW1040", Justification = "Standalone tool. ZArchitecture DPI-awareness checks not done")]
[assembly: SuppressMessage("CargoWiseOne", "CW1076:Do not use MessageBox.Show", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.GUI.LogShippingSetupForm.LogShippingSetupForm_FormClosing(System.Object,System.Windows.Forms.FormClosingEventArgs)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\GUI\LogShippingSetupForm.cs:83:32
[assembly: SuppressMessage("CargoWiseOne", "CW1076:Do not use MessageBox.Show", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.Program.Main")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\Program.cs:23:4
[assembly: SuppressMessage("CargoWiseOne", "CW1076:Do not use MessageBox.Show", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.GUI.DatabaseBackupMatchingForm.OnClosing(System.ComponentModel.CancelEventArgs)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\GUI\ScreenControls\DatabaseBackupMatchingForm.cs:124:5
[assembly: SuppressMessage("CargoWiseOne", "CW1076:Do not use MessageBox.Show", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.GUI.DatabaseBackupMatchingForm.OpenFolderBrowserAndSetValue(System.Windows.Forms.TextBox)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\GUI\ScreenControls\DatabaseBackupMatchingForm.cs:215:6
[assembly: SuppressMessage("CargoWiseOne", "CW1076:Do not use MessageBox.Show", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.ScreenNavigator.InitializeSeconaryDatabase(System.Boolean)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\ScreenNavigator.cs:766:4
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.LogShipping.Setup.LogShippingConfigurator.RestoreThresholdInMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\LogShippingConfigurator.cs:609:12
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.RestoreManager.GetRestoreStandBySqlScript(Enterprise.LogShipping.Setup.DatabaseInfo,Enterprise.LogShipping.Setup.BackupFileInfo[])")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\RestoreManager.cs:128:4
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.LogShipping.Setup.GUI.UserAreaControl.ShowMessage(System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\DataTools\LogShipping\Setup\GUI\ScreenControls\UserAreaControl.cs:14:59
