<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.BufferManagement.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.BufferManagement.GUI.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <UseLegacyRsa>false</UseLegacyRsa>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
    <PackageReference Include="WTG.Z.Blazor.Diagrams" />
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\NetworkVisualisation\NCN.ServiceTasks\BufferManagement.NetworkVisualisation.ServiceTasks.csproj" />
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.GUI.Test\VisualBoards.GUI.Test.Winzor.csproj" />
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.GUI\VisualBoards.GUI.Winzor.csproj" />
    <ProjectReference Include="..\GUI\BufferManagement.GUI.Winzor.csproj" />
    <ProjectReference Include="..\Module\BufferManagement.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.BufferManagement.NetworkVisualisation.ServiceTasks" />
    <Reference Include="Enterprise.PAVE.MENT.Business" />
    <Reference Include="Enterprise.PAVE.MENT.Business.ServiceTasks" />
    <Reference Include="WinzorFramework" />
    <Reference Include="CargoWise.Interop" />
  </ItemGroup>
</Project>