<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.BufferManagement.GUI.Test</RootNamespace>
    <AssemblyName>Enterprise.BufferManagement.GUI.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.RemoteDesktopServices.Server" />
    <Reference Include="Enterprise.RemoteDesktopServices.Shared" />
    <Reference Include="Moq" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="CargoWise.Interop" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.GUI.Test\VisualBoards.GUI.Test.csproj" />
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.GUI\VisualBoards.GUI.csproj" />
    <ProjectReference Include="..\GUI\BufferManagement.GUI.csproj" />
    <ProjectReference Include="..\Module\BufferManagement.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services\" />
  </ItemGroup>
</Project>