// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:19,18
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:20,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:21,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:22,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:23,22
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:24,21
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryItemTest.GetNewRegistryItem")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:25,22
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,184
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,226
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,271
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,316
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,362
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,408
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:36,454
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,188
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,230
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,275
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,320
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,366
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,412
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingRegistryDataTypeTest.GetValidSamples")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingRegistryItemTest.cs:37,458
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateMachineName")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:25,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:71,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:72,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:75,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:78,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:82,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:83,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLSMSMessageSendingTest.TestValidateFolders")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Registry/SMS/CLSMSMessageSendingValidationTest.cs:86,26
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:112,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:113,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:114,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:115,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:116,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:117,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLInterchangeProviderTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLInterchangeProviderTest.cs:118,24
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.AsycudaArrivalLineTest.GetNewBusinessObjectForDeleteTest(CargoWise.EntityFramework.BusinessObjectFactory)")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/BusinessObject/AsycudaArrivalLine/AsycudaArrivalLineTest.cs:20,43
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:100,20
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:101,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:102,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:103,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:104,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:105,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CL.Manifest.Business.Testing.CLOutgoingMessageProcessorTest.CreateSMSMessageSending")] // Enterprise/Product/Operations/Customs/CL/Manifest/Business.Test/Message/MessageProcessors/CLOutgoingMessageProcessorTest.cs:106,24
