<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWiseOne.WebInfrastructure" />
    <Reference Include="Enterprise.ZArchitecture.Web.Shared" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WTG.AppDomainWrappers.Core" />
    <PackageReference Include="WTG.AppDomainWrappers.Runner" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared.Test.Common\Enterprise.ZArchitecture.Web.Shared.Test.Common.csproj" />
  </ItemGroup>
</Project>