namespace Enterprise.MasterFiles.GUI
{
	public partial class TasksControl
	{
		#region Component Designer generated code

		private void InitializeComponent()
		{
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateTimeOffsetEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo zDateTimeOffsetEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateTimeOffsetEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo9 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo10 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo6 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo7 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZMultiControlColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo8 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo6 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo7 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo8 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo22 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			this.TasksTemplateLinkLabel = new Enterprise.ZArchitecture.GUI.ZLinkLabel();
			this.TasksGrid = new Enterprise.ZArchitecture.ZGrid();
			this.TasksHintSplitContainer = new CargoWise.Windows.UI.KSplitContainer();
			this.TasksHintLabel = new Enterprise.ZArchitecture.ZLabel();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.TasksGrid)).BeginInit();
			this.TasksGrid.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.TasksHintSplitContainer)).BeginInit();
			this.TasksHintSplitContainer.Panel1.SuspendLayout();
			this.TasksHintSplitContainer.Panel2.SuspendLayout();
			this.TasksHintSplitContainer.SuspendLayout();
			this.SuspendLayout();
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Enterprise.MasterFiles.Business.ProcessTask);
			// 
			// TasksTemplateLinkLabel
			// 
			this.TasksTemplateLinkLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
			this.TasksTemplateLinkLabel.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|2d8b4b07-1e5f-49ed-b237-c9bfc3ddc4eb", "Click to create tasks from Template");
			this.TasksTemplateLinkLabel.IsFontBold = false;
			this.TasksTemplateLinkLabel.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(3, 227, true);
			this.TasksTemplateLinkLabel.Name = "TasksTemplateLinkLabel";
			this.TasksTemplateLinkLabel.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(730, 13, true);
			this.TasksTemplateLinkLabel.TabIndex = 1;
			this.TasksTemplateLinkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.TasksTemplateLinkLabel_LinkClicked);
			// 
			// TasksGrid
			// 
			this.TasksGrid.AllowNavigation = false;
			this.TasksGrid.AllowReadOnlyRowsToBeDeleted = true;
			this.BindingSource.SetBindingMember(this.TasksGrid, ".");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((Enterprise.MasterFiles.Business.ProcessTask)(null)))));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_TaskID)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_Description)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).WorkflowSequence)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_Sequence)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_Type)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TypeDescription)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_IsCalendarItem)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_Status)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).StatusDescription)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_GS_NKAssignedStaffMember)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).StaffName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_GG_AssignedGroup)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).GroupName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_G4_RequiredCapability)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).CapabilityName)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_OA)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_OC)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTimeOffset)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ScheduledDateForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ScheduledDateUtcForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ScheduledDateLocalForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.INumericZType)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstimateVariationFactor)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).HighEstimatedDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).StandardEstimatedDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstimatedTimeToComplete)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTimeOffset)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ActualDateForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ActualDateUtcForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ActualDateLocalForBinding)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).CompletedTimeLocal)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_CompletedTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ActualDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).ElapsedDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).SuspendedDuration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).HasNote)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.OriginCountryCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.DestinationCountryCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_TaskCannotBeDeleted)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.TemplateCondition1)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.TemplateCondition2)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.TemplateCondition2Value)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TemplateConditions.TemplateCondition2ValueFieldType)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_FH_ProcessHeader)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).EstimatedHandoverTimeLocal)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstimatedHandoverTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_IsInterruptable)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_ShareTasksForAllCompanies)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstimatedDefaultedFrom)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_EstimatedDefaultTimeDelta)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).SourceTemplatePK)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_SE_NKTaskCompletionEvent)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_IsResetBeingAppliedToThisTask)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZBool)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_RecalculateScheduledDate)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).Iteration)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_SystemCreateTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_SystemCreateUser)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_SystemLastEditTimeUtc)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_SystemLastEditUser)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZDateTime)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TimeBecameStartable)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TriggerConditions.TriggerContextCode)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZGuid)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).TriggerConditions.TriggerCompany)));
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CargoWise.Types.ZString)(((Enterprise.MasterFiles.Business.ProcessTask)(null)).P9_MilestoneCompletionPivotKey)));
			this.TasksGrid.CaptionVisible = false;
			zTextBoxColumnStyleInfo1.ColumnName = "P9_TaskID";
			zTextBoxColumnStyleInfo1.IsVisible = false;
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(75);
			zTextBoxColumnStyleInfo2.ColumnName = "P9_Description";
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(220);
			zTextBoxColumnStyleInfo3.ColumnName = "WorkflowSequence";
			zTextBoxColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.ColumnName = "P9_Sequence";
			zCalcEditColumnStyleInfo1.Decimals = 0;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zDropEditColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo1.ColumnName = "P9_Type";
			zDropEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo4.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|0a07467b-702b-4650-a45e-ecc74a90ee77", "Type Description");
			zTextBoxColumnStyleInfo4.ColumnName = "TypeDescription";
			zTextBoxColumnStyleInfo4.IsVisible = false;
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zCheckBoxColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			zCheckBoxColumnStyleInfo1.ColumnName = "P9_IsCalendarItem";
			zCheckBoxColumnStyleInfo1.ToolTip = "If ticked, a calendar appointment item will be created for this task.";
			zCheckBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zDropEditColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo2.ColumnName = "P9_Status";
			zDropEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo5.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|924b489c-33f8-4270-b211-01e3cfeb01ab", "Status Description");
			zTextBoxColumnStyleInfo5.ColumnName = "StatusDescription";
			zTextBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(160);
			zCodeFindBoxColumnStyleInfo1.ColumnName = "P9_GS_NKAssignedStaffMember";
			zCodeFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo6.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|52461cac-31a2-47d3-8e28-f0d9bfaae770", "Staff Name");
			zTextBoxColumnStyleInfo6.ColumnName = "StaffName";
			zTextBoxColumnStyleInfo6.IsVisible = false;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zGuidFindBoxColumnStyleInfo1.ColumnName = "P9_GG_AssignedGroup";
			zGuidFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo7.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|58d0c6b1-8b2a-41d5-896f-288d261539ab", "Group Name");
			zTextBoxColumnStyleInfo7.ColumnName = "GroupName";
			zTextBoxColumnStyleInfo7.IsVisible = false;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zGuidFindBoxColumnStyleInfo2.ColumnName = "P9_G4_RequiredCapability";
			zGuidFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo8.ColumnName = "CapabilityName";
			zTextBoxColumnStyleInfo8.IsVisible = false;
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidDropEditColumnStyleInfo1.ColumnName = "P9_OA";
			zGuidDropEditColumnStyleInfo1.IsVisible = false;
			zGuidDropEditColumnStyleInfo1.ShowInDropDown = Enterprise.ZArchitecture.GUI.ZDropEdit.ShowInDropDownList.OnlyShowCode;
			zGuidDropEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zGuidDropEditColumnStyleInfo2.ColumnName = "P9_OC";
			zGuidDropEditColumnStyleInfo2.IsVisible = false;
			zGuidDropEditColumnStyleInfo2.ShowInDropDown = Enterprise.ZArchitecture.GUI.ZDropEdit.ShowInDropDownList.OnlyShowCode;
			zGuidDropEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDateTimeOffsetEditColumnStyleInfo1.ColumnName = "P9_ScheduledDateForBinding";
			zDateTimeOffsetEditColumnStyleInfo1.HasTimeZoneFindBox = true;
			zDateTimeOffsetEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo7.ColumnName = "P9_ScheduledDateUtcForBinding";
			zDateEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo8.ColumnName = "P9_ScheduledDateLocalForBinding";
			zDateEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zTimeEditExColumnStyleInfo1.AllowNegative = false;
			zTimeEditExColumnStyleInfo1.ColumnName = "P9_EstDuration";
			zTimeEditExColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(75);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.ColumnName = "P9_EstimateVariationFactor";
			zCalcEditColumnStyleInfo2.Decimals = 0;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTimeEditExColumnStyleInfo2.AllowNegative = false;
			zTimeEditExColumnStyleInfo2.ColumnName = "HighEstimatedDuration";
			zTimeEditExColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(75);
			zTimeEditExColumnStyleInfo3.AllowNegative = false;
			zTimeEditExColumnStyleInfo3.ColumnName = "StandardEstimatedDuration";
			zTimeEditExColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTimeEditExColumnStyleInfo4.AllowNegative = false;
			zTimeEditExColumnStyleInfo4.ColumnName = "P9_EstimatedTimeToComplete";
			zTimeEditExColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(85);
			zDateTimeOffsetEditColumnStyleInfo2.ColumnName = "P9_ActualDateForBinding";
			zDateTimeOffsetEditColumnStyleInfo2.HasTimeZoneFindBox = true;
			zDateTimeOffsetEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo9.ColumnName = "P9_ActualDateUtcForBinding";
			zDateEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo10.ColumnName = "P9_ActualDateLocalForBinding";
			zDateEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo1.ColumnName = "CompletedTimeLocal";
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDateEditColumnStyleInfo5.ColumnName = "P9_CompletedTimeUtc";
			zDateEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDateEditColumnStyleInfo5.IsReadOnly = true;
			zTimeEditExColumnStyleInfo5.AllowNegative = false;
			zTimeEditExColumnStyleInfo5.ColumnName = "P9_ActualDuration";
			zTimeEditExColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTimeEditExColumnStyleInfo6.AllowNegative = false;
			zTimeEditExColumnStyleInfo6.ColumnName = "ElapsedDuration";
			zTimeEditExColumnStyleInfo6.IsVisible = false;
			zTimeEditExColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTimeEditExColumnStyleInfo7.AllowNegative = false;
			zTimeEditExColumnStyleInfo7.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|1166f238-bd9b-4dda-9271-bd02dc182dee", "Suspended Duration");
			zTimeEditExColumnStyleInfo7.ColumnName = "SuspendedDuration";
			zTimeEditExColumnStyleInfo7.IsVisible = false;
			zTimeEditExColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo2.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|bc577b1c-f7f7-4709-b9c4-4c8f1db78d59", "Notes?");
			zCheckBoxColumnStyleInfo2.ColumnName = "HasNote";
			zCheckBoxColumnStyleInfo2.IsVisible = false;
			zCheckBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zCodeFindBoxColumnStyleInfo2.ColumnName = "TemplateConditions+OriginCountryCode";
			zCodeFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCodeFindBoxColumnStyleInfo3.ColumnName = "TemplateConditions+DestinationCountryCode";
			zCodeFindBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo3.ColumnName = "P9_TaskCannotBeDeleted";
			zCheckBoxColumnStyleInfo3.IsVisible = false;
			zCheckBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo3.ColumnName = "TemplateConditions+TemplateCondition1";
			zDropEditColumnStyleInfo3.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|750deeda-f941-48c4-af79-4b191b7ce49b", "Template Conditions");
			zDropEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo4.ColumnName = "TemplateConditions+TemplateCondition2";
			zDropEditColumnStyleInfo4.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|750deeda-f941-48c4-af79-4b191b7ce49b", "Template Conditions");
			zDropEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zMultiControlColumnStyleInfo1.BindToDecimalPlaces = null;
			zMultiControlColumnStyleInfo1.ColumnName = "TemplateConditions+TemplateCondition2Value";
			zMultiControlColumnStyleInfo1.FieldTypeColumnName = "TemplateConditions.TemplateCondition2ValueFieldType";
			zMultiControlColumnStyleInfo1.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|750deeda-f941-48c4-af79-4b191b7ce49b", "Template Conditions");
			zMultiControlColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zGuidDropEditColumnStyleInfo3.ColumnName = "P9_FH_ProcessHeader";
			zGuidDropEditColumnStyleInfo3.IsVisible = false;
			zGuidDropEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zDateEditColumnStyleInfo2.ColumnName = "EstimatedHandoverTimeLocal";
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(85);
			zDateEditColumnStyleInfo6.ColumnName = "P9_EstimatedHandoverTimeUtc";
			zDateEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(85);
			zDateEditColumnStyleInfo6.IsReadOnly = true;
			zCheckBoxColumnStyleInfo4.ColumnName = "P9_IsInterruptable";
			zCheckBoxColumnStyleInfo4.IsVisible = false;
			zCheckBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo5.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|13fe9c38-ad2f-4b58-9503-f8138bf4a526", "Share", "Share across companies", "Share this task across all companies.");
			zCheckBoxColumnStyleInfo5.ColumnName = "P9_ShareTasksForAllCompanies";
			zCheckBoxColumnStyleInfo5.IsVisible = false;
			zCheckBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDropEditColumnStyleInfo5.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|044e1297-a40b-4124-b5cc-a9de24015641", "Est. Def. From", "Estimate Defaulted From", "Specifies a date that the estimate of this task is defaulted from.\r\nThe date can be defaulted from a system defined event that occurs.\r\nThe estimate date on this task will be defaulted from the other related date when it becomes available, and the job is saved.");
			zDropEditColumnStyleInfo5.ColumnName = "P9_EstimatedDefaultedFrom";
			zDropEditColumnStyleInfo5.IsVisible = false;
			zDropEditColumnStyleInfo5.MaxDropDownItems = 30;
			zDropEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTimeEditExColumnStyleInfo8.AllowNegative = true;
			zTimeEditExColumnStyleInfo8.CaptionResourceString = Enterprise.MasterFiles.GUI.Res.GetData("TasksControl|23feb219-3742-4ded-a7ab-2cf940f0f6bf", "Est. Def. Hours", "Estimate Default Hours", "The number of hours difference to apply when defaulting the estimate date of this task from another date.");
			zTimeEditExColumnStyleInfo8.ColumnName = "P9_EstimatedDefaultTimeDelta";
			zTimeEditExColumnStyleInfo8.IsVisible = false;
			zTimeEditExColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo3.ColumnName = "SourceTemplatePK";
			zGuidFindBoxColumnStyleInfo3.IsVisible = false;
			zGuidFindBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo6.ColumnName = "P9_SE_NKTaskCompletionEvent";
			zDropEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCheckBoxColumnStyleInfo7.ColumnName = "P9_IsResetBeingAppliedToThisTask";
			zCheckBoxColumnStyleInfo7.IsVisible = false;
			zCheckBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCheckBoxColumnStyleInfo8.ColumnName = "P9_RecalculateScheduledDate";
			zCheckBoxColumnStyleInfo8.IsVisible = false;
			zCheckBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDropEditColumnStyleInfo7.ColumnName = "Iteration";
			zDropEditColumnStyleInfo7.IsVisible = false;
			zDropEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo3.ColumnName = "P9_SystemCreateTimeUtc";
			zDateEditColumnStyleInfo3.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("5fb7ee0a-903a-46d3-9ce8-f0fe4e532c16", "Audit Columns");
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo9.ColumnName = "P9_SystemCreateUser";
			zTextBoxColumnStyleInfo9.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("5fb7ee0a-903a-46d3-9ce8-f0fe4e532c16", "Audit Columns");
			zTextBoxColumnStyleInfo9.IsVisible = false;
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo4.ColumnName = "P9_SystemLastEditTimeUtc";
			zDateEditColumnStyleInfo4.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("5fb7ee0a-903a-46d3-9ce8-f0fe4e532c16", "Audit Columns");
			zDateEditColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo10.ColumnName = "P9_SystemLastEditUser";
			zTextBoxColumnStyleInfo10.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("5fb7ee0a-903a-46d3-9ce8-f0fe4e532c16", "Audit Columns");
			zTextBoxColumnStyleInfo10.IsVisible = false;
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo11.ColumnName = "TimeBecameStartable";
			zTextBoxColumnStyleInfo11.IsVisible = false;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDropEditColumnStyleInfo8.ColumnName = "TriggerConditions+TriggerContextCode";
			zDropEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo8.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("7040C9E2-B609-40E0-B603-18107AE53AC0", "Trigger Conditions");
			zGuidFindBoxColumnStyleInfo4.ColumnName = "TriggerConditions+TriggerCompany";
			zGuidFindBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo4.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("7040C9E2-B609-40E0-B603-18107AE53AC0", "Trigger Conditions");
			zDropEditColumnStyleInfo22.ColumnName = "P9_MilestoneCompletionPivotKey";
			zDropEditColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zDropEditColumnStyleInfo22.GroupName = Enterprise.MasterFiles.GUI.Res.GetData("955331e5-c651-46af-a2ad-5c57c0490dba", "Completion Milestone");
			zDropEditColumnStyleInfo22.IsVisible = false;
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.TasksGrid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.TasksGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.TasksGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.TasksGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zDateTimeOffsetEditColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo8);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zDateTimeOffsetEditColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo9);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo10);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo5);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo6);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo7);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zMultiControlColumnStyleInfo1);
			this.TasksGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo5);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo5);
			this.TasksGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo8);
			this.TasksGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo6);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo7);
			this.TasksGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo8);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo7);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.TasksGrid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.TasksGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo8);
			this.TasksGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo4);
			this.TasksGrid.ColumnStyles.Add(zDropEditColumnStyleInfo22);
			this.TasksGrid.Dock = System.Windows.Forms.DockStyle.Fill;
			this.TasksGrid.GridId = "ab091db7-aa57-4bcb-86c7-067438ae5fbb";
			this.TasksGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.TasksGrid.LayoutKey = "OpportunitiesGrid";
			this.TasksGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.TasksGrid.Name = "TasksGrid";
			this.TasksGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(736, 196, true);
			this.TasksGrid.TabIndex = 0;
			this.TasksGrid.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.TasksGrid_DoubleClick);
			// 
			// TasksHintSplitContainer
			// 
			this.TasksHintSplitContainer.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.TasksHintSplitContainer.IsSplitterFixed = true;
			this.TasksHintSplitContainer.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.TasksHintSplitContainer.Name = "TasksHintSplitContainer";
			this.TasksHintSplitContainer.Orientation = System.Windows.Forms.Orientation.Horizontal;
			// 
			// TasksHintSplitContainer.Panel1
			// 
			this.TasksHintSplitContainer.Panel1.Controls.Add(this.TasksHintLabel);
			this.TasksHintSplitContainer.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(736, 224, true);
			this.TasksHintSplitContainer.Panel1MinSize = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiY(20);
			// 
			// TasksHintSplitContainer.Panel2
			// 
			this.TasksHintSplitContainer.Panel2.Controls.Add(this.TasksGrid);
			this.TasksHintSplitContainer.SplitterDistance = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiY(24);
			this.TasksHintSplitContainer.TabIndex = 2;
			// 
			// TasksHintLabel
			// 
			this.TasksHintLabel.AutoSize = true;
			this.TasksHintLabel.FontType = ((Enterprise.ZArchitecture.Core.OFontTypes)((Enterprise.ZArchitecture.Core.OFontTypes.Normal | Enterprise.ZArchitecture.Core.OFontTypes.SansSerif)));
			this.TasksHintLabel.ForeColor = System.Drawing.Color.Blue;
			this.LabelCaptionRenderProvider.SetLabelCaptionVisible(this.TasksHintLabel, false);
			this.TasksHintLabel.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(3, 3, true);
			this.TasksHintLabel.Name = "TasksHintLabel";
			this.TasksHintLabel.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(0, 13, true);
			this.TasksHintLabel.TabIndex = 0;
			// 
			// TasksControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Controls.Add(this.TasksHintSplitContainer);
			this.Controls.Add(this.TasksTemplateLinkLabel);
			this.Name = "TasksControl";
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(736, 240, true);
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.TasksGrid)).EndInit();
			this.TasksGrid.ResumeLayout(false);
			this.TasksGrid.PerformLayout();
			this.TasksHintSplitContainer.Panel1.ResumeLayout(false);
			this.TasksHintSplitContainer.Panel1.PerformLayout();
			this.TasksHintSplitContainer.Panel2.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.TasksHintSplitContainer)).EndInit();
			this.TasksHintSplitContainer.ResumeLayout(false);
			this.TasksHintSplitContainer.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		#endregion

		internal protected Enterprise.ZArchitecture.GUI.ZLinkLabel TasksTemplateLinkLabel;
		protected internal Enterprise.ZArchitecture.ZGrid TasksGrid;
		private CargoWise.Windows.UI.KSplitContainer TasksHintSplitContainer;
		private Enterprise.ZArchitecture.ZLabel TasksHintLabel;

	}
}
