<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.BrandManager" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Services.Calendar\CargoWise.Services.Calendar.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>