using System.Diagnostics.CodeAnalysis;
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "Enterprise.BufferManagement.Integration.IProcessTaskTemplateWorkflowControl")]
[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "Enterprise.BufferManagement.Integration.IWorkflowDetailsUserControl")]
[assembly: SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "Enterprise.BufferManagement.Integration.IBMFilterRuleFilterBusinessObject")]
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BufferManagement.Integration.IEstimatable.EstimateHours")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\Workflow\IEstimatable.cs:4:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BufferManagement.Integration.IVisualBoardProvider.StartingRefreshIntervalInMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IVisualBoardProvider.cs:18:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BufferManagement.Integration.IWorkflow.PlannedDurationMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\Workflow\IWorkflow.cs:17:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BufferManagement.Integration.IBMSRegistry.TransferWorkflowComponentOnChangesWithinXMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\IBMSRegistry.cs:187:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BufferManagement.Integration.IBMSRegistry.AutoAssignCapabilityTasksOnChangesWithinXMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\IBMSRegistry.cs:215:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateBucket(Enterprise.BufferManagement.Integration.IBMSystem,System.String,System.Int32,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:14:88
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateTask(Enterprise.MasterFiles.Integration.IProcessTaskTemplate,Enterprise.BufferManagement.Integration.IProcessHeader,System.String,System.Int32,System.String,System.Decimal)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:30:108
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateTask(CargoWise.EntityFramework.BusinessObject,System.String,System.Int32,System.String,System.String,System.Nullable{System.Int32},System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:29:69
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateTask(Enterprise.BufferManagement.Integration.IProcessHeader,System.String,System.Int32,System.String,System.String,System.Nullable{System.Int32},System.String,System.Boolean,Enterprise.MasterFiles.Integration.IGlbCapability,Enterprise.Integration.IGlbGroup)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:28:74
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateTaskWithCompany(Enterprise.BufferManagement.Integration.IProcessHeader,System.String,System.Int32,System.String,System.String,System.Nullable{System.Int32},System.String,Enterprise.MasterFiles.Integration.IGlbCompany)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:31:85
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateWorkflowAndTask(CargoWise.EntityFramework.BusinessObjectFactory,System.String,Enterprise.BufferManagement.Integration.IBMComponent,System.Nullable{System.DateTime},System.String,System.Int32,System.String,System.Int32,System.Nullable{System.Int32},System.String,System.String,System.Nullable{System.Guid},System.Boolean)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:32:193
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BufferManagement.Integration.IBMTestHelper.CreateBuffer(Enterprise.BufferManagement.Integration.IBMSystem,System.String,System.Int32,System.Byte,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\BufferManagement\Main\Integration\VisualBoard\IBMTestHelper.cs:15:70
