
using Enterprise.ZArchitecture.Core;

namespace Enterprise.Customs.AU.Declaration.Business
{
	public class CodeDescriptionPairListCustomsCountryCode : CodeDescriptionPairList
	{
		public CodeDescriptionPairListCustomsCountryCode()
		{
			AddPair("AFGH", "Afghanistan");
			AddPair("ALBA", "Albania");
			AddPair("ALGR", "Algeria");
			AddPair("ANGO", "Angola");
			AddPair("ANGA", "Anguilla");
			AddPair("AGUA", "Antigua & Barbuda (With Rodonda)");
			AddPair("ARGE", "Argentina");
			AddPair("ARMN", "Armenia");
			AddPair("AUST", "Australia");
			AddPair("ANCA", "Australian Antarctic Territory");
			AddPair("AFZ", "Australian Fishing Zone");
			AddPair("ASTA", "Austria");
			AddPair("AZBJ", "Azerbaijan");
			AddPair("BAHA", "Bahamas");
			AddPair("BHRN", "Bahrain");
			AddPair("BADE", "Bangladesh");
			AddPair("BARB", "Barbados");
			AddPair("BELA", "Belarus");
			AddPair("BLGM", "Belgium-Luxembourg");
			AddPair("BELE", "Belize");
			AddPair("BENR", "Benin, People's Republic of ");
			AddPair("BMDA", "Bermuda");
			AddPair("BHUT", "Bhutan");
			AddPair("BOLI", "Bolivia");
			AddPair("BOHR", "Bosnia & Herzegovina");
			AddPair("BOTS", "Botswana");
			AddPair("BRAZ", "Brazil");
			AddPair("BIOT", "British Indian Ocean Territory");
			AddPair("BRUN", "Brunei Darussalam");
			AddPair("BULG", "Bulgaria");
			AddPair("BURK", "Burkina Faso");
			AddPair("BI", "Burundi BRND ");
			AddPair("CMBD", "Cambodia");
			AddPair("FCAM", "Cameroon");
			AddPair("CAN", "Canada");
			AddPair("CVER", "Cape Verde");
			AddPair("CAYM", "Cayman Islands");
			AddPair("CEAR", "Central African Republic");
			AddPair("CHAD", "Chad");
			AddPair("CHLE", "Chile");
			AddPair("CHIN", "China, People's Republic of");
			AddPair("CHRI", "Christmas Island");
			AddPair("COCO", "Cocos Islands");
			AddPair("COMB", "Colombia");
			AddPair("CMRO", "Comoros");
			AddPair("COBR", "Congo");
			AddPair("COOK", "Cook Islands");
			AddPair("COST", "Costa Rica");
			AddPair("IVOR", "Cote D'Ivoire");
			AddPair("CROA", "Croatia");
			AddPair("CUBA", "Cuba");
			AddPair("CYPR", "Cyprus");
			AddPair("CZEC", "Czech & Slovak Federal Republic");
			AddPair("CZEH", "Czech Republic");
			AddPair("DENM", "Denmark");
			AddPair("DJIB", "Djibouti");
			AddPair("DMCA", "Dominica");
			AddPair("DOMI", "Dominican Republic");
			AddPair("ECUA", "Ecuador");
			AddPair("EGYP", "Egypt");
			AddPair("SALV", "El Salvador");
			AddPair("EGUI", "Equatorial Guinea");
			AddPair("ERIT", "Eritrea");
			AddPair("ESTO", "Estonia");
			AddPair("ETHI", "Ethiopia");
			AddPair("FALK", "Falkland Islands");
			AddPair("FIJI", "Fiji");
			AddPair("FINL", "Finland");
			AddPair("FYRM", "Former Yugoslav Republic of Macedonia");
			AddPair("FRAN", "France");
			AddPair("FSAT", "French Southern & Antarctic Territories");
			AddPair("GABO", "Gabon");
			AddPair("GAMB", "Gambia");
			AddPair("GERG", "Georgia");
			AddPair("FGMY", "Germany, Federal Republic of");
			AddPair("GHAN", "Ghana");
			AddPair("GIBR", "Gibraltar");
			AddPair("GREE", "Greece");
			AddPair("GNDA", "Grenada");
			AddPair("GUAM", "Guam");
			AddPair("GMLA", "Guatemala");
			AddPair("FRGU", "Guiana (Fr.)");
			AddPair("GUIN", "Guinea");
			AddPair("BGUI", "Guinea - Bissau");
			AddPair("GUYA", "Guyana");
			AddPair("HAIT", "Haiti");
			AddPair("HDRS", "Honduras");
			AddPair("HONG", "Hong Kong");
			AddPair("HGRY", "Hungary");
			AddPair("ICEL", "Iceland");
			AddPair("INIA", "India");
			AddPair("INDO", "Indonesia");
			AddPair("PSIA", "Iran");
			AddPair("IRAQ", "Iraq");
			AddPair("IRE", "Ireland");
			AddPair("ISRA", "Israel");
			AddPair("ITAL", "Italy");
			AddPair("JMCA", "Jamaica");
			AddPair("JAP", "Japan");
			AddPair("JSIS", "Johnston Island");
			AddPair("JORD", "Jordan");
			AddPair("KAZA", "Kazakhstan");
			AddPair("KENY", "Kenya");
			AddPair("KIRI", "Kiribati");
			AddPair("KRDR", "Korea, Democratic People's Republic of");
			AddPair("RKOR", "Korea, Republic OF");
			AddPair("KUWA", "Kuwait");
			AddPair("KYRG", "Kyrgyztan");
			AddPair("LAOS", "Lao, People's Democratic Republic of");
			AddPair("LATV", "Latvia");
			AddPair("LEBA", "Lebanon");
			AddPair("LESO", "Lesotho");
			AddPair("LIBE", "Liberia");
			AddPair("LBYA", "Libyan Arab Jamahiriya");
			AddPair("LITH", "Lithuania");
			AddPair("MACA", "Macao");
			AddPair("MASY", "Madagascar");
			AddPair("MLWI", "Malawi");
			AddPair("MLAY", "Malaysia");
			AddPair("MLDV", "Maldives");
			AddPair("MALI", "Mali");
			AddPair("MLTA", "Malta");
			AddPair("MRNS", "Mariana Islands Republic of");
			AddPair("MARS", "Marshall Islands, Republic of");
			AddPair("MRTN", "Mauritania");
			AddPair("MAUS", "Mauritius");
			AddPair("MEXI", "Mexico");
			AddPair("MICR", "Micronesia, Federated States of");
			AddPair("MIDW", "Midway Islands");
			AddPair("MDOV", "Moldova");
			AddPair("MNGL", "Mongolia");
			AddPair("MTRO", "Montenegro");
			AddPair("MONT", "Montserrat");
			AddPair("MORO", "Morocco");
			AddPair("MOZA", "Mozambique");
			AddPair("BURM", "Myanmar, Union of");
			AddPair("NAMI", "Namibia");
			AddPair("NAUR", "Nauru");
			AddPair("NEPA", "Nepal");
			AddPair("NETH", "Netherlands");
			AddPair("ANTI", "Antigua and Barbuda");
			AddPair("NCAL", "New Caledonia");
			AddPair("NZ", "New Zealand");
			AddPair("NICA", "Nicaragua");
			AddPair("NIGE", "Niger");
			AddPair("NGRA", "Nigeria");
			AddPair("NIUE", "Niue");
			AddPair("NORF", "Norfolk Island");
			AddPair("NWAY", "Norway");
			AddPair("OMAN", "Oman");
			AddPair("PAKI", "Pakistan");
			AddPair("PALU", "Palau");
			AddPair("PNMA", "Panama");
			AddPair("PNG", "Papua New Guinea");
			AddPair("PRGY", "Paraguay");
			AddPair("PERU", "Peru");
			AddPair("PHIL", "Philippines");
			AddPair("PITC", "Pitcairn Island");
			AddPair("POLA", "Poland");
			AddPair("PLYN", "Polynesia (Fr.)");
			AddPair("PORT", "Portugal");
			AddPair("RICO", "Puerto Rico");
			AddPair("QATA", "Qatar");
			AddPair("REUN", "Reunion (Fr.)");
			AddPair("ROUM", "Romania");
			AddPair("ROSS", "Ross Dependency");
			AddPair("RUSS", "Russian Federation");
			AddPair("RWAN", "Rwanda");
			AddPair("SAMO", "Samoa (American)");
			AddPair("SAOT", "Sao Tome & Principe");
			AddPair("SAUD", "Saudi Arabia");
			AddPair("SENE", "Senegal");
			AddPair("SEYC", "Seychelles");
			AddPair("SLEO", "Sierra Leone");
			AddPair("SING", "Singapore");
			AddPair("SVAK", "Slovak Republic");
			AddPair("SLOV", "Slovenia");
			AddPair("SOLO", "Solomon Islands");
			AddPair("SOML", "Somalia");
			AddPair("SAFR", "South Africa");
			AddPair("SPAI", "Spain");
			AddPair("SRIL", "Sri Lanka");
			AddPair("STCN", "St Christopher & Nevis");
			AddPair("STHE", "St Helena");
			AddPair("STCH", "St Kitts-Nevis");
			AddPair("STLU", "St Lucia");
			AddPair("PIER", "St Pierre & Miquelon");
			AddPair("STVI", "St Vincent & Grenadines");
			AddPair("SUDA", "Sudan");
			AddPair("SRNM", "Suriname");
			AddPair("SWZI", "Swaziland");
			AddPair("SWED", "Sweden");
			AddPair("SWIT", "Switzerland");
			AddPair("SYRI", "Syrian Arab Republic");
			AddPair("TAIW", "Taiwan Province");
			AddPair("TAJI", "Tajikistan");
			AddPair("TANZ", "Tanzania");
			AddPair("THAI", "Thailand");
			AddPair("TOGO", "Togo");
			AddPair("TOKI", "Tokelau Islands");
			AddPair("TNGA", "Tonga");
			AddPair("TRIN", "Trinidad & Tobago");
			AddPair("TTPI", "Trust Territory of Pacific Islands");
			AddPair("TUNI", "Tunisia");
			AddPair("TURK", "Turkey");
			AddPair("TURS", "Turkmenistan");
			AddPair("TRCA", "Turks and Caicos Islands");
			AddPair("TUVA", "Tuvalu");
			AddPair("UGAN", "Uganda");
			AddPair("UKRA", "Ukraine");
			AddPair("UAEM", "United Arab");
			AddPair("UK", "United Kingdom");
			AddPair("USA", "U.S.A.");
			AddPair("OAPI", "U.S.A. Pacific Islands");
			AddPair("URUG", "Uruguay");
			AddPair("UZBK", "Uzbekistan");
			AddPair("VANU", "Vanuatu");
			AddPair("VENZ", "Venezuela");
			AddPair("VIET", "Vietnam, Socialist Republic of");
			AddPair("VIRG", "Virgin Islands (American)");
			AddPair("BVIR", "Virgin Islands (Br.)");
			AddPair("WAKE", "Wake Island");
			AddPair("WALL", "Wallis & Futuna Islands");
			AddPair("SARA", "Western Sahara");
			AddPair("WSAM", "Western Samoa");
			AddPair("FWIN", "West Indies (Fr.)");
			AddPair("ARYE", "Yemen, Republic of");
			AddPair("YUGO", "Yugoslavia");
			AddPair("ZAIR", "Zaire");
			AddPair("ZMBA", "Zambia");
			AddPair("ZIMB", "Zimbabwe");
			AddPair("UNKN ", "Unknown");
			AddPair("ORDR ", "Goods Exported \"For Orders\"");
			AddPair("OILS ", "Blended Oil");
		}
	}
}
