<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Win32.SystemEvents" />
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ActiveDirectory" />
    <Reference Include="CargoWise.ActiveDirectory.TestFramework" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing"  />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core.Encryption" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.Security.ActiveDirectory.ServiceTasks\Enterprise.Security.ActiveDirectory.ServiceTasks.csproj" />
    <ProjectReference Include="..\ActiveDirectory.Business\Enterprise.Security.ActiveDirectory.csproj" />
    <ProjectReference Include="..\ActiveDirectory.Testing\Enterprise.Security.ActiveDirectory.Test.csproj" />
  </ItemGroup>
</Project>