//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoCusSCAOceanBillValidation : ZValidation
	{
		protected AutoCusSCAOceanBillValidation(AutoCusSCAOceanBill Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoCusSCAOceanBillValidation); }
		}

		/// <summary>
		/// Add more validation to the CusSCAOceanBill's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoCusSCAOceanBillValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The CusSCAOceanBill's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoCusSCAOceanBillValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region CB_ApplicationCode

		public void ValidateCB_ApplicationCode()
		{
			ZValidationInternals.Validate(Parent.CB_ApplicationCodeInfo, GetCB_ApplicationCodeValidationInvoker());
		}

		RunValidationInvoker GetCB_ApplicationCodeValidationInvoker()
		{
			return delegate
			{
				CheckCB_ApplicationCodeIsWesternEuropean();
				CheckCB_ApplicationCode();
			};
		}

		protected virtual void CheckCB_ApplicationCodeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_ApplicationCodeInfo);
		}

		protected virtual void CheckCB_ApplicationCode()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_CustomsEntryNum

		public void ValidateCB_CustomsEntryNum()
		{
			ZValidationInternals.Validate(Parent.CB_CustomsEntryNumInfo, GetCB_CustomsEntryNumValidationInvoker());
		}

		RunValidationInvoker GetCB_CustomsEntryNumValidationInvoker()
		{
			return delegate
			{
				CheckCB_CustomsEntryNumIsWesternEuropean();
				CheckCB_CustomsEntryNum();
			};
		}

		protected virtual void CheckCB_CustomsEntryNumIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_CustomsEntryNumInfo);
		}

		protected virtual void CheckCB_CustomsEntryNum()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_CustomsStatus

		public void ValidateCB_CustomsStatus()
		{
			ZValidationInternals.Validate(Parent.CB_CustomsStatusInfo, GetCB_CustomsStatusValidationInvoker());
		}

		RunValidationInvoker GetCB_CustomsStatusValidationInvoker()
		{
			return delegate
			{
				CheckCB_CustomsStatusIsWesternEuropean();
				CheckCB_CustomsStatus();
			};
		}

		protected virtual void CheckCB_CustomsStatusIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_CustomsStatusInfo);
		}

		protected virtual void CheckCB_CustomsStatus()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_DateOfArrival

		public void ValidateCB_DateOfArrival()
		{
			ZValidationInternals.Validate(Parent.CB_DateOfArrivalInfo, GetCB_DateOfArrivalValidationInvoker());
		}

		RunValidationInvoker GetCB_DateOfArrivalValidationInvoker()
		{
			return delegate
			{
				CheckCB_DateOfArrivalIsValidZDateTime();
				CheckCB_DateOfArrivalIsValidZDateTimeRange();
				CheckCB_DateOfArrival();
			};
		}

		protected virtual void CheckCB_DateOfArrivalIsValidZDateTime()
		{
			TypeValidation.CheckValidSmallDateTime(Parent.CB_DateOfArrivalInfo);
		}

		protected virtual void CheckCB_DateOfArrivalIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.CB_DateOfArrivalInfo);
		}

		protected virtual void CheckCB_DateOfArrival()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_DateOfDeparture

		public void ValidateCB_DateOfDeparture()
		{
			ZValidationInternals.Validate(Parent.CB_DateOfDepartureInfo, GetCB_DateOfDepartureValidationInvoker());
		}

		RunValidationInvoker GetCB_DateOfDepartureValidationInvoker()
		{
			return delegate
			{
				CheckCB_DateOfDepartureIsValidZDateTime();
				CheckCB_DateOfDepartureIsValidZDateTimeRange();
				CheckCB_DateOfDeparture();
			};
		}

		protected virtual void CheckCB_DateOfDepartureIsValidZDateTime()
		{
			TypeValidation.CheckValidSmallDateTime(Parent.CB_DateOfDepartureInfo);
		}

		protected virtual void CheckCB_DateOfDepartureIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.CB_DateOfDepartureInfo);
		}

		protected virtual void CheckCB_DateOfDeparture()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_DateOfFirstArrival

		public void ValidateCB_DateOfFirstArrival()
		{
			ZValidationInternals.Validate(Parent.CB_DateOfFirstArrivalInfo, GetCB_DateOfFirstArrivalValidationInvoker());
		}

		RunValidationInvoker GetCB_DateOfFirstArrivalValidationInvoker()
		{
			return delegate
			{
				CheckCB_DateOfFirstArrivalIsValidZDateTime();
				CheckCB_DateOfFirstArrivalIsValidZDateTimeRange();
				CheckCB_DateOfFirstArrival();
			};
		}

		protected virtual void CheckCB_DateOfFirstArrivalIsValidZDateTime()
		{
			TypeValidation.CheckValidSmallDateTime(Parent.CB_DateOfFirstArrivalInfo);
		}

		protected virtual void CheckCB_DateOfFirstArrivalIsValidZDateTimeRange()
		{
			TypeValidation.CheckValidZDateTimeRange(Parent.CB_DateOfFirstArrivalInfo);
		}

		protected virtual void CheckCB_DateOfFirstArrival()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_GB

		public void ValidateCB_GB()
		{
			ZValidationInternals.Validate(Parent.CB_GBInfo, GetCB_GBValidationInvoker());
		}

		RunValidationInvoker GetCB_GBValidationInvoker()
		{
			return delegate
			{
				CheckCB_GBIsValidZGuid();
				CheckCB_GB();
			};
		}

		protected virtual void CheckCB_GBIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CB_GBInfo);
		}

		protected virtual void CheckCB_GB()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_IsActive

		public void ValidateCB_IsActive()
		{
			ZValidationInternals.Validate(Parent.CB_IsActiveInfo, GetCB_IsActiveValidationInvoker());
		}

		RunValidationInvoker GetCB_IsActiveValidationInvoker()
		{
			return delegate
			{
				CheckCB_IsActive();
			};
		}

		protected virtual void CheckCB_IsActive()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_IsBureau

		public void ValidateCB_IsBureau()
		{
			ZValidationInternals.Validate(Parent.CB_IsBureauInfo, GetCB_IsBureauValidationInvoker());
		}

		RunValidationInvoker GetCB_IsBureauValidationInvoker()
		{
			return delegate
			{
				CheckCB_IsBureau();
			};
		}

		protected virtual void CheckCB_IsBureau()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_IsCarrierCargoReport

		public void ValidateCB_IsCarrierCargoReport()
		{
			ZValidationInternals.Validate(Parent.CB_IsCarrierCargoReportInfo, GetCB_IsCarrierCargoReportValidationInvoker());
		}

		RunValidationInvoker GetCB_IsCarrierCargoReportValidationInvoker()
		{
			return delegate
			{
				CheckCB_IsCarrierCargoReport();
			};
		}

		protected virtual void CheckCB_IsCarrierCargoReport()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_LloydsIMO

		public void ValidateCB_LloydsIMO()
		{
			ZValidationInternals.Validate(Parent.CB_LloydsIMOInfo, GetCB_LloydsIMOValidationInvoker());
		}

		RunValidationInvoker GetCB_LloydsIMOValidationInvoker()
		{
			return delegate
			{
				CheckCB_LloydsIMOIsWesternEuropean();
				CheckCB_LloydsIMO();
			};
		}

		protected virtual void CheckCB_LloydsIMOIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_LloydsIMOInfo);
		}

		protected virtual void CheckCB_LloydsIMO()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_MasterHouseBill

		public void ValidateCB_MasterHouseBill()
		{
			ZValidationInternals.Validate(Parent.CB_MasterHouseBillInfo, GetCB_MasterHouseBillValidationInvoker());
		}

		RunValidationInvoker GetCB_MasterHouseBillValidationInvoker()
		{
			return delegate
			{
				CheckCB_MasterHouseBillIsWesternEuropean();
				CheckCB_MasterHouseBill();
			};
		}

		protected virtual void CheckCB_MasterHouseBillIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_MasterHouseBillInfo);
		}

		protected virtual void CheckCB_MasterHouseBill()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_MessageReference

		public void ValidateCB_MessageReference()
		{
			ZValidationInternals.Validate(Parent.CB_MessageReferenceInfo, GetCB_MessageReferenceValidationInvoker());
		}

		RunValidationInvoker GetCB_MessageReferenceValidationInvoker()
		{
			return delegate
			{
				CheckCB_MessageReferenceIsWesternEuropean();
				CheckCB_MessageReference();
			};
		}

		protected virtual void CheckCB_MessageReferenceIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_MessageReferenceInfo);
		}

		protected virtual void CheckCB_MessageReference()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_MessageStatus

		public void ValidateCB_MessageStatus()
		{
			ZValidationInternals.Validate(Parent.CB_MessageStatusInfo, GetCB_MessageStatusValidationInvoker());
		}

		RunValidationInvoker GetCB_MessageStatusValidationInvoker()
		{
			return delegate
			{
				CheckCB_MessageStatusIsWesternEuropean();
				CheckCB_MessageStatus();
			};
		}

		protected virtual void CheckCB_MessageStatusIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_MessageStatusInfo);
		}

		protected virtual void CheckCB_MessageStatus()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_MultiOBLUnpack

		public void ValidateCB_MultiOBLUnpack()
		{
			ZValidationInternals.Validate(Parent.CB_MultiOBLUnpackInfo, GetCB_MultiOBLUnpackValidationInvoker());
		}

		RunValidationInvoker GetCB_MultiOBLUnpackValidationInvoker()
		{
			return delegate
			{
				CheckCB_MultiOBLUnpack();
			};
		}

		protected virtual void CheckCB_MultiOBLUnpack()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_OA_GoodsLocation

		public void ValidateCB_OA_GoodsLocation()
		{
			ZValidationInternals.Validate(Parent.CB_OA_GoodsLocationInfo, GetCB_OA_GoodsLocationValidationInvoker());
		}

		RunValidationInvoker GetCB_OA_GoodsLocationValidationInvoker()
		{
			return delegate
			{
				CheckCB_OA_GoodsLocationIsValidZGuid();
				CheckCB_OA_GoodsLocation();
			};
		}

		protected virtual void CheckCB_OA_GoodsLocationIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CB_OA_GoodsLocationInfo);
		}

		protected virtual void CheckCB_OA_GoodsLocation()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_OA_UnpackDepotAddress

		public void ValidateCB_OA_UnpackDepotAddress()
		{
			ZValidationInternals.Validate(Parent.CB_OA_UnpackDepotAddressInfo, GetCB_OA_UnpackDepotAddressValidationInvoker());
		}

		RunValidationInvoker GetCB_OA_UnpackDepotAddressValidationInvoker()
		{
			return delegate
			{
				CheckCB_OA_UnpackDepotAddressIsValidZGuid();
				CheckCB_OA_UnpackDepotAddress();
			};
		}

		protected virtual void CheckCB_OA_UnpackDepotAddressIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CB_OA_UnpackDepotAddressInfo);
		}

		protected virtual void CheckCB_OA_UnpackDepotAddress()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_OceanBill

		public void ValidateCB_OceanBill()
		{
			ZValidationInternals.Validate(Parent.CB_OceanBillInfo, GetCB_OceanBillValidationInvoker());
		}

		RunValidationInvoker GetCB_OceanBillValidationInvoker()
		{
			return delegate
			{
				CheckCB_OceanBillIsWesternEuropean();
				CheckCB_OceanBill();
			};
		}

		protected virtual void CheckCB_OceanBillIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_OceanBillInfo);
		}

		protected virtual void CheckCB_OceanBill()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_OH_ShippingLine

		public void ValidateCB_OH_ShippingLine()
		{
			ZValidationInternals.Validate(Parent.CB_OH_ShippingLineInfo, GetCB_OH_ShippingLineValidationInvoker());
		}

		RunValidationInvoker GetCB_OH_ShippingLineValidationInvoker()
		{
			return delegate
			{
				CheckCB_OH_ShippingLineIsValidZGuid();
				CheckCB_OH_ShippingLine();
			};
		}

		protected virtual void CheckCB_OH_ShippingLineIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CB_OH_ShippingLineInfo);
		}

		protected virtual void CheckCB_OH_ShippingLine()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_ParentId

		public void ValidateCB_ParentId()
		{
			ZValidationInternals.Validate(Parent.CB_ParentIdInfo, GetCB_ParentIdValidationInvoker());
		}

		RunValidationInvoker GetCB_ParentIdValidationInvoker()
		{
			return delegate
			{
				CheckCB_ParentIdIsValidZGuid();
				CheckCB_ParentId();
			};
		}

		protected virtual void CheckCB_ParentIdIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CB_ParentIdInfo);
		}

		protected virtual void CheckCB_ParentId()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_ParentTableCode

		public void ValidateCB_ParentTableCode()
		{
			ZValidationInternals.Validate(Parent.CB_ParentTableCodeInfo, GetCB_ParentTableCodeValidationInvoker());
		}

		RunValidationInvoker GetCB_ParentTableCodeValidationInvoker()
		{
			return delegate
			{
				CheckCB_ParentTableCodeIsWesternEuropean();
				CheckCB_ParentTableCode();
			};
		}

		protected virtual void CheckCB_ParentTableCodeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_ParentTableCodeInfo);
		}

		protected virtual void CheckCB_ParentTableCode()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_PrincipalID

		public void ValidateCB_PrincipalID()
		{
			ZValidationInternals.Validate(Parent.CB_PrincipalIDInfo, GetCB_PrincipalIDValidationInvoker());
		}

		RunValidationInvoker GetCB_PrincipalIDValidationInvoker()
		{
			return delegate
			{
				CheckCB_PrincipalIDIsWesternEuropean();
				CheckCB_PrincipalID();
			};
		}

		protected virtual void CheckCB_PrincipalIDIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_PrincipalIDInfo);
		}

		protected virtual void CheckCB_PrincipalID()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_ResponsiblePartyID

		public void ValidateCB_ResponsiblePartyID()
		{
			ZValidationInternals.Validate(Parent.CB_ResponsiblePartyIDInfo, GetCB_ResponsiblePartyIDValidationInvoker());
		}

		RunValidationInvoker GetCB_ResponsiblePartyIDValidationInvoker()
		{
			return delegate
			{
				CheckCB_ResponsiblePartyIDIsWesternEuropean();
				CheckCB_ResponsiblePartyID();
			};
		}

		protected virtual void CheckCB_ResponsiblePartyIDIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_ResponsiblePartyIDInfo);
		}

		protected virtual void CheckCB_ResponsiblePartyID()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_RL_NKPortOfDischarge

		public void ValidateCB_RL_NKPortOfDischarge()
		{
			ZValidationInternals.Validate(Parent.CB_RL_NKPortOfDischargeInfo, GetCB_RL_NKPortOfDischargeValidationInvoker());
		}

		RunValidationInvoker GetCB_RL_NKPortOfDischargeValidationInvoker()
		{
			return delegate
			{
				CheckCB_RL_NKPortOfDischargeIsWesternEuropean();
				CheckCB_RL_NKPortOfDischarge();
			};
		}

		protected virtual void CheckCB_RL_NKPortOfDischargeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_RL_NKPortOfDischargeInfo);
		}

		protected virtual void CheckCB_RL_NKPortOfDischarge()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_RL_NKPortOfFirstArrival

		public void ValidateCB_RL_NKPortOfFirstArrival()
		{
			ZValidationInternals.Validate(Parent.CB_RL_NKPortOfFirstArrivalInfo, GetCB_RL_NKPortOfFirstArrivalValidationInvoker());
		}

		RunValidationInvoker GetCB_RL_NKPortOfFirstArrivalValidationInvoker()
		{
			return delegate
			{
				CheckCB_RL_NKPortOfFirstArrivalIsWesternEuropean();
				CheckCB_RL_NKPortOfFirstArrival();
			};
		}

		protected virtual void CheckCB_RL_NKPortOfFirstArrivalIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_RL_NKPortOfFirstArrivalInfo);
		}

		protected virtual void CheckCB_RL_NKPortOfFirstArrival()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_RL_NKPortOfLoading

		public void ValidateCB_RL_NKPortOfLoading()
		{
			ZValidationInternals.Validate(Parent.CB_RL_NKPortOfLoadingInfo, GetCB_RL_NKPortOfLoadingValidationInvoker());
		}

		RunValidationInvoker GetCB_RL_NKPortOfLoadingValidationInvoker()
		{
			return delegate
			{
				CheckCB_RL_NKPortOfLoadingIsWesternEuropean();
				CheckCB_RL_NKPortOfLoading();
			};
		}

		protected virtual void CheckCB_RL_NKPortOfLoadingIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_RL_NKPortOfLoadingInfo);
		}

		protected virtual void CheckCB_RL_NKPortOfLoading()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_VesselName

		public void ValidateCB_VesselName()
		{
			ZValidationInternals.Validate(Parent.CB_VesselNameInfo, GetCB_VesselNameValidationInvoker());
		}

		RunValidationInvoker GetCB_VesselNameValidationInvoker()
		{
			return delegate
			{
				CheckCB_VesselNameIsWesternEuropean();
				CheckCB_VesselName();
			};
		}

		protected virtual void CheckCB_VesselNameIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_VesselNameInfo);
		}

		protected virtual void CheckCB_VesselName()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CB_Voyage

		public void ValidateCB_Voyage()
		{
			ZValidationInternals.Validate(Parent.CB_VoyageInfo, GetCB_VoyageValidationInvoker());
		}

		RunValidationInvoker GetCB_VoyageValidationInvoker()
		{
			return delegate
			{
				CheckCB_VoyageIsWesternEuropean();
				CheckCB_Voyage();
			};
		}

		protected virtual void CheckCB_VoyageIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CB_VoyageInfo);
		}

		protected virtual void CheckCB_Voyage()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateCB_ApplicationCode();
				ValidateCB_CustomsEntryNum();
				ValidateCB_CustomsStatus();
				ValidateCB_DateOfArrival();
				ValidateCB_DateOfDeparture();
				ValidateCB_DateOfFirstArrival();
				ValidateCB_GB();
				ValidateCB_IsActive();
				ValidateCB_IsBureau();
				ValidateCB_IsCarrierCargoReport();
				ValidateCB_LloydsIMO();
				ValidateCB_MasterHouseBill();
				ValidateCB_MessageReference();
				ValidateCB_MessageStatus();
				ValidateCB_MultiOBLUnpack();
				ValidateCB_OA_GoodsLocation();
				ValidateCB_OA_UnpackDepotAddress();
				ValidateCB_OceanBill();
				ValidateCB_OH_ShippingLine();
				ValidateCB_ParentId();
				ValidateCB_ParentTableCode();
				ValidateCB_PrincipalID();
				ValidateCB_ResponsiblePartyID();
				ValidateCB_RL_NKPortOfDischarge();
				ValidateCB_RL_NKPortOfFirstArrival();
				ValidateCB_RL_NKPortOfLoading();
				ValidateCB_VesselName();
				ValidateCB_Voyage();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoCusSCAOceanBill Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
