<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.DbUpgrader.Data.GlbReleaseNote</AssemblyName>
    <RootNamespace>Enterprise.DbUpgrader.Data.GlbReleaseNote</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>