<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >
  <PropertyGroup>
    <Company>WiseTech Global Pty Ltd</Company>
    <Product>DMS USC</Product>
    <Copyright>© Copyright WiseTech Global</Copyright>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <AssemblyFileVersion>0.1.0.0</AssemblyFileVersion>
    <Deterministic>true</Deterministic>
    <BaseOutputPath>..\Bin\Build\$(MSBuildProjectName)</BaseOutputPath>
  </PropertyGroup>
</Project>