<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <_ProfilePropsImported>$true</_ProfilePropsImported>
    <_Server>SYDWP-SEWG-2.wisecloud.zone</_Server>
    <_SiteName>ehubgateway.wisegrid.net</_SiteName>
    <_AppPoolName>$(_SiteName)</_AppPoolName>
    <UserName>ewgadmin</UserName>
    <Password>KmqLJkDe0+Nl4dlNdN0fVe7gQqr0O0pT6SMpQxaSbwRIrreVIGd0WxY4vmLPkHxdMWx/rfa0SxoSLyhuQiIsaaRE+ajsIT8yEU1NbiM4YuscodFRfSkCIxZ/F9dYVVUcb3mD9s0dS59iMvq2Ba5396lVsE6q2+N/LieqBa7BFPQ=</Password>
  </PropertyGroup>
  <ItemGroup>
    <_Binding Include="1_Override">
      <Port>80</Port>
      <Protocol>http</Protocol>
    </_Binding>
  </ItemGroup>
</Project>