<Project>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Common.ModuleRegistration" />
    <Reference Include="Enterprise.Customs.GUI" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.Module" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.Universal.GUI" />
    <Reference Include="Enterprise.DeniedPartyScreening.GUI" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentVisualizer.GUI" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.GUI" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.GUI" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.MasterFiles.Module" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.GUI" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Registry.GUI" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.ZA.Business.csproj" />
  </ItemGroup>
</Project>