<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.IE.ExitControl.GUI</AssemblyName>
    <RootNamespace>Enterprise.Customs.IE.ExitControl.GUI</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>