<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(CWNetCoreTargetFramework)</TargetFramework>
  </PropertyGroup>
  <!--NOTE: If you need to add a new reference, please add it to the TestProject.CommonReferences.props file.-->
  <Import Project="../TestProject.CommonReferences.props" />
  <!--Below section is for .NET Core references only-->
  <ItemGroup>
    <Reference Include="CargoWise.BrandManager" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceHost.NetCore\Enterprise.Services.ServiceHost.NetCore.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="ServiceHost.Tests.Migration.props" />
</Project>
