<Project>
  <ItemGroup>
    <Compile Include="..\ServiceHost.Tests\WebAPI\Controllers\Dummy\*.cs">
      <Link>WebAPI\Controllers\Dummy\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost.Tests\WebAPI\Controllers\Accounting\**\*.cs">
      <Link>WebAPI\Controllers\Accounting\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost.Tests\WebAPI\Controllers\Customs\*.cs">
      <Link>WebAPI\Controllers\Customs\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost.Tests\WebAPI\Controllers\SecurityRight\*.cs">
      <Link>WebAPI\Controllers\SecurityRight\%(Filename)%(Extension)</Link>
    </Compile>
    <!--Region Helpers-->
    <Compile Include="..\ServiceHost\Migration\Helpers\*">
      <Link>WebAPI\ServiceHost\Migration\Helpers\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost\Migration\*">
      <Link>ServiceHost\Migration\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost.Tests\Migration\Helpers\*">
      <Link>Migration\Helpers\%(Filename)%(Extension)</Link>
    </Compile>
    <Compile Include="..\ServiceHost.Tests\WebAPI\Controllers\HttpActionResultAssertions.cs">
      <Link>WebAPI\%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

  <PropertyGroup>
    <ServiceHostRoot>$([System.String]::Copy('$(MSBuildThisFileDirectory)').Replace('.NetCore', ''))</ServiceHostRoot>
  </PropertyGroup>

  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\CarrierShipmentHeader\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Contracts\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Devices\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\BusinessIntelligence\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Contact\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\CRM\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Documents\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\CustomsMessaging\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\DangerousGoods\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\DocumentVisualizer\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Edocs\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\eTail\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Freight\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Incidents\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Notes\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\OrderManager\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\PasswordReset\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Pave\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Rating\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Report\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\SecurityCheckpoint\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\ShipamaxIntegration\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\System\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\TransportBooking\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Universal\Migration.props" />
  <Import Project="..\ServiceHost.Tests\HttpXmlServices\Controllers\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\WebTracker\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Workflow\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\Warehouse\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\CarbonEmissions\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\GateManagement\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\GlbStaffEmailAddress\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\LandTransport\Migration.props" />
  <Import Project="..\ServiceHost.Tests\WebAPI\Controllers\ShipperTMS\Migration.props" />
</Project>