<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Richard White (Eagle Datamation International) -->
<xs:schema targetNamespace="http://www.edi.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.edi.com.au/EnterpriseService/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="Elements.xsd"/>
	<xs:element name="ChargeCodes">
		<xs:annotation>
			<xs:documentation>Charge Codes collection</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ChargeCode" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Code" type="xs:string"/>
							<xs:element name="Description" type="xs:string"/>
							<xs:element name="DepartmentFilterList" type="xs:string"/>
							<xs:element name="ChargeType" type="xs:string"/>
							<xs:element name="MarginPercentage" type="xs:string"/>
							<xs:element name="GSTRate" type="xs:string"/>
							<xs:element name="WithholdingTaxRate" type="xs:string"/>
							<xs:element name="SalesGroup" type="xs:string" minOccurs="0"/>
							<xs:element name="ExpenseGroup" type="xs:string"/>
							<xs:element name="RevenueAccount" type="xs:string"/>
							<xs:element name="WIPAccount" type="xs:string"/>
							<xs:element name="CostAccount" type="xs:string"/>
							<xs:element name="AccrualAccount" type="xs:string"/>
							<xs:element name="ChargeGroup" type="xs:string"/>
							<xs:element name="IsGroupageCharge" type="xs:string" default='"N"'/>
							<xs:element name="SubGroup" type="xs:string" minOccurs="0"/>
							<xs:element name="RateCalculator" type="xs:string" default='""'/>
							<xs:element name="ShowOnQuotation" type="xs:string" default='"Y"'/>
							<xs:element name="SuppressOnQuoteIfZero" type="xs:string" default='"N"'/>
							<xs:element name="IATA_ChargeCodeMap" type="xs:string" default='""'/>
							<xs:element name="IsGlobal" type="xs:string" default='"N"'/>
							<xs:element name="GovtChargeCode" type="xs:string" default='""'/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
