<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.edi.com.au/EnterpriseService/" xmlns="http://www.edi.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:complexType name="ConversationMessage">
    <xs:sequence>
      <xs:element name="UserCode" type="xs:string" />
      <xs:element name="UserName" type="xs:string" />
      <xs:element name="Body" type="xs:string" />
			<xs:element name="SentTimeInUtc" type="xs:string" />
			<xs:element name="AdditionalNote" type="xs:string" minOccurs="0" />
			<xs:element name="Id" type="xs:string" minOccurs="0" />
			<xs:element name="MessageSubType" type="xs:string" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConversationMessageRating">
    <xs:sequence>
			<xs:element name="Id" type="xs:string" />
      <xs:element name="UserCode" type="xs:string" />
      <xs:element name="UserName" type="xs:string" />
      <xs:element name="Rating" type="xs:int" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
