<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Richard White (Eagle Datamation International) -->
<xs:schema targetNamespace="http://www.edi.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.edi.com.au/EnterpriseService/" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="Elements.xsd"/>
	<xs:include schemaLocation="Billing.xsd"/>
	<xs:complexType name="DebtorBalance">
		<xs:sequence>
			<xs:element name="Debtor" type="Organisation"/>
			<xs:element name="OutstandingBalance" type="FinancialValue" minOccurs="0"/>
			<xs:element name="OutstandingWIPAmount" type="FinancialValue" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="DebtorBalances">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DebtorBalance" type="DebtorBalance" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
