<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.edi.com.au/EnterpriseService/" xmlns="http://www.edi.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="ERequestDocument">
		<xs:sequence>
			<xs:element name="ReferenceId" type="xs:string" minOccurs="1" />
			<xs:element name="Attachments" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Attachment" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FileName" type="xs:string" />
									<xs:element name="Data" type="xs:base64Binary" />
									<xs:element name="IsPublished" type="xs:boolean" minOccurs="0"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>