<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Richard White (Eagle Datamation International) -->
<xs:schema targetNamespace="http://www.edi.com.au/EnterpriseService/" xmlns="http://www.edi.com.au/EnterpriseService/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="Elements.xsd"/>
	<xs:include schemaLocation="WebShipment.xsd"/>
	<xs:include schemaLocation="Order.xsd"/>
	<xs:complexType name="WebOrder">
		<xs:complexContent>
			<xs:extension base="Order">
				<xs:sequence>
          <xs:element name="Shipment" type="WebShipment" minOccurs="0"/>
          <xs:element name="DocumentLinks" type="DocumentLinks" minOccurs="0" />
        </xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="WebOrders">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="WebOrder" type="WebOrder" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="TotalRows" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="ReturnedRows" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="Version" type="Version" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
