//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Accounting.Business.JobInvoicing
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoJobChargeRevRecognitionLookups : ZLookups
	{
		protected AutoJobChargeRevRecognitionLookups(AutoJobChargeRevRecognition Parent) : base(Parent)
		{
		}

		#region Jobs

		public virtual JobHeaderCollection Jobs
		{
			get { return new JobHeaderCollection(Factory); }
		}

		#endregion
	}
}
