// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingModuleConsolCollection.LoadCusEntryNumbers(Enterprise.Freight.Forwarding.Business.ForwardingModuleConsol)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingModuleConsolCollection.cs:61:30
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingConsol.ReadFromTemplateRecord(Enterprise.MasterFiles.Business.StmTemplateRecord)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:8848:5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingModuleShipmentCollection.LoadHouseBills(Enterprise.Freight.Forwarding.Business.ForwardingModuleShipment)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingModuleShipmentCollection.cs:151:30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingModuleShipmentCollection.LoadCusEntryNumbers(Enterprise.Freight.Forwarding.Business.ForwardingModuleShipment)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingModuleShipmentCollection.cs:221:30
[assembly: SuppressMessage("CargoWiseOne", "CW1113:Do Not Show Message Box From Business Layer", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingProfitShareRedistribution.AddProfitShareRules(System.Collections.Generic.IEnumerable{Enterprise.MasterFiles.Business.OrgAgentRelationship})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\Rating\ProfitShareRedistribution\ForwardingProfitShareRedistribution.cs:178:4
[assembly: SuppressMessage("CargoWiseOne", "CW1113:Do Not Show Message Box From Business Layer", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingProfitShareRedistribution.AddProfitShareRules(System.Collections.Generic.IEnumerable{Enterprise.MasterFiles.Business.OrgAgentRelationship})")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\Rating\ProfitShareRedistribution\ForwardingProfitShareRedistribution.cs:195:23
[assembly: SuppressMessage("CargoWiseOne", "CW1113:Do Not Show Message Box From Business Layer", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingConsol.AllowDeallocatePrintedNeutralMAWB")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:3639:4
[assembly: SuppressMessage("CargoWiseOne", "CW1068:Do Not Use Math.Round", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingPackLine.GeneratePackageWithIDs")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\PackLine\ForwardingPackLine.cs:827:20
[assembly: SuppressMessage("CargoWiseOne", "CW1068:Do Not Use Math.Round", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingPackLine.GeneratePackageWithIDs")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\PackLine\ForwardingPackLine.cs:828:20
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.AWBActionsTest.CreatePrinter(System.Guid)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\ExportAWB\AWBActions\AWBActions.cs:955:27
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.PreparationTimeAtCFSDDDCalculationStep.AddMinutesBasedOnOpeningHours(CargoWise.Types.ZDateTime,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\DeliveryDueDateCalculation\DeliveryDueDateCalculationSteps\PreparationTimeAtCFSDDDCalculationStep.cs:38:12
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.PreparationTimeAtCFSDDDCalculationStep.AddMinutesBasedOnOpeningHours(CargoWise.Types.ZDateTime,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\DeliveryDueDateCalculation\DeliveryDueDateCalculationSteps\PreparationTimeAtCFSDDDCalculationStep.cs:38:62
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.OrderLineDeliveryTest.GetNewBusinessObject(System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\OrderLineDelivery\OrderLineDelivery.cs:562:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderLineDeliveryValidation.GetNewBusinessObject(System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\OrderLineDelivery\JobOrderLineDeliveryValidation.cs:215:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.TestValidateSenderAndReceiverAgentNotSame")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:924:40
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Order.RetrieveVoyage(CargoWise.Types.ZString,CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:885:50
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.GetAOrg")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:1719:10
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.DeliveryDueDateCalculationTestHelper.SetupTransportZone(CargoWise.EntityFramework.BusinessObjectFactory,Enterprise.MasterFiles.Business.OrgHeader,System.String,System.String,System.String,System.Int32,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\DeliveryDueDateCalculation\Helpers\DeliveryDueDateCalculationTestHelper.cs:66:3
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.DeliveryDueDateCalculationTestHelper.SetupTransitTime(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.Types.ZGuid,CargoWise.Types.ZGuid,CargoWise.Types.ZString,CargoWise.Types.ZString,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\DeliveryDueDateCalculation\Helpers\DeliveryDueDateCalculationTestHelper.cs:92:3
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestDelete")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:10343:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestFillWithValidTestData_DoesPopulatePickupDeliveryLists")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:10392:74
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderDoesntSetQtyInvoiced")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11807:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestOrderDoesntGoReadOnlyOnSplit")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11850:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestIsOrderPartiallyCompleteAndIsNotAlreadySplit")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11864:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestIsOrderPartiallyCompleteAndIsNotAlreadySplit_NoOverflowException")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11889:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderCopiesINCOCurrency")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11913:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderDoesntCopyShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:12117:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderDoesntCopyPlannedContainers")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:12149:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderDoesntCopySailingDetails")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:12165:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestSplitOrderDoesntCopyTrackingDates")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:12224:19
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.SupplyChainSecurityConfigurationSGTest.TestExpiryDate")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\SupplyChainSecurity\SupplyChainSecurityConfigurationSG.cs:488:29
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.TestParentOrderCollectionLimit(CargoWise.EntityFramework.BusinessObject,System.Func{Enterprise.Freight.Forwarding.Orders.Business.Order,CargoWise.EntityFramework.ZPropertyInfo},Enterprise.ZArchitecture.Environment.IntRegistryItem,Enterprise.ZArchitecture.Environment.DateTimeRegistryItem)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:1287:89
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.TestUnusedVoyagesAreNotUsedForValidation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:1388:33
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.TestUnusedVoyagesAreNotUsedForValidation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:1389:47
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.TestJobOrderHeaderValidation.TestUnusedVoyagesAreNotUsedForValidation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\JobOrderHeaderValidation.cs:1391:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestNoAEDEventLoggingOnOrderWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8651:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestNoAEDEventLoggingOnOrderWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8652:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestAIDEventLoggingOnOrder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8627:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestAIDEventLoggingOnOrder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8628:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestAEDEventLoggingOnOrder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8672:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestAEDEventLoggingOnOrder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8673:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestNoAIDEventLoggingOnOrderWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8606:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestNoAIDEventLoggingOnOrderWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:8607:37
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestUnusedVoyageDatesAreCleared")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11222:47
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestUnusedVoyageDatesAreCleared")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11224:33
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestUnusedVoyageDatesAreCleared")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11225:47
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Orders.Business.Testing.OrderTest.TestUnusedVoyageDatesAreCleared")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Orders\Order\Order.cs:11227:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolValidationTest.TestValidateJK_SendingForwarderHandlingType_WhenGatewayAgentHasCostsAndSharedCompanyLogedIn")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsolValidation.cs:2607:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolValidationTest.TestValidateJK_SendingForwarderHandlingType_WhenConvertingFromGTWtoNonGTWAndNotSavedJobExist")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsolValidation.cs:2712:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolValidationTest.TestValidateJK_ReceivingForwarderHandlingType_WhenConvertingFromGTWtoNonGTWAndNotSavedJobExist")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsolValidation.cs:2750:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolValidationTest.TestValidateJK_ReceivingForwarderHandlingType_WhenGatewayAgentHasCostsAndSharedCompanyLogedIn")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsolValidation.cs:2659:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolFreightTest.TestWorkflowRelationshipsWhenShipmentAdded")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:23482:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolFreightTest.TestWorkflowRelationshipsWhenShipmentAdded")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:23483:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolFreightTest.TestWorkflowRelationshipsWhenContainerAdded")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:23559:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolFreightTest.TestWorkflowRelationshipsWhenContainerAdded")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:23560:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestAEDEventLoggingOnConsol")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11291:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestAEDEventLoggingOnConsol")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11292:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestAIDEventLoggingOnConsol")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11244:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestAIDEventLoggingOnConsol")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11245:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestNoAIDEventLoggingOnConsolWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11222:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestNoAEDEventLoggingOnConsolWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11269:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestNoAIDEventLoggingOnConsolWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11223:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestNoAEDEventLoggingOnConsolWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:11270:37
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingContainerTest.TestCalculateDefaultDetention")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Container\ForwardingContainer.cs:1535:36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingContainerTest.TestCalculateDefaultDetention")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Container\ForwardingContainer.cs:1536:35
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.IcelandForwardingShipmentSupportTest.TestPreviousCOC")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\CountrySpecific\IcelandForwardingShipmentSupport.cs:564:13
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingContainerTest.TestProcessLogCoreUpdateDate_Pickup")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Container\ForwardingContainer.cs:3021:19
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingContainerTest.CreateVGMLog(Enterprise.Freight.Forwarding.Business.ForwardingContainer,Enterprise.ZArchitecture.Business.Event,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Container\ForwardingContainer.cs:3246:19
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestNoAIDEventLoggingOnShipmentWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10924:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestNoAIDEventLoggingOnShipmentWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10925:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestAEDEventLoggingOnShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10990:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestAIDEventLoggingOnShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10945:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestAIDEventLoggingOnShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10946:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestAEDEventLoggingOnShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10991:37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestNoAEDEventLoggingOnShipmentWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10969:38
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestNoAEDEventLoggingOnShipmentWithCountryRequiredDocuments")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:10970:37
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestIsAllowedToChangeShippingLineEvents")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:18816:32
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingConsolTest.TestIsAllowedToChangeShippingLineEvents")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Consol\ForwardingConsol.cs:18827:33
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestInspectionTypeOnlyDefaultsForOriginMatchingCurrentCountryCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:15276:50
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestCanExportData")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Freight\Forwarding\Forwarding.Business\Shipment\ForwardingShipment.cs:24935:135
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ShipmentSendingarnumerGeneratorTest.TestCarrierNumberNumberFountain(Enterprise.Freight.Forwarding.Business.ForwardingConsol,Enterprise.ZArchitecture.Environment.INumberFountainProxy,CargoWise.Types.ZString)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/Sendingarnumer/ShipmentSendingarnumerGenerator.cs:276,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ShipmentSendingarnumerGeneratorTest.TestCarrierNumberNumberFountain(Enterprise.Freight.Forwarding.Business.ForwardingConsol,Enterprise.ZArchitecture.Environment.INumberFountainProxy,CargoWise.Types.ZString)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/Sendingarnumer/ShipmentSendingarnumerGenerator.cs:280,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ShipmentSendingarnumerGeneratorTest.TestCarrierNumberNumberFountain(Enterprise.Freight.Forwarding.Business.ForwardingConsol,Enterprise.ZArchitecture.Environment.INumberFountainProxy,CargoWise.Types.ZString)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/Sendingarnumer/ShipmentSendingarnumerGenerator.cs:284,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.SendingarnumerNumberFountainTestHelper.SetNextForNumberFountain(Enterprise.ZArchitecture.Environment.INumberFountainProxy,System.Int32)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/CountrySpecific/Iceland/SendingarnumerNumberFountainTestHelper.cs:14,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.SendingarnumerNumberFountainTestHelper.SetNextForNumberFountain(Enterprise.ZArchitecture.Environment.INumberFountainProxy,System.Int32)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/CountrySpecific/Iceland/SendingarnumerNumberFountainTestHelper.cs:19,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.SendingarnumerNumberFountainTestHelper.SetNextForNumberFountain(Enterprise.ZArchitecture.Environment.INumberFountainProxy,System.Int32)")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/CountrySpecific/Iceland/SendingarnumerNumberFountainTestHelper.cs:23,4
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderUniqueIndexFailureHandlerTest.TestUniqueIndexConflictResolution")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeaderUniqueIndexFailureHandler.cs:104,76
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_CustomField_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25264,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_CustomField_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25327,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Consol_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25336,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Consol_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25387,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Shipment")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25396,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Shipment")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25424,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Shipment_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25433,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.TestHandleSaveException_Shipment_Shipment_CustomField")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:25482,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestDuplicateExchangeRateIsDeletedBeforeSaveWhenConvertingAmountsUsingJobExRateCurrencyConverter")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:4104,20
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestEH_SecurityStatusIssuedByAndEH_GS_NKSecurityStatusIssuedByCodeWhenIsAWBValuesOverriddenPropertyChanged")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:4047,16
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestEH_SecurityStatusIssuedByAndEH_GS_NKSecurityStatusIssuedByCodeWhenIsAWBValuesOverriddenPropertyChanged")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:4047,66
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestEH_SecurityStatusIssuedByWhenSetEH_GS_NKSecurityStatusIssuedByCode")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:4011,16
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestEH_SecurityStatusIssuedByWhenSetEH_GS_NKSecurityStatusIssuedByCode")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:4011,113
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.AWB.Testing.ExportAWBHeaderTest.TestAgentShipperSignature_ShouldBeIssuingCarrierAgentName_ForHongKongExportBorrowedMAWB")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:7213,141
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Freight.Forwarding.Business.JobConsolAWBSpecialHandling.TypeDecider")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Consol/AWBSpecialHandling/JobConsolAWBSpecialHandling.cs:14,64
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Freight.Forwarding.Business.AWB.ExportAWBHeader.TypeDecider")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/ExportAWB/ExportAWBHeader/ExportAWBHeader.cs:48,56
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Freight.Forwarding.Business.Testing.ForwardingShipmentTest.IncludedColumns")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipment.cs:22535,34
[assembly: SuppressMessage("CargoWiseOne", "EDI003:Business Object Property Max Length Validation", Justification = "Baseline WI00752625", Scope = "member", Target = "~M:Enterprise.Freight.Forwarding.Business.ForwardingShipmentProcessTask.OnSaving")] // Enterprise/Product/Operations/Freight/Forwarding/Forwarding.Business/Shipment/ForwardingShipmentProcessTask.cs:202,27
