using Enterprise.Edifact.Auto;

namespace Enterprise.Customs.AU.Declaration.Business.D98B
{
	[Resources.AutoGeneratedSourceCode()]
	public class LocationIdentificationElements : ValueBase
	{
		public LocationIdentificationElements()
		{
			MaximumNumberOfValues = 4;
		}

		public string PlaceLocationIdentification;

		public CodeListQualifierList CodeListQualifier;

		public CodeListResponsibleAgencyCodedList CodeListResponsibleAgencyCoded;

		public string PlaceLocation;

		#region Implementation

		protected override void GetValues()
		{
			ValueItems = new object[]
			{
				PlaceLocationIdentification,
				CodeListQualifier,
				CodeListResponsibleAgencyCoded,
				PlaceLocation
			};
		}

		protected override void SetValues()
		{
			PlaceLocationIdentification = Values(0);
			CodeListQualifier = CodeListQualifierList.GetFromString(Values(1));
			CodeListResponsibleAgencyCoded = CodeListResponsibleAgencyCodedList.GetFromString(Values(2));
			PlaceLocation = Values(3);
		}

		#endregion
	}
}
