//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from InspectionStatus_2_InspectionType.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.JP.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class InspectionStatus_2_InspectionType : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string One = "1";
			public const string Three = "3";
			public const string Two = "2";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString One { get { return ResString.GetMultilingualString("InspectionStatus_2_InspectionType|One", "Simple Inspection"); } }
			public static MultilingualString Three { get { return ResString.GetMultilingualString("InspectionStatus_2_InspectionType|Three", "Other Inspection"); } }
			public static MultilingualString Two { get { return ResString.GetMultilingualString("InspectionStatus_2_InspectionType|Two", "Document Inspection"); } }
		}

		public InspectionStatus_2_InspectionType()
		{
			AddPair(Codes.One, Descriptions.One);
			AddPair(Codes.Three, Descriptions.Three);
			AddPair(Codes.Two, Descriptions.Two);
		}
	}
}
