<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="placeholder">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="LazyLoading" type="xs:string" fixed="Yes">
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>
<xs:schema targetNamespace="http://www.cargowise.com/Schemas/DISDocument" version="1" elementFormDefault="qualified" xmlns="http://www.cargowise.com/Schemas/DISDocument" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DISDocument" type="DISDocument0" />
  <xs:complexType name="DISAdditionalData1">
    <xs:all>
      <xs:element name="Data" minOccurs="0" type="string_maxLength35" />
      <xs:element name="Name" minOccurs="0" type="string_maxLength35" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISAdditionalNumber12">
    <xs:all>
      <xs:element name="Number" minOccurs="0" type="string_maxLength35" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISBondData2">
    <xs:all>
      <xs:element name="AgentIDNumber" minOccurs="0" type="string_maxLength50" />
      <xs:element name="BondAmount" minOccurs="0" type="decimal_15_2" />
      <xs:element name="BondName" minOccurs="0" type="string_maxLength3" />
      <xs:element name="BondNumber" minOccurs="0" type="string_maxLength50" />
      <xs:element name="BondType" minOccurs="0" type="string_maxLength3" />
      <xs:element name="DefaultBondCode" minOccurs="0" type="string_maxLength3" />
      <xs:element name="SuretyCode" minOccurs="0" type="string_maxLength3" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISCBPRequest3">
    <xs:all>
      <xs:element name="ID" minOccurs="0" type="string_maxLength15" />
      <xs:element name="RequestDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="Type" minOccurs="0" type="string_maxLength3" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISCertificateData4">
    <xs:all>
      <xs:element name="CertificateNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="CertificateType" minOccurs="0" type="string_maxLength3" />
      <xs:element name="ExpiryDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="GrossTonnage" minOccurs="0" type="decimal_15_2" />
      <xs:element name="InspectionLocation" minOccurs="0" type="string_maxLength10" />
      <xs:element name="IssueDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="NetTonnage" minOccurs="0" type="decimal_15_2" />
      <xs:element name="Statement" minOccurs="0" type="string_maxLength500" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISCommodityLine5">
    <xs:all>
      <xs:element name="InvoiceLineNumber" minOccurs="0" type="xs:int" />
      <xs:element name="InvoiceLineTo" minOccurs="0" type="xs:int" />
      <xs:element name="InvoiceNumber" minOccurs="0" type="string_maxLength50" />
      <xs:element name="VNELineNumber" minOccurs="0" type="xs:int" />
      <xs:element name="VNELineNumberTo" minOccurs="0" type="xs:int" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISDocument0">
    <xs:all>
      <xs:element name="Comment" minOccurs="0" type="string_maxLength100" />
      <xs:element name="DocumentDescription" minOccurs="0" type="string_maxLength50" />
      <xs:element name="DocumentLabel" minOccurs="0" type="string_maxLength10" />
      <xs:element name="EDocsDocumentPK" minOccurs="0" type="guid" />
      <xs:element name="IDSuffix" minOccurs="0" type="xs:int" />
      <xs:element name="ITN" minOccurs="0" type="string_maxLength35" />
      <xs:element name="ShipmentNo" minOccurs="0" type="string_maxLength35" />
      <xs:element name="SubmitDateUTC" minOccurs="0" type="xs:dateTime" />
      <xs:element name="XTN" minOccurs="0" type="string_maxLength35" />
      <xs:element name="AdditionalData" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DISAdditionalData" minOccurs="0" maxOccurs="unbounded" type="DISAdditionalData1" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="BondData" minOccurs="0" type="DISBondData2" />
      <xs:element name="CBPRequest" minOccurs="0" type="DISCBPRequest3" />
      <xs:element name="CertificateData" minOccurs="0" type="DISCertificateData4" />
      <xs:element name="CommodityData" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DISCommodityLine" minOccurs="0" maxOccurs="unbounded" type="DISCommodityLine5" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="Invoice" minOccurs="0" type="DISInvoice6" />
      <xs:element name="PackingList" minOccurs="0" type="DISPackingListData8" />
      <xs:element name="PermitData" minOccurs="0" type="DISPermitData9" />
      <xs:element name="PGAs" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DISPGA" minOccurs="0" maxOccurs="unbounded" type="DISPGA10" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ToxicSubstanceData" minOccurs="0" type="DISToxicSubstanceData11" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISInvoice6">
    <xs:all>
      <xs:element name="InvoiceNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="InvoiceLineRanges" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DISInvoiceLineRange" minOccurs="0" maxOccurs="unbounded" type="DISInvoiceLineRange7" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISInvoiceLineRange7">
    <xs:all>
      <xs:element name="InvoiceLineFrom" minOccurs="0" type="xs:int" />
      <xs:element name="InvoiceLineTo" minOccurs="0" type="xs:int" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISPackingListData8">
    <xs:all>
      <xs:element name="InvoiceNumber" minOccurs="0" type="string_maxLength50" />
      <xs:element name="PackingListNumber" minOccurs="0" type="string_maxLength50" />
      <xs:element name="PurchaseOrderNumber" minOccurs="0" type="string_maxLength50" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISPermitData9">
    <xs:all>
      <xs:element name="ApprovalNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="EndDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="PermitNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="PermitType" minOccurs="0" type="string_maxLength3" />
      <xs:element name="StartDate" minOccurs="0" type="xs:dateTime" />
      <xs:element name="Statement" minOccurs="0" type="string_maxLength500" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISPGA10">
    <xs:all>
      <xs:element name="Code" minOccurs="0" type="string_maxLength10" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="DISToxicSubstanceData11">
    <xs:all>
      <xs:element name="EPAProducerEstNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="EPARegistrationNumber" minOccurs="0" type="string_maxLength35" />
      <xs:element name="CASNumbers" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="DISAdditionalNumber" minOccurs="0" maxOccurs="unbounded" type="DISAdditionalNumber12" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <xs:simpleType name="decimal_15_2">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value ="15" />
      <xs:fractionDigits value="2" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="guid">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength10">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength100">
    <xs:restriction base="xs:string">
      <xs:maxLength value="100" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength15">
    <xs:restriction base="xs:string">
      <xs:maxLength value="15" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength3">
    <xs:restriction base="xs:string">
      <xs:maxLength value="3" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength35">
    <xs:restriction base="xs:string">
      <xs:maxLength value="35" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength50">
    <xs:restriction base="xs:string">
      <xs:maxLength value="50" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string_maxLength500">
    <xs:restriction base="xs:string">
      <xs:maxLength value="500" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
