<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>CargoWise.RefDataRepo.Ent.Client.NudgeServiceTask</RootNamespace>
    <AssemblyName>CargoWise.RefDataRepo.Ent.Client.NudgeServiceTask</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.RefDbRepo.Client.Common" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.ServiceTasks" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
</Project>