<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <RootNamespace>Enterprise.ServiceManager.Tasks.ScheduledUpgrader.ServiceTasks</RootNamespace>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
    <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
      <Reference Include="System.ServiceModel.Primitives" />
      <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Upgrades" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Encryption" />
    <Reference Include="MailManager" />
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ScheduledUpgrader\Enterprise.ServiceManager.Tasks.ScheduledUpgrader.csproj" />
  </ItemGroup>
</Project>