<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">

    <!-- Representation of TARIC record 24500, 24505, 24510, 24515 -->
    <xsd:element name="additionalCode">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:additionalCodeFootnoteAssociation" minOccurs="0" maxOccurs="unbounded"/>
                <xsd:element ref="at:additionalCodeDescriptionPeriod" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- SID for additional code -->
        	<xsd:attribute ref="at:SID"/>
            <!-- Additional code type id -->
        	<xsd:attribute ref="at:additionalCodeType"/>
            <!-- Additional code -->
            <xsd:attribute ref="at:additionalCodeId"/>
            <!-- Validity start date of additional code -->
        	<xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of additional code -->
        	<xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
        	<xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
        	<xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="additionalCodeFootnoteAssociation">
        <xsd:complexType>
            <!-- Footnote type id -->
            <xsd:attribute ref="at:footnoteType"/>
            <!-- Footnote id -->
            <xsd:attribute ref="at:footnoteId"/>
            <!-- Validity start date of association between additional codes and footnotes -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of association between additional codes and footnotes -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="additionalCodeDescriptionPeriod">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:additionalCodeDescription" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- SID for additional code description -->
            <xsd:attribute ref="at:SID"/>
            <!-- Validity start date of additional code description -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of additional code description -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="additionalCodeDescription">
        <xsd:complexType>
            <!-- Language id of description -->
            <xsd:attribute ref="at:languageId"/>
            <!-- Long description of additional code -->
            <xsd:attribute ref="at:description"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>
