<xs:schema xmlns:baf="BiztalkAdapterFramework.xsd" xmlns:b="http://schemas.microsoft.com/BizTalk/2003" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import schemaLocation="BiztalkAdapterFramework.xsd" namespace="BiztalkAdapterFramework.xsd" />
	<xs:simpleType name="pollingInterval">
		<xs:annotation>
			<xs:appinfo>
				<baf:designer>
					<baf:displayname _locID="">Polling Interval</baf:displayname>
					<baf:description _locID="">Enter the polling interval</baf:description>
					<baf:category _locID="">Polling</baf:category>
				</baf:designer>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:int" />
	</xs:simpleType>
	<xs:simpleType name="pollingUnitOfMeasure">
		<xs:annotation>
			<xs:appinfo>
				<baf:designer>
					<baf:displayname _locID="">Polling Unit</baf:displayname>
					<baf:description _locID="">The unit of time measure that the polling interval represents</baf:description>
					<baf:category _locID="">Polling</baf:category>
				</baf:designer>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Seconds">
				<xs:annotation>
					<xs:appinfo>
						<baf:designer>
							<baf:displayname _locID="">Seconds</baf:displayname>
							<baf:description _locID="">Seconds</baf:description>
						</baf:designer>
					</xs:appinfo>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Minutes">
				<xs:annotation>
					<xs:appinfo>
						<baf:designer>
							<baf:displayname _locID="">Minutes</baf:displayname>
							<baf:description _locID="">Minutes</baf:description>
						</baf:designer>
					</xs:appinfo>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Hours">
				<xs:annotation>
					<xs:appinfo>
						<baf:designer>
							<baf:displayname _locID="">Hours</baf:displayname>
							<baf:description _locID="">Hours</baf:description>
						</baf:designer>
					</xs:appinfo>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="Days">
				<xs:annotation>
					<xs:appinfo>
						<baf:designer>
							<baf:displayname _locID="">Days</baf:displayname>
							<baf:description _locID="">Days</baf:description>
						</baf:designer>
					</xs:appinfo>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TransferErrorsDisablePort">
		<xs:annotation>
			<xs:appinfo>
				<baf:designer>
					<baf:displayname _locID="">Transfer Errors Disable Port</baf:displayname>
					<baf:description _locID="">Disable the port after the specified number of transfer errors.</baf:description>
					<baf:category _locID="">Polling</baf:category>
				</baf:designer>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:boolean" />
	</xs:simpleType>
	<xs:simpleType name="TransferErrorsRetryCount">
		<xs:annotation>
			<xs:appinfo>
				<baf:designer>
					<baf:displayname _locID="">Transfer Errors Retry Count</baf:displayname>
					<baf:description _locID="">Number of times to retry a transfer before disabling the port.</baf:description>
					<baf:category _locID="">Polling</baf:category>
				</baf:designer>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:int" />
	</xs:simpleType>
	<xs:simpleType name="TransferErrorsRetryInterval">
		<xs:annotation>
			<xs:appinfo>
				<baf:designer>
					<baf:displayname _locID="">Transfer Errors Retry Interval (seconds)</baf:displayname>
					<baf:description _locID="">Number of times to retry a transfer before disabling the port.</baf:description>
					<baf:category _locID="">Polling</baf:category>
				</baf:designer>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:int" />
	</xs:simpleType>
</xs:schema>
