<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <AssemblyName>Enterprise.Customs.CH.Business</AssemblyName>

    <!-- this is used by CargoWiseOne.ResourceStrings MsBuildTest.TestPerformance() -->
    <GenerateSgen Condition="'$(CWGenerateSgen)' == ''">true</GenerateSgen>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>

  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />

  <!-- this is used by CargoWiseOne.ResourceStrings MsBuildTest.TestPerformance() -->
  <ItemGroup Condition="'$(UseLegacyRsa)' == 'true'">
    <Using Include="CargoWise.ResourceStrings" />
    <Using Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.CH.MessageContracts" />
    <Reference Include="CargoWise.Customs.CH.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.xTMessaging.Business" />
    <Reference Include="Enterprise.xTMessaging.Shared" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="MailManager" />
    <Reference Include="MimeKit" />
    <Reference Include="MsgReader" />
    <Reference Include="Resources" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Memory" />
    <Reference Include="System.Security" />
    <Reference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Business\CusEntryInstruction\AutoCusEntryInstruction.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoCusEntryInstruction.xml</DependentUpon>
    </Compile>
    <Compile Update="Business\JobComInvHeaderCharge\CalculateFreight\AutoCalculateFreightBizObj.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoCalculateFreightBizObj.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\BordereauChargeTypeList.cs">
      <DependentUpon>BordereauChargeTypeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\BordereauReceivedStatusList.cs">
      <DependentUpon>BordereauReceivedStatusList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CHMessageStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CHMessageStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EVVInvoiceCurrencyType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EVVInvoiceCurrencyType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\TobaccoSpecialUnitOfMeasureList.cs">
      <DependentUpon>TobaccoSpecialUnitOfMeasureList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CHLogicalStatusList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CHLogicalStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\AdditionalCHEntryStatusList.cs">
      <DependentUpon>AdditionalCHEntryStatusList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EComplaintStatusWithoutNotSentList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EComplaintStatusWithoutNotSentList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PassarDeclarationPhaseList.cs">
      <DependentUpon>PassarDeclarationPhaseList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CustomArrivalCustomerReferenceFormatYearOptionList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CustomArrivalCustomerReferenceFormatYearOptionList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EVVTransportModeList.cs">
      <DependentUpon>EVVTransportModeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CusAuthorizationHeaderTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CusAuthorizationHeaderTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\CusCodeDataTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CusCodeDataTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\DeclarationPayerList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DeclarationPayerList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\GuaranteeTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GuaranteeTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EvvDocumentType.cs">
      <DependentUpon>EvvDocumentType.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EComplaintStatusList.cs">
      <DependentUpon>EComplaintStatusList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\ActivationTypeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ActivationTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PassarMessageTypeList.cs">
      <DependentUpon>PassarMessageTypeList.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageSubTypeCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageSubTypeCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\MessageTypeCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageTypeCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\PermitItemDetailKeyList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PermitItemDetailKeyList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\SwissCustomsLanguageList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwissCustomsLanguageList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EComplaintLocationList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>EComplaintLocationList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\TransportMeansList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TransportMeansList.xml</DependentUpon>
    </Compile>
    <Compile Update="MessageSending\Chartera\AutoCharteraOutputDocumentSearchSendingObject.cs">
      <DependentUpon>AutoCharteraOutputDocumentSearchSendingObject.xml</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="MessageSending\Declaration\AutoMessageSendingDeclaration.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoMessageSendingDeclaration.xml</DependentUpon>
    </Compile>
    <Compile Update="MessageSending\EComplaint\AutoEComplaintMessageSendingObject.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoEComplaintMessageSendingObject.xml</DependentUpon>
    </Compile>
    <Compile Update="MessageSending\EComplaint\AutoEComplaintMessageSendingObjectLine.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoEComplaintMessageSendingObjectLine.xml</DependentUpon>
    </Compile>
    <Compile Update="MessageSending\Evv\AutoEvvRequestSendingObjectParent.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoEvvRequestSendingObjectParent.xml</DependentUpon>
    </Compile>
    <Compile Update="Registry\ArrivalCustomerReferenceFormat\AutoCustomArrivalCustomerReferenceFormat.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoCustomArrivalCustomerReferenceFormat.xml</DependentUpon>
    </Compile>
    <Compile Update="Registry\EdecBordereauConfig\AutoEdecBordereauConfig.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoEdecBordereauConfig.xml</DependentUpon>
    </Compile>
    <Compile Update="Registry\PassarSearchRequestConfig\AutoPassarSearchRequestConfig.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AutoPassarSearchRequestConfig.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Business\JobComInvHeaderCharge\CalculateFreight\AutoCalculateFreightBizObj.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoCalculateFreightBizObj.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\BordereauChargeTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>BordereauChargeTypeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\BordereauReceivedStatusList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>BordereauReceivedStatusList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\CHMessageStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CHMessageStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EVVInvoiceCurrencyType.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>EvvInvoiceCurrencyType.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\TobaccoSpecialUnitOfMeasureList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>TobaccoSpecialUnitOfMeasureList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\CHLogicalStatusList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>CHLogicalStatusList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\AdditionalCHEntryStatusList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AdditionalCHEntryStatusList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\EComplaintStatusWithoutNotSentList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EComplaintStatusWithoutNotSentList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\PassarDeclarationPhaseList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>PassarDeclarationPhaseList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\CustomArrivalCustomerReferenceFormatYearOptionList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>CustomArrivalCustomerReferenceFormatYearOptionList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="MessageSending\Chartera\AutoCharteraOutputDocumentSearchSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AutoCharteraOutputDocumentSearchSendingObject.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
    <None Update="MessageSending\Declaration\AutoMessageSendingDeclaration.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AutoMessageSendingDeclaration.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
    <None Update="MessageSending\EComplaint\AutoEComplaintMessageSendingObject.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AutoEComplaintMessageSendingObject.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
    <None Update="MessageSending\EComplaint\AutoEComplaintMessageSendingObjectLine.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoEComplaintMessageSendingObjectLine.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Business\CusLineTariffDetail\AutoCusLineTariffDetail.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AutoCusLineTariffDetail.cs</LastGenOutput>
      <Generator>AddInfoPartialWrapperGenerator</Generator>
    </None>
    <None Update="Business\CusEntryInstruction\AutoCusEntryInstruction.xml">
      <Generator>AddInfoPartialWrapperGenerator</Generator>
      <LastGenOutput>AutoCusEntryInstruction.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EVVTransportModeList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>EVVTransportModeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\CusAuthorizationHeaderTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>CusAuthorizationHeaderTypeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\CusCodeDataTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CusCodeDataTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\DeclarationPayerList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DeclarationPayerList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\GuaranteeTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>GuaranteeTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EvvDocumentType.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>EvvDocumentType.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\EComplaintStatusList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EComplaintStatusList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\EComplaintLocationList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>EComplaintLocationList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\ActivationTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ActivationTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\PassarMessageTypeList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>PassarMessageTypeList.cs</LastGenOutput>
      <Generator>CodeDescriptionPairListGenerator</Generator>
    </None>
    <None Update="CodeDescriptionPairLists\MessageSubTypeCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageSubTypeCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\MessageTypeCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>MessageTypeCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\PermitItemDetailKeyList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PermitItemDetailKeyList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\SwissCustomsLanguageList.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SwissCustomsLanguageList.cs</LastGenOutput>
    </None>
    <None Update="CodeDescriptionPairLists\TransportMeansList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransportMeansList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="MessageSending\Evv\AutoEvvRequestSendingObjectParent.xml">
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
      <LastGenOutput>AutoEvvRequestSendingObjectParent.cs</LastGenOutput>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
    </None>
    <None Update="Registry\ArrivalCustomerReferenceFormat\AutoCustomArrivalCustomerReferenceFormat.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoCustomArrivalCustomerReferenceFormat.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="Registry\EdecBordereauConfig\AutoEdecBordereauConfig.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoEdecBordereauConfig.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
    <None Update="Registry\PassarSearchRequestConfig\AutoPassarSearchRequestConfig.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoPassarSearchRequestConfig.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.CH.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>