using System;
using System.Linq;
using System.Text;
using CargoWise.ComponentModel;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using NUnit.Framework;

namespace Enterprise.Accounting.ElectronicMessaging.India.Testing
{
	public class IndiaEInvoiceDataResponseReaderTest : TestCase
	{
		public void TestConstructor()
		{
			AssertExceptionThrown(typeof(ArgumentNullException), "Value cannot be null.\r\nParameter name: payload", () => new IndiaEInvoiceResponseReader(null, null));
			AssertExceptionThrown(typeof(ArgumentException), "Value cannot be empty string (\"\").\r\nParameter name: payload", () => new IndiaEInvoiceResponseReader(string.Empty, null));
			AssertExceptionThrown(typeof(ArgumentNullException), "Value cannot be null.\r\nParameter name: notifications", () => new IndiaEInvoiceResponseReader("some string", null));
			AssertNoExceptionThrown("Correct arguments", () => new IndiaEInvoiceResponseReader("some string", new NotificationBuffer()));
		}

		public void TestRead_EmptyString()
		{
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(" ", notifications);

			AssertNull(reader.Read());
			Assert(notifications.HasErrors);
			var errors = notifications.GetEventsByType(NotificationType.Error);
			AssertEquals("Expected error count for empty json string", 1, errors.Length);
			AssertContains("Reading the following India E-Invoice Response has failed due to invalid JSON:", errors[0].Message);
		}

		public void TestRead_AllFields()
		{
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'2019-12-25 12:30:01'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g'",
				"'SignedQRCode':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJEb2NOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEb2NUeXBcIjpcIklOVlwiLFwiRG9jRHRcIjpcIjIwMTktMTEtMjhcIixcIlRvdEludlZhbFwiOjAsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCIxMDAxXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIn0iLCJpc3MiOiJOSUMifQ.UbnWZAI_lq9s9JK8_MovcmjpMPIJnv2-4qGkiXegggQbry_0fJxjwaR8fwCjK_-HVeMujnw8C7F3ITrxKIg5RsdDMzAvLrCNE0K3QkNHGczbvyxhJ02VRFl1wrQoArxSW1RiyGssLSbH_4tdQ6vke0nSUajXRXvXX2yUeI01CyLsbf2FDNIq46MrDmka5RPNGp0dCx4uX2gkmsCx0Yb0CKjqFI176sTbxOQDHQtRCAfJ0I6dwwggVkfnC3p2F-x6GhEls_7GVsFg1Z6k4A_aB89c3N6CaWfe8DOQEJTjWaPggMUa2-1hDE1ODTBcIlLcOwB-8jT971hZWgtBubUzFg'",
				"'Status':'ACT'",
			};
			var json = GetJsonString(fields);
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(json)), notifications);

			AssertNotNull("Json result object should not be null when all required fields are present", reader.Read());
			Assert("When Json parsing is successful there should be no errors", !notifications.HasErrors);
		}

		public void TestRead_InvalidJson()
		{
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'2019-12-25 12:30:01'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g'",
				"'SignedQRCode':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJEb2NOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEb2NUeXBcIjpcIklOVlwiLFwiRG9jRHRcIjpcIjIwMTktMTEtMjhcIixcIlRvdEludlZhbFwiOjAsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCIxMDAxXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIn0iLCJpc3MiOiJOSUMifQ.UbnWZAI_lq9s9JK8_MovcmjpMPIJnv2-4qGkiXegggQbry_0fJxjwaR8fwCjK_-HVeMujnw8C7F3ITrxKIg5RsdDMzAvLrCNE0K3QkNHGczbvyxhJ02VRFl1wrQoArxSW1RiyGssLSbH_4tdQ6vke0nSUajXRXvXX2yUeI01CyLsbf2FDNIq46MrDmka5RPNGp0dCx4uX2gkmsCx0Yb0CKjqFI176sTbxOQDHQtRCAfJ0I6dwwggVkfnC3p2F-x6GhEls_7GVsFg1Z6k4A_aB89c3N6CaWfe8DOQEJTjWaPggMUa2-1hDE1ODTBcIlLcOwB-8jT971hZWgtBubUzFg'",
				"'Status''ACT'",		// Missing ':'
			};
			var invalidJson = GetJsonString(fields);
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(invalidJson)), notifications);

			AssertNull("Json object should be null when json string is invalid", reader.Read());
			Assert("When Json parsing is successful there should be errors", notifications.HasErrors);

			var errors = notifications.GetEventsByType(NotificationType.Error);
			AssertEquals("Expected error count for invalid json string", 1, errors.Length);
			AssertContains("Reading the following India E-Invoice Response has failed due to invalid JSON:", errors[0].Message);
			AssertContains(invalidJson, errors[0].Message);
		}

		public void TestRead_MissingRequiredFields()
		{
			// All fields are required in India.
			var requiredFields = new string[]
			{
				"AckNo",
				"AckDt",
				"Irn",
				"SignedInvoice",
				"SignedQRCode",
				"Status",
			};
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'2019-12-25 12:30:01'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g'",
				"'SignedQRCode':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJEb2NOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEb2NUeXBcIjpcIklOVlwiLFwiRG9jRHRcIjpcIjIwMTktMTEtMjhcIixcIlRvdEludlZhbFwiOjAsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCIxMDAxXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIn0iLCJpc3MiOiJOSUMifQ.UbnWZAI_lq9s9JK8_MovcmjpMPIJnv2-4qGkiXegggQbry_0fJxjwaR8fwCjK_-HVeMujnw8C7F3ITrxKIg5RsdDMzAvLrCNE0K3QkNHGczbvyxhJ02VRFl1wrQoArxSW1RiyGssLSbH_4tdQ6vke0nSUajXRXvXX2yUeI01CyLsbf2FDNIq46MrDmka5RPNGp0dCx4uX2gkmsCx0Yb0CKjqFI176sTbxOQDHQtRCAfJ0I6dwwggVkfnC3p2F-x6GhEls_7GVsFg1Z6k4A_aB89c3N6CaWfe8DOQEJTjWaPggMUa2-1hDE1ODTBcIlLcOwB-8jT971hZWgtBubUzFg'",
				"'Status':'ACT'",
			};

			foreach (var excludedField in requiredFields)
			{
				var jsonBuilder = new ZStringBuilder();
				foreach (var field in fields)
				{
					if (!field.Contains("'" + excludedField + "'"))
					{
						jsonBuilder.Append(field);
					}
				}

				var incompleteJson = GetJsonString(jsonBuilder);
				var notifications = new NotificationBuffer();
				var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(incompleteJson)), notifications);

				AssertNull("Json object is null when following required part is missing: " + excludedField.Replace("'", "\""), reader.Read());
				Assert(notifications.HasErrors);
				var errors = notifications.GetEventsByType(NotificationType.Error);
				AssertEquals("Expected error count for missing " + excludedField.Replace("'", "\""), 3, errors.Length);
				Assert(errors.Take(2).All(x => x.Message.Contains("Required propert")));
				AssertContains(incompleteJson, errors[2].Message);
			}
		}

		public void TestRead_InvalidDatestamp()
		{
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'not a valid date'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g'",
				"'SignedQRCode':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJEb2NOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEb2NUeXBcIjpcIklOVlwiLFwiRG9jRHRcIjpcIjIwMTktMTEtMjhcIixcIlRvdEludlZhbFwiOjAsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCIxMDAxXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIn0iLCJpc3MiOiJOSUMifQ.UbnWZAI_lq9s9JK8_MovcmjpMPIJnv2-4qGkiXegggQbry_0fJxjwaR8fwCjK_-HVeMujnw8C7F3ITrxKIg5RsdDMzAvLrCNE0K3QkNHGczbvyxhJ02VRFl1wrQoArxSW1RiyGssLSbH_4tdQ6vke0nSUajXRXvXX2yUeI01CyLsbf2FDNIq46MrDmka5RPNGp0dCx4uX2gkmsCx0Yb0CKjqFI176sTbxOQDHQtRCAfJ0I6dwwggVkfnC3p2F-x6GhEls_7GVsFg1Z6k4A_aB89c3N6CaWfe8DOQEJTjWaPggMUa2-1hDE1ODTBcIlLcOwB-8jT971hZWgtBubUzFg'",
				"'Status':'ACT'",
			};
			var json = GetJsonString(fields);
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(json)), notifications);

			AssertNull("Json object should be null when json string is invalid", reader.Read());
			var errors = notifications.GetEventsByType(NotificationType.Error);
			AssertEquals("Expected error count for invalid timestamp", 1, errors.Length);
			AssertContains("India E-Invoice Response has invalid 'AckDt' field", errors[0].Message);
			AssertContains(json, errors[0].Message);
		}

		public void TestRead_InvalidSignedInvoiceJwt()
		{
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'2019-12-25 12:30:01'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'not a valid invoice'",
				"'SignedQRCode':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiU2VsbGVyR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiQnV5ZXJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJEb2NOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEb2NUeXBcIjpcIklOVlwiLFwiRG9jRHRcIjpcIjIwMTktMTEtMjhcIixcIlRvdEludlZhbFwiOjAsXCJJdGVtQ250XCI6MSxcIk1haW5Ic25Db2RlXCI6XCIxMDAxXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIn0iLCJpc3MiOiJOSUMifQ.UbnWZAI_lq9s9JK8_MovcmjpMPIJnv2-4qGkiXegggQbry_0fJxjwaR8fwCjK_-HVeMujnw8C7F3ITrxKIg5RsdDMzAvLrCNE0K3QkNHGczbvyxhJ02VRFl1wrQoArxSW1RiyGssLSbH_4tdQ6vke0nSUajXRXvXX2yUeI01CyLsbf2FDNIq46MrDmka5RPNGp0dCx4uX2gkmsCx0Yb0CKjqFI176sTbxOQDHQtRCAfJ0I6dwwggVkfnC3p2F-x6GhEls_7GVsFg1Z6k4A_aB89c3N6CaWfe8DOQEJTjWaPggMUa2-1hDE1ODTBcIlLcOwB-8jT971hZWgtBubUzFg'",
				"'Status':'ACT'",
			};
			var invalidJson = GetJsonString(fields);
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(invalidJson)), notifications);

			AssertNull("Json object should be null when json string is invalid", reader.Read());
			Assert("When Json parsing is successful there should be errors", notifications.HasErrors);

			var errors = notifications.GetEventsByType(NotificationType.Error);
			AssertEquals("Expected error count for invalid invoice", 1, errors.Length);
			AssertContains("India E-Invoice Response has invalid 'SignedInvoice' field", errors[0].Message);
			AssertContains(invalidJson, errors[0].Message);
		}

		public void TestRead_InvalidSignedQRCodeJwt()
		{
			var fields = new string[]
			{
				"'AckNo':2",
				"'AckDt':'2019-12-25 12:30:01'",
				"'Irn':'d056a57cc7cfcc6c9230aa0014e439259d0dc57cfa4eea2326253011fd53ea7e'",
				"'SignedInvoice':'eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Iiwia2lkIjoiRTc4MDhFNkZGMDNFMTMyODUzMzBCMDQxQjNFMEEzQUVDNDc4MTMyMCIsInR5cCI6IkpXVCIsIng1dCI6IjU0Q09iX0EtRXloVE1MQkJzLUNqcnNSNEV5QSJ9.eyJkYXRhIjoie1wiQWNrTm9cIjoxNzEwMDAwMDA1NCxcIkFja0R0XCI6XCIyMDE5LTEyLTI1IDEyOjAzOjAwXCIsXCJUYXhTY2hcIjpudWxsLFwiVmVyc2lvblwiOlwiMS4wXCIsXCJJcm5cIjpcImQwNTZhNTdjYzdjZmNjNmM5MjMwYWEwMDE0ZTQzOTI1OWQwZGM1N2NmYTRlZWEyMzI2MjUzMDExZmQ1M2VhN2VcIixcIlRyYW5EdGxzXCI6e1wiQ2F0Z1wiOlwiQjJCXCIsXCJSZWdSZXZcIjpcIlJHXCIsXCJUeXBcIjpcIlJFIFwiLFwiRWNtVHJuXCI6XCJOXCIsXCJFY21Hc3RpblwiOlwiXCJ9LFwiRG9jRHRsc1wiOntcIlR5cFwiOlwiSU5WXCIsXCJOb1wiOlwiZG9jL3Rlc3QxXCIsXCJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiT3JnSW52Tm9cIjpcIjEyMzMyMTEyMzMyMTEyMzJcIn0sXCJTZWxsZXJEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIlRyYWRlIE5hbWUxXCIsXCJCbm9cIjpcIjFcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCJcIixcIkxvY1wiOlwiTG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJjQHh5ei5jb21cIn0sXCJCdXllckR0bHNcIjp7XCJHc3RpblwiOlwiMjlBQUdQQjg2NzhMMVoxXCIsXCJUcmRObVwiOlwiVHJhZGUgTmFtZTFcIixcIkJub1wiOlwiMVwiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIlwiLFwiTG9jXCI6XCJMb2NhdGlvblwiLFwiRHN0XCI6XCJcIixcIlBpblwiOjU2MDA0MyxcIlN0Y2RcIjoyOSxcIlBoXCI6bnVsbCxcIkVtXCI6XCJhYmNAeHl6LmNvbVwifSxcIkRpc3BEdGxzXCI6e1wiR3N0aW5cIjpcIjI5QUFHUEI4Njc4TDFaMVwiLFwiVHJkTm1cIjpcIm5hbWUgXCIsXCJCbm9cIjpcIjEyM1wiLFwiQm5tXCI6XCJcIixcIkZsbm9cIjpcIjJcIixcIkxvY1wiOlwibG9jYXRpb25cIixcIkRzdFwiOlwiXCIsXCJQaW5cIjo1NjAwNDMsXCJTdGNkXCI6MjksXCJQaFwiOm51bGwsXCJFbVwiOlwiYWJDQFhZWi5DT01cIn0sXCJTaGlwRHRsc1wiOntcIkdzdGluXCI6XCIyOUFBR1BCODY3OEwxWjFcIixcIlRyZE5tXCI6XCJuYW1lIFwiLFwiQm5vXCI6XCIxMjNcIixcIkJubVwiOlwiXCIsXCJGbG5vXCI6XCIyXCIsXCJMb2NcIjpcImxvY2F0aW9uXCIsXCJEc3RcIjpcIlwiLFwiUGluXCI6NTYwMDQzLFwiU3RjZFwiOjI5LFwiUGhcIjpudWxsLFwiRW1cIjpcImFiQ0BYWVouQ09NXCJ9LFwiSXRlbUxpc3RcIjpbe1wiUHJkTm1cIjpcIldoZWF0XCIsXCJQcmREZXNjXCI6XCJXaGVhdCBkZXNjXCIsXCJIc25DZFwiOlwiMTAwMVwiLFwiQmFyY2RlXCI6bnVsbCxcIlF0eVwiOjEsXCJGcmVlUXR5XCI6bnVsbCxcIlVuaXRcIjpcIktHU1wiLFwiVW5pdFByaWNlXCI6MCxcIlRvdEFtdFwiOjAsXCJEaXNjb3VudFwiOjAsXCJPdGhDaHJnXCI6MCxcIkFzc0FtdFwiOjAsXCJDZ3N0UnRcIjozLFwiU2dzdFJ0XCI6MyxcIklnc3RSdFwiOjAsXCJDZXNSdFwiOjAsXCJDZXNOb25BZFZhbFwiOjAsXCJTdGF0ZUNlc1wiOjM2LFwiVG90SXRlbVZhbFwiOjIzNDMyfV0sXCJWYWxEdGxzXCI6e1wiQXNzVmFsXCI6MTAsXCJDZ3N0VmFsXCI6MixcIlNnc3RWYWxcIjoyLFwiSWdzdFZhbFwiOjAsXCJDZXNWYWxcIjowLFwiU3RDZXNWYWxcIjowLFwiQ2VzTm9uQWRWYWxcIjowLFwiRGlzY1wiOjAsXCJPdGhDaHJnXCI6MCxcIlRvdEludlZhbFwiOjB9LFwiRXhwRHRsc1wiOntcIkV4cENhdFwiOlwiU0VaXCIsXCJXdGhQYXlcIjpcIk5cIixcIlNoaXBCTm9cIjpcIlwiLFwiU2hpcEJEdFwiOlwiMjAxOS0xMS0yOFwiLFwiUG9ydFwiOlwiXCIsXCJJbnZGb3JDdXJcIjoyMzQ0NSxcIkZvckN1clwiOlwiQkRUXCIsXCJDbnRDb2RlXCI6XCJCRFwifSxcIlBheUR0bHNcIjp7XCJOYW1cIjpcIlwiLFwiTW9kZVwiOlwiQ0FTSFwiLFwiRmluSW5zQnJcIjpcIlwiLFwiUGF5VGVybVwiOlwiMTAwMVwiLFwiUGF5SW5zdHJcIjpcIlwiLFwiQ3JUcm5cIjpcIlwiLFwiRGlyRHJcIjpcIlwiLFwiQ3JEYXlcIjoyLFwiQmFsQW10XCI6MixcIlBheUR1ZUR0XCI6XCIyMDE5LTExLTI4XCIsXCJBY2N0RGV0XCI6XCIxMFwifSxcIlJlZkR0bHNcIjp7XCJJbnZSbWtcIjpcIjBcIixcIkludlN0RHRcIjpcIjIwMTktMTEtMjhcIixcIkludkVuZER0XCI6XCIyMDE5LTExLTI4XCIsXCJQcmVjSW52Tm9cIjpcIlwiLFwiUHJlY0ludkR0XCI6XCIyMDE5LTExLTI4XCIsXCJJbnZSZWZOb1wiOlwiMFwiLFwiUmVjQWR2UmVmXCI6XCJcIixcIlRlbmRSZWZcIjpcIlwiLFwiQ29udHJSZWZcIjpcIjEwXCIsXCJFeHRSZWZcIjpcIjJcIixcIlByb2pSZWZcIjpcIlwiLFwiUE9SZWZcIjpcIlwifX0iLCJpc3MiOiJOSUMifQ.II0jejF0wOrY0CPwIb6oQsSBYilvFSNHZqQJHYOsFt7txrpAvLlCEo4CDNUhPZGWZ6IeERuoY2ScXKNIsCIMQR_9dc0E_fmsaN5XUscxBV3nqPNIkusFcmzjxu59sT8MzcaFqDWfqHunkA-klW40M7oVy6HtL5eI0zbmNoZpdl2yB1Fxfx5AF_vcDv9vWV2u6i39XQ0KdTSbkTAVStdXHix2hE0TlHtHB9Tqt7i9umNPJc_Uf5Kpn4qHiOPvFT2uxhw1N7bIU00cc-PDIqzlLk2VnLb2Zko7wSgYAMrf5G1hn5Op4lbyQe9EwxOPcvJPjJBJsoOmFTbxd1IRgewm7g'",
				"'SignedQRCode':'not a valid QR code'",
				"'Status':'ACT'",
			};
			var invalidJson = GetJsonString(fields);
			var notifications = new NotificationBuffer();
			var reader = new IndiaEInvoiceResponseReader(Convert.ToBase64String(Encoding.UTF8.GetBytes(invalidJson)), notifications);

			AssertNull("Json object should be null when json string is invalid", reader.Read());
			Assert("When Json parsing is successful there should be errors", notifications.HasErrors);

			var errors = notifications.GetEventsByType(NotificationType.Error);
			AssertEquals("Expected error count for invalid qrcode", 1, errors.Length);
			AssertContains("India E-Invoice Response has invalid 'SignedQRCode' field", errors[0].Message);
			AssertContains(invalidJson, errors[0].Message);
		}

		#region Implementation

		string GetJsonString(string[] fields)
		{
			var jsonBuilder = new ZStringBuilder();
			foreach (var field in fields)
			{
				jsonBuilder.Append(field);
			}
			return GetJsonString(jsonBuilder);
		}

		string GetJsonString(ZStringBuilder jsonBuilder)
			=> ("{" + jsonBuilder.ToStringWithDelimiterBetweenAppends(",") + "}").Replace("'", "\"");

		#endregion
	}
}
