using System;
using System.Linq;
using System.Windows.Forms;
using Enterprise.Freight.Business;
using Enterprise.Freight.Forwarding.Business;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture.Core;
using Enterprise.ZArchitecture.GUI;

namespace Enterprise.Freight.Forwarding.GUI
{
	public partial class ConsolContainerUserControl : ZUserControl
	{
		ZPanel panel1;
		ZPanel panel2;
		ZPanel panel3;
		internal ForwardingContainersUserControl containersUserControl1;
		internal ZModuleButtonGrid JobContainerBoundGrid;

		void InitializeComponent()
		{
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo2 = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo3 = new ZDropEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo4 = new ZDropEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo2 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo5 = new ZDropEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo3 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo6 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo4 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo7 = new ZDropEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo5 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo8 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo6 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo9 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo1 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo7 = new ZGuidFindBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo10 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo11 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo2 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo12 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo13 = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo14 = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo15 = new ZDropEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo16 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo9 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo10 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo8 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo9 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo10 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo11 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo12 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo13 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo14 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo15 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo16 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo17 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo18 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo19 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo20 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo17 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo21 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZMultiControlColumnStyleInfo zMultiControlColumnStyleInfo1 = new ZMultiControlColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo18 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo3 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo4 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo5 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo11 = new ZArchitecture.ZCalcEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo19 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo1 = new ZCodeFindBoxColumnStyleInfo();
			ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo22 = new ZArchitecture.ZDateEditColumnStyleInfo();
			ZDropEditColumnStyleInfo zDropEditColumnStyleInfo20 = new ZDropEditColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo emptyReturnReferenceColumnStyleInfo = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new ZArchitecture.ZTextBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo6 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo7 = new ZArchitecture.ZCheckBoxColumnStyleInfo();
			var allocationIDColumnStyleInfo1 = new AllocationIDFindBoxColumnStyleInfo();

			this.panel2 = new ZPanel();
			this.panel1 = new ZPanel();
			this.containersUserControl1 = new ForwardingContainersUserControl();
			this.JobContainerBoundGrid = new ZModuleButtonGrid();
			this.panel3 = new ZPanel();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			this.panel2.SuspendLayout();
			this.panel1.SuspendLayout();
			this.containersUserControl1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.JobContainerBoundGrid.InnerGrid)).BeginInit();
			this.JobContainerBoundGrid.SuspendLayout();
			this.SuspendLayout();
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(ForwardingContainer);
			// 
			// panel2
			// 
			this.panel2.Controls.Add(this.panel1);
			this.panel2.Controls.Add(this.panel3);
			this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel2.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.panel2.Name = "panel2";
			this.panel2.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(988, 560, true);
			this.panel2.TabIndex = 0;
			// 
			// panel1
			// 
			this.panel1.Controls.Add(this.containersUserControl1);
			this.panel1.Controls.Add(this.JobContainerBoundGrid);
			this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel1.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 8, true);
			this.panel1.Name = "panel1";
			this.panel1.Padding = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPadding(8, 0, 8, 8, true);
			this.panel1.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(988, 552, true);
			this.panel1.TabIndex = 1;
			// 
			// containersUserControl1
			// 
			this.containersUserControl1.AllowDrop = true;
			this.containersUserControl1.Anchor = ((AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
			this.BindingSource.SetBindingMember(this.containersUserControl1, ".");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((CommonContainer)(((ForwardingContainer)(null)))));
			this.containersUserControl1.CurrentContainer = null;
			this.containersUserControl1.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(8, 146, true);
			this.containersUserControl1.Name = "containersUserControl1";
			this.containersUserControl1.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(1067, 403, true);
			this.containersUserControl1.TabIndex = 2;
			// 
			// JobContainerBoundGrid
			// 
			this.JobContainerBoundGrid.GridId = "GridLayoutzcqY9hNZIXmSS7+SaYceHQ==";
			this.JobContainerBoundGrid.AllowDrop = true;
			this.JobContainerBoundGrid.Anchor = ((AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.BindingSource.SetBindingMember(this.JobContainerBoundGrid, ".");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((ForwardingContainer)(null)))));
			zTextBoxColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo1.ColumnName = "JC_ContainerNum";
			zTextBoxColumnStyleInfo1.IsMandatory = true;
			zTextBoxColumnStyleInfo1.ToolTip = "Container Number";
			zTextBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.ColumnName = "JC_ContainerCount";
			zCalcEditColumnStyleInfo1.Decimals = 0;
			zCalcEditColumnStyleInfo1.IsMandatory = true;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo12.ColumnName = "JC_SealNum";
			zTextBoxColumnStyleInfo12.IsMandatory = true;
			zTextBoxColumnStyleInfo12.ToolTip = "Seal Number /  Rate Class";
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo2.ColumnName = "JC_SealParty";
			zDropEditColumnStyleInfo2.IsMandatory = true;
			zDropEditColumnStyleInfo2.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDropEditColumnStyleInfo3.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo3.ColumnName = "JC_ContainerMode";
			zDropEditColumnStyleInfo3.IsMandatory = true;
			zDropEditColumnStyleInfo3.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo3.ToolTip = "Container Mode";
			zDropEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo1.ColumnName = "JC_RC";
			zGuidFindBoxColumnStyleInfo1.IsMandatory = true;
			zGuidFindBoxColumnStyleInfo1.ToolTip = "Container Type";
			zGuidFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo4.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zDropEditColumnStyleInfo4.ColumnName = "DeliveryModeForBinding";
			zDropEditColumnStyleInfo4.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo4.ToolTip = "Delivery Mode";
			zDropEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("0e67a5ef-c2d5-439d-97c7-a5caf50c9d90", "Delivery Mode");
			zGuidFindBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|a998e299-85b7-4a4f-9f65-9eeda63ad4a6", "Pickup Empty From Org.", "Pickup Empty From Organization");
			zGuidFindBoxColumnStyleInfo2.ColumnName = "JC_Calc_DepartureContainerYardAddressOrg";
			zGuidFindBoxColumnStyleInfo2.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|e722da18-eff5-495a-8805-386602f13e92", "Pickup Empty From");
			zGuidFindBoxColumnStyleInfo2.IsVisible = false;
			zGuidFindBoxColumnStyleInfo2.ToolTip = "Point for Empty/Export container pickup";
			zGuidFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|aa0667bd-c91b-41d6-90cd-390678b4a1ab", "Pickup Empty From");
			zDropEditColumnStyleInfo5.ColumnName = "JC_Calc_DepartureContainerYardAddressCode";
			zDropEditColumnStyleInfo5.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|e722da18-eff5-495a-8805-386602f13e92", "Pickup Empty From");
			zDropEditColumnStyleInfo5.IsVisible = false;
			zDropEditColumnStyleInfo5.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo5.ToolTip = "Point for Empty/Export container pickup";
			zDropEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zGuidFindBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|1a602a8e-c822-4fa9-ba8e-40cdb7b5c0cb", "Pack At Org.", "Pack At Organization");
			zGuidFindBoxColumnStyleInfo3.ColumnName = "JC_Calc_DeparturePackAddressOrg";
			zGuidFindBoxColumnStyleInfo3.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|3db863ea-48c0-4934-a338-3ddf9b44b3c4", "Pack At");
			zGuidFindBoxColumnStyleInfo3.IsVisible = false;
			zGuidFindBoxColumnStyleInfo3.ToolTip = "Pack Container At";
			zGuidFindBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|29e3d1e6-3dd2-416f-b19d-36af040d35a5", "Pack At");
			zDropEditColumnStyleInfo6.ColumnName = "JC_Calc_DeparturePackAddressCode";
			zDropEditColumnStyleInfo6.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|3db863ea-48c0-4934-a338-3ddf9b44b3c4", "Pack At");
			zDropEditColumnStyleInfo6.IsVisible = false;
			zDropEditColumnStyleInfo6.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo6.ToolTip = "Pack Container At";
			zDropEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zDateEditColumnStyleInfo1.ColumnName = "JC_DepartureEstimatedPickup";
			zDateEditColumnStyleInfo1.IsVisible = false;
			zDateEditColumnStyleInfo1.ToolTip = "Pickup Full container for export on this date time";
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|57130ea0-fc50-44ac-9939-56df9d441e62", "Load CTO Org.", "Load CTO Organization");
			zGuidFindBoxColumnStyleInfo4.ColumnName = "JC_Calc_DepartureCTOAddressOrg";
			zGuidFindBoxColumnStyleInfo4.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|eb841af6-8e41-4bec-a186-34a59cfedc8d", "Load CTO");
			zGuidFindBoxColumnStyleInfo4.IsVisible = false;
			zGuidFindBoxColumnStyleInfo4.ToolTip = "Departure CTO / Terminal";
			zGuidFindBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|4e7c46ac-80ca-4554-9194-a865a59ffd91", "Load CTO");
			zDropEditColumnStyleInfo7.ColumnName = "JC_Calc_DepartureCTOAddressCode";
			zDropEditColumnStyleInfo7.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|eb841af6-8e41-4bec-a186-34a59cfedc8d", "Load CTO");
			zDropEditColumnStyleInfo7.IsVisible = false;
			zDropEditColumnStyleInfo7.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo7.ToolTip = "Departure CTO / Terminal";
			zDropEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zGuidFindBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|ef20a3b0-353e-4dcc-8608-9812a92c5913", "Discharge CTO Org.", "Discharge CTO Organization");
			zGuidFindBoxColumnStyleInfo5.ColumnName = "JC_Calc_ArrivalCTOAddressOrg";
			zGuidFindBoxColumnStyleInfo5.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|985ffb62-6af2-4184-9b0d-068852be5f14", "Discharge CTO");
			zGuidFindBoxColumnStyleInfo5.IsVisible = false;
			zGuidFindBoxColumnStyleInfo5.ToolTip = "Arrival CTO / Terminal";
			zGuidFindBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(130);
			zDropEditColumnStyleInfo8.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|2dff9a74-0d33-4661-a9eb-7233f356a6c7", "Discharge CTO");
			zDropEditColumnStyleInfo8.ColumnName = "JC_Calc_ArrivalCTOAddressCode";
			zDropEditColumnStyleInfo8.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|985ffb62-6af2-4184-9b0d-068852be5f14", "Discharge CTO");
			zDropEditColumnStyleInfo8.IsVisible = false;
			zDropEditColumnStyleInfo8.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo8.ToolTip = "Arrival CTO / Terminal";
			zDropEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zDateEditColumnStyleInfo2.ColumnName = "JC_FCLAvailable";
			zDateEditColumnStyleInfo2.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo2.IsVisible = false;
			zDateEditColumnStyleInfo2.ToolTip = "FCL Container has been made available by CTO at";
			zDateEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|f4044f6f-b236-4b96-8a93-4ced08d05b91", "Unpack At Org.", "Unpack At Organization");
			zGuidFindBoxColumnStyleInfo6.ColumnName = "JC_Calc_ArrivalUnpackAddressOrg";
			zGuidFindBoxColumnStyleInfo6.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|be371469-6a14-492a-aca8-2062023288c9", "Unpack At");
			zGuidFindBoxColumnStyleInfo6.IsVisible = false;
			zGuidFindBoxColumnStyleInfo6.ToolTip = "Unpack container at";
			zGuidFindBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo9.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|61ab6246-42d1-4a4a-aa1c-3344088de729", "Unpack At");
			zDropEditColumnStyleInfo9.ColumnName = "JC_Calc_ArrivalUnpackAddressCode";
			zDropEditColumnStyleInfo9.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|be371469-6a14-492a-aca8-2062023288c9", "Unpack At");
			zDropEditColumnStyleInfo9.IsVisible = false;
			zDropEditColumnStyleInfo9.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo9.ToolTip = "Unpack container at";
			zDropEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zCheckBoxColumnStyleInfo1.ColumnName = "JC_IsSealOk";
			zCheckBoxColumnStyleInfo1.IsVisible = false;
			zCheckBoxColumnStyleInfo1.ToolTip = "Is Seal Ok";
			zCheckBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo3.ColumnName = "JC_LCLAvailable";
			zDateEditColumnStyleInfo3.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.ToolTip = "LCL has been made available at CFS/Depot";
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo4.ColumnName = "JC_LCLStorageCommences";
			zDateEditColumnStyleInfo4.DateTimeFormat = Enterprise.ZArchitecture.Core.ZDateTimePickerFormat.Short;
			zDateEditColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo4.ToolTip = "LCL storage commences at CFS/Depot";
			zDateEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zGuidFindBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|a45c3e15-8b65-4caa-96f0-3b0cbe170e98", "Return Empty To Org.", "Return Empty To Organization");
			zGuidFindBoxColumnStyleInfo7.ColumnName = "JC_Calc_ArrivalContainerYardAddressOrg";
			zGuidFindBoxColumnStyleInfo7.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|938ffe4b-a4ac-4c8a-b61e-049ca957a8a1", "Return Empty To");
			zGuidFindBoxColumnStyleInfo7.IsVisible = false;
			zGuidFindBoxColumnStyleInfo7.ToolTip = "Point for Empty/Import container Return";
			zGuidFindBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zDropEditColumnStyleInfo10.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|1b45a71b-863f-4553-944d-0425f88a012e", "Return Empty To");
			zDropEditColumnStyleInfo10.ColumnName = "JC_Calc_ArrivalContainerYardAddressCode";
			zDropEditColumnStyleInfo10.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|938ffe4b-a4ac-4c8a-b61e-049ca957a8a1", "Return Empty To");
			zDropEditColumnStyleInfo10.IsVisible = false;
			zDropEditColumnStyleInfo10.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo10.ToolTip = "Point for Empty/Import container Return";
			zDropEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(150);
			zTextBoxColumnStyleInfo2.ColumnName = "JC_AdditionalSealNum";
			zTextBoxColumnStyleInfo2.IsVisible = false;
			zTextBoxColumnStyleInfo2.ToolTip = "2nd or Additional Seal Number";
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo3.ColumnName = "JC_Additional2SealNum";
			zTextBoxColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo3.ToolTip = "3rd or Additional Seal Number";
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|474659ae-2b41-4880-a04e-d392abf28ae0", "Capacity", "Container Capacity", "");
			zCalcEditColumnStyleInfo2.ColumnName = "JC_Calc_ContainerCapacity";
			zCalcEditColumnStyleInfo2.IsVisible = false;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|14c542c2-599e-45b7-9e05-c3c99e7c83ae", "Max Gross Wt", "Max Gross Weight", "");
			zCalcEditColumnStyleInfo3.ColumnName = "JC_Calc_MaxGrossWeight";
			zCalcEditColumnStyleInfo3.IsVisible = false;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo4.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|6865ee9e-e784-4fb7-924f-982844b4db77", "Tare Weight (On File)");
			zCalcEditColumnStyleInfo4.ColumnName = "JC_Calc_TareWeight";
			zCalcEditColumnStyleInfo4.IsVisible = false;
			zCalcEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("02049aa1-fa8e-4eef-aa8d-4a7424460eff", "Override Gross Weight");
			zCheckBoxColumnStyleInfo6.ColumnName = "IsGrossWeightOverriddenForBinding";
			zCheckBoxColumnStyleInfo6.IsVisible = false;
			zCheckBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(64);
			zCheckBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("C79B0AC -2A0F-4CF2-B1DA-C23A3836003C", "Non-Operating Reefer");
			zCheckBoxColumnStyleInfo7.ColumnName = "JC_IsNonOperativeReefer";
			zCheckBoxColumnStyleInfo7.IsVisible = false;
			zCheckBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(64);
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|52399709-6a8d-4f11-b2a7-418e0354a23c", "Gross Weight");
			zCalcEditColumnStyleInfo5.ColumnName = "JC_GrossWeight";
			zCalcEditColumnStyleInfo5.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|349d00a7-f221-4f7b-893e-190f08548c25", "Gross Weight");
			zCalcEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo11.ColumnName = "JC_GrossWeightUQ";
			zDropEditColumnStyleInfo11.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|349d00a7-f221-4f7b-893e-190f08548c25", "Gross Weight");
			zDropEditColumnStyleInfo11.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zTextBoxColumnStyleInfo4.ColumnName = "JC_TrainWagonNumber";
			zTextBoxColumnStyleInfo4.IsVisible = false;
			zTextBoxColumnStyleInfo4.ToolTip = "Train Wagon Number";
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo2.ColumnName = "JC_IsShipperOwned";
			zCheckBoxColumnStyleInfo2.IsVisible = false;
			zCheckBoxColumnStyleInfo2.ToolTip = "Is Shipper Owned";
			zCheckBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.ColumnName = "JC_AirVentFlow";
			zCalcEditColumnStyleInfo6.Decimals = 0;
			zCalcEditColumnStyleInfo6.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|00071511-e9c0-4da0-807c-f735d0677cd7", "Air Vent");
			zCalcEditColumnStyleInfo6.IsVisible = false;
			zCalcEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo12.ColumnName = "JC_AirVentFlowRateUnit";
			zDropEditColumnStyleInfo12.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|00071511-e9c0-4da0-807c-f735d0677cd7", "Air Vent");
			zDropEditColumnStyleInfo12.IsVisible = false;
			zDropEditColumnStyleInfo12.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo5.ColumnName = "JC_TempRecorderSerialNo";
			zTextBoxColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo13.ColumnName = "JC_ContainerStatus";
			zDropEditColumnStyleInfo13.IsVisible = false;
			zDropEditColumnStyleInfo13.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo14.ColumnName = "JC_ContainerQuality";
			zDropEditColumnStyleInfo14.IsVisible = false;
			zDropEditColumnStyleInfo14.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo15.ColumnName = "JC_AdditionalSealParty";
			zDropEditColumnStyleInfo15.IsVisible = false;
			zDropEditColumnStyleInfo15.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zDropEditColumnStyleInfo16.ColumnName = "JC_Additional2SealParty";
			zDropEditColumnStyleInfo16.IsVisible = false;
			zDropEditColumnStyleInfo16.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(120);
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.ColumnName = "JC_DeliverySequence";
			zCalcEditColumnStyleInfo7.IsVisible = false;
			zCalcEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.ColumnName = "JC_TareWeight";
			zCalcEditColumnStyleInfo8.IsVisible = false;
			zCalcEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo9.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo9.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|afe0d41d-dadf-47f4-a9de-65909748f0ec", "Goods Weight");
			zCalcEditColumnStyleInfo9.ColumnName = "GoodsWeightForBinding";
			zCalcEditColumnStyleInfo9.IsVisible = false;
			zCalcEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo10.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo10.ColumnName = "JC_DunnageWeight";
			zCalcEditColumnStyleInfo10.IsVisible = false;
			zCalcEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo5.ColumnName = "JC_EmptyRequired";
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo6.ColumnName = "JC_ReleaseNum";
			zTextBoxColumnStyleInfo6.IsVisible = false;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo6.ColumnName = "JC_ContainerYardEmptyPickupGateOut";
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo7.ColumnName = "JC_DepartureCartageAdvised";
			zDateEditColumnStyleInfo7.IsVisible = false;
			zDateEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo7.ColumnName = "JC_DepartureCartageRef";
			zTextBoxColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|1768cb99-31a9-4353-9f54-4fbe3f12d30a", "Export Port Transport Ref");
			zTextBoxColumnStyleInfo7.IsVisible = false;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo8.ColumnName = "JC_DepartureCartageComplete";
			zDateEditColumnStyleInfo8.IsVisible = false;
			zDateEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo9.ColumnName = "JC_DepartureSlotDateTime";
			zDateEditColumnStyleInfo9.IsVisible = false;
			zDateEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo8.ColumnName = "JC_DepartureSlotReference";
			zTextBoxColumnStyleInfo8.IsVisible = false;
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo10.ColumnName = "JC_FCLWharfGateIn";
			zDateEditColumnStyleInfo10.IsVisible = false;
			zDateEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo11.ColumnName = "JC_FCLOnBoardVessel";
			zDateEditColumnStyleInfo11.IsVisible = false;
			zDateEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo12.ColumnName = "JC_FCLUnloadFromVessel";
			zDateEditColumnStyleInfo12.IsVisible = false;
			zDateEditColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo9.ColumnName = "JC_ContainerImportDORelease";
			zTextBoxColumnStyleInfo9.IsVisible = false;
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo13.ColumnName = "JC_ArrivalCartageAdvised";
			zDateEditColumnStyleInfo13.IsVisible = false;
			zDateEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo10.ColumnName = "JC_ArrivalCartageRef";
			zTextBoxColumnStyleInfo10.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|d9bd6a19-d48b-49ec-a86c-070ae240dfb6", "Import Port Transport Ref");
			zTextBoxColumnStyleInfo10.IsVisible = false;
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo14.ColumnName = "JC_ArrivalSlotDateTime";
			zDateEditColumnStyleInfo14.IsVisible = false;
			zDateEditColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo15.ColumnName = "JC_FCLWharfGateOut";
			zDateEditColumnStyleInfo15.IsVisible = false;
			zDateEditColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo16.ColumnName = "JC_ArrivalEstimatedDelivery";
			zDateEditColumnStyleInfo16.IsVisible = false;
			zDateEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo17.ColumnName = "JC_ArrivalCartageComplete";
			zDateEditColumnStyleInfo17.IsVisible = false;
			zDateEditColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo18.ColumnName = "JC_EmptyReturnedBy";
			zDateEditColumnStyleInfo18.IsVisible = false;
			zDateEditColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo19.ColumnName = "JC_EmptyReadyForReturn";
			zDateEditColumnStyleInfo19.IsVisible = false;
			zDateEditColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo20.ColumnName = "JC_ContainerYardEmptyReturnGateIn";
			zDateEditColumnStyleInfo20.IsVisible = false;
			zDateEditColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo17.ColumnName = "JC_GrossWeightVerificationType";
			zDropEditColumnStyleInfo17.IsVisible = false;
			zDropEditColumnStyleInfo17.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo17.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo21.ColumnName = "JC_GrossWeightVerificationDateTime";
			zDateEditColumnStyleInfo21.IsVisible = false;
			zDateEditColumnStyleInfo21.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zMultiControlColumnStyleInfo1.ColumnName = "GrossWeightVerifiedByNameOrPK";
			zMultiControlColumnStyleInfo1.FieldTypeColumnName = "GrossWeightVerifiedByFieldType";
			zMultiControlColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("269c80cd-fd81-4196-9345-146133f06a80", "Verified By", "VGM Verified By");
			zMultiControlColumnStyleInfo1.IsVisible = false;
			zMultiControlColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo18.ColumnName = "WeightUnitForBinding";
			zDropEditColumnStyleInfo18.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("dd91824e-3aa5-4f92-8630-184fab9b4f39", "Weight UQ");
			zDropEditColumnStyleInfo18.IsVisible = false;
			zDropEditColumnStyleInfo18.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo18.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo3.ColumnName = "JC_IsEmptyContainer";
			zCheckBoxColumnStyleInfo3.IsVisible = false;
			zCheckBoxColumnStyleInfo3.ToolTip = "Is Empty";
			zCheckBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo4.ColumnName = "JC_IsDamaged";
			zCheckBoxColumnStyleInfo4.IsVisible = false;
			zCheckBoxColumnStyleInfo4.ToolTip = "Is Damaged";
			zCheckBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCheckBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.Forwarding.GUI.Res.GetData("169c144e-4756-4502-980e-e171ccc40075", "Temp. Controlled");
			zCheckBoxColumnStyleInfo5.ColumnName = "JC_IsControlledAtmosphere";
			zCheckBoxColumnStyleInfo5.IsVisible = false;
			zCheckBoxColumnStyleInfo5.ToolTip = "Temp Controlled";
			zCheckBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCalcEditColumnStyleInfo11.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo11.ColumnName = "JC_SetPointTemp";
			zCalcEditColumnStyleInfo11.Decimals = 1;
			zCalcEditColumnStyleInfo11.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|17f8cb51-3ada-4634-80c8-3bf54848da97", "Temperature Set Point");
			zCalcEditColumnStyleInfo11.IsVisible = false;
			zCalcEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo19.ColumnName = "JC_SetPointTempUnit";
			zDropEditColumnStyleInfo19.GroupName = Enterprise.Freight.Forwarding.GUI.Res.GetData("ZModuleButtonGrid|17f8cb51-3ada-4634-80c8-3bf54848da97", "Temperature Set Point");
			zDropEditColumnStyleInfo19.IsVisible = false;
			zDropEditColumnStyleInfo19.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zTextBoxColumnStyleInfo11.ColumnName = "JC_TempRecorderSerialNo";
			zTextBoxColumnStyleInfo11.IsVisible = false;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zCodeFindBoxColumnStyleInfo1.ColumnName = "JC_RH_NKContainerCommodityCode";
			zCodeFindBoxColumnStyleInfo1.IsVisible = false;
			zCodeFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDateEditColumnStyleInfo22.ColumnName = "JC_ArrivalCTOStorageStartDate";
			zDateEditColumnStyleInfo22.IsVisible = false;
			zDateEditColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			zDropEditColumnStyleInfo20.ColumnName = "JC_GrossWeightVerificationStatus";
			zDropEditColumnStyleInfo20.IsVisible = false;
			zDropEditColumnStyleInfo20.ShowHorizontalScrollBar = false;
			zDropEditColumnStyleInfo20.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			emptyReturnReferenceColumnStyleInfo.ColumnName = "JC_EmptyReturnReference";
			emptyReturnReferenceColumnStyleInfo.IsVisible = false;
			emptyReturnReferenceColumnStyleInfo.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);
			allocationIDColumnStyleInfo1.ColumnName = "JC_RCA_AllocationLine";
			allocationIDColumnStyleInfo1.IsVisible = false;
			allocationIDColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(80);

			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo8);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo9);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo10);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo11);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo2);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo12);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo13);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo14);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo15);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo16);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo9);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo10);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo8);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo9);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo10);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo11);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo12);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo13);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo14);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo15);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo16);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo17);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo18);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo19);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo20);
			this.JobContainerBoundGrid.ColumnStyles.Add(zMultiControlColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo17);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo21);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo18);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo3);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo4);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo5);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo11);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo19);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.JobContainerBoundGrid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo1);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDateEditColumnStyleInfo22);
			this.JobContainerBoundGrid.ColumnStyles.Add(zDropEditColumnStyleInfo20);
			this.JobContainerBoundGrid.ColumnStyles.Add(emptyReturnReferenceColumnStyleInfo);
			this.JobContainerBoundGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			if (ContractsPermissions.IsAllocationsVisible())
			{
				this.JobContainerBoundGrid.ColumnStyles.Add(allocationIDColumnStyleInfo1);
			}
			this.JobContainerBoundGrid.GridId = "77449eec-8a56-4971-b735-99b2528371b3";
			// 
			// 
			// 
			this.JobContainerBoundGrid.InnerGrid.AllowNavigation = false;
			this.JobContainerBoundGrid.InnerGrid.Anchor = ((AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
			| System.Windows.Forms.AnchorStyles.Left)
			| System.Windows.Forms.AnchorStyles.Right)));
			this.JobContainerBoundGrid.InnerGrid.CaptionVisible = false;
			this.JobContainerBoundGrid.InnerGrid.CopySelectedRowsAllowed = true;
			this.JobContainerBoundGrid.InnerGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.JobContainerBoundGrid.InnerGrid.IsDataVersionLogsMenuItemVisible = true;
			this.JobContainerBoundGrid.InnerGrid.LayoutKey = "JobContainerBoundGrid";
			this.JobContainerBoundGrid.InnerGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(2, 2, true);
			this.JobContainerBoundGrid.InnerGrid.Name = "Grid";
			this.JobContainerBoundGrid.InnerGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(967, 103, true);
			this.JobContainerBoundGrid.InnerGrid.TabIndex = 0;
			this.JobContainerBoundGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(8, 0, true);
			this.JobContainerBoundGrid.Name = "JobContainerBoundGrid";
			this.JobContainerBoundGrid.NameOfAGridElement = Enterprise.Freight.Forwarding.GUI.Res.GetData("4A74B310-2111-4584-9159-534652483391", "Container");
			this.JobContainerBoundGrid.ReadOnly = false;
			this.JobContainerBoundGrid.ShowAttachButton = false;
			this.JobContainerBoundGrid.ShowDetachButton = false;
			this.JobContainerBoundGrid.ShowNewButton = false;
			this.JobContainerBoundGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(972, 140, true);
			this.JobContainerBoundGrid.TabIndex = 0;
			// 
			// panel3
			// 
			this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel3.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.panel3.Name = "panel3";
			this.panel3.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(988, 8, true);
			this.panel3.TabIndex = 0;
			// 
			// ConsolContainerUserControl
			// 
			this.CaptionRenderingEnabled = true;
			this.Controls.Add(this.panel2);
			this.Name = "ConsolContainerUserControl";
			this.ShouldSerializeTabPageMethods = false;
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(988, 560, true);
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			this.panel2.ResumeLayout(false);
			this.panel2.PerformLayout();
			this.panel1.ResumeLayout(false);
			this.panel1.PerformLayout();
			this.containersUserControl1.ResumeLayout(true);
			this.containersUserControl1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.JobContainerBoundGrid.InnerGrid)).EndInit();
			this.JobContainerBoundGrid.ResumeLayout(true);
			this.JobContainerBoundGrid.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
	}
}
