<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <OutputPath>..\..\..\..\..\bin\</OutputPath>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Setup|AnyCPU'">
    <OutputPath>bin\Setup\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Enterprise.RemoteDesktopServices.Shared" />
    <Reference Include="Microsoft.IdentityModel.Tokens" />
    <Reference Include="nunit.framework" />
    <Reference Include="System.Buffers" />
    <Reference Include="System.IdentityModel.Tokens.Jwt" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Text.Json" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Server\Enterprise.RemoteDesktopServices.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>