<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Enterprise.ZArchitecture.Web.Shared.Test</RootNamespace>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <IsCwTestProject>false</IsCwTestProject>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ActiveDirectory.TestFramework" />
    <Reference Include="Microsoft.Web.Administration" />
    <Reference Include="WTG.DevTools.TestFramework" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>