<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.TransportCommon.Integration</RootNamespace>
    <AssemblyName>Enterprise.TransportCommon.Integration</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="WTG.RTUS.Interface" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>