<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientDFD.Test</AssemblyName>
    <RootNamespace>Enterprise.Client.DFD.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientDFD\ZClientDFD.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Business\Import\USOrganisationDataUpdate\TestFiles\test.csv">
      <LogicalName>test.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Business\Import\USProductDataImport\TestFiles\DSV CHB Product Data Import.csv">
      <LogicalName>DSV CHB Product Data Import.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Business\Import\USSupplierDataImport\TestFiles\DSVMIDs.csv">
      <LogicalName>DSVMIDs.csv</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>