<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.DFD.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <EmbeddedResource Include="Business\Import\USOrganisationDataUpdate\TestFiles\test.csv">
      <LogicalName>test.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Business\Import\USProductDataImport\TestFiles\DSV CHB Product Data Import.csv">
      <LogicalName>DSV CHB Product Data Import.csv</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Business\Import\USSupplierDataImport\TestFiles\DSVMIDs.csv">
      <LogicalName>DSVMIDs.csv</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientDFD\ZClientDFD.csproj" />
  </ItemGroup>
</Project>