<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.FJ.Manifest.Business.Testing</RootNamespace>
    <AssemblyName>Enterprise.Customs.FJ.Manifest.Business.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business" />
    <Reference Include="Enterprise.Customs.ASYCUDA.Business.Test" />
    <Reference Include="Enterprise.Customs.ASYCUDAManifest.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Customs.ManifestBase.Test" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.Customs.Universal.Test" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.FJ.Manifest.Business.csproj" />
  </ItemGroup>
</Project>