<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Accounting.ElectronicMessaging.Testing</RootNamespace>
    <AssemblyName>Enterprise.Accounting.ElectronicMessaging.Testing</AssemblyName>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <Reference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Accounting.eInvoicing.Egypt" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Test" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.FeatureControl.Abstractions" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Accounting.Business" />
    <Reference Include="Enterprise.Accounting.Business.Testing" />
    <Reference Include="Enterprise.Accounting.CountryCompliance.Interfaces" />
    <Reference Include="Enterprise.Accounting.DataTransfer" />
    <Reference Include="Enterprise.Accounting.Export" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Accounting.Utility.Testing" />
    <Reference Include="Enterprise.Accounting.TaxFramework.Business" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentScanning.Business" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Business.Test" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Business.Test" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Rating.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Registry.Business.Test" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Management" />
    <Reference Include="Enterprise.UniversalDataBuss.ServiceTasks" />
    <Reference Include="Enterprise.UniversalDataBuss.Testing" />
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Test" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="JsonPointer.Net" />
    <Reference Include="JsonSchema.Net" />
    <Reference Include="MailManager" />
    <Reference Include="Moq" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="Newtonsoft.Json.Schema" />
    <Reference Include="NUnitCore" />
    <Reference Include="NUnitCore.ExtendedAssertions" />
    <Reference Include="Resources" />
    <Reference Include="WTG.TestHelpers.Xml" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Text.Json" />
    <Reference Include="System.Threading.Tasks.Extensions" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Common\TestFile\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Hungary\XmlBuilders\TestCases\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="India\TestMessages\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Italy\FatturaElettronicaXmlWriter\Validation\TestFiles\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Romania\UniversalEventXml\*.xml" />
    <EmbeddedResource Include="Romania\UniversalEventXml\ZippedXmlFiles\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Taiwan\TestCases\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Turkey\EInvoiceXmlWriter\Xml\*.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Vietnam\EInvoice\TestCases\*.json" />
  </ItemGroup>
  <ProjectExtensions />
  <ItemGroup>
    <ProjectReference Include="..\Accounting.ElectronicMessaging\Accounting.ElectronicMessaging.csproj" />
  </ItemGroup>
</Project>