//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.DocumentEngine.Shared
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoStmDefaultPrinterValidation : ZValidation
	{
		protected AutoStmDefaultPrinterValidation(AutoStmDefaultPrinter Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoStmDefaultPrinterValidation); }
		}

		/// <summary>
		/// Add more validation to the StmDefaultPrinter's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoStmDefaultPrinterValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The StmDefaultPrinter's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoStmDefaultPrinterValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region SDP_NumberOfCopies

		public void ValidateSDP_NumberOfCopies()
		{
			ZValidationInternals.Validate(Parent.SDP_NumberOfCopiesInfo, GetSDP_NumberOfCopiesValidationInvoker());
		}

		RunValidationInvoker GetSDP_NumberOfCopiesValidationInvoker()
		{
			return delegate
			{
				CheckSDP_NumberOfCopies();
			};
		}

		protected virtual void CheckSDP_NumberOfCopies()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region SDP_SI

		public void ValidateSDP_SI()
		{
			ZValidationInternals.Validate(Parent.SDP_SIInfo, GetSDP_SIValidationInvoker());
		}

		RunValidationInvoker GetSDP_SIValidationInvoker()
		{
			return delegate
			{
				CheckSDP_SIIsValidZGuid();
				CheckSDP_SI();
			};
		}

		protected virtual void CheckSDP_SIIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.SDP_SIInfo);
		}

		protected virtual void CheckSDP_SI()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region SDP_SQ_Printer

		public void ValidateSDP_SQ_Printer()
		{
			ZValidationInternals.Validate(Parent.SDP_SQ_PrinterInfo, GetSDP_SQ_PrinterValidationInvoker());
		}

		RunValidationInvoker GetSDP_SQ_PrinterValidationInvoker()
		{
			return delegate
			{
				CheckSDP_SQ_PrinterIsNotEmpty();
				CheckSDP_SQ_PrinterIsValidZGuid();
				CheckSDP_SQ_Printer();
			};
		}

		protected virtual void CheckSDP_SQ_PrinterIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.SDP_SQ_PrinterInfo);
		}

		protected virtual void CheckSDP_SQ_PrinterIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.SDP_SQ_PrinterInfo);
		}

		protected virtual void CheckSDP_SQ_Printer()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region SDP_SubjectID

		public void ValidateSDP_SubjectID()
		{
			ZValidationInternals.Validate(Parent.SDP_SubjectIDInfo, GetSDP_SubjectIDValidationInvoker());
		}

		RunValidationInvoker GetSDP_SubjectIDValidationInvoker()
		{
			return delegate
			{
				CheckSDP_SubjectIDIsNotEmpty();
				CheckSDP_SubjectIDIsValidZGuid();
				CheckSDP_SubjectID();
			};
		}

		protected virtual void CheckSDP_SubjectIDIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.SDP_SubjectIDInfo);
		}

		protected virtual void CheckSDP_SubjectIDIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.SDP_SubjectIDInfo);
		}

		protected virtual void CheckSDP_SubjectID()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region SDP_SubjectTableCode

		public void ValidateSDP_SubjectTableCode()
		{
			ZValidationInternals.Validate(Parent.SDP_SubjectTableCodeInfo, GetSDP_SubjectTableCodeValidationInvoker());
		}

		RunValidationInvoker GetSDP_SubjectTableCodeValidationInvoker()
		{
			return delegate
			{
				CheckSDP_SubjectTableCodeIsWesternEuropean();
				CheckSDP_SubjectTableCode();
			};
		}

		protected virtual void CheckSDP_SubjectTableCodeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.SDP_SubjectTableCodeInfo);
		}

		protected virtual void CheckSDP_SubjectTableCode()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region SDP_SU_Document

		public void ValidateSDP_SU_Document()
		{
			ZValidationInternals.Validate(Parent.SDP_SU_DocumentInfo, GetSDP_SU_DocumentValidationInvoker());
		}

		RunValidationInvoker GetSDP_SU_DocumentValidationInvoker()
		{
			return delegate
			{
				CheckSDP_SU_DocumentIsValidZGuid();
				CheckSDP_SU_Document();
			};
		}

		protected virtual void CheckSDP_SU_DocumentIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.SDP_SU_DocumentInfo);
		}

		protected virtual void CheckSDP_SU_Document()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateSDP_NumberOfCopies();
				ValidateSDP_SI();
				ValidateSDP_SQ_Printer();
				ValidateSDP_SubjectID();
				ValidateSDP_SubjectTableCode();
				ValidateSDP_SU_Document();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoStmDefaultPrinter Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
