@StorageApi_HostAddress = http://localhost:5249
@Authorization_Header = Basic VVNDOkRNJHBoYXNlMQ==

HEAD {{StorageApi_HostAddress}}/wtg/alive
Accept: application/json

###
GET {{StorageApi_HostAddress}}/wtg/status
Accept: application/json

###
GET {{StorageApi_HostAddress}}/USC/docs/ViaDMS/HYEDUSCMT
Accept: application/json
Authorization: {{Authorization_Header}}

###
PUT {{StorageApi_HostAddress}}/USC/docs/ViaDMS/HYEDUSCMT
Accept: application/json
Content-Type: application/json
Authorization: {{Authorization_Header}}

{ "ViaDMS": true }
###
GET {{StorageApi_HostAddress}}/USC/blobs/RefFiles/FIRMS
Accept: application/octet-stream
Authorization: {{Authorization_Header}}

###
PUT {{StorageApi_HostAddress}}/USC/blobs/RefFiles/FIRMS
Accept: application/json
Content-Type: application/octet-stream
Authorization: {{Authorization_Header}}

░░░░░░░▄▀▀▀▀█░░░░░░░░░░░░░░░░░░░░
░░░░░░█▀░░░░█░░░░░░░░░░░░░░░░░░░░
░░░░░█░░░░░░█▀▀▀▄▄░░░░░░▓░░░░░░░░
░░░░▄█░░░░░░░░░░░░▀▀▄▄░▓▓▓░░░░░░░
░░░▄█░░░░░░░░░░░░░░░░░▀▓▓▓▓▀▀▀█░░
▀▄▄█░░░░░░░░░░░░░░░░▓▓▓▓▓▓▓▓░░█░░
▀▄█░▀▄░░░░▄▄░░░░░░▓▓▓▓▓▓▓░░▓▓▓▓▓▓
▄▀█▀▄░░░░███░░░░░░░░░▓▓▓▓▓▓▓▓▓▓▓░
░▀█▀▄░░░░▀▀░░░░░░░░░▄▄░░░▓▓▓▓▓░░░
░░▀█░░░░░░░░▄▄░░░░░███░░░░▓▓░█░░░
░░░▀█░░░░░░█░░▀▄░░░▀▀░░░░░▓░█▀░░░
░░░░▀█░░░░░░▀▄▄▀░░░░░░░░▀▄░█▀░░░░
░░░░░░▀█▄░░░░░░░░░░░░░▀▄░░██░░░░░
░░░░░░░░░▀█▄░░░░░░░░▀▄░░██▀░▀░░░░
░░░░░░░░░░░░▀▀▄▄▄▄▄▄▄█▀█░░▀▄░░░░░
░░░░░░░░░░░░░░░░░░░░░░░░▀░░░░░░░░
###
