<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.RemoteDesktopServices.Server" />
    <Reference Include="Microsoft.Toolkit.Forms.UI.Controls.WebView" />
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounting.TaxFramework\Business\Accounting.TaxFramework.Business.csproj" />
    <ProjectReference Include="..\Accounting.TaxFramework\GUI\Accounting.TaxFramework.GUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="DataExport\CASSAdjustment\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Job Management\AutoJobClosureDiagnosisForm.cs" />
    <Compile Update="Job Management\JobInvoicingForm.cs" />
    <Compile Update="JobInvoicing\Apportionment\JobConsolCostingForm.cs" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>