<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.M1A.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common.Testing" />
    <Reference Include="NUnitCore" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineCore.Test" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="DocumentWrappers" />
    <Reference Include="DocumentWrappers.Test" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Accounting.Business" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientM1A\ZClientM1A.csproj" />
  </ItemGroup>
</Project>