<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.Messaging.Integration\Enterprise.Messaging.Integration.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>