<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DataTools.DbBackupAndRestore.Business.Testing</RootNamespace>
    <AssemblyName>Enterprise.DbBackupAndRestore.Business.Test</AssemblyName>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription_RefDb_Trf_CA.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription_SD001.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase_Audit.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase_EDW.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-CW-RefDatabase.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription_RefDb_Trf_CA.bak" />
    <None Remove="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription_SD001.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest_Audit.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest_EDW.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest_SD001.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest_SD002.bak" />
    <None Remove="Restore\TestFiles\DatabaseRestoreTest_NotInAG.bak" />
    <None Remove="Restore\TestFiles\Odyssey2WithDescription.bak" />
    <None Remove="Restore\TestFiles\Odyssey2WithDescription_RefDb_Trf_CA.bak" />
    <None Remove="Restore\TestFiles\Odyssey2WithDescription_SD001.bak" />
    <None Remove="Restore\TestFiles\OdysseyNoDescription.bak" />
    <None Remove="Restore\TestFiles\OdysseyNoDescription_RefDb_Trf_CA.bak" />
    <None Remove="Restore\TestFiles\OdysseyNoDescription_SD001.bak" />
    <None Remove="Restore\TestFiles\OdysseyWithBiServerDetails.bak" />
    <None Remove="Restore\TestFiles\OdysseyWithDescription.bak" />
    <None Remove="Restore\TestFiles\OdysseyWithDescription_Diff.dbk" />
    <None Remove="Restore\TestFiles\OdysseyWithDescription_RefDb_Trf_CA.bak" />
    <None Remove="Restore\TestFiles\OdysseyWithDescription_SD001.bak" />
    <None Remove="Restore\TestFiles\OdysseyWithOldRegistryItem.sql" />
    <None Remove="Restore\TestFiles\Odyssey_Diff.dbk" />
    <None Remove="Restore\TestFiles\TestOdysseyRestoreTrn.bak" />
    <None Remove="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000001.trn" />
    <None Remove="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000002.trn" />
    <None Remove="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000003.trn" />
    <None Remove="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000004.trn" />
    <None Remove="Restore\TestFiles\testProdCopy.bak" />
    <None Remove="Restore\TestFiles\testProdCopyCdc.bak" />
    <None Remove="Restore\TestFiles\testProdCopyCdc_Audit.bak" />
    <None Remove="Restore\TestFiles\testProdCopyCdc_EDW.bak" />
    <None Remove="Restore\TestFiles\testProdCopyWithADLogins.bak" />
    <None Remove="Restore\TestFiles\testProdCopy_Diff.dbk" />
    <None Remove="Restore\TestFiles\TestProdCopy_UserRepository.bak" />
    <None Remove="Restore\TestFiles\testProdDbCopyWithInterchagneAndMessage.bak" />
    <None Remove="Restore\TestFiles\testProdWithBiServers.bak" />
    <None Remove="Restore\TestFiles\testProdWithCdc.bak" />
    <None Remove="Restore\TestFiles\testProdWithoutCdc.bak" />
    <None Remove="Restore\TestFiles\testRestore.bak" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest.bak" />
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest_Audit.bak" />
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest_EDW.bak" />
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest_SD002.bak" />
    <EmbeddedResource Include="Restore\TestFiles\DatabaseRestoreTest_NotInAG.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription_RefDb_Trf_CA.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20151023-111725_S-SYDCO-WJBL-1_D-OdysseyWithDescription_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase_Audit.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20161028-110830_S-SYDCO-WJMG-1_D-testBiDatabase_EDW.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-CW-RefDatabase.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription_RefDb_Trf_CA.bak" />
    <EmbeddedResource Include="Restore\TestFiles\CW1Bkp_T-20230630-114910_S-SYDCO-LMZT-1_D-OdysseyNoDescription_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\Odyssey2WithDescription.bak" />
    <EmbeddedResource Include="Restore\TestFiles\Odyssey2WithDescription_RefDb_Trf_CA.bak" />
    <EmbeddedResource Include="Restore\TestFiles\Odyssey2WithDescription_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyNoDescription.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyNoDescription_RefDb_Trf_CA.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyNoDescription_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithBiServerDetails.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithDescription.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithDescription_Diff.dbk" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithDescription_RefDb_Trf_CA.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithDescription_SD001.bak" />
    <EmbeddedResource Include="Restore\TestFiles\OdysseyWithOldRegistryItem.sql" />
    <EmbeddedResource Include="Restore\TestFiles\Odyssey_Diff.dbk" />
    <EmbeddedResource Include="Restore\TestFiles\TestOdysseyRestoreTrn.bak" />
    <EmbeddedResource Include="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000001.trn" />
    <EmbeddedResource Include="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000002.trn" />
    <EmbeddedResource Include="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000003.trn" />
    <EmbeddedResource Include="Restore\TestFiles\TestOdysseyRestoreTrn_00000000000004.trn" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopy.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopyCdc.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopyCdc_Audit.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopyCdc_EDW.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopyWithADLogins.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdCopy_Diff.dbk" />
    <EmbeddedResource Include="Restore\TestFiles\TestProdCopy_UserRepository.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdDbCopyWithInterchagneAndMessage.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdWithBiServers.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdWithCdc.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testProdWithoutCdc.bak" />
    <EmbeddedResource Include="Restore\TestFiles\testRestore.bak" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AppDomainWrappers.Net" />
    <Reference Include="AWSSDK.Core" />
    <Reference Include="AWSSDK.IdentityManagement" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Test" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.DbBackup.Engine" />
    <Reference Include="Enterprise.DbUpgrader.Resource.Version" />
    <Reference Include="Enterprise.DbUpgrader.Shared" />
    <Reference Include="Enterprise.DocumentScanning.Business" />
    <Reference Include="Enterprise.DocumentScanning.Business.Test" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Core.Encryption" />
    <Reference Include="log4net" />
    <Reference Include="Resources" />
    <Reference Include="WTG.Foundation.Cryptography.UserSecrets" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DbBackupAndRestore.Business\DbBackupAndRestore.Business.csproj" />
  </ItemGroup>
</Project>