<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.LandedCosting.Module</AssemblyName>
    <RootNamespace>Enterprise.LandedCosting.Module</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.LandedCosting.GUI.Winzor.csproj" />
  </ItemGroup>
</Project>