<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.ZAReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.ZAReferenceData.Business</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug;Release;UAT</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZAReferenceData.Services\ZAReferenceData.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>