<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.GB.H7.Module.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <RootNamespace>Enterprise.Customs.GB.H7.Module.Testing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\H7.Module\Enterprise.Customs.GB.H7.Module.csproj" />
  </ItemGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>