// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.CusInBondMoveHeaderTest.TestICBPEDIMessageMessageTextNumberPlaceHolderFillerMembers")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:534,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.CusInBondMoveHeaderTest.TestICBPEDIMessageMessageTextNumberPlaceHolderFillerMembers")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/CusInBondMoveHeader/CusInBondMoveHeaderTest.cs:580,4
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.MessageSendingBillTest.TestDeleteMessageWithMultipleBillOfLanding")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/MessageSendingAction/MessageSendingBill/MessageSendingObjectTest.cs:510,37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.MessageSendingBillTest.TestDeleteMessageWithMultipleBillOfLanding")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/MessageSendingAction/MessageSendingBill/MessageSendingObjectTest.cs:511,39
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.MessageSendingBillTest.TestDeleteMessageWithMultipleBillOfLanding")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/MessageSendingAction/MessageSendingBill/MessageSendingObjectTest.cs:516,37
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.US.AMS.Business.Testing.MessageSendingBillTest.TestDeleteMessageWithMultipleBillOfLanding")] // Enterprise/Product/Operations/Customs/US/AMS/Business.Test/BusinessObject/MessageSendingAction/MessageSendingBill/MessageSendingObjectTest.cs:517,39
