namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.ACE.Input
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[InputBlock("TN")]
	public partial class AICCTN : MessageBlock
	{
		public AICCTN()
			: base("TN")
		{
		}

		/// <summary>
		/// Code indicating the type of additional information being provided.
		/// </summary>
		[MessageBlockString(3, 3, "M")]
		public ZString AdditionalInformationQualifierCode;

		/// <summary>
		/// Text of the additional information related to the additional reference qualifier code.
		/// </summary>
		[MessageBlockString(70, 6, "C")]
		public ZString AdditionalInformation;
	}
}
