<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(CWNetCoreTargetFramework);net48</TargetFrameworks>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ServiceManager.Common.Abstractions\ServiceManager.Common.Abstractions.csproj" />
    <ProjectReference Include="..\ServiceManager.Shared.Abstractions\ServiceManager.Shared.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ServiceManager.Integration.ServiceHostUtilities" />    
    <Reference Include="Microsoft.Extensions.Logging.Abstractions" />
    <Reference Include="Microsoft.Extensions.Logging" />
    <Reference Include="ServiceManager.Integration.ServiceHostClient.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceHostClient" />
  </ItemGroup>
</Project>