<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>ElasticSearchAdaptor</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Elasticsearch.Net" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Nest" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientEDI.Business\ZClientEDI.Business.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>