<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Tracking.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.Tracking.Module.Test</RootNamespace>
    <TargetFramework>net48</TargetFramework>
    <OutputPath>..\..\..\..\..\Bin\</OutputPath>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tracking.Web.Test\Tracking.Web.Test.csproj" />
    <ProjectReference Include="..\Tracking.Web\Tracking.Web.csproj" />
    <Reference Include="CargoWise.Integration">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ComponentModel">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ComponentModel.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Universal">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Universal.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Universal.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Universal.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.US.ISF.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.US.ISF.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.US.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.US.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineCore">
      <HintPath>..\..\..\..\..\Bin\Enterprise.DocumentEngineCore.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Agency.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Agency.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Agency.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Agency.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.CarbonEmissions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CFS.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.CFS.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CFS.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.CFS.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.AWB.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.AWB.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.LocalCartage.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.LocalCartage.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings.Cache">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ResourceStrings.Cache.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ResourceStrings">
      <HintPath>..\..\..\..\..\Bin\CargoWise.ResourceStrings.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.GUI.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.GUI.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GlobalBase">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GlobalBase.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Accounting.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Accounting.Business.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Common">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Customs.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Common.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Common.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.QuotedBookings.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.QuotedBookings.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.QuotedBookings.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Freight.QuotedBookings.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterData.Common">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterData.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Rating.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Rating.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Registry.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Registry.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Environment.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Environment.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Environment.Business.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Environment.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Integration">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.Business.Testing">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.Business.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Transactions.Module">
      <HintPath>..\..\..\..\..\Bin\Enterprise.Warehouse.Transactions.Module.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.GUI">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.GUI.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business.Test" Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI.Test">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI.Ajax">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.Ajax.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\..\..\Bin\Resources.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
    <Reference Include="CargoWise.Types">
      <HintPath>..\..\..\..\..\Bin\CargoWise.Types.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business">
      <HintPath>..\..\..\..\..\Bin\Enterprise.ZArchitecture.Business.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework.Testing">
      <HintPath>..\..\..\..\..\Bin\CargoWise.EntityFramework.Testing.dll</HintPath>
    </Reference>
    <ProjectReference Include="..\Tracking.Business\Tracking.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tracking.Module\Tracking.Module.csproj" />
  </ItemGroup>
</Project>