// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ZArchitecture.GlowInterop.TokenizedAccessControl.Enterprise#ZArchitecture#GlowInterop#ITokenizedAccessControl#TryConsume(System.String,System.String,Enterprise.ZArchitecture.GlowInterop.AccessTokenInfo@)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Architecture\GlowInterop\GlowInterop\AccessToken\TokenizedAccessControl.cs:11:24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ZArchitecture.GlowInterop.TokenizedAccessControl.Enterprise#ZArchitecture#GlowInterop#ITokenizedAccessControl#TryPeek(System.String,System.String,Enterprise.ZArchitecture.GlowInterop.AccessTokenInfo@)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Architecture\GlowInterop\GlowInterop\AccessToken\TokenizedAccessControl.cs:41:24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ZArchitecture.GlowInterop.TokenizedAccessControl.Enterprise#ZArchitecture#GlowInterop#ITokenizedAccessControl#TryCreate(System.String,System.String,System.Boolean,System.Nullable{System.DateTime},System.Int32,Enterprise.ZArchitecture.GlowInterop.AccessTokenInfo)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Architecture\GlowInterop\GlowInterop\AccessToken\TokenizedAccessControl.cs:72:24
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ZArchitecture.GlowInterop.TokenizedAccessControlExtensions.CreateLimitedToken(Enterprise.ZArchitecture.GlowInterop.ITokenizedAccessControl,System.String,Enterprise.ZArchitecture.GlowInterop.AccessTokenInfo,System.Nullable{System.TimeSpan},System.Int32,System.Collections.Generic.IList{System.Char},System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Architecture\GlowInterop\GlowInterop\AccessToken\TokenizedAccessControlExtensions.cs:23:16
