<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ZArchitecture.GlowInterop</RootNamespace>
    <AssemblyName>Enterprise.ZArchitecture.GlowInterop</AssemblyName>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Authentication.Glow.Client" />
    <Reference Include="CargoWise.Authentication.Primitives" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.SystemToSystemTrust" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Microsoft.AspNet.SignalR.Client" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Net.Http.Formatting" />
    <Reference Include="WTG.Foundation.Cryptography" />
    <Reference Include="WTG.Foundation.Cryptography.Algorithms" />
    <Reference Include="WTG.Foundation.Http" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
</Project>