<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentScanning.Integration" />
    <Reference Include="ServiceManager.Shared.Abstractions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Recruitment.Common.Test\Enterprise.Recruitment.Common.Test.csproj" />
    <ProjectReference Include="..\Recruitment.Module\Enterprise.Recruitment.Module.csproj" />
  </ItemGroup>
</Project>
