<Project>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="Enterprise.MasterFiles.Module" />
    <Reference Include="Enterprise.Scheduler.Business" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Enterprise.ZArchitecture.GUI.UserControls" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Enterprise.ZArchitecture.Schema" />
    <Reference Include="GlowIndexQueryService.Business" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.UniversalCopy.Business\Enterprise.UniversalCopy.Business.csproj" />
    <ProjectReference Include="..\UniversalCopy\UniversalCopy.csproj" />
  </ItemGroup>
</Project>