//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from OIDCServerTypesList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Registry.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class OIDCServerTypesList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Azure = "AZU";
			public const string Generic = "GEN";
			public const string Okta = "OKT";
			public const string OneLogin = "ONE";
			public const string WiseTechIdP = "WTG";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString Azure { get { return ResString.GetMultilingualString("OIDCServerTypesList|Azure", "Azure AD Connect Server"); } }
			public static MultilingualString Generic { get { return ResString.GetMultilingualString("OIDCServerTypesList|Generic", "Generic OpenID Connect Server"); } }
			public static MultilingualString Okta { get { return ResString.GetMultilingualString("OIDCServerTypesList|Okta", "Okta OpenID Connect Server"); } }
			public static MultilingualString OneLogin { get { return ResString.GetMultilingualString("OIDCServerTypesList|OneLogin", "OneLogin OpenID Connect Server"); } }
			public static MultilingualString WiseTechIdP { get { return ResString.GetMultilingualString("OIDCServerTypesList|WiseTechIdP", "WiseTech Identity Server"); } }
		}

		public OIDCServerTypesList()
		{
			AddPair(Codes.Azure, Descriptions.Azure);
			AddPair(Codes.Generic, Descriptions.Generic);
			AddPair(Codes.Okta, Descriptions.Okta);
			AddPair(Codes.OneLogin, Descriptions.OneLogin);
			AddPair(Codes.WiseTechIdP, Descriptions.WiseTechIdP);
		}
	}
}
