using Enterprise.ZArchitecture.GUI;

namespace Enterprise.Freight.LocalCartage.GUI
{
	partial class CartageLegsControl
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo zCheckBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCheckBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo2 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo5 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo zCodeFindBoxColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZCodeFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo1 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo6 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo2 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo7 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo8 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo9 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo10 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo11 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo zGuidDropEditColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZGuidDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo12 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo13 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo14 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo3 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo zGuidFindBoxColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZGuidFindBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo9 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo10 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo11 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo12 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo13 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo14 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo zTimeEditExColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.Internal.ZTimeEditExColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo15 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo16 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo1 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo17 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo18 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo19 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo20 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo2 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo21 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo4 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo5 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo6 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo7 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo8 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo3 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo15 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo16 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo17 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo22 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo18 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo23 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo4 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo5 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo24 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo25 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo26 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo27 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo19 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo28 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo29 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo20 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo30 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo21 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo31 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo6 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo32 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo9 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo10 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo11 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo33 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo22 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo23 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo24 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo25 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZMultiLineTextBoxColumnInfo zMultiLineTextBoxColumnInfo1 = new Enterprise.ZArchitecture.GUI.ZMultiLineTextBoxColumnInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo34 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo35 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo36 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo37 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo38 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo39 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo26 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo40 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo41 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo42 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo43 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo44 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo45 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo46 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo47 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo27 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo28 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo29 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo30 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo31 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo32 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo33 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo34 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo35 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo36 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo37 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZDateEditColumnStyleInfo zDateEditColumnStyleInfo38 = new Enterprise.ZArchitecture.ZDateEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo zTextBoxColumnStyleInfo48 = new Enterprise.ZArchitecture.ZTextBoxColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo12 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo7 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo zCalcEditColumnStyleInfo13 = new Enterprise.ZArchitecture.ZCalcEditColumnStyleInfo();
			Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo zDropEditColumnStyleInfo8 = new Enterprise.ZArchitecture.GUI.ZDropEditColumnStyleInfo();
			this.CartageLegWithDetailsPanel = new Enterprise.Freight.LocalCartage.GUI.CartageLegControlWithDetails();
			this.CartageLegsGrid = new Enterprise.ZArchitecture.GUI.ZModuleButtonGrid();
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.CartageLegsGrid.InnerGrid)).BeginInit();
			this.SuspendLayout();
			// 
			// BindingSource
			// 
			this.BindingSource.DataSourceType = typeof(Enterprise.Freight.LocalCartage.Business.CommonCartage);
			// 
			// CartageLegWithDetailsPanel
			// 
			this.BindingSource.SetBindingMember(this.CartageLegWithDetailsPanel, "CartageLegs");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((Enterprise.Freight.LocalCartage.Business.CommonCartageLeg)(((Enterprise.Freight.LocalCartage.Business.CommonCartageLeg)(((System.Collections.IList)(((Enterprise.Freight.LocalCartage.Business.CommonCartage)(null)).CartageLegs)).SyncRoot)))));
			this.CartageLegWithDetailsPanel.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.CartageLegWithDetailsPanel.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 399, true);
			this.CartageLegWithDetailsPanel.Margin = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPadding(0, true);
			this.CartageLegWithDetailsPanel.MinimumSize = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(992, 200, true);
			this.CartageLegWithDetailsPanel.Name = "CartageLegWithDetailsPanel";
			this.CartageLegWithDetailsPanel.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(1003, 200, true);
			this.CartageLegWithDetailsPanel.TabIndex = 1;
			// 
			// CartageLegsGrid
			// 
			this.BindingSource.SetBindingMember(this.CartageLegsGrid, "CartageLegs");
			// The line(s) below are a compile-time check for a binding member. Reflection is used to determine the return type of collection indexes and may require an up to date compilation of your solution. If compilation fails below, try removing them and rebuild your solution. Then, open the form, move a control up and then down, and re-compile again.
			CargoWise.ComponentModel.Design.CompileTimeCheckBindingMember.Check(((System.Collections.IList)(((Enterprise.Freight.LocalCartage.Business.CommonCartage)(null)).CartageLegs)));
			zGuidFindBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|0e5665c7-4b29-457f-9e86-cf9d8300b070", "Run Sheet");
			zGuidFindBoxColumnStyleInfo1.ColumnName = "JU_EY_RunSheet";
			zTextBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|53fcd0ff-dd7c-4aa1-b5a0-8b4554b622dc", "Container#");
			zTextBoxColumnStyleInfo1.ColumnName = "Container+JC_ContainerNum";
			zTextBoxColumnStyleInfo1.IsReadOnly = true;
			zGuidFindBoxColumnStyleInfo2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			zGuidFindBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|d0ce4f1c-abd9-4902-8fac-d24df403c142", "Cont. Type");
			zGuidFindBoxColumnStyleInfo2.ColumnName = "Container+JC_RC";
			zGuidFindBoxColumnStyleInfo2.IsReadOnly = true;
			zGuidFindBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(65);
			zCheckBoxColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|a6a8b639-f0ab-4c4d-81bb-fc085030efae", "MT Leg");
			zCheckBoxColumnStyleInfo1.ColumnName = "JU_IsEmptyContainer";
			zCheckBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(15);
			zTextBoxColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|7d4b103c-d84a-455e-a5bd-676e850a7361", "Pickup Co.", "Pickup Company", "Pickup Company Name", "");
			zTextBoxColumnStyleInfo2.ColumnName = "PickupFromDocAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo2.IsReadOnly = true;
			zTextBoxColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|0dd7037d-4632-4470-9e28-aece7a73631d", "P. City", "Pic. City", "Pickup City", "");
			zTextBoxColumnStyleInfo3.ColumnName = "PickupFromDocAddress+E2_City";
			zTextBoxColumnStyleInfo3.IsReadOnly = true;
			zTextBoxColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDateEditColumnStyleInfo1.ColumnName = "QuickPlannedPickupTime";
			zDateEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(93);
			zTextBoxColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|2eccde49-414a-4ede-83c3-b72e62783acb", "Delivery Co.", "Delivery Company", "Delivery Company Name", "");
			zTextBoxColumnStyleInfo4.ColumnName = "DeliverToDocAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo4.IsReadOnly = true;
			zTextBoxColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|a424fcd8-f0af-40a9-8a40-490c931fa9ac", "D. City", "Dlv. City", "Delivery City", "");
			zTextBoxColumnStyleInfo5.ColumnName = "DeliverToDocAddress+E2_City";
			zTextBoxColumnStyleInfo5.IsReadOnly = true;
			zTextBoxColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zDateEditColumnStyleInfo2.ColumnName = "QuickEstimatedDeliveryTime";
			zGuidFindBoxColumnStyleInfo3.ColumnName = "QuickRQTruck";
			zGuidFindBoxColumnStyleInfo3.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|47d96136-fd83-49de-92f0-a975d857f3cc", "Vehicle");
			zCodeFindBoxColumnStyleInfo1.ColumnName = "QuickGSDriver";
			zCodeFindBoxColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(35);
			zCalcEditColumnStyleInfo1.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo1.ColumnName = "BookedCtgMove+EW_BookedPackCount";
			zCalcEditColumnStyleInfo1.Decimals = 0;
			zCalcEditColumnStyleInfo1.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|0d3ba76f-ed58-4cfa-afd7-5a5f76a7835f", "Booked Packages");
			zCalcEditColumnStyleInfo1.IsReadOnly = true;
			zCalcEditColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo6.ColumnName = "BookedCtgMove+EW_F3_NKPackType";
			zTextBoxColumnStyleInfo6.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|0d3ba76f-ed58-4cfa-afd7-5a5f76a7835f", "Booked Packages");
			zTextBoxColumnStyleInfo6.IsReadOnly = true;
			zTextBoxColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zCalcEditColumnStyleInfo2.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo2.ColumnName = "BookedCtgMove+EW_BookedWeight";
			zCalcEditColumnStyleInfo2.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|c266144e-a16e-46a9-a0aa-53fc7e19e132", "Booked Weight");
			zCalcEditColumnStyleInfo2.IsReadOnly = true;
			zCalcEditColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo7.ColumnName = "BookedCtgMove+EW_WeightUQ";
			zTextBoxColumnStyleInfo7.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|c266144e-a16e-46a9-a0aa-53fc7e19e132", "Booked Weight");
			zTextBoxColumnStyleInfo7.IsReadOnly = true;
			zTextBoxColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zCalcEditColumnStyleInfo3.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo3.ColumnName = "BookedCtgMove+EW_BookedVolume";
			zCalcEditColumnStyleInfo3.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|2e71bd99-e995-40e8-8d6d-184e6ffd4774", "Booked Volume");
			zCalcEditColumnStyleInfo3.IsReadOnly = true;
			zCalcEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo8.ColumnName = "BookedCtgMove+EW_VolumeUQ";
			zTextBoxColumnStyleInfo8.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|2e71bd99-e995-40e8-8d6d-184e6ffd4774", "Booked Volume");
			zTextBoxColumnStyleInfo8.IsReadOnly = true;
			zTextBoxColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zTextBoxColumnStyleInfo9.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|df3eb072-8e5c-46c9-ba20-cb93a516c7e0", "Received By");
			zTextBoxColumnStyleInfo9.ColumnName = "JU_DeliverySignedFor";
			zTextBoxColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(110);
			zGuidDropEditColumnStyleInfo1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			zGuidDropEditColumnStyleInfo1.ColumnName = "JU_E2PickupAddressID";
			zGuidDropEditColumnStyleInfo1.IsVisible = false;
			zTextBoxColumnStyleInfo10.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|eae81164-1448-48b3-af2f-380daaef008a", "P. P/C", "Pic. P/C", "Pickup Postcode", "");
			zTextBoxColumnStyleInfo10.ColumnName = "PickupFromDocAddress+E2_Postcode";
			zTextBoxColumnStyleInfo10.IsReadOnly = true;
			zTextBoxColumnStyleInfo10.IsVisible = false;
			zTextBoxColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zGuidDropEditColumnStyleInfo2.ColumnName = "JU_E2DeliveryAddressID";
			zGuidDropEditColumnStyleInfo2.IsVisible = false;
			zTextBoxColumnStyleInfo11.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|b7a5a2ad-32b3-4a4d-9dca-33874260db35", "D. P/C", "Dlv. P/C", "Delivery Postcode", "");
			zTextBoxColumnStyleInfo11.ColumnName = "DeliverToDocAddress+E2_Postcode";
			zTextBoxColumnStyleInfo11.IsReadOnly = true;
			zTextBoxColumnStyleInfo11.IsVisible = false;
			zTextBoxColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zGuidDropEditColumnStyleInfo3.ColumnName = "JU_E2WaitPointAddressID";
			zGuidDropEditColumnStyleInfo3.IsVisible = false;
			zTextBoxColumnStyleInfo12.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|2bce8c09-cd8b-486c-86c0-b7f4bfe8585f", "Wt. City", "Wait Point City", "");
			zTextBoxColumnStyleInfo12.ColumnName = "WaitPointDocAddress+E2_City";
			zTextBoxColumnStyleInfo12.IsReadOnly = true;
			zTextBoxColumnStyleInfo12.IsVisible = false;
			zTextBoxColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo13.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|7ad11b77-56d5-47e7-8aee-8dc41b5201f6", "W. P/C", "Wt. P/C", "Wait Point Postcode", "");
			zTextBoxColumnStyleInfo13.ColumnName = "WaitPointDocAddress+E2_Postcode";
			zTextBoxColumnStyleInfo13.IsReadOnly = true;
			zTextBoxColumnStyleInfo13.IsVisible = false;
			zTextBoxColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zTextBoxColumnStyleInfo14.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|932c807c-260b-4b33-989f-a92cada776e8", "Job#");
			zTextBoxColumnStyleInfo14.ColumnName = "Cartage+JJ_ConsignmentID";
			zTextBoxColumnStyleInfo14.IsVisible = false;
			zDateEditColumnStyleInfo3.ColumnName = "JU_PlannedPickupTimeEnd";
			zDateEditColumnStyleInfo3.IsVisible = false;
			zDateEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo4.ColumnName = "JU_EstimatedDeliveryTimeEnd";
			zDateEditColumnStyleInfo4.IsVisible = false;
			zGuidFindBoxColumnStyleInfo4.ColumnName = "QuickOHTransportCompany";
			zGuidFindBoxColumnStyleInfo4.IsVisible = false;
			zDateEditColumnStyleInfo5.ColumnName = "JU_PickupTimeIn";
			zDateEditColumnStyleInfo5.IsVisible = false;
			zDateEditColumnStyleInfo6.ColumnName = "JU_PickupTimeOut";
			zDateEditColumnStyleInfo6.IsVisible = false;
			zDateEditColumnStyleInfo7.ColumnName = "JU_WaitPointTimeIn";
			zDateEditColumnStyleInfo7.IsVisible = false;
			zDateEditColumnStyleInfo8.ColumnName = "JU_WaitPointTimeOut";
			zDateEditColumnStyleInfo8.IsVisible = false;
			zDateEditColumnStyleInfo9.ColumnName = "JU_DeliverTimeIn";
			zDateEditColumnStyleInfo9.IsVisible = false;
			zDateEditColumnStyleInfo10.ColumnName = "JU_DeliverTimeOut";
			zDateEditColumnStyleInfo10.IsVisible = false;
			zDateEditColumnStyleInfo11.ColumnName = "Container+JC_EmptyReturnedBy";
			zDateEditColumnStyleInfo11.IsReadOnly = true;
			zDateEditColumnStyleInfo11.IsVisible = false;
			zDateEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo12.ColumnName = "Container+JC_LCLUnpack";
			zDateEditColumnStyleInfo12.IsReadOnly = true;
			zDateEditColumnStyleInfo12.IsVisible = false;
			zDateEditColumnStyleInfo12.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo13.ColumnName = "Container+JC_LCLStorageCommences";
			zDateEditColumnStyleInfo13.IsReadOnly = true;
			zDateEditColumnStyleInfo13.IsVisible = false;
			zDateEditColumnStyleInfo13.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo14.ColumnName = "Container+JC_LCLAvailable";
			zDateEditColumnStyleInfo14.IsReadOnly = true;
			zDateEditColumnStyleInfo14.IsVisible = false;
			zDateEditColumnStyleInfo14.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zTimeEditExColumnStyleInfo1.AllowNegative = false;
			zTimeEditExColumnStyleInfo1.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|ca05c955-e0c5-48e5-847d-b8648b4c2a1a", "Time At Pic.", "Time At Pickup", "");
			zTimeEditExColumnStyleInfo1.ColumnName = "JU_CartagePickupDemurrage";
			zTimeEditExColumnStyleInfo1.IsVisible = false;
			zTimeEditExColumnStyleInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTimeEditExColumnStyleInfo2.AllowNegative = false;
			zTimeEditExColumnStyleInfo2.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|d4073123-a7fe-4c4a-96a3-fa562831af07", "Time At Wt Pt.");
			zTimeEditExColumnStyleInfo2.ColumnName = "JU_CartageWaitPointDemurrage";
			zTimeEditExColumnStyleInfo2.IsVisible = false;
			zTimeEditExColumnStyleInfo2.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTimeEditExColumnStyleInfo3.AllowNegative = false;
			zTimeEditExColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|c067f46c-9e3c-47c5-8a43-707d13e9418b", "Time At Dlv.", "Time At Delivery", "");
			zTimeEditExColumnStyleInfo3.ColumnName = "JU_CartageDeliveryDemurrage";
			zTimeEditExColumnStyleInfo3.IsVisible = false;
			zTimeEditExColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo15.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|5487aa91-eeb0-4748-9e96-ca863e776e84", "Cont. Seal#");
			zTextBoxColumnStyleInfo15.ColumnName = "Container+JC_SealNum";
			zTextBoxColumnStyleInfo15.IsReadOnly = true;
			zTextBoxColumnStyleInfo15.IsVisible = false;
			zTextBoxColumnStyleInfo16.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|cab322c0-f86f-4326-bc1d-2753584b62db", "Client", "Client Code", "Client Org. Code", "Client Organization Code.");
			zTextBoxColumnStyleInfo16.ColumnName = "Cartage+LocalClient+OH_Code";
			zTextBoxColumnStyleInfo16.IsReadOnly = true;
			zTextBoxColumnStyleInfo16.IsVisible = false;
			zDropEditColumnStyleInfo1.ColumnName = "JU_MessageStatus";
			zDropEditColumnStyleInfo1.IsVisible = false;
			zTextBoxColumnStyleInfo17.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|54ac3de2-057b-491f-9f6a-09a455678929", "Quote No.");
			zTextBoxColumnStyleInfo17.ColumnName = "Cartage+JJ_QuoteNumber";
			zTextBoxColumnStyleInfo17.IsReadOnly = true;
			zTextBoxColumnStyleInfo17.IsVisible = false;
			zTextBoxColumnStyleInfo18.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|5385934f-a5e8-4631-9753-ea1bc8e5cf8b", "Con. Note");
			zTextBoxColumnStyleInfo18.ColumnName = "Cartage+JJ_WaybillNumber";
			zTextBoxColumnStyleInfo18.IsReadOnly = true;
			zTextBoxColumnStyleInfo18.IsVisible = false;
			zTextBoxColumnStyleInfo19.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|d4f3dbcf-d1ae-45ff-a0e7-50f68e416bd4", "Ref No.");
			zTextBoxColumnStyleInfo19.ColumnName = "Cartage+JJ_OrderReferenceNumber";
			zTextBoxColumnStyleInfo19.IsReadOnly = true;
			zTextBoxColumnStyleInfo19.IsVisible = false;
			zTextBoxColumnStyleInfo20.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|44ba8718-614f-4a18-9a12-2fbcc4ee628d", "Description");
			zTextBoxColumnStyleInfo20.ColumnName = "Cartage+JJ_GoodsDescription";
			zTextBoxColumnStyleInfo20.IsReadOnly = true;
			zTextBoxColumnStyleInfo20.IsVisible = false;
			zDropEditColumnStyleInfo2.ColumnName = "BookedCtgMove+EW_DropMode";
			zDropEditColumnStyleInfo2.IsVisible = false;
			zTextBoxColumnStyleInfo21.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo21.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|7315e9b0-a100-4298-b0e5-95596346f884", "Cont. Release Num.");
			zTextBoxColumnStyleInfo21.ColumnName = "Container+JC_ReleaseNum";
			zTextBoxColumnStyleInfo21.IsReadOnly = true;
			zTextBoxColumnStyleInfo21.IsVisible = false;
			zCalcEditColumnStyleInfo4.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|46c81b56-1733-4f96-853e-aed030648f88", "Cont. Length (ft.)");
			zCalcEditColumnStyleInfo4.ColumnName = "Container+JC_TotalLength";
			zCalcEditColumnStyleInfo4.Decimals = 3;
			zCalcEditColumnStyleInfo4.IsReadOnly = true;
			zCalcEditColumnStyleInfo4.IsVisible = false;
			zCalcEditColumnStyleInfo4.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo5.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|28714d6c-5825-4fc9-827d-97c9d98c1ba9", "Cont. Width (ft.)");
			zCalcEditColumnStyleInfo5.ColumnName = "Container+JC_TotalWidth";
			zCalcEditColumnStyleInfo5.Decimals = 3;
			zCalcEditColumnStyleInfo5.IsReadOnly = true;
			zCalcEditColumnStyleInfo5.IsVisible = false;
			zCalcEditColumnStyleInfo5.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo6.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|b2c0d447-ccec-4935-aad1-0250b9a90202", "Cont. Height (ft.)");
			zCalcEditColumnStyleInfo6.ColumnName = "Container+JC_TotalHeight";
			zCalcEditColumnStyleInfo6.Decimals = 3;
			zCalcEditColumnStyleInfo6.IsReadOnly = true;
			zCalcEditColumnStyleInfo6.IsVisible = false;
			zCalcEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo7.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo7.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|73ac866e-2968-4f99-ae59-49abebe0923c", "Cont. Tare Weight");
			zCalcEditColumnStyleInfo7.ColumnName = "Container+JC_TareWeight";
			zCalcEditColumnStyleInfo7.Decimals = 3;
			zCalcEditColumnStyleInfo7.IsReadOnly = true;
			zCalcEditColumnStyleInfo7.IsVisible = false;
			zCalcEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zCalcEditColumnStyleInfo8.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo8.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|75c5e2a6-e69c-40e6-99b7-15922cb505be", "Cont. Gross Weight");
			zCalcEditColumnStyleInfo8.ColumnName = "Container+JC_GrossWeight";
			zCalcEditColumnStyleInfo8.Decimals = 3;
			zCalcEditColumnStyleInfo8.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|aa64b71d-6828-4d89-b470-423e70affc14", "Gross Weight");
			zCalcEditColumnStyleInfo8.IsReadOnly = true;
			zCalcEditColumnStyleInfo8.IsVisible = false;
			zDropEditColumnStyleInfo3.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|96cbd047-6351-465c-8d49-6206989fe79c", "Cont. UW");
			zDropEditColumnStyleInfo3.ColumnName = "Container+JC_GrossWeightUQ";
			zDropEditColumnStyleInfo3.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|aa64b71d-6828-4d89-b470-423e70affc14", "Gross Weight");
			zDropEditColumnStyleInfo3.IsReadOnly = true;
			zDropEditColumnStyleInfo3.IsVisible = false;
			zDropEditColumnStyleInfo3.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(25);
			zDateEditColumnStyleInfo15.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|c2f87e89-9212-4719-babf-a9f3f3258df9", "Cont. Empty Actually Returned");
			zDateEditColumnStyleInfo15.ColumnName = "Container+JC_ContainerYardEmptyReturnGateIn";
			zDateEditColumnStyleInfo15.IsReadOnly = true;
			zDateEditColumnStyleInfo15.IsVisible = false;
			zDateEditColumnStyleInfo15.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(95);
			zDateEditColumnStyleInfo16.ColumnName = "Container+JC_EmptyRequired";
			zDateEditColumnStyleInfo16.IsReadOnly = true;
			zDateEditColumnStyleInfo16.IsVisible = false;
			zDateEditColumnStyleInfo16.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(95);
			zDateEditColumnStyleInfo17.ColumnName = "Container+JC_DepartureEstimatedPickup";
			zDateEditColumnStyleInfo17.IsReadOnly = true;
			zDateEditColumnStyleInfo17.IsVisible = false;
			zTextBoxColumnStyleInfo22.ColumnName = "Container+JC_AdditionalSealNum";
			zTextBoxColumnStyleInfo22.IsReadOnly = true;
			zTextBoxColumnStyleInfo22.IsVisible = false;
			zDateEditColumnStyleInfo18.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|1a80b37b-1396-49aa-99c5-658b8090732f", "Cont. Pack Date");
			zDateEditColumnStyleInfo18.ColumnName = "Container+JC_PackDate";
			zDateEditColumnStyleInfo18.IsReadOnly = true;
			zDateEditColumnStyleInfo18.IsVisible = false;
			zTextBoxColumnStyleInfo23.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|1aef8a2b-e2b6-449e-817d-7c9985c048aa", "Cont. Location");
			zTextBoxColumnStyleInfo23.ColumnName = "Container+JC_ContainerStorageLocation";
			zTextBoxColumnStyleInfo23.IsReadOnly = true;
			zTextBoxColumnStyleInfo23.IsVisible = false;
			zDropEditColumnStyleInfo4.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|41ed7326-768d-4c69-8a65-e43c35bff5e3", "Cont. Status");
			zDropEditColumnStyleInfo4.ColumnName = "Container+JC_ContainerStatus";
			zDropEditColumnStyleInfo4.IsReadOnly = true;
			zDropEditColumnStyleInfo4.IsVisible = false;
			zDropEditColumnStyleInfo5.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|5c6fe438-93ff-464b-88d5-0b99381164b8", "Cont. Quality");
			zDropEditColumnStyleInfo5.ColumnName = "Container+JC_ContainerQuality";
			zDropEditColumnStyleInfo5.IsReadOnly = true;
			zDropEditColumnStyleInfo5.IsVisible = false;
			zTextBoxColumnStyleInfo24.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|6384e808-12ab-46b1-8ad7-efd67783564d", "Cont. Rating");
			zTextBoxColumnStyleInfo24.ColumnName = "Container+JC_ContainerRating";
			zTextBoxColumnStyleInfo24.IsReadOnly = true;
			zTextBoxColumnStyleInfo24.IsVisible = false;
			zTextBoxColumnStyleInfo25.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|7018454f-b3d2-4ef0-abee-e287837c9a0c", "Cont. Export Customs Ref");
			zTextBoxColumnStyleInfo25.ColumnName = "Container+JC_ExportDepotCustomsReference";
			zTextBoxColumnStyleInfo25.IsReadOnly = true;
			zTextBoxColumnStyleInfo25.IsVisible = false;
			zTextBoxColumnStyleInfo26.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|9b0ab52d-dbd5-49fa-b449-119bc8a24064", "Cont. Train Wagon");
			zTextBoxColumnStyleInfo26.ColumnName = "Container+JC_TrainWagonNumber";
			zTextBoxColumnStyleInfo26.IsReadOnly = true;
			zTextBoxColumnStyleInfo26.IsVisible = false;
			zTextBoxColumnStyleInfo27.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|8ae3098f-796a-4300-93fa-da931724ce08", "Cont. Temp. Rec. No.");
			zTextBoxColumnStyleInfo27.ColumnName = "Container+JC_TempRecorderSerialNo";
			zTextBoxColumnStyleInfo27.IsReadOnly = true;
			zTextBoxColumnStyleInfo27.IsVisible = false;
			zDateEditColumnStyleInfo19.ColumnName = "Cartage+JJ_SystemCreateTimeUtc";
			zDateEditColumnStyleInfo19.IsReadOnly = true;
			zDateEditColumnStyleInfo19.IsVisible = false;
			zDateEditColumnStyleInfo19.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(105);
			zTextBoxColumnStyleInfo28.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|a30b1d1a-e45a-46b5-9eee-f1c6e0148fd9", "Pickup Wait Time");
			zTextBoxColumnStyleInfo28.ColumnName = "PickupWaitTime";
			zTextBoxColumnStyleInfo28.IsVisible = false;
			zTextBoxColumnStyleInfo29.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|669b0254-c76a-47a2-b764-239c7a2552e4", "Delivery Wait Time");
			zTextBoxColumnStyleInfo29.ColumnName = "DeliveryWaitTime";
			zTextBoxColumnStyleInfo29.IsVisible = false;
			zDateEditColumnStyleInfo20.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|5fee7813-c947-4887-832f-4212bb3a50e5", "Cont. Arv. Slot Date");
			zDateEditColumnStyleInfo20.ColumnName = "Container+JC_ArrivalSlotDateTime";
			zDateEditColumnStyleInfo20.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|99197d54-7303-4c90-9250-1007a628ca6b", "Arrival Slot");
			zDateEditColumnStyleInfo20.IsReadOnly = true;
			zDateEditColumnStyleInfo20.IsVisible = false;
			zTextBoxColumnStyleInfo30.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo30.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|f1838a7c-18f0-48bb-8d65-17384d26fa5c", "Cont. Arv. Slot Ref");
			zTextBoxColumnStyleInfo30.ColumnName = "Container+JC_ArrivalSlotReference";
			zTextBoxColumnStyleInfo30.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|99197d54-7303-4c90-9250-1007a628ca6b", "Arrival Slot");
			zTextBoxColumnStyleInfo30.IsReadOnly = true;
			zTextBoxColumnStyleInfo30.IsVisible = false;
			zDateEditColumnStyleInfo21.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|0ea48bb5-3404-4c2c-8c65-e22c2c56af80", "Cont. Dep. Slot Date");
			zDateEditColumnStyleInfo21.ColumnName = "Container+JC_DepartureSlotDateTime";
			zDateEditColumnStyleInfo21.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|3b195319-d3d0-46ab-a9b5-95c0d8cd3a86", "Departure Slot");
			zDateEditColumnStyleInfo21.IsReadOnly = true;
			zDateEditColumnStyleInfo21.IsVisible = false;
			zTextBoxColumnStyleInfo31.CharacterCasing = System.Windows.Forms.CharacterCasing.Upper;
			zTextBoxColumnStyleInfo31.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|f894a935-9d83-4889-a1eb-2320cc5ad702", "Cont. Dep. Slot Ref");
			zTextBoxColumnStyleInfo31.ColumnName = "Container+JC_DepartureSlotReference";
			zTextBoxColumnStyleInfo31.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|3b195319-d3d0-46ab-a9b5-95c0d8cd3a86", "Departure Slot");
			zTextBoxColumnStyleInfo31.IsReadOnly = true;
			zTextBoxColumnStyleInfo31.IsVisible = false;
			zDropEditColumnStyleInfo6.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|62bc9938-6a00-4806-9222-14ddd42a78f5", "Cont. Mode");
			zDropEditColumnStyleInfo6.ColumnName = "Container+JC_ContainerMode";
			zDropEditColumnStyleInfo6.IsMandatory = true;
			zDropEditColumnStyleInfo6.IsReadOnly = true;
			zDropEditColumnStyleInfo6.IsVisible = false;
			zDropEditColumnStyleInfo6.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(35);
			zTextBoxColumnStyleInfo32.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|0f4a9f7b-b092-4ed6-99fa-fcfc0d75d2e8", "Wt. Co.", "Wait Point Company", "Wait Point Company Name", "");
			zTextBoxColumnStyleInfo32.ColumnName = "WaitPointDocAddress+E2_CompanyName";
			zTextBoxColumnStyleInfo32.IsReadOnly = true;
			zTextBoxColumnStyleInfo32.IsVisible = false;
			zTextBoxColumnStyleInfo32.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zCalcEditColumnStyleInfo9.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo9.ColumnName = "BookedCtgMove+EW_BookedHeight";
			zCalcEditColumnStyleInfo9.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|a586c975-7eff-47d4-ae4d-23c3131e56ef", "Booked Dimensions");
			zCalcEditColumnStyleInfo9.IsReadOnly = true;
			zCalcEditColumnStyleInfo9.IsVisible = false;
			zCalcEditColumnStyleInfo9.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo10.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo10.ColumnName = "BookedCtgMove+EW_BookedLength";
			zCalcEditColumnStyleInfo10.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|a586c975-7eff-47d4-ae4d-23c3131e56ef", "Booked Dimensions");
			zCalcEditColumnStyleInfo10.IsReadOnly = true;
			zCalcEditColumnStyleInfo10.IsVisible = false;
			zCalcEditColumnStyleInfo10.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zCalcEditColumnStyleInfo11.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo11.ColumnName = "BookedCtgMove+EW_BookedWidth";
			zCalcEditColumnStyleInfo11.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|a586c975-7eff-47d4-ae4d-23c3131e56ef", "Booked Dimensions");
			zCalcEditColumnStyleInfo11.IsReadOnly = true;
			zCalcEditColumnStyleInfo11.IsVisible = false;
			zCalcEditColumnStyleInfo11.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo33.ColumnName = "BookedCtgMove+EW_DimUnit";
			zTextBoxColumnStyleInfo33.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|a586c975-7eff-47d4-ae4d-23c3131e56ef", "Booked Dimensions");
			zTextBoxColumnStyleInfo33.IsReadOnly = true;
			zTextBoxColumnStyleInfo33.IsVisible = false;
			zTextBoxColumnStyleInfo33.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			zDateEditColumnStyleInfo22.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|99977297-2842-4c92-be26-ec99dea0f77e", "Pic. From", "Pickup From", "Requested Pickup From", "");
			zDateEditColumnStyleInfo22.ColumnName = "BookedCtgMove+EW_RequestedPickupTimeStart";
			zDateEditColumnStyleInfo22.IsReadOnly = true;
			zDateEditColumnStyleInfo22.IsVisible = false;
			zDateEditColumnStyleInfo22.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo23.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|45120364-6a78-4db0-b1eb-0107d59c932f", "Pic. To", "Pickup To", "Requested Pickup To", "");
			zDateEditColumnStyleInfo23.ColumnName = "BookedCtgMove+EW_RequestedPickupTimeEnd";
			zDateEditColumnStyleInfo23.IsReadOnly = true;
			zDateEditColumnStyleInfo23.IsVisible = false;
			zDateEditColumnStyleInfo23.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo24.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|7cdf6909-94fb-462f-9316-999ad795fb0e", "Dlv. From", "Delivery From", "Requested Delivery From", "");
			zDateEditColumnStyleInfo24.ColumnName = "BookedCtgMove+EW_RequestedDeliveryTimeStart";
			zDateEditColumnStyleInfo24.IsReadOnly = true;
			zDateEditColumnStyleInfo24.IsVisible = false;
			zDateEditColumnStyleInfo24.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zDateEditColumnStyleInfo25.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|a7e75a07-1e35-4033-b13f-a885f7e53a2a", "Dlv. To", "Delivery To", "Requested Delivery To", "");
			zDateEditColumnStyleInfo25.ColumnName = "BookedCtgMove+EW_RequestedDeliveryTimeEnd";
			zDateEditColumnStyleInfo25.IsReadOnly = true;
			zDateEditColumnStyleInfo25.IsVisible = false;
			zDateEditColumnStyleInfo25.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(90);
			zMultiLineTextBoxColumnInfo1.ColumnName = "JU_LegNotes";
			zMultiLineTextBoxColumnInfo1.IsVisible = false;
			zMultiLineTextBoxColumnInfo1.MinimumEditControlWidth = 300;
			zMultiLineTextBoxColumnInfo1.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(100);
			zTextBoxColumnStyleInfo34.ColumnName = "JU_SplitDeliverySuffix";
			zTextBoxColumnStyleInfo34.IsReadOnly = true;
			zTextBoxColumnStyleInfo34.IsVisible = false;
			zTextBoxColumnStyleInfo35.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|6780292e-3fd1-4a0b-8070-0a1baaf286bb", "Client");
			zTextBoxColumnStyleInfo35.ColumnName = "Cartage+LocalClient+OH_Code";
			zTextBoxColumnStyleInfo35.IsReadOnly = true;
			zTextBoxColumnStyleInfo35.IsVisible = false;
			zTextBoxColumnStyleInfo35.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo36.ColumnName = "Cartage+JJ_OrderReferenceNumber";
			zTextBoxColumnStyleInfo36.IsReadOnly = true;
			zTextBoxColumnStyleInfo36.IsVisible = false;
			zTextBoxColumnStyleInfo36.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(50);
			zTextBoxColumnStyleInfo37.ColumnName = "Cartage+JJ_QuoteNumber";
			zTextBoxColumnStyleInfo37.IsReadOnly = true;
			zTextBoxColumnStyleInfo37.IsVisible = false;
			zTextBoxColumnStyleInfo38.ColumnName = "Cartage+JJ_WaybillNumber";
			zTextBoxColumnStyleInfo38.IsReadOnly = true;
			zTextBoxColumnStyleInfo38.IsVisible = false;
			zTextBoxColumnStyleInfo39.ColumnName = "Cartage+JJ_GoodsDescription";
			zTextBoxColumnStyleInfo39.IsReadOnly = true;
			zTextBoxColumnStyleInfo39.IsVisible = false;
			zDateEditColumnStyleInfo26.ColumnName = "Cartage+JJ_A_JCL";
			zDateEditColumnStyleInfo26.IsReadOnly = true;
			zDateEditColumnStyleInfo26.IsVisible = false;
			zTextBoxColumnStyleInfo40.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|ceba8a23-6b5b-49cc-b8bb-f47343a22b97", "Vessel");
			zTextBoxColumnStyleInfo40.ColumnName = "Cartage+Vessel";
			zTextBoxColumnStyleInfo40.IsReadOnly = true;
			zTextBoxColumnStyleInfo40.IsVisible = false;
			zTextBoxColumnStyleInfo41.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsControl|753dab6e-c1c9-446f-b756-c51ebb72a35c", "Voyage");
			zTextBoxColumnStyleInfo41.ColumnName = "Cartage+VoyageFlight";
			zTextBoxColumnStyleInfo41.IsReadOnly = true;
			zTextBoxColumnStyleInfo41.IsVisible = false;
			zTextBoxColumnStyleInfo41.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(60);
			zTextBoxColumnStyleInfo42.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|bbe73269-d1ae-4f39-8143-3b5db584a042", "Pic. Org.", "Pickup Org.", "Pickup Organization Code", "");
			zTextBoxColumnStyleInfo42.ColumnName = "PickupFromDocAddress+Organisation+OH_Code";
			zTextBoxColumnStyleInfo42.IsReadOnly = true;
			zTextBoxColumnStyleInfo42.IsVisible = false;
			zTextBoxColumnStyleInfo42.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo43.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|659c1471-c70c-495b-9d6b-164800d427eb", "Pic. Addr.", "Pickup Addr.", "Pickup Address", "");
			zTextBoxColumnStyleInfo43.ColumnName = "PickupFromDocAddress+E2_Address1";
			zTextBoxColumnStyleInfo43.IsReadOnly = true;
			zTextBoxColumnStyleInfo43.IsVisible = false;
			zTextBoxColumnStyleInfo44.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|d01ba3ab-3c02-4cb5-95e2-c280ce681c3d", "Wt Pt Org.", "Wait Point Org.", "Wait Point Organization Code", "");
			zTextBoxColumnStyleInfo44.ColumnName = "WaitPointDocAddress+Organisation+OH_Code";
			zTextBoxColumnStyleInfo44.IsReadOnly = true;
			zTextBoxColumnStyleInfo44.IsVisible = false;
			zTextBoxColumnStyleInfo44.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo45.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|40ef1bf6-873c-46eb-903a-0c9556b22d5a", "Wt Pt Addr.", "Wait Point Addr.", "Wait Point Address", "");
			zTextBoxColumnStyleInfo45.ColumnName = "WaitPointDocAddress+E2_Address1";
			zTextBoxColumnStyleInfo45.IsReadOnly = true;
			zTextBoxColumnStyleInfo45.IsVisible = false;
			zTextBoxColumnStyleInfo46.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|0d77c8dc-2aaa-478c-8d05-29e4f39882e6", "Dlv. Org.", "Delivery Org.", "Delivery Organization Code", "");
			zTextBoxColumnStyleInfo46.ColumnName = "DeliverToDocAddress+Organisation+OH_Code";
			zTextBoxColumnStyleInfo46.IsReadOnly = true;
			zTextBoxColumnStyleInfo46.IsVisible = false;
			zTextBoxColumnStyleInfo46.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(70);
			zTextBoxColumnStyleInfo47.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("CartageLegsModuleButtonGrid|ddab6655-6fd4-459c-9d82-1934d62d75e6", "Dlv. Addr.", "Delivery Addr.", "Delivery Address", "");
			zTextBoxColumnStyleInfo47.ColumnName = "DeliverToDocAddress+E2_Address1";
			zTextBoxColumnStyleInfo47.IsReadOnly = true;
			zTextBoxColumnStyleInfo47.IsVisible = false;
			zDateEditColumnStyleInfo27.ColumnName = "Cartage+FCLStorageDate";
			zDateEditColumnStyleInfo27.IsReadOnly = true;
			zDateEditColumnStyleInfo27.IsVisible = false;
			zDateEditColumnStyleInfo28.ColumnName = "Cartage+FCLAvailabilityDate";
			zDateEditColumnStyleInfo28.IsReadOnly = true;
			zDateEditColumnStyleInfo28.IsVisible = false;
			zDateEditColumnStyleInfo29.ColumnName = "Cartage+FCLReceivalCommences";
			zDateEditColumnStyleInfo29.IsReadOnly = true;
			zDateEditColumnStyleInfo29.IsVisible = false;
			zDateEditColumnStyleInfo30.ColumnName = "Cartage+FCLCutOff";
			zDateEditColumnStyleInfo30.IsReadOnly = true;
			zDateEditColumnStyleInfo30.IsVisible = false;
			zDateEditColumnStyleInfo31.ColumnName = "Cartage+E_DEP";
			zDateEditColumnStyleInfo31.IsReadOnly = true;
			zDateEditColumnStyleInfo31.IsVisible = false;
			zDateEditColumnStyleInfo32.ColumnName = "Cartage+E_ARV";
			zDateEditColumnStyleInfo32.IsReadOnly = true;
			zDateEditColumnStyleInfo32.IsVisible = false;
			zDateEditColumnStyleInfo33.ColumnName = "Cartage+LCLStorageDate";
			zDateEditColumnStyleInfo33.IsReadOnly = true;
			zDateEditColumnStyleInfo33.IsVisible = false;
			zDateEditColumnStyleInfo34.ColumnName = "Cartage+LCLAvailabilityDate";
			zDateEditColumnStyleInfo34.IsReadOnly = true;
			zDateEditColumnStyleInfo34.IsVisible = false;
			zDateEditColumnStyleInfo35.ColumnName = "Cartage+LCLReceivalCommences";
			zDateEditColumnStyleInfo35.IsReadOnly = true;
			zDateEditColumnStyleInfo35.IsVisible = false;
			zDateEditColumnStyleInfo36.ColumnName = "Cartage+LCLCutOff";
			zDateEditColumnStyleInfo36.IsReadOnly = true;
			zDateEditColumnStyleInfo36.IsVisible = false;
			zDateEditColumnStyleInfo37.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|16ddd489-1a80-4d15-b50e-28cad5076cb8", "ATD", "Schedule ATD", "When the voyage is actually to departed the load port.");
			zDateEditColumnStyleInfo37.ColumnName = "Cartage+A_DEP";
			zDateEditColumnStyleInfo37.IsReadOnly = true;
			zDateEditColumnStyleInfo37.IsVisible = false;
			zDateEditColumnStyleInfo38.CaptionResourceString = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|29d26097-beb0-43df-99b9-7baf2ce7ec0e", "ATA", "Schedule ATA", "When the voyage actually arrived at the discharge port.");
			zDateEditColumnStyleInfo38.ColumnName = "Cartage+A_ARV";
			zDateEditColumnStyleInfo38.IsReadOnly = true;
			zDateEditColumnStyleInfo38.IsVisible = false;
			zTextBoxColumnStyleInfo48.ColumnName = "TruckDescription";
			zTextBoxColumnStyleInfo48.IsVisible = false;
			zCalcEditColumnStyleInfo12.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo12.ColumnName = "PostcodeDistance";
			zCalcEditColumnStyleInfo12.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|4707975c-dacb-4678-9f19-56d18a42b882", "Postcode Distance");
			zCalcEditColumnStyleInfo12.IsVisible = false;
			zDropEditColumnStyleInfo7.ColumnName = "JU_DistanceUnit";
			zDropEditColumnStyleInfo7.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|4707975c-dacb-4678-9f19-56d18a42b882", "Postcode Distance");
			zDropEditColumnStyleInfo7.IsReadOnly = true;
			zDropEditColumnStyleInfo7.IsVisible = false;
			zDropEditColumnStyleInfo7.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(40);
			zCalcEditColumnStyleInfo13.BindToDecimalPlaces = null;
			zCalcEditColumnStyleInfo13.ColumnName = "JU_Distance";
			zCalcEditColumnStyleInfo13.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|ba03b2a9-8b01-4263-95df-35a5479c760e", "Driving Distance");
			zCalcEditColumnStyleInfo13.IsVisible = false;
			zDropEditColumnStyleInfo8.ColumnName = "JU_DistanceUnit";
			zDropEditColumnStyleInfo8.GroupName = Enterprise.Freight.LocalCartage.GUI.Res.GetData("ZModuleButtonGrid|ba03b2a9-8b01-4263-95df-35a5479c760e", "Driving Distance");
			zDropEditColumnStyleInfo8.IsVisible = false;
			zDropEditColumnStyleInfo8.Width = CargoWise.Windows.UI.ControlDpiScalingHelper.ScaleToCurrentDpiX(30);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zCheckBoxColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo4);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo5);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zCodeFindBoxColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo6);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo7);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo8);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo9);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo10);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo11);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidDropEditColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo12);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo13);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo14);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo4);
			this.CartageLegsGrid.ColumnStyles.Add(zGuidFindBoxColumnStyleInfo4);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo5);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo6);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo7);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo8);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo9);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo10);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo11);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo12);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo13);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo14);
			this.CartageLegsGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zTimeEditExColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo15);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo16);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo17);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo18);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo19);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo20);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo2);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo21);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo4);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo5);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo6);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo7);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo8);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo3);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo15);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo16);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo17);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo22);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo18);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo23);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo4);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo5);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo24);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo25);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo26);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo27);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo19);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo28);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo29);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo20);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo30);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo21);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo31);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo6);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo32);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo9);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo10);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo11);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo33);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo22);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo23);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo24);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo25);
			this.CartageLegsGrid.ColumnStyles.Add(zMultiLineTextBoxColumnInfo1);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo34);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo35);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo36);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo37);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo38);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo39);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo26);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo40);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo41);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo42);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo43);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo44);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo45);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo46);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo47);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo27);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo28);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo29);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo30);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo31);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo32);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo33);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo34);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo35);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo36);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo37);
			this.CartageLegsGrid.ColumnStyles.Add(zDateEditColumnStyleInfo38);
			this.CartageLegsGrid.ColumnStyles.Add(zTextBoxColumnStyleInfo48);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo12);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo7);
			this.CartageLegsGrid.ColumnStyles.Add(zCalcEditColumnStyleInfo13);
			this.CartageLegsGrid.ColumnStyles.Add(zDropEditColumnStyleInfo8);
			this.CartageLegsGrid.GridId = "13ff37fc-594f-4229-972e-b542dd55d978";
			this.CartageLegsGrid.Dock = System.Windows.Forms.DockStyle.Fill;
			// 
			// 
			// 
			this.CartageLegsGrid.InnerGrid.AllowNavigation = false;
			this.CartageLegsGrid.InnerGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
						| System.Windows.Forms.AnchorStyles.Left)
						| System.Windows.Forms.AnchorStyles.Right)));
			this.CartageLegsGrid.InnerGrid.CaptionVisible = false;
			this.CartageLegsGrid.InnerGrid.HeaderForeColor = System.Drawing.SystemColors.ControlText;
			this.CartageLegsGrid.InnerGrid.LayoutKey = "zGrid1";
			this.CartageLegsGrid.InnerGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(3, 2, true);
			this.CartageLegsGrid.InnerGrid.Name = "Grid";
			this.CartageLegsGrid.InnerGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(993, 361, true);
			this.CartageLegsGrid.InnerGrid.TabIndex = 0;
			this.CartageLegsGrid.Location = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledPoint(0, 0, true);
			this.CartageLegsGrid.Name = "CartageLegsGrid";
			this.CartageLegsGrid.ReadOnly = false;
			this.CartageLegsGrid.ShowAttachButton = false;
			this.CartageLegsGrid.ShowDetachButton = false;
			this.CartageLegsGrid.ShowNewButton = false;
			this.CartageLegsGrid.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(1003, 399, true);
			this.CartageLegsGrid.TabIndex = 0;
			// 
			// CartageLegsControl
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
			this.CaptionRenderingEnabled = true;
			this.Controls.Add(this.CartageLegsGrid);
			this.Controls.Add(this.CartageLegWithDetailsPanel);
			this.Name = "CartageLegsControl";
			this.ShouldSerializeTabPageMethods = false;
			this.Size = CargoWise.Windows.UI.ControlDpiScalingHelper.NewScaledSize(1003, 599, true);
			((System.ComponentModel.ISupportInitialize)(this.BindingSource)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.CartageLegsGrid.InnerGrid)).EndInit();
			this.ResumeLayout(false);

		}

		#endregion

		private CartageLegControlWithDetails CartageLegWithDetailsPanel;
		internal ZModuleButtonGrid CartageLegsGrid;
	}
}
