<?xml version="1.0"?>
<xs:schema xmlns:tns="http://cargowise.com/ehub/products/sgcustoms/mhaccess/2017/09" elementFormDefault="qualified" targetNamespace="http://cargowise.com/ehub/products/sgcustoms/mhaccess/2017/09" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="response" type="tns:Response" />
  <xs:complexType name="Response">
    <xs:sequence>
      <xs:element name="status" type="xs:string" />
      <xs:element name="state" type="xs:string" />
      <xs:element minOccurs="0" name="errorCode" type="xs:short" />
      <xs:element minOccurs="0" name="errorMessage" type="xs:string" />
      <xs:element minOccurs="0" name="messages" type="tns:Messages" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Messages">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="message" type="tns:Message" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Message">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="msgID" type="xs:string" use="required" />
        <xs:attribute name="trackingID" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>