<?xml version="1.0"?>
<xs:schema xmlns:ns1="http://cargowise.com/ehub/products/sgcustoms/mhaccess/2017/09" targetNamespace="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation=".\MHAccessGateway_Types.xsd" namespace="http://cargowise.com/ehub/products/sgcustoms/mhaccess/2017/09" />
  <xs:element name="deleteMessages" xmlns:q1="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q1:deleteMessages" />
  <xs:element name="deleteMessagesResponse" xmlns:q2="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q2:deleteMessagesResponse" />
  <xs:element name="retrieveMessages" xmlns:q3="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q3:retrieveMessages" />
  <xs:element name="retrieveMessagesResponse" xmlns:q4="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q4:retrieveMessagesResponse" />
  <xs:element name="submitMessage" xmlns:q5="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q5:submitMessage" />
  <xs:element name="submitMessageResponse" xmlns:q6="http://cargowise.com/ehub/products/sgcustoms/MHAccessGateway" type="q6:submitMessageResponse" />
  <xs:complexType name="deleteMessages">
    <xs:sequence>
      <xs:element form="qualified" name="username" type="xs:string" />
      <xs:element form="qualified" name="password" type="xs:string" />
      <xs:element minOccurs="0" form="qualified" name="trackingID" type="xs:string" />
      <xs:element maxOccurs="unbounded" form="qualified" name="mhaccessMsgID" nillable="true" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="deleteMessagesResponse">
    <xs:sequence>
      <xs:element minOccurs="0" ref="ns1:response" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="retrieveMessages">
    <xs:sequence>
      <xs:element form="qualified" name="username" type="xs:string" />
      <xs:element form="qualified" name="password" type="xs:string" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="retrieveMessagesResponse">
    <xs:sequence>
      <xs:element minOccurs="0" ref="ns1:response" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="submitMessage">
    <xs:sequence>
      <xs:element form="qualified" name="username" type="xs:string" />
      <xs:element form="qualified" name="password" type="xs:string" />
      <xs:element minOccurs="0" form="qualified" name="trackingID" type="xs:string" />
      <xs:element form="qualified" name="messageContent" nillable="true" type="xs:base64Binary" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="submitMessageResponse">
    <xs:sequence>
      <xs:element minOccurs="0" ref="ns1:response" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>