<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.ZClientASA.Testing</RootNamespace>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="NUnitCore" />
    <Reference Include="Enterprise.ZArchitecture.GUI.Test" />
    <Reference Include="CargoWise.Data" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientASA\ZClientASA.csproj" />
  </ItemGroup>
</Project>