<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.GlobalCommercialInvoice.Integration</RootNamespace>
    <AssemblyName>Enterprise.GlobalCommercialInvoice.Integration</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <ItemGroup>
    <Reference Include="CargoWise.ResourceStrings" />
  </ItemGroup>
</Project>