<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <NoWarn>$(NoWarn);NUnit2005</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Billing.API">
      <HintPath>..\Bin\Dependencies\CargoWise.Billing.API\CargoWise.Billing.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Client">
      <HintPath>..\Bin\Dependencies\CargoWise.Billing.Client\CargoWise.Billing.Client.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Kafka.API">
      <HintPath>..\Bin\Dependencies\CargoWise.Billing.API\CargoWise.Billing.Kafka.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Billing.Service">
      <HintPath>..\Bin\Dependencies\CargoWise.Billing.API\CargoWise.Billing.Service.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Integration">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eHub.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.AirMessaging.ServiceBroker.Services">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eHub.Products.AirMessaging.ServiceBroker.Services.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.Authentication.ServiceClient">
      <HintPath>..\Bin\Dependencies\CargoWise.eServices.Authentication\CargoWise.eServices.Authentication.ServiceClient.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.Monitoring.HealthCheck.API">
      <HintPath>..\bin\Dependencies\CargoWise.eServices.Monitoring.HealthCheck\CargoWise.eServices.Monitoring.HealthCheck.API.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.Monitoring.HealthCheck.API.Test">
      <HintPath>..\bin\Dependencies\CargoWise.eServices.Monitoring.HealthCheck\CargoWise.eServices.Monitoring.HealthCheck.API.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.Common">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.Integration">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandler">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandler.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerABIACE">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerABIACE.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerAES">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerAES.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerAMA">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerAMA.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerAMS">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerAMS.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerMAN">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerMAN.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MessageHandlerUEM">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MessageHandlerUEM.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfiguration">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfiguration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationABIACE">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationABIACE.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationAES">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationAES.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationAMA">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationAMA.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationAMS">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationAMS.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationMAN">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationMAN.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.MQConfigurationUEM">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.MQConfigurationUEM.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eServices.USCustoms.Services">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\CargoWise.eServices.USCustoms.Services.dll</HintPath>
    </Reference>
    <Reference Include="Confluent.Kafka">
      <HintPath>..\Bin\Dependencies\CargoWise.Billing.API\Confluent.Kafka.dll</HintPath>
    </Reference>
    <Reference Include="eServices.eHubDataAccess.Cache">
      <HintPath>..\Bin\Dependencies\eServices.eHubDataAccess\eServices.eHubDataAccess.Cache.dll</HintPath>
    </Reference>
    <Reference Include="eServices.eHubDataAccess.Integration">
      <HintPath>..\Bin\Dependencies\eServices.eHubDataAccess\eServices.eHubDataAccess.Integration.dll</HintPath>
    </Reference>
    <Reference Include="eServices.eHubDataAccess.Sql">
      <HintPath>..\Bin\Dependencies\eServices.eHubDataAccess\eServices.eHubDataAccess.Sql.dll</HintPath>
    </Reference>
    <Reference Include="ServiceBroker.Common">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\ServiceBroker.Common.dll</HintPath>
    </Reference>
    <Reference Include="ServiceBroker.Interface">
      <HintPath>..\Bin\Dependencies\eServices.eHubShared\ServiceBroker.Interface.dll</HintPath>
    </Reference>
    <Reference Include="eServices.eHubConfiguration.Helpers">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\eServices.eHubConfiguration.Helpers.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.ACAS.BR.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.ACAS.BR.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.AUCustomsNEXDOC.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.AUCustomsNEXDOC.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.CNCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.CNCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.ESCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.ESCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.GBCustoms.Core.ConfigurationHandler">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.GBCustoms.Core.ConfigurationHandler.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.GlobalInvoice.India.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.GlobalInvoice.India.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.GLSHK.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.GLSHK.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.ITCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.ITCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.JPCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.JPCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.SGCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.SGCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.TRCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.TRCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.TWCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.TWCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.eHub.Products.USCustoms.Configuration">
      <HintPath>..\Bin\Dependencies\eServices.eHubConfiguration\CargoWise.eHub.Products.USCustoms.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gateway\CargoWise.eHub.Gateway.csproj">
      <Private></Private>
      <CopyLocalSatelliteAssemblies></CopyLocalSatelliteAssemblies>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\FPM_XTMessage.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\GLB_ELEC_INVOICING_Fiji.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\GLB_ELEC_INVOICING_NoMessagingSystem.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\GLB_ELEC_INVOICING_PropertyMessageTypeTest.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\GLB_ELEC_INVOICING_Taiwan.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_eManifest.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_eManifest_NoSourceParty.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_MutipleRecipientsCopying.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_ShippingOrder.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_VGM_Booking.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\Routing\SqlMessage_VGM_Handling.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\BillingMessageHandlerV4\NonBilledUsage_Output_EmptyReference.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\BillingMessageHandlerV4\NonBilledUsage_Output_NullValue.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\BillingMessageHandlerV4\NonBilledUsage_Output.txt" />
    <EmbeddedResource Include="InboxMessageHandler\TestFiles\BillingMessageHandlerV4\NonBilledUsage_Input.txt" />
    <EmbeddedResource Include="KafkaLogging\TestFiles\CargoWise.eHub.Gateway.KafkaAppender.log4net.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CompareNETObjects" Version="3.5.0" />
    <PackageReference Include="librdkafka.redist" Version="2.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="3.8.3" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="RhinoMocks" Version="3.6.1" />
  </ItemGroup>
</Project>