<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(CWNetCoreTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Setup\CargoWise.Setup.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Moq">
      <HintPath>..\..\..\..\Bin\Moq.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Upgrades">
      <HintPath>..\..\..\..\Bin\net8.0\Enterprise.Upgrades.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
