<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreTargetFramework)</TargetFrameworks>
    <SuppressObsoleteWarnings>SYSLIB0011</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>true</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup>
    <NoWarn>$(NoWarn);IDE0044;CS8073</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AWSSDK.Core" />
    <Reference Include="AWSSDK.S3" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="CargoWise.Bi.Configuration" />
    <Reference Include="CargoWise.Bi.ConfigLoader" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="CargoWise.Data.Test" />
    <Reference Include="CargoWise.Database.Abstractions" />
    <Reference Include="CargoWise.Database.ExtendedProperties" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Database.TestFramework" />
    <Reference Include="CargoWise.DataProtection" />
    <Reference Include="CargoWise.DbUpgrader.Foundation" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.Build.Database.Script.TestFramework" />
    <Reference Include="Enterprise.ChangeDataCapture.Common" />
    <Reference Include="Enterprise.ChangeDataCapture.Common.Test" />
    <Reference Include="Enterprise.DbUpgrader.Resource.Version" />
    <Reference Include="Enterprise.DbUpgrader.Schema.Synchroniser" />
    <Reference Include="Enterprise.DbUpgrader.Schema.Template" />
    <Reference Include="Enterprise.DbUpgrader.Schema.Template.Test" />
    <Reference Include="Enterprise.DbUpgrader.Shared" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Enterprise.DbUpgrader.Shared.Testing" />
    <Reference Include="Microsoft.CodeAnalysis" />
    <Reference Include="Microsoft.CodeAnalysis.CSharp" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Text.Json" />
    <Reference Include="CargoWise.DbUpgrader.Scripts.Abstractions" />
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Data.Entity" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common.Test\Enterprise.DbUpgrader.Transformation.Common.Test.csproj" />
    <ProjectReference Include="..\Common\Enterprise.DbUpgrader.Transformation.Common.csproj" />
    <ProjectReference Include="..\Transformations\Enterprise.DbUpgrader.Transformations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Registry\CustomsRegistrySettings.xml">
      <LogicalName>CustomsRegistrySettings.xml</LogicalName>
      <DependentUpon>UpdateBECustomsRegistryNumberFountainDataTransformationTest.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Registry\UpdateUSOverseasTerritoriesExportStatementTest.AfterTransformation.xml">
      <LogicalName>UpdateUSOverseasTerritoriesExportStatementTest.AfterTransformation.xml</LogicalName>
      <DependentUpon>UpdateUSOverseasTerritoriesExportStatementTest.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Registry\UpdateUSOverseasTerritoriesExportStatementTest.BeforeTransformation.xml">
      <LogicalName>UpdateUSOverseasTerritoriesExportStatementTest.BeforeTransformation.xml</LogicalName>
      <DependentUpon>UpdateUSOverseasTerritoriesExportStatementTest.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>