<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ResourceStrings.Maintenance</RootNamespace>
    <AssemblyName>Enterprise.ResourceStrings.Maintenance</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="DoNotTranslate.txt" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Design" />
  </ItemGroup>
</Project>