//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from EdiIdentityApplicationRedirectUrlStatus.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Client.EDI.IdentityApplication.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class EdiIdentityApplicationRedirectUrlStatus : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Error = "ERR";
			public const string None = "NON";
			public const string Nudged = "NUD";
			public const string Scheduled = "SCH";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString Error { get { return ResString.GetMultilingualString("EdiIdentityApplicationRedirectUrlStatus|Error", "The synchronization has failed and will not be attempted again"); } }
			public static MultilingualString None { get { return ResString.GetMultilingualString("EdiIdentityApplicationRedirectUrlStatus|None", "The system is not synchronized"); } }
			public static MultilingualString Nudged { get { return ResString.GetMultilingualString("EdiIdentityApplicationRedirectUrlStatus|Nudged", "The redirect URL for this application has been updated, value will synchronize immediately"); } }
			public static MultilingualString Scheduled { get { return ResString.GetMultilingualString("EdiIdentityApplicationRedirectUrlStatus|Scheduled", "The system is synchronized based on the schedule run of the service task"); } }
		}

		public EdiIdentityApplicationRedirectUrlStatus()
		{
			AddPair(Codes.Error, Descriptions.Error);
			AddPair(Codes.None, Descriptions.None);
			AddPair(Codes.Nudged, Descriptions.Nudged);
			AddPair(Codes.Scheduled, Descriptions.Scheduled);
		}
	}
}
