// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Customs.ServiceTasks.NumberRangeThresholdRunOutChecker.GetNumberRangeThatHasReachWarning")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\ServiceTasks\ServiceTasks\NumberRangeThresholdRunOutChecker.cs:70:23
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.Customs.ServiceTasks.BranchCustomsMessagingService.DefaultPeriodInMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\ServiceTasks\ServiceTasks\CustomsMessaging\BranchCustomsMessagingService.cs:76:12
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.Customs.ServiceTasks.MultiCompanyCustomsMessagingService.DefaultPeriodInMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\ServiceTasks\ServiceTasks\CustomsMessaging\MultiCompanyCustomsMessagingService.cs:87:12
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.Customs.ServiceTasks.CustomsStmProcessQueueServiceTask.DefaultPeriodInSeconds")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Customs\Shared\ServiceTasks\ServiceTasks\CustomsStmProcessQueueServiceTask.cs:12:19
