using System.Diagnostics.CodeAnalysis;
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#IsSelected")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#OptionIndex")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#OptionIndexAsText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#Question")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#QuestionIndex")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#QuestionIndexWithPaddedZeroesAsString")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#QuestionPKs")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#ResultText")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Enterprise.Recruiter.Business.TestQuestionResultBusinessObject.#IsMultipleChoiceQuestion")]
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestAnswerSummaryCollectionTest.GetSurveyQuestion")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestAnswerSummary.cs:137,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestAnswerSummaryCollectionTest.GetSurveyQuestion")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestAnswerSummary.cs:146,36
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:83,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:86,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:89,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:92,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:95,31
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.ExamQuestionsImporterTestCase.TestNew")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/ExamQuestionsImporter.cs:98,31
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryPerQuestionCollectionTest.GetSurveyQuestion")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummaryPerQuestionCollection.cs:154,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryCollectionTest.GetSurveyQuestions")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummaryCollection.cs:137,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryTest.GetSurveyQuestion1")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummary.cs:234,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryTest.GetSurveyQuestion1")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummary.cs:243,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryTest.GetSurveyQuestion2")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummary.cs:261,36
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTestSummaryTest.GetSurveyQuestion2")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreTestSummary.cs:267,36
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.HRJobSkillTest.JobSkillDescription")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/JobSkillTest/HRJobSkillTest.cs:316,50
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.DocHRJobApplicantSkillRatingTestTest.TestProperties")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/DocumentWrappers/DocHRJobApplicantSkillRatingTest.cs:53,32
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTranslationDataSourceTest.TestGetSources")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Translation/LearningCentreTranslationDataSource.cs:182,11
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreTranslationDataSourceTest.TestGetSources")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Translation/LearningCentreTranslationDataSource.cs:182,91
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.LearningCentreCampaign.PopulateFromRelatedSkillTest(Enterprise.Recruiter.Business.HRJobSkillTest)")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreCampaign.cs:356,33
[assembly: SuppressMessage("CargoWiseOne", "EDI007:Customizable Data Translation Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Recruiter.Business.Testing.LearningCentreCampaignTest.TestPopulateFromRelatedSkillTest")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/LearningCentre/LearningCentreCampaign.cs:892,49
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditationJobSkillGroup.Groups")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditationJobSkillGroup/GlbAccreditationJobSkillGroup.cs:56,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditationJobSkillGroup.Skills")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditationJobSkillGroup/GlbAccreditationJobSkillGroup.cs:109,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditationJobSkillGroup.SkillPivots")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditationJobSkillGroup/GlbAccreditationJobSkillGroup.cs:79,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.RecruiterTestType.DocumentNames")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Registry/RecruiterTestType/RecruiterTestType.cs:270,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditation.Groups")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditation/GlbAccreditation.cs:454,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditation.SubsequentAccreditations")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditation/GlbAccreditation.cs:493,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditation.Requirements")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditation/GlbAccreditation.cs:516,5
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Recruiter.Business.GlbAccreditationGroup.Accreditations")] // Enterprise/Product/Operations/Recruiter/Recruiter.Business/Accreditation/GlbAccreditationGroup/GlbAccreditationGroup.cs:48,5
