using CargoWise.Customs.FR.MessageDefinitions.TP5.CC182C;
using CargoWise.Types;

namespace Enterprise.Customs.FR.Business.EdiMessages.Testing
{
	sealed class CC182CMessagePrettierTest : NCTSMessagePrettierTest<Cc182CType, CC182CMessageDataObject>
	{
		protected override ZString GetExpectedMessageInterpretation() => new ZString(@"<style>body, p, td {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px;}</style><pre><p style=""font-size: 120%""><strong>Status: </strong>Forwarded Incident Notification to ED<br><strong>MRN: </strong>MRN1<br><strong>Incident Notification Date: </strong>7/09/2024 12:20:30 PM<br><strong>Customs Office of Departure: </strong>referen1<br><strong>Customs Office of Incident Registration: </strong>referen1<br>
<br><strong>Incident: </strong>Token1<br><strong>  Text: </strong>text1<br><strong>  Code: </strong>Token1 -<br><strong>  Endorsement: </strong><br><strong>    Date: </strong>1/01/1900 12:00:00 AM<br><strong>    Authority: </strong>authority1<br><strong>    Place: </strong>place1<br><strong>    Country: </strong>c1<br><strong>  Location: </strong><br><strong>    UNLocode: </strong>Token1<br><strong>  Equipment: </strong><br><strong>    Container: </strong>containerIdentif1 - 0<br><strong>      Seal #: </strong>identifier1<br><strong>      Seal #: </strong>identifier2<br><strong>      Seal #: </strong>identifier3<br><strong>    Container: </strong>containerIdentif2 - 9999<br><strong>      Seal #: </strong>identifier4<br><strong>      Seal #: </strong>identifier5<br><strong>      Seal #: </strong>identifier6<br><strong>    Container: </strong>containerIdentif3 - 1<br><strong>      Seal #: </strong>identifier7<br><strong>      Seal #: </strong>identifier8<br><strong>      Seal #: </strong>identifier9<br>
<br><strong>Incident: </strong>Token2<br><strong>  Text: </strong>text2<br><strong>  Code: </strong>Token2 -<br><strong>  Endorsement: </strong><br><strong>    Date: </strong>1/01/0001 12:00:00 AM<br><strong>    Authority: </strong>authority2<br><strong>    Place: </strong>place2<br><strong>    Country: </strong>c2<br><strong>  Location: </strong><br><strong>    Street: </strong>streetAndNumber2<br><strong>    City: </strong>city2<br><strong>    Post Code: </strong>postcode2<br><strong>  Equipment: </strong><br><strong>    Container: </strong>containerIdentif4 - 9998<br><strong>      Seal #: </strong>identifier10<br><strong>      Seal #: </strong>identifier11<br><strong>      Seal #: </strong>identifier12<br><strong>    Container: </strong>containerIdentif5 - 2<br><strong>      Seal #: </strong>identifier13<br><strong>      Seal #: </strong>identifier14<br><strong>      Seal #: </strong>identifier15<br><strong>    Container: </strong>containerIdentif6 - 9997<br><strong>      Seal #: </strong>identifier16<br><strong>      Seal #: </strong>identifier17<br><strong>      Seal #: </strong>identifier18<br>
<br><strong>Incident: </strong>Token3<br><strong>  Text: </strong>text3<br><strong>  Code: </strong>Token3 -<br><strong>  Endorsement: </strong><br><strong>    Date: </strong>31/12/9999 12:00:00 AM<br><strong>    Authority: </strong>authority3<br><strong>    Place: </strong>place3<br><strong>    Country: </strong>c3<br><strong>  Location: </strong><br><strong>    Longitude: </strong>longitude3<br><strong>    Latitude: </strong>latitude3<br><strong>  Equipment: </strong><br><strong>    Container: </strong>containerIdentif7 - 3<br><strong>      Seal #: </strong>identifier19<br><strong>      Seal #: </strong>identifier20<br><strong>      Seal #: </strong>identifier21<br><strong>    Container: </strong>containerIdentif8 - 9996<br><strong>      Seal #: </strong>identifier22<br><strong>      Seal #: </strong>identifier23<br><strong>      Seal #: </strong>identifier24<br><strong>    Container: </strong>containerIdentif9 - 4<br><strong>      Seal #: </strong>identifier25<br><strong>      Seal #: </strong>identifier26<br><strong>      Seal #: </strong>identifier27</p></pre>");

		protected override ZString GetMessageText() => resourceRetriever.Value.GetString("Enterprise.Customs.FR.Business.Testing.EDIMessage.TestFiles.NCTS_CC182CResponseMessage.xml");
	}
}
