namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.Output
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[OutputBlock("KE")]
	public partial class CONKE : MessageBlock
	{
		public CONKE()
			: base("KE")
		{
		}

		/// <summary>
		/// The city portion of the business address if different from the mailing address.
		/// </summary>
		[MessageBlockString(21, 3, "M")]
		public ZString CitySecondaryAddress;

		/// <summary>
		/// The U.S. Postal Service state code, Canadian Province/Territory code, or FN for any other foreign business address.
		/// </summary>
		[MessageBlockString(2, 24, "M")]
		public ZString StateSecondaryAddress;

		/// <summary>
		/// The ZIP code as established by the U.S. Postal Service, Canadian Postal routing code in ANANAN format (where A = alphabetic and N = numeric), or other foreign postal routing code.
		/// </summary>
		[MessageBlockString(9, 26, "C")]
		public ZString ZIPSecondaryAddress;

		/// <summary>
		/// The International Organization for Standardization (ISO) country code of the business address if different from the mailing address. Valid ISO codes are listed in Appendix B of this publication.
		/// </summary>
		[MessageBlockString(2, 35, "C")]
		public ZString ISOCountryCodeSecondaryAddress;
	}
}
