using System.Diagnostics.CodeAnalysis;
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("CargoWiseOne", "EDI013:UnmaintainableProductName_XML", Justification = "Baseline issue")]
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIInterchange.GetSizeInKB")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\EDIInterchange.cs:889:21
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIInterchange.CheckInterchangeTypeIsSupportedForGMD")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\EDIInterchange.cs:1597:29
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.HttpXmlMessaging.HttpXmlEDIMessage.EM_MessageText")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\HttpXmlEDIMessage\HttpXmlEDIMessage.cs:34:29
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.HttpXmlMessaging.HttpXmlEDIMessage.EM_MessageInterpretation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\HttpXmlEDIMessage\HttpXmlEDIMessage.cs:49:29
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.HttpXmlMessaging.HttpXmlEDIMessage.EM_MessageText")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\HttpXmlEDIMessage\HttpXmlEDIMessage.cs:29:29
[assembly: SuppressMessage("CargoWiseOne", "CW1121:Do Not Include Column Values Or Names In Error Reporter Keys", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.HttpXmlMessaging.HttpXmlEDIMessage.EM_MessageInterpretation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\HttpXmlEDIMessage\HttpXmlEDIMessage.cs:44:29
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BatchProcessor.BatchDirectorBase.TimerIntervalInMilliseconds")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\BatchDirectorBase.cs:41:2
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.BatchProcessor.Schedule.TimeInterval.DurationMinutes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\Schedule.cs:326:3
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.Testing.DiagnosticsReportGeneratorTest.TestMessageFilter")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MailManager\DiagnosticsReportGenerator.cs:371:27
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.Testing.DiagnosticsReportGeneratorTest.InsertDiagnosticsRequest")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MailManager\DiagnosticsReportGenerator.cs:606:27
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.InterchangeProviders.Testing.InterchangeProviderTestCase.OtherCompany")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\InterchangeProviders\InterchangeProviderBase.cs:907:11
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.Schedule.RandomiseNextScheduledTime(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\Schedule.cs:222:41
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.DiagnosticsReportGenerator.GetMailItemsReport(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.Types.ZString,CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MailManager\DiagnosticsReportGenerator.cs:99:37
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.DiagnosticsReportGenerator.GetInterchangesReport(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.Types.ZString,CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MailManager\DiagnosticsReportGenerator.cs:178:44
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.Schedule.HourMinute.AddMinutes(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\Schedule.cs:275:15
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.BatchProcessor.Schedule.HourMinute.AddMinutes(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\Schedule.cs:275:26
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.Testing.BaseInterchangeSender_Test.BaseInterchangeSenderTimed.SendOutboundInterchanges(System.Threading.CancellationToken)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\BaseInterchangeSender.cs:867:34
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.Testing.BaseInterchangeSender_Test.BaseInterchangeSenderTimed.SendOutboundInterchanges(System.Threading.CancellationToken)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\BatchProcessor\BaseInterchangeSender.cs:868:34
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.MessageProcessors.MessageProcessor.CopyGroupToEmails(CargoWise.EntityFramework.IBusiness,Enterprise.ZArchitecture.Environment.EmailDef,CargoWise.Types.ZGuid)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:193:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.MessageProcessors.MessageProcessor.CopyGroupToEmails(CargoWise.EntityFramework.IBusiness,Enterprise.ZArchitecture.Environment.EmailDef,CargoWise.Types.ZGuid)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:198:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.MessageProcessors.MessageProcessor.MessageProcessorTestCase.SetUp")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:474:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.MessageProcessors.MessageProcessor.MessageProcessorTestCase.TestHelperMessageProcessor.AcknowledgementEmailGroup")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:513:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.MessageProcessors.MessageProcessor.MessageProcessorTestCase.TestHelperMessageProcessor.AcknowledgementEmailGroup")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:514:37
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.MessageProcessors.MessageProcessor.MessageProcessorTestCase.TestHelperMessageProcessor.AcknowledgementEmailGroup")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\MESSAGEPROCESSOR\MessageProcessor.cs:518:26
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageAttachTest.TestGetAttachment_CusEntryHeaderInShipment")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessageAttach\EDIMessageAttach.cs:129:17
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.Testing.InterchangeResenderTest.TestUnacknowledgeInterchangeCanBeResent")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\InterchangeResender.cs:137:38
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.Testing.InterchangeResenderTest.TestAcknowledgeInterchangeCanBeResentByForcing")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\InterchangeResender.cs:150:38
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.Testing.InterchangeResenderTest.TestAcknowledgeInterchangeCanBeResentByForcing")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\InterchangeResender.cs:157:23
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIMessageCollectionView.Test.GetCollectionToTest")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageCollectionView.cs:131:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIMessageCollectionView.Test.GetNewElementToAddToTheCollection")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageCollectionView.cs:138:11
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:47:35
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:50:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:54:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:68:44
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:74:17
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:75:29
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.FetchStrategy.Testing.EDIMessageFetchStrategyTest.TestFetchForLoad")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFetchStrategy.cs:80:20
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIMessageCollectionView.Test.SetUp")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageCollectionView.cs:147:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.EDIMessageFlattenedCollection.EDIMessageFlattenedCollectionTest.InterchangeWithAnAcknowledgement")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFlattenedCollection.cs:244:42
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.EDIMessageFlattenedCollection.EDIMessageFlattenedCollectionTest.InterchangeWithARejection")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageFlattenedCollection.cs:271:35
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIMessageCollectionTest.TestRelationshipSetForOldChild")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageCollection.cs:657:27
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Business.EDIMessageCollectionTest.TestWeAreNoLongerWaitingIfWeHaveReceivedAnAcknowledgementAndDontExpectToReceiveAResponse")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessageCollection.cs:706:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.EDIMessage.Interchange")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:340:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Messaging.Business.EDIInterchange.ExistingInterchangeMatchingToFromAndInterchangeNum")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\EDIInterchange.cs:1517:11
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIInterchangeTest.TestReplaceUniqueBatchNumberPlaceHolder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\EDIInterchange.cs:3169:17
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIInterchangeTest.SetUp")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIInterchange\EDIInterchange.cs:3517:17
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestGetAutoEdifactMessageUsingNamedFactory")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3346:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestFactoryNewSequenceNumber")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3397:25
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestFactoryNewSequenceNumber")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3398:25
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestFactoryNewSequenceNumber_WhenEDIMessageSavedToDb")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3404:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_MessageInterpretation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3412:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_InterchangeStatus")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3469:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_InterchangeStatus")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3470:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestReceiveTransmitValidation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3558:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestIsTransmitReceiveSetter")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3572:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestIsTransmitMessageGetter")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3582:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestDefaults")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3592:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestDontSetEscapeCharacterForUNOB")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3602:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestDontSetEscapeCharacterForUNOB")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3603:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_DateTimeInterchangeSent")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3611:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_DateTimeInterchangeSent")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3614:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestUNOACharacterSetWithoutInterchange")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3627:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestUNOBCharacterSetWithoutInterchange")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3634:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEdiMessageNumberPlaceHolderIsRestoredAfterFactoryFailedToSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3641:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEdiMessageNumberPlaceHolderIsRestoredAfterFactoryFailedToSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3645:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestCopyPersistentValuesFrom")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3661:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestCopyPersistentValuesFrom")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3662:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestCopyPersistentValuesFrom")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3665:30
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestAssumeMessageClearIfAcknowledgedAndNoResponse")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3687:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestContainedChecksumPlaceHolder")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3693:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsCusUnderbond")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3705:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsZAAsycudaManifestHeader")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3714:21
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsCusTempStorageDec")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3723:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsQuarantineExdocHeader")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3734:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestOwnerReferenceFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3743:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestSystemCommonAccessReferencePkPlaceholderFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3751:21
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestAgentReferenceFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3759:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEntryNumberFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3767:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestDocumentMessageVersionFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3775:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestBatchNumberFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3783:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestBatchNumberFilledInOnSave")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3787:17
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestAgentReferenceFilledInOnSave_WhenAgentsRefIsNull")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3796:49
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestClone")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:3804:21
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsCusPermitHeader")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:4151:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsCusReconDeclaration")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:4160:32
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Messaging.Testing.EDIMessageBaseOnlyTest.TestEM_LinkedObjectAsCusExitReport")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\Messaging\Enterprise.Messaging.Business\EDIMessage\EDIMessage.cs:4169:32
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Messaging.Business.SendersMessageReferenceProviderTest.TestPopulateSendersReferenceIfNeeded")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/EDIMessage/ISendersMessageReferenceProvider.cs:23,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Messaging.Business.SendersMessageReferenceProviderTest.TestPopulateSendersReferenceIfNeeded")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/EDIMessage/ISendersMessageReferenceProvider.cs:33,4
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.Testing.DiagnosticsReportGeneratorTest.TestGetReportDoesntBlowUpBadlyIfThereIsAnException")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/MailManager/DiagnosticsReportGenerator.cs:451,26
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.Testing.DiagnosticsReportGeneratorTest.TestGetReport")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/MailManager/DiagnosticsReportGenerator.cs:399,4
[assembly: SuppressMessage("CargoWiseOne", "EDI012:Unmaintainable Product Name CSharp", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.BatchProcessor.MailManager.Testing.DiagnosticsReportGeneratorTest.TestGetEnterpriseReport")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/MailManager/DiagnosticsReportGenerator.cs:513,22
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Messaging.Testing.MessageProcessingExceptionTest.MessageTextAllFormatted")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/EDIInterchange/MessageProcessingException.cs:117,17
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Messaging.Testing.MessageProcessingExceptionTest.MessageText")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/EDIInterchange/MessageProcessingException.cs:115,17
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Messaging.Testing.MessageProcessingExceptionTest.MessageTextCropped")] // Enterprise/Product/Core/Messaging/Enterprise.Messaging.Business/EDIInterchange/MessageProcessingException.cs:116,17
[assembly: SuppressMessage("CargoWiseOne", "CW1194:Usafe BusinessObjectCollection Creation", Justification = "Baseline WI00842925", Scope = "member", Target = "~P:Enterprise.Messaging.Business.EDIInterchange.LogCollection")]
