<?xml version="1.0" encoding="utf-8"?>
<xs:schema
	xmlns="http://www.edi.com.au/EnterpriseService/"
	attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	targetNamespace="http://www.edi.com.au/EnterpriseService/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

	<xs:include schemaLocation="..\..\..\..\..\Core\DataTransfer\DataTransfer\DataFileDefinitions\Xml\Version1\Elements.xsd" />

	<!-- Top Level Collection -->
	<xs:complexType name="SystemMergeWarehouseReceives">
		<xs:sequence>
			<xs:element maxOccurs="unbounded" name="Receive" type="SystemMergeWarehouseReceive" />
		</xs:sequence>
	</xs:complexType>

	<!-- Top Level Entity -->
	<xs:complexType name="SystemMergeWarehouseReceive">
		<xs:sequence>
			<xs:element minOccurs="0" name="PK" type="Guid"/>
			<xs:element minOccurs="0" name="ClientPK" type="Guid"/>
			<xs:element minOccurs="0" name="WarehousePK" type="Guid"/>
			<xs:element minOccurs="0" name="ExWhsJobGuid" type="Guid"/>
			<xs:element minOccurs="0" name="StagingAreaPK" type="Guid"/>

			<xs:element minOccurs="0" name="DocketType" type ="xs:string"/>
			<xs:element minOccurs="0" name="DocketSubType" type ="xs:string"/>
			<xs:element minOccurs="0" name="DocketID" type ="xs:string"/>
			<xs:element minOccurs="0" name="ExternalReference" type ="xs:string"/>
			<xs:element minOccurs="0" name="TotalWeightUnit" type ="xs:string"/>
			<xs:element minOccurs="0" name="TotalCubicUnit" type ="xs:string"/>
			<xs:element minOccurs="0" name="DocketStatus" type ="xs:string"/>
			<xs:element minOccurs="0" name="PickOption" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomerReference" type ="xs:string"/>
			<xs:element minOccurs="0" name="TransportReference" type ="xs:string"/>
			<xs:element minOccurs="0" name="DropMode" type ="xs:string"/>
			<xs:element minOccurs="0" name="CODPayMethod" type ="xs:string"/>
			<xs:element minOccurs="0" name="INCO" type ="xs:string"/>
			<xs:element minOccurs="0" name="TotalPackagesUnit" type ="xs:string"/>
			<xs:element minOccurs="0" name="F3_NKTotalPackType" type ="xs:string"/>
			<xs:element minOccurs="0" name="PL_NKCarrierServiceLevel" type ="xs:string"/>
			<xs:element minOccurs="0" name="RS_NKServiceLevel" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib1" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib2" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib3" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib4" type ="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib5" type ="xs:string"/>

			<xs:element minOccurs="0" name="TotalUnits" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="UnitsSent" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="LocalCartageCost" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CubicSent" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="LocalCartInsuranceCost" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="ShipperCODAmount" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="WeightSent" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="WeightSentUserEntered" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal1" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal2" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal3" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal4" type ="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal5" type ="xs:decimal"/>

			<xs:element minOccurs="0" name="PackagesSent" type="xs:int"/>

			<xs:element minOccurs="0" name="TotalPallets" type="xs:short"/>
			<xs:element minOccurs="0" name="TotalHirePallets" type="xs:short"/>
			<xs:element minOccurs="0" name="PalletsSent" type="xs:short"/>
			
			<xs:element minOccurs="0" name="ExternalReferenceSplit" type="xs:unsignedByte"/>

			<xs:element minOccurs="0" name="WeightVolSetFromImport" type="xs:boolean"/>
			<xs:element minOccurs="0" name="AddPalletWeightToOrder" type="xs:boolean"/>
			<xs:element minOccurs="0" name="AutoFinaliseBOMIntoInventory" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag1" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag2" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag3" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag4" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag5" type="xs:boolean"/>

			<xs:element minOccurs="0" name="BookingDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="ArrivalDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="FinalisedDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="RequiredDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="ETADateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="ETDDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate1" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate2" type="xs:dateTime"/>

			<!-- Dependent Collections-->

			<xs:element minOccurs="0" name ="DocketReferences">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="DocketReference" type="SystemMergeDocketReference" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element minOccurs="0" name ="ReceiveLines">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="ReceiveLine" type="SystemMergeReceiveLine" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!--Docket Reference Entity-->
	<xs:complexType name="SystemMergeDocketReference">
		<xs:sequence>
			<xs:element minOccurs="0" name="PK" type="Guid" />

			<xs:element minOccurs="0" name="RefType" type="xs:string"/>
			<xs:element minOccurs="0" name="Reference" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	 <!--Receive Line Entity-->
	<xs:complexType name ="SystemMergeReceiveLine">
		<xs:sequence>
			<xs:element minOccurs="0" name="PK" type="Guid" />
			<xs:element minOccurs="0" name="LocationPK" type="Guid"/>
			<xs:element minOccurs="0" name="ProductPK" type="Guid"/>

			<xs:element minOccurs="0" name="PackType" type="xs:string"/>
			<xs:element minOccurs="0" name="PartAttrib1" type="xs:string"/>
			<xs:element minOccurs="0" name="PartAttrib2" type="xs:string"/>
			<xs:element minOccurs="0" name="PartAttrib3" type="xs:string"/>
			<xs:element minOccurs="0" name="SerialNumber" type="xs:string"/>
			<xs:element minOccurs="0" name="BondedEntryKey" type="xs:string"/>
			<xs:element minOccurs="0" name="ChargableUnitsUQ" type="xs:string"/>
			<xs:element minOccurs="0" name="LineComment" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib1" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib2" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib3" type="xs:string"/>
			<xs:element minOccurs="0" name="DocketLineStatus" type="xs:string"/>
			<xs:element minOccurs="0" name="RX_NKUnitPriceCurrency" type="xs:string"/>
			<xs:element minOccurs="0" name="F3_NKPackType" type="xs:string"/>
			<xs:element minOccurs="0" name="PalletID" type="xs:string"/>
			<xs:element minOccurs="0" name="ReceiveCrossDockOrderNo" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib4" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib5" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomAttrib6" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomTextBlob1" type="xs:string"/>

			<xs:element minOccurs="0" name="ExpiryDate" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="PackingDate" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="AdjustmentArrivalDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="FinalisedDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="RequiredByDateTimeOffset" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate1" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate2" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate3" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate4" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomDate5" type="xs:dateTime"/>

			<xs:element minOccurs="0" name="Units" type="xs:decimal"/>
			<xs:element minOccurs="0" name="UnitsMet" type="xs:decimal"/>
			<xs:element minOccurs="0" name="ChargableUnits" type="xs:decimal"/>
			<xs:element minOccurs="0" name="ClientOrderedUnits" type="xs:decimal"/>
			<xs:element minOccurs="0" name="RecommendedUnitPrice" type="xs:decimal"/>
			<xs:element minOccurs="0" name="UnitDiscountPercent" type="xs:decimal"/>
			<xs:element minOccurs="0" name="UnitDiscountAmount" type="xs:decimal"/>
			<xs:element minOccurs="0" name="UnitPriceAfterDiscount" type="xs:decimal"/>
			<xs:element minOccurs="0" name="ExtendedLinePrice" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal1" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal2" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal3" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal4" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomDecimal5" type="xs:decimal"/>

			<xs:element minOccurs="0" name="LineNo" type="xs:short"/>
			<xs:element minOccurs="0" name="SubLineNo" type="xs:short"/>

			<xs:element minOccurs="0" name="CustomFlag1" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag2" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag3" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag4" type="xs:boolean"/>
			<xs:element minOccurs="0" name="CustomFlag5" type="xs:boolean"/>

			<xs:element minOccurs="0" name="CustomsData" type="SystemMergeBondedWarehouseAttribute"/>
			
			<!-- Dependent Collections-->

			<xs:element minOccurs ="0" name ="Inventories">
				<xs:complexType>
					<xs:sequence>
						<xs:element maxOccurs="unbounded" name="Inventory" type="SystemMergeInventory"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<!--Bonded Warehouse Attribute Entity-->
	<xs:complexType name ="SystemMergeBondedWarehouseAttribute">
		<xs:sequence>
			<xs:element minOccurs="0" name="PK" type="Guid"/>
			<xs:element minOccurs="0" name="WB_InwardsEntry" type="Guid"/>
			<xs:element minOccurs="0" name="ParentID" type="Guid"/>

			<xs:element minOccurs="0" name="DeclarationReference" type="xs:string"/>
			<xs:element minOccurs="0" name="EntryKey" type="xs:string"/>
			<xs:element minOccurs="0" name="CustomsUnitOfQty" type="xs:string"/>
			<xs:element minOccurs="0" name="BondedWhsUnitOfQty" type="xs:string"/>
			<xs:element minOccurs="0" name="RN_NKCountryOfOrigin" type="xs:string"/>
			<xs:element minOccurs="0" name="AddInfo" type="xs:string"/>
			<xs:element minOccurs="0" name="ParentTableCode" type="xs:string"/>
			<xs:element minOccurs="0" name="RX_NKTILVCurrency" type="xs:string"/>

			<xs:element minOccurs="0" name="IsActive" type="xs:boolean"/>

			<xs:element minOccurs="0" name="EntryLineNo" type="xs:short"/>

			<xs:element minOccurs="0" name="CustomsQty" type="xs:decimal"/>
			<xs:element minOccurs="0" name="BondedWhsQty" type="xs:decimal"/>
			<xs:element minOccurs="0" name="ValueForDuty" type="xs:decimal"/>
			<xs:element minOccurs="0" name="TILV" type="xs:decimal"/>

			<xs:element minOccurs="0" name="EntryDate" type="xs:dateTime"/>
			<xs:element minOccurs="0" name="CustomsSecondQuantity" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomsSecondUnitQty" type="xs:string"/>
			<xs:element minOccurs="0" name="Tariff" type="xs:string"/>
			<xs:element minOccurs="0" name="PrimaryPreference" type="xs:string"/>
			
			<xs:element minOccurs="0" name="CustomsThirdQuantity" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CustomsThirdUnitQty" type="xs:string"/>
			<xs:element minOccurs="0" name="ManufacturerAddress" type="Guid"/>
			<xs:element minOccurs="0" name="ZoneStatus" type="xs:string"/>
			<xs:element minOccurs="0" name="IsFromOtherFTZWarehouse" type="xs:boolean"/>
			<xs:element minOccurs="0" name="OutwardType" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<!--Inventory Line Entity-->
	<xs:complexType name="SystemMergeInventory">
		<xs:sequence>
			<xs:element minOccurs="0" name="PK" type="Guid" />

			<xs:element minOccurs="0" name="InventoryStatus" type="xs:string"/>
			<xs:element minOccurs="0" name="InDocketLineType" type="xs:string"/>
			<xs:element minOccurs="0" name="PackType" type="xs:string"/>
			<xs:element minOccurs="0" name="F3_NKPackType" type="xs:string"/>
			<xs:element minOccurs="0" name="PalletID" type="xs:string"/>

			<xs:element minOccurs="0" name="TotalUnits" type="xs:decimal"/>
			<xs:element minOccurs="0" name="CommittedUnits" type="xs:decimal"/>
			<xs:element minOccurs="0" name="InDocketLineUnits" type="xs:decimal"/>

			<xs:element minOccurs="0" name="ArrivalDateTimeOffset" type="xs:dateTime"/>

			<xs:element minOccurs="0" name="IsOriginalReceiptLine" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>
