CREATE TABLE RefCarrierVesselPivot (
	[ZZQ_PK] [UNIQUEIDENTIFIER] ROWGUIDCOL  NOT NULL,
	[ZZQ_ZZ4] [UNIQUEIDENTIFIER] NOT NULL,
	[ZZQ_ZZO] [UNIQUEIDENTIFIER] NOT NULL,
	[ZZQ_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZZQ_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZZQ_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZZQ_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZZQ_SysStartTime], [ZZQ_SysEndTime]),
	CONSTRAINT [PK_RefCarrierVesselPivot] PRIMARY KEY CLUSTERED ([ZZQ_PK] ASC),
	CONSTRAINT [FK_RefCarrierVesselPivot_Carrier] FOREIGN KEY([ZZQ_ZZ4])  REFERENCES [RefCarrierCode] ([ZZ4_PK]),
	CONSTRAINT [FK_RefCarrierVesselPivot_Vessel] FOREIGN KEY([ZZQ_ZZO])  REFERENCES [RefVesselZZ] ([ZZO_PK])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCarrierVesselPivotHistory))
GO
CREATE NONCLUSTERED INDEX IX_RefCarrierVesselPivot_ZZQ_ZZ4 ON RefCarrierVesselPivot(ZZQ_ZZ4 ASC)
GO
CREATE NONCLUSTERED INDEX IX_RefCarrierVesselPivot_ZZQ_ZZO ON RefCarrierVesselPivot(ZZQ_ZZO ASC)
GO
ALTER TABLE RefCarrierVesselPivot SET (LOCK_ESCALATION = DISABLE);
