CREATE TABLE RefCusRateCodeLanguage(
	[ZXC_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusRateCodeLanguage_ZXC_PK] DEFAULT(NEWID()),
	[ZXC_ZX6_NKLanguage] VARCHAR(3) NOT NULL,
	[ZXC_ZY1_RateCode] UNIQUEIDENTIFIER NOT NULL,
	[ZXC_Description] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_RefCusRateCodeLanguage_ZXC_Description] DEFAULT(''),
	[ZXC_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZXC_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZXC_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZXC_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	[ZXC_DataSetPK] UNIQUEIDENTIFIER,
	[ZXC_DataSetCode] VARCHAR(3),
	PERIOD FOR SYSTEM_TIME ([ZXC_SysStartTime], [ZXC_SysEndTime]),
	CONSTRAINT [PK_RefCusRateCodeLanguage] PRIMARY KEY CLUSTERED ([ZXC_PK] ASC),
	CONSTRAINT [FK_RefCusRateCodeLanguage_RefCusRateCode] FOREIGN KEY([ZXC_ZY1_RateCode]) REFERENCES RefCusRateCode ([ZY1_PK]),
	CONSTRAINT [FK_RefCusRateCodeLanguage_RefLanguageType] FOREIGN KEY([ZXC_ZX6_NKLanguage]) REFERENCES RefLanguageType ([ZX6_Language])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusRateCodeLanguageHistory))
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusRateCodeLanguage_ZXC_ZX6_NKLanguage_ZXC_ZY1_RateCode ON RefCusRateCodeLanguage(ZXC_ZX6_NKLanguage, ZXC_ZY1_RateCode)
GO
ALTER TABLE RefCusRateCodeLanguage SET (LOCK_ESCALATION = DISABLE);
