CREATE TABLE RefCusRateRule (
	ZZ2_PK UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_RefCusRateRule_ZZ2_PK DEFAULT (NEWID()),
	ZZ2_ZZ1_Tariff UNIQUEIDENTIFIER NOT NULL,
	ZZ2_RateFormula VARCHAR(500) NOT NULL,
	ZZ2_SelectorFormula VARCHAR(500) NOT NULL CONSTRAINT DF_RefCusRateRule_ZZ2_SelectorFormula DEFAULT (''),
	ZZ2_ZZZ_NKDataGrouping VARCHAR(3) NOT NULL CONSTRAINT DF_RefCusRateRule_ZZ2_ZZZ_NKDataGrouping DEFAULT (''),
	ZZ2_RateFormulaDerivedFrom NVARCHAR(1000) NULL,
CONSTRAINT PK_RefCusRateRule PRIMARY KEY CLUSTERED( ZZ2_PK ASC ),
CONSTRAINT FK_RefCusRateRule_RefCusTariff FOREIGN KEY(ZZ2_ZZ1_Tariff) REFERENCES RefCusTariffRule (ZZ1_PK) ON DELETE CASCADE,
CONSTRAINT CK_RefCusRateRule_ZZ2_RateFormula CHECK (ZZ2_RateFormula <>'')
)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusRateRule_ZZ2_ZZ1_Tariff_ZZ2_SelectorFormula ON RefCusRateRule(ZZ2_ZZ1_Tariff ASC, ZZ2_SelectorFormula ASC)
GO
ALTER TABLE RefCusRateRule SET (LOCK_ESCALATION = DISABLE);
