CREATE TABLE RefCusCodeTypeLanguage(
	[ZXI_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusCodeTypeLanguage_ZXI_PK] DEFAULT(NEWID()),
	[ZXI_ZX6_NKLanguage] VARCHAR(3) NOT NULL,
	[ZXI_ZZK_CodeType] UNIQUEIDENTIFIER NOT NULL,
	[ZXI_Description] NVARCHAR(MAX) NOT NULL CONSTRAINT [DF_RefCusCodeTypeLanguage_ZXI_Description] DEFAULT (''),
	[ZXI_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZXI_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZXI_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZXI_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZXI_SysStartTime], [ZXI_SysEndTime]),
	CONSTRAINT [PK_RefCusCodeTypeLanguage] PRIMARY KEY CLUSTERED ([ZXI_PK] ASC),
	CONSTRAINT [FK_RefCusCodeTypeLanguage_ZXI_ZX6_NKLanguage] FOREIGN KEY([ZXI_ZX6_NKLanguage]) REFERENCES RefLanguageType ([ZX6_Language]),
	CONSTRAINT [FK_RefCusCodeTypeLanguage_ZXI_ZZK_CodeType] FOREIGN KEY([ZXI_ZZK_CodeType]) REFERENCES RefCusCodeType ([ZZK_PK]),
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusCodeTypeLanguageHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusCodeTypeLanguage_ZXI_ZX6_NKLanguage_ZXI_ZZK_CodeType ON RefCusCodeTypeLanguage (ZXI_ZX6_NKLanguage, ZXI_ZZK_CodeType)
GO
ALTER TABLE RefCusCodeTypeLanguage SET (LOCK_ESCALATION = DISABLE);
