CREATE TABLE RefCusTariffUOM(
	[ZZ8_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusTariffUOM_ZZ8_PK] DEFAULT (NEWID()),
	[ZZ8_ZZ1_Tariff] UNIQUEIDENTIFIER NULL,
	[ZZ8_Type] VARCHAR(3) NOT NULL,
	[ZZ8_UOM] VARCHAR(10) NOT NULL,
	[ZZ8_ZZA_TradeGroup] UNIQUEIDENTIFIER SPARSE NULL,
	[ZZ8_ZZW_TariffNationalCode] UNIQUEIDENTIFIER SPARSE NULL,
	[ZZ8_ZZZ_NKDataGrouping] VARCHAR(3) NOT NULL CONSTRAINT [DF_RefCusTariffUOM_ZZ8_ZZZ_NKDataGrouping] DEFAULT (''),
	[ZZ8_DataSetPK] UNIQUEIDENTIFIER,
	[ZZ8_DataSetCode] VARCHAR(3),
	[ZZ8_ZZA_SecondTradeGroup] UNIQUEIDENTIFIER SPARSE NULL,
	[ZZ8_StartDate] SMALLDATETIME SPARSE NULL,
	[ZZ8_EndDate] SMALLDATETIME SPARSE NULL,
	[ZZ8_SysStartTime]  DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZZ8_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZZ8_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZZ8_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZZ8_SysStartTime], [ZZ8_SysEndTime]),
	CONSTRAINT [PK_RefCusTariffUOM] PRIMARY KEY CLUSTERED( [ZZ8_PK] ASC ),
	CONSTRAINT [FK_RefCusTariffUOM_RefCusTariff] FOREIGN KEY([ZZ8_ZZ1_Tariff]) REFERENCES RefCusTariff ([ZZ1_PK]),
	CONSTRAINT [FK_RefCusTariffUOM_RefCusTradeGroup] FOREIGN KEY([ZZ8_ZZA_TradeGroup]) REFERENCES RefCusTradeGroup ([ZZA_PK]),
	CONSTRAINT [FK_RefCusTariffUOM_RefCusTariffNationalCode] FOREIGN KEY([ZZ8_ZZW_TariffNationalCode]) REFERENCES RefCusTariffNationalCode ([ZZW_PK]),
	CONSTRAINT [FK_RefCusTariffUOM_RefCusTradeGroup2] FOREIGN KEY([ZZ8_ZZA_SecondTradeGroup]) REFERENCES RefCusTradeGroup ([ZZA_PK]),
	CONSTRAINT [CK_RefCusTariffUOM_ZZ8_Type] CHECK ([ZZ8_Type]='CU1' OR [ZZ8_Type]='RU1' OR [ZZ8_Type]='AD1' OR [ZZ8_Type]='CU2' OR [ZZ8_Type]='CU3' OR [ZZ8_Type]='CU4' OR [ZZ8_Type]='CU5'),
	CONSTRAINT [CK_RefCusTariffUOM_ZZ8_UOM] CHECK ([ZZ8_UOM] <>''),
	CONSTRAINT [CK_RefCusTariffUOM_ZZ8_ZZ1_Tariff_ZZ8_ZZW_TariffNationalCode] CHECK (([ZZ8_ZZ1_Tariff] IS NULL AND [ZZ8_ZZW_TariffNationalCode] IS NOT NULL) OR ([ZZ8_ZZ1_Tariff] IS NOT NULL AND [ZZ8_ZZW_TariffNationalCode] IS NULL)),
	CONSTRAINT [CK_RefCusTariffUOM_ZZ8_StartDate_ZZ8_EndDate] CHECK (([ZZ8_StartDate] IS NULL AND [ZZ8_EndDate] IS NULL) OR ([ZZ8_StartDate] IS NOT NULL AND [ZZ8_EndDate] IS NOT NULL AND [ZZ8_StartDate] <= [ZZ8_EndDate]))

)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[RefCusTariffUOMHistory]))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefCusTariffUOM_ZZ8_ZZ1_Tariff_ZZ8_Type_ZZ8_UOM_ZZ8_ZZZ_NKDataGrouping_ZZ8_ZZA_TradeGroup_ZZ8_ZZW_TariffNationalCode] ON RefCusTariffUOM([ZZ8_ZZ1_Tariff] ASC, [ZZ8_Type] ASC, [ZZ8_UOM] ASC, [ZZ8_ZZZ_NKDataGrouping] ASC, [ZZ8_ZZA_TradeGroup] ASC, [ZZ8_ZZW_TariffNationalCode] ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefCusTariffUOM_Tariff_Type_UOM_NKDataGrouping_TradeGroup_SecondTradeGroup_StartDate_TariffNationalCode] ON RefCusTariffUOM([ZZ8_ZZ1_Tariff] ASC, [ZZ8_Type] ASC, [ZZ8_UOM] ASC, [ZZ8_ZZZ_NKDataGrouping] ASC, [ZZ8_ZZA_TradeGroup] ASC, [ZZ8_ZZA_SecondTradeGroup] ASC, [ZZ8_StartDate] ASC, [ZZ8_ZZW_TariffNationalCode] ASC)
GO
CREATE NONCLUSTERED INDEX [IX_RefCusTariffUOM_ZZ8_DataSetPK_ZZ8_DataSetCode] ON [RefCusTariffUOM]([ZZ8_DataSetPK] ASC, [ZZ8_DataSetCode] ASC)
GO
ALTER TABLE RefCusTariffUOM SET (LOCK_ESCALATION = DISABLE);
