CREATE TABLE RefCusRuling(
	[ZZX_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusRuling_ZZX_PK] DEFAULT (NEWID()),
	[ZZX_RN_NKCountryCode] CHAR(2) NOT NULL,
	[ZZX_RulingNumber] VARCHAR(35) NOT NULL,
	[ZZX_Description] VARCHAR(500) NOT NULL,
	[ZZX_RulingType] CHAR(3) NOT NULL,
	[ZZX_StartDate] DATE NOT NULL CONSTRAINT [DF_RefCusRuling_ZZX_StartDate] DEFAULT GetUtcDate(),
	[ZZX_EndDate] DATE NOT NULL CONSTRAINT [DF_RefCusRuling_ZZX_EndDate] DEFAULT ('2079-06-06 23:59'),
	[ZZX_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZZX_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZZX_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZZX_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZZX_SysStartTime], [ZZX_SysEndTime]),
	CONSTRAINT [PK_RefCusRuling] PRIMARY KEY CLUSTERED ([ZZX_PK] ASC),
	CONSTRAINT [CK_RefCusRuling_RN_NKCountryCode] CHECK (LEN([ZZX_RN_NKCountryCode]) = 2),
	CONSTRAINT [CK_RefCusRuling_RulingNumber] CHECK ([ZZX_RulingNumber] <>''),
	CONSTRAINT [CK_RefCusRuling_Description] CHECK ([ZZX_Description] <>''),
	CONSTRAINT [CK_RefCusRuling_RulingType] CHECK ([ZZX_RulingType] <>''),
	CONSTRAINT [CK_RefCusRuling_EndDate] CHECK ([ZZX_EndDate] >= [ZZX_StartDate])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusRulingHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusRuling_ZZX_RN_NKCountryCode_ZZX_RulingNumber_ZZX_RulingType_ZZX_StartDate ON RefCusRuling(ZZX_RN_NKCountryCode ASC, ZZX_RulingNumber ASC, ZZX_RulingType ASC, ZZX_StartDate ASC)
GO
ALTER TABLE RefCusRuling SET (LOCK_ESCALATION = DISABLE);
