CREATE TABLE RefCusRulingConfig(
	[ZZY_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusRulingConfig_ZZY_PK] DEFAULT NEWID(),
	[ZZY_Category] VARCHAR(3) NOT NULL,
	[ZZY_Type] VARCHAR(15) NOT NULL,
	[ZZY_Rate] DECIMAL(9,3) NOT NULL CONSTRAINT [DF_RefCusRulingConfig_ZZY_Rate] DEFAULT 0,
	[ZZY_Value] VARCHAR(35) NOT NULL CONSTRAINT [DF_RefCusRulingConfig_ZZY_Value] DEFAULT '',
	[ZZY_ZZX_CusRuling] UNIQUEIDENTIFIER NOT NULL,
	[ZZY_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZZY_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZZY_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZZY_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZZY_SysStartTime], [ZZY_SysEndTime]),
	CONSTRAINT [PK_RefCusRulingConfig] PRIMARY KEY CLUSTERED ([ZZY_PK] ASC),
	CONSTRAINT [CK_RefCusRulingConfig_Category] CHECK ([ZZY_Category]='DTY' OR [ZZY_Category]='EXC' OR [ZZY_Category]='SIM' OR [ZZY_Category]='GST'),
	CONSTRAINT [CK_RefCusRulingConfig_Type] CHECK ([ZZY_Type] <>''),
	CONSTRAINT [CK_RefCusRulingConfig_Rate] CHECK ([ZZY_Rate] >= 0),
	CONSTRAINT [FK_RefCusRulingConfig_ZZY_ZZX_CusRuling] FOREIGN KEY([ZZY_ZZX_CusRuling]) REFERENCES RefCusRuling([ZZX_PK])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusRulingConfigHistory))
GO
CREATE NONCLUSTERED INDEX IX_RefCusRulingConfig_ZZY_ZZX_CusRuling ON RefCusRulingConfig(ZZY_ZZX_CusRuling ASC)
GO
ALTER TABLE RefCusRulingConfig SET (LOCK_ESCALATION = DISABLE);
