CREATE TABLE RefCusConditionValue(
	[ZX3_PK]	UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusConditionValue_ZX3_PK] DEFAULT NEWID(),
	[ZX3_ZX4_ValueType]	UNIQUEIDENTIFIER  NOT NULL,
	[ZX3_ZX1_Condition]	UNIQUEIDENTIFIER	NOT NULL,
	[ZX3_Value]	NVARCHAR(500)	NOT NULL,
	[ZX3_LogicalORWithinGroup] TINYINT NOT NULL CONSTRAINT [DF_RefCusConditionValue_ZX3_LogicalORWithinGroup] DEFAULT 0,
	[ZX3_DataSetPK] UNIQUEIDENTIFIER,
	[ZX3_DataSetCode] VARCHAR(3),
	[ZX3_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZX3_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZX3_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZX3_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZX3_SysStartTime], [ZX3_SysEndTime]),
	CONSTRAINT [PK_RefCusConditionValue] PRIMARY KEY CLUSTERED( [ZX3_PK] ASC ),
	CONSTRAINT [FK_RefCusConditionValue_RefCusConditionValueType] FOREIGN KEY ([ZX3_ZX4_ValueType]) REFERENCES RefCusConditionValueType ([ZX4_PK]),
	CONSTRAINT [FK_RefCusConditionValue_RefCusCondition] FOREIGN KEY ([ZX3_ZX1_Condition]) REFERENCES RefCusCondition ([ZX1_PK]),
	CONSTRAINT [CK_RefCusConditionValue_ZX3_Value] CHECK ([ZX3_Value] <> ''),
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusConditionValueHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusConditionValue_ZX3_ZX1_Condition_ZX3_ZX4_ValueType_ZX3_Value ON RefCusConditionValue(ZX3_ZX1_Condition, ZX3_ZX4_ValueType, ZX3_Value)
GO
CREATE NONCLUSTERED INDEX IX_RefCusConditionValue_ZX3_DataSetPK_ZX3_DataSetCode ON RefCusConditionValue(ZX3_DataSetPK ASC, ZX3_DataSetCode ASC)
GO
ALTER TABLE RefCusConditionValue SET (LOCK_ESCALATION = DISABLE);
