CREATE TABLE RefCusCodeListAttribute(
	[ZZE_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusCodeListAttribute_ZZE_PK] DEFAULT (NEWID()),
	[ZZE_ZZD_CodeList] UNIQUEIDENTIFIER NOT NULL,
	[ZZE_ZXE_NKName] VARCHAR(32) NOT NULL,
	[ZZE_Value] NVARCHAR(255) NOT NULL,
	[ZZE_StartDate] SMALLDATETIME SPARSE NULL,
	[ZZE_EndDate] SMALLDATETIME SPARSE NULL,
	[ZZE_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZZE_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZZE_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZZE_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZZE_SysStartTime], [ZZE_SysEndTime]),
	CONSTRAINT [PK_RefCusCodeListAttribute] PRIMARY KEY CLUSTERED( [ZZE_PK] ASC ),
	CONSTRAINT [FK_RefCusCodeListAttribute_RefCusCodeList] FOREIGN KEY([ZZE_ZZD_CodeList]) REFERENCES RefCusCodeList ([ZZD_PK]),
	CONSTRAINT [CK_RefCusCodeListAttribute_ZZE_Name] CHECK ([ZZE_ZXE_NKName] <>''),
	CONSTRAINT [CK_RefCusCodeListAttribute_ZZE_StartDate_ZZE_EndDate] CHECK (([ZZE_StartDate] IS NULL AND [ZZE_EndDate] IS NULL) OR ([ZZE_StartDate] IS NOT NULL AND [ZZE_EndDate] IS NOT NULL AND [ZZE_StartDate] < [ZZE_EndDate]))
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusCodeListAttributeHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusCodeListAttribute_ZZE_ZZD_CodeList_ZZE_ZXE_NKName_ZZE_StartDate_ZZE_Value ON RefCusCodeListAttribute(ZZE_ZZD_CodeList ASC, ZZE_ZXE_NKName ASC, ZZE_StartDate ASC, ZZE_Value ASC)
GO
ALTER TABLE RefCusCodeListAttribute SET (LOCK_ESCALATION = DISABLE);
