CREATE TABLE RefCusTradeGroupLanguage(
	[ZXD_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefCusTradeGroupLanguage_ZXD_PK] DEFAULT(NEWID()),
	[ZXD_ZX6_NKLanguage] VARCHAR(3) NOT NULL,
	[ZXD_ZZA_TradeGroup] UNIQUEIDENTIFIER NOT NULL,
	[ZXD_Description] NVARCHAR(MAX) NOT NULL CONSTRAINT DF_RefCusTradeGroupLanguage_ZXD_Description DEFAULT '',
	[ZXD_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZXD_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZXD_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZXD_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZXD_SysStartTime], [ZXD_SysEndTime]),
	CONSTRAINT [PK_RefCusTradeGroupLanguage] PRIMARY KEY CLUSTERED ([ZXD_PK] ASC),
	CONSTRAINT [FK_RefCusTradeGroupLanguage_RefLanguageType] FOREIGN KEY([ZXD_ZX6_NKLanguage]) REFERENCES RefLanguageType ([ZX6_Language]),
	CONSTRAINT [FK_RefCusTradeGroupLanguage_RefCusTradeGroup] FOREIGN KEY([ZXD_ZZA_TradeGroup]) REFERENCES RefCusTradeGroup ([ZZA_PK])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefCusTradeGroupLanguageHistory))
GO

CREATE UNIQUE NONCLUSTERED INDEX IX_RefCusTradeGroupLanguage_ZXD_ZX6_NKLanguage_ZXD_ZZA_TradeGroup ON RefCusTradeGroupLanguage([ZXD_ZX6_NKLanguage], [ZXD_ZZA_TradeGroup])
GO
ALTER TABLE RefCusTradeGroupLanguage SET (LOCK_ESCALATION = DISABLE);
