CREATE TABLE [RefDamage] (
   [RFM_PK] UNIQUEIDENTIFIER NOT NULL,
   [RFM_IsActive] BIT NOT NULL CONSTRAINT [DF_RefDamage_RFM_IsActive] DEFAULT (1),
   [RFM_Code] VARCHAR(10) NOT NULL CONSTRAINT [DF_RefDamage_RFM_Code] DEFAULT (''),
   [RFM_Description] VARCHAR(240) NOT NULL CONSTRAINT [DF_RefDamage_RFM_Description] DEFAULT (''),
   [RFM_Group] VARCHAR(25) NOT NULL CONSTRAINT [DF_RefDamage_RFM_Group] DEFAULT (''),
   [RFM_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RFM_SysStartTime] DEFAULT SYSUTCDATETIME(),
   [RFM_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RFM_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
   PERIOD FOR SYSTEM_TIME ([RFM_SysStartTime], [RFM_SysEndTime]),
   CONSTRAINT [PK_RefDamage] PRIMARY KEY CLUSTERED ([RFM_PK] ASC),
   CONSTRAINT [CK_RefDamage_RFM_Code] CHECK  ([RFM_Code] <> ''),
   CONSTRAINT [CK_RefDamage_RFM_Description] CHECK  ([RFM_Description] <> ''),
   CONSTRAINT [CK_RefDamage_RFM_Group] CHECK  ([RFM_Group] = 'CEDEX' OR [RFM_Group] = 'MERC')
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefDamageHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefDamage_RFM_Code_RFM_Group] ON [RefDamage] ([RFM_Code] ASC, [RFM_Group] ASC)
GO
ALTER TABLE [RefDamage] SET (LOCK_ESCALATION = DISABLE);
