CREATE TABLE RefLanguageText(
	[RLT_PK] UNIQUEIDENTIFIER NOT NULL,
	[RLT_ParentId] UNIQUEIDENTIFIER NOT NULL,
	[RLT_ParentTableCode] VARCHAR(4) NOT NULL,
	[RLT_Language] VARCHAR(7) NOT NULL,
	[RLT_ColumnName] VARCHAR(50) NOT NULL,
	[RLT_Text] NVARCHAR(1000) NOT NULL,
	[RLT_SysStartTime]  DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RLT_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[RLT_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RLT_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([RLT_SysStartTime], [RLT_SysEndTime]),
	CONSTRAINT [PK_UX__RLT_PK] PRIMARY KEY CLUSTERED ([RLT_PK] ASC),
	CONSTRAINT CK_RefLanguageText_RLT_ParentTableCode CHECK (RLT_ParentTableCode = 'RN' OR RLT_ParentTableCode = 'RW' OR RLT_ParentTableCode = 'RX')
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefLanguageTextHistory))
GO
CREATE NONCLUSTERED INDEX [IX_RefLanguageText_RLT_ParentTableCode_RLT_ParentPK] ON [RefLanguageText]([RLT_ParentTableCode] ASC, [RLT_ParentId] ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX [NR_UC__RLT_ParentTableCode_RLT_ParentPK_RLT_Language_RLT_ColumnName] ON [RefLanguageText] ([RLT_ParentTableCode] ASC, [RLT_ParentId] ASC, [RLT_Language] ASC, [RLT_ColumnName] ASC)
GO
ALTER TABLE [RefLanguageText] SET (LOCK_ESCALATION = DISABLE);
