CREATE TABLE RefLanguageType(
	[ZX6_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefLanguageType_ZX6_PK] DEFAULT(NEWID()),
	[ZX6_Language] VARCHAR(3) NOT NULL CONSTRAINT [DF_RefLanguageType_ZX6_Language] DEFAULT(''),
	[ZX6_Description] NVARCHAR(50) NOT NULL CONSTRAINT [DF_RefLanguageType_ZX6_Description] DEFAULT(''),
	[ZX6_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZX6_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZX6_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZX6_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZX6_SysStartTime], [ZX6_SysEndTime]),
	CONSTRAINT [PK_RefLanguageType] PRIMARY KEY CLUSTERED ([ZX6_PK] ASC),
	CONSTRAINT [CK_ZX6_Language] CHECK (LEN(ZX6_Language)=2 OR LEN(ZX6_Language)=3)
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefLanguageTypeHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefLanguageType_ZX6_Language] ON [RefLanguageType] ([ZX6_Language])
GO
ALTER TABLE RefLanguageType SET (LOCK_ESCALATION = DISABLE);
