CREATE TABLE RefSysConfigType(
	[ZRT_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefSysConfigType_ZRT_PK] DEFAULT (NEWID()),
	[ZRT_ConfigCode] VARCHAR(10) NOT NULL,
	[ZRT_Description] VARCHAR(100) NOT NULL,
	[ZRT_LongDescription] VARCHAR(500) NOT NULL,
	[ZRT_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_ZRT_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[ZRT_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_ZRT_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([ZRT_SysStartTime], [ZRT_SysEndTime]),
	CONSTRAINT [PK_RefSysConfigType] PRIMARY KEY CLUSTERED (ZRT_PK ASC),
	CONSTRAINT Constraint_ZRT_ConfigCode CHECK (ZRT_ConfigCode <> '' AND datalength(ZRT_ConfigCode) >= (3)),
	CONSTRAINT Constraint_ZRT_Description CHECK (ZRT_Description <> ''),
	CONSTRAINT Constraint_ZRT_LongDescription CHECK (ZRT_LongDescription <> '')
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefSysConfigTypeHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefSysConfigType_ZRT_ConfigCode ON RefSysConfigType ([ZRT_ConfigCode] ASC)
GO
ALTER TABLE RefSysConfigType SET (LOCK_ESCALATION = DISABLE);
