CREATE TABLE RefUNLOCOPortMapping (
	[RLM_PK] UNIQUEIDENTIFIER NOT NULL,
	[RLM_RL_NKCode] VARCHAR(5) NOT NULL,
	[RLM_RL_NKCodeRelated] VARCHAR(5) NOT NULL,
	[RLM_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RLM_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[RLM_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RLM_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([RLM_SysStartTime], [RLM_SysEndTime]),
	CONSTRAINT [PK_RefUNLOCOPortMapping] PRIMARY KEY CLUSTERED ([RLM_PK] ASC),
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefUNLOCOPortMappingHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefUNLOCOPortMapping_RLM_RL_NKCode_RLM_RL_NKCodeRelated ON RefUNLOCOPortMapping (RLM_RL_NKCode ASC, RLM_RL_NKCodeRelated ASC)
GO
ALTER TABLE RefUNLOCOPortMapping SET (LOCK_ESCALATION = DISABLE);
