CREATE TABLE [RefUNLOCORelatedPort](
	[RLR_PK] [UNIQUEIDENTIFIER] NOT NULL CONSTRAINT [DF_RefUNLOCORelatedPort_RLR_PK] DEFAULT (NEWID()),
	[RLR_GroupNumber] [SMALLINT] NOT NULL,
	[RLR_RL_NKRelatedPort] [VARCHAR](5) NOT NULL,
	[RLR_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RLR_SysStartTime] DEFAULT SYSUTCDATETIME(),
	[RLR_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RLR_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([RLR_SysStartTime], [RLR_SysEndTime]),
	CONSTRAINT [PK_RefUNLOCORelatedPort] PRIMARY KEY NONCLUSTERED ([RLR_PK]),
	CONSTRAINT RefUNLOCORelatedPort_RLR_RL_NKRelatedPort CHECK  ((LEN([RLR_RL_NKRelatedPort])=(5))),
	CONSTRAINT [FK_RefUNLOCORelatedPort_RefUNLOCO] FOREIGN KEY ([RLR_RL_NKRelatedPort]) REFERENCES [RefUNLOCO] ([RL_Code]),
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefUNLOCORelatedPortHistory))
GO
CREATE UNIQUE CLUSTERED INDEX [IX_RefUNLOCORelatedPort_RLR_GroupNumber_RLR_RL_NKRelatedPort] ON [RefUNLOCORelatedPort] ([RLR_GroupNumber] ASC, [RLR_RL_NKRelatedPort] ASC)
GO
CREATE NONCLUSTERED INDEX [IX_RefUNLOCORelatedPort_RLR_RL_NKRelatedPort] ON [RefUNLOCORelatedPort] ([RLR_RL_NKRelatedPort] ASC)
GO
ALTER TABLE [RefUNLOCORelatedPort] SET (LOCK_ESCALATION = DISABLE);
