CREATE TABLE RefUNLOCOUtcOffset(
	[RLO_PK] UNIQUEIDENTIFIER NOT NULL,
	[RLO_RL_NKCode] VARCHAR(5) NOT NULL CONSTRAINT [DF_RefUNLOCOUtcOffset_RLO_RL_NKCode]  DEFAULT (''),
	[RLO_StartTimeUtc] SMALLDATETIME NOT NULL,
	[RLO_EndTimeUtc] SMALLDATETIME NOT NULL,
	[RLO_OffsetMinutesFromUtc] SMALLINT NOT NULL CONSTRAINT [DF_RefUNLOCOUtcOffset_RLO_OffsetMinutesFromUtc]  DEFAULT ((0)),
	[RLO_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RLO_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[RLO_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RLO_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([RLO_SysStartTime], [RLO_SysEndTime]),
	CONSTRAINT [PK_RefUNLOCOUtcOffset] PRIMARY KEY CLUSTERED ( [RLO_PK] ASC ),
	CONSTRAINT [RefUNLOCOUtcOffset_RLO_EndTimeUtc] CHECK  (([RLO_EndTimeUtc]>[RLO_StartTimeUtc])),
	CONSTRAINT [RefUNLOCOUtcOffset_RLO_RL_NKCode] CHECK  ((LEN([RLO_RL_NKCode])=(5))),
	CONSTRAINT [FK_RefUNLOCOUtcOffset_RefUNLOCO] FOREIGN KEY([RLO_RL_NKCode]) REFERENCES RefUNLOCO ([RL_Code])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefUNLOCOUtcOffsetHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_RefUNLOCOUtcOffset_RLO_RL_NKCode_RLO_StartTimeUtc ON RefUNLOCOUtcOffset (RLO_RL_NKCode ASC,RLO_StartTimeUtc ASC)
GO
ALTER TABLE RefUNLOCOUtcOffset SET (LOCK_ESCALATION = DISABLE);
