CREATE TABLE [RefUnitSection] (
   [RUS_PK] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_RefUnitSection_RUS_PK] DEFAULT (NEWID()),
   [RUS_Code] VARCHAR(10) NOT NULL CONSTRAINT [DF_RefUnitSection_RUS_Code] DEFAULT (''),
   [RUS_Description] VARCHAR(50) NOT NULL CONSTRAINT [DF_RefUnitSection_RUS_Description] DEFAULT (''),
   [RUS_Group] VARCHAR(10) NOT NULL CONSTRAINT [DF_RefUnitSection_RUS_Group] DEFAULT (''),
   [RUS_SysStartTime] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RUS_SysStartTime] DEFAULT SYSUTCDATETIME(),
   [RUS_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RUS_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME ([RUS_SysStartTime], [RUS_SysEndTime]),
    CONSTRAINT [PK_RefUnitSection] PRIMARY KEY CLUSTERED ([RUS_PK] ASC),
    CONSTRAINT [CK_RefUnitSection_RUS_Code] CHECK  ([RUS_Code] <> ''),
    CONSTRAINT [CK_RefUnitSection_RUS_Description] CHECK  ([RUS_Description] <> ''),
    CONSTRAINT [CK_RefUnitSection_RUS_Group] CHECK  ([RUS_Group] = 'CEDEX' OR [RUS_Group] = 'MERC')
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.RefUnitSectionHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RefUnitSection_RUS_Code_RUS_Group] ON [RefUnitSection] ([RUS_Code] ASC, [RUS_Group] ASC)
GO
ALTER TABLE RefUnitSection SET (LOCK_ESCALATION = DISABLE);
