CREATE TABLE [dbo].[UNDGSubstanceRID]
(
	[RID_PK] UNIQUEIDENTIFIER NOT NULL,
	[RID_IsActive] BIT NOT NULL CONSTRAINT [DF_RID_IsActive] DEFAULT 1,
	[RID_UNNO] VARCHAR(4) NOT NULL CONSTRAINT [DF_RID_UNNO] DEFAULT '',
	[RID_Variant] VARCHAR(2) NOT NULL CONSTRAINT [DF_RID_Variant] DEFAULT '',
	[RID_PSN] VARCHAR(200) NOT NULL CONSTRAINT [DF_RID_PSN] DEFAULT '',
	[RID_Class] VARCHAR(4) NOT NULL CONSTRAINT [DF_RID_Class] DEFAULT '',
	[RID_ClassificationCode] VARCHAR(20) NOT NULL CONSTRAINT [DF_RID_ClassificationCode] DEFAULT '',
	[RID_PG] VARCHAR(3) NOT NULL CONSTRAINT [DF_RID_PG] DEFAULT '',
	[RID_Labels] VARCHAR(20) NOT NULL CONSTRAINT [DF_RID_Labels] DEFAULT '',
	[RID_SpecialProvisions] VARCHAR(46) NOT NULL CONSTRAINT [DF_RID_SpecialProvisions] DEFAULT '',
	[RID_LQMaxAmt] DECIMAL(9,3) NOT NULL CONSTRAINT [DF_RID_LQMaxAmt] DEFAULT 0,
	[RID_LQMaxAmtUQ] VARCHAR(2) NOT NULL CONSTRAINT [DF_RID_LQMaxAmtUQ] DEFAULT '',
	[RID_LQ2MaxAmt] DECIMAL(9,3) NOT NULl CONSTRAINT [DF_RID_LQ2MaxAmt] DEFAULT 0,
	[RID_LQ2MaxAmtUQ] VARCHAR(2) NOT NULL CONSTRAINT [DF_RID_LQ2MaxAmtUQ] DEFAULT '',
	[RID_ExceptedQuantityCode] VARCHAR(2) NOT NULL CONSTRAINT [DF_RID_ExceptedQuantityCode] DEFAULT '',
	[RID_PackIns] VARCHAR(50) NOT NULL CONSTRAINT [DF_RID_PackIns] DEFAULT '',
	[RID_IBCIns] VARCHAR(46) NOT NULL CONSTRAINT [DF_RID_IBCIns] DEFAULT '',
	[RID_PackProv] VARCHAR(48) NOT NULL CONSTRAINT [DF_RID_PackProv] DEFAULT '',
	[RID_MixedPackProv] VARCHAR(18) NOT NULL CONSTRAINT [DF_RID_MixedPackProv] DEFAULT '',
	[RID_BulkContainerTankIns] VARCHAR(20) NOT NULL CONSTRAINT [DF_RID_BulkContainerTankIns] DEFAULT '',
	[RID_BulkContainerTankProv] VARCHAR(34) NOT NULL CONSTRAINT [DF_RID_BulkContainerTankProv] DEFAULT '',
	[RID_TankCode] VARCHAR(35) NOT NULL CONSTRAINT [DF_RID_TankCode] DEFAULT '',
	[RID_TankSpecProv] VARCHAR(60) NOT NULL CONSTRAINT [DF_RID_TankSpecProv] DEFAULT '',
	[RID_TransportCategory] VARCHAR(2) NOT NULL CONSTRAINT [DF_RID_TransportCategory] DEFAULT '',
	[RID_CarriagePackagesSpecialProv] VARCHAR(18) NOT NULL CONSTRAINT [DF_RID_CarriagePackagesSpecialProv] DEFAULT '',
	[RID_CarriageBulkSpecialProv] VARCHAR(38) NOT NULL CONSTRAINT [DF_RID_CarriageBulkSpecialProv] DEFAULT '',
	[RID_CarriageLoadingSpecialProv] VARCHAR(40) NOT NULL CONSTRAINT [DF_RID_CarriageLoadingSpecialProv] DEFAULT '',
	[RID_ColisExpressCode] VARCHAR(36) NOT NULL CONSTRAINT [DF_RID_ColisExpressCode] DEFAULT '',
	[RID_HazardIDNumber] VARCHAR(8) NOT NULL CONSTRAINT [DF_RID_HazardIDNumber] DEFAULT '',
	[RID_SysStartTime]  DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL CONSTRAINT [DF_RID_SysStartTime] DEFAULT CONVERT(DATETIME2, '1900-01-01 0:0:0.0000000'),
	[RID_SysEndTime] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL CONSTRAINT [DF_RID_SysEndTime] DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
	PERIOD FOR SYSTEM_TIME ([RID_SysStartTime], [RID_SysEndTime]),
	CONSTRAINT [PK_UNDGSubstanceRID] PRIMARY KEY CLUSTERED  ([RID_PK] ASC),
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.UNDGSubstanceRIDHistory))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_UNDGSubstanceRID_UNNO_RID_Variant] ON [UNDGSubstanceRID] ([RID_UNNO] ASC,[RID_Variant] ASC)
GO
ALTER TABLE UNDGSubstanceRID SET (LOCK_ESCALATION = DISABLE);
