<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:rsm="iata:housemanifest:1"
    xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2"
    xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:8"
    xmlns:ram="iata:datamodel:3"
    targetNamespace="iata:housemanifest:1"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified"
    version="2.0">
  <xsd:import namespace="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:8" schemaLocation="standard/UnqualifiedDataType_8p0.xsd"/>
  <xsd:import namespace="iata:datamodel:3" schemaLocation="ReusableAggregateBusinessInformationEntity_3.xsd"/>
  <xsd:element name="HouseManifest" type="rsm:HouseManifestType"/>
  <xsd:complexType name="HouseManifestType">
    <xsd:sequence>
      <xsd:element name="MessageHeaderDocument" type="ram:MessageHeaderDocumentType"/>
      <xsd:element name="BusinessHeaderDocument" type="ram:BusinessHeaderDocumentType"/>
      <xsd:element name="MasterConsignment" type="ram:MasterConsignmentType" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
