<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.CHReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.CHReferenceData.Business</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <Configurations>Debug;Release;UAT</Configurations>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeLists\Schema\PassarCodelists_v1.cs">
      <DependentUpon>PassarCodelists_v1.xsd</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\Schema\edecDomainSchema_v_1_0.cs">
      <DependentUpon>edecDomainSchema_v_1_0.xsd</DependentUpon>
    </Compile>
    <Compile Update="CodeLists\Schema\edec_permit_item_details_schema_v_1_0.cs">
      <DependentUpon>edec_permit_item_details_schema_v_1_0.xsd</DependentUpon>
    </Compile>
    <Compile Update="CustomsOffices\edec_customs_office_schema.cs">
      <DependentUpon>edec_customs_office_schema.xsd</DependentUpon>
    </Compile>
    <Compile Update="ExchangeRates\dailyrates.cs">
      <DependentUpon>dailyrates.xsd</DependentUpon>
    </Compile>
    <Compile Update="Tariffs\edecTariffMasterDataSchema_v_1_0.cs">
      <DependentUpon>edecTariffMasterDataSchema_v_1_0.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <ProjectReference Include="..\CHReferenceData.Services\CHReferenceData.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeLists\Schema\edecDomainSchema_v_1_0.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="CodeLists\Schema\edec_permit_item_details_schema_v_1_0.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="CodeLists\Schema\PassarCodelists_v1.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="ExchangeRates\dailyrates.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="Tariffs\edecTariffMasterDataSchema_v_1_0.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="TradeGroups\edec_country_code_schema_v.1.0.xsd">
      <SubType>Designer</SubType>
    </None>
    <None Update="CustomsOffices\edec_customs_office_schema.xsd">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>