<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>CargoWise.Macros.Testing</RootNamespace>
    <AssemblyName>CargoWise.Macros.Testing</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Macros"/>
    <Reference Include="CargoWise.Types"/>
    <Reference Include="NUnitCore"/>
  </ItemGroup>
</Project>