<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.ASYCUDAManifest.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.Customs.ASYCUDAManifest.GUI.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Gui.Test\ASYCUDA.GUI.Test.Winzor.csproj" />
    <ProjectReference Include="..\..\Gui\ASYCUDA.GUI.Winzor.csproj" />
    <ProjectReference Include="..\GUI\ASYCUDAManifest.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.Customs.ASYCUDA.Business.Test" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>