//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from YesNoList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class YesNoList : UntranslatableCodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string No = "N";
			public const string Yes = "Y";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string No = "No";
			public const string Yes = "Yes";
		}

		public YesNoList() : base("Common Yes No List")
		{
			AddPair(Codes.No, Descriptions.No);
			AddPair(Codes.Yes, Descriptions.Yes);
		}
	}
}
