<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
      <_DeploymentPropsImported>True</_DeploymentPropsImported>
      <Server Condition="'$(Server)'==''">SYDSP-SBTS-X.sand.wtg.zone</Server>
      <UserId Condition="'$(UserId)'==''">DevAdmin</UserId>
      <Password Condition="'$(Password)'==''">3hubRock$</Password>
      <ConnectionString>Data Source=localhost;Initial Catalog=eHubTransactions;Integrated Security=True;Connect Timeout=120</ConnectionString>
    </PropertyGroup>
</Project>