<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.DE.NCTS.GUI.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.Messaging.Integration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.DE.NCTS.GUI.csproj" />
  </ItemGroup>
</Project>