<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.EquipmentManagement.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.EquipmentManagement.Module.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.EquipmentManagement.Business" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module\Enterprise.EquipmentManagement.Module.Winzor.csproj" />
  </ItemGroup>
</Project>
