<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Compile Update="BusinessObject\Area\AreaTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AreaTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="BusinessObject\Area\AutoArea.cs">
      <DependentUpon>AutoArea.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\GroupByColumn\AutoGroupByColumn.cs">
      <DependentUpon>AutoGroupByColumn.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\DataSource\AutoDataSource.cs">
      <DependentUpon>AutoDataSource.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\ColumnHeading\AutoColumnHeading.cs">
      <DependentUpon>AutoColumnHeading.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\ColumnData\AutoColumnData.cs">
      <DependentUpon>AutoColumnData.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\RowData\AutoRowData.cs">
      <DependentUpon>AutoRowData.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\ReportBizObj\AutoReportBizObj.cs">
      <DependentUpon>AutoReportBizObj.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="BusinessObject\MainBizObj\AutoMainBizObj.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AutoMainBizObj.xml</DependentUpon>
    </Compile>
    <EmbeddedResource Include="ReportTemplate.xls" />
  </ItemGroup>
  <ItemGroup>
    <None Update="BusinessObject\Area\AreaTypeList.xml">
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AreaTypeList.cs</LastGenOutput>
    </None>
    <None Update="BusinessObject\Area\AutoArea.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoArea.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\GroupByColumn\AutoGroupByColumn.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoGroupByColumn.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\DataSource\AutoDataSource.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoDataSource.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\ColumnHeading\AutoColumnHeading.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoColumnHeading.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\ColumnData\AutoColumnData.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoColumnData.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\RowData\AutoRowData.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoRowData.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\ReportBizObj\AutoReportBizObj.xml">
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoReportBizObj.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
    </None>
    <None Update="BusinessObject\MainBizObj\AutoMainBizObj.xml">
      <CustomToolNamespace>Enterprise.ReportWriter</CustomToolNamespace>
      <Generator>NonPersistentBusinessObjectGenerator</Generator>
      <LastGenOutput>AutoMainBizObj.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>