<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DbUpgrader.ReferenceDatabases</RootNamespace>
    <AssemblyName>Enterprise.DbUpgrader.ReferenceDatabases</AssemblyName>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.ExtendedProperties" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DbUpgrader.Foundation" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.RefDbRepo.Client.Common" />
    <Reference Include="Enterprise.DbUpgrader.Schema.Synchroniser" />
    <Reference Include="Enterprise.DbUpgrader.Shared" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="NUnitCore" Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'" />
    <Reference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="CA\Data\CACCasualImpCommodities.csv" />
    <EmbeddedResource Include="CA\Data\CACCasualImpDummyHS.csv" />
    <EmbeddedResource Include="CA\Data\CACCasualImpRates.csv" />
    <EmbeddedResource Include="CA\Data\CACDocumentTypes.csv" />
    <EmbeddedResource Include="CA\Data\CACClass.csv" />
    <EmbeddedResource Include="US\USCAMSProductResource.csv" />
    <EmbeddedResource Include="US\USCRuleSecondaryTariff.csv" />
    <EmbeddedResource Include="US\USCRuleSecondaryTariffException.csv" />
    <EmbeddedResource Include="US\USCTariffRule.csv" />
    <EmbeddedResource Include="US\USCTariffRuleAMS.csv" />
    <EmbeddedResource Include="US\USCTariffRuleFDA.csv" />
    <EmbeddedResource Include="US\USCTariffRuleTTB.csv" />
    <EmbeddedResource Include="US\USCTariffRuleTTBPrice.csv" />
    <EmbeddedResource Include="US\USCZipCode.csv" />
    <EmbeddedResource Include="US\USCTariffRuleAESExcluded.csv" />
    <EmbeddedResource Include="US\USCTariffRuleCFE.csv" />
    <EmbeddedResource Include="CA\Data\CACPGAHSCode.csv" />
    <EmbeddedResource Include="US\USCSTN9902RuleSecondaryTariff.csv" />
    <EmbeddedResource Include="US\USCSTN9902TariffRule.csv" />
    <EmbeddedResource Include="US\USCRule.csv" />
    <EmbeddedResource Include="US\USCarriersData.csv" />
    <EmbeddedResource Include="AU\CmrFiles\CMRAqisPostCodes.csv" />
    <EmbeddedResource Include="US\USCAESResponseCodeData.csv" />
    <EmbeddedResource Include="CA\Data\CACPlaceOfReport.csv" />
    <EmbeddedResource Include="CA\Data\CACPortOfExit.csv" />
    <EmbeddedResource Include="CA\Data\CACTradeZone.csv" />
    <EmbeddedResource Include="CA\Data\CACUSPortOfExit.csv" />
    <EmbeddedResource Include="CA\Data\CACFIAEndUseCodes.csv" />
    <EmbeddedResource Include="CA\Data\CACFIARegTypes.csv" />
    <EmbeddedResource Include="US\USScheduleBData.txt" />
    <EmbeddedResource Include="CA\Data\CACAcrossErrorCodes.csv" />
    <EmbeddedResource Include="CA\Data\CACAdditionalAcrossErrorCodes.csv" />
    <EmbeddedResource Include="CA\Data\CACCBSAOfficeCodes.csv" />
    <EmbeddedResource Include="CA\Data\CACountryPreferences.csv" />
    <EmbeddedResource Include="CA\View\CACDocumentTypesCombinedView.sql" />
    <EmbeddedResource Include="CA\Data\CACPGAHSCode_GAC.csv" />
    <EmbeddedResource Include="CA\Data\CACTaxRateCodes.csv" />
  </ItemGroup>
</Project>