<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.NewSafeDataUpdateService.Test</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.NewSafeDataUpdateService.Test</AssemblyName>
    <OutputPath>..\..\..\Bin\Server\</OutputPath>
    <Configurations>Debug</Configurations>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.ErrorReporting">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.ErrorReporting.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Infrastructure.Test">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.Infrastructure.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.TypeProvider">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.TypeProvider.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Utils">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.Utils.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.Web">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Common.Web.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Service.Schema_0_9_New">
      <HintPath>..\..\..\Bin\Server\net8.0\CargoWise.RefDbRepo.Service.Schema_0_9_New.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewSafeDataUpdateService\NewSafeDataUpdateService.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ConnectionStrings.SafeUpdateService.Test.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>
