<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.GB.H7.GUI.Test</AssemblyName>
    <RootNamespace>Enterprise.Customs.GB.H7.GUI.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Business\Enterprise.Customs.GB.Business.csproj" />
    <ProjectReference Include="..\..\Core\CDS\Enterprise.Customs.GB.CDS.csproj" />
    <ProjectReference Include="..\..\Core\Chief\Enterprise.Customs.GB.Chief.csproj" />
    <ProjectReference Include="..\..\Core\Registry\Enterprise.Customs.GB.Registry.csproj" />
    <ProjectReference Include="..\H7.Messaging\Enterprise.Customs.GB.H7.Messaging.csproj" />
    <ProjectReference Include="..\H7.GUI\Enterprise.Customs.GB.H7.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>