// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.ShelvesetToolsTest.CreateAspectWithReviewAndData(System.String,System.Guid)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/ShelvesetToolsTest.cs:152,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.ShelvesetToolsTest.UpdateShelfResults(System.Guid,System.String,System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/ShelvesetToolsTest.cs:131,20
[assembly: SuppressMessage("CargoWiseOne", "CW1056:Do Not Use GC.Collect()", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.OrganisationBillTest.TestCreateInvoice_NewFactory")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/OrganisationBill/OrganisationBillTest.cs:251,3
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.KeyAppendStrategyTest.line1")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/KeyAppendStrategyTest.cs:24,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.KeyAppendStrategyTest.line2")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/KeyAppendStrategyTest.cs:25,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.KeyAppendStrategyTest.line4")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/KeyAppendStrategyTest.cs:27,23
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.KeyAppendStrategyTest.line3")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/KeyAppendStrategyTest.cs:26,23
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AsycudaBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ASYCUDA/AsycudaBillingSystemTest.cs:54,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AsycudaBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ASYCUDA/AsycudaBillingSystemTest.cs:128,186
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.IsfBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/ISF/IsfBillingSystemTest.cs:47,184
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.IsfBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/ISF/IsfBillingSystemTest.cs:105,184
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.ExceptionTime")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:823,52
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.ExeCreationTime")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:827,54
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.Calls")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:849,6
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.Calls")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:850,6
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.Calls")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:851,6
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionXmlTest.ValidXml.Values.Calls")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/ExceptionXmlTest.cs:852,6
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.ClientIncidentQuoteTest.TestQuoteSentDatePopulatesOtherDates")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/EstimateAndQuote/ClientIncidentQuoteTest.cs:15,19
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.IncidentAssociationQueryTest.SetUp")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/IncidentAssociationQueryTest.cs:19,9
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.IncidentAssociationQueryTest.MakeIncidentMain(System.DateTime)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/IncidentAssociationQueryTest.cs:47,13
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.IncidentAssociationQueryTest.MakeIncidentSimilarityTfIdf(System.Guid,System.DateTime)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/IncidentAssociationQueryTest.cs:78,13
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IssueManager.Business.Tests.StackLinesWeightsLogAutoAssignerTests.AddPublishedAssembly(System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/StackLinesWeightsLogAutoAssignerTests.cs:1391,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IssueManager.Business.Tests.StackLinesWeightsLogAutoAssignerTests.AddPublishedClass(System.Guid,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/StackLinesWeightsLogAutoAssignerTests.cs:1410,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IssueManager.Business.Tests.StackLinesWeightsLogAutoAssignerTests.AddPublishedMethod(System.Guid,System.String,System.DateTimeOffset)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/StackLinesWeightsLogAutoAssignerTests.cs:1434,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IssueManager.Business.Tests.StackLinesWeightsLogAutoAssignerTests.AddSourceTreeResponsibility(System.String,System.String,System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/HelpErrorLog/HelperClasses/StackLinesWeightsLogAutoAssignerTests.cs:1455,25
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.FlightStatsBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/FlightStats/FlightStatsBillingSystemTest.cs:55,206
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.FlightStatsBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/FlightStats/FlightStatsBillingSystemTest.cs:123,205
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.CrikeyDataAccessTests.AddUserTestHeader(CargoWise.Data.DbConnection,System.String,System.Guid,System.String,System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/CrikeyDataAccessTests.cs:753,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.CrikeyDataAccessTests.AddUserTest(CargoWise.Data.DbConnection,System.Guid,System.String,System.String,System.Guid,System.String,System.String,System.Nullable{System.Int32},System.String,System.String,System.Nullable{System.Guid},System.Nullable{System.Guid})")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/CrikeyDataAccessTests.cs:786,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.LicenceKeyBuilder.Business.Test.PackagePublishServiceTest.TestLastErrorMessage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Upgrades/PackageSenders/PackagePublishServiceTest.cs:362,21
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.MetaSupportIncidentProviderTest.SetUp")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Business/MetaSupportIncidentProviderTest.cs:19,9
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.BatchProcessor.Testing.SupportRequestProcessorTest.DummySupportRequestProcessorWithConcurrencyException.SaveIncident(CargoWise.EntityFramework.BusinessObjectFactory)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/SupportRequestProcessorTest.cs:992,32
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.E2EBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/E2E/E2EBillingSystemTest.cs:71,186
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.E2EBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/E2E/E2EBillingSystemTest.cs:126,186
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.SupportIncidentTest.TestCalculateWorkflowDependentPropertiesDoesNotAffectUnchangedIncidents")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/SupportIncidentTest.cs:9305,30
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.SupportIncidentTest.TestIM_ProgramAreaIndex_ShouldUseIndex")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/SupportIncidentTest.cs:10008,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.SupportIncidentTest.TestIM_ProgramAreaIndex_ShouldNotUseIndex")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/SupportIncidentTest.cs:10034,24
[assembly: SuppressMessage("CargoWiseOne", "CW1109:Do Not Use System.Windows.Forms. Form Or KForm Class", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.LicenceKeyBuilder.Business.Test.LicenceDatabaseTest.TestReadOnlySecurity_InnerObjects")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/LicenceDatabase/LicenceDatabaseTest.cs:1092,22
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Registry.Business.Test.TestRigRegistryOptionsValidationTest.TestBackupFile")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Registry/TestRigs/TestRigRegistryOptionsValidationTest.cs:63,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Modules.Testing.NumberFountainsTest.SetUp")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ClientConfiguration/NumberFountainsTest.cs:60,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Modules.Testing.NumberFountainsTest.TearDown")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ClientConfiguration/NumberFountainsTest.cs:66,3
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.MetaIncidentSimilarityTfIdfProviderTest.SetUp")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Business/MetaIncidentSimilarityTfIdfProviderTest.cs:15,9
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Hosting.Test.HostingDataAccessBillingSystemTest.CreateRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Hosting/HostingDataAccessBillingSystemTest.cs:213,220
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.WorkItemProcessTaskTest.GetShelfPk(Enterprise.Client.EDI.IncidentManager.Business.WorkItemProcessTask)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/ProcessTasks/WorkItemProcessTaskTest.cs:735,25
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.WorkItemProcessTaskTest.LoadShelvesByProcessTaskAndShelfName(Enterprise.Client.EDI.IncidentManager.Business.WorkItemProcessTask,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/ProcessTasks/WorkItemProcessTaskTest.cs:1179,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.WorkItemProcessTaskTest.TestWorkItemNumberPropagatedToUserTestHeader")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/ProcessTasks/WorkItemProcessTaskTest.cs:2239,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.WorkItemProcessTaskTest.RenameStoredProcedure(System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/ProcessTasks/WorkItemProcessTaskTest.cs:2281,25
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:326,11
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:353,0
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:354,0
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:355,0
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:356,0
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~P:Enterprise.Client.EDI.Licencing.Business.Test.EDIVersionReportTest.XmlForTestingFormat_2015_04")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/Legacy/EDIVersionReportTest.cs:393,0
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.BillingTestHelper.SetDepositBalance(System.Guid,System.String,System.Decimal,System.Decimal,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Testing/BillingTestHelper.cs:1119,20
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.LicenceKeyBuilder.Business.Test.LicenceDatabaseRegistrationImporterTest.TestImportLicenceDatabase_TenantRegistrationInfo")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Licencing/LicenceDatabase/Import/LicenceDatabaseRegistrationImporterTest.cs:218,18
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.GBCustomsBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/GBCustoms/GBCustomsBillingSystemTest.cs:87,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.GBCustomsBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/GBCustoms/GBCustomsBillingSystemTest.cs:172,186
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilarities")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:138,53
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilarities")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:139,62
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilarities")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:142,43
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilarities")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:143,41
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesMinimumSimilarity")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:155,53
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesMinimumSimilarity")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:156,62
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesMinimumSimilarity")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:160,43
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesMinimumSimilarity")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:161,41
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesNoSource")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:176,53
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesNoSource")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:177,96
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesNoSource")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:180,43
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentRepositoryTest.TestSearchStoredIncidentSimilaritiesNoSource")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentRepositoryTest.cs:181,41
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.PortMessagingBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/PortMessaging/PortMessagingBillingSystemTest.cs:57,188
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.OceanTracingLegacyBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/OceanTracing/OceanTracingLegacyBillingSystemTest.cs:60,185
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.OceanTracingLegacyBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/OceanTracing/OceanTracingLegacyBillingSystemTest.cs:117,185
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~F:Enterprise.Client.EDI.IssueManager.Business.Test.ExceptionReportRendererTest.testXmlWithCorruptDllVersionSection")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IssueManager/ExceptionReportRendererTest.cs:617,53
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestSchedule")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:59,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestSchedule")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:79,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestRemoveFromSchedule")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:125,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestRemoveFromSchedule")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:139,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestHasBeenBuilt")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:155,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestHasBeenBuilt")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:171,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestUpdateStatus")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:188,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestUpdateStatus")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:203,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.GetFirstSumittedDate(CargoWise.Data.DbConnection,System.Guid)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:210,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.GetPriority(CargoWise.Data.DbConnection,System.Guid)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:219,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.SetPriority(CargoWise.Data.DbConnection,System.Guid,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:228,24
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:286,92
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:303,79
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:321,4
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:341,4
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:359,75
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:377,4
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:399,75
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.EDIShelvesetInfoTest.TestOptions_ShouldUseDetailsFromRegistryAsFallback")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/Workflow/EDIShelvesetInfoTest.cs:410,4
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ShippingPortMessagingBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ShippingPortMessaging/ShippingPortMessagingBillingSystemTest.cs:55,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ShippingPortMessagingBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ShippingPortMessaging/ShippingPortMessagingBillingSystemTest.cs:140,186
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.OceanTracingBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/OceanTracing/OceanTracingBillingSystemTest.cs:48,185
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.OceanTracingBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/OceanTracing/OceanTracingBillingSystemTest.cs:119,185
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.JapanAFRBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/JapanAFR/JapanAFRBillingSystemTest.cs:47,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.JapanAFRBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/JapanAFR/JapanAFRBillingSystemTest.cs:102,187
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.EServicesBillingTestHelper.InsertClientMappingInterface(System.String,System.DateTime)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/EServicesBillingSystemTestHelper.cs:284,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.EServicesBillingTestHelper.DoSql(System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/EServicesBillingSystemTestHelper.cs:344,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.EServicesBillingTestHelper.InsertTransaction(Enterprise.Client.EDI.Billing.Test.EServicesBillingTestHelper.RawUsageInfo)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/EServicesBillingSystemTestHelper.cs:336,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ABMCustomsDataImporterTest.TestImportAndSave")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ABMCustoms/ABMCustomsDataImporterTest.cs:160,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ABMCustomsDataImporterTest.TestImportAndSave")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ABMCustoms/ABMCustomsDataImporterTest.cs:165,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ABMCustomsDataImporterTest.TestImportAndSave")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ABMCustoms/ABMCustomsDataImporterTest.cs:171,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ABMCustomsDataImporterTest.TestImportAndSave")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ABMCustoms/ABMCustomsDataImporterTest.cs:177,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ABMCustomsDataImporterTest.TestImportAndSave")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ABMCustoms/ABMCustomsDataImporterTest.cs:183,24
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.ClientIncidentEstimateTest.TestEstimateSentDatePopulatesOtherDates")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/EstimateAndQuote/ClientIncidentEstimateTest.cs:15,19
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.DepositBalanceCollectionTest.TestLoad")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/EdiDepositAdjust/DepositBalanceCollectionTest.cs:36,20
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.USCustomsBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/USCustoms/USCustomsBillingSystemTest.cs:71,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.USCustomsBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/USCustoms/USCustomsBillingSystemTest.cs:174,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AirlineMessagingBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/AirlineMessaging/AirlineMessagingBillingSystemTest.cs:71,230
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AirlineMessagingBillingSystemTest.TestLoadOdplRawUsagePre201808")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/AirlineMessaging/AirlineMessagingBillingSystemTest.cs:170,230
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AirlineMessagingBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/AirlineMessaging/AirlineMessagingBillingSystemTest.cs:286,230
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.AirlineMessagingBillingSystemTest.TestLoadStlRawUsagePre201808")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/AirlineMessaging/AirlineMessagingBillingSystemTest.cs:388,230
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWhenLastBuildIsSupersededButCutOffBuildIsFine")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:81,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWhenNoActiveBuildsAreBeforeCutOffDateAndTwoBuildsAreAfter")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:130,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWithOneActiveBuildBeforeCutOffDateAndLastBuildIsActive")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:158,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWhenOnlyOneLastBuildIsActive")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:103,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWithWeeklyCutOffBuildsDisabled")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:214,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestCorrectSupersessionIrrespectiveOfImportOrder")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:277,17
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWithTwoActiveBuildsBeforeCutOffDate")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:186,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.TestImportPackageWhenFirstInRing")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:350,39
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.AutoDeploy.Test.PackageImporterTest.PrepareBuildsForImportPackageTest(System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.Boolean,System.String,System.DateTime@)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/AutoDeploy/PackageImporterTest.cs:386,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Registry.Business.Test.AYCTriggerTypeRegistryItemTest.TestUpdateRegistry")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Registry/AYCTriggerType/AYCTriggerTypeRegistryItemTest.cs:39,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.TestAmnestyClosureOnlySetsExpiredWhenNotAlreadySet")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1080,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.GetAmnestyExpiry(CargoWise.Data.DbConnection,System.Guid)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1122,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.TestAmnestyClosure")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1029,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.TestCancelPreApprovedWorkItemsOnAspectsWhenWorkItemClosedOrCancelled")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1151,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.TestCancelPreApprovedWorkItemsOnAspectsWithMultpleApprovals")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1222,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.TestCancelPreApprovedWorkItemsOnAspectsOnlySetsInactiveWhenNotAlreadySet")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1275,21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.Test.NewWorkItemTest.GetAP_DateInactive(CargoWise.Data.DbConnection,System.Guid)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/WorkItem/NewWorkItemTest.cs:1312,20
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.NZCustomsBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/NZCustoms/NZCustomsBillingSystemTest.cs:66,188
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.NZCustomsBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/NZCustoms/NZCustomsBillingSystemTest.cs:145,188
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ZACustomsBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ZACustoms/ZACustomsBillingSystemTest.cs:91,187
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ZACustomsBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ZACustoms/ZACustomsBillingSystemTest.cs:170,186
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentSearchOptionsTest.TestRestrictionModeNoneToUtcNow")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentSearchOptionsTest.cs:30,13
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentSearchOptionsTest.TestRestrictionModeDateFrom")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentSearchOptionsTest.cs:61,15
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.IncidentManager.Business.IncidentAssociation.Test.SimilarIncidentSearchOptionsTest.TestRestrictionModeDateTo")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/IncidentManager/SupportIncident/IncidentAssociation/Model/SimilarIncidentSearchOptionsTest.cs:78,13
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.GlobalContainerTrackingBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/GlobalContainerTracking/GlobalContainerTrackingBillingSystemTest.cs:155,185
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Hosting.Test.HostingRemoteDevicesBillingSystemTest.CreateTable")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Hosting/HostingRemoteDevicesBillingSystemTest.cs:358,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Hosting.Test.HostingRemoteDevicesBillingSystemTest.DropTable")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Hosting/HostingRemoteDevicesBillingSystemTest.cs:369,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Hosting.Test.HostingRemoteDevicesBillingSystemTest.InsertTransaction(System.String,System.String,CargoWise.Types.ZGuid,CargoWise.Types.ZGuid,CargoWise.Types.ZDate,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Hosting/HostingRemoteDevicesBillingSystemTest.cs:387,24
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ForwardAirBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ForwardAir/ForwardAirBillingSystemTest.cs:71,186
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.ForwardAirBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/eServices/ForwardAir/ForwardAirBillingSystemTest.cs:132,186
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.AddUserTest(System.Guid,System.Guid,System.String,System.String,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:409,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.AddDeploymentJob(System.Guid,System.String)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:443,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.AddBuildJobResult(System.Guid,System.String,System.Version,System.Nullable{CargoWise.Types.ZDateTime})")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:424,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.TestIsCargoWiseOneChange")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:313,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.AddUserTestHeader(System.Guid,System.String,System.Nullable{System.Guid},System.Nullable{System.Guid},System.String,System.Nullable{CargoWise.Types.ZDateTime})")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:393,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.ReleaseBuilds.Test.ReleaseBuildContentTestBase.SetUp")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/ReleaseBuilds/ReleaseBuildContentTestDev.cs:463,24
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.S8CargoBillingSystemTest.TestLoadOdplRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/S8Cargo/S8CargoBillingSystemTest.cs:25,194
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Test.S8CargoBillingSystemTest.TestLoadStlRawUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/S8Cargo/S8CargoBillingSystemTest.cs:82,194
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.StlCombinedUsageReportQueueTest.TestGenerateReport")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Reporting/StlCombinedUsageReportQueueBusinessObjectTestTest.cs:66,186
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.StlCombinedUsageReportQueueTest.TestGenerateReport_GenericUsage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Reporting/StlCombinedUsageReportQueueBusinessObjectTestTest.cs:145,186
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Hosting.Test.HostingStorageBillingSystemTestHelper.SetupHostingStorage")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/Hosting/HostingStorageBillingSystemTest.cs:379,20
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.StlBillingTest.LoadStlUsageLinesForTest(Enterprise.Client.EDI.LicenceKeyBuilder.Business.LicenceCompany,CargoWise.Types.ZDateTime)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/STL/StlBillingTest.cs:6973,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Billing.Business.Test.StlBillingTest.LoadOdplUsageLinesForTest(Enterprise.ZArchitecture.Core.CodeDescriptionPairList,Enterprise.MasterFiles.Business.OrgHeader,CargoWise.Types.ZDateTime)")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Billing/STL/StlBillingTest.cs:7010,24
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Mail.Business.Test.BusinessObjectEmailProcessorTestCase`2.TestCreateAndProcessBusinessObjectEmail_ExistingBusinessObjectNotFound")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Mail/BatchProcessor/BusinessObjectEmailProcessorTestCase.cs:61,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Client.EDI.Mail.Business.Test.BusinessObjectEmailProcessorTestCase`2.TestCreateAndProcessBusinessObjectEmail_ExistingBusinessObjectNotFound")] // Enterprise/ClientExtensions/EDI/ZClientEDI/ZClientEDI.Business.Test/Mail/BatchProcessor/BusinessObjectEmailProcessorTestCase.cs:71,4
