<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.BRReferenceData.Business</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.BRReferenceData.Business</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXmlProducers\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug;Release;UAT</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.Common.Argument">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.Argument.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.RefDbRepo.Common.UniversalXmlWriter">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.Common.UniversalXmlWriter.dll</HintPath>
    </Reference>
    <Reference Include="FlexCel">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\FlexCel.dll</HintPath>
    </Reference>
    <Reference Include="WTG.StaticAnalysis.Annotation">
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\WTG.StaticAnalysis.Annotation.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BRReferenceData.Services\BRReferenceData.Services.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>