<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Registry.GUI</AssemblyName>
    <RootNamespace>Enterprise.Registry.GUI</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Design" />
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreWindowsTargetFramework)' == 'true'">
    <Reference Include="System.Drawing.Common" />
    <Reference Include="System.Windows.Forms.Design" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RegistryItemEditors\DocBuilderTheme\DocBuilderThemePreviewHotSpots.png">
      <CustomToolNamespace>Enterprise.Registry.GUI</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Winzor\GlobalSupressions.cs" />
    <EmbeddedResource Remove="RegistryItemEditors\InboundMessageNotifications\InboundMessageNotificationsControl.resx" />
    <EmbeddedResource Remove="RegistryItemEditors\ShipmentInspection\SupplyChainSecurityOrganisationToUseControl.resx" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Form\RegistryItemChangeLogFilter\SelectChangeLogFilterDatesForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="RegistryItemEditors\BoleroEBLForOrganisationIntegration\BoleroEBLForOrganisationConfigurationControl.cs" />
    <Compile Update="RegistryItemEditors\DeniedPartyScreening\AddressMatchingLevel\AddressMatchingLevelControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="RegistryItemEditors\HVLVDeniedPartyScreening\HVLVDeniedPartyScreeningRegistryControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="RegistryItemEditors\Scim\ScimApiTokenAuthentication\ScimApiTokenAuthenticationControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>