<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ZClientYAS.Test</AssemblyName>
    <RootNamespace>Enterprise.Client.YAS.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZClientYAS\ZClientYAS.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.DataTransfer" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.LogWalker" />
    <Reference Include="Enterprise.LogWalker.Test" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.ServiceManager.Business" />
    <Reference Include="Enterprise.ServiceManager.Shared" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>