<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <Import Project="..\nuget-deploy.target" />

  <ItemGroup>
    <None Remove="Hawking.UnitTest.Tools.csproj.vspscc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hawking.Xslt.Compiler" Version="1.0.0" />
    <PackageReference Include="XmlDiffPatch.Core" Version="1.0.1" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.targets" />
</Project>
