// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderTestCase.TestOnSavingSetAMA_JobReferenceWithoutConsol_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderTestCase.cs:21,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderTestCase.TestOnSavingSetAMA_JobReferenceWithoutConsol_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderTestCase.cs:28,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderTestCase.TestOnSavingSetAMA_JobReferenceWithConsol_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderTestCase.cs:59,4
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderTestCase.TestOnSavingSetAMA_JobReferenceWithConsol_NoDuplicateReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderTestCase.cs:65,4
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaArrivalLineTest.GetNewBusinessObjectForDeleteTest(CargoWise.EntityFramework.BusinessObjectFactory)")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaArrivalLine/AsycudaArrivalLineTest.cs:103,43
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderBaseOnlyTest.TestSavingSetsJobReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderBaseOnlyTest.cs:1926,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaManifestHeaderBaseOnlyTest.TestSavingSetsJobReference")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaManifestHeader/AsycudaManifestHeaderBaseOnlyTest.cs:1962,4
[assembly: SuppressMessage("CargoWiseOne", "CW1062:Do not use System.DateTime.Today Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.ASYCUDA.Business.Testing.AsycudaArrivalHeaderTest.GetNewBusinessObjectForDeleteTest(CargoWise.EntityFramework.BusinessObjectFactory)")] // Enterprise/Product/Operations/Customs/ASYCUDA/Business.Test/BusinessObjects/AsycudaArrivalHeader/AsycudaArrivalHeaderTest.cs:139,43
