namespace Enterprise.Customs.US.Messaging.Business.MessageBuildingBlocks.Input
{
	using CargoWise.Types;

	[Resources.AutoGeneratedSourceCode]
	[InputBlock("CC1")]
	public partial class AIICC1 : MessageBlock
	{
		public AIICC1()
			: base("CC1")
		{
		}

		/// <summary>
		/// Free-form description of Shipping Symbol. For example, initials “Z.K.M.” inside Diamond.
		/// </summary>
		[MessageBlockString(70, 4, "M")]
		public ZString ShippingSymbolDescription;
	}
}
