CREATE TABLE  StmNums
( 
     SN_ID INT IDENTITY(1, 1) NOT NULL,
     SN_Name VARCHAR(35) NOT NULL DEFAULT '',
     SN_Value INT NOT NULL DEFAULT 0,
     SN_Owner UNIQUEIDENTIFIER NOT NULL DEFAULT 0x,
)
ALTER TABLE  StmNums
ADD CONSTRAINT PK_UX__SN_ID PRIMARY KEY NONCLUSTERED  (SN_ID)
;

CREATE UNIQUE CLUSTERED INDEX NR_UC__SN_Name_SN_Owner ON StmNums (SN_Name,SN_Owner)
;

CREATE TABLE  StmNumberCache
( 
     SG_Value INT NOT NULL DEFAULT 0,
     SG_SN UNIQUEIDENTIFIER NOT NULL
)

CREATE UNIQUE CLUSTERED INDEX NR_UC__SG_SN_SG_Value ON StmNumberCache (SG_SN,SG_Value)
;

CREATE TABLE  StmData
( 
     SD_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SD_Name VARCHAR(300) NOT NULL DEFAULT '',
     SD_Owner UNIQUEIDENTIFIER NULL,
     SD_DepartmentGuid UNIQUEIDENTIFIER NULL,
     SD_Type CHAR(3) NOT NULL DEFAULT '',
     SD_IsLogged CHAR(1) NOT NULL DEFAULT 'N',
     SD_BinaryValue VARBINARY(max) NULL,
     SD_GuidValue UNIQUEIDENTIFIER NULL,
     SD_IsCancelled CHAR(1) NOT NULL DEFAULT 'N'
)
ALTER TABLE  StmData
ADD CONSTRAINT PK_UX__SD_PK PRIMARY KEY NONCLUSTERED  (SD_PK)
;

CREATE UNIQUE NONCLUSTERED INDEX NR_UX__SD_Name_SD_Owner_SD_DepartmentGuid ON StmData (SD_Name,SD_Owner,SD_DepartmentGuid)
;

CREATE TABLE  RefDocType
( 
     RT_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     RT_ReferenceType VARCHAR(3) NOT NULL DEFAULT '',
     RT_DocType VARCHAR(4) NOT NULL DEFAULT '',
     RT_SE_NKDocumentReceivedEvent VARCHAR(3) NOT NULL DEFAULT '',
     RT_Desc VARCHAR(50) NOT NULL DEFAULT '',
     RT_HPPclPrintFile CHAR(1) NOT NULL DEFAULT 'N',
     RT_ForceUserToRead CHAR(1) NOT NULL DEFAULT 'N',
     RT_IsActive CHAR(1) NOT NULL DEFAULT 'Y',
     RT_IsSystem CHAR(1) NOT NULL DEFAULT 'N',
     RT_IsPublished CHAR(1) NOT NULL DEFAULT 'N',
     RT_IsPublishUpdatable CHAR(1) NOT NULL DEFAULT 'N',
     RT_SaveVersions CHAR(1) NOT NULL DEFAULT 'N',
     RT_LogSystemCreatedDocsToEDocs CHAR(1) NOT NULL DEFAULT 'Y',
     RT_OriginalDocumentReleasedOnPayment CHAR(1) NOT NULL DEFAULT 'N'
)
ALTER TABLE  RefDocType
ADD CONSTRAINT PK_UX__RT_PK PRIMARY KEY NONCLUSTERED  (RT_PK)
;

CREATE UNIQUE CLUSTERED INDEX NR_UC__RT_ReferenceType_RT_DocType ON RefDocType (RT_ReferenceType,RT_DocType)
;

CREATE TABLE  StmMenuEDocs
( 
     SX_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SX_SU UNIQUEIDENTIFIER NOT NULL,
     SX_RT_DocType UNIQUEIDENTIFIER NULL,
     SX_IsSystemDefined CHAR(1) NOT NULL DEFAULT 'N',
     SX_IsClientSupressed CHAR(1) NOT NULL DEFAULT 'N'
)
ALTER TABLE  StmMenuEDocs
ADD CONSTRAINT PK_UX__SX_PK PRIMARY KEY NONCLUSTERED  (SX_PK)
;

CREATE NONCLUSTERED INDEX FK_RX__SX_SU ON StmMenuEDocs (SX_SU)
;

CREATE NONCLUSTERED INDEX FK_RX__SX_RT_DocType ON StmMenuEDocs (SX_RT_DocType)
;

CREATE UNIQUE NONCLUSTERED INDEX NR_UX__SX_SU_SX_RT_DocType ON StmMenuEDocs (SX_SU,SX_RT_DocType)
;

CREATE TABLE  StmMenuItem
( 
     SU_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SU_IsDocPack CHAR(1) NOT NULL DEFAULT 'N',
     SU_IsPublished CHAR(1) NOT NULL DEFAULT 'N',
     SU_IsModifiable CHAR(1) NOT NULL DEFAULT 'Y',
     SU_IsCreditControlled CHAR(1) NOT NULL DEFAULT 'N',
     SU_IsSystemDefined CHAR(1) NOT NULL DEFAULT 'N',
     SU_IsClientSpecific CHAR(1) NOT NULL DEFAULT 'N',
     SU_MustRunOnline CHAR(1) NOT NULL DEFAULT 'N',
     SU_MenuType VARCHAR(3) NOT NULL DEFAULT 'DOC',
     SU_MenuName VARCHAR(127) NOT NULL DEFAULT '',
     SU_BusinessContext VARCHAR(20) NOT NULL DEFAULT '',
     SU_ContactType CHAR(3) NOT NULL DEFAULT '',
     SU_AddressCategory VARCHAR(3) NOT NULL DEFAULT '',
     SU_PreventAutoDelivery CHAR(1) NOT NULL DEFAULT 'N',
     SU_SupportsVisualisation CHAR(1) NOT NULL DEFAULT 'Y',
     SU_ShowDocToSendTab CHAR(1) NOT NULL DEFAULT 'Y',
     SU_AllowRawView CHAR(1) NOT NULL DEFAULT 'N',
     SU_AllowDraft CHAR(1) NOT NULL DEFAULT 'Y',
     SU_MenuPath VARCHAR(64) NOT NULL DEFAULT '',
     SU_LicenceLevel VARCHAR(3) NOT NULL DEFAULT 'STD',
     SU_MenuShortcut VARCHAR(15) NOT NULL DEFAULT '',
     SU_MenuIndex SMALLINT NOT NULL DEFAULT 0,
     SU_FilterList VARCHAR(128) NOT NULL DEFAULT '',
     SU_DocumentDirection VARCHAR(3) NOT NULL DEFAULT '',
     SU_SE_NKDocumentEvent VARCHAR(3) NOT NULL DEFAULT '',
     SU_Hint VARCHAR(1024) NOT NULL DEFAULT '',
     SU_MenuDataContext VARCHAR(35) NOT NULL DEFAULT '',
     SU_EmailSubjectLine VARCHAR(256) NOT NULL DEFAULT '',
     SU_ActionDataUpdateBlob VARBINARY(max) NULL,
     SU_ActionMenusAndMethodsBlob VARBINARY(max) NULL,
     SU_IsLocalDocument CHAR(1) NOT NULL DEFAULT 'N',
     SU_IncludeDocInArchive VARCHAR(3) NOT NULL DEFAULT '',
     SU_FlexCelLineSpacing DECIMAL(9,3) NOT NULL DEFAULT 1,
     SU_GS UNIQUEIDENTIFIER NULL
)
ALTER TABLE  StmMenuItem
ADD CONSTRAINT PK_UX__SU_PK PRIMARY KEY NONCLUSTERED  (SU_PK)
;

CREATE TABLE  StmMenuMenuPivot
( 
     SF_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SF_SU_Outward UNIQUEIDENTIFIER NULL,
     SF_SU_Inward UNIQUEIDENTIFIER NULL,
     SF_Index SMALLINT NOT NULL DEFAULT 0,
     SF_IsClientSpecific CHAR(1) NOT NULL DEFAULT 'N',
     SF_IsSystemDefined CHAR(1) NOT NULL DEFAULT 'N'
)
ALTER TABLE  StmMenuMenuPivot
ADD CONSTRAINT PK_UX__SF_PK PRIMARY KEY NONCLUSTERED  (SF_PK)
;

CREATE TABLE  StmMenuTemplatePivot
( 
     SI_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SI_SU UNIQUEIDENTIFIER NOT NULL,
     SI_SO UNIQUEIDENTIFIER NOT NULL,
     SI_DocumentTitle VARCHAR(128) NOT NULL DEFAULT '',
     SI_MenuTemplateFilter VARCHAR(128) NOT NULL DEFAULT '',
     SI_PrintCopyType VARCHAR(3) NOT NULL DEFAULT '',
     SI_IsClientSpecific CHAR(1) NOT NULL DEFAULT 'N',
     SI_IsSystemDefined CHAR(1) NOT NULL DEFAULT 'N',
     SI_PrintByDefault CHAR(1) NOT NULL DEFAULT 'Y',
     SI_Index TINYINT NOT NULL DEFAULT 0,
     SI_TrailingLines SMALLINT NOT NULL DEFAULT 0,
     SI_SE_NKDocumentSentEvent VARCHAR(3) NOT NULL DEFAULT '',
     SI_RT_DocType UNIQUEIDENTIFIER NULL,
     SI_ClosingText VARCHAR(max) NOT NULL DEFAULT '',
     SI_OpeningText VARCHAR(max) NOT NULL DEFAULT ''
)
ALTER TABLE  StmMenuTemplatePivot
ADD CONSTRAINT PK_UX__SI_PK PRIMARY KEY NONCLUSTERED  (SI_PK)
;

CREATE TABLE  StmTemplate
( 
     SO_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     SO_Name VARCHAR(127) NOT NULL DEFAULT '',
     SO_DataContext VARCHAR(35) NOT NULL DEFAULT '',
     SO_LicenceCode VARCHAR(3) NOT NULL DEFAULT '',
     SO_Template VARBINARY(max) NULL,
     SO_IsSystemDefined CHAR(1) NOT NULL DEFAULT 'N',
     SO_IsUserConfigurable CHAR(1) NOT NULL DEFAULT 'N',
     SO_IsClientSpecific CHAR(1) NOT NULL DEFAULT 'N',
     SO_IsPasswordProtected CHAR(1) NOT NULL DEFAULT 'N',
     SO_CannotEditDocumentData CHAR(1) NOT NULL DEFAULT 'N',
     SO_UDFFieldCache VARBINARY(max) NULL,
     SO_TemplateRestriction VARCHAR(256) NOT NULL DEFAULT '',
     SO_ExcelTemplatePath VARCHAR(255) NOT NULL DEFAULT ''
)
ALTER TABLE  StmTemplate
ADD CONSTRAINT PK_UX__SO_PK PRIMARY KEY NONCLUSTERED  (SO_PK)
;

CREATE UNIQUE NONCLUSTERED INDEX NR_UX__SO_Name_SO_DataContext_SO_IsSystemDefined_SO_IsClientSpecific ON StmTemplate (SO_Name,SO_DataContext,SO_IsSystemDefined,SO_IsClientSpecific)
;

CREATE TABLE  StmMenuDocumentConfig
( 
     S3_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     S3_IsSystem CHAR(1) NOT NULL DEFAULT 'N',
     S3_IsPasswordProtected CHAR(1) NOT NULL DEFAULT 'N',
     S3_SI UNIQUEIDENTIFIER NOT NULL,
     S3_GC UNIQUEIDENTIFIER NULL,
     S3_OH UNIQUEIDENTIFIER NULL,
     S3_OverrideSystemOpeningClosingText CHAR(1) NOT NULL DEFAULT 'N',
     S3_OverrideOpeningText VARCHAR(max) NOT NULL DEFAULT '',
     S3_OverrideClosingText VARCHAR(max) NOT NULL DEFAULT ''
)
ALTER TABLE  StmMenuDocumentConfig
ADD CONSTRAINT PK_UX__S3_PK PRIMARY KEY NONCLUSTERED  (S3_PK)
;

CREATE UNIQUE NONCLUSTERED INDEX FK_UX__S3_SI_S3_GC_S3_OH_S3_IsSystem ON StmMenuDocumentConfig (S3_SI,S3_GC,S3_OH,S3_IsSystem)
;

CREATE TABLE  StmMenuDocumentConfigItem
( 
     S4_PK UNIQUEIDENTIFIER NOT NULL DEFAULT newid(),
     S4_PrintOrder INT NOT NULL DEFAULT 0,
     S4_SectionType VARCHAR(3) NOT NULL DEFAULT '',
     S4_SectionItemName VARCHAR(128) NOT NULL DEFAULT '',
     S4_Color INT NOT NULL DEFAULT 0,
     S4_FilterList VARCHAR(128) NOT NULL DEFAULT '',
     S4_S3 UNIQUEIDENTIFIER NOT NULL
)
ALTER TABLE  StmMenuDocumentConfigItem
ADD CONSTRAINT PK_UX__S4_PK PRIMARY KEY NONCLUSTERED  (S4_PK)
;

ALTER TABLE StmNumberCache
      ADD CONSTRAINT StmNumberCache_SG_SN_FK2_StmNums_RRR_120N FOREIGN KEY
          ( SG_SN )
          REFERENCES StmNums
          ( SN_PK )
;

CREATE TABLE RateAttachmentSet
(
	TS_PK uniqueidentifier NOT NULL
)
;

