using CargoWise.Data;
using NUnit.Framework;
using static System.Data.SqlDbType;

namespace Enterprise.Build.Database.Script.Testing.Public.Customs.US.ModelViews
{
	[TestedType(typeof(CargoWise.DbUpgrader.Scripts.Definitions.Customs.US.ModelViews.USJobDeclaration))]
	class USJobDeclarationTest : DbCreateScriptTest
	{
		public void TestViewColumns()
		{
			TestDbViewHelper.AssertViewColumns(
				Db.Connection,
				"USJobDeclaration",
				"JobDeclaration",
				new []
				{
					new TestDbViewHelper.DbColumn("JE_PK", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JE_ClusterKey", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JE_7501Agent", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_7501Purchased", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_AcceleratedClaimInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_AccLiqReq", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ADDCVDSuretyCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_AESBGMRefLastUsed", VarChar, 17),
					new TestDbViewHelper.DbColumn("JE_ALDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_ALDuty", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JE_AuditFdaLastLogDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_AuditFdaLastLogReference", VarChar, 128),
					new TestDbViewHelper.DbColumn("JE_AuditFdaLastLogUser", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_AuditSpiLastLogDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_AuditSpiLastLogReference", VarChar, 128),
					new TestDbViewHelper.DbColumn("JE_AuditSpiLastLogUser", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_BondAmount", Decimal, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JE_BondAmount2", Decimal, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JE_BondCalcCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_BondDesignationCode", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_BondDispositionCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_BondDispositionCode2", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_BondProducerAccNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_BondProducerAccNo2", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_BondSuperseding", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_BondType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_BondType2", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_BondWaiverCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_Box29IncludeContainers", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_Box29Text", VarChar, 200),
					new TestDbViewHelper.DbColumn("JE_BRDRefNo", VarChar, 20),
					new TestDbViewHelper.DbColumn("JE_CargoReleaseType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_CarrierName", VarChar, 35),
					new TestDbViewHelper.DbColumn("JE_CBPBondNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JE_CBPBondNo2", VarChar, 9),
					new TestDbViewHelper.DbColumn("JE_CertifyCargoRelease", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_CertReqDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_CheckNo", VarChar, 35),
					new TestDbViewHelper.DbColumn("JE_ClaimPort", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_ClientBranchDesignation", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_CommodityFilingOption", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_ConsolACE", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ConsolidatedInformalIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_CRLAction", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_DateOfExport", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DDTCITARExemptionNo", VarChar, 12),
					new TestDbViewHelper.DbColumn("JE_DDTCMilitaryEquipmentIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_DDTCPartyCertificationIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_DDTCRegistrationNo", VarChar, 6),
					new TestDbViewHelper.DbColumn("JE_DDTCUSMLCategoryCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_DeferredTaxDueDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DES", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_DestinationState", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_DisclaimSanctions", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DomesticCargo", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWBillOfFormula", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWCertOfManufacture", VarChar, 8),
					new TestDbViewHelper.DbColumn("JE_DRWCommRuling", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_DRWDatePeriodFrom", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DRWDatePeriodTo", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DRWDestroyedValuation", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWDestructionResult", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_DRWElectManufPetroleumCert", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWElectPetroleumCert", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWEnableMerge", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWExamBadge", VarChar, 12),
					new TestDbViewHelper.DbColumn("JE_DRWExamDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DRWExamName", VarChar, 40),
					new TestDbViewHelper.DbColumn("JE_DRWExamPhone", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_DRWExamWitness", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWFilingMethod", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_DRWIntendedPortOfExport", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_DRWLocatOfDest", VarChar, 30),
					new TestDbViewHelper.DbColumn("JE_DRWOilSpillTaxCert", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWOneTimeWaiverInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWPrintSubTotals", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWProcBadge", VarChar, 12),
					new TestDbViewHelper.DbColumn("JE_DRWProcDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_DRWProcName", VarChar, 40),
					new TestDbViewHelper.DbColumn("JE_DRWProcPhone", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_DRWPurpose", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_DRWRejectedMerchandiseReason", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_DRWRulingNo", VarChar, 12),
					new TestDbViewHelper.DbColumn("JE_DRWSameCondNAFTA", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWSection", VarChar, 35),
					new TestDbViewHelper.DbColumn("JE_DRWSuperfundInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_DRWTENo", VarChar, 30),
					new TestDbViewHelper.DbColumn("JE_DRWTotalPRDC", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JE_DRWTransferee", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JE_DRWUnUsedWine", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_EarliestExportDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_ECCN", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_EnableAII", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_EnableCRL", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_EnableENS", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_EnableINB", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_EnableSPN", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ENSAction", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_EntryDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_EntryDateElectionCode", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_EntryFilerCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_EntryMode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_EntryType", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_EstEnteredValue", Decimal, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JE_EstimatedEntryDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_ExpConsign", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_ExportCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_ExporterSummaryInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_F_AdmissionType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_F_BOCStatInfoFurnished", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_F_DeliveryCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_F_DirectDelivery", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_F_IncludePTT", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_F_PNMode", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_F_PTTWOExc", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_F_RoutingDetails", VarChar, 9),
					new TestDbViewHelper.DbColumn("JE_FDAADTA", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_FDAAPC", VarChar, 25),
					new TestDbViewHelper.DbColumn("JE_FDACAN", VarChar, 25),
					new TestDbViewHelper.DbColumn("JE_FDACANType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_FDACCN", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_FDAContactEmail", VarChar, 254),
					new TestDbViewHelper.DbColumn("JE_FDAContactName", VarChar, 101),
					new TestDbViewHelper.DbColumn("JE_FDAContactPhoneNo", VarChar, 15),
					new TestDbViewHelper.DbColumn("JE_FileTheirOwnRecon", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_FirstPortOfCallCity", VarChar, 25),
					new TestDbViewHelper.DbColumn("JE_FixDefTaxDueDate", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_FixPSD", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_FixRecon", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ForeignTradeZone", VarChar, 9),
					new TestDbViewHelper.DbColumn("JE_FSISInspec", VarChar, 20),
					new TestDbViewHelper.DbColumn("JE_FTZConcurrenceQty", Decimal, -1, 19, 0),
					new TestDbViewHelper.DbColumn("JE_FTZNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JE_GeneralOrderNo", VarChar, 13),
					new TestDbViewHelper.DbColumn("JE_GoodsFromFTZ", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_HazardousCargo", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_IBBTAFDA", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ImmediateDelivery", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ImportConveyanceName", VarChar, 23),
					new TestDbViewHelper.DbColumn("JE_ImportEntryNo", VarChar, 17),
					new TestDbViewHelper.DbColumn("JE_InBondArrivalConveyance", VarChar, 23),
					new TestDbViewHelper.DbColumn("JE_InBondArrivalDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_InBondExportConveyance", VarChar, 23),
					new TestDbViewHelper.DbColumn("JE_InBondExportDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_InBondExportTransMode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_InBondMoveFromFTZ", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_InBondTOLCity", VarChar, 19),
					new TestDbViewHelper.DbColumn("JE_InBondTOLDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_InBondTOLState", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_InbondType", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_InspecDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_InspecFirms", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_InspecPort", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_InsuranceAgent", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_InsuranceDisposition", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_IsAIIRequested", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_IsFinalWHS", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_IsHMFApplicable", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_IsInvoiceByRequest", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ITDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_ITPresentationPort", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_JobReadyForPost", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_JurisdictionNumber", VarChar, 10),
					new TestDbViewHelper.DbColumn("JE_LatestRateDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_LicenseNo", VarChar, 14),
					new TestDbViewHelper.DbColumn("JE_LicenseType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_LiveEntryIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_ManEntry", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_MissingDocument1", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_MissingDocument2", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_MonthlyFiling", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_NAFTAClaimInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_NAFTAClaimStat", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_NAFTADrawbackCountry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_NAFTAReconIndicator", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_NoDutyCalc", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_NonAMS", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_OGALineReleaseIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_OriginalITNNumber", VarChar, 15),
					new TestDbViewHelper.DbColumn("JE_OtherReconIndicator", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_Paid", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_PaperlessEntry", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_PayableMPF", Decimal, -1, 15, 7),
					new TestDbViewHelper.DbColumn("JE_PaymentDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_PaymentDueDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_PaymentType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_PeriodicStatementMM", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_PetroleumClaimInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_PGAExpeditedRelease", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_PipelineName", VarChar, 20),
					new TestDbViewHelper.DbColumn("JE_PreInspectionInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_PreliminaryStatementPrintDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_PreparerDistrictPort", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_PreparerOfficeCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_PresentationDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_PriorDisclosure", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_ProtestStat", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_PSC", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_QtyBeingWithdrawn", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JE_QtyInWHAfterWithdrawal", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JE_QtyInWHBeforeWithdrawal", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JE_RL_NKPortOfExport", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_RN_NKCountryOfDestination", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_RN_NKFirstPortOfCallCountry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_RoutedTransaction", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_SchDArrival", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDEntry", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDExam", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_SchDExport", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDINBArrival", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDINBExport", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDLoading", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchDUSDestination", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SchKINBFinalForeignDest", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SEMultiCargoDispInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_SESplitRel", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_SoldEnRouteIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_SpecialKINBFinalForeignDest", VarChar, 5),
					new TestDbViewHelper.DbColumn("JE_SPNIDType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_StateOfOrigin", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_StatusTibLastLogDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JE_StatusTibLastLogReference", VarChar, 128),
					new TestDbViewHelper.DbColumn("JE_StatusTibLastLogUser", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_SuretyCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_TariffType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_TaxDeferIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_TeamNo", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_TIBMotorVehicles", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_TIBMVNonConforming", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_TIBPurpose", VarChar, 80),
					new TestDbViewHelper.DbColumn("JE_TotalEnteredValue", Decimal, -1, 15, 0),
					new TestDbViewHelper.DbColumn("JE_TransactionsRelated", VarChar, 1),
					new TestDbViewHelper.DbColumn("JE_TransportReference", VarChar, 30),
					new TestDbViewHelper.DbColumn("JE_UC_NKCountryOfExport", VarChar, 2),
					new TestDbViewHelper.DbColumn("JE_UI_NKCarrierSCAC", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_US_NKCentralizedExamSite", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_US_NKLocationOfGoods", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_USMCAClaimInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_WaiverNoticeInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JE_WHSDistrictPortCode", VarChar, 4),
					new TestDbViewHelper.DbColumn("JE_WHSEntryFilerCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JE_WHSEntryNumber", VarChar, 20),
				}
			);
		}

		public void TestViewIndexes()
		{
			TestDbViewHelper.AssertViewIndexes(
				Db.Connection,
				"USJobDeclaration_IDx",
				new[]
				{
					new TestDbViewHelper.DbIndex("NR_UC__JE_ClusterKey_JE_PK", "JE_ClusterKey,JE_PK"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_AcceleratedClaimInd", "JE_AcceleratedClaimInd"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_ALDate", "JE_ALDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_BondDispositionCode", "JE_BondDispositionCode"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_BondDispositionCode2", "JE_BondDispositionCode2"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_BondProducerAccNo", "JE_BondProducerAccNo"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_BondType", "JE_BondType"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_BRDRefNo", "JE_BRDRefNo"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_ClaimPort", "JE_ClaimPort"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_CRLAction", "JE_CRLAction"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_DateOfExport", "JE_DateOfExport"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_DeferredTaxDueDate", "JE_DeferredTaxDueDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_DRWDatePeriodFrom", "JE_DRWDatePeriodFrom"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_DRWDatePeriodTo", "JE_DRWDatePeriodTo"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EarliestExportDate", "JE_EarliestExportDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_ENSAction", "JE_ENSAction"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EntryDate", "JE_EntryDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EntryFilerCode", "JE_EntryFilerCode"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EntryMode", "JE_EntryMode"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EntryType", "JE_EntryType"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_EstimatedEntryDate", "JE_EstimatedEntryDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_ExporterSummaryInd", "JE_ExporterSummaryInd"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_F_AdmissionType", "JE_F_AdmissionType"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_FTZNo", "JE_FTZNo"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_InbondType", "JE_InbondType"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_InsuranceDisposition", "JE_InsuranceDisposition"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_IsAIIRequested", "JE_IsAIIRequested"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_NAFTAClaimInd", "JE_NAFTAClaimInd"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_NAFTADrawbackCountry", "JE_NAFTADrawbackCountry"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_NAFTAReconIndicator", "JE_NAFTAReconIndicator"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_OtherReconIndicator", "JE_OtherReconIndicator"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PaperlessEntry", "JE_PaperlessEntry"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PaymentDueDate", "JE_PaymentDueDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PaymentType", "JE_PaymentType"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PetroleumClaimInd", "JE_PetroleumClaimInd"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PreInspectionInd", "JE_PreInspectionInd"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PreliminaryStatementPrintDate", "JE_PreliminaryStatementPrintDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PreparerDistrictPort", "JE_PreparerDistrictPort"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PresentationDate", "JE_PresentationDate"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_PSC", "JE_PSC"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_RN_NKCountryOfDestination", "JE_RN_NKCountryOfDestination"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_SchDArrival", "JE_SchDArrival"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_SchDEntry", "JE_SchDEntry"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_SchDExport", "JE_SchDExport"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_SchDLoading", "JE_SchDLoading"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_SuretyCode", "JE_SuretyCode"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_TeamNo", "JE_TeamNo"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_TransportReference", "JE_TransportReference"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_UI_NKCarrierSCAC", "JE_UI_NKCarrierSCAC"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_US_NKLocationOfGoods", "JE_US_NKLocationOfGoods"),
					new TestDbViewHelper.DbIndex("NR_UX__JE_WaiverNoticeInd", "JE_WaiverNoticeInd"),
				}
			);
		}
	}
}
