using CargoWise.Data;
using NUnit.Framework;
using static System.Data.SqlDbType;

namespace Enterprise.Build.Database.Script.Testing.Public.Customs.US.ModelViews
{
	[TestedType(typeof(CargoWise.DbUpgrader.Scripts.Definitions.Customs.US.ModelViews.USJobComInvoiceLine))]
	class USJobComInvoiceLineTest : DbCreateScriptTest
	{
		public void TestViewColumns()
		{
			TestDbViewHelper.AssertViewColumns(
				Db.Connection,
				"USJobComInvoiceLine",
				"JobComInvoiceLine",
				new []
				{
					new TestDbViewHelper.DbColumn("JI_PK", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JI_ClusterKey", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_9802PerUnit", Decimal, -1, 19, 4),
					new TestDbViewHelper.DbColumn("JI_98GoodsValue", Decimal, -1, 19, 4),
					new TestDbViewHelper.DbColumn("JI_98InvCurrPerUnit", Decimal, -1, 19, 4),
					new TestDbViewHelper.DbColumn("JI_98ValueInvCurr", Decimal, -1, 19, 4),
					new TestDbViewHelper.DbColumn("JI_ADCVDStat", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ADD_NA", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_ADDCaseNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_ADDDecID", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_ADDDepositRateIndicator", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_ADDDepositRateOverride", Decimal, -1, 8, 4),
					new TestDbViewHelper.DbColumn("JI_ADDDepositValue", Decimal, -1, 10, 4),
					new TestDbViewHelper.DbColumn("JI_ADDQty", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JI_ADDuty", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JI_ADD_Cert", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_AESOriginIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_AgricultureLicNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_AllocationQuantity", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JI_AMMVPercentage", Decimal, -1, 9, 5),
					new TestDbViewHelper.DbColumn("JI_AMMVPerUnit", Decimal, -1, 19, 4),
					new TestDbViewHelper.DbColumn("JI_AMSDisclaimProgram", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_AMSDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_AMSInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_APHISDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_APHISInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ArticleNoA", VarChar, 35),
					new TestDbViewHelper.DbColumn("JI_ArticleNoB", VarChar, 35),
					new TestDbViewHelper.DbColumn("JI_ATFInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_BOMLineExpanded", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_BOMParentLine", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JI_CAExportCertificate", VarChar, 8),
					new TestDbViewHelper.DbColumn("JI_CBTPACertificateNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_CI_PreviousPivot", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JI_CBMADefaultTaxAmount", Decimal, -1, 19, 5),
					new TestDbViewHelper.DbColumn("JI_CBMADefaultTaxRate", Decimal, -1, 18, 9),
					new TestDbViewHelper.DbColumn("JI_ControlledGroupName", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_CottonCertificateNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_CottonFeeExempt", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_CPSCDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_CPSCInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_CustomsValue", Decimal, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_CVD_NA", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_CVDCaseNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_CVDDepositRateIndicator", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_CVDDepositRateOverride", Decimal, -1, 8, 4),
					new TestDbViewHelper.DbColumn("JI_CVDDepositValue", Decimal, -1, 10, 4),
					new TestDbViewHelper.DbColumn("JI_CVDQty", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JI_CVDuty", Decimal, -1, 12, 4),
					new TestDbViewHelper.DbColumn("JI_CVD_Cert", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DateOfExport", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DateOfExportFromCountryOfOrigin", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DDTCArrivalDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DDTCExemptionCode", VarChar, 8),
					new TestDbViewHelper.DbColumn("JI_DDTCInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DDTCITARExemptionNo", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_DDTCLicenseNo", VarChar, 33),
					new TestDbViewHelper.DbColumn("JI_DDTCLicenseType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DDTCMilitaryEquipmentIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DDTCPartyCertificationIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DDTCQuantity", Decimal, -1, 7, 0),
					new TestDbViewHelper.DbColumn("JI_DDTCRegistrationNo", VarChar, 6),
					new TestDbViewHelper.DbColumn("JI_DDTCTrackingStatus", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DDTCUnit", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DDTCUSMLCategoryCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DEADisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DEAInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DerivedCV", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DestinationState", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DisclaimSanctions", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DOTIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DRW99ClaimedDuty", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRW99ClaimedHMF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRW99ClaimedMPF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRW99ClaimedTax", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAccMethod", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAdjClaimDuty", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAdjClaimHMF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAdjClaimMPF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAdjClaimTax", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWAdValoremRate", Decimal, -1, 12, 6),
					new TestDbViewHelper.DbColumn("JI_DRWAllowQty", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWAllowQty2", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWAllowQty3", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWCalcDuty", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCalcDutyWithAdValoremRate", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWCalcHMF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCalcMPF", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCalcTax", Decimal, -1, 8, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCDInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWCDUse", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCertOfManufacture", VarChar, 8),
					new TestDbViewHelper.DbColumn("JI_DRWClaimAmountOverriden_New", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWClaimBasis", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DRWCMCDIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DRWDateDelFrom", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateDelTo", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateOfManufacture", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateRcvFrom", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateRcvTo", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateUsedFrom", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDateUsedTo", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWDeclaredHMF", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DRWDeclaredMPF", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DRWDeclaredOtherFees", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DRWDeclaredTax", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DRWDeclaredVFD", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_DRWDescrManufactured", VarChar, 40),
					new TestDbViewHelper.DbColumn("JI_DRWDescrUsed", VarChar, 32),
					new TestDbViewHelper.DbColumn("JI_DRWDutyRate_New", Decimal, -1, 10, 5),
					new TestDbViewHelper.DbColumn("JI_DRWEntryDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWExpBOLCarrier", VarChar, 4),
					new TestDbViewHelper.DbColumn("JI_DRWExpBOLInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWExpNoticeInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWExportAction", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DRWExportDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWExportDest", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_DRWExportID", VarChar, 28),
					new TestDbViewHelper.DbColumn("JI_DRWExportQuantity", Decimal, -1, 18, 5),
					new TestDbViewHelper.DbColumn("JI_DRWExportUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DRWExpWavInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWFactoryLocation", VarChar, 20),
					new TestDbViewHelper.DbColumn("JI_DRWImpActInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DRWImpManufRuleNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_DRWImportEntryLine", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_DRWImportInvoiceLineNo", SmallInt, -1, 5, 0),
					new TestDbViewHelper.DbColumn("JI_DRWImportQuantity", Decimal, -1, 18, 5),
					new TestDbViewHelper.DbColumn("JI_DRWImportQuantity2", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWImportQuantity3", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWImportUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DRWImportUQ2", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DRWImportUQ3", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DRWImpTrkID", VarChar, 5),
					new TestDbViewHelper.DbColumn("JI_DRWIntendedPortOfExport", VarChar, 4),
					new TestDbViewHelper.DbColumn("JI_DRWIsForExportSection", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWIsForImportSection", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWIsForManufacturerSection", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWLineDuty", Decimal, -1, 9, 2),
					new TestDbViewHelper.DbColumn("JI_DRWLineDutyRateDesc", VarChar, 30),
					new TestDbViewHelper.DbColumn("JI_DRWMafActInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_DRWMafTrkID", VarChar, 5),
					new TestDbViewHelper.DbColumn("JI_DRWManufRuleNo", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_DRWMethodOfDestruction", VarChar, 150),
					new TestDbViewHelper.DbColumn("JI_DRWMPFWeightedRatio", Decimal, -1, 9, 6),
					new TestDbViewHelper.DbColumn("JI_DRWNoticeOfIntentLastPrint", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_DRWOldData", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWPort", VarChar, 4),
					new TestDbViewHelper.DbColumn("JI_DRWQuantityUsed", Decimal, -1, 19, 5),
					new TestDbViewHelper.DbColumn("JI_DRWQuarterlyHMF", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_DRWSubstituted", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWSubstituted2", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWSubstituted3", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWTENo", VarChar, 30),
					new TestDbViewHelper.DbColumn("JI_DRWUQUsed", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_DRWValuePerUQ", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWValuePerUQ2", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWValuePerUQ3", Decimal, -1, 16, 4),
					new TestDbViewHelper.DbColumn("JI_DRWWeightedRatio", Decimal, -1, 9, 6),
					new TestDbViewHelper.DbColumn("JI_Duty", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_ECCN", VarChar, 5),
					new TestDbViewHelper.DbColumn("JI_EPAConsentNumber", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_EPANetQty", Decimal, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_EPANetQtyUQ", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_ExclusionNumber", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_ExportCertificateNo", VarChar, 13),
					new TestDbViewHelper.DbColumn("JI_ExportCode", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_ExportTariff", VarChar, 13),
					new TestDbViewHelper.DbColumn("JI_F_PNDisclaimer", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FCCIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FDAContactEmail", VarChar, 254),
					new TestDbViewHelper.DbColumn("JI_FDAContactName", VarChar, 101),
					new TestDbViewHelper.DbColumn("JI_FDAContactPhoneNo", VarChar, 15),
					new TestDbViewHelper.DbColumn("JI_FDADisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FDAIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FirstSale", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FlavorContentCreditInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_FPI", VarChar, 14),
					new TestDbViewHelper.DbColumn("JI_FSISDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FSISInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FTADuty", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_FTAPayableMPF", Decimal, -1, 15, 7),
					new TestDbViewHelper.DbColumn("JI_FTASPI", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_FTZCurrentTariff", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_FWSDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_FWSInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_HasMPF", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_HazMatClassDesc", VarChar, 60),
					new TestDbViewHelper.DbColumn("JI_HazMatDesc", VarChar, 60),
					new TestDbViewHelper.DbColumn("JI_HazWasteTrackingNo", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_HFCInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_HFCDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ImpDecInvoiceNum", VarChar, 35),
					new TestDbViewHelper.DbColumn("JI_ImportEntryNo", VarChar, 17),
					new TestDbViewHelper.DbColumn("JI_IsBondedADD", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_IsBondedCVD", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_IsExcludedFromAII", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_IsNAFTANet", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_IsParent", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_IsUsedVehicle", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_JI_ParentProduct", UniqueIdentifier, -1),
					new TestDbViewHelper.DbColumn("JI_JurisdictionNumber", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_LaceyDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_LaceyIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_LicenseNo", VarChar, 14),
					new TestDbViewHelper.DbColumn("JI_LicenseType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_LicenseValue", Decimal, -1, 10, 2),
					new TestDbViewHelper.DbColumn("JI_LumberExportCharges", Decimal, -1, 10, 2),
					new TestDbViewHelper.DbColumn("JI_LumberExportPrice", Decimal, -1, 10, 2),
					new TestDbViewHelper.DbColumn("JI_LumberImporterDeclaration", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ManifestQty", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_ManifestUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_MarksAndNumbers", VarChar, 75),
					new TestDbViewHelper.DbColumn("JI_MiscPermitNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_NAFTADutyFGN", Decimal, -1, 12, 2),
					new TestDbViewHelper.DbColumn("JI_NAFTADutyRate", Decimal, -1, 12, 2),
					new TestDbViewHelper.DbColumn("JI_NAFTADutyUS", Decimal, -1, 12, 2),
					new TestDbViewHelper.DbColumn("JI_NAFTATariff", VarChar, 10),
					new TestDbViewHelper.DbColumn("JI_NHTDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NHTSAIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFS370DisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFS370Ind", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSAMRDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSCOAInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSAMRInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSHMSDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSHMSInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NMFSSIMPInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NonFTADuty", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_NonFTAPayableMPF", Decimal, -1, 15, 7),
					new TestDbViewHelper.DbColumn("JI_RN_NKPrimCtry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_RN_NKSecCtry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_RN_NKCastCtry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_RN_NKCertOrigin", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_RN_NKMeltCtry", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_NOPDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_NOPInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ODSDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ODSInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_ODSLineNumber", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_ODSTrackingStatus", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_OMCDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_OMCInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_OverrideDuty", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_OverrideSupDuty", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_PayableMPF", Decimal, -1, 15, 7),
					new TestDbViewHelper.DbColumn("JI_PGATrackingID", VarChar, 50),
					new TestDbViewHelper.DbColumn("JI_PIRPRulingNo", VarChar, 6),
					new TestDbViewHelper.DbColumn("JI_PIRPRulingType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_Prim_NA", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_PrivilegedStatusDate", DateTime, -1),
					new TestDbViewHelper.DbColumn("JI_ProductExclusion", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_PSTDisclaimProgram", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_PSTDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_PSTIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_R_HTSChanged4ValueInd", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_R_Orig98Value", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigCottonFeeExempt", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_R_OrigCV", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigDuty", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_R_OrigEntryLineNo" , VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigFirstQty", Decimal, -1, 15, 5),
					new TestDbViewHelper.DbColumn("JI_R_OrigFirstUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigHasMPF", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_R_OrigOverrideDuty", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_R_OrigOverrideSupDuty", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_R_OrigRateType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_R_OrigSecondQty", Decimal, -1, 15, 5),
					new TestDbViewHelper.DbColumn("JI_R_OrigSecondUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigSPI", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupDuty", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupQty1", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupQty2", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupQty3", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupTariff", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupUQ1", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupUQ2", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigSupUQ3", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigTariff", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxApply", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxQty", Decimal, -1, 15, 8),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxRate", Decimal, -1, 15, 8),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxRateS", VarChar, 20),
					new TestDbViewHelper.DbColumn("JI_R_OrigTaxRateT", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_R_OrigThirdQty", Decimal, -1, 15, 5),
					new TestDbViewHelper.DbColumn("JI_R_OrigThirdUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_R_ReconReasonText", VarChar, 40),
					new TestDbViewHelper.DbColumn("JI_R_Textile", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_SchDLoading", VarChar, 5),
					new TestDbViewHelper.DbColumn("JI_Sec_NA", Bit, -1),
					new TestDbViewHelper.DbColumn("JI_SecondarySPI", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_SelectedRateType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_SetInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_SPI", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_SupGoodsValue", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_SupDuty", Decimal, -1, 15, 2),
					new TestDbViewHelper.DbColumn("JI_SupQty1", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_SupQty2", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_SupQty3", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_SupTariff", VarChar, 12),
					new TestDbViewHelper.DbColumn("JI_SupUQ1", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_SupUQ2", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_SupUQ3", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_SWPMIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TariffType", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_TaxApply", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TaxCode", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_TaxQty", Decimal, -1, 15, 4),
					new TestDbViewHelper.DbColumn("JI_TaxRate", Decimal, -1, 18, 9),
					new TestDbViewHelper.DbColumn("JI_TaxRateS", VarChar, 20),
					new TestDbViewHelper.DbColumn("JI_TaxRateT", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TeamNo", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_TextileCategoryNo", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_TransactionsRelated", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TSCACertification", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TSCADisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TSCAInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TSCAIndicator", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TSCALineNumber", Int, -1, 10, 0),
					new TestDbViewHelper.DbColumn("JI_TSCAName", VarChar, 35),
					new TestDbViewHelper.DbColumn("JI_TSCAODSCertIndividual", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_TSCATrackingStatus", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_TTBDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TTBInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_TTBRateDesignationCode", VarChar, 20),
					new TestDbViewHelper.DbColumn("JI_UC_NKCountryOfExport", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_UC_NKCountryOfOrigin", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_UI_NKCarrierSCAC", VarChar, 4),
					new TestDbViewHelper.DbColumn("JI_VehicleID", VarChar, 25),
					new TestDbViewHelper.DbColumn("JI_VehicleIDType", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_VehicleTitleNo", VarChar, 15),
					new TestDbViewHelper.DbColumn("JI_VehicleTitleState", VarChar, 2),
					new TestDbViewHelper.DbColumn("JI_VisaNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_VisaQty", Decimal, -1, 11, 2),
					new TestDbViewHelper.DbColumn("JI_VisaUQ", VarChar, 3),
					new TestDbViewHelper.DbColumn("JI_VNEDisclaimReason", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_VNEInd", VarChar, 1),
					new TestDbViewHelper.DbColumn("JI_GrossWeight", Decimal, -1, 11, 3),
					new TestDbViewHelper.DbColumn("JI_WeightNET", Decimal, -1, 11, 0),
					new TestDbViewHelper.DbColumn("JI_WHSEntryLineNo", SmallInt, -1, 5, 0),
					new TestDbViewHelper.DbColumn("JI_WHSEntryNumber", VarChar, 20),
					new TestDbViewHelper.DbColumn("JI_WoolLicenceNo", VarChar, 9),
					new TestDbViewHelper.DbColumn("JI_ZoneStatus", VarChar, 1),
				}
			);
		}

		public void TestViewIndexes()
		{
			TestDbViewHelper.AssertViewIndexes(
				Db.Connection,
				"USJobComInvoiceLine_Idx",
				new[]
				{
					new TestDbViewHelper.DbIndex("NR_UC__JI_ClusterKey_JI_PK", "JI_ClusterKey,JI_PK"),
					new TestDbViewHelper.DbIndex("NR_UX__JI_SPI", "JI_SPI"),
				}
			);
		}
	}
}
