//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from ChannelAxisCodeList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.BufferManagement.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class ChannelAxisCodeList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Primary = "PRI";
			public const string Secondary = "SEC";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public static MultilingualString Primary { get { return ResString.GetMultilingualString("ChannelAxisCodeList|Primary", "Primary"); } }
			public static MultilingualString Secondary { get { return ResString.GetMultilingualString("ChannelAxisCodeList|Secondary", "Secondary"); } }
		}

		public ChannelAxisCodeList()
		{
			AddPair(Codes.Primary, Descriptions.Primary);
			AddPair(Codes.Secondary, Descriptions.Secondary);
		}
	}
}
