<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.IN.GUI</AssemblyName>
    <RootNamespace>Enterprise.Customs.IN.GUI</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Schema">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Schema.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>