<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Schema">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Schema.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="JobDeclaration\InvoiceLineUserControl\JobWorks\JobWorkUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="JobDeclaration\Layouts\ExportOrientedUnits\ExportOrientedUnitsUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="JobDeclaration\Layouts\SupportingDocumentDetails\LayoutSupportingDocumentsUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="PlugIn\Organisation\OrganisationConsigneePlugInUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="JobDeclaration\Layouts\InvoiceLineDetails\InvoiceLineDetailsLayoutUserControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>