<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.MasterFiles.Module</AssemblyName>
    <RootNamespace>Enterprise.MasterFiles.Module</RootNamespace>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\MasterFiles.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>