<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Customs.ES.TemporaryStorage.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.Customs.ES.TemporaryStorage.Module.Testing</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business.Test\Enterprise.Customs.ES.TemporaryStorage.Business.Test.csproj" />
    <ProjectReference Include="..\Business\Enterprise.Customs.ES.TemporaryStorage.Business.csproj" />
    <ProjectReference Include="..\Module\Enterprise.Customs.ES.TemporaryStorage.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Enterprise.Customs.ES.GUI" />
    <Reference Include="Enterprise.Customs.Module" />
    <Reference Include="Enterprise.Customs.Module.Test" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>