<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <UserSecretsId>1e10e1d5-e681-4630-9917-6d3fab57fd1a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="eServices.eHubDataModel" />
    <PackageReference Include="KafkaFlow" />
    <PackageReference Include="KafkaFlow.Admin" />
    <PackageReference Include="KafkaFlow.Admin.Dashboard" />
    <PackageReference Include="KafkaFlow.LogHandler.Microsoft" />
    <PackageReference Include="KafkaFlow.Microsoft.DependencyInjection" />
    <PackageReference Include="KafkaFlow.OpenTelemetry" />
    <PackageReference Include="KafkaFlow.Retry" />
    <PackageReference Include="log4net" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="WTG.ErrorReporting" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="eServices.ApplicationEvent.EnrichmentService" />
    <Using Include="eServices.ApplicationEvent.EnrichmentService.Enrichers" />
    <Using Include="eServices.ApplicationEvent.EnrichmentService.Instrumentation" />
    <Using Include="eServices.ApplicationEvent.EnrichmentService.Kafka" />
    <Using Include="eServices.ApplicationEvent.EnrichmentService.Services" />
    <Using Include="eServices.eHubDataModel.eHubTransactionsCore" />
    <Using Include="KafkaFlow" />
    <Using Include="KafkaFlow.Admin.Dashboard" />
    <Using Include="KafkaFlow.Configuration" />
    <Using Include="KafkaFlow.OpenTelemetry" />
    <Using Include="Microsoft.EntityFrameworkCore" />
    <Using Include="Microsoft.Extensions.Caching.Distributed" />
    <Using Include="OpenTelemetry" />
    <Using Include="OpenTelemetry.Metrics" />
    <Using Include="OpenTelemetry.Resources" />
    <Using Include="OpenTelemetry.Trace" />
    <Using Include="System.Collections.Concurrent" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Diagnostics" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Nodes" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Enrichers\OceanMessagingResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OceanMessagingResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Enrichers\OceanMessagingResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>OceanMessagingResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="eServices.ApplicationEvent.Tests" />
  </ItemGroup>
</Project>
