// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestReadXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:132,28
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestReadXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:142,16
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestWriteXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:148,30
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestWriteXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:151,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.RunProgramActionMethodSettingsValidationTest.TestValidatePath")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettingsValidation.cs:89,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestReadXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:132,28
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestReadXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:142,16
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestWriteXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:148,30
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.RunProgramActionMethodSettingsTest.TestWriteXml")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettings.cs:151,19
[assembly: SuppressMessage("CargoWiseOne", "CW1054:Do Not Use Hard Coded Paths", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.RunProgramActionMethodSettingsValidationTest.TestValidatePath")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/RunProgramActionMethodSettingsValidation.cs:89,19
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.DummyActionMethodWithOversizedGui.NewGuiControl")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/Testing/DummyActionMethodWithOversizedGui.cs:43,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.GridSelectionTest.TestGetSelectedRecordPKs")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/Selection/GridSelection.cs:83,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.DummyActionMethodWithLargeGui.NewGuiControl")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/Testing/DummyActionMethodWithLargeGui.cs:42,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.OperationalActionsModulePluginTest.TestGetButtonGridMenuItemsToAddCore")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/OperationalActionsModulePlugin.cs:136,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.DummyActionMethodWithOversizedGui.NewGuiControl")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/Testing/DummyActionMethodWithOversizedGui.cs:43,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.OperationalActionsModulePluginTest.TestGetButtonGridMenuItemsToAddCore")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/OperationalActionsModulePlugin.cs:136,4
[assembly: SuppressMessage("CargoWiseOne", "CW1017:Non DPI-aware code has been detected", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Services.OperationalActions.Module.Testing.DummyActionMethodWithLargeGui.NewGuiControl")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/Testing/DummyActionMethodWithLargeGui.cs:42,4
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Services.OperationalActions.Module.ShowEditNoteActionMethodApplicator.ShownPopup")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/ShowEditNoteActionMethodApplicator.cs:101,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Services.OperationalActions.Module.ShowEditNoteActionMethodApplicator.ShownPopup")] // Enterprise/Product/Core/OperationalActions/OperationalActions.Module/General/ShowEditNoteActionMethodApplicator.cs:101,23
