<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.UniversalCopy.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.UniversalCopy.Module.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.UniversalCopy.GUI\Enterprise.UniversalCopy.GUI.Winzor.csproj" />
    <ProjectReference Include="..\Enterprise.UniversalCopy.Module\Enterprise.UniversalCopy.Module.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>