// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.CusCAeMHHouseTest.TestShouldDefaultUniqueMessageReference")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/CusCAeMH/CusCAeMHHouse/CusCAeMHHouseTest.cs:128,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.CusCAeMHHouseTest.TestShouldDefaultUniqueMessageReference")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/CusCAeMH/CusCAeMHHouse/CusCAeMHHouseTest.cs:139,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.CAStateOfOriginCodeDescriptionPairProviderTest.TestIsReturningCorrectCollection")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/Enterprise_ReferenceFiles_CA/CACountryPreference/CAStateOfOriginCodeDescriptionPairProviderTest.cs:22,23
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.EDIReleaseMessageTest.TestMessageNumberFilledIn")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/EDIMessage/ImportMessages/EDIReleaseMessageTest.cs:180,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.EDIReleaseMessageTest.TestMessageNumberFilledIn")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/EDIMessage/ImportMessages/EDIReleaseMessageTest.cs:187,4
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.JobDeclarationTest.TestGetSentCADMessageCountInThisVersion")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/BusinessObject/JobDeclarationTest.cs:93,37
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.JobDeclarationTest.TestGetSentCADMessageCountInThisVersion")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/BusinessObject/JobDeclarationTest.cs:100,37
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.JobDeclarationTest.TestSentCADMessageCount")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/BusinessObject/JobDeclarationTest.cs:120,37
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.JobDeclarationTest.TestSentCADMessageCount")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/BusinessObject/JobDeclarationTest.cs:126,37
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.B3DeferInstructionTest.TestDifferentActionList")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/NonPersistentObjects/B3ScheduleInstructionTest.cs:580,32
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.CusCAeMHMasterTest.TestShouldDefaultUniqueMessageReference")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/CusCAeMH/CusCAeMHMaster/CusCAeMHMasterTest.cs:114,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.CusCAeMHMasterTest.TestShouldDefaultUniqueMessageReference")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/CusCAeMH/CusCAeMHMaster/CusCAeMHMasterTest.cs:124,3
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.TransactionNumberTest.TestCalculateTransactionNumber(System.Boolean)")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/Utilities/TransactionNumber/TransactionNumberTest.cs:436,5
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Business.Testing.TransactionNumberTest.TestCalculateTransactionNumber(System.Boolean)")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Business/JobDeclaration/Utilities/TransactionNumber/TransactionNumberTest.cs:457,6
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.Customs.CA.Registry.Testing.CACustomsDataRegistryTest.TestIsCAWHSUniversalXMLActive")] // Enterprise/Product/Operations/Customs/CA/Business.Test/Registry/CACustomsDataRegistryTest.cs:1591,100
