<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.ASYCUDA.Module.Testing</RootNamespace>
    <AssemblyName>Enterprise.Customs.ASYCUDA.Module.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gui\ASYCUDA.GUI.csproj" />
    <ProjectReference Include="..\Module\ASYCUDA.Module.csproj" />
  </ItemGroup>
</Project>