<Project>
  <ItemGroup>
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.Windows.UI" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.GUI" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\Warehouse.Cartonisation.Business.csproj" />
    <ProjectReference Include="..\Integration\Warehouse.Cartonisation.Integration.csproj" />
  </ItemGroup>
</Project>