//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Packing.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoPkgPackageSealValidation : ZValidation
	{
		protected AutoPkgPackageSealValidation(AutoPkgPackageSeal Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoPkgPackageSealValidation); }
		}

		/// <summary>
		/// Add more validation to the PkgPackageSeal's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoPkgPackageSealValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The PkgPackageSeal's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoPkgPackageSealValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region KPE_IsSealOK

		public void ValidateKPE_IsSealOK()
		{
			ZValidationInternals.Validate(Parent.KPE_IsSealOKInfo, GetKPE_IsSealOKValidationInvoker());
		}

		RunValidationInvoker GetKPE_IsSealOKValidationInvoker()
		{
			return delegate
			{
				CheckKPE_IsSealOK();
			};
		}

		protected virtual void CheckKPE_IsSealOK()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region KPE_KP_Package

		public void ValidateKPE_KP_Package()
		{
			ZValidationInternals.Validate(Parent.KPE_KP_PackageInfo, GetKPE_KP_PackageValidationInvoker());
		}

		RunValidationInvoker GetKPE_KP_PackageValidationInvoker()
		{
			return delegate
			{
				CheckKPE_KP_PackageIsNotEmpty();
				CheckKPE_KP_PackageIsValidZGuid();
				CheckKPE_KP_Package();
			};
		}

		protected virtual void CheckKPE_KP_PackageIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.KPE_KP_PackageInfo);
		}

		protected virtual void CheckKPE_KP_PackageIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.KPE_KP_PackageInfo);
		}

		protected virtual void CheckKPE_KP_Package()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region KPE_Seal

		public void ValidateKPE_Seal()
		{
			ZValidationInternals.Validate(Parent.KPE_SealInfo, GetKPE_SealValidationInvoker());
		}

		RunValidationInvoker GetKPE_SealValidationInvoker()
		{
			return delegate
			{
				CheckKPE_SealIsWesternEuropean();
				CheckKPE_Seal();
			};
		}

		protected virtual void CheckKPE_SealIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.KPE_SealInfo);
		}

		protected virtual void CheckKPE_Seal()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateKPE_IsSealOK();
				ValidateKPE_KP_Package();
				ValidateKPE_Seal();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoPkgPackageSeal Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
