<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Client.ELG</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Compile Update="Business\SageAccountingInterface\Registry\SageAccountCodeMappingRegistry\SageLedgerTypes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SageLedgerTypes.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Business\SageAccountingInterface\Registry\SageAccountCodeMappingRegistry\SageLedgerTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>SageLedgerTypes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Client.ELG</CustomToolNamespace>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Design" />
  </ItemGroup>
</Project>