<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(CWNetCoreWindowsTargetFramework)</TargetFramework>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions" />
    <Reference Include="WTG.ApplicationLogging.Abstractions" />
    <Reference Include="Moq" />
    <Reference Include="nunit.framework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CargoWise.Logging\CargoWise.Logging.csproj" />
  </ItemGroup>
</Project>
