<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Customs.GB.EMCS.Business</AssemblyName>
    <OutputPath>..\..\..\..\..\..\..\Bin</OutputPath>
    <RootNamespace>Enterprise.Customs.GB.EMCS.Business</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Customs.GB.MessageContracts" />
    <Reference Include="CargoWise.Customs.GB.MessageDefinitions" />
    <Reference Include="CargoWise.Customs.Shared.MessageContracts" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EventReference" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.EMCS.Business" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.UniversalDataBuss.DataObjects" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.XmlIO" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework) == 'net48'">
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Business\Enterprise.Customs.GB.Business.csproj" />
    <ProjectReference Include="..\Messaging\Enterprise.Customs.GB.EMCS.Messaging.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="CodeDescriptionPairLists\EMCSGBFunctionalErrorCodeList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBFunctionalErrorCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBGlobalConclusionOfReceiptList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBGlobalConclusionOfReceiptList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBInterruptionReasonList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBInterruptionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBManualClosureRejectionReasonList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBManualClosureRejectionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBNotificationType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBNotificationType.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBRejectionReasonList.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBRejectionReasonList.xml</DependentUpon>
    </Compile>
    <Compile Update="CodeDescriptionPairLists\EMCSGBReminderMessageType.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>EMCSGBReminderMessageType.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="CodeDescriptionPairLists\EMCSGBFunctionalErrorCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBFunctionalErrorCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBGlobalConclusionOfReceiptList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBGlobalConclusionOfReceiptList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBInterruptionReasonList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBInterruptionReasonList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBManualClosureRejectionReasonList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBManualClosureRejectionReasonList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBNotificationType.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBNotificationType.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBRejectionReasonList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBRejectionReasonList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
    <None Update="CodeDescriptionPairLists\EMCSGBReminderMessageType.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>EMCSGBReminderMessageType.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.Customs.GB.EMCS.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>