// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.OrderCsvImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/OrderCsvImportTaskTest.cs:17,16
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.CommercialInvoiceXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/CommercialInvoiceXmlImportTaskTest.cs:18,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.ConsolXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/ConsolXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.LocalCartageXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/LocalCartageXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.ContainerEventsXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/ContainerEventsXmlImportTaskTest.cs:17,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.ScheduleXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/ScheduleXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.ShipmentXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/ShipmentXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.EventXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/EventXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.ProductXmlImportTaskTest.TestNotificationEmailIsSendAfterProductImported")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/ProductXmlImportTaskTest.cs:34,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.WarehouseCartageXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/WarehouseCartageXmlImportTaskTest.cs:12,16
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.OrderXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/OrderXmlImportTaskTest.cs:17,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.WarehouseXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/WarehouseXmlImportTaskTest.cs:16,36
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.ServiceManager.Tasks.XMLAutomation.Testing.BookingXmlImportTaskTest.TestTaskDescription")] // Enterprise/Product/Core/ServiceManager/ServiceManager.Tasks/XMLAutomation.Test/ImportTask/BookingXmlImportTaskTest.cs:16,36
