<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AIRAED2UEvent\MapFiles\AIRAED2UEvent.xsl" />
    <None Remove="AIRAED2UEvent\MapFiles\AIRAEP2UEvent.xsl" />
    <None Remove="AIRAED2UEvent\TestFiles\Test1_input.xml" />
    <None Remove="AIRAED2UEvent\TestFiles\Test1_output_failure.xml" />
    <None Remove="AIRAED2UEvent\TestFiles\Test1_output_success.xml" />
    <None Remove="AIRAED2UEvent\TestFiles\Test1_output_success_modified.xml" />
    <None Remove="AIRAED2UEvent\TestFiles\Test2_input.xml" />
    <None Remove="AIRAED2UEvent\TestFiles\Test2_output.xml" />
    <None Remove="Hawking.BizTalk.CompiledXslt.Tests.csproj.vspscc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hawking.UnitTest.Tools" Version="1.0.0" />
    <PackageReference Include="Hawking.Xslt.ExtensionObjects" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="AIRAED2UEvent\MapFiles\AIRAED2UEvent.xsl" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test1_input.xml" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test1_output_failure.xml" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test1_output_success.xml" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test1_output_success_modified.xml" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test2_input.xml" />
    <EmbeddedResource Include="AIRAED2UEvent\TestFiles\Test2_output.xml" />
  </ItemGroup>

  <Import Project="..\.paket\Paket.targets" />
</Project>
