input {
  jdbc { 
    jdbc_connection_string => "jdbc:mysql://sydco-wbln-2:3306/Tracking"
    jdbc_user => "root"
    jdbc_password => "password"
    jdbc_driver_library => "D:\Apps\jdbc\drivers\mysql\mysql-connector-java-8.0.11.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    statement => "SELECT * FROM MessageEvents"
  }
}

filter {
  json {
    source => "[messageheaders]"
    skip_on_invalid_json => "true"
  }
  json {
    source => "[eventsourcereference]"
    skip_on_invalid_json => "true"
  }
  json {
    source => "[eventheaders]"
    skip_on_invalid_json => "true"
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "cs_tracking_messageevents_1"
    user => "logstash_internal"
    password => "3hubRock$"
  }
}