<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <OutputPath>..\..\..\..\..\..\..\Bin\</OutputPath>
    <RootNamespace>Enterprise.Customs.DE.Intrastat.Module.Testing</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\..\..\..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\Module\Enterprise.Customs.DE.Intrastat.Module.csproj" />
  </ItemGroup>
</Project>