<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>CargoWise.RefDbRepo.ComplianceListReferenceData.CmdLine</RootNamespace>
    <AssemblyName>CargoWise.RefDbRepo.ComplianceListReferenceData.CmdLine</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\..\..\Bin\UniversalXMLProducers\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Configurations>Debug;Release;UAT</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="CargoWise.RefDbRepo.ComplianceListReferenceData.CmdLine.config.json" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.RefDbRepo.XmlProducer.Common">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\Bin\UniversalXMLProducers\net8.0\CargoWise.RefDbRepo.XmlProducer.Common.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\CommonAssemblyInfo.cs" Link="CommonAssemblyInfo.cs" />
    <Content Include="CargoWise.RefDbRepo.ComplianceListReferenceData.CmdLine.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ComplianceListReferenceData.Business\ComplianceListReferenceData.Business.csproj" />
  </ItemGroup>
  <Import Project="..\..\..\.paket\Paket.Restore.targets" />
</Project>