<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net48</TargetFramework>
    <UseIISExpress>true</UseIISExpress>
    <AssemblyName>TestApplicationBasedOnZGlobal</AssemblyName>
    <Use64BitIISExpress />
    <IISExpressSSLPort>44382</IISExpressSSLPort>
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
    <UseGlobalApplicationHostFile />
    <OutputPath>..\..\..\..\Bin\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>false</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Shared.40">
      <HintPath>..\..\..\..\Bin\CargoWise.Shared.40.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.Business">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.Web.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GlobalBase">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GlobalBase.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Web.GUI">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.Web.GUI.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Http">
      <HintPath>..\..\..\..\Bin\System.Web.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Http.WebHost">
      <HintPath>..\..\..\..\Bin\System.Web.Http.WebHost.dll</HintPath>
    </Reference>
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Web.Debug.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
    <None Include="Web.Release.config">
      <DependentUpon>Web.config</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TestWebApplication.Common\TestWebApplication.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Default.aspx.cs">
      <DependentUpon>Default.aspx</DependentUpon>
    </Compile>
    <Compile Update="Error.aspx.cs">
      <DependentUpon>Error.aspx</DependentUpon>
    </Compile>
    <Compile Update="Error.aspx.designer.cs">
      <DependentUpon>Error.aspx</DependentUpon>
    </Compile>
    <Compile Update="Global.asax.cs">
      <DependentUpon>Global.asax</DependentUpon>
    </Compile>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
        <WebProjectProperties>
          <UseIIS>True</UseIIS>
          <AutoAssignPort>True</AutoAssignPort>
          <DevelopmentServerPort>7022</DevelopmentServerPort>
          <DevelopmentServerVPath>/</DevelopmentServerVPath>
          <IISUrl>https://localhost:44382/</IISUrl>
          <NTLMAuthentication>False</NTLMAuthentication>
          <UseCustomServer>False</UseCustomServer>
          <CustomServerUrl></CustomServerUrl>
          <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
        </WebProjectProperties>
      </FlavorProperties>
    </VisualStudio>
  </ProjectExtensions>
</Project>