//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Client.EDI.IdentityApplicationPermission.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoEdiIdentityApplicationPermissionValidation : ZValidation
	{
		protected AutoEdiIdentityApplicationPermissionValidation(AutoEdiIdentityApplicationPermission Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoEdiIdentityApplicationPermissionValidation); }
		}

		/// <summary>
		/// Add more validation to the EdiIdentityApplicationPermission's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoEdiIdentityApplicationPermissionValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The EdiIdentityApplicationPermission's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoEdiIdentityApplicationPermissionValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region IAP_IDA

		public void ValidateIAP_IDA()
		{
			ZValidationInternals.Validate(Parent.IAP_IDAInfo, GetIAP_IDAValidationInvoker());
		}

		RunValidationInvoker GetIAP_IDAValidationInvoker()
		{
			return delegate
			{
				CheckIAP_IDAIsNotEmpty();
				CheckIAP_IDAIsValidZGuid();
				CheckIAP_IDA();
			};
		}

		protected virtual void CheckIAP_IDAIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.IAP_IDAInfo);
		}

		protected virtual void CheckIAP_IDAIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.IAP_IDAInfo);
		}

		protected virtual void CheckIAP_IDA()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region IAP_IsActive

		public void ValidateIAP_IsActive()
		{
			ZValidationInternals.Validate(Parent.IAP_IsActiveInfo, GetIAP_IsActiveValidationInvoker());
		}

		RunValidationInvoker GetIAP_IsActiveValidationInvoker()
		{
			return delegate
			{
				CheckIAP_IsActive();
			};
		}

		protected virtual void CheckIAP_IsActive()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region IAP_Scope

		public void ValidateIAP_Scope()
		{
			ZValidationInternals.Validate(Parent.IAP_ScopeInfo, GetIAP_ScopeValidationInvoker());
		}

		RunValidationInvoker GetIAP_ScopeValidationInvoker()
		{
			return delegate
			{
				CheckIAP_ScopeIsWesternEuropean();
				CheckIAP_Scope();
			};
		}

		protected virtual void CheckIAP_ScopeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.IAP_ScopeInfo);
		}

		protected virtual void CheckIAP_Scope()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateIAP_IDA();
				ValidateIAP_IsActive();
				ValidateIAP_Scope();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoEdiIdentityApplicationPermission Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
