<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DbUpgrader.Data.AccAssetDepreciationBook.Testing</RootNamespace>
    <AssemblyName>Enterprise.DbUpgrader.Data.AccAssetDepreciationBook.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Database.TestFramework" />
    <Reference Include="Enterprise.DbUpgrader.Data.Shared" />
    <Reference Include="Enterprise.DbUpgrader.Shared.Testing" />
    <Reference Include="NUnitCore" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\AccAssetDepreciationBook\AccAssetDepreciationBook.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AccAssetDepreciationBook\AccAssetDepreciationBook.csproj" />
  </ItemGroup>
</Project>