<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<RootNamespace>Enterprise.Customs.JP.Manifest.GUI.Testing</RootNamespace>
	</PropertyGroup>
	<Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
	<ItemGroup>
		<ProjectReference Include="..\GUI\Enterprise.Customs.JP.Manifest.GUI.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="Enterprise.Environment" />
		<Reference Include="Enterprise.Security.Core" />
		<Reference Include="System.Collections.Immutable" />
	</ItemGroup>
</Project>