<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.BufferManagement.Business</RootNamespace>
    <AssemblyName>Enterprise.BufferManagement.Business</AssemblyName>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <Configurations>Debug;Release;DEBUGFAST</Configurations>
    <SuppressObsoleteWarnings>SYSLIB0051</SuppressObsoleteWarnings>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
    <CWUsesSqlClient>true</CWUsesSqlClient>
    <NoWarn>$(NoWarn);CS8073</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'DEBUGFAST|AnyCPU'">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CWGenerateXmlSerializationAssemblies>false</CWGenerateXmlSerializationAssemblies>
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Async" />
    <Reference Include="CargoWise.CalendarArithmetic" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.NetworkVisualisation.Business" />
    <Reference Include="CargoWise.NetworkVisualisation.Integration" />
    <Reference Include="CargoWise.PAVE.Common.Cache" />
    <Reference Include="CargoWise.PAVE.Common.DTO" />
    <Reference Include="CargoWise.PAVE.Common.Implementation" />
    <Reference Include="CargoWise.PAVE.Common.Interfaces" />
    <Reference Include="CargoWise.PAVE.Common.Model" />
    <Reference Include="CargoWise.Pipes" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Billing.Business" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.BufferManagement.Service.Shared" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.PAVE.MENT.Shared" />
    <Reference Include="Enterprise.BufferManagement.Service.Client" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.ProcessManagement.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.Scheduler.Business" />
    <Reference Include="Enterprise.Security" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TimeEngineScheduler.Integration" />
    <Reference Include="Enterprise.Workflow.Business" />
    <Reference Include="Enterprise.Workflow.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="Polly" />
    <Reference Include="QuikGraph" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Text.Json" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
    <Reference Include="System.Diagnostics.DiagnosticSource" />
    <Reference Include="System.Resources.Extensions" />
    <Reference Include="ServiceManager.Integration.Abstractions" />
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Registry\WorkflowManagementModes.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>WorkflowManagementModes.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\Controls\StatusButtonBehaviorOptionsList.cs">
      <DependentUpon>StatusButtonBehaviorOptionsList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Tags\TagRule\AddRemoveTagRulePreviewOptionsList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AddRemoveTagRulePreviewOptionsList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSectionChannel\ChannelAxisCodeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ChannelAxisCodeList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\CardTypeList.cs">
      <DependentUpon>CardTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="SystemSchematic\BMComponentAcceptabilityBand\ReleaseGroupFilteringOptions.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ReleaseGroupFilteringOptions.xml</DependentUpon>
    </Compile>
    <Compile Update="SystemSchematic\BMComponentAcceptabilityBand\SectionFilteringOptions.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SectionFilteringOptions.xml</DependentUpon>
    </Compile>
    <Compile Update="SystemSchematic\BMComponent\ViewComponentChangeLog\TransferTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TransferTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\AcceptabilityBands\AcceptabilityBandShowOnOptions.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AcceptabilityBandShowOnOptions.xml</DependentUpon>
    </Compile>
    <Compile Update="SystemSchematic\ConstrainedMode\ConstraintStatusList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ConstraintStatusList.xml</DependentUpon>
    </Compile>
    <Compile Update="Workflow\ProcessHeader\ProcessHeaderTypeList.cs">
      <DependentUpon>ProcessHeaderTypeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Workflow\WorkflowDeferralReasonsList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>WorkflowDeferralReasonsList.xml</DependentUpon>
    </Compile>
    <Compile Update="SystemSchematic\BMComponentAcceptabilityBand\AcceptabilityBandTypes1.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>AcceptabilityBandTypes.xml</DependentUpon>
    </Compile>
    <Compile Update="Tags\TagDefinition\TagUsageScopeList.cs">
      <DependentUpon>TagUsageScopeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Tags\TagDefinition\TagScopeList.cs">
      <DependentUpon>TagScopeList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Tags\TagRule\TagRuleActionTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TagRuleActionTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\PanelLayoutTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PanelLayoutTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\FlowDirectionList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>FlowDirectionList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\LastCellList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LastCellList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\TimeProgressionFieldList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TimeProgressionFieldList.xml</DependentUpon>
    </Compile>
    <Compile Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\TimeProgressionModeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TimeProgressionModeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\Controls\ControlAlignmentList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>ControlAlignmentList.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\Controls\StaticControlTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>StaticControlTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\CustomisationLine\PropertyTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PropertyTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\CustomisationLine\PropertySourceList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>PropertySourceList.xml</DependentUpon>
    </Compile>
    <Compile Update="CustomisedLayouts\CustomisedControlTypeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>CustomisedControlTypeList.xml</DependentUpon>
    </Compile>
    <Compile Update="Configuration\DateAcceptability\DateAcceptabilityList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DateAcceptabilityList.xml</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Workflow\ProcessHeader\ViewModel\WorkflowDeferalActionList.cs">
      <DependentUpon>WorkflowDeferalActionList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Workflow\ProcessHeader\WorkflowPrerequisiteStatusList.cs">
      <DependentUpon>WorkflowPrerequisiteStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Workflow\ProcessHeader\WorkflowStatusList.cs">
      <DependentUpon>WorkflowStatusList.xml</DependentUpon>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
    </Compile>
    <Compile Update="Workflow\WorkQueues\QueueStatusList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>QueueStatusList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Configuration\ReleaseGateMode\ReleaseGateModeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ReleaseGateModeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="CustomisedLayouts\Controls\StatusButtonBehaviorOptionsList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>StatusButtonBehaviorOptionsList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="Registry\WorkflowManagementModes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>WorkflowManagementModes.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Include="SystemSchematic\BMBufferTimespan\BMBufferTimespanResourceStrings.xml" />
    <None Update="SystemSchematic\BMComponentAcceptabilityBand\ReleaseGroupFilteringOptions.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
      <LastGenOutput>ReleaseGroupFilteringOptions.cs</LastGenOutput>
    </None>
    <None Update="SystemSchematic\BMComponentAcceptabilityBand\SectionFilteringOptions.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
      <LastGenOutput>SectionFilteringOptions.cs</LastGenOutput>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMReleaseSequence\BMReleaseSequenceResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMReleaseSequence\BMReleaseSequenceItemResourceStrings.xml" />
    <None Update="SystemSchematic\BMReleaseSequence\SequencedWorkflowsList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="SystemSchematic\ConstrainedMode\ConstraintStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ConstraintStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMComponent\ViewComponentChangeLog\ViewComponentChangeLogResourceStrings.xml" />
    <None Update="SystemSchematic\BMComponent\ViewComponentChangeLog\TransferTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransferTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMSystem\BMSystemWorkflowDeterminer\BMSystemWorkflowDeterminerResourceStrings.xml" />
    <EmbeddedResource Include="VisualBoards\BMBoardSection\AcceptabilityBands\AcceptabilityBandShowOnOptions.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AcceptabilityBandShowOnOptions.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Include="VisualBoards\BMBoardSectionChannel\BMBoardSectionChannelResourceStrings.xml" />
    <None Update="Tags\TagRule\AddRemoveTagRulePreviewOptionsList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AddRemoveTagRulePreviewOptionsList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="VisualBoards\BMBoardSectionChannel\ChannelAxisCodeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ChannelAxisCodeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\CardTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CardTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMSystem\BMSystemReleaseGroup\BMSystemReleaseGroupResourceStrings.xml" />
    <None Update="Workflow\ProcessHeader\ProcessHeaderTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ProcessHeaderTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="Workflow\ProcessTemplateReleaseGroupRule\ProcessTemplateReleaseGroupRuleResourceStrings.xml" />
    <EmbeddedResource Include="Workflow\ProcessTemplateReleaseGroupRuleMapping\ProcessTemplateReleaseGroupRuleMappingResourceStrings.xml" />
    <None Update="Workflow\WorkflowDeferralReasonsList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>WorkflowDeferralReasonsList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="Workflow\WorkQueues\QueueStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>QueueStatusList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="CustomisedLayouts\BMControlCustomisationLink\BMControlCustomisationLinkResourceStrings.xml" />
    <None Update="Tags\TagDefinition\TagScopeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TagScopeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="Tags\TagDefinition\TagUsageScopeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TagUsageScopeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="VisualBoards\BMBoardSection\BMBoardSectionConfiguration\PanelLayoutTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PanelLayoutTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="Workflow\ProcessHeader\WorkflowPrerequisiteStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
      <LastGenOutput>WorkflowPrerequisiteStatusList.cs</LastGenOutput>
    </None>
    <None Update="Workflow\ProcessHeader\WorkflowStatusList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
      <LastGenOutput>WorkflowStatusList.cs</LastGenOutput>
    </None>
    <None Update="SystemSchematic\BMComponentAcceptabilityBand\AcceptabilityBandTypes.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>AcceptabilityBandTypes1.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Tags\TagRule\TagRuleResourceStrings.xml" />
    <None Update="Tags\TagRule\TagRuleActionTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TagRuleActionTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="Workflow\ProcessHeader\ViewModel\WorkflowDeferalActionList.xml">
      <LastGenOutput>WorkflowDeferalActionList.cs</LastGenOutput>
    </None>
    <EmbeddedResource Include="VisualBoards\BMBoardSection\BMBoardSectionResourceStrings.xml" />
    <EmbeddedResource Include="VisualBoards\BMBoardSectionAdditionalComponent\BMBoardSectionAdditionalComponentResourceStrings.xml" />
    <EmbeddedResource Include="VisualBoards\BMBoard\BMBoardResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMComponentLink\BMComponentLinkResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMComponent\BMComponentResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMSystem\BMSystemResourceStrings.xml" />
    <EmbeddedResource Include="Workflow\ProcessHeaderLink\ProcessHeaderLinkResourceStrings.xml" />
    <EmbeddedResource Include="Workflow\ProcessHeader\ProcessHeaderResourceStrings.xml" />
    <EmbeddedResource Include="VisualBoards\BMBoardSlideshow\BMBoardSlideshowResourceStrings.xml" />
    <EmbeddedResource Include="VisualBoards\BMBoardSlideshowPivot\BMBoardSlideshowPivotResourceStrings.xml" />
    <EmbeddedResource Include="CustomisedLayouts\BMControlCustomisation\BMControlCustomisationResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMComponentReleaseGroupLink\BMComponentReleaseGroupLinkResourceStrings.xml" />
    <EmbeddedResource Include="SystemSchematic\BMComponentAcceptabilityBand\BMComponentAcceptabilityBandResourceStrings.xml" />
    <None Update="CustomisedLayouts\Controls\ControlAlignmentList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>ControlAlignmentList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="CustomisedLayouts\Controls\StaticControlTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>StaticControlTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="CustomisedLayouts\CustomisationLine\PropertyTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PropertyTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="CustomisedLayouts\CustomisationLine\PropertySourceList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>PropertySourceList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <None Update="CustomisedLayouts\CustomisedControlTypeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>CustomisedControlTypeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMZoneCapacityMultiplier\BMZoneCapacityMultiplierResourceStrings.xml" />
    <None Update="Configuration\DateAcceptability\DateAcceptabilityList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DateAcceptabilityList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.BufferManagement.Business</CustomToolNamespace>
    </None>
    <EmbeddedResource Include="SystemSchematic\BMComponentResourceLink\BMComponentResourceLinkResourceStrings.xml" />
    <EmbeddedResource Include="Tags\TagDefinition\TagDefinitionResourceStrings.xml" />
    <EmbeddedResource Include="Tags\TagMagnitude\TagMagnitudeResourceStrings.xml" />
    <EmbeddedResource Include="Tags\TagLink\TagLinkResourceStrings.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VisualBoards\VisualBoards.Business\VisualBoards.Business.csproj" />
    <ProjectReference Include="..\Integration\BufferManagement.Integration.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Service References\" />
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>