using System.Diagnostics.CodeAnalysis;
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "WOW", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_Client_WOW_OutstandingOrdersReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_Client_WOW_OutstandingOrdersReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientCheckDeclarationJobService")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientDecImpedimentMonitorReportHeader")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientGetAllClientVisibleNotes")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientGetEntryNumberList")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientGetJobServiceFromRegistry")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientGetLatestStmaLog")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientReportDecImpedimentMonitor")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientReportOrderCurrencyRequirement")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Stma", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_ClientGetLatestStmaLog")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "SignOff", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Create_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "WOW", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_Client_WOW_OutstandingOrdersReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_Client_WOW_OutstandingOrdersReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientCheckDeclarationJobService")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientDecImpedimentMonitorReportHeader")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientGetAllClientVisibleNotes")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientGetEntryNumberList")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientGetJobServiceFromRegistry")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Stma", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientGetLatestStmaLog")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientGetLatestStmaLog")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientReportDecImpedimentMonitor")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_ClientReportOrderCurrencyRequirement")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerTracking")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientContainerVolume")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientDeclarationFreightPayments")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientInvoicePaymentNotify")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientLandedCostingAccounting")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderBuyersTripReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderContainersInYard")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrderInvoiceDiscrepancy")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "SignOff", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOrdersSignOff")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vw", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1707:IdentifiersShouldNotContainUnderscores", Scope = "member", Target = "Enterprise.Client.ClientOverride.#Drop_vw_Report_ClientOverseasConsolidatorOrderReport")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Enterprise.Client.BWD.Testing.WowTestHelper.#GetPopulatedDeclaration(Enterprise.ZArchitecture.BusinessObjectFactory)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SubType", Scope = "member", Target = "Enterprise.Client.Wow.WowMessageSendingValidation.#RegisterThisSubTypeOverride()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SubType", Scope = "member", Target = "Enterprise.Client.Wow.WowMessageSendingValidation.#UnregisterThisSubTypeOverride()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Enterprise.Client.Wow.WowMessageSendingValidation+WowMessageSendingValidationTest")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tni", Scope = "member", Target = "Enterprise.Client.Wow.WowMessageSendingValidation+WowMessageSendingValidationTest.#TestNoTniNoContinue()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tni", Scope = "member", Target = "Enterprise.Client.Wow.WowMessageSendingValidation+WowMessageSendingValidationTest.#TestNoTniWithContinue()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Tni", Scope = "member", Target = "Enterprise.Client.Wow.WowMessageSendingValidation+WowMessageSendingValidationTest.#TestValidTniNoMessage()")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1405:ComVisibleTypeBaseTypesShouldBeComVisible", Scope = "type", Target = "Enterprise.Client.Wow.Testing.WOWOutstandingOrdersReportTemplateTest")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "WOW", Scope = "type", Target = "Enterprise.Client.Wow.Testing.WOWOutstandingOrdersReportTemplateTest")]
[assembly: SuppressMessage("Microsoft.Interoperability", "CA1405:ComVisibleTypeBaseTypesShouldBeComVisible", Scope = "type", Target = "Enterprise.Client.Wow.Testing.WOWOutstandingOrdersReportTest")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "WOW", Scope = "type", Target = "Enterprise.Client.Wow.Testing.WOWOutstandingOrdersReportTest")]
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WoolworthsOrder.UpdateOrderStatusesForReport(Enterprise.DocumentEngine.Report)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\Business\WoolworthsOrder.cs:96:26
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Client.Wow.WoolworthsJobDocsAndCartageValidation.Declaration")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\Business\WoolworthsJobDocsAndCartageValidation.cs:21:11
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WoolworthsJobExchangeRate.GetExchangeRate(CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\Business\WoolworthsJobExchangeRate.cs:20:33
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.OrderCsvRecord.GetOrCreateOrder(CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Orders\OrderCsvRecord.cs:107:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.OrderCsvRecord.GetOrCreateOrder(CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Orders\OrderCsvRecord.cs:110:13
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.OrderCsvRecord.GetOrCreateOrder(CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Orders\OrderCsvRecord.cs:112:35
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WoolworthsOrder.UpdateOrderStatusesForReport(Enterprise.DocumentEngine.Report)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\Business\WoolworthsOrder.cs:115:28
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.OrderLineCsvRecord.GetOrCreateOrderLine(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.ComponentModel.INotifications)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Orders\OrderLineCsvRecord.cs:121:31
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.ProductCsvRecord.UpdateOrAddPart(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.ComponentModel.INotifications)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Parts\ProductsCsvRecord.cs:105:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.OrderLineCsvRecord.GetNextOrderLineNo(CargoWise.EntityFramework.BusinessObjectFactory,CargoWise.Types.ZGuid)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\DataImportExport\Orders\OrderLineCsvRecord.cs:141:24
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WowDataRegistry.IsUnmatchedDataItemsAccountValid(CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\WowDataRegistry.cs:51:19
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WowDataRegistry.LoadUnmatchDataItemsAccount(CargoWise.EntityFramework.BusinessObjectFactory)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\WowDataRegistry.cs:57:22
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WowDocDeclaration.FindJobCharge(CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DocWrappers\WowDocDeclaration.cs:201:57
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.WowDocDeclaration.FindJobCharge(CargoWise.Types.ZString)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DocWrappers\WowDocDeclaration.cs:207:33
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.Client.Wow.ContainerCustomsDeclGenerator.UpdateInvoiceFromOrderContainer(Enterprise.Client.Wow.WoolworthsOrder,Enterprise.Client.Wow.WoolworthsOrderLine,Enterprise.Freight.Forwarding.Orders.Business.OrderLineDelivery,Enterprise.Freight.Forwarding.Orders.Business.OrderLineDeliverContainer,Enterprise.Customs.AU.Declaration.Business.JobComInvoiceHeader)")] // C:\git\wtg\CargoWise\Dev\Enterprise\ClientExtensions\WOW\ZClientWOW\ZClientWOW\DataManipulation\ContainerCustomsDeclGeneration\ContainerCustomsDeclGenerator.cs:457:32
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.OrderCsvRecord.OrderPropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/Orders/OrderCsvRecord.cs:83,36
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.DeliveryCsvRecord.DeliveryPropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/Orders/OrderDeliveryCsvRecord.cs:70,36
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.ContainerManifestCsvLine.ContainerPropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/ContainerManifest/ContainerManifestCsvLine.cs:118,36
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.OrderLineCsvRecord.OrderLinePropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/Orders/OrderLineCsvRecord.cs:83,36
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.ProductCsvRecord.PartPropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/Parts/ProductsCsvRecord.cs:56,36
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.Client.Wow.ProductCsvRecord.PartLocationPropertyMappings")] // Enterprise/ClientExtensions/WOW/ZClientWOW/ZClientWOW/DataManipulation/DataImportExport/Parts/ProductsCsvRecord.cs:75,36
