<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
    <RootNamespace>Enterprise.Customs.US.InBond.GUI.Testing</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="WTG.SecurityRights" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GUI\Enterprise.Customs.US.InBond.GUI.csproj" />
  </ItemGroup>
</Project>