<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DbUpgrader.Data.RefLocalLanguage</RootNamespace>
    <AssemblyName>Enterprise.DbUpgrader.Data.RefLocalLanguage</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="Enterprise.DbUpgrader.Data.Shared" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="RefLocalLanguage.xml" />
  </ItemGroup>
</Project>