<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Framework\eServices.Configuration.Framework.csproj" />
    <ProjectReference Include="..\Helper\eServices.Configuration.Helper.csproj" />
    <ProjectReference Include="..\Schemas\eServices.Configuration.Schemas.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas\TestFiles\Test2_Deserialization.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas\TestFiles\Test1_Serialization.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Schemas\Configuration.xsd">
      <Link>Schemas\TestFiles\Configuration.xsd</Link>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schemas\TestFiles\Test3_Deserialization_EmptyPassword.xml">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CargoWise.eServices.Encryption.Client.Encryptor" />
    <PackageReference Include="CompareNETObjects" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Moq.EntityFrameworkCore" />
  </ItemGroup>
</Project>