<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ResourceStrings.Business.Test</RootNamespace>
    <AssemblyName>Enterprise.ResourceStrings.Business.Test</AssemblyName>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Reflection" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="BuildTools" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="Enterprise.eHubMessaging.Business" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.Licensing.Core" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings.Cache.Test" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="System.Runtime.Caching" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Mono.Cecil" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="WTG.SpellCheck" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
    <Reference Include="WTG.TranslationMemoryExchange" />
  </ItemGroup>
  <ItemGroup Condition="'$(IsNetFrameworkTargetFramework)' == 'true'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Business\ResourceStrings.Business.csproj" />
  </ItemGroup>
</Project>