// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.FaxRouter.FaxDataModule.GetOverDueAckFaxes(System.Boolean,System.Int32,System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\FaxDataModule.cs:541:80
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.FaxRouter.EDIFaxDBJobDataLine.fReceivedDateTime")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\EDIFaxDBJobDataLine.cs:79:31
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.FaxRouter.FaxAcknowledgementDataLine.fAckReceivedDateTime")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\FaxAcknowledgementDataLine.cs:39:34
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.FaxRouter.LogFile.AddLog(System.String,System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\LogFile.cs:20:26
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.FaxRouter.EventLogging.Testing.EventLogTest.InsertTestEmailToFaxMailDBItem")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\EventLog.cs:166:60
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.FaxRouter.LogFile.LogFilename")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\LogFile.cs:67:19
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.FaxRouter.Test.MailDataModuleTest.InsertTestFaxAcknowledgementsMailDBItems(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\MailDataModule.cs:288:61
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.FaxRouter.Test.MailDataModuleTest.InsertTestEmailToFaxMailDBItems(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\FaxRouter\Common\MailDataModule.cs:268:61
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.BaseDataModule.CheckedIndex")] // Enterprise/Product/Core/FaxRouter/Common/BaseDataModule.cs:33,14
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDI_ACK_SMTP_SERVER")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:19,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_HANDLER_EMAIL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:20,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_GATEWAY_SYSID")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:14,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.NOREPLY_EMAIL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:16,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_ACK_RETURN_EMAIL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:21,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDI_FAXJOB_SMTP_SERVER")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:18,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.ENTERPRISE_DATABASE_NAME")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:12,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_ADMINISTRATOR_EMAIL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:17,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_GATEWAY_TEMP_FILE_DIRECTORY")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:23,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_ACK_SENDER")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:22,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDI_SEND_FAX_ACK_EMAIL_ON_FAILURE")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:26,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDI_SEND_FAX_ACK_EMAIL_ON_SUCCESS")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:25,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDI_SEND_FAX_ACK_EMAIL_ON_OVERDUE")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:27,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_ACK_IS_HUMAN")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:28,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.IS_FAX_ACK_ON")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:29,21
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_GATEWAY_POLLING_INTERVAL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:30,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.EDIFAXDB_CONNECTION")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:35,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_VIEWER_PAGE_HIEGHT")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:31,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.MAILDB_CONNECTION")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:33,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_VIEWER_PAGE_WIDTH")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:32,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.CHARGE_CODE_CONTROL_FILE_FIELD_NAME")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:37,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.ACK_FORMAT")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:38,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.ENTERPRISE_SERVER_NAME")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:13,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_GATEWAY_LOG")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:36,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.BLACKLIST")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:11,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.DAILY_REPORT_DISCREPANCY_THRESHOLD")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:10,20
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.Constants.FAX_GATEWAY_EMAIL")] // Enterprise/Product/Core/FaxRouter/Common/Constants.cs:15,23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.FaxRouter.LogFile.fLogFilename")] // Enterprise/Product/Core/FaxRouter/Common/LogFile.cs:115,16
