<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.ProductionRules.GUI</RootNamespace>
    <AssemblyName>Enterprise.ProductionRules.GUI</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>