//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from DataSetUpdaterScriptGenerator.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CargoWise.RefDbRepo.RemoteDbManager
{
	public partial class RefAccessorialUpdaterInfo_1 : IUpdaterScriptInfo
	{
		public string DataSetName => "RefAccessorial";

		public Dictionary<string, string> PrepareTemporaryTablesScripts => new Dictionary<string, string>
		{
{ "#TempRefAccessorial", @"
IF OBJECT_ID('tempdb..#TempRefAccessorial') IS NOT NULL
BEGIN
	DROP TABLE #TempRefAccessorial
END
	SELECT ASI_PK AS ASI_PK,ASI_Code AS ASI_Code,ASI_Description AS ASI_Description,CAST (0 AS BIT) AS Deleted INTO #TempRefAccessorial FROM RefAccessorial WHERE 1 =0
	CREATE CLUSTERED INDEX PK_#TempRefAccessorial ON #TempRefAccessorial (ASI_PK)
" }
		};

		public string MergeScript => @"
DECLARE @dummy bit = 0

DECLARE @RefAccessorial_DELETE TABLE
(
	ASI_PK uniqueidentifier INDEX _@RefAccessorial_DELETE_PK CLUSTERED
)



INSERT INTO @RefAccessorial_DELETE
SELECT t.ASI_PK
FROM RefAccessorial AS t
JOIN #TempRefAccessorial AS s ON (((t.ASI_Code = s.ASI_Code))) ;




DELETE FROM RefAccessorial
WHERE ASI_PK IN (SELECT ASI_PK FROM @RefAccessorial_DELETE);


INSERT RefAccessorial (ASI_PK,ASI_Code,ASI_Description)
SELECT ASI_PK,ASI_Code,ASI_Description FROM #TempRefAccessorial
WHERE Deleted = 0;


TRUNCATE TABLE #TempRefAccessorial


";

		public string[] Prerequisites => new string[0];
		public int UpdaterVersion => 1;
	}
}
