//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from DataSetUpdaterScriptGenerator.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace CargoWise.RefDbRepo.RemoteDbManager
{
	public partial class RefUNLOCOUpdaterInfo_1 : IUpdaterScriptInfo
	{
		public string DataSetName => "RefUNLOCO";

		public Dictionary<string, string> PrepareTemporaryTablesScripts => new Dictionary<string, string>
		{
{ "#TempRefUNLOCO", @"
IF OBJECT_ID('tempdb..#TempRefUNLOCO') IS NOT NULL
BEGIN
	DROP TABLE #TempRefUNLOCO
END
	SELECT RL_PK AS RL_PK,RL_Code AS RL_Code,CAST (0 AS BIT) AS Deleted INTO #TempRefUNLOCO FROM RefUNLOCO WHERE 1 =0
	CREATE CLUSTERED INDEX PK_#TempRefUNLOCO ON #TempRefUNLOCO (RL_PK)
" },
{ "#TempRefUNLOCOUtcOffset", @"
IF OBJECT_ID('tempdb..#TempRefUNLOCOUtcOffset') IS NOT NULL
BEGIN
	DROP TABLE #TempRefUNLOCOUtcOffset
END
	SELECT RLO_PK AS RLO_PK,RLO_RL_NKCode AS RLO_RL_NKCode,RLO_StartTimeUtc AS RLO_StartTimeUtc,RLO_EndTimeUtc AS RLO_EndTimeUtc,RLO_OffsetMinutesFromUtc AS RLO_OffsetMinutesFromUtc INTO #TempRefUNLOCOUtcOffset FROM RefUNLOCOUtcOffset WHERE 1 =0
	CREATE CLUSTERED INDEX PK_#TempRefUNLOCOUtcOffset ON #TempRefUNLOCOUtcOffset (RLO_PK)
" }
		};

		public string MergeScript => @"
DECLARE @dummy bit = 0

DECLARE @RefUNLOCO_DELETE TABLE
(
	RL_PK uniqueidentifier INDEX _@RefUNLOCO_DELETE_PK CLUSTERED,
	RL_Code varchar(50)
)


DECLARE @RefUNLOCOUtcOffset_DELETE TABLE
(
	RLO_PK uniqueidentifier INDEX _@RefUNLOCOUtcOffset_DELETE_PK CLUSTERED
)



DECLARE @ParentPKChangesTable TABLE
(
	TargetPK uniqueidentifier,
	SourcePK uniqueidentifier INDEX _@ParentPKChangesTable_SourcePK CLUSTERED
)
MERGE RefUNLOCO AS t
USING #TempRefUNLOCO AS s
ON ((t.RL_Code = s.RL_Code))
WHEN MATCHED AND s.Deleted = 0 THEN
	UPDATE SET RL_Code = s.RL_Code
WHEN NOT MATCHED AND s.Deleted = 0 THEN
	INSERT (RL_PK, RL_Code) VALUES (s.RL_PK, s.RL_Code)
OUTPUT inserted.RL_PK, s.RL_PK INTO @ParentPKChangesTable
;


;WITH TempParentTableCTE AS
(
	SELECT * FROM #TempRefUNLOCO WHERE Deleted = 0
),
TempChilTableCTE AS
(
	SELECT * FROM #TempRefUNLOCOUtcOffset
)

INSERT INTO @RefUNLOCOUtcOffset_DELETE
SELECT RLO_PK
FROM RefUNLOCOUtcOffset c
JOIN TempParentTableCTE p ON c.RLO_RL_NKCode = p.RL_Code
WHERE 1=1;

INSERT INTO @RefUNLOCO_DELETE
SELECT t.RL_PK, t.RL_Code
FROM RefUNLOCO AS t
JOIN #TempRefUNLOCO AS s ON ((((t.RL_Code = s.RL_Code))) AND Deleted = 1) ;




INSERT INTO @RefUNLOCOUtcOffset_DELETE
SELECT RLO_PK
FROM RefUNLOCOUtcOffset
JOIN @RefUNLOCO_DELETE ON RLO_RL_NKCode = RL_Code
WHERE 1=1;





DELETE FROM RefUNLOCOUtcOffset
WHERE RLO_PK IN (SELECT RLO_PK FROM @RefUNLOCOUtcOffset_DELETE);



DELETE FROM RefUNLOCO
WHERE RL_PK IN (SELECT RL_PK FROM @RefUNLOCO_DELETE);


INSERT INTO RefUNLOCOUtcOffset (RLO_PK,RLO_RL_NKCode,RLO_StartTimeUtc,RLO_EndTimeUtc,RLO_OffsetMinutesFromUtc)
SELECT RLO_PK,RLO_RL_NKCode,RLO_StartTimeUtc,RLO_EndTimeUtc,RLO_OffsetMinutesFromUtc FROM #TempRefUNLOCOUtcOffset;

DELETE FROM RefUNLOCOUtcOffset
WHERE RLO_StartTimeUtc < DATEADD(MONTH, -24, GETUTCDATE())
OR RLO_EndTimeUtc < DATEADD(MONTH, -24, GETUTCDATE());

TRUNCATE TABLE #TempRefUNLOCO
TRUNCATE TABLE #TempRefUNLOCOUtcOffset


";

		public string[] Prerequisites => new string[0];
		public int UpdaterVersion => 1;
	}
}
