<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreWindowsTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.Customs.IL.Manifest.Module.Testing</RootNamespace>
    <AssemblyName>Enterprise.Customs.IL.Manifest.Module.Test</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <EmbeddedResource Include="TestFiles\Manifest_1171.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Module\Enterprise.Customs.IL.Manifest.Module.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Moq" />
  </ItemGroup>
</Project>