<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <RootNamespace>CargoWise.NetworkVisualisation.GUI</RootNamespace>
    <AssemblyName>CargoWise.NetworkVisualisation.GUI</AssemblyName>
    <NoWarn>$(NoWarn);1701;1702;NU1702;NU1504;RZ9991;</NoWarn>
    <UseLegacyRsa>false</UseLegacyRsa>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Controller\NetworkEntityController.cs" Link="Controller/NetworkEntityController.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Controls\DiagramAreaUserControlViewModel.cs" Link="Controls/DiagramAreaUserControlViewModel.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\NetworkUserControlViewModel.cs" Link="Controls/NetworkUserControlViewModel.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Controls\ConnectionBadIndicator.cs" Link="Controls\ConnectionBadIndicator.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Controls\ConnectionOkIndicator.cs" Link="Controls\ConnectionOkIndicator.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Ribbon\**" LinkBase="Ribbon" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\NetworkActions\**" LinkBase="NetworkActions" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Search\**" LinkBase="Search" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Constants.cs" Link="Constants/Constants.cs" />
    <Compile Include="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Utilities\TooltipHelper.cs" Link="Utils\TooltipHelper.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Ribbon\DefaultViewModel\SourceIcons\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Ribbon\DefaultViewModel\DefaultNetworkRibbonResources.xaml" />
    <Compile Remove="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Ribbon\NetworkRibbonControl.xaml" />
    <Compile Remove="..\..\Common\Product\NetworkVisualisation\NetworkVisualisation.GUI\Ribbon\NetworkRibbonControl.xaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Architecture\Windows.UI\CargoWise.Windows.UI.Winzor.csproj" />
    <ProjectReference Include="..\..\Enterprise\Architecture\GUI\Enterprise.ZArchitecture.GUI\Enterprise.ZArchitecture.GUI.Winzor.csproj" />
    <ProjectReference Include="..\BArchitecture.GUI\WinzorFramework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.Blazor.Client.Integration" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.NetworkVisualisation.Business" />
    <Reference Include="CargoWise.NetworkVisualisation.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.PAVE.Common.Interfaces" />
    <Reference Include="Enterprise.BufferManagement.NetworkVisualisation.Business" /> 
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="WTG.Z.Blazor.Diagrams" />
  </ItemGroup>
</Project>