<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(Temp_CWNetCoreTargetFramework)</TargetFrameworks>
    <AssemblyName>Enterprise.Customs.DutyCalculator</AssemblyName>
    <RootNamespace>Enterprise.Customs.DutyCalculator</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
  <ItemGroup>
    <ProjectReference Include="..\Business\Enterprise.Customs.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Antlr4.Runtime" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DeniedPartyScreening.Common" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
</Project>