<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ApplicationIcon>App.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <PostBuildEvent>if exist $(OutDir)$(TargetFileName).config del $(OutDir)$(TargetFileName).config</PostBuildEvent>
    <OutputPath>..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ResourceStrings.Cache">
      <HintPath>..\..\..\..\Bin\CargoWise.ResourceStrings.Cache.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Environment">
      <HintPath>..\..\..\..\Bin\Enterprise.Environment.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Initialisation">
      <HintPath>..\..\..\..\Bin\Enterprise.Initialisation.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.GUI.Test">
      <HintPath>..\..\..\..\Bin\Enterprise.ZArchitecture.GUI.Test.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\Bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="App.ico" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="TestRunnerInAnotherProcess.cs" />
  </ItemGroup>
</Project>