//------------------------------------------------------------------------------
// <auto-generated>
//     This file was auto-generated from EMCSGBInterruptionReasonList.xml.
//     Do not edit this file, because changes will be lost next time it is generated.
//     If the input filename ends with 'Base', this class will be generated as
//     an abstract class so you can subclass it to add extra functionality.
//     All sublist names will be trimmed. So do not worry about spaces after commas.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using Enterprise.ZArchitecture.Core;
using Resources;

namespace Enterprise.Customs.GB.EMCS.Business
{
	[GeneratedCode("CodeDescriptionPairListGenerator", "1.0")]
	public partial class EMCSGBInterruptionReasonList : CodeDescriptionPairList
	{
		[AutoGeneratedSourceCode]
		public class Codes
		{
			public const string Item0 = "0";
			public const string Item1 = "1";
			public const string Item2 = "2";
			public const string Item3 = "3";
			public const string Item4 = "4";
		}

		[AutoGeneratedSourceCode]
		public class Descriptions
		{
			public const string Item0 = "Other";
			public const string Item1 = "Fraud suspected";
			public const string Item2 = "Goods destroyed";
			public const string Item3 = "Goods lost or stolen";
			public const string Item4 = "Interruption requested at control";
		}

		public EMCSGBInterruptionReasonList()
		{
			AddPair(Codes.Item0, Descriptions.Item0);
			AddPair(Codes.Item1, Descriptions.Item1);
			AddPair(Codes.Item2, Descriptions.Item2);
			AddPair(Codes.Item3, Descriptions.Item3);
			AddPair(Codes.Item4, Descriptions.Item4);
		}
	}
}
