<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <BaseOutputPath>..\..\..\Bin\FRCustoms</BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.eHub.Adapter">
      <HintPath>..\..\..\Bin\CargoWise.eHub.Adapter.dll</HintPath>
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="CargoWise.eHub.Common">
      <HintPath>..\..\..\Bin\CargoWise.eHub.Common.dll</HintPath>
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\Bin\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Renci.SshNet">
      <HintPath>..\..\..\Bin\Renci.SshNet.dll</HintPath>
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.Configuration">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.Configuration.Install">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.ServiceModel">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.Web">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Microsoft.CSharp">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="System.Net.Http">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Enterprise.Customs.FR.TransportSvc.Utilities\Enterprise.Customs.FR.TransportSvc.Utilities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Message\Templates\UniversalEvent.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\APPLUSResponse.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\DeltaGResponse.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\DeltaIEResponse.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\DeltaTPhase5Response.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\DeltaTResponse.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformAPPLUS.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformCIN745.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformCIN750.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformCIN755.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformDeltaG.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformDeltaIE.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformDeltaT.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformDeltaTPhase5.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformECS.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\MessagePlateformPNTS.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Message\Transformation\PNTSResponse.xslt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Data">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Drawing">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression.FileSystem">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Numerics">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Runtime.Serialization">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Xml.Linq">
      <Private>True</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
  </ItemGroup>
</Project>