using System.Diagnostics.CodeAnalysis;
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Enterprise.DocumentEngine.RuntimeOptions.Testing.ColumnHeading.#.ctor(System.String,System.String,System.String,System.Int32,System.Int32,System.Int32,System.Boolean,System.String)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.DocumentEngine.Service.DeliveryInstructionDetail.#Recipients")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.DocumentEngine.Service.DeliveryInstructionDetail.#Documents")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Enterprise.DocumentEngine.Service.DeliveryInstructionDetail.#Printers")]
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~F:Enterprise.DocumentEngine.FlexCelInterface.Testing.ExcelInterfaceTest.ExcelInterfaceWithDelayedProcess.secondsDelay")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\FlexCelInterface\ExcelInterface.cs:3712:7
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.FlexCelInterface.Testing.ExcelInterfaceTest.ExcelInterfaceWithDelayedProcess.#ctor(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\FlexCelInterface\ExcelInterface.cs:3707:43
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.RuntimeOptions.Testing.DynamicOrderHeaderLineStatusCodeDescriptionPairProviderTest.GetClientListBlob(System.String,System.String,System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\RuntimeOptions\MultipleChoice\CodeDescriptionPairListProviders\DynamicOrderLineStatusCodeDescriptionPairProvider.cs:152:3
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.RuntimeOptions.Testing.DynamicOrderHeaderLineStatusCodeDescriptionPairProviderTest.GetClientListBlob(System.String,System.String,System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\RuntimeOptions\MultipleChoice\CodeDescriptionPairListProviders\DynamicOrderLineStatusCodeDescriptionPairProvider.cs:152:22
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.RuntimeOptions.Testing.DynamicOrderHeaderStatusCodeDescriptionPairProviderTest.GetClientListBlob(System.String,System.String,System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\RuntimeOptions\MultipleChoice\CodeDescriptionPairListProviders\DynamicOrderHeaderStatusCodeDescriptionPairProvider.cs:149:3
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.RuntimeOptions.Testing.DynamicOrderHeaderStatusCodeDescriptionPairProviderTest.GetClientListBlob(System.String,System.String,System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\RuntimeOptions\MultipleChoice\CodeDescriptionPairListProviders\DynamicOrderHeaderStatusCodeDescriptionPairProvider.cs:149:22
[assembly: SuppressMessage("CargoWiseOne", "CW1122:Do Not Use DateTime Parse Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TextMacroProcessorTest.TestReplaceMacroNowHasNewValueEveryCall")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Core\TextMacroProcessor.cs:380:15
[assembly: SuppressMessage("CargoWiseOne", "CW1122:Do Not Use DateTime Parse Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TextMacroProcessorTest.TestReplaceMacroNowHasNewValueEveryCall")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Core\TextMacroProcessor.cs:382:15
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Baseline WI00585389", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TemplateTest.TestDocumentTemplatesHaveSameTableSchemaAsInDatabase")] // Enterprise/Product/Documents/DocumentEngine/Testing/TemplateTest.cs:376,4
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.UtilityClasses.ClientDocumentsXMLUpdater.WriteTemplateToXml(System.String,System.String)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Testing\UtilityClasses\ClientDocumentsXMLUpdater.cs:75:10
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TemplateTest.TestClientSpecificMenuItemsForOldUsageOf_GlbCompany_CountryCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Testing\TemplateTest.cs:63:12
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TemplateTest.GetAllClientTemplates(System.Boolean,System.Boolean)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Testing\TemplateTest.cs:2749:12
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.TemplateTest.GetClientFilesOnly")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Testing\TemplateTest.cs:3040:11
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.Testing.UtilityClasses.ClientDocumentsXMLUpdater.ScanAndFixClientMenuPathsRemovingLeadingAndTrailingSlashes")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\Testing\UtilityClasses\ClientDocumentsXMLUpdater.cs:113:12
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.DocumentEngine.DataProviders.Testing.ReportDataProviderTest.DataProviderForUnitTest.DS")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\DataProviders\Report\ReportDataProvider.cs:766:14
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.DataProviders.Testing.NativeSqlTableProviderTest.TestExecutionPlanCodeByItself")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\DataProviders\Table\NativeSqlTableProvider.cs:666:21
[assembly: SuppressMessage("CargoWiseOne", "CW1107:Do Not Use Db.Connection Methods", Justification = "Baseline WI00586871", Scope = "member", Target = "~M:Enterprise.DocumentEngine.DataProviders.Testing.NativeSqlTableProviderTest.TestExecutionPlanCodeByItself")] // Enterprise/Product/Documents/DocumentEngine/DataProviders/Table/NativeSqlTableProvider.cs:643,24
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.DocumentMenu.Testing.DocumentNoteTest.TestErrorReporterForLoadedDataTableWithoutColumnName")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\DocumentMenu\DocumentNote.cs:1096:26
[assembly: SuppressMessage("CargoWiseOne", "CW1108:Do Not Use DataSet", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.DocumentEngine.DocumentMenu.Testing.DocumentNoteTest.TestSetIsOverrideInDocDataForFilterField")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Documents\DocumentEngine\DocumentMenu\DocumentNote.cs:1143:26
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroErrorReportedWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:108,151
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroErrorReportedWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:108,205
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroErrorReportedWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:118,152
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroErrorReportedWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:118,208
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroReplacementWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:840,150
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroReplacementWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:840,204
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroReplacementWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:853,151
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~M:Enterprise.DocumentEngine.MacroValueProviders.Testing.RecipientNameAndIntendedRecipientAddressTest.TestMacroReplacementWhenPrefixRegistryInputInvalid")] // Enterprise/Product/Documents/DocumentEngine.Test/ValueProviders/Macros/RecipientNameAndIntendedRecipientAddressTest.cs:853,207
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.DocumentEngine.Testing.DocumentOutputTest.DummyBusinessObjectWithMultilingualString.TheMultilingualString")] // Enterprise/Product/Documents/DocumentEngine.Test/Testing/DocumentOutputTest.cs:3587,17
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.DocumentEngine.Testing.DocumentOutputTest.DummyWithCachedWrapperCollection.MyLines")] // Enterprise/Product/Documents/DocumentEngine.Test/Testing/DocumentOutputTest.cs:3604,69
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.DocumentEngine.Testing.ChildDummyBusinessObject.DeliveryType")] // Enterprise/Product/Documents/DocumentEngine.Test/Testing/ChildDummyBusinessObject.cs:18,34
[assembly: SuppressMessage("CargoWiseOne", "CW1199:Do Not Use Unnecessary Resource String In Unit Tests", Justification = "Baseline WI00893395", Scope = "member", Target = "~P:Enterprise.DocumentEngine.Testing.ChildDummyBusinessObject.ServiceType")] // Enterprise/Product/Documents/DocumentEngine.Test/Testing/ChildDummyBusinessObject.cs:20,33
