<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:std="http://www.cargowise.com/Schemas/FPM/APPLUS"
           xmlns="http://www.cargowise.com/Schemas/FPM/APPLUS/DOSImport"
           targetNamespace="http://www.cargowise.com/Schemas/FPM/APPLUS/DOSImport">

  <xs:import namespace="http://www.cargowise.com/Schemas/FPM/APPLUS" schemaLocation="patterns.xsd"/>

  <xs:complexType name="dossier_import_type">
    <xs:sequence>
      <xs:element name="reference-dos" type="reference_dos_type"/>
      <xs:element name="tiers-dos" type="tiers_dos_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="reference-annexe-dos" type="reference_annexe_dos_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="manifest-dos" type="manifest_dos_type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="reference_dos_type">
    <xs:attribute name="ext" type="xs:string" use="required"/>
    <xs:attribute name="sic" type="xs:string" use="optional"/>
    <xs:attribute name="sub" type="xs:string" use="optional"/>
    <xs:attribute name="baeti" type="std:Booleen_type" use="optional"/>
    <xs:attribute name="ndu" type="std:Booleen_type" use="optional"/>
    <xs:attribute name="comp" type="std:Booleen_type" use="optional"/>
  </xs:complexType>
  <xs:complexType name="tiers_dos_type">
    <xs:attribute name="type" type="xs:string" use="optional"/>
    <xs:attribute name="code" type="xs:string" use="optional"/>
    <xs:attribute name="nom" type="xs:string" use="optional"/>
    <xs:attribute name="adresse" type="xs:string" use="optional"/>
    <xs:attribute name="codepostal" type="xs:string" use="optional"/>
    <xs:attribute name="ville" type="xs:string" use="optional"/>
    <xs:attribute name="pays" type="xs:string" use="optional"/>
    <xs:attribute name="mail" type="xs:string" use="optional"/>
    <xs:attribute name="telephone" type="xs:string" use="optional"/>
    <xs:attribute name="mobile" type="xs:string" use="optional"/>
    <xs:attribute name="fax" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="reference_annexe_dos_type">
    <xs:attribute name="typ" type="xs:string" use="optional"/>
    <xs:attribute name="val" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="manifest_dos_type">
    <xs:sequence>
      <xs:element name="transport-dos" type="transport_dos_type" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="agentFret" type="xs:string" use="optional"/>
    <xs:attribute name="refdoc" type="xs:string" use="optional"/>
    <xs:attribute name="sic" type="xs:string" use="optional"/>
    <xs:attribute name="typ" type="xs:string" use="optional"/>
  </xs:complexType>
  <xs:complexType name="transport_dos_type">
    <xs:attribute name="ref" type="xs:string" use="optional"/>
    <xs:attribute name="VOS" type="xs:string" use="optional"/>
    <xs:attribute name="VAG" type="xs:string" use="optional"/>
    <xs:attribute name="stage" type="xs:string" use="optional"/>
    <xs:attribute name="mode" type="xs:string" use="optional"/>
    <xs:attribute name="typ" type="xs:string" use="optional"/>
    <xs:attribute name="armement" type="xs:string" use="optional"/>
    <xs:attribute name="typarmement" type="xs:string" use="optional"/>
    <xs:attribute name="meansID" type="xs:string" use="optional"/>
    <xs:attribute name="typmeansID" type="xs:string" use="optional"/>
    <xs:attribute name="meansname" type="xs:string" use="optional"/>
    <xs:attribute name="meansnationality" type="xs:string" use="optional"/>
    <xs:attribute name="RTD" type="std:DateLongue_type" use="optional"/>
    <xs:attribute name="RTA" type="std:DateLongue_type" use="optional"/>
    <xs:attribute name="ETD" type="std:DateLongue_type" use="optional"/>
    <xs:attribute name="ETA" type="std:DateLongue_type" use="optional"/>
  </xs:complexType>
</xs:schema>
