// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetailView.Job")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetailView.cs:149:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetailView.ChargeCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetailView.cs:116:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetailView.Branch")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetailView.cs:182:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetailView.ChargeCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetailView.cs:184:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetail.ChargeCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetail.cs:48:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetailView.Branch")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetailView.cs:250:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetail.Branch")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetail.cs:90:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetailView.Job")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetailView.cs:217:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetail.Job")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetail.cs:69:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetail.Department")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetail.cs:111:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossSummaryDetailView.Department")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossSummaryDetailView.cs:215:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetailView.Department")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetailView.cs:283:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetail.ChargeCode")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetail.cs:79:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetail.Department")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetail.cs:142:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetail.Job")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetail.cs:100:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetail.Branch")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetail.cs:121:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetailView.Organisation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetailView.cs:613:16
[assembly: SuppressMessage("CargoWiseOne", "CW1052:Do Not Cast Factory Method", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~P:Enterprise.Accounting.Integration.ProfitLossDetail.Organisation")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Operations\Accounting\Integration\ProfitLossDetail.cs:336:16
