c:\Enterprise\PrintProcessing\EDIPrintProcessor\WatchDirectory\id_8B56B1D7-1E37-4ed8-8FC1-395D44FE0EC6_00008_01.emf
c:\Enterprise\PrintProcessing\EDIPrintProcessor\WatchDirectory\id_8B56B1D7-1E37-4ed8-8FC1-395D44FE0EC6_00008_02.emf
c:\Enterprise\PrintProcessing\EDIPrintProcessor\WatchDirectory\id_8B56B1D7-1E37-4ed8-8FC1-395D44FE0EC6_00008_03.emf
c:\Enterprise\PrintProcessing\EDIPrintProcessor\WatchDirectory\id_8B56B1D7-1E37-4ed8-8FC1-395D44FE0EC6_00008_04.emf
c:\Enterprise\PrintProcessing\EDIPrintProcessor\WatchDirectory\id_8B56B1D7-1E37-4ed8-8FC1-395D44FE0EC6_00008_05.emf
