<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <!--Include your child projects here. For example:-->
    <!--<_Projects Include="..\ProjectTypes\NoOp\NoOp.csproj" Condition="Exists('..\ProjectTypes\NoOp\NoOp.csproj')" />-->
  </ItemGroup>
</Project>
