
<!DOCTYPE html>
	<html lang="en-GB">

	<head><meta charset="utf-8"><title>
	Exchange rates to be used in determining customs value - September 2023
</title><link rel="shortcut icon" type="image/x-icon" href="/SiteElements/Images/favicon.ico" />
    
    
    
    <meta name="GENERATOR" content="Contensis CMS Version 11.3" />
<meta name="dc.date.modified" content="2023-09-01" />
<meta name="dc.title" content="Exchange rates to be used in determining customs value - September 2023" />
<meta name="description" content="Rates of exchange calculated in accordance with Article 146 of Commission Implementing Regulation (EU) 2015/2447" />
<meta name="keywords" content="conversion rates, customs, exchange rates, fluctuations" />


<link href="/SiteElements/css/foundation.css?version=752" rel="stylesheet" type="text/css" />
<link href="/SiteElements/css/foundation.min.css?version=752" rel="stylesheet" type="text/css" />
<link href="/SiteElements/css/foundation-icons.css?version=754" rel="stylesheet" type="text/css" />
<link href="/SiteElements/css/site.css?version=152156" rel="stylesheet" type="text/css" />
<!--[if IE 9]><link href="/SiteElements/css/ie9.css?version=22732" rel="stylesheet" type="text/css" />
<![endif]--><link href="/SiteElements/css/footnote.css?version=35535" rel="stylesheet" type="text/css" />
<link href="/SiteElements/css/hacks.css?version=91709" rel="stylesheet" type="text/css" />
<link href="/SiteElements/css/print.css?version=39488" rel="stylesheet" type="text/css" />
		<script  type="text/javascript" src="/SiteElements/js/jquery.js?version=37258&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/jquery-ui-1.9.2.custom.js?build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/foundation.min.js?build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/bowser.min.js?build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/app.js?version=137868&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/outdated-browser.js?version=25982&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/cookie-banner.js?version=124637&amp;build=1131401"></script>
<meta name='cmupdated' content='2023-08-24T20:16:00.0000000'>
<meta name='robots' content='index, follow'>
<meta name='contensispublished' content='25 August 2023'>
<meta name='url' content='https://www.revenue.ie/en/customs/businesses/importing-exporting/exchange-rates/2023/september.aspx'>
<meta name='lang' content='en'>
<meta name='google' content='notranslate'>
<meta name='section' content='Customs'>
<meta name='solrsearch' content='include'>
<meta name='template' content='SingleContent'>
<meta http-equiv="x-ua-compatible" content="ie=edge" /><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0" />

		<!-- Matomo -->
		<script>
			var _paq = window._paq = window._paq || [];
			/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
			_paq.push(["disableCookies"]);
			_paq.push(['trackPageView']);
			_paq.push(['addDownloadExtensions', "csv|doc|docx|xls|xlsx|xlsm|xsd|zip|wsdl"]);
			_paq.push(['enableLinkTracking']);
			(function () {
				var u = "//analytics.www2.revenue.ie/";
				_paq.push(['setTrackerUrl', u + 'matomo.php']);
				_paq.push(['setSiteId', '2']);
				var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
				g.async = true; g.src = u + 'matomo.js'; s.parentNode.insertBefore(g, s);
			})();

			var _mtm = window._mtm = window._mtm || [];
			_mtm.push({ 'mtm.startTime': (new Date().getTime()), 'event': 'mtm.Start' });
			var d = document, g = d.createElement('script'), s = d.getElementsByTagName('script')[0];
			g.async = true; g.src = 'https://analytics.www2.revenue.ie/js/container_NJ38hL7m.js'; s.parentNode.insertBefore(g, s);
		</script>
		<!-- End Matomo -->

	</head>

	<body class="revenue">
		<form method="post" action="/en/customs/businesses/importing-exporting/exchange-rates/2023/september.aspx" id="aspnetForm">
<div class="aspNetHidden">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="paEGAhMEfCFAIG8GvJPO5W03qf452FbkFqDk94+Y/dH6drnctJ5OFQBVKwNwjIOoRoev/GHhXJNGfaPzjjDXA5RxNOB0IgpQBe8RGfzY510GOYPKqSE9gRnMnA/afuDs3Hz1CrxsVVQ3XPGQN2ob8ZChkfw+VareMDmmJn/2BikMhSSZs1ES2zZJRK0WGowE6E6zqg1Aj5JJyGqsAgWJ3mw5PTI/IjSjBjtvld0xt7goPqS6y0JTX+xp7i/vmgJlEw6dzfxvbECmYxw3NKCElVo6aZmGEW9N+yGpwaHpAodwWOO0sPn1ViLQJmKub94SgS03PZGon+NRj+OjJMwcSVDaokkDoTJYK6D8fYtuRLit1qvw03xdIxYlq1M/jlUqdAIoo2TjHsZwpDvU/L2UFdLLrgA4sicIT+8rNxdpuaCduVy1Zp4Rdg1/jhuwCRJwloZH9AyrLamQs/sVss84omNid7Mgxx3hHAStD1cm3W7wdWUm4zKXEILp7fJldNw1J2qj/bw68am1UD0mTPClVwt1JwqIAUUcLiNnBTt9/OcBApGOS6SXYSW9RCdv8VPWwUlO0ifcaX5A1J2NFhDKtrChAr8i0Txyf82ytv5uHDhPMGchJpB3kA34um1/ltg+vPeN+hecRrI3H52N8GirD5hHJ0R0Huyc16PWuroq2XhkGC6neGUguWYKPqx67bnbxoGLh2jcFpo04Z9yk2QQWdP5upVjJYZCFKn4NEEh6b3Vv29F066tObFSGAqSQIrgVMRrEMzNybskR0+JppAkZyFRDKZ9MVyVlctSRkfA+JYx02RTQ5KUllLcKkQ69HDuzjcBUF4qF33UXWALRW7YHD74YTK60u6ym3n6N5BEiQ2PglFeZLo3mllA8aC2otalWA6pOK7MUUj9G2bpeg/htVxF6ywxuyyexaAq7lSKhAX6y8TxgPw3fpe5qCYk19CYWZadOJ1B4TbYjttjEIaHDsBAX701lMR8pfm/82nn5WDcMI5AmGvKJiLotdF3qnbSgaOtNRx6wEv25cDMf64UarAMIzbFqq/kuo7dSmS9U8T5BNgouzue0/TpbOMHj28Mbmayrmk80p6U5Pn+saHZzhyGSreUUxUgp9Ee8dd+coY9M8b+yudAKOao25q7ViVzkmAzdbimnPaBD4/GQN2/RT+IpSZITm6YnVjgRzk2/kvtCsLEX3C7u/E6lxd/ImTY9pjen6C38i0Zl6sOQ/Mx6ggqG0/DO6uOEBPfYTRvOdUt01pI+ePie0KMPWCmad/UFVDTm/bdrI3X7/HjPAcAyxVdbX1I3azlGADLggHzFRYScj0LW6qqYbmCMCn2/KFecLikZX8bZl18GTdnJR+j0fw01l//0lMyvcRmkHfmAtC05XZVtrNgtpiN/m39laRNK+a+KmtFq1AfYP36ur51QL0eM5pkgJ6exJRSG4KEEKj5D6jMtx8x0m9nxKy1A84EH/6lDvmHSXnG/KcRiNPZNFuOd7VZLbzEIFFeQf4c/v6eBvmdVYXqrlf/7NknO9q4t+12JB1mvb5OXcZ7ciwdZLnQLfMW++dzAVVgs0EHctju3YCgSA6025qQTg92xOPbfy2vYIp+3tub8GakDbVnCxV1ecIalAVa0J/iq2kQ6bhd4OJqmWhHxSDgWSWoBz78giPZjgQtfYq8PrpRUYXpqGvJdfSYH92BbZmNMzs+dZXYLNRGOoyOpiiIPAhIHh6YfLrJdzX3TMnY8pPm1NT+kPM0iuLShwymhqBoHVdRFO9s8dFndrMlCm6Y4d0zb8sSYMbORMlgNm7PGeUooMnmNzBlTPcOZQSeF9LuINqIjWJL3omXYac3GfqITVMgWcyA6qcDti1LKO5k7J1a7zxEIXIYEZVbTK4w9iY20joGwicBsAtifGEuUAuk8pSJ2brQprUSUJj0tXAfmCtvYKmQSelIJ8Gy2otpOzU/sTTdVgLCE7H8wzjQnqqTDKuU7e8+qYC2VB1xbqMU8mehKbBJdicj9P0r1nnTJyyVFtQVqqVOoc9+ltkahDUut0f3pk02fvR1xfKjYx504OtBnaa2VPBeEJaZrTaieRTaobb7rOtoPo3LHpmi/dFAUPCUtBNFC4RSWeezfhHHRACOVJb9sQ5I/F5Wo0+yHrBFATCb+gJArN2jAbhifAVXnFC5Vh8E3HFzfoYk8//7wMpwQBEdSwO3xa8DOJZIMUd71Grfo6YUshwZO6l7/5zK3UgXXZughxPse73KWGTHZpEjwfKzYNbQaELeEeP2I838Lfe1ImDIDaKhPuBV4+1TWqra7wpysWGhwtuUt7o8TwkpN3FRB5XxM4nleoEjZ70aCQ3WgspPIfqwFXh/HCnYWoCGzuFVNmlrfki0Ek+uer8rG3T8eAwM8FqoxmLpq89WpIpQFEFBX8oIQoYSMgLP2XOm5wFJaBRrJeFNwDx84z+pes8V8AP1KgVTByuj62oqJstzi7VG6mEy6+9gVUW8WgNZtz3xEkcRbl6jFKsog9G9l9jJoY9w9oO2myNZcCKchux1usUiIzOEEJF3kwJjl3j8dAd6DECGI2PjoLyhwuTpR28/LTA8n4SfMUfl6NWGrOY+WibEQoK1iS888fHMnmlvoej4yf3X/iOrdDmZt9MtSQ7phX9npSNcV0maARAP0TsAaVPaDgQI48Oychzmk9gtuyLv2L5OBlE+JF2uqh3mf9dMVMG0INnCbwW3hxFPa/0EEsukyRlD1/3zRoVf5J31SeBL9dfiIORr3DJqLJBTkKNJDZcVEvsfGbPsO91tfY2IkqIpOBBaINgH89inQ4nsIvcj7zuODpoiWhoqfna/vtOvOl09W966RV0sbHgvfxrCHo16gSanAyt0roLYUoy++sj3csEH9yqws/EH+71BsBWlmMaxj+ZjhUAEN2o0wisjSRUduwx5ps9oMNQjF7AoZ3ER2poAAQCnUN9lRIXarjdSqfi5wfipsKWbi/IY0PAfWuRHfx3ATAAE3SzbzHbg8hkI21H419RXY9QM6W6C8iyDa9NFKzne78qGS4zk0VdUZN9gFgs7k1k+Wr7cWgHtbkhDZysGq1U8X/LPSAS2YAfhjjg1OmvPHu/OStbxiwJ0twHE8MGr58hXeUg6fXwkC0PXRuDxz3ZbkaGso2nd7ERGMTVEwlwPpDm30Ck7i5QmumXP92CF5etfbQ3XocodOyObyyaQtALYvGzeXWLvgwdmC5Z5RPpM8NW8jz16u+qsUdITwB1//gjW1g4QoaCNtSQcvqAUhe0fd7yuuJ7serzCgb+BUCYE1sdp3RJ/8ILI1dUfveQUViAgf+q9YWbietJsEYn7D5ibmKOV3k76DbJQo2aTaHoF0tgxr425AT4FSiY6Zzw45RaKzD4zkcXQVHI5DrWofZB16fDTCrl69GrmKu/1l35TmpeoKe2TSYtULE1f339ibMd+tZbLAAeOLB6/530Aw9j4JC1wiSPImDTkDWupyj5HI84hNFlq8RPfE4YL2PnkSg8GW1Y/lQnk0gxrmhyAPcGovX+cp0WFUFFgZBF8cIxoqYDFkVdJZukHZORlmelHN+v5Zwbd+i0++JPl1uUgcw2zmpdcm0o40yY/nDCX5eXRGnXPNUYB3e30zc2Mv6fWSmWoO199nwVPvulDpsEjNLIcbzjAPKBCAozVkfGO+YgtCOSqpK87H3WGLb6075r8HikOeeeehRvcRibNw2NNtooNYhVyIyql1O7eraA6ypdiMkSTmTYJgaxXkpC/sn/TkCJOamcyvXaY5FPw/Ci21ed3E8uM52c4fzCZQpontbWvB3WXfrwceMF2eBbrdyTKuAEjWj5SJBEIaa7g8gAHeh2MHFlix6eGmu02pQYnIRxzgC2o37d+06vo6lhlcAJzUfAjIXQYy0H5A9SUmStKUHlHLdv9RuHbPr9tfLKyAe72fXcU3PRs00aEbU3d0E8bStpaMjxYHk++hsagTnlCNgmY2665gQtepn436KZSujdJNIobSbzYACxw4KsUhPHj0sh7TyA1zvxlTbBl8DfSfEp17IPNl9o9V01GHMGcT0Jd0YVYB52lAif27kobJ9vjloHaKK+wJdij8S4490nS+adoQ6LATlDu2bJipC3cuV2IDg/lENgn2+F5JoCEKokUfLHrsJ8jA8YS1CJGBDpwaOdLHE0XY6DAIv1eDX2oajTkTl02a8cxV4iZaYkyvKzpPajXwKy8zBgY8pzBNaulXMvvhRngP/bIdrJVkP4wGlQQWWCOtNzmYvnupsRmuClQjW0XUWZ63vBZNrRqbaVa/BEtzZYeJ6Wfidj2x7G+OZEA24vN5b4rcaZDRUGIe458O/iBmUftf6YcTOfCe6R6JL02pjP7sILAKc6lcI2B541xNhXqK/wKCqxZQ2c2cxpiSZCxl2gaAXxx+ngGpncGPHSGm6DirgNb7XcjsI4rhKB6cz79UGnEtLtnfcm0/aZExcHcJQWTEiAz+osvmH5ys6O2HjkxqyoE5OBR90Fb68ShYMzk3HDzv6BSxp6v0Vfbv2qOGGQqKuzlf9ccHOrzt2tnev1dnJqhGhkhP/fACNfopLz2IEPvN1cJ5PdoWAsb8w+rNadcAdN7Pn3l/YjpLm2zuDOTbec2JPeMJNidTtf0qk2j4Yz4yIjPGRUbYdnnI2WZeSmggKdOsin5LOiCiXd8qDk3av32Snl2y8KPpcwGMUXxFJlhlayyPQr4J+UNVRC4b9T6BuIobJ+Lun86z/L8ZVGUoSYTP05qYEdSuQDsZavKvVlY4bXhiMHHUfsnnJoiB3tPyr6v/9P0kXY/c41/3hYEBF2VpDbTa017857hYVwt3Jj6WCYJbczPIDMqD91tggK0FmdC/OUB7bTofTIviZSlE/Y2fH/ohHuZaXf8G5/59Q3xrMi7NW82W4cjnSR7QuzByMLrl545ii/dCoSCR0KUdiKeN1CkmVxX1qeZ9I1G5lS35e0xTMe9Yqav/DNib34rfQoeOHDo+7Gn6T+DNl6mnnd3FJ+7f2JCTRW/FBHCVZkSzh4FhFd6FEnl5Mm2u8RsS7QGM5R6EbCTnUx8ILEjew7xxqm94wFnwUrMl48aMIXgypNomfI66kg7HtneGQQGzWG9n0sWRBjjfIKIbhbF2OB6qtz+qWGNHOwOS10yda8hhI/nROqexHXMByAbUUAFQ/7RrksmtN4KnzJGLug4mhfKbpFycT9b95sQd2YKl974DULKT3RGgayp9nldEPwZHy7414435UMnmrqQfRqpWCZivAYe6rLA5rI1ojqjVC5AbkmxI4gzyPgXgRn6ahJON8AtcJLGyBNjs2PDAL8gdE0xLIqvjSqOXZCrCMt7zeyImv5y2NMZ6wpGAk++xg7+B/GNMBlmT754+vwHr/JaMzkSg62SrpidYU9tCcLI17eWLlVr4xYoIkS4+7gJ/bbPjz8kqOSIc3whjZDh76+isiX4eoJYUDFY4NkI+FhcvPmEearK0yfRFw6Z97dRxiZvgIKFZLrhAGFJng/unjAAXgrE2K7fK5mznchYa4sjwQ32DiIg4MQ7d1n4icQIjWp8e7D7YRoMFW3ratnuAKrVQPDc89c37zhpe9Wd2zPGphycKIE1j56jFSfnDrNJtbf4itZtmMbqKjpSHtzpcn1HzxI7w8g9tYX/6eBhyQbiXF5WCI/OlsYvUTyS4QXxROm1Od5cIIIqQu8OqOBQdlVVb2JzI5l7IxOAU0xXkZZ8KOcp2Z3o7EdQjEVjvn5Nxa90mUUrbHfwcfyXZsE7+O0AuxzGV/cbMy7XiPJki5m1XWAU23TrutN7zArl/M/jk7rQ16Ft4sU0H/WWKuSKZnv2tGjuSnlwoQkbBrbmwiis8Ms7unY4zQGPW5Xanf/Tll1jwzMBh6CtoOEShYUjzneR4txUyQLXj8M3QHqc2Mfpy8tEKQtY05Jl+1UxPLPlPz+B1W+fu3IzsSPC0xpA05I9nJiy1BDs1TSdHrd62ByR0QXZDZ1pZI4GSFsDTLSvpavpyMmgB/6LIXVIpiVr/dCdM7UemSioot/UNyS1oytY3cy8SFOMWGI5OJwlXZDpvCVKO5g6FqAcq3RC1HSDCZu1Y1iWSXBwhsu1UNTdez6O1F34lGNHR15mmB/P6Ash1GGFVeM0mz7QTGy3WZziW575tBq8XxJ4rq619wTGQaxjJ1CxYDcLlN5roELIxlXehmoUuHE2CToAYQVOWHk89Vm5b/7Gt9UxxIvWZOOGwKBy3kvaO0YrNwGvqPCI/rGkfrDUpDNamLYlsRu7WqRZAZ2qK4buWyDHOYgYmyTgF724dJQF1dZs4ng7RO8WYJoHuyHDAL2fcgtdJsskmtyoYolk0PDEa4mfJT0wf2N6fjxlLJqI0UHu7YyvBGtTyB2tmg/5jZD1Er/3qu24qto2MvT4yd4eWWfo0be+JNAn9O7Q5AYrd9R+J5izLCbpB9LnZlpZ0CC+PeXs66EGU0gQGfEZKJjXxS4fo2VQiJXouKq5b3MR25NbIShrDRHEsQdeJ3Bh1XFoGtVCsrUCdMxDkelnolOzu6aiNu9PMPw6kcvpPC36Sb1sGQUke/8Lbj7YgFJ6YVUGADYqRSxxJu9LVwaE0hnZpxma7XHrJlr/ECD3M5ml67VrMce5/SvxvAnq73B3zLr+kFu6Hufx5pD8a9d/GZxYVuZWhuE9hxYb8Yh3QyD8aJKt+JX5jjHQWjj5vIAqwlvSmS/rDbaOcnoXrjOAhQm/YWkmeUgGpXhC5vVnNeWFGuni8GmOchHADPTO9EBBPqhyeZgBEhU1To0Dn8I/xuAZMPOYR/R/C7w8z5Pr9EkVcVVyNgYchf9gfdPHjo9uEj/V+Ly4qyh+LrYY+JHkcjoNpzP/6489HMF0Pjt+Vj0dXfdb69TsQUFqDSI9rKVzOsOGArMRxkCHD/ipItQrzITsytwn/Ujjp0RThXh+ejTqIYHPKLPmruBPgPN4DFVBM6W4M2rb33VCiNz6RgA4zyeukR1vsLJy2QEmYE1ttLdehbJPf2IgvGzaLZOf3hQuMZXHVz4h9Oiy6Rf3aNYEpwDHvRW3RzbyFMwzjcFCySykm4guYIcU8DcpZiruWQ4ZKKw9ZRRO7J5THQw137BREdeQPbVMGN4bzZseBl/GDBpcE9QfKTgvO3sbI0ofQNSW9tv2ujkhk8MDz8bpuH3WYutrzVSwGZA/qGFbkMtpF/SXnxpJMkhZ30tuxy4ucE3IEHEjUUWWdlGLYoXrRoWbqeY5/y+hKi7yQ5srjwnlPy+q/dw5IaqgsXMKf89hX7OCB27cUN93WWAiE2vhDNE3OBSpSihnEntyM1LYkRAbzOEyZPQHrf2GHo0doAdp+9qCtUmw+rxMA8cbFeB8HBTENjtMLFmuO5fw0u1zHn4TvNSb7QAjGG5zBB30AJuOTLO46MM6rpjCx/rBZ4rfaZemFSx48XlbR1hzsPLu+nIdonPyV/94FkSdmu/SfSLZiwDVvef7obtzJkvSK3aQKiRfvu0PUzomdZf3XSUa+HFk6hd+qjDxxHbohK7mucfzYOQ0aDrHixj8VGjJl2HzswCJc9zD0DGnGJ5EaoR/Lun6GHfI/r0Sfg4QHX/PakAgrbad42KEoBl0bSgUsJAsxQJ8F3cZhLyI+JqOK+ssqmw3PsUnIjFX3Q8tDBxKiYeBYqK+y4WP23Qgz68h2zc9BNw4CckKWaO0Q4D80wbBqO0V3U0EWJKCbJwmvJ3Atjl/iJdZRilXKAb2rmatHHgNZM5lAlj/zNX2/ZNf7IR29ql36QYzXoSKYlhcy3Ls4iYewI/gBw1F/s4fzBj0zzJxYxMsnnzIax2T5QcUhFk0bJIMm3Au+uuZdTTMZXwNu5d2LDDN6uZx2ax/O6jHWLjKKlx+BI8HAvc6XyrvGSsRXuGfHhXHcxB4LI0VqcvfyzpV88Pmp4fuOinIr5LMKeMMWpsPcINb7W3nGvU7aTP1DKpnOCF+aW6/B8LeI2jQwy0xzlXKk/lfTAo8sFEQm31P2atHL9fl0+sEv1gxnCAhLSGuf/BxU3uDS+ym2F83zX2zb4nVsmVLAp6TY7UC2muYu8FStNQ9AlOYwutQhdKgzHhtHJ7IbJAOH+HJiW4nswaBTwURxh01O/gtzhwbz0ltrxxqGfPGz8ZfqE2buHhkvmCDmJAy4N7G3jGQpcDaSSXBKxi7jP9y47mASolYXn0jd3a9/CjlT3WcqIiOeKrepYw7sq7zY8I01UrIu0shiAEVUCpj5Bal3t5KR464ZgA15ECfruB0NXR+5Hw1GRUC+NGySv0poBg7tA2qplC90Z1ukkPKTkdRDj9O2lVnusSvR5fB+k3HL1XC8ExDsbVAM9yFfwaRPw41WXfVIMJJjSJy8TzWDAS2w05Es7Iyc4TjDUmN3ShvQ1KcnU0rWd++q+eudV1Zx+CtrufxV4QdCU1XPw3pHtlKG7d8O1LHTl05wgQmM8IxNyPHeOh65yAcRMSE/Lv//i1q/29dj/zGi4yXO6zYOdjIcttLKx+WeHqPSY8OLCiCjawIzyNnZP09i0acBQcbrm6WfavuHHVPoAYBqY7pGBC85sMXpbblAMovz0gBI4jeUf9+QiWkcBi+VJpdHq0s2llsqb/6C62BXFA0QLeQoGZWm5/M9QzOPa6i7gtLP7rVK/1m84N0zMlGRMMLejghkk40WizhGcI1/SHIjHbGpDeXf6TC/xxnCfxp+lWYxpmwdDjE+edOX0R95snMgAtJ+0/kRZcaok83WnD+JD+XE3EJ09w+OD3Lu3bhGLeQw5xpq3/1E6EhQcwnuPeBOrNYHb/quI1wjnj8RnJB+2NVynVnIvOPyp88uGvY511rvh651XR+1pAicKrGtfc7tZd6w/4vC1baYw4SxDZ7ToMqXONtFX0yj4gOl0eifI5L7Sab+MxYTOR8fLX3bBlWQnJ2DShJYTLJM2ldKHabhj3fMvn0QHYejhqsQEpavkG7CQhgGbVz8CMXryNAsXxcMT7Brfa8CJGv6I5nMV9NI8sIQkXwKZuLdZk6Sbtp31br33KURWScK1CRIkjZMbFfn/2o5+QdH9rUMB0kvs+JOovE3W8irV2ouEUWY0iXn8k9xxniU8mUklLdeHgWXxh7AwsSYYGZYFCregQeq21OyRhGinHHHSRb8ttUafxfS+TdoWoBTcbRsEQS63zRTLS9lDlUn1ILmC+C8/YIrOzbn6Xqa6IC7lGsNptYcqe5191dVmIOBljic8WCcX1Bqli6yBA8xY0PfnoE7ANXLp7X5kHLlEQQZKGPPTlZieYCBAmB2OZ6fvIuw2mQKTBquZHEhRa1nUPMarW/EvHMM/1w1BidNbsfmSE8cgxGMU523jfDVqw1KjndfH7LZOKzycNQ6673CWYG08QRastpJup9TZyqJtOeMvvRoYSAbHpJ+S7MFJ5w4iNU46/4HujX1i2zsVbkEg/75GvSQ0By8NnY2h/Aujmv23aQFwvyUCHIausXrmdCjpAaHATuTf3esPBDVkDOsUrBRd7SASdYWhL71wFuKY0Sg2TWaGd4hxmtYxbL0sugiDVdmg9ritPthtmOSv0UENPCWe1hq2JI2ahglzZ0mU00wMW425eDFr2GhJmrCON9n4QXE59UvWuR+nee/yuTOo7j9TiIOa/5sgcceME/vSezhGaJ0MpcMxv0qaY++ZPscjIAXLya1zu0uOloT5kpllNv1R3AFs7A1oW7oHb2iUbAMDL4lSAYXiNSbGPAF6mkDS6GzanNjfsF1yI6J6NwYhihGpXqsSanY1rGKx1Wv1N3NSOmQ/BCd6kMet9z1yfA2qzm28jSwQH3w1HeI5T4p/OQDvElxSjhiG1QEXDkPLG7s+h1fZvi+XguNnDvXmzzePmL4e8GuFwV5ESiT/x7wcgRISHS7nBIchUWfPTWgC+OLOyjaG8qhWG14XxUDM8GBskuNwKw0hOWg/tcapvqLaXjy5qlSCGH9RjpAAxdKUNViWytqFExNCB57IcZM6YQU+31/BXwYNH9T43XW3SqeoPyBr+1s01CSnlwWSyXkLPvIqM/4Ee8tvuVY0kSgYbv43z3zaf8ahegcnUBVk8AmTQtZ5fGC/UPQrLD7cKj2YnpD+/ebccxooH5++3PnCV7wnj62hkqrJo25kB/irQVph4kJEJPiwZBBPwxk5zd9KMoVJtrGWjUgpFPP3VHTq/eS3GZFC8WPx9j6AxeC9cxOJeh4FMG9aJ6t4kIdwTSQoDklQP8rTWBrPqyG+fB8kYVUXkqXG2tq7tgALtyEVAv+Vt8L57TT2Yd1zkpcZwUOVu2hd7+Yt27nzQbTBXhvSvSq0JR6tN0MDDZx+6SGKIkhXQ/L4zJ2GTNQLbvR6iMOQu5xWE0zkwSPqVyuvVEunte7vOcVzYvRLKF4BzqtoooG7SNe8BiWOLWu6SgWPZDNtFbLdGRPcvhH075n/6lv7dO8sNH2J6RhalzinArKXCaOqoYpVSOBqvokjmXBm+CIbaktFFU7MFAvwpfZaQaOLO2QPLTHtgxur1Zqtw+/HuduRo08cIprhq1Ni8HKugmLuQJsmk8OsL+tBsE6DiSKiCjqfMI05GwyvKstljuhibDDljWIA7gyA8+qA/pQtm3ht5n69tphvgi1QLu3pnoDitOKHdOvYQ1LP0+XvHGDuhNozvYEbnC8ADbwWyOgrRp7O5B/qlUBXpb+yd1eQGCtDSZIukNGT3JmksJtA2797AP2Hc5fKm5xA6ZnSmnqZACgZs6L6oNAej0ZU9M+20MUEYQoXjH2IR4SrB2Fdm+jXEvY91D2v1YdtFSiC2eJr12YOqU28gNmO4JSfSBCItO5rSm5FIWkhx+H7MLO/OBW4EBCrZCI+Q8SZpQSu45RjJFOia1OOVxxAcf2/5hQiQG6D9Rm4Tul+9noR2tgsvXT+RWvn1CrLZWW3BwU3j7zzLnxM3WD31zcfWrmgt9/aUJRiQf5/IlEfcwV/ktqU/E6kKCoRUKCpq6xhJ+c+PrEU2J/Oo805GJv+oabsO184zUWPCO9+8eFpOKV+1BAhD28qd+q3kdvuMarD1j53N4fDCau+4mrzT+6Jg5PFGeOQlhbVL8qWFWK0L1Sn49Y6BEIZn8YIXaorGhtx5dX+9NTlC8KsfVvzbOFl81aPd+43fS3YPJ4HgjkCcG//3NveYZjYYyvT/br72hlqRk2czaYSiE/ModCUGkZRRl5Vl5LwAuTSE8Loj4j6544GBm7Oxapm82/+2r67Rk18txykR5MbXr/ptuhxNhqKtlT3XI57LqzTy1/pA4qWoJTQKxaDyxp2kxmh1Shrg6bLlBmxewbXOygJ/ROFsVuO6PaqZKW2W+YGhNe9SSiPqKkzWfTrbArcNovAfH+gXvsAknkKnWgJ/8avOXAKvJ8QzRF8VF0L2SmrTJHQVAowfvMZje2CsXO5xZyRaoIuhehMvD2rr9JgLy1U1j0ss4wslU2I/fXTypnxQ5C69kPeQfHSden6FpWRoY8M4HI6S6zmzFzoORGoje0WCBmRUBKXWu8v5bHtw/OEvmuqIrNU4h/Hh+v4IpSgOSLhJk8ViQhS+55wGnZt1rzVTy70QSvIVwmXr45JhnMgj7qinW+T8/PYve++9FXwScPpz5mo+C+WA/b9XmFnZKHpgl74dBgsL+TTi6VLtikmzeCKQzn8qHbP4vL0rf36lTs9uM4nkp4Sn5RSFnUAldpVy9Oon2+92Zf3sLAK+R7RtEGInxn5TvUULPvjLw3KJ8mkKxqbKfKnpuxVJEMAotLGS19zK2m2yjTaDXf8T/RNC5m+RmO9/PjAZQsz36WpqAyIcXsIkoQIBfCLr8bO3LRlImthRm+LgY+U7W0YD2Wqz2/V+Xqk7rLryEq/z1zaTqyYSY8eIRmOmOc3X/zLrq4Zutr4I13WmeI0EYZRZEW47ZZHPeaTeT7POAfy9su3tDEMhC6ohEFZKbsEuS6I3AQPwIQ7MR1Qu8jJmPZ9I+BkMqLgff33hGHTfnvy3pnyvReF2mrLJflD4Yqlnnxp/6Rlovr2cv9o4oGCOyY8ZfPLcMz1aRLSrGRhyGe6WpLCxZmBeag9Sa/6bUsJj8GfvPRzChkv+ZcGesB6tvovriIhudA3iBxI5iignzld2N6gxMRdclEoajuGYuhUe4s3+V4zNRSM4N4gCHMH/H2EnK/tvWN+KPyGLnIhP22K/b+m7WcTD+92KuCXrboxUTtjElqRpQm9bpYs/IuvNnUnVnPcDAa8eM7RFJ+RjJk9W4WraI1d6AOvIRvh82uOfc85PF4J6a72oZe58ixPjEJy32yMVAkeT6Qp+azp1km7ys2INtEwPXMiE3k47HfjqYzvLaVITnLt6f1ExK16IA9NNvZWWtz6yAoG4lnynRGWrNI4s76mecE3KDzQoHK3cDv/qorKQBJt4Qvtljc2fLgJPbou6YFICOJ3byEK+vxprnRB/GbnXhkR6rcYfBvH60A7iZRCWLsqrPQBNTOXYpaeSU7SSd4AElvHpCoKbI89zD2tRzTSdLsZxOuUjGSBNbpuYkndjGclOyQyg6OBFFPk4+GtAFRnPNN+6/efZ81X4nr+1SBYPuv1MiXfCfi/9Uc3GqsiVv19MF/Ey8wucQxTpVOplTdLtqPyV6xtud7tJZTzatHaLkYmPMFt13m4SWOfSyWpz+31BfPa2ZuEISUNJ8EqfenGWGjkMdRrPU/gYsoiwcCSWN6B0TF1CPTaS/iP+9nQaLykTPLSOwdBU2fpHEcsYEDrqsqqH3r+h0jVqlgv4sCls42TKtofK+gc4HK1n6BloLYvPO7eCPpOD0HTBHUH+aEA8gUzDRUnF6omtruCpLlTRllWq3auSnJUZQ/JnDXtVPMIYiSUw8tMlTKQIFTlHCkrvbSccT8Igu2vdnZc22FBuHY4VE/67qUNoleD+0PSRmKGiNLOqgdiT+az1woEG61bbDQd+G9nbXxC7GNZZQaQqS6F7uToG7jamm4aUFmlZkIVhAvksLIg1wcoXtzbE+z4Vc46izh3GIAEp4jcFQAczr2dAo6fPbsaOdxyLlPQ/nW6zCgU+41lnWsEm1i17J60udc4wCRwSdwXQYxTmDQnb+xUPFM3ap8n5/pZRGKn2qpvqky+FH7bW2lJnIvSkxqHGPISgvRFGE9426Jk4BMNMlfoWPiup8jaZuiIAYxJLZMxY6nRxg1SC7DzZ540VJsJFN2slD47jPXfyDHj7G2EoBzR+eq8OF244qsmQfaSVdzqS4KQh6MyLyEsOen8APIGdySDOKXVe15BB7Lh3MAWi3T51x6joQlazFwKha4rSWRwbcNVdgKGUl/VhKKZVNPx6Ldm1xcbWFnz+Y6C2mvCz2R0mjGwYLBFyJClmXpXq3MpRpTauHHg2LUmRRLRoYY9AE/p1v5y9pk/5Zqztf1VtEs2TZdorxEknHjIya/mSuPX+ESBfRGqYpWsk2t9rJcPck/NAgQ6iwvIFT1sW2pyZo6yfJulGSYDUt9DdBxe0B9lxBiTkLSgROMpTprIZ7/QQXxZLiyVCRCLjj0snQefcjcM47P41xprjMo7igIq3QGFxwos4uyLSY9sYdKM+Nu+2b58Dr5gJB36YFCQk6KKIv6DE2EROIlcajS57lLIzpvAyq4H1nQ5HjL36FnVlbtNvO1PJlYeVBwaZQ5jwdONRIUXORBKntbyNREA5J7vFnj7CCUxnLOROkaW7AxGMnjfisapHUc+KGcrz/+Adv2JcmNggM8CKYMcJu9wsidjakx2HS22sdE+Kme++fmQVUx9ZASDzkUHFc3rOzmFsJa3CEOF9cjmIaM4xTXQQ0YVEjn+m6ORizUjhmG6+kbUcz6Dde4MHP0GC0CEoFsMmk2gg+oIIIE3IxMK/DsBf8VUHJtv0scAtXya9D/aZ4Klt7WnHbGhHVgo1PxLLX9D916/qf8a6X/LbTi1rkGc8Omt/hcJ4fgkuXvBg8KqeE3DDwttbOTW074ZVl7hmYOd9FC2Cx2uIrcvhdh+lTqe/hAmcQdqEgj1TU37MlxBBuTpLsYiV3auxW5pIT45j+2bgMhGSHMVLJRocdyq0OLT8S6R4b978KoKyEFjSWdWn9PpDchTX4SnE+i9/foVodwOzd81Wqe7WSeo64jIqVbXkC4t6BmpUz7ISmBG5F8c2Dbvzl6juZ/G6Q/g0ALPc1c+lsxIngdheSzIFwf0JAoSyp/lBIcdAHcyRCRIDPE1hgnBjOZb3ZS9kY5EcuCmIkAv66G+H8uWG9votsXmRqFFpGxeUA3JIs5mH2rK/MGXahs4f+H08i+EJ1V/OA2CXr6jzIF7E4foUR7pFqQnjKVvyliWjfS9/tInC/8SYOrdIkV93QAy7c0JZPnM5aie5EE1P/L35P0nfYDTSRN27XjjLhiXp98smaMezi4V/SlpRK1EZ/pthtNQM1aq49YZmOFfkIvV4wC4UXr2Oa57BUg2SAjsbxrhkLPbRtQ2i0SCk+BYocH0XSnkWphsLgL9MKsRqbAgrMc9bhcfSCJ5VGhmKpPwvVz1zSO4toYw1CYyBW57TNM3Nxgg8mHHzkV7mKkBUN9f4TWfnAUVfAlmN4XlJNYuXTI0fDiEpnjqQpdctp5huIJYlaA9w6TC/4ghkMJVP50ch4WtiOIkHixa3W9qlLmTBfgevV9kLw1pacd/dRgrYwkBOMhqUNFjqNAaM9bTv3ofw6AoWM9RXaCswNGm+CNy4LsRRQ22fs7DQbRno2xvI0ydMxEOxS0MygabLjLVfy+BjhquoYEVTnzw+cWhV7yS8ZfaQ8G/lBhJe2yJf6o0InB+h9m+evwuYj6wjjCB12FQ4j+rBFYJJzT3MAQvPNr/PIPin3GIquOjEH3LEghwjXoU8fw55OC32v3g5xfrKZkYBjvX7iIwaGhv4T8zEYb/EvwLqlb0CKDClkHH1M7wAbqqHo8zahrywfAgD2r+kv2vIzAJNssLnZ61Rg7Ig6eeUDg0SaesEcibghQLvXG+66pmaxirhkE2rZnnO/IlRPBq1X1vtcoTokwpTAx2b3veG/vdRK9LzFpXyhWTu6jhe40ekdxk2OgrYLUmwfANALSTO8PLqjiadmKja8ovkmn9IxYUZQbSomXVG1e1VxK85Yf1Zl3McVnXOWCznFi/ODpUZQFYENCdLDWo7i2ohpqg9arkZ25+YREB8taybS8gdtLcmV5LWlSexSOOWYlWY2Ea/uumZpGUwlSlNHWngvbnLz8r9OxjiuAIt7zfvzT4pRysqT99Ol6LMw4ryTyT3s3tscg28uShRkZVPb7PNnEKJQS7UK6zfQRkejTXwQ0xMJBznOCsthxa1oPWbNJ/QefFwtJQQTM/30aEGB/MMCtSMoGKTlMhY8dFo141gDGjH6inUmR3UX7bnvV3luf+bROYYSDfzjl50kGQBYLIyLLFJW0JlfLhlxQIgkSwZwTDBHU7BZELilfB+ckUHi3FUPVtTnb5+Ww7ndzZgmNTm31A2CcSX0qcgOUF381h+SYWcIoO2SiLS7X0FG45IBYkPopQjUzYeUNo43Znbl/q/AmWXrQVjk61EPh7NZAAewkrO5brb0oww6ATpNk2e5sTvgUuh41e6eWRlFrsFrxbZssKzoFyaIECeN+/k3yVuEEOfNmzwcJ0dl94kTR8ccQOih6dchFQg8IOBASLDLYL4aujKpg2+0Bc1+v0mWaJ/ip3s3tzDlJhrx+LkK/n3UPw69kRkRC5p2ZcgEX+7wNqy3S6vGkDmWW8Uauidh47ilrP6IOJIuJxuaxBcAmf15HKzbgquWuxaEwKkkYkjt5c/iKMWk+9BJVKjT09s4Dq9qbMHIvU+jdz3jHv1dwG/PmyIhmLM8Jti/MKQ0ebGW2eBLPQEGi9jPlqLwu6QiGTAu5I2q6RzEFCFj5Fc1GosbGBg2QJa5cjNcamR7IzkGue06FwH6M5on/kHgPkLXd9hNDiHVQzb4aj+02Hf8CaOECsYPMW+JYPJjl66511w1JdGekX35wyhqaQxo/1DqUnexM29FFFg3LrLEo7TMotTdfYruZ2otG+PoQs6Oki0R4m7GP41/hKjkEwq+QUoFY5rmFi1TDEp7WRzR5tHNGmHdA+W0/Im3+/n2h64vE/cwtD79hmZ2ATgFZ6OrULVtBWyX9YVIJbMnZfmlHuoPrhf24tqgqfhHXw3nS68jYJ+mtpD5U5oK0aiz+M+/oILHz+lTFWFCYmHj4ZCvVmmsRbXOBIFVHHq5UezqBxBv++/KICseHrHYvYbjKQcy1/Fo4Fy+wBT76gELhuz3GoEHPNAiclI5xjevFrMDB1/murX3aCH5pcmH29+qAN+quaE6AHCuPcb18OrSkaePSWEp8Y1813aJcNdL0OJBwuihJO0p/NCvghK4l7sgTOK+bs96WUM42aV9y0DiiyG2yrIntEqlFfwhu0+cxJMnK7O3StWBDQs4WCBourIaoqoUCvmF3LvAPriVNecZMm/E6ZsZfCKH0LYo3xZzjtb8vWS7vhb/7Fa/VS1ZpEs16aR7+hf+LR4DXazxWRtw7wa5Vr2Ys66Z8BZDIaXriQjcJOlMRIxUxjbY5JnLqGAovAr6Ear3W6cLJyrx9Hi1P15204dAYGF1wlrH5tDWg4n4tVIReMbVn50CTAwqAgLEmNs+U7axdWOFChxb9+euO8O+jlg6u0233Mbm5Wrs8kThVU9klu8PzIKL/pVUmxfYBJIj/bV3eNscZwfxRTD2lJNytFfzAlrI8OqP/3TTvwLaQfgLUX22IAQJcU8gPvM3raQOZJYd2EL6oTE5nVQS2pUWQGcm+vQNaijQW+HknrjMlJBhnmodz69nmFOrGZS9f0vhsJWsCF/yOdVPzvsevv0E67SFoHchL8bD/YdcPkArbVkVjshTLAKq0jOgHefbEGFWKGLRtov5kDVYV77oWo8MYAGbWsNihsPlIJIQfXTU/8xZBdl4JS918eLactMFJew+LUuIPfHBwPzOV82xHbrXXo/siHRKGEUVO7r6nxiYcbe/IFBh8Vhv0j/nZcR2XbFj4hOiM0Jr4NAXZbGPa/htdIpjacWFg1pbNIYrHjq5l2CC+6VgoJd+eyt9hGJ1Zbdz2XxclIEVsWYDDKzogSy0Rq0OI8otmKL862Ob7Seyjnlj6EbOfFn+nvrRn1Xd2Ft/0e9YYfl1oF6PLHeudJZMB65oJ0PQkrUVNJFSfQGJZZr2LqcoLNY6aq8Dy6DQy6V1SiTEa3mcXdHccVjJXLLLMvQv7zlDKeviLzcC2ci1+8UFHDA+87dWSBIMTx9w9UOk56burSNV9a5cJ7Yy1QfvyDpemP5tl08H2ZI0InBR0pbq1yc6KG/t8X54ttgxxIQZKRIZmbySib8jwAf+halDNGKuHmdVVDwkMVk+TQaqg5aC2cj56GDmjn9udil0tsNbVFsgJT/lWyMQMkS+71sdZRdDYTPAMx2zP0a8wxa3zQQNOmZEvMxfQQX9gTQLDJfRAI4M4HIiPNNk9VmAvzuV3M+X4umD8o0wNSuAm355gRUTyVD9ge4JbJOU5QnqkMoaM9Mw9szJ85ozg/68HEQIbfoK1Yqf+Wapo2BfTZvcyc/9uemuCckBhquCPPzndOfm/C5RhEU+K/RrIdYkVuZzotSHdQF5tMVhANraoX2g718OSSOznZxmUWqtXljc4nrAd2K6qFDAuLwJ7oN4b0wFjQaiU8ofvOLEmCqQ2buWqwW6OaTzjTrJSbDK63z1sIYQfmUGoPfPe2GLcKsZYYAaX8Jx6EEiaN+N6PevLW4JrJsx5MMDJZC2K4ahZudaia6Yhblpd51VR6EyVD1M0sVp3jfrUYg87DaCBpmXcjQDQPW3GGabU3T35+Bp8T4hwqpL5UTR6jawkp/263EFLVVGONV8iIVlrMicyDl16+Ozi5zGT6qolSkvFmYOkLnlKOr83zv4akQYsCu1GmCjC1gLcLLPZV7CGxYGND3jAwOH7HxV0/QyN8xv5ER8rwS7qUjNUnWENEJr3hFl86psb0aIibK42Fq7mju1UEr96QzJI0E39tx/4AiDSJmTIEcZJ17fayb++aqY7ENGcy5FaUjSDBR3MKZnYMQHJsr2QH2REag/sm5HNfP07vTErB2gu06P2A9GcJsgMWL+6jwsdHYxm28zBG5Hnbyy8Sxq+mtdO2DGYDV/SoQAwQZXvtdzRmSjC+ZQj9stcF1q1gHTjaPjxkmu7t+33dnMxml9MyZHAMC3R7wu6btrFRKJf5TwpRXGpUoGiLBk7GKDV9olFg79eXRdN+3ryLVusLKrW1Ti/lQ945GQ7ResT2+JWyh4Ii0XtWHqFwbnSFZ5rJcsWfz9EuGCApFxaz9Lz6cKeyYdfNfJqH3/DIvTDM1hkBrtYXSN+0+JYS8gUl88KVc0F/GvjFznIVd7/iM3nzqoFImtH/X7GHPTuDGDHNFydmIvNJkMfBZzDMQUqddFCWCFCF/U2zvAPLuSjms6nxBbEtrGi48oKgqIXFVinDpX5oJpQy1GfQPDFlh9AudNSUZgk+4VBnUYWUE+9cPGt1OOjChZUexCQvz8CWNBNwoPd3Fe3UZE3/GQRNDQAmZL1wYmlzm0XdGfc125QFJbaQkBQHqZN4n/hzIBtzoKm3CZCw2msbO4aLVDbaswPMbW/1KXVpoFuwGMoyFSQSmOKG08NrZKwJ/hq4k+A/WsRFEo4D3RSMP1JA+Ac/+ZzwHde+AH3lWB9Z0GcvBRiY0C+pgFPhCBQetgiO9t3A7xTrU2bWpgd1DmkeyczhRhZH/B50ilrweGrc+oUOClBVBvMr3uEzBuYhxvTQ3qo0UYdTbJ0yuB9pL/RDhscTQAWlEHLx8ywETy0skk0yvm6jCoYCCqyiaQI3l1AQX1Oj0nh0SKIuwFeNeEHJqLWxfR5KjBAxuzU7DfTDLR3vwF6SoU5fWJr+R7RO1hDgnozg4yU2xDDoC9k8EWzdI+eNyGdZyRh7A+RC6Hegz5L0FtYTkh+eARLE+y6kIVkcFGJ+Y/7OWKxUN8bUWgi3KljNVPQW/lo0bGmmQ0e4uhsGSZeRDdKK+Y6Ogwz4JARX2n9guy4xt2WQQRGcl3QtGjY8pFlqIA2EcROEGLH27RXFKG8BuUkSmQQ2/torLj4Q0wN4OqFF5tIFkPXCNrKwhpueuhyYqsXSbRdwsBLuGw0mR0QOiF7LyJjsTF+n7qP1GtpjgO6qhr22DeQtzhBm2alVlJT4WpbVonfa1r3RXqdaTXF4Th3ByV3Kv05Q4f07y8k+D3WQaq03WvUDUQANVyiQDhZiUoy0pN/Dx4kz0Fr4bYQ6FxazF27uFjSj7gJR34+QBIIoduqydDUGavaWXGyOxZ12PCHaHgtJJsGqW3Z2KNkaK/5/Iu7iTyO/F8zAaipYhBDg/BTKcJSOk8nRJ5EALM4v0PuYQ83vLbMejXL3Fa3jymh3Ibw7fsOTvydZ1jtDPc4Kl/3I7yROUKlkx3VZdOEYeP4y0s7EfN2Cj2uekNCKeSFBhIfKhn83j8q/UEULsSJSWOQIac/P9gBjcUCdLPgaGTMN7pnkO0dxReQ9fUMO7wZl5XxLDNXE8slrl2VmJqa2lEhnTR4OGXYgr5Qc4CnnKPBXqOmsIs2KGNToyszLdAFI4U8dvRv0RRGB6zAe7EbiYs9BDw9f5hk0gLOLsvEvLFzBg9TyoYm3IaozVzOEciouhW+BV3OYIFmjXk+29PvCMUGwWpULjZwqpDNxXxGuPiNO3/srFLi2oic+TqeTcm1gzummc7z6rOFAca3BlysZ6eVb9IDI0qOXlZcvuSH0CVipiagr/6jn+C9vagkag3FQ9t4VEFVE8AqQipgXIDhdUZ78Bh/y7WVBEjdX2jFPareUQl6ttKEfjFb1TKqw7C5FCxoU5hGGDx8xlypylNus6RSGO7wr8AF79I8QXvFq/VOSzZBQUOI6dnPWZ8JYtBz/ul9jl3fRgjA4A443esfWqcaNl3MMACyeoiInqg+Pqrhr3DZ7R6j2vxzLI19IL9jNi1Z2+As4P2E/g7Qy2Aiv81j3ne5IbUB1KoU8Uj5ZsvDLLaG+HmD/Gzg1g7ipZBhmezNs5F5kemWOcjpNNvIDni2ZLVOZ+B57jfw+XG9JKFHBSesA+AF4C8bKkUFWlWQr9cpoTNIXq96Rg92unq1K/7OCtH9hjv0k37km4T5jYZ/IMBMCTF+eB/0PQlqkqo0uuMVy5cf9ek9wSxQLuwtk2OHPI5Fi35hzKq/A4q8lhj8fv8+QjAZPfaAAkXitATXFBIWgc+1eD8V0H2pt/Qi/4raB9L1qvAtzfkpRlGfWvm9kC/qtxukl7CA1dwK8qJd5USA2De01O4Y7IzFn/dEBXsVw/f7TIaPDORPw7yhgqwzPQLfMCCb9kmeoNV/XnJkZf38pIkFMJEV8gLZFZZ0jnNLkly1N9Vr5YGuM2i9bjZvAAUqmpzQFtSGcSEJe6jkxiQltkKDf2D3WghAd4Ne8TFJ4UscH1ykJF7EcoWD8Q9z5RvuNSTFd1T/FFIMB7+WgEwvvmpi79YQS2EokdAUqZBnBle7WaJvzCYT9nJK8PgjrwcSq1EWM3NKCuW+IEyxAlKy5N0hx3we5RUxS4V5k4lrWbbnHhdtTzJ2YQuAUGV6CBNx3QRq0Pr7aiu1VeqVVJjM6O//X0q2o5dz5h/IaYmnDAIVnsemyl2rRStgnvUvC6hnMjibT+rvOHCI5ekOavlVi/KMi+ZwmMnM4nvgpzAJLs0zCy77GWx4d1Stgs5te0UzYYEYGsGJPnxp0VJrh8sed7QrvLkeJQtxHmHDOGn+3biKpzXvoiWYZcRyqCJGmZjXJ89+23z57xNNudY+v6dOn5jFGlTzoTMRe9E2N1E7cfA0XHqoZAZUjfdudKejdKj/95U4nJJKO3H3ZJrBSuJmbxzFgicDaQ8xWXPOxjCvvPPaIA43pNTdLNWAyBV5/WW/PyA5nUa2Fc1wYpGvngCeYGy/36L3m2OV15Hqu0D9ppddm7/KXt1z42YE4/6dbpgiukinTGlBrmgTRzgWeGy6wjapNdPUaqwXdTBtqFnfV2fC0e7RWrEM+2Fcjjr9YWjLO7ZhglP+aMZZQZaF50FZhfQT/PlUjVgNBCDCJlOEVVrDHOEiIZHoJ8An3u3ipVpodTXNV/CcWHyj1sDEVMTGWqUhseiQIaUwYcNu72+SEXxnpeOjjykj0aYZ0SXaLhB3vrYwyK5l5bFF4RWT7SYZBsyQfY5jCRbCnTrRmThleUNNmH8Xo6W+TNvjk7wbBIO0hyiAhlFrP4d9R4/kAhI9V/oge5oeny22P7hjsJ4M7CLWmeurrbrKS4cOPo56xFXyiopE+XLTbzUVbtpkiQEzQkFJaxmnescuZKf5AVe0CEW9cV/GNh7p/G7sICtMUr8RdKBK06qW8i2L97UrPzuCCwfCms/zxAVwXXn3kveUM5omUzmv1KmbhI8pv65VxxZw5h1/RULjPEMzZk5kF0deFcwYMmQDETgkyiLkkpHwD6fg9KKolyZw4tArP+PZnFF0orH0CRpwiFKP5uwkmVL+/lrweTQQMOdsyWOypHX239eIQ9Z6riZ6SLpV3M4BTNgPz3KO08G8leuDLIDO1ZqBquoW94z//nC2u304KEJNIMKTo25GwK2qWkiCbvW7qcOzMBpDsE2UQ6I33YttNn0kNjIPChEedYcACwpp0pHIMP1rZob3jh4AIm6w28M2Jg0DuNir8LSto/Ak5CRR+/dFC94Fh5FB+qenNqKHvuLKy8UpW3wuKivttgN2yr4rGFxCKlvjLXXyLHRvvP/fxV413UeaB8V87aVrncT9XNDs2Wl20EvPFEahexe5rU5V9Vr5un4oMiUlCNjQ+1Flbap54Ze9p4VlubXGnaK82e7eaf7FD5VNlgfY6/Krt/yBN4MMdmYwB9Mp55uzjbDJ/fEFnO2u2WSORv++xa689S1jNwsqXGmcVyYj07y+lww89fLjLgKbmxr6By0ZZqTjWLv0EEv52ot/A9BDYuI0X83T2s0VYh105wFBdrZgQmn5Zxa5107bfXZxwOPolbZx4yz5ckQm0rc+rE/Q5VItx3rkdplT0fwa8Ze1xdEfcppOcTd/nxECZNS/l8A4ykBVsOyEUVv1EAXwajBf8KK2vVJ3kNhYRo9pI4lZW+C1QbkAZwZi1z6cxFApOk35k2unlGqpTINFFeCjdgA9HLNtPEd/Frzgd9jIt78e8cejLKsoJR39Bpu5jIk1JrM/T6o2wpZ1hU/TBpmFu+J1w1aNRx8J8z73GwPNjJ5O7Vw6V3aWLsAYj6bvw8Kxhft2/NyVsdExINGaSYcUyvuNQ6WMi7g5quvW9s74flwf1FibUgsjDswaviV8ENxUgw4oh00juXdtk2+XBt2PdAO76GQH2HkkpQswD+94WOsorNJNT6pXf96Nxof/03SuMwNLsYUP6c1/iBiqRe/fX3QGfdbc9pEmo7Mjo3ZIRBynOzRqMWXoRtMTKB36AmPLXv9xhXuw3ZxNMJG3XM3f+//0FXHpxBMts1IfHP4BapIuuhc87YsYAR3n4+DnM9vbEy5ZM2wXAhkmyFY3Qg/sYdpOeSsrL5GbXdK7bvMZuWxQtYD9cMlfhXVnCwz7Q1rgik3IcsYiyjyHYlelEZd3aAozbzeOz077zgiY/GuAJdJ9a6kMs5cWtXpejH3VAX/MlMeJcQ7k71IJsFFMKyobTsOOnqd8jBiHUv9AL8wl7iH+8/Mxa/IpSf9UxzZnBojXz5UWMYdh0slQSw6NzKwG2AnbbY5acbT7ZBCMwBRadinHm/9w4841s+CjwXfqsS5n2NTasT9ukrwi49V5Pa9OcCV7S1Q72VTxVjZgMDfHSMV6IohS20Pui9iAnQvy23YjdNqpJogsMjA8QQ643LXCdb7LsOYxrN1OWHtlbzSjgF+XCPglTo1EyR1OnEZlotd3rDgoOCtFhxqjMMVs9NFnWBz8u1pkqfWGVfZRNsq2QoVkEJyi7LbvOKeNsUFvfDl/WdNBIjREKJp0aypC6mANmH39fKMx33fvrdFYm9EakSc8wak/IxvaiQK5/UajaXFLuLbmKot5xBIEa2VYCHobAIVrQsgYg6eETw6c1kviFmmBAJ7wtvI+Po522yEH2UhD78zc6eOy3xRc3PiDmK/UVvXQuxxkq5lhCOp1fdBEAWHRviPEHfgFNsgsnlh/uLLJoNTaUyhLGIrA0AnviVVQTj4nHyaNBRNwS8C9T6KXrtv5GwQ3prpE9j9/ZrdJHf0udviQGmFzgEPACeh5RhUn8kAMhdSsbGNHi+7eR4ebJU8tmbW+DAH4RRlx8HziQmtxWKC6f8FU4iwq7MhTsvYJwKgafH9VJnAxaWb+8iVqW0JE8iN2Noj7eYbZmmIE9+WeiWBPy/32dWG1yorG6XJOfKzOUN3ECbaKCdRdmjKvoTUmLBzBCaTBYHm/tp9b9u0C3hgUWwddwqLr9Do85wA1W6WxuKLtTYEYIdkd7jI2LvFhkZ5qF/JRR1+Pgw5j9oBDV5s22GVH41omxNuc5mwjUIGzknBTQsP/iw3OfSzGQAenx/COG2TyxNzvA4q70i+KlaCHwCbTugB3Q0rX5ms6eXppVolqlF9Ep3mMRjEtv2qfCMjvSWCbLrKHgcwr4MfHdKoWcP/Gv9OiCC3pe0eHlPcuo9WGYgp73gyS3+kUMrVqSPGmOXFN/up5G9oeIcW0VAN569fi/Fa6qiB3ZDrnNoMBzU69tVzzpYcDuIfZDz8eWotRencmhC9yPhjfByHXQeUPsTuQwlQptZbz4s328Dp1NFKnDC7cg+tSwScjysL8/jEMNOCafkXGN4Y8LzuMNk/y2IVlgITBOrQszEcyQnENFrEjGlEubggN12bfg5Mw+ss0ZaF848avY9fweH3FeYLRKCTrOFacYwH7etejKl0L3hR5ismLUdJszccIGw9HOhrUBw08E5401wKVEmUB1HGYnmm0ddNZXVVljqaRWAHhDvrSID8hE0HZG66np2g42ia/nsIvV/2T5uQW+IqksBzs+8Nmyqt0ikQTrV2OfBfrBXX5kP1RnPlA+9nGLGBH0nZl/tTzbDUdZo9oRahHjjL2VZE2i6znvg6aeUMNvFCr1/SkEq3jA17mOgmXAingSa3AwIdfQHAMmVYnrn9gY/m/C3aPoHqRUWtvPt1reSBXGY8PN2VXB7djVutJQS3TZoHp0fb8ZZwKs1UjRWmgp7I6Rzjm11Y5Y5rukqpQAAtrOj3lJwAoOl1a5hQfxAmpGSvnP6CvdcktaH95QcO5PcVXcmiFwDgfTiHpsCdR7bwM+vjh3vJTCbMQucUAv+hASU5MJSUlM0rGFbLsAAKpDF0BUql3vZLoU4tf5sBwdQEEpesyDQePUjPbGSkfuDrNzZZh6pb9L3oskxCXEW8YuI6uEeE1COCSzV5lF2DWd9LxRIPox/8WxLH9wJO/TGPjBX7u+BrKHYb5jbAuyvwRyK5j0WOLYgaZ6Q/zWbpRpLgAxZgq9PocjNQrClhRKxlB7aPLluHQVXBUK0UiJM6fUmdgfGde6VmXJX2w1xYrmV3NDHqTOD1Zx6euCBO0WxM/RjoWBwi1VRztCI1tlO4Lko4uAxFL5sJebZrljxwRzF9Zv3g94SdTMZjv+q6sETFxg9wwwDRsTkYyFw+v2sVF/NjXNauKXJp+B71JJVMtVNfezdLnCzAueqpsS/vooZv93MxTN7/qFghzSPRiVH50yGSzrfMmQlZGylrfGxKjBuUKUYxpJ3XIotQ+kXPtLELS1TatKPH3ChfW0JoEvw+daAaM2N3Hua9enCddg6MPnSdxJPJSWlkHY/j/n4z1cjWF+Qn2kMpi04Zl2enUazqO3RXGdLwf2Q0xZOutiA3iTzfn/5raR96NbZ5wEvn5gDDYpcAeiX7PZqqTWyHBBWd1Frr44X2UERIE9ZavoVzc/8vDc2eoU3QBNSoxM2VLsVoN4s2qnOCvXlRvcg0x2krGSj3IVk6RWoXCe7+px82b1pwkMyf/1cc0Zkdf54T4qxzNrSkR1xXOoj0ogfl0Z2Uj3OxYbkB9/C8Ee/ey80oqp7Z0zdypaPv9qXNma3S2wfYGAb9k0D6Cxhg5Yj9lbZRTBMHWczdLJMd3se3eQKvMTAmwCHOQy4xZ07wWhIiGiAInVC0jaITWNIn6Y90StFfHfG1FVyF6cqx2G0ARQVpM1i4dnnWPgD8dFTxmJrR99RPleUbP6X+v++aQL5bjBWgOtL+pSDdFpsNWaItSJd9jzLlV2mR0oZKf7jRkL0UtB8PCNHaU15I7KTEZixYcHPSJbxzujejWDfVymvfDn5bdkCw8NF5OfJYjVlXnzXfosBbMEoc0I/E/os4Y6TK5uYTl0duk4NTjyJocG1FwlFDhqwUp/JnJw1hnVaEoo6dytBHdBAchWUCARKLatBIWlxkq2ja+jC88gAUIgmt/T+TOBXTqtq1S6bB2pJPVZ2eCwoXxeywkukRhpTWpxVJykFeomXOsqIslRrHsiBLxq5FEXJqiA7i4wEiCG4+vyoYtEmosmeC+0wbwb7a/NQ8ipAC2pWgrP43oeL6EeUgz5wDa99gw4gHQcF+lOb2HZvgue+ExIuqXh/9bO6kyVTZl4CyYCLkxJYbI8go8RgywcDzlUpAZ1Wu5a0XAX9vJ6p90ZejV382AcPIn3iKXd8BKtIpSXZj+sitT/4CYWmyPrLbGmtJakXSxQiOoEFT6EOfQSVx3tyH2u+Q1Nuo/q2d+yjYSAgK8rts7ijL2oerXT0Ubx5srRIvkYfG4kISujCadponNAZJbbwdyol4KSwgNMfbxGEOfrWrrNdQjPbDB5C0exTb6gFFGGFBiBxim+qdZ338ydRpVqbwXnO7DvdFYKScs18mL+osY/xQmNYIgXM9kseqNjTZ7JBLAsADsCTM3jayZj6Sb79QhIujuxek2s/DM9K/knWpeu8WbrbMAU/qXOvuj4iSvIYItkoLBccOjbb1+i+gUfyRzhCDZ5qG8DMsqYjX9Qe0X4hOjMIK7xgYEe2PvtaUyTTGdHQtedhXttovJ4dIbcMpzjBsRyGzthLN0so1Afkbxbg9sTKTIXRWxxto9AcvjMBAu9MV3vx6f8f5ukh4yUa7+bpMyVizdc5bBrr3u3pI2a/Mwni0708nMIlMy5oamp2pRyHYjUrRWval5wOnV7SLRTtEmL8IgVRPS6TU44EgDDj6nRm8Tpf+1IZPaf4esQ6At/VeiyCI7TVwgAyFWJEao5shxknf6i4MJsQsCbBlIu5XdFzIfkJtaMUnR9navjbMT0SfrIkvql07Uv6SYhR2px3hcSORLJTnQX/UC6+XaX6DVyBocKXvHDEQjUBQlsNvHu+KHwn5pz+20ZRM+sN1WDhcdh+UD7u8ThG3UGj2ZHIn/UotjPnlN4DXijNDykOpEOujou+Ppkdxf/ylEGwVjAroWE8otv7YveAs27okL6tYGlakyt+q1Y8yojfBOEn8gTR6Z66TnwZ+7Iem2n4IZr3YgxXfr1OxtChho4dRQn8akermQTzLAm3MrY3qmGq9Dt9c8u803VPhzV9SiViyj7HpbqhDXFjf0WKwHfYj1EHKh96oBIfbDMKlIrzVlmt3Urj9etTg02R0AbLiUf1chGILN0TnUGZOk1Von+rcpv/x8kgwQ6/AB9ns4t3YXcZEiP4y9RXmTLfJ5LfwyzufjqUOtXuWnTkdSaCyCkIO2Dtc0vZ26U2uxJOVeHo1kiGeuCsvtHsBsJn2L0dV1I+/IYsMmCRR/i7tt2DZtgphJw3NQp2BBaojQknfgFOHPGbikSkJHRJ+n3PSFuAapNlq51EQm+mMQJQcrz2RRyQWP9p4twJaxWFdDhtehS6fKzZPHAuI6f5pR3EGE8OtULtEMCJYLIOQFpGpuNx60pwy4/5x57qbOahJt2gmL0z9lLiDo3hRF+DgmR331Al9KGvwsn1tihqPgaOA8CUtJK4KZQTgQfvJ/AMnxsVpsj0JOkCKtZKAGGY9niz9CtE8e/9IGDPNfIy2qwJKzdU3YX8fGvARVOiPSSbHP6NsGzAqIudAEotGgwiWCY1HRBUAVehEZcn89DDUhtqflaftkukgeQwuPLP+j1HtwbUXy09OGN692E+78+JORE6k0ptlSflhg3FUleorb9OISLee/2zgHSLUNFdBSVj1652Tqi2slGgVEwbQuHB8IDTP2Sq47XlFM2zzP+xC0fmCI2rj5Vdgkd0CGboQPAyAPK/lzRpfUc8K8W/wTReBrFRMvK9NQZfXl85p4n5aiyhk5KUe2PT0p0kHAFHfdEIsmuxnkCH2pFAj8VHCg3rW0rQK3FTMrQMiXGDF/O9sNpbw79zM36LXVg8CqioHyRJ8BZvaZVLzrK3A6QY2x7NtQeSoYtZ/FSZMAU/63iwsrsxo/mqkbKj6SH4Ac9TJwY7LYioH8sW6dLs4pn3BihZwpL+zWgogGIqmJeNK6ofMGfyZ3Zl8kNyjAAAl9hABDw09h9a8jXHoVzfxXA/EzI2ufcTtdg7++IadIGiITWmV7Lfn+FKeFvISObARqpeC65w3kZa7o21+zlNqv9UDMH8i8RLWpzASicnOsswVIu7J3usNTpvc/V5cNxlUWUEO0ID9PfyKDhSFHqyWibr0H6FHArXAx7NKz90L2QWnNz/WPLwmix5evwdymFv7+aanCszTC9u5cMM6CmhbA8hH13IztlpSQGfqzqkekip2o5lZ0gAe58554zWQ1i1e2miiT2248I1dCh7CqYBG3RFAi1ahpI1GKj8TGA4gFK/rxcuHshjGokoqkHfkQisOzQy2/Z4UzHbSH3kwbmrJ71aiVJwIfap8CCt9vh68Oi7AmOqdstTru086L9D6xE1ag5wdcfiv2AxljgoIYqjGweOPYv7MIwYQ8p5uBqU0J5yG0ox2A3CG1zPxnVCImeG3EcjJftNLxmABOw/d4CTe76da+6mxRr6cjXiFTmNpOBr0l5akkFlV1OQPPWOF15SUV/gLC29XEYITUxOOjDxMEUMJEqoC/uGQK+2uLv7ZLllSOrio2BDLASbKp+zx5qJz7FmRLUnKMI39oVh+ILJUzcpAvkd5kYOs0eO57B5gbninZXV1XOTrVXCwRSU5RuLgETdfaawYYleWa4z4LnyviPbY3amINnr2GrJut4CSiWYW3wKu/E992q58psMPH9nTL6W1qKUE9g8+TgPR53AikpQVGL1iogdU4r5HW7pNlQ60FYYKhlRLn2QmSNBN6N6evNK6VRXB607zOAQ7OeDPtvGbOpuh5+1MeQ3fOx+7f5xr+Jhz4Rxc14eAngXppXubzwAqVgF83zFm5za19f6MdfbPOqeZXJwJt+jPPwcCaxU/aSpRXeORO4luvwezBNs57xIvZ0Gef+vGcO0BVShWC4FfUuZER9PmeB/Fm4IyFPnorn2+86hqlTLpREn935WnwjyzAIcOTdropTsW+nnA3m5EEZ/j5LAjzFppmCzQI5iheoyf068ckGkZmde1bmQFE7Cp0N4EflI+4pU2luc2fOIIlGkPuQ8Hd+rulGiNF71H2HdUY1eTJQG1TTdJRECwH2rTjH00RjfmCZLTdAjCmsF9XW/ZP/H9XiHnzupKNCtIqiiA0NB3gW5y8h+Z8ta2A8BUvJDsIX/M0aUryWDqPk0K9ZeFflsg1eLK+O8OGGjQHdCY/RHjNXdSK8wUe/0Mgrsy+TyYts0nmtu0B79uMCkz8ADvbUHY8OfPzIFMxB5CoC3GlTaySm941vRhdQgqauJHDd31rNqV3wCbsKxbw/9C1xdfqJXfmAy1nyzCI3m8N1ku2Tjvok+L/tPDGceOnY2fyYZ6yHI8CSWtjdDgUw4rDEZq/LK3XGjRAeoaWQZyclgkBhJN8BimD4HQNSe+J4cOgOyIZYmzYAPsifrcKe2Gk5/MWPcIyU015LHxkAAjbe2p4lTiR9cT0PyjydCeBsaPxWRjmYOYpiQ4B14sCPuMd0R3zjeLkWnFwiDcnGXq7art+MjDinf4wS5jP8+uHR3pzhLcvZ52bCERsazvEEx8BC1X1HhliWUJ99PKPmlf3RWJhfuELjOjSHKQngbNY2DkUCMCqEz/BXj+Ji5r/fHCmjD0R/YE7fR8T7lpRH9jqHkoQEdNrellg49rMpSu+ZgRzYJBNOiTC9yNvDZngfQGjz5mTpS1wZNaLgmkAjGht3ErDohRTXOKLuiDa6jztbd9hUm0z7Yu1tddGc6bjTCxAIEUVvlgexaxE23B7cIMl1aizFZG5O2JQ0Cv0V+GVm9jpZXF2BSdOlFHFStIVK0sLIyiEyVLJqFkiq4TgEmQ8egaqkUKuPJwZUxJ9o1rHj4t8Y+uFh3QxvzDdWFzDr+T4fYc7oWTgcO8QqsJCpCnV8XasCqQQ3dHnpD4i2eixZQGNuNr67d+E+qEayNQ63LO1/X2WkX8um9kKTLrA8z0/KQ8kxfXXkb9zbGhH3+1NDceT0oEm8HV9D7nbqf0tEXvGBWRtCc3e2Z4+wLAx+ZvD8XTE5eSviG+HZflnRZ68rDgaVCNhwMH6obBOznhJ4U0gzmYodAHj9NkYBH2zb5AGMnTiwPPiKTTariyVPPldRbA9UCWvV41d4wwbopo94nZmh0lqjYBoN1zj31mqRX+xPQ/1N9/K0oGwdDVf790zQdsOF0dMmr+DPrLEiH5r7UFVrx2yNVt2zsfPbKJIO5HfU2XE8FASJopZG3aYb/tZPqOVOXwaok5NxI6YdcWd5f33aDoP75Eu48Lz8N6ffMT6so5H3eN3pgl94Kb1xOfYiwNtQzmQDAxLPGEJjWHLZBOPCA6ttol7rFA3pj5eKnzn7K1ukRM+/IxihO4Gr2udK7oh9rTHfWruBxO+gaDhZrLYLSK5aobqJPF2sHN/OIwP83ptFHAWhgO9uepNv+EGPPRSW/hRfJyJYHafSnTImBFjpKUu83ifko8abetY3ef+AueKuZMTQUcfoECqHldYIye4/IH+cCS2MRQnzn+7zJAy8+xXzg/RNSTJVW2kqgwtBPcfV4AIx3Q6dzAJoVAR0ymGl9eQ5Zlk/rfe4Zv0KZpbKutu1cpGmxFU155dHifzcEbdAlm4DzcCpnS3QLaNFINB7hlYlZqsRS8PzjOBWYrofNVjSv+lZIAdIhPZypLRQ7gvgoWHa1vauIt4cLRLKRksioD9Pa0MVizqh8s40p+VaXJ8GcntKKccQUglIQwhWJAIsca8dJjyXSY55w0FKt7EYbELVxirnhW6HovELpfDkLCVv2x2luWvJo0QFMgeTeHDrAydwxSHMSUvh/iOvYr3qL951c1pcy28KIeaTPQsWZIPoE0SNAJeSyD+Mw16h/lz4E2zg1ZC7ceL+HpLNkL9+vmlmq/E6rTIw0FhrpbHjOUI3XUQQMT+hJGsuEdg9da+RNUzioufX6domgxIZ/MWaT4lkGzYhg3crK/C/ZEPPVXUQQ3SIW7QNSzwpz6HHeFLjoiO/i1idY/pnui/nEIj9TV4qzun8MkdSq47TlOHmXI47i1HDGGqPT49zeiGktIeqrSLm7T4VO0HaE4NyEMFYsZRUHJIBdv4j2WQf6Vycdp1Yr3yNjsW7umJ+/kzMNB0LxH8UTWnYiV2xQF9E5mEDodzxnTRa9Hb58Ke/wmj20FkcyhhvskOuCdxL8Yg1sHjZgcibdlGnoL6DS1+Hh0GLXL1hVflNKUdWkAWU9z6XkSwwMJWTCJlUhszrDBaEU1dJyqwMmLBDKDd2Rn3/ClATIBlvVYxH0W7a19akk2BOsP1wo6Whjhz3tTE431gf/7hbeXVpmSXnk3XnFEkgpt2d7T0ZfGkvRUWSJeHa+KM5dOQImDbW51h+oEnjpy+tmlMJ/rD9PhRLzH9cx59U+aZZ4swwPZ/1OhuDVO64DPWgFXLEnCQ2ogAW5s/xivCWsWEi2C/o8UTJd6ICn+RpqodG2ZmoNLSdsyu24J3aDbHXmd1CqiBMCIQOP8qCbqjFfSFS2HzmrGsJYLqlZygvELccta89Iss15NMy6f76xk5ew7FMiPc7tZJq+PuHKqZWznwm2RRAG15AogGjl8mgnfTQfqQg38MeJdqtTZgb9tjMn9AFr1WDkOhRf159Q6O8sPCMl6EM6129f5TAto3Pp4+ihFmglhl6W6+QdGgUjNhXT0sKrE88hKdso2pIFz9Lq6HQQX91DrqJFtTV/fPYR3Km2Ktl/W8lv31iKqYzq37nxJ2JL3kC7sR8etZn7LiLh14P2p3b/37LqvbmfbCQSEQOgbnE7ad9QtgsAvtWXJPu/ar+q2b6dK7ZTLLfR6FBDNrXaBnOj7plJdVFThMnde3yy8xo4atcYAGFhTj/aJ1c/AOV2DsdXMIed8i40TBLRee/G8MfCOpFc9TWsiEPc0Y6q50j4CQxtzg09CxhV9WrH9yDZZWMFr9nb8MoXAMIbZhBYFMrcX9luj1w31ZfEOxELjmr4a+4jISosYATTJKNnFpXH5PJVfgsENjbj195xcpZUgz7u95+HFErRR4maMaaMx1y6sIkif87QfezAF/kewxJLr7+iRrZ9Zgib3MqxqlUhbbiLEpZyJEQE5GfCmuKDfe8I7QzYu7H7wdOjCao9Yo4GbRegYaL96Anfs0QDKOx0ZkbFJeTvMf7Z2rNZAsMmLqBnp2bXoaGX/j06LdfgvACiDQ3rSPDakFlekcXKAaUUKw80GZsa7fxb3pRBsRG572cuy8jdWjlCosRFz62soHNsxxxTO6fBl2+M/k9XoT+AoOdo6WlOUykd4aOgQ/33fxBBruR+997W0LvJal9BNitX261EKOboHh/ZU+ODSnzjTyXZagayf3rtEvk1UTQhTstHSHI23wYIbGWU7WchbwE9AyE9Jr8b6fcv4mJHQf/A/rFwluKIYl4SkTSGvwYVnFQK1a9ZUVa7rQ8kvrYV1CJPC5T55cm8PRK1kcLCQu4VZWwrxE4cvIXmZtZEOVGa/3k/dQCimcCyEs8MWQDY4Qerbea+WCTsraNEt9hdV2GAJvnx+6Ba1h++HbPXNs8D9pmcpGlG3OTLoqE1L9XJRkwiuMj2rAAEZo6x1PcU+HFQ93nbwn+5+wmo/LXiMidN1sUXDV1IP8izk1UKePDC838+U1Gl8VMs1NCG6jse1zB10r5VJWz2pATjc/orlQk4Pi9uipxR9QW2+bQijqzW/2hNQvJQqvNQmxOZ90AqhH5m6u6tRhcfKy13bTKdgTZYwgaDjICo2eE066q4hEJMdmwcNY8yx0d9J0PdaJ3eVvz29py8ti/AZmDAhRkPPXdgm0qbK1LrK0hkqqwmxzg6EMSDy3ohKzhd8BzZ0WayrGBCU0sduU9aJh0ds5U5gKnMRBUSWPxlTTgTIkZ6kOx8LJoOMGXHh1Hx1ljWNIWPCkE069NKTh6Pxwdb8CafruMF8FtltKkETYfKeqqtyn91LOk4qiNJXe7K7z0d/nDxYM/sbLAzsqrcpOq+bBX4Io/hTyBxAuseYnwtPadcge5YNg0QjiAYrWMjni4j5oTs5B2WjfUr0lu69IYabO3k8PXrCg8jvR3P11J4GVpdJnWvLBT0j8YIJsZivjZqL000j6r03PV7LpKuS5jB5Vplx+Kc9B+bcTIAqh5niyzWsx4Akf5vjBdJc2zfKytrZmg4OWkc6XMTxoZLvCEmqzrSh4S5EFkUcYLyoWqTNwi4OCJG+flpenIGP9r5v+gUmQFdLs3hreHuLbW1JUt6oU0Ajv5NTAPf8VaKoTas8yAanEjgguoH6WDuFQ4M55k++8Rq+wni/GhxbPONKuq3vgAGgXDQm0T8rqoSvrjNcgM7UZuNZkPZYIlQ7etWfQDv4DlaXha4S1WU8qWOiXRllyjB9Kp45Hr1T1l+XPlzvArTrriJNpzRrvYNkvbxAtk42khgG1bCtXAIIgM+ccPo6ao5UH0pCcmilMs2k2YVkTYOqeGEtEIBkSg5ux20iGy3ZN25lYdlqX7hh42pwPtgbN6Om4x+tVxs8T9n1RHRiI44OJ/HtkLbwRM6xX0qEshFgfPTCvgX4LE4ffX1bqUf+RgSOzsU8u0N8843rUO22zl630AauE3Q+KK1QjIYwlgrCXJRH0AHx0YR6zqx847+jVzT4JEjbLagqwygIYPMn2BV/VlHxZd3aVFBIr6izrKmR0SqhR9uqJQ9n4FAGxZ78prV33URFTVWAvFVWJNYKYgODApbn0xJNcHhCNK07dbGE9oHsA0gCDXOr3x2MK62G+EnbSoS48wdViDkprF3QoGRqZeZvtZmVPzQXXkq2RAr3vHqN9ikErvqqN2Z+8NwNZFsPY25/FpE9L6Ch/8KINeS6S0DSIfyRRznHsOaPGj+FzosyfiML31uAe3XAu/CeIPjFXoBe89nIr+85sbiRorL15/ZGtbvxahm8+VzkmR3Z8oBB+iiMX6RSPOLvbE7KuqpxiO44gnZdOhkUvEJZpa8qA82lJWDK0ckh967GE/fTh7/IyGsXusnCdSRDwR9dT8qfrzXo32sbvu6qEo6EjnFGjYwr4+uP9EVDAo7SysH17NEdKi3A1PPu9VFuFVo+FR/IH3xOBcL8TqNjkShvVOPWMFV0Vq82h09IGPWwao5n4vsLdaUUljf1rwiGlJXQkTm3edf0VHcG01IDl4pNVqgi8Q3RXOmF6O943uWVR/tDBTdeKIZV/MJpj51gztrHtg06IPErkFWquJKWBUPzlYDpVMsiATgK3Ug+syIQXaLDqf7eUkDX2+KLg/JKCXPvdqcicuLHgL8L7vHebbHvt56vMWdP+So2yjBHwWUzU+XztXRS73nXc3RDCNibbjNTzquRAylNBQBvvSsSlpu1gsUFzgorE4KZ57S11A3f+ZxsJRX/uHpG3syzHx8lbDl31eSIEBXo80Y6099PN/OpsOUY5eYTTsdYVf/Qbgd78Qfe232vOWsT3Va3Wlub8oraHBhTJ9Nba5QA/ANEfqnElC7uiXGl5BX9+JVDqWl3WzuLo4JoisMm1VFF5EysdQFNNz/I+cbKtKhI6WoFOjdZyDK3s64O6IEThwWYsZs2MxSNX7hp6vdWilmw54Dvl5HOoi8xEk/qAWXwp5xa5NnucG6A+Kgow5w1mFbH/01MlDdGQBaHMbDmXikD55/tqJ17Ms7KSDwt0wH3GA8Lq0/wZ2VpKG2edvCK3pO6Aj0Qe5UYEp8zxC+lVGeOQLeyioZZEOpACouTiqzqH1+NbuK1tRcCJ6Z0rKKS/ZjJGox7DJh8DZg+kEfbN0giT/Cw+84wnwVJEVwdJ/Cz84jwoQrR8R3dDQslGPFa4f1oKcZPBuB1h44MnV9oNQjXBulIZB0p9z+NESQX2gaxaESsbvplpxNCdGcnhznixeuUyxn8cGMipBvn00ClwP7nAPdJAdPtONPVyue2Fw95C4B+lyn2gEd6IGrQOjHfstX6EI6vbKnF1AbgsbTrbJrQ/+FJwnftEUJnuJcMW0iSjbJGwSwcHjy3391wbR1gTGfNEHqzm4XGru+ZfMz0R+y1aUJMlCatTHWuBiN4HJjVhHKRQDQHW4rhjXuYj7y3GKrQUfscD7pVOw==" />
</div>


			
    <div class="revenue">



<noscript>
  <div class="top-alert top-alert--javascript-disabled">
    <div class="row">
      <div class="columns small-12 medium-12 large-12">
  		It looks like you have JavaScript disabled. Certain parts of this website may not work without it. Please <a href="http://www.google.ie/search?q=enable+javascript+in+browser">enable JavaScript</a> for the best experience.
  	</div>
    </div>
  </div>
</noscript>



<!-- New Cookie Banner 23 February 2021, Removal of GA banner 
<div class="darker"></div>
  <div class="cookieBanner" style="display: none">
        <div>
            <span class="cookie-lang"><a href="#">Gaeilge</a></span>
        </div>
            <div class="cookie-overflow">
                <p class="cookie-title">Your choices on cookies</p>
                <p class="cookie-description">This website uses cookies that are necessary to make the website work. You can also choose to set optional analytics cookies that are described below.</p>
                <p class="cookie-description-statement">You can find more information on how we use our cookies in our <a href="https://revenue.ie/en/online-services/support/data-and-security/privacy/use-of-cookies.aspx">Cookie Statement</a>. You can change your cookie preferences at any time by clicking the Cookie preferences link in the footer of every page on this website.
                </p>
                <h2 class="cookie-necessary-title">Necessary Cookies and Preferences Cookies</h2>
                <p class="cookie-necesssary-description">Necessary cookies are used so that the basic functions of this website work. They are limited to only those that are strictly necessary. For example, we set a session cookie on your device to store a session's status in between http requests to enable better performance.</p>
                <p class="cookie-necesssary-description">You can disable these cookies by changing your browser settings but this may affect how this website functions for you.</p>
                <p class="cookie-necesssary-description">Preferences cookies allow a website to remember the choices you have made when you save your cookie preferences.</p>
                <hr> -->
                <!-- Analytics Cookies
                <h2  class="cookie-toggle-title">
                    Analytics cookies
                <label class="cookie-switch" for="cookie-opt-google-banner">
                    <input type="checkbox" id="cookie-opt-google-banner" name="ckbx-square-1">
                    <span class="cookie-slider round"></span>
                </label>
                </h2>
                <p class="cookie-toggle-description">These cookies are used to help us understand how website visitors use this website. They are set by a third-party service provided by Google. The service collects and reports information to us in a way that does not directly identify you as a website user. For example, the service provides summary reports to us that help us to understand which pages our website visitors access most often. This enables us to keep improving the website.
                </p>
                <p class="cookie-toggle-description">You can help us to continue to improve our website by turning analytics cookies on. You can change your mind and turn them off at any point in the future by clicking the Cookie Statement quick link in the footer of every page on this website. When you save your analytics cookies choice below, a cookie will be saved on your device to remember your choice.
                </p>
            </div>
      <div>
           <button class='cookie-button' onclick='acknowledgeCookieMessage(event);'>Save and close</button>
      </div>
  </div> -->

  <!-- Qualtrics Cookie Banner -->
        <div class="qualtricsCookieBanner" style="display: none">
            <div class="cookie-overflow-dynamic">
                <p class="cookie-title">Your choices on cookies</p>
                <p class="cookie-description">This website uses cookies in order for our feedback functionality to work. You can choose to set these optional survey cookies that are described below.</p>
                <p class="cookie-description-statement">You can find more information on how we use our cookies in our <a href="https://revenue.ie/en/online-services/support/data-and-security/privacy/use-of-cookies.aspx">Cookie Statement</a>. You can change your cookie preferences at any time by clicking the Cookie preferences link in the footer of every page on this website.
                </p>
                <!-- Qualtrics cookies -->
                <h2  class="cookie-toggle-title">
                    Survey cookies
                <label class="cookie-switch" for="cookie-opt-qualtrics-banner">
                    <input type="checkbox" id="cookie-opt-qualtrics-banner" name="ckbx-square-1">
                    <span class="cookie-slider round"></span>
                </label>
                </h2>
                <p class="cookie-toggle-description">Survey cookies are set by a third-party service provided by Qualtrics. These cookies are required in order for our feedback functionality to work.
                </p>
                <p class="cookie-toggle-description">The survey cookies collect information about the page you are providing feedback from. When you save your survey cookies choice below, a cookie will be saved on your device to remember your choice. These cookies are set as session cookies and will be deleted once you close this browsing session.</p>
                <p class="cookie-toggle-description">We welcome your feedback and you can help us to continue to improve our website by turning survey cookies on.</p>
            </div>
      <div>
           <button type='button' class='cookie-button' onclick='acknowledgeQualtricsMessage(event);'>Save and close</button>
      </div>
  </div>

   <!-- Youtube Cookie Banner -->
        <div class="youtubeCookieBanner" style="display: none">
            <div class="cookie-overflow-dynamic">
                <p class="cookie-title">Your choices on cookies</p>
                <p class="cookie-description">This website uses cookies in order for our video functionality to work. You can choose to set these optional video cookies that are described below.</p>
                <p class="cookie-description-statement">You can find more information on how we use our cookies in our <a href="https://revenue.ie/en/online-services/support/data-and-security/privacy/use-of-cookies.aspx">Cookie Statement</a>. You can change your cookie preferences at any time by clicking the Cookie preferences link in the footer of every page on this website.
                </p>
                <!-- Youtube cookies -->
                <h2  class="cookie-toggle-title">
                    YouTube cookies
                <label class="cookie-switch" for="cookie-opt-youtube-banner">
                    <input type="checkbox" id="cookie-opt-youtube-banner" name="ckbx-square-1">
                    <span class="cookie-slider round"></span>
                </label>
                </h2>
                <p class="cookie-toggle-description">YouTube cookies are set by a third-party service provided by YouTube, a company owned by Google. These cookies are required in order for our video functionality to work.</p>
                <p class="cookie-toggle-description">When you save your YouTube cookies choice below, Revenue will save a cookie on your device to remember your choice. This Revenue cookie is set as a session cookie and will be deleted once you close this browsing session. YouTube may set cookies directly according to <a href="https://policies.google.com/technologies/types?hl=en">YouTube's own cookies policy</a>.</p>
            </div>
      <div>
           <button type='button' class='cookie-button' onclick='acknowledgeYoutubeMessage(event);'>Save and close</button>
      </div>
  </div>
  
<script>
	//Deletion of GA Cookie banner 23 Feb 2021. Should not have a function that tries to call the cookie banner div. 
	// if (shouldShowCookieBanner() && "True" == "True" ) {
	//    $('.cookieBanner').show();
	//   $(".darker").show();
	// }

	$(document).ready(function () {
		//var cookieGoogleChecked = RevenueJs.Cookie.getCookie("cookie-opt-google") == "true";
		var cookieQualtricsChecked = RevenueJs.Cookie.getCookie("cookie-opt-qualtrics") == "true";
		var cookieYoutubeChecked = RevenueJs.Cookie.getCookie("cookie-opt-youtube") == "true";

		//$("#cookie-opt-google").prop('checked', cookieGoogleChecked)
		$("#cookie-opt-qualtrics").prop('checked', cookieQualtricsChecked)
		$("#cookie-opt-youtube").prop('checked', cookieYoutubeChecked)

		//$("#cookie-opt-google-banner").prop('checked', cookieGoogleChecked)
		$("#cookie-opt-qualtrics-banner").prop('checked', cookieQualtricsChecked)
		$("#cookie-opt-youtube-banner").prop('checked', cookieYoutubeChecked)

		//To check if the param has qualtricsLoad to open feedback
		if (window.location.search.indexOf('qualtricsLoaded=true') > -1) {
			setTimeout(function () { $('#pageFeedbackTarget')[0].click(); }, 500);
		}

		if (!cookieYoutubeChecked) {
			var youtubes = $(".youtube");
			$('.youtube').addClass("stopyoutube");
			$('.youtube').append("<div class='youtubealert'><span class='youtubemsg'>In order to view videos on revenue.ie, you will need to <a class='enablecookiequaltrics' onclick='showYoutubeCookieMessage(event)'>review and accept YouTube cookies</a></span></div>");
		}
	});

</script>
  



<div class="row top-alert top-alert--outdated-browser" style="display: none">
  <div class="row columns">
    <div class="columns small-10 medium-11 large-11">
  		It looks like the internet browser you are using is out of date. Please <a href="https://browser-update.org/update-browser.html">update your browser</a> for the best experience.
  </div>
    <div class="columns small-2 medium 1 large-1">
      <a class="top-alert__close-link" href="#" onclick="acknowledgeOutdatedBrowserWarning();">
  		Close
      </a>
  </div>
  </div>
  <script>
	  if (shouldShowOutdatedBrowserWarning()) {
		  $('.top-alert--outdated-browser').show();
	  }
  </script>
</div>
<div class="top-alert top-alert--gaelic-unavailable-for-current-section" style="display: none">
  
  <div class="row columns">
  
  	<div class="columns small-12 medium-12 large-12">
		<p>Tá an chuid seo den suíomh idirlín ar fáil i mBéarla amháin i láthair na huaire.</p>
		This section of the site is currently only available in English
   	</div>
    
  </div>
  
</div>
<script>
	$(document).ready(
		function () {
			$("table").wrap("<div class='table-scroll'></div>");
			var lastchild = $('.revenue .breadcrumb .row div span:last-child').text();
			if (lastchild != "") $('.revenue .breadcrumb .row div span:last-child').remove();

			var pattern = RegExp("/[^/]+(?=/$|$)");
			var pattern2 = RegExp("[^/]+(?=/$|$)");
			var numeric4digit = RegExp("[0-9][0-9][0-9][0-9]");
			var newpath = window.location.href.replace(pattern, "");
			var year = newpath.match(pattern2)[0];
			if (!isNaN(parseFloat(year)) && isFinite(year) && year.length == 4) {
				var lnk = $('.revenue .breadcrumb .row div a:last').attr("href") + "?year=" + year;
				$('.revenue .breadcrumb .row div a:last').attr("href", lnk);
			}
		}
	);
</script>


<div id="top-bar">



  <div class="row columns show-for-small-only">
          <div class="SignIn--small changeLang--small float-left">
            <a class="changeLang links nopadding" href="#">Gaeilge</a>
          </div>
          <div class="SignIn--small float-right">
            <a class="links nopadding" href="https://www.ros.ie/myaccount-web/sign_in.html">myAccount</a> <span class="pipe">|</span>
            <a class="links nopadding" href="https://www.ros.ie">ROS</a> 
            <!--LPT Header 20 September -->
             <span class="pipe">|</span>
           <a class="links nodpadding" href="https://lpt.revenue.ie/lpt-web/views/login.html?execution=e1s1">LPT Online</a>
          </div>
        </div>


	<div class="row">


	<div class="small-6 medium-5 large-7 columns logo">
			<a class="revenueLogo float-left" title="Home" href="/en/Home.aspx">
				<img alt="revenue-Logo" height="209" width="437" src="/SiteElements/Images/Revenue-Logo.png" />
      		</a>	
    </div>
	
      <div class="small-6 medium-7 large-5 columns search">
			<div class="row">

              <div class="SignIn hide-for-small-only">
               Sign in to <a class="links nopadding" href="https://www.ros.ie/myaccount-web/sign_in.html">myAccount</a> or <a class="links nopadding" href="https://www.ros.ie">ROS</a>
               <!--LPT Header 20 September -->
               or <a class="links nopadding" href="https://lpt.revenue.ie/lpt-web/views/login.html?execution=e1s1">LPT Online</a>
               <span class="pipelpt">|</span>
               <!-- <span class="pipe">|</span> -->
                <a class="changeLang links nopadding" href="#">Gaeilge</a>
              </div>
      		  <span class="float-right vertical-bar"><span class="float-right vertical-bar"></span></span>
              <div class="small-collapse">
                              <div class="columns">
                                  <div class="input-group">
                                      <input name="searchInput" id="searchInput" aria-label="Search" placeholder="Search" type="text" class="input-group-field" maxlength="140"/>
                                      <div class="input-group-button">
                                          <button id="btnSearch" class="button icon-button" type="button">
                                                      <img alt="Please click search" src="/SiteElements/images/svg/search.svg" />
                                                      <span class="hidesearchtext">Search</span>
                                          </button>
                                      </div>
                                  </div>
                              </div>
              </div>
              <input type="hidden" id="prefLang" value="English" data-idlang="0" />

      </div>
     </div>
   </div>
<script>

	var path;

	(function () {
		// to remove for the new cookie banner
		RevenueJs.PreferredLanguage = "English";
		//RevenueJs.ShowCovidMessage("CovidMessage", "CovidTextLink", "CovidMessage2"); note: took the at off
		path = 'https://www.revenue.ie/ga/customs/businesses/importing-exporting/exchange-rates/2023/september.aspx';

	})();

	//23 Feb 2021 Deletion of GA Cookie banner funtions.
	//shouldShowCookieBanner();
	deleteOldCookies();

</script>


<script>
	(function () {
		RevenueJs.Localisation.ShowMore = htmlDecode("Show more");
		RevenueJs.Localisation.ShowLess = htmlDecode("Show less");
		RevenueJs.Localisation.BackToTextFootnoteLink = htmlDecode("Back to text");
		RevenueJs.Localisation.PrintAllPagesIn = htmlDecode("Print all pages in");
		function htmlDecode(input) {
			if (input == "") return "";
			var e = document.createElement('div');
			e.innerHTML = input;
			return e.childNodes[0].nodeValue;
		}

	})();
</script>
</div>
<div class="breadcrumb">
<div class="row">
<div>
	<a title="Go to Home from here" class="sys_0 sys_t108" href="/en/Home.aspx">Home</a> <span class="separator">&nbsp;</span> <a title="Go to Customs from here" class="sys_0 sys_t47524" href="/en/customs/index.aspx">Customs</a> <span class="separator">&nbsp;</span> <a title="Go to Customs for businesses from here" class="sys_0 sys_t110" href="/en/customs/businesses/index.aspx">Customs for businesses</a> <span class="separator">&nbsp;</span> <a title="Go to Importing and exporting from here" class="sys_0 sys_t107" href="/en/customs/businesses/importing-exporting/index.aspx">Importing and exporting</a> <span class="separator">&nbsp;</span>     
</div>
</div>
</div>
<div class="hub-destination-pages">
<div class="content row">
<div class="large-7 columns">




<h1>
   Exchange rates to be used in determining customs value - September 2023
</h1>


<p>During the calendar month commencing 01/09/2023 the following rates of exchange will apply. These are calculated in accordance with Article 146 of <a class="external-links" title="Europa website - Commission Implementing Regulation (EU) 2015/2447" href="https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32015R2447&amp;from=EN">Commission Implementing Regulation (EU) 2015/2447</a>.</p>
<table><caption>Exchange Rates against the &euro; September 2023</caption>
<thead>
<tr><th>Denomination&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th><th headers="rate010923">Rate at 01/09/23</th></tr>
</thead>
<tbody>
<tr>
<td headers="denomination">US Dollar</td>
<td headers="rate010923">
<p>1.0805</p>
</td>
</tr>
<tr>
<td headers="denomination">Sterling</td>
<td headers="rate010923">0.85653</td>
</tr>
<tr>
<td headers="denomination">Japanese Yen</td>
<td headers="rate010923">
<p>157.28&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Swiss Franc</td>
<td headers="rate010923">
<p>0.9524&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Danish Krone</td>
<td headers="rate010923">
<p>7.4531&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Swedish Krona</td>
<td headers="rate010923">
<p>11.9061&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Norwegian Krone</td>
<td headers="rate010923">11.5730&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Czech Koruna</td>
<td headers="rate010923">24.132&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Hungarian Forint</td>
<td headers="rate010923">
<p>383.33</p>
</td>
</tr>
<tr>
<td headers="denomination">Polish Zloty</td>
<td headers="rate010923">
<p>4.4773&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Canadian Dollar</td>
<td headers="rate010923">
<p>1.4667</p>
</td>
</tr>
<tr>
<td headers="denomination">Australian Dollar</td>
<td headers="rate010923">
<p>1.6840</p>
</td>
</tr>
<tr>
<td headers="denomination">New Zealand Dollar</td>
<td headers="rate010923">
<p>1.8224&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Chinese Renminbi</td>
<td headers="rate010923">7.8796</td>
</tr>
<tr>
<td headers="denomination">Hong Kong Dollar</td>
<td headers="rate010923">
<p>8.4716</p>
</td>
</tr>
<tr>
<td headers="denomination">Indian Rupee</td>
<td headers="rate010923">
<p>89.3258</p>
</td>
</tr>
<tr>
<td headers="denomination">Indonesian Rupiah</td>
<td headers="rate010923">
<p>16523.94</p>
</td>
</tr>
<tr>
<td headers="denomination">Israeli Shekel</td>
<td headers="rate010923">4.0916</td>
</tr>
<tr>
<td headers="denomination">South Korean Won</td>
<td headers="rate010923">1448.26</td>
</tr>
<tr>
<td headers="denomination">Malaysian Ringgit</td>
<td headers="rate010923">
<p>5.0313</p>
</td>
</tr>
<tr>
<td headers="denomination">Mexican Peso</td>
<td headers="rate010923">
<p>18.2457</p>
</td>
</tr>
<tr>
<td headers="denomination">Philippines Peso</td>
<td headers="rate010923">61.351</td>
</tr>
<tr>
<td headers="denomination">Romanian Leu</td>
<td headers="rate010923">4.9408</td>
</tr>
<tr>
<td headers="denomination">Russian Rouble</td>
<td headers="rate010923">
<p>102.3092</p>
</td>
</tr>
<tr>
<td headers="denomination">Singapore Dollar</td>
<td headers="rate010923">
<p>1.4677</p>
</td>
</tr>
<tr>
<td headers="denomination">South African Rand</td>
<td headers="rate010923">20.2097</td>
</tr>
<tr>
<td headers="denomination">Thailand Baht</td>
<td headers="rate010923">37.936</td>
</tr>
<tr>
<td headers="denomination">Turkish Lira</td>
<td headers="rate010923">29.4080</td>
</tr>
<tr>
<td headers="denomination">Bulgarian Lev</td>
<td headers="rate010923">
<p>1.9558&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Brazil Real</td>
<td headers="rate010923">5.3306</td>
</tr>
<tr>
<td headers="denomination">Algerian Dinar</td>
<td headers="rate010923">148.0628</td>
</tr>
<tr>
<td headers="denomination">Bahrain Dinar</td>
<td headers="rate010923">0.4090</td>
</tr>
<tr>
<td headers="denomination">Botswana Pula</td>
<td headers="rate010923">14.5688</td>
</tr>
<tr>
<td headers="denomination">CFA Franc</td>
<td headers="rate010923">655.9544</td>
</tr>
<tr>
<td headers="denomination">Costa Rican Colon</td>
<td headers="rate010923">585.6274</td>
</tr>
<tr>
<td headers="denomination">Egyptian Pound</td>
<td headers="rate010923">33.5162</td>
</tr>
<tr>
<td headers="denomination">Ghana Cedi</td>
<td headers="rate010923">12.3107</td>
</tr>
<tr>
<td headers="denomination">Gibraltar Pound</td>
<td headers="rate010923">0.8552</td>
</tr>
<tr>
<td headers="denomination">Iraqi Dinar</td>
<td headers="rate010923">
<p>1420.4513</p>
</td>
</tr>
<tr>
<td headers="denomination">Kenyan Shilling</td>
<td headers="rate010923">
<p>157.0025</p>
</td>
</tr>
<tr>
<td headers="denomination">Kuwaiti Dinar</td>
<td headers="rate010923">
<p>0.3343</p>
</td>
</tr>
<tr>
<td headers="denomination">Lebanese Pound</td>
<td headers="rate010923">
<p>16383.5856</p>
</td>
</tr>
<tr>
<td headers="denomination">Malawi Kwacha</td>
<td headers="rate010923">
<p>1169.7038</p>
</td>
</tr>
<tr>
<td headers="denomination">Moroccan Dirham</td>
<td headers="rate010923">
<p>10.8760&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">Nigerian Naira</td>
<td headers="rate010923">824.8732</td>
</tr>
<tr>
<td headers="denomination">Pakistan Rupee</td>
<td headers="rate010923">325.1226</td>
</tr>
<tr>
<td headers="denomination">Qatar Riya</td>
<td headers="rate010923">3.9481</td>
</tr>
<tr>
<td headers="denomination">Saudi Arabia Riyal</td>
<td headers="rate010923">4.0684</td>
</tr>
<tr>
<td headers="denomination">Sri Lankan Rupee</td>
<td headers="rate010923">350.8829</td>
</tr>
<tr>
<td headers="denomination">Taiwan Dollar</td>
<td headers="rate010923">34.6257</td>
</tr>
<tr>
<td headers="denomination">Tanzanian Shilling</td>
<td headers="rate010923">2706.1915</td>
</tr>
<tr>
<td headers="denomination">Trinidad/Tobago Dollar</td>
<td headers="rate010923">7.3269</td>
</tr>
<tr>
<td headers="denomination">Tunisian Dinar</td>
<td headers="rate010923">3.3753&nbsp;</td>
</tr>
<tr>
<td headers="denomination">UAE Dirham</td>
<td headers="rate010923">3.9839</td>
</tr>
<tr>
<td headers="denomination">Yemen Rial</td>
<td headers="rate010923">271.4868&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Omani Rial</td>
<td headers="rate010923">
<p>0.4176</p>
</td>
</tr>
<tr>
<td headers="denomination">Argentina Peso</td>
<td headers="rate010923">379.6005</td>
</tr>
<tr>
<td headers="denomination">Colombian Peso</td>
<td headers="rate010923">4426.5807&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Bermuda Dollar</td>
<td headers="rate010923">1.0846</td>
</tr>
<tr>
<td headers="denomination">Brunei Dollar</td>
<td headers="rate010923">
<p>1.4685</p>
</td>
</tr>
<tr>
<td headers="denomination">Fiji Dollar</td>
<td headers="rate010923">2.4862</td>
</tr>
<tr>
<td headers="denomination">Namibia Dollar</td>
<td headers="rate010923">20.0605</td>
</tr>
<tr>
<td headers="denomination">Libyan Dinar</td>
<td headers="rate010923">5.2192</td>
</tr>
<tr>
<td headers="denomination">Chilean Peso</td>
<td headers="rate010923">932.3453</td>
</tr>
<tr>
<td headers="denomination">Vietnam Dong</td>
<td headers="rate010923">26026.0781</td>
</tr>
<tr>
<td headers="denomination">Peruvian New Sol</td>
<td headers="rate010923">4.0234</td>
</tr>
<tr>
<td headers="denomination">Nepalese Rupee</td>
<td headers="rate010923">143.5247</td>
</tr>
<tr>
<td headers="denomination">Icelandic Krona</td>
<td headers="rate010923">143.10&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Maur Rupee</td>
<td headers="rate010923">49.2429&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Ukraine Hryvnia</td>
<td headers="rate010923">40.0576</td>
</tr>
<tr>
<td headers="denomination">Serbia Dinar</td>
<td headers="rate010923">117.2448</td>
</tr>
<tr>
<td headers="denomination">
<p>Georgia Lari</p>
</td>
<td headers="rate010923">2.8526&nbsp;</td>
</tr>
<tr>
<td headers="denomination">Cayman Island Dollar</td>
<td headers="rate010923">0.8894</td>
</tr>
<tr>
<td headers="denomination">
<p>Kazakhstan Tenge</p>
</td>
<td headers="rate010923">500.6833&nbsp;&nbsp;&nbsp;&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Albania Lek</p>
</td>
<td headers="rate010923">108.0578&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Azerbaijan New Manet</p>
</td>
<td headers="rate010923">1.8466&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Bosnia Herzegoviaea Marka</p>
</td>
<td headers="rate010923">1.9558</td>
</tr>
<tr>
<td headers="denomination">
<p>Barbados Dollar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
<td headers="rate010923">2.1693&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Bangladesh Taka&nbsp;</p>
</td>
<td headers="rate010923">
<p>118.7145&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">
<p>Bhutan Ngultrum</p>
</td>
<td headers="rate010923">89.7029&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Belize Dollar&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
<td headers="rate010923">2.1693&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Dominican Republic Peso</p>
</td>
<td headers="rate010923">61.6187&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Eritrea Nakfa&nbsp;&nbsp;</p>
</td>
<td headers="rate010923">16.2697&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Ethiopia Birr&nbsp;</p>
</td>
<td headers="rate010923">59.9428&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Jordan Dinar&nbsp;&nbsp;&nbsp;&nbsp;</p>
</td>
<td headers="rate010923">0.7690&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Moldova Leu&nbsp;</p>
</td>
<td headers="rate010923">19.3284&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Solomon Islands Dollar&nbsp;</p>
</td>
<td headers="rate010923">9.1454&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Saint Helena Pound</p>
</td>
<td headers="rate010923">0.8552&nbsp;</td>
</tr>
<tr>
<td headers="denomination">
<p>Antigua &amp; Barbuda Dollar&nbsp;&nbsp;</p>
</td>
<td headers="rate010923">
<p>2.9285&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">
<p>Uruguay Peso</p>
</td>
<td headers="rate010923">
<p>40.9980&nbsp;</p>
</td>
</tr>
<tr>
<td headers="denomination">
<p>Zimbabwe Dollar</p>
</td>
<td headers="rate010923">392.5333&nbsp;</td>
</tr>
</tbody>
</table>





    <div class="bottom-links row">
        <p>
      		



            
        </p>
    </div>

<script>
	(function () {
		var v = RevenueJs.Cookie.getCookie('cookie-opt-qualtrics');
		if (v == "" || JSON.parse(v) == false) {
			$('#pageFeedbackTarget').on("click", function () {
				showQualtricsCookieMessage(event);
				event.preventDefault();
			});
		}

	})();
</script>


<!-- Normally, when configuring a Qualtrics intercept, the Qualtrics dashboard provides you with
     a chunk of HTML that you include on your webpage. This consists of a script tag followed by
     a div. The div acts as a container for where the intercept's 'creative' appears in the DOM
     and the script is all the Qualtrics magic that ensures the interceptor does what its
     supposed to, as per the configuration of the interceptor on the Qualtrics dashboard.
     We've separated the contents of the script tag (an immediately-invoked function
     expression) into a separate .js file, e.g.
     SiteElements/js/QualtricsInterceptors/FeedbackSinglePage.js
       
       
     
     The div tag below and its JavaScript (in the .js file referred to above) are correlated
     using a unique identifier (i.e. the value of the id attribute of the div tag below).
       -->
<div id='SI_3q7XY6pm4eVorBz'><!--DO NOT REMOVE-CONTENTS PLACED HERE--></div>

</div>
<div class="large-4 columns">
<div class="collapsible-list-links">
<ul id="T999_ulplace" class="collapsible-list-links">
            
            



                
</ul>
</div>
</div>
</div>
</div>
<div class="footer-navigation">
<div class="row">



  <a href="/en/Home.aspx">Back to homepage</a>




 <a class="back-to-top" href="#">Back to top</a>

</div>
</div>



<div class="footer" id="footer">
	<div class="row">
		<div class="medium-6 large-8 columns">
			<div class="large-6 columns">
                         <ul>
                            <li>

                                Information about Revenue
                            </li>
                            <li><a  title="Role of Revenue" href="/en/corporate/information-about-revenue/role-of-revenue/index.aspx">Role of Revenue</a></li>
<li><a  title="Customer service commitments" href="/en/corporate/information-about-revenue/customer-service/index.aspx">Customer service commitments</a></li>
<li><a  title="Press office" href="/en/corporate/press-office/index.aspx">Press office</a></li>
<li><a  title="Governance" href="/en/corporate/information-about-revenue/governance/index.aspx">Governance</a></li>
<li><a  title="Appeals" href="/en/corporate/information-about-revenue/appeals/index.aspx">Appeals</a></li>
<li><a  title="Statistics on income, tax and duties" href="/en/corporate/information-about-revenue/statistics/index.aspx">Statistics on income, tax and duties</a></li>
<li><a  title="Research" href="/en/corporate/information-about-revenue/research/index.aspx">Research</a></li>
<li><a  title="Careers" href="/en/corporate/information-about-revenue/careers/index.aspx">Careers</a></li>
<li><a  title="Revenue Museum" href="/en/corporate/information-about-revenue/revenue-museum/index.aspx">Revenue Museum</a></li>
<li><a  title="Revenue Centenary" href="/en/rev-100/index.aspx">Revenue Centenary</a></li>

                         </ul>
                                          <ul>
                            <li>

                                Using revenue.ie
                            </li>
                            <li><a  title="Accessibility statement" href="/en/online-services/support/technical-requirements/accessibility-statement/index.aspx">Accessibility statement</a></li>
<li><a  title="Security" href="/en/online-services/support/data-and-security/security/index.aspx">Security</a></li>
<li><a  title="Privacy" href="/en/online-services/support/data-and-security/privacy/index.aspx">Privacy</a></li>
<li><a  title="Disclaimer" href="/en/online-services/support/data-and-security/disclaimer/index.aspx">Disclaimer</a></li>
<li><a  title="Re-use of public sector information" href="/en/corporate/using-revenue/reuse-of-public-sector-information/index.aspx">Re-use of public sector information</a></li>
<li><a  title="Cookie preferences" href="/en/online-services/support/data-and-security/privacy/use-of-cookies.aspx">Cookie preferences</a></li>

                         </ul>


			</div>
			<div class="large-6 columns">
                         <ul>
                            <li>

                                Statutory obligations
                            </li>
                            <li><a  title="Freedom of Information" href="/en/corporate/statutory-obligations/freedom-of-information/index.aspx">Freedom of Information</a></li>
<li><a  title="Data protection" href="/en/corporate/statutory-obligations/data-protection/index.aspx">Data protection</a></li>
<li><a  title="Protected disclosures" href="/en/corporate/statutory-obligations/protected-disclosures/index.aspx">Protected disclosures</a></li>
<li><a  title="Procurement" href="/en/corporate/statutory-obligations/procurement/index.aspx">Procurement</a></li>
<li><a  title="Regulation of Lobbying Act" href="/en/corporate/statutory-obligations/regulation-of-lobbying-act/index.aspx">Regulation of Lobbying Act</a></li>
<li><a  title="Official Languages Act" href="/en/corporate/statutory-obligations/official-languages-act/index.aspx">Official Languages Act</a></li>
<li><a  title="Child Safeguarding Statement" href="/en/corporate/statutory-obligations/child-safeguarding-statement/index.aspx">Child Safeguarding Statement</a></li>
<li><a  title="Gender pay gap" href="/en/corporate/statutory-obligations/gender-pay-gap/index.aspx">Gender pay gap</a></li>

                         </ul>
                                          <ul>
                            <li>

                                Assist us
                            </li>
                            <li><a  title="Reporting shadow economy activity (tax evasion)" href="/en/corporate/assist-us/reporting-shadow-economy-activity/index.aspx">Reporting shadow economy activity (tax evasion)</a></li>
<li><a  title="Drug and tobacco smuggling" href="/en/corporate/assist-us/drug-and-tobacco-smuggling/index.aspx">Drug and tobacco smuggling</a></li>

                         </ul>

                         <ul>
                            <li>

                                Consultations and submissions
                            </li>
                            <li><a   title="Submission to the Commission on Taxation and Welfare" href="/en/corporate/consultations-and-submissions/submission-commission-taxation-welfare/index.aspx">Submission to the Commission on Taxation and Welfare</a></li>

                         </ul>

             </div>
		</div>
		<div class="medium-6 large-4 columns">
                         <ul>
                            <li>

                                Communications
                            </li>
                            <li><a    title="Contact us" href="/en/contact-us/index.aspx">Contact us</a></li>
<li><a    title="Twitter" href="/en/corporate/communications/twitter/index.aspx">Twitter</a></li>
<li><a    title="Fraudulent emails and SMS (text messages)" href="/en/corporate/communications/fraudulent-emails/index.aspx">Fraudulent emails and SMS (text messages)</a></li>
<li><a  class=external-links-white  title="Website feedback" href="https://revenue.eu.qualtrics.com/jfe/form/SV_3EpTMqX6iaPuoYJ">Website feedback</a></li>

                         </ul>
                                          <ul>
                            <li>

                                COVID-19
                            </li>
                            <li><a    title="COVID-19 Information" href="/en/covid-19-information/index.aspx">COVID-19 Information</a></li>

                         </ul>
                                          <ul>
                            <li>

                                Central Register of Beneficial Ownership of Trusts (CRBOT)
                            </li>
                            <li><a  title="Central Register of Beneficial Ownership of Trusts (CRBOT)" href="/en/crbot/index.aspx">Central Register of Beneficial Ownership of Trusts (CRBOT)</a></li>

                         </ul>

                         <ul>
                            <li>

                                External Links
                            </li>
                            <li><a class=external-links-white title="whodoeswhat.ie" href="http://www.whodoeswhat.gov.ie/">whodoeswhat.ie</a></li>
<li><a class=external-links-white title="gov.ie" href="http://www.gov.ie/">gov.ie</a></li>

                         </ul>

		</div>
	</div>
</div>
          
          


</div>

		
<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="2B3789F1" />
</div>
		<script  type="text/javascript" src="/SiteElements/Js/CollapseFilterAndContentPages.js?version=152158&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/footnote.js?version=40758&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/QualtricsInterceptors/FeedbackSinglePage.js?version=117934&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/HandleSearchInputForMobile.js?version=42501&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/DocumentsListColapseOlderVersions.js?version=47439&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/Autocomplete.js?version=80402&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/lang-preference.js?version=117935&amp;build=1131401"></script>
		<script  type="text/javascript" src="/SiteElements/js/localise-survey-link.js?version=43011&amp;build=1131401"></script>
</form>
	</body>

	</html>
