//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated,
//     except for the namespace which will stay as you edit it.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Customs.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoCusEntrySnapshotValidation : ZValidation
	{
		protected AutoCusEntrySnapshotValidation(AutoCusEntrySnapshot Parent) : base(Parent)
		{
			if (Object.ReferenceEquals(Parent, null))
			{
				throw new ArgumentNullException("Parent");
			}
			this.Parent = Parent;
			this.ParentListInternals = (ISingleElementListInternal) Parent;
			this.ZValidationInternals = (IValidationInternals) this;
		}

		/// <summary>
		/// The auto validation type.
		/// </summary>
		public override Type AutoValidationType
		{
			get { return typeof(AutoCusEntrySnapshotValidation); }
		}

		/// <summary>
		/// Add more validation to the CusEntrySnapshot's base validation. This will not replace existing validation 
		/// (to replace existing validation you should override the 'Validation' property in the business object).
		/// </summary>
		public void Add(AutoCusEntrySnapshotValidation Validation)
		{
			ZValidationInternals.Add(Validation);
		}

		/// <summary>
		/// Remove validation. The CusEntrySnapshot's base validation object cannot be removed.
		/// </summary>
		public void Remove(AutoCusEntrySnapshotValidation Validation)
		{
			ZValidationInternals.Remove(Validation);
		}

		#region Properties

		#region CES_CH_EntryHeader

		public void ValidateCES_CH_EntryHeader()
		{
			ZValidationInternals.Validate(Parent.CES_CH_EntryHeaderInfo, GetCES_CH_EntryHeaderValidationInvoker());
		}

		RunValidationInvoker GetCES_CH_EntryHeaderValidationInvoker()
		{
			return delegate
			{
				CheckCES_CH_EntryHeaderIsNotEmpty();
				CheckCES_CH_EntryHeaderIsValidZGuid();
				CheckCES_CH_EntryHeader();
			};
		}

		protected virtual void CheckCES_CH_EntryHeaderIsValidZGuid()
		{
			TypeValidation.CheckValidGuid(Parent.CES_CH_EntryHeaderInfo);
		}

		protected virtual void CheckCES_CH_EntryHeaderIsNotEmpty()
		{
			MandatoryValidation.CheckEntered(Parent.CES_CH_EntryHeaderInfo);
		}

		protected virtual void CheckCES_CH_EntryHeader()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CES_MessageType

		public void ValidateCES_MessageType()
		{
			ZValidationInternals.Validate(Parent.CES_MessageTypeInfo, GetCES_MessageTypeValidationInvoker());
		}

		RunValidationInvoker GetCES_MessageTypeValidationInvoker()
		{
			return delegate
			{
				CheckCES_MessageTypeIsWesternEuropean();
				CheckCES_MessageType();
			};
		}

		protected virtual void CheckCES_MessageTypeIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CES_MessageTypeInfo);
		}

		protected virtual void CheckCES_MessageType()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CES_SnapshotXml

		public void ValidateCES_SnapshotXml()
		{
			ZValidationInternals.Validate(Parent.CES_SnapshotXmlInfo, GetCES_SnapshotXmlValidationInvoker());
		}

		RunValidationInvoker GetCES_SnapshotXmlValidationInvoker()
		{
			return delegate
			{
				CheckCES_SnapshotXml();
			};
		}

		protected virtual void CheckCES_SnapshotXml()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CES_Status

		public void ValidateCES_Status()
		{
			ZValidationInternals.Validate(Parent.CES_StatusInfo, GetCES_StatusValidationInvoker());
		}

		RunValidationInvoker GetCES_StatusValidationInvoker()
		{
			return delegate
			{
				CheckCES_StatusIsWesternEuropean();
				CheckCES_Status();
			};
		}

		protected virtual void CheckCES_StatusIsWesternEuropean()
		{
			EnglishCharactersValidation.ErrorIfNotWesternEuropean(Parent.CES_StatusInfo);
		}

		protected virtual void CheckCES_Status()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#region CES_VersionNumber

		public void ValidateCES_VersionNumber()
		{
			ZValidationInternals.Validate(Parent.CES_VersionNumberInfo, GetCES_VersionNumberValidationInvoker());
		}

		RunValidationInvoker GetCES_VersionNumberValidationInvoker()
		{
			return delegate
			{
				CheckCES_VersionNumber();
			};
		}

		protected virtual void CheckCES_VersionNumber()
		{
			// sub-classes should override to implement custom validation
		}

		#endregion

		#endregion

		#region Validate All

		public override void ValidateAll()
		{
			using (ParentListInternals.SuspendListChanged())
			{
				ValidateCES_CH_EntryHeader();
				ValidateCES_MessageType();
				ValidateCES_SnapshotXml();
				ValidateCES_Status();
				ValidateCES_VersionNumber();
			}
		}

		#endregion

		#region Implementation

		protected readonly AutoCusEntrySnapshot Parent;
		private readonly ISingleElementListInternal ParentListInternals;
		private readonly IValidationInternals ZValidationInternals;

		#endregion
	}
}
