using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Enterprise.ActivityLogger.Test")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Enterprise.ActivityLogger.SafeNativeMethods.#DetachHooks()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Enterprise.ActivityLogger.SafeNativeMethods.#GetSyshookPath()")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Enterprise.ActivityLogger.SafeNativeMethods.#GetWindowText(System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "Enterprise.ActivityLogger.SafeNativeMethods.#AttachHooks()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.NativeMethodTester.#TestLoadFree()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.NativeMethodTester.#TestFreeFirst()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.NativeMethodTester.#TestDoubleFree()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.NativeMethodTester.#TestDoubleLoad()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.NativeMethodTester.#TestAttachDetach()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Enterprise.ActivityLogger.Test.ActivityInfoTest.#TestInvalidProcessId()")]

[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.Hooker.WaitForEvent(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\Syshook\Hooker.cs:52:34
[assembly: SuppressMessage("CargoWiseOne", "CW1050:Use System.TimeSpan Type For A Duration", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.SafeNativeMethods.WaitForEvent(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\Syshook\SafeNativeMethods.cs:140:41

[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.ActivityInfo.#ctor(System.Int32)")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\ActivityInfo.cs:41:18
[assembly: SuppressMessage("CargoWiseOne", "CW1061:Do not use System.DateTime.UtcNow Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.ActivityInfo.End")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\ActivityInfo.cs:46:16
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.ActivityLogger.HookerThread")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\ActivityLogger.cs:89:28
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.ActivityLogger.HookerThread")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\ActivityLogger.cs:99:27
[assembly: SuppressMessage("CargoWiseOne", "CW1060:Do not use System.DateTime.Now Rule", Justification = "Auto generated baseline suppressions - WI00545660", Scope = "member", Target = "~M:Enterprise.ActivityLogger.ActivityLogger.HookerThread")] // C:\git\wtg\CargoWise\Dev\Enterprise\Product\Core\ActivityLogger\ActivityLogger\ActivityLogger.cs:114:23
[assembly: SuppressMessage("CargoWiseOne", "CW1021:Static Fields Are Thread Static Rule", Justification = "Baseline WI00605045", Scope = "member", Target = "~F:Enterprise.ActivityLogger.ExternalActivityLoggerProvider.hasReported")] // Enterprise/Product/Core/ActivityLogger/ActivityLogger/ExternalActivityLoggerProvider.cs:87,14
