<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.BarcodeParsing.Business.Testing</RootNamespace>
    <AssemblyName>Enterprise.BarcodeParsing.Business.Test</AssemblyName>
    <CWDisableNetCoreTestDiscovery>true</CWDisableNetCoreTestDiscovery>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.EntityFramework.Testing" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.BarcodeParsingEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="Moq" />
    <Reference Include="NUnitCore" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BarcodeParsing.Business\BarcodeParsing.Business.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Common\BarcodeParsingConsumer\DummyTargetFields.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DummyTargetFields.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Common\BarcodeParsingConsumer\DummyTargetFields.xml">
      <CustomToolNamespace>Enterprise.BarcodeParsing.Business.Testing</CustomToolNamespace>
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>DummyTargetFields.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>