//------------------------------------------------------------------------------
// <autogenerated>
//     Manual changes to this file will be lost when it is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;

using CargoWise.EntityFramework;
using CargoWise.Types;
using Enterprise.MasterFiles.Business;
using Enterprise.ZArchitecture;
using Enterprise.ZArchitecture.Business;

namespace Enterprise.Licensing.Billing.Business
{
	[Resources.AutoGeneratedSourceCode()]
	public abstract class AutoLicenceEnterpriseLookups : ZLookups
	{
		protected AutoLicenceEnterpriseLookups(AutoLicenceEnterprise Parent) : base(Parent)
		{
		}

		#region Headers

		public virtual OrgHeaderCollection Headers
		{
			get
			{
				return new OrgHeaderCollection(Factory);
			}
		}

		#endregion
	}
}
