<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.SqlSecurity</AssemblyName>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <CWUsesSqlClient>true</CWUsesSqlClient>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.DirectoryServices" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ActiveDirectory" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.Bi.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Database.Shared" />
    <Reference Include="CargoWise.DataProtection"/>
    <Reference Include="CargoWise.DataProtection.SqlExtensions"/>
    <Reference Include="CargoWise.DataProtection.Administration"/>
    <Reference Include="CargoWise.DataProtection.Administration.SqlServer"/>
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.Security.ActiveDirectory.Integration" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="WTG.Data.SqlDbSecuritySynchroniser" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Data.Shared" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="CargoWise.SqlSecurity" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="Microsoft.Extensions.DependencyInjection"/>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions"/>
  </ItemGroup>
</Project>