<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DataTransfer.SystemMerge.XmlDefinition</RootNamespace>
    <AssemblyName>Enterprise.DataTransfer.SystemMerge.XmlDefinition</AssemblyName>
    <CWGenerateXmlSerializationAssemblies>true</CWGenerateXmlSerializationAssemblies>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Resources" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="SysMergeEdocs.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SysMergeEdocs.xsd</DependentUpon>
    </Compile>
    <Compile Update="SysMergeOrganisation.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SysMergeOrganisation.xsd</DependentUpon>
    </Compile>
    <Compile Update="SysMergeProduct.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>SysMergeProduct.xsd</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SysMergeProduct.xsd">
      <CustomToolNamespace>Enterprise.DataTransfer.SystemMerge.XmlDefinition</CustomToolNamespace>
      <Generator>XsdClassGenerator</Generator>
      <LastGenOutput>SysMergeProduct.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SysMergeOrganisation.xsd">
      <CustomToolNamespace>Enterprise.DataTransfer.SystemMerge.XmlDefinition</CustomToolNamespace>
      <Generator>XsdClassGenerator</Generator>
      <LastGenOutput>SysMergeOrganisation.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="SysMergeEdocs.xsd">
      <CustomToolNamespace>Enterprise.DataTransfer.SystemMerge.XmlDefinition</CustomToolNamespace>
      <Generator>XsdClassGenerator</Generator>
      <LastGenOutput>SysMergeEdocs.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>