<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Enterprise.SqlSecurity.SpecTesting.Regenerate</RootNamespace>
    <AssemblyName>SqlSecurity.SpecTesting.Regenerate</AssemblyName>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <Configurations>Debug</Configurations>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <ItemGroup>
    <ProjectReference Include="..\SqlSecurity.SpecTesting\Enterprise.SqlSecurity.SpecTesting.csproj" />
    <ProjectReference Include="..\SqlSecurity\Enterprise.SqlSecurity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WTG.TestHelpers.SpecTesting" />
  </ItemGroup>
</Project>
