namespace Enterprise.BufferManagement.GUI.Test
{
	class WorkflowCapabilityAssignerTest_AutoAssignWorkflowsInBatchesImmediately_OldCalculator : WorkflowCapabilityAssignerTestCase_AutoAssignWorkflowsInBatchesImmediately
	{
	}
}
