<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:decxs="http://www.chinaport.gov.cn/dec" targetNamespace="http://www.chinaport.gov.cn/dec" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="DEC_RESULT">
	<xs:annotation>
	  <xs:documentation>报关单回执报文</xs:documentation>
	</xs:annotation>
	<xs:complexType>
	  <xs:sequence>
		<xs:element name="CUS_CIQ_NO" type="xs:string"/>
		<xs:element name="ENTRY_ID" type="xs:string">
		  <xs:annotation>
			<xs:documentation>海关编号</xs:documentation>
		  </xs:annotation>
		</xs:element>
		<xs:element name="NOTICE_DATE">
		  <xs:annotation>
			<xs:documentation>通知时间</xs:documentation>
		  </xs:annotation>
		  <xs:simpleType>
			<xs:restriction base="xs:string">
			  <xs:length value="19"/>
			  <xs:pattern value="yyyy-MM-ddTHH:mm:ss"/>
			</xs:restriction>
		  </xs:simpleType>
		</xs:element>
		<xs:element name="CHANNEL" type="xs:string">
		  <xs:annotation>
			<xs:documentation>处理结果</xs:documentation>
		  </xs:annotation>
		</xs:element>
		<xs:element name="NOTE" type="xs:string">
		  <xs:annotation>
			<xs:documentation>审核备注</xs:documentation>
		  </xs:annotation>
		</xs:element>
		<xs:element name="CUSTOM_MASTER" type="xs:string"/>
		<xs:element name="I_E_DATE">
		  <xs:annotation>
			<xs:documentation>进出口日期</xs:documentation>
		  </xs:annotation>
		  <xs:simpleType>
			<xs:restriction base="xs:string">
			  <xs:length value="8"/>
			  <xs:pattern value="yyyyMMdd"/>
			  <xs:pattern value=""></xs:pattern>
			</xs:restriction>
		  </xs:simpleType>
		</xs:element>
		<xs:element name="D_DATE">
		  <xs:annotation>
			<xs:documentation>申报日期</xs:documentation>
		  </xs:annotation>
		  <xs:simpleType>
			<xs:restriction base="xs:string">
			  <xs:length value="19"/>
			  <xs:pattern value="yyyy-MM-ddTHH:mm:ss"/>
			</xs:restriction>
		  </xs:simpleType>
		</xs:element>
	  </xs:sequence>
	</xs:complexType>
  </xs:element>
</xs:schema>