<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;$(CWNetCoreTargetFramework)</TargetFrameworks>
    <RootNamespace>Enterprise.DocumentWrappers</RootNamespace>
  </PropertyGroup>
  <Import Project="$(WTGBranchRoot)NetCore\NetCoreCommon.props" />
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsNetCoreTargetFramework)' == 'true'">
    <PackageReference Include="System.Drawing.Common" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CargoWise.ApplicationContext" />
    <Reference Include="CargoWise.Common" />
    <Reference Include="CargoWise.ComponentModel" />
    <Reference Include="CargoWise.Data" />
    <Reference Include="CargoWise.Definitions" />
    <Reference Include="CargoWise.EntityFramework" />
    <Reference Include="CargoWise.Integration" />
    <Reference Include="CargoWise.Odyssey.Schema" />
    <Reference Include="CargoWise.Organizations.PatternMatching" />
    <Reference Include="CargoWise.ResourceStrings.Cache" />
    <Reference Include="CargoWise.Schema" />
    <Reference Include="CargoWise.Shared.40" />
    <Reference Include="CargoWise.Types" />
    <Reference Include="CargoWise.UniversalCopy" />
    <Reference Include="Enterprise.Accounting.CountryCompliance.Interfaces" />
    <Reference Include="Enterprise.ComplianceRisk.Integration" />
    <Reference Include="Enterprise.Customs.EU.EMCS.Business" />
    <Reference Include="Enterprise.Customs.ManifestBase" />
    <Reference Include="Enterprise.Packing.Integration" />
    <Reference Include="Enterprise.Services.OperationalActions.Integration" />
    <Reference Include="Enterprise.UniversalDataBuss.Integration" />
    <Reference Include="CargoWise.ResourceStrings" />
    <Reference Include="DocumentWrappersCore" />
    <Reference Include="Enterprise.Accounting.Business" />
    <Reference Include="Enterprise.Accounting.DataTransfer" />
    <Reference Include="Enterprise.Accounting.ElectronicMessaging" />
    <Reference Include="Enterprise.Accounting.Integration" />
    <Reference Include="Enterprise.Accounting.Netting" />
    <Reference Include="Enterprise.Accounting.TaxFramework.Business" />
    <Reference Include="Enterprise.Barcode.Business" />
    <Reference Include="Enterprise.BarcodeParsing.Business" />
    <Reference Include="Enterprise.BarcodeParsingEngine" />
    <Reference Include="Enterprise.Billing.Integration" />
    <Reference Include="Enterprise.CommissionManagement.Business" />
    <Reference Include="Enterprise.Customs.AU.Declaration.Business" />
    <Reference Include="Enterprise.Customs.Business" />
    <Reference Include="Enterprise.Customs.Common" />
    <Reference Include="Enterprise.Customs.EU.Business" />
    <Reference Include="Enterprise.Customs.EU.NCTS.Business" />
    <Reference Include="Enterprise.Customs.EU.NCTS.Messaging" />
    <Reference Include="Enterprise.Customs.NZ.Business" />
    <Reference Include="Enterprise.Customs.NZ.TradeSingleWindow" />
    <Reference Include="Enterprise.Customs.Universal" />
    <Reference Include="Enterprise.DataTransfer.Integration" />
    <Reference Include="Enterprise.DeniedPartyScreening.Business" />
    <Reference Include="Enterprise.DocumentEngine" />
    <Reference Include="Enterprise.DocumentEngineCore" />
    <Reference Include="Enterprise.DocumentEngineIntegration" />
    <Reference Include="Enterprise.DocumentScanning.Integration" />
    <Reference Include="Enterprise.DocumentVisualizer.DocDataObjects" />
    <Reference Include="Enterprise.EConversation.Business" />
    <Reference Include="Enterprise.Environment" />
    <Reference Include="Enterprise.eTail.Business" />
    <Reference Include="Enterprise.eTail.Integration" />
    <Reference Include="Enterprise.Freight" />
    <Reference Include="Enterprise.Freight.Agency.Business" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Business" />
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration" />
    <Reference Include="Enterprise.Freight.CFS.Business" />
    <Reference Include="Enterprise.Freight.Common.Business" />
    <Reference Include="Enterprise.Freight.ContainerYard.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.AWB.Business" />
    <Reference Include="Enterprise.Freight.Forwarding.Business" />
    <Reference Include="Enterprise.Freight.Integration" />
    <Reference Include="Enterprise.Freight.LocalCartage.Integration" />
    <Reference Include="Enterprise.Freight.LocalCartage.Business" />
    <Reference Include="Enterprise.Freight.QuotedBookings.Business" />
    <Reference Include="Enterprise.Integration" />
    <Reference Include="Enterprise.LandedCosting.Business" />
    <Reference Include="Enterprise.MarketingManager.Business" />
    <Reference Include="Enterprise.MasterData.Business" />
    <Reference Include="Enterprise.MasterData.Common" />
    <Reference Include="Enterprise.MasterFiles.Business" />
    <Reference Include="Enterprise.MasterFiles.Integration" />
    <Reference Include="Enterprise.MasterFiles.Tracking" />
    <Reference Include="Enterprise.Messaging.Business" />
    <Reference Include="Enterprise.Messaging.Integration" />
    <Reference Include="Enterprise.Packing.Business" />
    <Reference Include="Enterprise.ProcessManagement.Business" />
    <Reference Include="Enterprise.ProcessManagement.Integration" />
    <Reference Include="Enterprise.Rating.Business" />
    <Reference Include="Enterprise.Rating.Integration" />
    <Reference Include="Enterprise.Recruiter.Business" />
    <Reference Include="Enterprise.Registry.Business" />
    <Reference Include="Enterprise.ResourceStrings.Business" />
    <Reference Include="Enterprise.Security" />
    <Reference Include="Enterprise.Security.Core" />
    <Reference Include="Enterprise.TransportBookings.Business" />
    <Reference Include="Enterprise.TransportBookings.Shared" />
    <Reference Include="Enterprise.TransportCommon.Business" />
    <Reference Include="Enterprise.TransportCommon.Integration" />
    <Reference Include="Enterprise.TransportCommon.Registry" />
    <Reference Include="Enterprise.TransportCommon.Shared" />
    <Reference Include="Enterprise.TransportConsignment.Business" />
    <Reference Include="Enterprise.TransportConsignment.Integration" />
    <Reference Include="Enterprise.Warehouse.Cartonisation.Integration" />
    <Reference Include="Enterprise.Warehouse.Environment.Business" />
    <Reference Include="Enterprise.Warehouse.Integration" />
    <Reference Include="Enterprise.Warehouse.Transactions.Business" />
    <Reference Include="Enterprise.Warehouse.Transactions.Invoicing" />
    <Reference Include="Enterprise.Warehouse.Transit.Business" />
    <Reference Include="Enterprise.Warehouse.Yard.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Core" />
    <Reference Include="Enterprise.ZArchitecture.Business" />
    <Reference Include="Enterprise.ZArchitecture.Business.Test" Condition="'$(Configuration)' == 'Debug'" />
    <Reference Include="Enterprise.ZArchitecture.Modules" />
    <Reference Include="Enterprise.ZArchitecture.Web.Business" />
    <Reference Include="Resources" />
    <Reference Include="System.Collections.Immutable" />
    <Reference Include="System.Memory" />
    <Reference Include="WTG.SecurityRights" />
    <Reference Include="WTG.StaticAnalysis.Annotation" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="AirWatermark.png" />
    <EmbeddedResource Include="EmptyTransparentImage.gif" />
    <EmbeddedResource Include="Freight\AWBBrandingMaster_600b.png" />
    <EmbeddedResource Include="Freight\AWBFrenchHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBFrenchMasterHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBFrenchMasterTitle.png" />
    <EmbeddedResource Include="Freight\AWBHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBMasterHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBMasterTitle.png" />
    <EmbeddedResource Include="Freight\AWBSpanishHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBSpanishMasterHouseTitle.png" />
    <EmbeddedResource Include="Freight\AWBSpanishMasterTitle.png" />
    <EmbeddedResource Include="Freight\Signature.png" />
    <EmbeddedResource Include="SeaWatermark.png" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-AFIF.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-BIFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-CBAFF.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-CIFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-CIFFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-FFI.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-FMFF.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-HAFFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-INFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-IOFFLAT.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-JAFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-KIFFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-MIFFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-SAAFF.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-SLA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-SSV.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-TIA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-TIFFA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATAlogo-VLA.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATATextLogo-FWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATATextLogo-HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATATextLogo-ICC.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\FIATA\FIATATextLogo-SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\DHK_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\DHK_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\EAG_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\EAG_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\FIA_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\FIA_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\IAU_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\IAU_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\INZ_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\INZ_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\TAN_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\TAN_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\Test_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\Test_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\TNZ_HBL.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\Standard Bill Terms\TNZ_SWB.gif" />
    <EmbeddedResource Include="Specialised Classes\Resources\Raw\TestImage.gif" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="GenericWrappers\ChildWrappers\Routing\TransportModeList.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>TransportModeList.xml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="GenericWrappers\ChildWrappers\Routing\TransportModeList.xml">
      <Generator>CodeDescriptionPairListGenerator</Generator>
      <LastGenOutput>TransportModeList.cs</LastGenOutput>
      <CustomToolNamespace>Enterprise.DocumentWrappers.GenericWrappers</CustomToolNamespace>
    </None>
  </ItemGroup>
  <Import Project="$(WTGBinRoot)CargoWiseOne.ResourceStrings.Transform.targets" />
</Project>