<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.MasterData.Module.Test</AssemblyName>
    <RootNamespace>Enterprise.MasterData.Module.Test</RootNamespace>
    <EnableWinzorTests>true</EnableWinzorTests>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MasterData.Common\MasterData.Common.csproj" />
    <ProjectReference Include="..\MasterData.Module\MasterData.Module.Winzor.csproj" />
  </ItemGroup>
</Project>