<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Enterprise.Recruiter.Module</AssemblyName>
    <RootNamespace>Enterprise.Recruiter.Module</RootNamespace>
    <UseLegacyRsa>false</UseLegacyRsa>
    <NoWarn>$(NoWarn);CA1416;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Recruiter.GUI\Enterprise.Recruiter.GUI.Winzor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="WinzorFramework" />
  </ItemGroup>
</Project>