<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.arcticgroup.se/tariff/arctictariff/export" elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:at="http://www.arcticgroup.se/tariff/arctictariff/export">
<!--
    Representation of TARIC record 28500, 29000, 30000
 -->            
   <xsd:element name="baseRegulation">
        <xsd:complexType>
            <!-- Base regulation role -->
            <xsd:attribute ref="at:regulationRoleType"/>
            <!-- Base regulation id -->
            <xsd:attribute ref="at:regulationId"/>
            <!-- Base regulation publication date -->
            <xsd:attribute ref="at:datePublished"/>
            <!-- Official journal number -->
            <xsd:attribute ref="at:officialJournalId"/>
            <!-- Official journal page -->
            <xsd:attribute ref="at:journalPage"/>
            <!-- Validity start date of base regulation -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of base regulation -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Base regulation effective end date -->
            <xsd:attribute ref="at:effectiveEndDate"/>
            <!-- Community code -->
            <xsd:attribute ref="at:communityCode"/>
            <!-- Regulation group id -->
            <xsd:attribute ref="at:regulationGroup"/>
            <!-- Anti-dumping regulation role -->
            <xsd:attribute ref="at:antidumpingRegulationRoleType"/>
            <!-- Related anti-dumping regulation id -->
            <xsd:attribute ref="at:antidumpingRegulationId"/>
            <!-- Replacement indicator -->
            <xsd:attribute ref="at:replacementIndicator"/>
            <!-- Stopped flag -->
            <xsd:attribute ref="at:stoppedFlag"/>
            <!-- Information text -->
            <xsd:attribute ref="at:description"/>
            <!-- Approved flag -->
            <xsd:attribute ref="at:regulationApprovedFlag"/>
            <!-- URL with more information about the regulation.
                 Represent the national column X_URL -->
            <xsd:attribute ref="at:url"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="modificationRegulation">
        <xsd:complexType>
            <!-- Modification regulation role -->
            <xsd:attribute ref="at:modificationRegulationRoleType"/>
            <!-- Modification regulation id -->
            <xsd:attribute ref="at:modificationRegulationId"/>
            <!-- Modification regulation publication date -->
            <xsd:attribute ref="at:datePublished"/>
            <!-- Official journal number -->
            <xsd:attribute ref="at:officialJournalId"/>
            <!-- Official journal page -->
            <xsd:attribute ref="at:journalPage"/>
            <!-- Validity start date of modification regulation -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of modification regulation -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Modification regulation effective end date  -->
            <xsd:attribute ref="at:effectiveEndDate"/>
            <!-- Base regulation role -->
            <xsd:attribute ref="at:baseRegulationRoleType"/>
            <!-- Base regulation id -->
            <xsd:attribute ref="at:baseRegulationId"/>
            <!-- Replacement indicator -->
            <xsd:attribute ref="at:replacementIndicator"/>
            <!-- Stopped flag -->
            <xsd:attribute ref="at:stoppedFlag"/>
            <!-- Information text -->
            <xsd:attribute ref="at:description"/>
            <!-- Approved flag -->
            <xsd:attribute ref="at:regulationApprovedFlag"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="fullTemporaryStopRegulation">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="at:fullTemporaryStopRegulationAction" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
            <!-- Full temporary stop regulation role -->
            <xsd:attribute ref="at:ftsRegulationRoleType"/>
            <!-- Full temporary stop regulation id -->
            <xsd:attribute ref="at:ftsRegulationId"/>
            <!-- Full temporary stop regulation publication date -->
            <xsd:attribute ref="at:datePublished"/>
            <!-- Official journal number -->
            <xsd:attribute ref="at:officialJournalId"/>
            <!-- Official journal page -->
            <xsd:attribute ref="at:journalPage"/>
            <!-- Validity start date of full temporary stop regulation -->
            <xsd:attribute ref="at:dateStart"/>
            <!-- Validity end date of full temporary stop regulation -->
            <xsd:attribute ref="at:dateEnd"/>
            <!-- Effective end date of full temporary stop regulation -->
            <xsd:attribute ref="at:effectiveEndDate"/>
            <!-- Replacement indicator -->
            <xsd:attribute ref="at:replacementIndicator"/>
            <!-- Information text -->
            <xsd:attribute ref="at:description"/>
            <!-- Approved flag -->
            <xsd:attribute ref="at:regulationApprovedFlag"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
            <!-- Represent the type of update that has been performed for this element -->
            <xsd:attribute ref="at:changeType"/>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="fullTemporaryStopRegulationAction">
        <xsd:complexType>
            <!-- Role of stopped regulation -->
            <xsd:attribute ref="at:stoppedRegulationRoleType"/>
            <!-- Stopped regulation id -->
            <xsd:attribute ref="at:stoppedRegulationId"/>
            <!-- Represent the national column X_NATIONAL -->
            <xsd:attribute ref="at:national"/>
        </xsd:complexType>
    </xsd:element>
    
</xsd:schema>
