<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputPath>..\..\..\..\..\..\..\Bin\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="CargoWise.BrandManager">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.BrandManager.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Schema">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Common">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Common.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ComponentModel">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.ComponentModel.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Accounting.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Accounting.Integration.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.ApplicationContext">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.ApplicationContext.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Billing.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Billing.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ComplianceRisk.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.ComplianceRisk.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Business.Test">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Common">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.EU.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.EU.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Universal">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.Universal.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Customs.Universal.Test">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Customs.Universal.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngine">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.DocumentEngine.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineCore">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.DocumentEngineCore.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.DocumentEngineIntegration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.DocumentEngineIntegration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Environment">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Environment.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Freight.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.CarbonEmissions.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Freight.CarbonEmissions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Common.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Freight.Common.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Forwarding.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Freight.Forwarding.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Freight.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Freight.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterData.Common">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.MasterData.Common.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.MasterFiles.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.MasterFiles.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.MasterFiles.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Messaging.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Messaging.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Messaging.Business.Test">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Messaging.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Messaging.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Messaging.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Registry.Business">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Registry.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Scheduler.Business">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.Scheduler.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ServiceManager.Business">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ServiceManager.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ServiceManager.Shared">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.ServiceManager.Shared.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW.Test">
      <HintPath>..\..\..\..\..\..\..\bin\ServiceManager.Integration.ServiceTasks.CW.Test.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Services.OperationalActions.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Services.OperationalActions.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.TransportBookings.Shared">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.TransportBookings.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.Warehouse.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.Warehouse.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Business.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Business.Test">
      <HintPath>..\..\..\..\..\..\..\bin\Enterprise.ZArchitecture.Business.Test.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework">
      <HintPath>..\..\..\..\..\..\..\bin\CargoWise.EntityFramework.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.EntityFramework.Testing">
      <HintPath>..\..\..\..\..\..\..\bin\CargoWise.EntityFramework.Testing.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Core">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Core.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Data">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Data.dll</HintPath>
    </Reference>
    <Reference Include="Enterprise.ZArchitecture.Modules">
      <HintPath>..\..\..\..\..\..\..\Bin\Enterprise.ZArchitecture.Modules.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Odyssey.Schema">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Odyssey.Schema.dll</HintPath>
    </Reference>
    <Reference Include="CargoWise.Types">
      <HintPath>..\..\..\..\..\..\..\Bin\CargoWise.Types.dll</HintPath>
    </Reference>
    <Reference Include="MailManager">
      <HintPath>..\..\..\..\..\..\..\bin\MailManager.dll</HintPath>
    </Reference>
    <Reference Include="MailManager.Test">
      <HintPath>..\..\..\..\..\..\..\bin\MailManager.Test.dll</HintPath>
    </Reference>
    <Reference Include="MailManager.Integration">
      <HintPath>..\..\..\..\..\..\..\Bin\MailManager.Integration.dll</HintPath>
    </Reference>
    <Reference Include="Moq">
      <HintPath>..\..\..\..\..\..\..\Bin\Moq.dll</HintPath>
    </Reference>
    <Reference Include="NUnitCore">
      <HintPath>..\..\..\..\..\..\..\Bin\NUnitCore.dll</HintPath>
    </Reference>
    <Reference Include="Resources">
      <HintPath>..\..\..\..\..\..\..\Bin\Resources.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Shared.Abstractions">
      <HintPath>..\..\..\..\..\..\..\Bin\ServiceManager.Shared.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="System.Web.Services" />
    <Reference Include="ServiceManager.Integration.Abstractions">
      <HintPath>..\..\..\..\..\..\..\Bin\ServiceManager.Integration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="ServiceManager.Integration.ServiceTasks.CW">
      <HintPath>..\..\..\..\..\..\..\Bin\ServiceManager.Integration.ServiceTasks.CW.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MCP\Enterprise.Customs.GB.MCP.csproj" />
    <ProjectReference Include="..\Chief.Test\Enterprise.Customs.GB.Chief.Test.csproj" />
    <ProjectReference Include="..\Registry\Enterprise.Customs.GB.Registry.csproj" />
  </ItemGroup>
</Project>